### ISSUE TITLE
DefaultCredentialsProvider eagerly blows up on invalid .aws/credentials

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#1014]
A colleague was having inexplicable crashes on startup when we added SDK v2 to our application. After substantial troubleshooting, we determined that it was because trying out the CLI utilities some months ago had created a file named `~/.aws/credentials`:

```
[default]
aws_access_key_id=
aws_secret_access_key=
```

These values are invalid, to be sure, but the problem is that they're loaded and validated (and thus will throw an exception from `ProfileCredentialsUtil#credentialsProvider`) _when the class `DefaultCredentialsProvider` is loaded_. Thus, even though our application configures a `StaticCredentialsProvider` with everything that the SDK needs, the SDK still throws on startup.

I can see two sensible behaviors, either that the `ProfileCredentialsProvider` loads credentials lazily or that `DefaultCredentialsProvider`'s default chain is initialized lazily, but unrequested credentials shouldn't be inspected for correctness and block application startup. (It also should provide a substantially better error message, such as "invalid credentials in file `foo`", but I'm not sure how to phrase an issue for that.)

**Comment by varunnvs92** [comment]
This should be fixed in https://github.com/aws/aws-sdk-java-v2/commit/c6fd8242d70f5321a1e3e0fa4539659e2384f252. Please try the latest version of the SDK and reopen if the issue still exists.
