### ISSUE TITLE
Documentation on how to set proxy for Apache HTTP client is lacking 

### ISSUE THREAD

**Issue by favetelinguis** [aws/aws-sdk-java-v2#1020]
Im stuck on how to set a proxy on the Apache HTTP client. The documentation is contradicting and incomplete and I would very much appreciate some more clarification on how to do this.
[See this SO question for more details](https://stackoverflow.com/questions/54235387/how-to-set-proxy-on-aws-java-sdk-v2-apache-client)

**Comment by varunnvs92** [comment]
You should be able to set the proxy config using the [builder](https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/ApacheHttpClient.java#L398-L401) on ApacheHttpClient class. Did you try that?

**Comment by favetelinguis** [comment]
Yes i got it working that way
