### ISSUE TITLE
KinesisAsyncClient doesn't work with CBOR disabled (since 2.3.0 I guess)

### ISSUE THREAD

**Issue by aesteve** [aws/aws-sdk-java-v2#1021]
## Expected Behavior
`KinesisAsyncClient` should not fail even if CBOR has been disabled.

## Current Behavior
When CBOR is disabled. `KinesisAsyncClient.describeStream` fails parsing the date.

## Possible Solution
Maybe an issue with jackson ? I don't really know. Sorry.

## Steps to Reproduce (for bugs)
Just set :
```
System.setProperty(SdkSystemSettings.CBOR_ENABLED.property(), "false")
```
before any Kinesis integration test

## Context
I'm trying to upgrade from 2.2.0 to 2.3.2. I've been testing my project against [localstack](https://github.com/localstack/localstack) which doesn't send back CBOR-encoded data. Hence I'm disabling CBOR for testing against localstack.

## Your Environment
* AWS Java SDK version used: 
2.3.2
* JDK version used:
11 or 8, same issue.
* Operating System and version: 
Mac OS (irrelevant I guess).

## Notes

I've tried forking the repository and adding an integration test. But it requires testing with a real IAM account :(

**Comment by aesteve** [comment]
For a more detailed output of the parsing exception, see #1023 that's exactly the same message (exponential notation not parsed correctly).

**Comment by aesteve** [comment]
From @oripwk in #1023 :

```
The root cause is that TimestampFormatTrait.Format evaluates to UNIX_TIMESTAMP_MILLIS instead of UNIX_TIMESTAMP. If it would have been the latter, the parseUnixTimestampInstant() method would be used instead of parseUnixTimestampMillisInstant() and it would have worked.
```

**Comment by zoewangg** [comment]
Closing in favor of #1023
