### ISSUE TITLE
AWS SDK JAVA 2.0 S3 Directory Download

### ISSUE THREAD

**Issue by studioam** [aws/aws-sdk-java-v2#1028]
In AWS SDK JAVA 2.0 S3 there are methods and examples to get object.

How to download a whole directory given bucket name, directory name (= key) and path using download acceleration and multipart download?

I know how to do it with 1.11 using transfermanager etc.... Which are the same tools in the 2.0?

**Comment by debora-ito** [comment]
Hi @studioam, since this is a question regarding V2 we transferred it to the V2 repo.

**Comment by spfink** [comment]
We have a tracking issue for this: https://github.com/aws/aws-sdk-java-v2/issues/37

We don't yet have TransferManager in v2 but will be bringing it back. If you have any additional suggestions for it's implementation in v2, feel free to add them there.

**Comment by ahsentaqi** [comment]
Hi @spfink , i need to download directory with SSE-C 
Is there any provision for this in V2?
In v1 we had option to download file with SSE-C using TransferManager but not Directory.
Can we have this functionality in v2?

**Comment by aman-agrawala** [comment]
Piggybacking off @ahsentaqi I'm also trying to download an entire directory using the jdk v2. Is there no way to do this? The documentation specifies only how to download objects but not an entire folder: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3-objects.html#download-object
