### ISSUE TITLE
Allow disabling CBOR at a per-request level

### ISSUE THREAD

**Issue by zoewangg** [aws/aws-sdk-java-v2#1031]
## Expected Behavior
SDK should support toggle `CBOR` setting after SDK client creation. 

## Current Behavior
Currently, `CBOR` setting will only take effect if it is set before client creation.
```
System.setProperty(CBOR_ENABLED.property(), "false");
KinesisClient  client = KinesisClient.builder().build();
client.getRecords(b -> b.shardIterator("test")).records();
```

## Steps to Reproduce (for bugs)
```
KinesisClient  client = KinesisClient.builder().build();
System.setProperty(CBOR_ENABLED.property(), "false");
client.getRecords(b -> b.shardIterator("test")).records();
```

## Context
#1027 

## Your Environment

* AWS Java SDK version used: `2.3.6-SNAPSHOT`
* JDK version used:
* Operating System and version:

**Comment by millems** [comment]
This is true of a lot of our system properties. Not sure if we'd generally want to do this for all system properties. Converting this to "allow disabling CBOR at a per-request level". What's the use-case for this feature?

**Comment by millems** [comment]
Based on the demand of this feature, the priority seems low. What's the use-case for this feature?
