### ISSUE TITLE
Using HTTPS proxy with ApacheHttpClient

### ISSUE THREAD

**Issue by pavelperner** [aws/aws-sdk-java-v2#1032]
I am trying to use the S3 client with ApacheHttpClient. That is the only client that supports proxy setting (via ProxyConfiguration). However, setting the proxy does not make S3 client to use it anyway.

I have found an interesting piece of code in ApacheUtils::addPreemptiveAuthenticationProxy. There is a condition which tells that if the provided instance of ProxyConfiguration has preemptive basic authentication enabled, then and only then the proxy is set up. But I've disabled any authentication on proxy (our company does not use authentication on our proxies).

Without proxy, I'm not able to communicate with our S3 bucket (java.net.UnknownHostException).

I should also say that I cannot set the proxy via System::setProperty.

## Expected Behavior
I should be able to set proxy without authentication.

## Current Behavior
ProxyConfiguration with preemptive basic authentication disabled is ignored.

## Context
I am trying to use the AWS SDK to upload files to our S3 bucket.

## Your Environment
* AWS Java SDK version used: 2.3.6
* JDK version used: 1.8.0_191

**Comment by zoewangg** [comment]
Closing due to lack of response, please re-open if you're still experiencing this issue.
