### ISSUE TITLE
S3 ETag should not be validated if using KMS SSE

### ISSUE THREAD

**Issue by kgncan** [aws/aws-sdk-java-v2#1035]
## Expected Behavior
[Version 1](https://github.com/aws/aws-sdk-java/blob/5fb7554098a60228347ab823ddde06567f1ef85c/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/internal/SkipMd5CheckStrategy.java#L245) of the AWS SDK skipped the ETag validation check if KMS server side encryption is used. This is causing issues using LocalStack which is returning the ETag regardless. 

According to the [API](https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html)

    In the response, Amazon S3 returns the encryption algorithm and MD5 of the encryption key that you specified when uploading the object. 
    The ETag that is returned is not the MD5 of the object.

## Current Behavior
`ChecksumsEnabledValidator` executes the Checksum check if a ETag is returned, causing a NPE ([as the request context doesn't include the checksum](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L104)).

  
    Caused by: java.lang.NullPointerException: null
    	at software.amazon.awssdk.services.s3.checksums.ChecksumsEnabledValidator.validatePutObjectChecksum(ChecksumsEnabledValidator.java:129)
    	at software.amazon.awssdk.services.s3.internal.handlers.AsyncChecksumValidationInterceptor.afterUnmarshalling(AsyncChecksumValidationInterceptor.java:86)

## Possible Solution
~~Check if the validation should be executed on the response in [ChecksumsEnabledValidator#validatePutObjectChecksum](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/checksums/ChecksumsEnabledValidator.java#L128), similar to V1 or include a null check for `checksum`.~~

## Context
Bug raised with https://github.com/localstack/localstack/issues/1092 too.

## Your Environment
* AWS Java SDK version used: 2.3.6
* JDK version used: 1.8
* Operating System and version: Mac OS 10.13.6

**Comment by kgncan** [comment]
I believe the bug is in [AsyncChecksumValidationInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/a0379920f54cba715773f821ac5d237be8a47985/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/AsyncChecksumValidationInterceptor.java#L82).
The 4th parameter should be the request headers: `context.httpRequest()`

**Comment by zoewangg** [comment]
I did a quick test and `x-amz-server-side-encryption: aws:kms` was present in the response header. We also have integration tests to test PutObject using kms and both of them passed.

https://github.com/aws/aws-sdk-java-v2/blob/114510dcf3588706113472b7c82f4c6c5a5eedc6/services/s3/src/it/java/software/amazon/awssdk/services/s3/SyncServerSideEncryptionIntegrationTest.java#L79
https://github.com/aws/aws-sdk-java-v2/blob/114510dcf3588706113472b7c82f4c6c5a5eedc6/services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncServerSideEncryptionIntegrationTest.java#L78

Though we might still want to use `requestHeader` to be consistent with `AsyncChecksumValidationInterceptor#modifyAsyncHttpContent`

**Comment by kgncan** [comment]
@zoewangg, to clarify, as the checksum is added to the context based on the request headers, it seems appropriate to _also_ use the request headers to determine if the response checksum should be validated.

**Comment by zoewangg** [comment]
@kgncan  Yeah, I agree that we should make that change. Thank you for your PR, I left a few minor comments on it.
