### ISSUE TITLE
software.amazon.awssdk.http Does not exist in Maven Repository

### ISSUE THREAD

**Issue by kidomine** [aws/aws-sdk-java-v2#1037]
## Expected Behavior
1. The following import should resolve the symbol for `ApacheHttpClient `:
```java
import software.amazon.awssdk.http.apache.ApacheHttpClient;
```

2. Either of the following POM dependency configurations should result to the relevant JAR file being downloaded: 
```xml
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>2.3.9</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
::
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>http</artifactId>
    </dependency>
```

or
```xml
<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>bom</artifactId>
        <version>2.3.9</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
::
    <dependency>
      <groupId>software.amazon.awssdk.http</groupId>
      <artifactId>apache</artifactId>
    </dependency>
```

3. Package information should exist in the Maven repository. 

## Current Behavior
During compile:
```text
Error:(27, 42) java: package software.amazon.awssdk.http.apache does not exist
```

As I understand it, the official AWS Java SDK 2.x.x is published to Maven repository under the group name `software.amazon.awssdk`. However, the following search in Maven repository turns up with nothing:
https://mvnrepository.com/search?q=software.amazon.awssdk.http

In any case, the task that I was originally trying to address has already been resolved as I have found a simpler way to do it. However, I would like to leave this issue here just in case this is indeed a bug and/or someone has an explanation as to what is happening.

## Your Environment
* AWS Java SDK version used: 2.3.9
* JDK version used: 1.8.0_45
* Operating System and version: macOS 10.14.2 (Mojave)

**Comment by zoewangg** [comment]
The artifactId for apache-client module is actually `apache-client`

https://github.com/aws/aws-sdk-java-v2/blob/89826f128269dc549d60facb890f9b077c151f6e/http-clients/apache-client/pom.xml#L27

So you would need 
```
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>apache-client</artifactId>
    </dependency>
```

**Comment by kidomine** [comment]
Oh I see. I did find something similar in the preview version (I think it was `apache-client-preview`).
In any case, I am under the impression that the Maven repository should follow the same package hierarchy as the one described in the API specs (see https://sdk.amazonaws.com/java/api/2.0.0-preview-11/software/amazon/awssdk/http/apache/ApacheHttpClient.html).
i.e. the class is defined in `software.amazon.awssdk.http.apache`, thus the expected artifact is either `http` or `apache`.

I assume that this case is not unique, and that there are other instances similar to this. Is there some kind of mapping between the API specs and the actual artifact in the Maven repository?
I mean, how would I know that I should use `apache-client` and not `http` or `apache` as artifactId?

Thanks!

**Comment by brainstorm** [comment]
+1, I just hit this one right now, I agree with @kidomine, would be excellent to have that Maven mapping.

+1 on the v2 comment too, cleaner API 👍

**Comment by Kailash2509** [comment]
I am facing same problem with all these classes ( and may be much more)

import com.amazonaws.AmazonServiceException;
import com.amazonaws.SdkClientException;
import com.amazonaws.auth.profile.ProfileCredentialsProvider;
import com.amazonaws.services.s3.AmazonS3;
import com.amazonaws.services.s3.AmazonS3ClientBuilder;

The error is these classes are not resolved but I have added the dependency in pom.xml file and I can see jar being downloaded to M2_REPO under some path ...\repository\software\amazon\awssdk... 
but the aws version one jars were downloaded at different path under M2_REPO, I am not sure if this is the reason for the error?

**Comment by Kailash2509** [comment]
Ah.. the solution was there in my question itself, since the package structure is chanted I should have used the import statement like "import **software.amazon.awssdk**.services.s3.*" 
It has solved the problem, but I could see lot of classes have been removed as compared to previous 1.0 package.
Mainly the error came because the example I was running from aws documentation was from 1.0 version but I imported the latest package for running.

**Comment by kidomine** [comment]
@Kailash2509 sorry, I was busy the past several weeks, and I did not notice your question. Glad to know you got around it though. :)

**Comment by abdsamad1** [comment]
@kidomine what is the simple way you found to solve this issue? I am facing the same issue.

**Comment by kidomine** [comment]
@abdsamad1 the first reply from @zoewangg is correct and resolved my problem. I did not close this issue due to the fact that my second concern, i.e. "how to avoid this issue", is not yet addressed.

**Comment by zoewangg** [comment]
Hi @kidomine @abdsamad1 

Do you think updating README to include the code snippets of the http client imports would help discoverability? (Unfortunately, we can't change the artifactIds without breaking customers at this point)

In fact, `apache-client` and `netty-nio-client` dependencies are provided by default and you don't need to explicitly add them in your pom.

**Comment by kidomine** [comment]
@zoewangg So sorry, I've been very busy these past few months.
Yes, I think updating the README would help a lot in this case.

**Comment by yifanHuang129** [comment]
@zoewangg Hi, I just met a similar problem, I tried to write an application that connecting to AWS serves and then downloading and uploading objects. However, when I used javac to compile the code, it showed me a message like this "error: package software.amazon.awssdk.regions does not exist", and my pom file looks like this
    <dependencies>
 34         <dependency>
 35             <groupId>software.amazon.awssdk</groupId>
 36             <artifactId>s3</artifactId>
 37             <exclusions>
 38                 <exclusion>
 39                     <groupId>software.amazon.awssdk</groupId>
 40                     <artifactId>netty-nio-client</artifactId>
 41                 </exclusion>
 42                 <exclusion>
 43                     <groupId>software.amazon.awssdk</groupId>
 44                     <artifactId>apache-client</artifactId>
 45                 </exclusion>
 46             </exclusions>
 47         </dependency>

As you mentioned above, it does have an "apache-client" instead "apache", however, it still showed me the error.

**Comment by telangsachin** [comment]
@zoewangg Thanks a lot.

**Comment by AnweshaSen** [comment]
hey @Kailash2509 can you please elaborate your solution a bit more ? am facing similar issue

**Comment by millems** [comment]
I'm not sure what value this issue is still holding. software.amazon.awssdk.http is not a group ID. The proper group ID is software.amazon.awssdk, and the proper artifact ID for the Apache HTTP client is apache-client: https://mvnrepository.com/artifact/software.amazon.awssdk/apache-client
