### ISSUE TITLE
Invalid exception message in DynamoDbMapperConfig

### ISSUE THREAD

**Issue by siudeks** [aws/aws-sdk-java-v2#104]
When I do DynamoDbMapper::save with POJO object
I’m expecting an exception with description `(...) not annotated with @DynamoDbTable` to happen
But instead, I’m seeing an exception with description `(...) not annotated with @DynamoDBTable`

**Comment by kiiadi** [comment]
@siudeks DynamoDbMapper isn't fully supported in v2 yet. We'll likely move it to the side for now and re-implement it when the core runtime is solidified. See #101
