### ISSUE TITLE
S3 Control Client

### ISSUE THREAD

**Issue by pameghna** [aws/aws-sdk-java-v2#1050]
## Expected Behavior
<It is present for Java-v1 but not for v2.>
Here is the doc for v1 : https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3control/model/GetPublicAccessBlockRequest.html

## Possible Solution
< Need it for JAVA SDK-2 as well
## Your Environment

* AWS Java SDK version used: 2
* JDK version used:
* Operating System and version:

**Comment by spfink** [comment]
Support for S3 Control has been merged and will be released tomorrow.
