### ISSUE TITLE
Incorrect deleting item from DynamoDB

### ISSUE THREAD

**Issue by ratoshniuk** [aws/aws-sdk-java-v2#1051]
Hi there!

I am currently upgrading AWS SDK to v2 and try to force dynamo DB API work correctly. 
It seems that `DeleteItemRequest` performs wrong. 

## Expected Behavior
when I perform client.deleteItem(???) I response success. 
When I read again, I am waiting for nothing by requested key

## Current Behavior
When I read again, I get a response with empty attributes map by requested key.
But when i do ```scan``` , i retrieve list of items without recently deleted 

## Possible Solution

https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/DeleteItem.java

Please, add into your examples reading after deleting to ensure that it works well

* AWS Version is 2.3.9
* Java 11
* Language: Scala
* docker image for local dynamo: amazon/dynamodb-local:latest

**Comment by debora-ito** [comment]
Closing due to no response, please feel free to re-open if you're still experiencing this issue.
