### ISSUE TITLE
Consider adding common prefix to maven artifact names

### ISSUE THREAD

**Issue by brharrington** [aws/aws-sdk-java-v2#106]
The developer preview currently uses simple subproject names for the maven artifacts like `core`, `ec2`, `config`, etc. My concern is that when just examining the set of jars that are part of a deployment it becomes harder to reason about. Examples:

1. In the past we have frequently had problems due to mismatched versions of various aws sdk jars. It is convenient to be able to just look at the jars at the classpath and sanity check that all of the jars from the aws java sdk are consistent. The common prefix of `aws-java-sdk` for the 1.x version makes this really easy. Usually the problem is something like:
    * depA -> ec2-1.11 -> core-1.11
    * depB -> config-1.10 -> core-1.10
    * app gets: ec2-1.11, core-1.11, config-1.10 (breaks because it doesn't work with newer core)
2. Some of the names are pretty common and overlap with other commonly used projects. For example config project jar would have the same name other than maybe version as [typesafe config](https://github.com/typesafehub/config). If nothing else this creates confusion when looking at the jars in the classpath and if the versions ever happened to be the same they may overwrite each other if the tools do not handle it properly.

**Comment by dagnir** [comment]
Yes, looks like they're still be being prefixed: http://repo1.maven.org/maven2/software/amazon/awssdk/config/2.0.0-preview-4/

Going to go ahead and reopen this.

**Comment by kiiadi** [comment]
Looking into this a bit more this may not actually be possible without changing the artifact name. From the reading I've done I've not figured out a way to configure the jar name separately from the artifactId.

**Comment by spfink** [comment]
@brharrington, after looking into this further, it does not appear that this is something that we can do. While we added the finalName property to our POM, this only effects the generated JARs when building locally. The name of the JAR files in Maven must be the artifactId. 

Since we've released 2.0 versions of a few of our modules, we can't now add in the aws-sdk-java prefix.

**Comment by zoewangg** [comment]
Closing as it would be backwards incompatible changes by now
