### ISSUE TITLE
Use consistent casing between client and high level libraries

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#107]
For example: `DynamoDBClient` vs `DynamoDbMapper`

**Comment by kntyskw** [comment]
+1. This will help migrating existing code base to 2.0. Currently it is necessary to change casing for all occurrences of DynamoDB Mapper related classes.

**Comment by dagnir** [comment]
Hey @kntyskw To be clear, the plan is to move to `DynamoDb*` style; that is, no consecutive capital letters.

**Comment by brharrington** [comment]
It would be nice if the consistency applied to all clients so it is easier to guess the correct name. For example, `STSClient` is still used instead of `StsClient`.

**Comment by zoewangg** [comment]
Fixed via https://github.com/aws/aws-sdk-java-v2/pull/545 and https://github.com/aws/aws-sdk-java-v2/pull/609
