### ISSUE TITLE
Support for S3 Bucket Exists API in SDK 2.3.2

### ISSUE THREAD

**Issue by sammad** [aws/aws-sdk-java-v2#1081]
I am using AWS SDK 2.3.2. I fail to find the api which tells me if S3 bucket exists. There is absolutely no way to upgrade to latest version of SDK
## Expected Behavior
BucketUtils should have an API which provides boolean value if Bucket with the name specified exists
## Context
Right now I am trying to get LocationConstraint for a bucket and if I get a response that means Bucket exists else not.
## Your Environment

* AWS Java SDK version used: 2.3.2
* JDK version used: 1.8
* Operating System and version: Windows 2010

**Comment by spfink** [comment]
Is GetBucketLocation not sufficient?

**Comment by millems** [comment]
Closing due to no response. Please reopen if `GetBucketLocation` is not sufficient.

**Comment by sammad** [comment]
I moved to SDK 1.x version as I wanted resilience support which was missing in SDK 2.x.

**Comment by SushmitaGoswami** [comment]
is there any update on this? How to check for whether a bucket exists using sdk 2.x?

**Comment by cartwrightian** [comment]
Reading the java api docs unclear how to infer bucket is missing form the GetBucketLocationResponse object returned from GetBucketLocation , especially as the enum BucketLocationConstraint does not seem to include a value for this case. The exceptions documented against the method do not mention behaviour when the requested bucket is missing.
