### ISSUE TITLE
dynamodb provisioned throughput autoscale provisioning capability

### ISSUE THREAD

**Issue by polavishnu4444** [aws/aws-sdk-java-v2#109]
I did not see anywhere for a way to create dynamodb table with read write units configurable to be autoscale ones.

This will be helpful if it can be provided during dynamo table creation through sdk. A way for the read and write units to be autoscale with min and max values for a table.

**Comment by kiiadi** [comment]
This isn't something that's actually exposed via the DynamoDB [API](http://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html) but rather something that's managed via Application AutoScaling [API](http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/Welcome.html). You can use Application AutoScaling to create a scaling policy that targets your Dynamo table : [PutScalingPolicy](http://docs.aws.amazon.com/ApplicationAutoScaling/latest/APIReference/API_PutScalingPolicy.html) 

See here for an example : http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/AutoScaling.HowTo.SDK.html
