### ISSUE TITLE
Regression: S3 User Meta Data uses case sensitive comparision

### ISSUE THREAD

**Issue by rezss** [aws/aws-sdk-java-v2#1091]
Hi,
https://github.com/aws/aws-sdk-java-v2/blob/985ec92c0dfac868b33791fe4623296c68e2feab/core/protocols/aws-xml-protocol/src/main/java/software/amazon/awssdk/protocols/xml/internal/unmarshall/HeaderUnmarshaller.java#L42

is a regression of a bug mentioned here: https://github.com/aws/aws-sdk-java/issues/704

## Your Environment

* AWS Java SDK version used: 2.4.14

**Comment by zoewangg** [comment]
Thank you for reporting! Created PR #1105 to fix it
