### ISSUE TITLE
Better Documentation for using S3 Async Client with KMS encrypted buckets

### ISSUE THREAD

**Issue by kibbled** [aws/aws-sdk-java-v2#1111]
This isn't a bug request but a simple ask that there be additional documentation and code samples for when using S3 with KMS such as follows:

```Kotlin
        return S3AsyncClient.builder()
                // checksum validation must be disabled when using S3 Async with KMS encryption
                .serviceConfiguration { it.checksumValidationEnabled(false) }
                .build()
```

I could not locate any anything that documented the use of checksumValidationEnabled, we had to dig through the SDK code. If you do not disable checksum validation you will get the following exception, which also could perhaps provide hints about async/kms.

```
java.util.concurrent.ExecutionException: software.amazon.awssdk.core.exception.SdkClientException: Data read has a different checksum than expected.
```

**Comment by zoewangg** [comment]
Hmm, I think this is more likely related to #953 

We have integ test to test for the case where KMS is used. https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/it/java/software/amazon/awssdk/services/s3/AsyncServerSideEncryptionIntegrationTest.java#L78

Closing in favor of #953
