### ISSUE TITLE
SQS ReceiveMessageRequest.Builder .attributes() method takes the wrong type of attributes

### ISSUE THREAD

**Issue by paulschwarz** [aws/aws-sdk-java-v2#1117]
See https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/ReceiveMessageRequest.Builder.html#attributeNames-java.util.Collection-

I think the method argument here is wrong. It should take not take `Collection<QueueAttributeName> attributeNames`, but rather `Collection<MessageSystemAttributeName> attributeNames`.

Compare the enum members available on MessageSystemAttributeName and QueueAttributeName and you'll see that they've got it mixed up

## Current Behavior
Currently, the method accepts a collection of `QueueAttributeName`s which is wrong. This request pertains to messages, not queues. `ReceiveMessageRequest.Builder attributeNames(Collection<QueueAttributeName> attributeNames)`.

## Possible Solution
The method signature should be `ReceiveMessageRequest.Builder attributeNames(Collection<MessageSystemAttributeName> attributeNames)`.

## Context
Right now, fortunately `QueueAttributeName` supports an "ALL" member, so the workaround is to create the `ReceiveMessageRequest` but overfetching, specifying `QueueAttributeName.ALL`.

What I would like to do is `builder.attributeNames(MessageSystemAttributeName.APPROXIMATE_RECEIVE_COUNT)`, as per the docblock (and SQS API documentation).

## Your Environment
* AWS Java SDK version used: 2.5.0

**Comment by paulschwarz** [comment]
My PR is faulty. https://github.com/aws/aws-sdk-java-v2/pull/1119

However, it's pretty clear to see the cause of the bug https://github.com/aws/aws-sdk-java-v2/blob/master/services/sqs/src/main/resources/codegen-resources/service-2.json#L346

This line should read `"shape":"MessageSystemAttributeName",`.

**Comment by millems** [comment]
Thanks for your report! This model is owned by the SQS team. Let me run it up the flagpole for them and get back to you...

**Comment by vendamere** [comment]
Any progress underway on this issue?

**Comment by millems** [comment]
SQS has acknowledged the issue, but no other update or ETA is available right now.

**Comment by luqasn** [comment]
It is ridiculous that this issue is still open :(

**Comment by openwebsolns** [comment]
Any updates two months later, please?

**Comment by debora-ito** [comment]
No updates here, other than the SQS team is aware of the issue.
I'll go ahead and close this issue, please track updates here: https://github.com/aws/aws-sdk/issues/233.
