### ISSUE TITLE
Cognito support for authorization code grant flow

### ISSUE THREAD

**Issue by JakubJecminek** [aws/aws-sdk-java-v2#1126]
Hi,
I am trying to replicate functionality of cognito hosted ui sign in page(https://docs.aws.amazon.com/cognito/latest/developerguide/login-endpoint.html), but aws sdk does not provide any method that would take username,password and would return authorization code which could be used for obtaining access/id token. The initiateAuth and adminInitiateAuth only support implicit flow which returns directly access/id token. Is there plan to support this, or has anybody any workaround for this how to retrieve authorization code?

With best regards,
Jakub

**Comment by millems** [comment]
Unfortunately this is more of a service feature request, so we can't field it. Could you ask this on the AWS forums?
