### ISSUE TITLE
Expose Apache HttpRoutePlanner on ApacheHttpClient#builder

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sdk-java-v2#1135]
## Current Behavior
The current behavior does not allow for dynamically determining the proxy.

## Possible Solution
Add `httpRoutePlanner()` on `ApacheHttpClient.Builder` that takes a `org.apache.http.conn.routing.HttpRoutePlanner` and forwards it onto `org.apache.http.impl.client.HttpClientBuilder#setRoutePlanner`. 

This would override any settings on `software.amazon.awssdk.http.apache.ProxyConfiguration`

**Comment by abrooksv** [comment]
If no concern, I'll start the code changes

**Comment by abrooksv** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/1154

**Comment by zoewangg** [comment]
Implemented via #1154
