### ISSUE TITLE
Wrong param validation in SdkBytes

### ISSUE THREAD

**Issue by GuillermoBlasco** [aws/aws-sdk-java-v2#1145]
In line 80 of SdkBytes.java there is a param validation that does not correspond to the actual param to validate. [Link](https://github.com/aws/aws-sdk-java-v2/blob/985ec92c0dfac868b33791fe4623296c68e2feab/core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkBytes.java#L80)

Actual code:
``` 
    public static SdkBytes fromString(String string, Charset charset) {
        Validate.paramNotNull(string, "string");
        Validate.paramNotNull(string, "charset");
        return new SdkBytes(string.getBytes(charset));
    }
```
Expected code:
``` 
    public static SdkBytes fromString(String string, Charset charset) {
        Validate.paramNotNull(string, "string");
        Validate.paramNotNull(charset, "charset"); // here the fix
        return new SdkBytes(string.getBytes(charset));
    }
```

As of seen in version 2.5.10

**Comment by varunnvs92** [comment]
Thanks for finding a bug. Do you want to send a pull request? If not, I can make the change.

**Comment by GuillermoBlasco** [comment]
I'm on it.

**Comment by varunnvs92** [comment]
Thanks for the contribution. PR is merged.
