### ISSUE TITLE
CloudSearch using CloudSearchDomainClient fails with Search requests cannot accept content streams

### ISSUE THREAD

**Issue by lilianaziolek** [aws/aws-sdk-java-v2#1151]
I have created a new domain in CloudSearch and uploaded documents. It is open for unauthorised search (for simplicity sake) and works fine in a browser via search similar to:
https://XXX.eu-west-1.cloudsearch.amazonaws.com/2013-01-01/search?q=lorem

I have tried running this search through SDK 2.x by instantiating the client and submitting search request as follows:
`
CloudSearchDomainClient client = CloudSearchDomainClient.builder()
.region(Region.EU_WEST_1)
.credentialsProvider(awsCredentialsProvider)
.endpointOverride(URI.create("https://XXX.eu-west-1.cloudsearch.amazonaws.com"))
.build();
SearchRequest searchRequest = SearchRequest.builder().query("lorem").build();
SearchResponse searchResponse = client.search(searchRequest);
`
## Expected Behavior
The call should return search results similar to direct call in browser

## Current Behavior
The request fails with:
software.amazon.awssdk.services.cloudsearchdomain.model.SearchException: Search requests cannot accept content streams (Service: CloudSearchDomain, Status Code: 400, Request ID: null)

In debug logs I can see that the request is sent via POST not GET (as happens in the browser) - see somewhat redacted
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "POST /2013-01-01/search HTTP/1.1[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: XXX.eu-west-1.cloudsearch.amazonaws.com[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-invocation-id: ...[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=... Signature=...[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: application/x-amz-json-1.1[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: aws-sdk-java/2.5.10 Windows_10/10.0 Java_HotSpot_TM__64-Bit_Server_VM/25.131-b11 Java/1.8.0_131 scala/2.11.12[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Date: 20190319T234439Z[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 35[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
00:44:39.798 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "format=sdk&pretty=true&q=lorem"
00:44:40.078 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 400 Bad Request[\r][\n]"
00:44:40.078 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/json; charset=UTF-8[\r][\n]"
00:44:40.078 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 224[\r][\n]"
00:44:40.079 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: keep-alive[\r][\n]"
00:44:40.079 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"

## Possible Solution
It seems it might possibly be related to SwitchToPostInterceptor converting the request from GET? Also, it seems a bit odd that the contentType is set to application/x-amz-json-1.1 and not application/x-www-form-urlencoded as per the interceptor - not sure where this change applied.
Might be related to issue #923 ?

## Steps to Reproduce (for bugs)
See code above

## Context
If there is setup missing somewhere in my code rather than this being a bug, more information in documentation would be helpful.

## Your Environment
* AWS Java SDK version used: 2.5.10
* JDK version used: JDK8
* Operating System and version: Win10

**Comment by lilianaziolek** [comment]
Just as an extra comment - suggest call on the same instance of cloudSearchDomainClient works fine, returning a response, and I was also able to run upload docs through this version of SDK jars - so the problem is only on searches.

**Comment by varunnvs92** [comment]
* The issue was the incorrect content-type. Fixed in https://github.com/aws/aws-sdk-java-v2/pull/1156
* The Http verb POST is correct which is also used in v1 SDK

**Comment by lilianaziolek** [comment]
> * The issue was the incorrect content-type. Fixed in #1156
> * The Http verb POST is correct which is also used in v1 SDK

Thank you 👍 I'll watch #1156 for release date then :)
