### ISSUE TITLE
No longer able to stream audio to Lex client (no InputStream support on AsyncRequestBody))

### ISSUE THREAD

**Issue by ConcreteLlama** [aws/aws-sdk-java-v2#1177]
We are no longer able to stream audio to Lex in the v2 API (2.5.20). Will this feature be re-added in the future?

## Expected Behavior
Ability to stream audio with a postContent request on LexRuntimeAsyncClient

## Current Behavior
In v1, we could set an InputStream on a PostContentRequest. In v2, it looks like you need to send an AsyncRequestBody on the LexRuntimeAsyncClient's  postContent method. However, AsyncRequestBody does not have an InputStream option. RequestBody does have an InputStream option, but it looks like you need to specify the content length too, implying that you need all of the audio data in memory before posting it. Looking at it again I believe this could be implemented with a ContentStreamProvider implementation, but that doesn't appear to be supported on AysncRequestBody, only RequestBody.

This leads me to believe that it is no longer possible to stream data to Lex with the v2 API - is this correct? And if so, are there plans to reintroduce this feature? The Lex API documentation says that streaming audio is the best way to use the Lex API and we have built our Lex integration with this in mind.

**Comment by zoewangg** [comment]
V2 async uses NIO APIs and supports non-blocking streaming operations. With v2 async client, you need to provide a [Publisher](https://www.reactive-streams.org/reactive-streams-1.0.0-javadoc/org/reactivestreams/Publisher.html) instead of InputStream (blocking IO) via `AsyncRequestBody#fromPublisher`.

**Comment by debora-ito** [comment]
@ConcreteLlama Looks like @zoewangg answered your question. Closing this, feel free to reopen if you have further questions.
