### ISSUE TITLE
Include a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by dagnir** [aws/aws-sdk-java-v2#118]
Having a well written `CONTRIBUTING.md` file will be very helpful as a starting point for community members considering making a contribution (code/issue/feature request).

Examples:
- https://github.com/aws/aws-sdk-js/blob/66c72964eac2080449b25bcc1a5cd0c0584877af/CONTRIBUTING.md
- https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md

**Comment by spfink** [comment]
Mozilla has a well written guide on CONTRIBUTING.md files:

http://mozillascience.github.io/working-open-workshop/contributing/

Don't have to follow it to the T but should make sure we aren't missing anything obvious when we do ours.

**Comment by millems** [comment]
We should include detailed information that won't all fit into the CONTRIBUTING.md in our wiki: https://github.com/aws/aws-sdk-java-v2/wiki
