### ISSUE TITLE
java.lang.NoSuchFieldError in Android Studio

### ISSUE THREAD

**Issue by LittleHans8** [aws/aws-sdk-java-v2#1180]
## Expected Behavior
 No `java.lang.NoSuchFieldError` should be thrown.

## Current Behavior
```
 java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes3.dex)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:146)
```

## Possible Solution
see : [using-apache-httpclient-with-android-sdk-23-nosuchmethod](https://stackoverflow.com/a/32313284)

## Steps to Reproduce (for bugs)
I want to generate an S3Client and the operation is failed, this is my code:
```
Region region = Region.US_EAST_1;
AwsSessionCredentials awsCreds = AwsSessionCredentials.create(ACCESS_KEY, SECRET_ACCESS_KEY, "");
S3Client s3 = S3Client.builder()
 .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
 .region(region).build();
```
## Your Environment

* AWS Java SDK version used:  software.amazon.awssdk:s3:2.5.20
* JDK version used: 1.8.0_152-release-1248-b01 amd64
* Operating System and version: Windows 10 10.0
* Android Studio version: 3.3.2
* Android compileSdkVersion : 28

**Comment by zoewangg** [comment]
@LittleHans8 Are you using AWS Java SDK v2 on Andriod? I'm not sure if it would work though. 

We have a designated mobile SDK. https://docs.aws.amazon.com/sdk-for-android/index.html

**Comment by LittleHans8** [comment]
@zoewangg  Yes,I am using AWS Java SDK v2 on Andriod , sdk-for-android is work for me, but it can't custom endpoint.

**Comment by zoewangg** [comment]
Unfortunately, we won't be able to fix Apache http client for Android use case. Can you try with http url connection client?
```xml
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>url-connection-client</artifactId>
            <version>${awsjavasdk.version}</version>
        </dependency>
```
```java
S3Client.builder()
.httpClientBuilder(UrlConnectionHttpClient.builder())
.build()
```

**Comment by LittleHans8** [comment]
It works! Thanks, but need add `javax.xml.stream:stax-api`  and `com.bea.xml.stream:org.motechproject.com.bea.xml.stream` lib to 'build.gradle' file.

**Comment by Cornflower1991** [comment]
> It works! Thanks, but need add `javax.xml.stream:stax-api` and `com.bea.xml.stream:org.motechproject.com.bea.xml.stream` lib to 'build.gradle' file.

`javax.xml.stream:stax-api  and com.bea.xml.stream:org.motechproject.com.bea.xml.stream version
