### ISSUE TITLE
why s3 are all test scope

### ISSUE THREAD

**Issue by mynameiscode** [aws/aws-sdk-java-v2#1193]
I found that all java s3 sdk was in test scrop when i get amazon sdk from maven repository. Can help me?
link:
https://mvnrepository.com/artifact/software.amazon.awssdk/s3

**Comment by zoewangg** [comment]
I don't quite understand your question. Could you clarify it?

**Comment by zoewangg** [comment]
Okay, now I see. It's adding `test` scope in the generated maven dependency. That's odd. Investigating

```xml
<!-- https://mvnrepository.com/artifact/software.amazon.awssdk/s3 -->
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>s3</artifactId>
    <version>2.5.23</version>
    <scope>test</scope>
</dependency>

```

**Comment by spfink** [comment]
It appears that if we reference a service as a test dependency anywhere in our project, it will show up as the test scope on mvnrepository.com. I'm not sure that this is something that we can even fix but I'll see what I can do.

**Comment by zoewangg** [comment]
I don't there is a way we can update it. Closing the issue. Feel free to re-open if you have further questions.
