### ISSUE TITLE
Dummy merger throws IllegalStateException due to case insensitive merge.

### ISSUE THREAD

**Issue by aninhumer** [aws/aws-sdk-java-v2#1198]
## Current Behavior
While trying to subscribe to an SNS topic on a localstack instance, I get the following exception:
```
java.lang.IllegalStateException: Duplicate keys are impossible when collecting from a map
```

Investigating the code, this is a result of `CollectionUtils.throwIllegalStateException` which is documented as a dummy merge implementation that shouldn't ever be called:

```
/**
  * Dummy merger since there can't be a conflict when collecting from a map.
  */
```

## Expected Behavior
Either successful subscription, or some other exception which explains the incorrect usage.

## Possible Solution
It looks like the `DefaultSdkHttpFullResponse` constructor uses `CollectionUtils.deepUnmodifiableMap` to convert the `headers` in the builder to an unmodifiable *case insensitive* map. This can fail if there are keys in the headers which are equivalent when considered as case insensitive.

Using a debugger I have confirmed that this does in fact occur. Specifically, the `builder.headers` map has a `"Server"` key and also a `"server"` key. I haven't investigated the source of these yet.

## Steps to Reproduce (for bugs)
I haven't isolated full steps. I can do so if necessary, but I'm hoping the above information is sufficient to fix the issue.

## Context
Issue encountered while attempting to subscribe to an SNS topic on a localstack instance with a HTTP endpoint on a mockserver instance in a docker container, for the purposes of testing SNS message behaviour of an application.
I don't know if any of this is relevant, but it might help explain how this issue might occur in normal usage.

**Comment by varunnvs92** [comment]
Is this only happening when testing on a localstack instance? I could not repo doing a normal email subscription. It would be helpful if you can give full code/instructions to repo the issue.

**Comment by zoewangg** [comment]
Closing due to lack of response, please reopen if you're still experiencing this issue.

**Comment by pavlospt** [comment]
FYI this issue happened to us as well @ Blueground. We forked the repo and removed the duplication of the `server` key added in response headers. https://github.com/bluegroundltd/moto/commit/f6427fe5b5302d284754c61c3d5422bae0f959ad

Not sure if it is the most optimal solution, but it worked for us & we are do not have extensive usage of Motoserver, in order to verify if it affects something else, so please use with caution.
