### ISSUE TITLE
S3 client depnds on conflicting versions of netty-handler and netty-codec-http

### ISSUE THREAD

**Issue by bradkaiser** [aws/aws-sdk-java-v2#1205]
I am using the java aws sdk s3 client in my scala project and I get a warning that says that there might be a binary incompatibility between versions of these libraries. I checked with a minimal project and the conflict is completely within the aws sdk and is not related to my project.

```
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn]  * io.netty:netty-codec-http:4.1.33.Final is selected over 4.1.13.Final
[warn]      +- software.amazon.awssdk:netty-nio-client:2.5.25     (depends on 4.1.33.Final)
[warn]      +- io.netty:netty-codec-http2:4.1.33.Final            (depends on 4.1.33.Final)
[warn]      +- com.typesafe.netty:netty-reactive-streams-http:2.0.0 (depends on 4.1.13.Final)
[warn]  * io.netty:netty-handler:4.1.33.Final is selected over 4.1.13.Final
[warn]      +- software.amazon.awssdk:netty-nio-client:2.5.25     (depends on 4.1.33.Final)
[warn]      +- io.netty:netty-codec-http2:4.1.33.Final            (depends on 4.1.33.Final)
[warn]      +- com.typesafe.netty:netty-reactive-streams:2.0.0    (depends on 4.1.13.Final)
```

## Expected Behavior

No warnings
## Current Behavior

incompatbility warning
## Possible Solution

It looks like this is related to netty-reactive-streams, maybe that needs to be updated.
## Steps to Reproduce (for bugs)

Here is my minimal sbt
```
lazy val root = (project in file (".")).settings(
  inThisBuild(List(
    organization  := "org",
    scalaVersion  := "2.11.8",
  )),
    name := "test",
    libraryDependencies += "software.amazon.awssdk" % "s3" % "2.5.25"
```
run `$sbt evicted`

## Your Environment

MacOS
java 1.8
scala 2.11.8
sbt  1.1.0
aws sdk 2.5.25

**Comment by varunnvs92** [comment]
This should not cause inconsistent behavior. As SDK directly depends on `4.1.33.Final`, the other version `4.1.13.Final` pulled in by another dependency will be ignored.

I noticed there are new versions of these dependencies. But we faced few bugs in Netty dependencies, so we will need to do proper load testing before using the new versions. I don't have a timeline for it though. This won't be a high priority request as this is a dependency warning and is not a blocker. You can always override the sdk dependency versions with the newer versions if your use case requires it.

**Comment by bradkaiser** [comment]
Thanks for looking into it 👍
