### ISSUE TITLE
headBucket operation throwing wrong exception when bucket does not exist

### ISSUE THREAD

**Issue by gpj1** [aws/aws-sdk-java-v2#123]
Hi,
I'm using aws s3 java sdk 2.0.0-preview-2 and I'm invoking headBucket method on s3Client.
In the HeadBucketRequest, when I give non existing bucket name, as per documentation I was expecting it to throw "NoSuchBucketException" but, it is throwing S3Exception with error code 404 inside it.
Below is my code snippet.

S3Client s3Client = S3Client.builder().credentialsProvider(new StaticCredentialsProvider(new AwsCredentials("xxxaccesskey", "yyyysecretkey"))).region("us-east-1").build();
try {
s3Client.headBucket(HeadBucketRequest.builder().bucket("non-existing-bucket-name").build());	
} catch(NoSuchBucketException noSuchBucketException) {
System.out.println("Nosuchbucket exception");
} catch(S3Exception s3Exception) {
System.out.println("s3Exception");
}

**Comment by gpj1** [comment]
Hi, because of this bug, currently I'm relying on some temporary work around. Is it possible to provide an ETA for the fix which helps me to plan our things correctly?

**Comment by kiiadi** [comment]
This actually looks more like a service issue to me, I can't get the NoSuchBucket exception to occur using the CLI either and as far as I can tell it's not an expected exception on head bucket : http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketHEAD.html

**Comment by gpj1** [comment]
Right. The doc says "404 error code inside S3Exception" when no such bucket exists in headBucket operation.
Then it is more interesting to know the purpose of NoSuchBucketException which also is declared as throws along with S3Exception in headBucket method.

**Comment by shorea** [comment]
Correct this is a limitation of HEAD requests since they don't return an XML body containing the error details. But for those operations that do return error codes, we are not unmarshalling them correctly in V2 to the modeled exception types. GetObjectAcl for example should throw a NoSuchBucketException when the bucket does not exist but right now it throws a generic S3Exception.

**Comment by zoewangg** [comment]
This has been fixed as part of #830 and will be included in the next release.
