### ISSUE TITLE
Where is the v2 equivalent of the com.amazonaws.services.dynamodbv2.document.Item.toJSON() fonctionality from the v1 sdk

### ISSUE THREAD

**Issue by lestephane** [aws/aws-sdk-java-v2#1240]
It used to be possible to call toJSON() on a dynamodb item with the v1 SDK.
I need some guidance on how this is to be achieved in the v2 SDK.

Searching for **toJSON** in the migration guide and the issues here did not yield any result.

Here is the method in question from the v1 SDK
```java
package com.amazonaws.services.dynamodbv2.document;
...
public class Item {
...
    /**
     * Returns this item as a JSON string.  Note all binary data will become
     * base-64 encoded in the resultant string.
     */
    public String toJSON() {
        return Jackson.toJsonString(this.attributes);
    }
```

**Comment by dagnir** [comment]
HI @lestephane, the Dynamo DB Document library is not yet available in V2. Work on the the library is current in progress, and can be tracked here in #35 (#36 is the original Document-specific ticket but the work is being combined with #35). There is an earlier MVP preview available in the
[dynamodb-enhanced](https://github.com/aws/aws-sdk-java-v2/tree/dynamodb-enhanced) branch but I don't believe this specific functionality is implemented there: https://github.com/aws/aws-sdk-java-v2/blob/dynamodb-enhanced/services-custom/dynamodb-enhanced/README.md

**Comment by millems** [comment]
Tracking this as part of #35
