### ISSUE TITLE
Too many SDK threads despite using non-blocking IO

### ISSUE THREAD

**Issue by martin-tarjanyi** [aws/aws-sdk-java-v2#1251]
## Expected Behavior
I expect only a fixed, low number of threads (proportional to number of CPU cores) used by the AWS SDK.

## Current Behavior
Based on the log messages it seems lots of (100s) threads are created to handle SDK responses.
Thread IDs start with 'sdk-async-response-' prefix. It seems there are are different thread pools for different services. S3 uses 'sdk-async-response-0-', while Athena  uses 'sdk-async-response-3-' prefix.

## Possible Solution
Using a single fixed sized thread pool used commonly by all AWS services.

## Steps to Reproduce (for bugs)
I noticed increasing number of threads for all services (S3 read/write, Athena pagination) that I used.

## Context
In reactive environments it's highly discouraged and ineffective to use so many threads especially if support for non-blocking IO exists.

## Your Environment
* AWS Java SDK version used: 2.5.24
* JDK version used: 1.8.0_111
* Operating System and version: Windows 10, Linux

**Comment by martin-tarjanyi** [comment]
Thanks for the response. Is this decision/reasoning documented somewhere?

I was checking the current implementation:
https://github.com/aws/aws-sdk-java-v2/blob/edf8f9f4a1cba5fbb268eab32b07f2ad0b058553/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkDefaultClientBuilder.java#L271-L275
As I see the default thread pool has 50 core threads and 50 maximum threads. Wouldn't it make sense to lower the number of core threads? I think that would benefit both the advanced non-blocking users (since they don't block the threads, only a couple of threads would be used and there is no overehead by the unused threads) and also the users that might block the thread (since the pool would scale up on demand). What do you think?

**Comment by millems** [comment]
The full code snipped allows core threads to be timed out:
```java
ThreadPoolExecutor executor = new ThreadPoolExecutor(50, 50,
                                                     10, TimeUnit.SECONDS,
                                                     new LinkedBlockingQueue<>(10_000),
                                                     new ThreadFactoryBuilder()
                                                         .threadNamePrefix("sdk-async-response").build());

// Allow idle core threads to time out
executor.allowCoreThreadTimeOut(true);
```

This means that there's no overhead on the unused threads (after 10 seconds of them not doing anything).

**Comment by martin-tarjanyi** [comment]
I've seen that option. Unfortunately, in practice it doesn't improve too much on efficiency since the the thread pool uses its threads in a round robin session.

Check the following code:
```java
ThreadPoolExecutor executor = new ThreadPoolExecutor(50, 50,
        10, TimeUnit.SECONDS,
        new LinkedBlockingQueue<>(10_000));

executor.allowCoreThreadTimeOut(true);

for (int i = 0; i < 300; i++) // runs for 300 * 100 / 1000 = 30 seconds
{
    executor.submit(() -> System.out.println(Thread.currentThread().getName()));
    System.out.println("Pool size: " + executor.getPoolSize());
    Thread.sleep(100);
}

executor.shutdown();
```
At anytime we have at most 1 active thread, however, we always have 50 alive threads in the pool since it uses them in round-robin, so the 10 seconds never expires.

If you run the same code with core size 1, then you will see the pool size is never bigger than one.
```java
ThreadPoolExecutor executor = new ThreadPoolExecutor(1, 50,
        10, TimeUnit.SECONDS,
        new LinkedBlockingQueue<>(10_000));

executor.allowCoreThreadTimeOut(true);

for (int i = 0; i < 300; i++) // runs for 300 * 100 / 1000 = 30 seconds
{
    executor.submit(() -> System.out.println(Thread.currentThread().getName()));
    System.out.println("Pool size: " + executor.getPoolSize());
    Thread.sleep(100);
}

executor.shutdown();
```

`allowCoreThreadTimeOut(true)` helps only if the there is significant time difference between subsequent SDK calls. In peak traffics it will use the entire pool even if it would be able to execute tasks with a single thread.

**Comment by millems** [comment]
It's definitely not ideal, but reducing the core pool size is risky as well, since 10,000 is a big backlog to build up for lower-traffic use-cases.

It would probably add some overhead (we'd have to benchmark to see how much) to shut down the idle workers when they're not needed (eg. with `setCorePoolSize`). Are you observing that the current thread count is causing too much memory consumption / contention?

**Comment by martin-tarjanyi** [comment]
I haven't seen any performance issues so far. It just simply goes against my expectations. I don't expect such thread pool in a library that uses non-blocking IO. Fortunately, as you've written there is a setting to modify this behavior.

I have the feeling that some documentation would be better to protect (and educate) users instead of introducing thread pools which might be confusing for other users (like me).

**Comment by millems** [comment]
We went back and forth on it in the original design. 

We found the impact of a customer accidentally using too many threads was smaller (a few milliseconds of latency) than a customer accidentally using too few (the application collapsing).

I agree that we can document this better, but I'm not sure of the best place. Is there a specific place you might have looked for this information? We're planning on doing a "configuring the SDK" series of blog posts and developer guide topics that this would show up. Would you have found this information there?

**Comment by martin-tarjanyi** [comment]
I was browsing this guide for information:
https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html

And I would have expected this info appear on this particular page:
https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html

Thanks for the discussion and your quick response time!

**Comment by millems** [comment]
Awesome, thanks for confirmation! That's where we'll put it, then.

**Comment by jaymmodi** [comment]
Were above mentioned documents updated?
