### ISSUE TITLE
Artifacts missed in maven repository 

### ISSUE THREAD

**Issue by guangleibao** [aws/aws-sdk-java-v2#1258]
## Following services artifacts are not found in Maven repo on `mvnrepository.com`:
+ alexaforbusiness, autoscalingplans, chime, cloud9, cloudhsmv2, cloudsearchdomain, comprehend, dlm, eks, fms, glue, guardduty, iot1clickdevices, iot1clickprojects, iotanalytics, iotjobsdataplane, kinesisvideoarchivedmedia, kinesisvideomedia, macie, mediaconvert, medialive, mediapackage, mediatailor, migrationhub, mobile, mq, pi, pinpointemail, pinpointsmsvoice, pricing, ram, resourcegroupstaggingapi, route53domains, route53resolver, sagemaker, sagemakerruntime, servicediscovery, signer, transcribe, transcribestreaming, translate, waf, and workmail.

**Comment by zoewangg** [comment]
Hmm, I did some quick searches and verified the artifacts were in maven.

https://search.maven.org/search?q=g:software.amazon.awssdk
https://mvnrepository.com/search?q=software.amazon.awssdk

**Comment by guangleibao** [comment]
`=)` I'm using following dependency in my pom.xml:
    
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>aws-sdk-java</artifactId>
      <version>2.5.42</version>
    </dependency>

Following services cannot be imported in code: `alexaforbusiness, autoscalingplans, chime, cloud9, cloudhsmv2, cloudsearchdomain, comprehend, dlm, eks, fms, glue, guardduty, iot1clickdevices, iot1clickprojects, iotanalytics, iotjobsdataplane, kinesisvideoarchivedmedia, kinesisvideomedia, macie, mediaconvert, medialive, mediapackage, mediatailor, migrationhub, mobile, mq, pi, pinpointemail, pinpointsmsvoice, pricing, ram, resourcegroupstaggingapi, route53domains, route53resolver, sagemaker, sagemakerruntime, servicediscovery, signer, transcribe, transcribestreaming, translate, waf,` and `workmail.`

## Example pom.xml (e.g: transcribe)
    <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
      <modelVersion>4.0.0</modelVersion>
      <groupId>org.example.basicapp</groupId>
      <artifactId>myapp</artifactId>
      <packaging>jar</packaging>
      <version>1.0-SNAPSHOT</version>
      <name>myapp</name>
      <url>http://maven.apache.org</url>
      <dependencies>
        <dependency>
          <groupId>junit</groupId>
          <artifactId>junit</artifactId>
          <version>3.8.1</version>
          <scope>test</scope>
        </dependency>
	    <dependency>
          <groupId>software.amazon.awssdk</groupId>
          <artifactId>aws-sdk-java</artifactId>
          <version>2.5.42</version>
        </dependency>
      </dependencies>
    </project>

## Example code (e.g: transcribe):
    package org.example.basicapp;
    import software.amazon.awssdk.services.transcribe.TranscribeClient;
    
    public class App {
        public static void main( String[] args ){
            TranscribeClient tc = null;
        }
    }

`mvn package` fails if the services are alexaforbusiness, autoscalingplans, chime, cloud9, cloudhsmv2, cloudsearchdomain, comprehend, dlm, eks, fms, glue, guardduty, iot1clickdevices, iot1clickprojects, iotanalytics, iotjobsdataplane, kinesisvideoarchivedmedia, kinesisvideomedia, macie, mediaconvert, medialive, mediapackage, mediatailor, migrationhub, mobile, mq, pi, pinpointemail, pinpointsmsvoice, pricing, ram, resourcegroupstaggingapi, route53domains, route53resolver, sagemaker, sagemakerruntime, servicediscovery, signer, transcribe, transcribestreaming, translate, waf, and workmail.

**Comment by zoewangg** [comment]
Can you try to just import the service you need? It's recommended to just import individual models instead to keep jar size smaller.

**Comment by guangleibao** [comment]
... I think not recommend is not equal to not worked. Anyway, this is the most smart patch I have ever seen, and Are Right A Lot and Bias for Action.

**Comment by zoewangg** [comment]
Thank you for your input. Yes, we will fix `aws-sdk-java` module. We just wanted to point out that importing individual modules is preferable.
