### ISSUE TITLE
Unable to connect to AWS Transcribe Streaming

### ISSUE THREAD

**Issue by gs2810** [aws/aws-sdk-java-v2#1266]
Unable to connect to AWS Transcribe Streaming using SDK

## Expected Behavior
Should be able to connect to AWS Transcribe to start a Transcribe Streaming job when following [this sample code](https://github.com/aws-samples/aws-transcribe-streaming-example-java) (linked to from the docs).

## Current Behavior
When connecting to AWS Transcribe, an SDKClientException is thrown, with inner exception `io.netty.handler.codec.http2.Http2Exception`.

```2019-05-24 10:12:05 [aws-java-sdk-NettyEventLoop-1-6] DEBUG software.amazon.awssdk.http.nio.netty.internal.NettyRequestExecutor:250 - Failed to create connection to https://transcribe.eu-west-3.amazonaws.com/stream-transcription
io.netty.handler.codec.http2.Http2Exception: First received frame was not SETTINGS. Hex dump for first 5 bytes: 485454502f
at io.netty.handler.codec.http2.Http2Exception.connectionError(Http2Exception.java:85) ~[netty-codec-http2-4.1.33.Final.jar:4.1.33.Final]
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.verifyFirstFrameIsSettings(Http2ConnectionHandler.java:350) ~[netty-codec-http2-4.1.33.Final.jar:4.1.33.Final]
at io.netty.handler.codec.http2.Http2ConnectionHandler$PrefaceDecoder.decode(Http2ConnectionHandler.java:251) ~[netty-codec-http2-4.1.33.Final.jar:4.1.33.Final]
at io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:450) ~[netty-codec-http2-4.1.33.Final.jar:4.1.33.Final]
...
```

See attached full log: [errorLog.txt](https://github.com/aws/aws-sdk-java-v2/files/3216116/errorLog.txt)

## Possible Solution
According to [this GitHub issue](https://github.com/grpc/grpc-java/issues/2905), the error means the server is not configured to support HTTP/2.

I may be missing an extra step in my client configuration, or I may be using the wrong endpoint, although my endpoint is consistent with [this official list](https://docs.aws.amazon.com/general/latest/gr/rande.html#transcribe_region).

I have tried using a different region, but the result is the same.
I intend to use use the **eu-west-3** region.

## Steps to Reproduce (for bugs)

I have reproduced this behaviour in a minimal client, see attached: [aws-transcribe.zip](https://github.com/aws/aws-sdk-java-v2/files/3216063/aws-transcribe.zip)

Relevant configuration code:

```java
public AwsTranscriberService() throws URISyntaxException {
    Region region = new DefaultAwsRegionProviderChain().getRegion();
    String endpoint = String.format("https://transcribe.%s.amazonaws.com", region.toString().toLowerCase().replace('_', '-'));

    this.awsAsyncClient = TranscribeStreamingAsyncClient.builder()
            .credentialsProvider(DefaultCredentialsProvider.create())
            .region(region)
            .endpointOverride(new URI(endpoint))
            .overrideConfiguration(c -> c.putAdvancedOption(SdkAdvancedClientOption.SIGNER, EventStreamAws4Signer.create()))
            .build();
}
```

## Context
This issue prevents me from integrating the Transcribe service with my application 😃 

## Your Environment
* AWS Java SDK version used: 2.5.48
* JDK version used: 1.8.0_202
* Operating System and version: Windows 10, 64-bit

**Comment by zoewangg** [comment]
Hmm, I think the endpoint is not right. You don't need to construct the endponit and the SDK would find the right endpoint based on the region you provided. Also, you don't need to override the signer.

For example:

https://github.com/aws/aws-sdk-java-v2/blob/39f6568dfd126dd8f4b579a0e4703c576f227ada/services/transcribestreaming/src/it/java/software/amazon/awssdk/services/transcribestreaming/TranscribeStreamingIntegrationTest.java#L52-L55

Looks like we need to update the code sample.

**Comment by gs2810** [comment]
KISS...

Thank you!
