### ISSUE TITLE
I am not able to import libraries from AWS Java SDK v2 into my AWS Java App project in Eclipse.

### ISSUE THREAD

**Issue by Shinehah-Gnolaum** [aws/aws-sdk-java-v2#1271]
## Expected Behavior
When I type "import software.amazon.awssdk." in a .java file in my AWS Java App project in Eclipse, with AWS Toolkit for Java installed, I expect the dropdown context help to show the libraries that I can import with the names starting with what I've already typed -- "software.amazon.awssdk.".

## Current Behavior
When I type "import software.amazon.awssdk." in a .java file in my AWS Java App project in Eclipse, with AWS Toolkit for Java installed, the dropdown context help does not show the libraries that I can import  with the names starting with what I've already typed -- "software.amazon.awssdk.".

## Possible Solution
I probably need to set some settings in Eclipse or in terminal so that Eclipse will see the AWS Java SDK v2. Perhaps I need to set settings in my AWS Java App project.

I found this documentation: https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/setup-project-maven.html. Eclipse uses Maven. I would need to do what that documentation says in the context of Eclipse.

## Steps to Reproduce (for bugs)
1. Create an AWS Java App project or an AWS Java Web project in Eclipse with the AWS Java Toolkit installed.
2. Create a package in "src/main/java".
3. Create a file and name it "Main.java".
4. Type "import software.amazon.awssdk."
5. A dropdown view should appear listing all the libraries that you can select to import with the names starting with "software.amazon.awssdk.". The error is that no libraries starting with that name is shown.

## Context
I'm trying to create an app to run on AWS that gets communication from iOS devices to cause the app on AWS to run code to send an SNS message to the iOS device via Apple Push Notification at a certain time determined by the user using the iOS device.

## Your Environment
* AWS Java SDK version used: v2
* JDK version used: 12.0.1
* Operating System and version: macOS Mojave Version 10.14.5
* Java IDE: Eclipse Version: 2019-03 (4.11.0); Build id: 20190314-1200

**Comment by varunnvs92** [comment]
This doesn't look like an issue in the SDK but might be a usage issue or bug in AWS Eclipse toolkit. Please open an issue in [aws-toolkit-eclipse](https://github.com/aws/aws-toolkit-eclipse) repo.

Feel free to reopen if you feel this is a feature request for the SDK team.
