### ISSUE TITLE
I can't use aws sdk for java 2 with login and password as credentials.

### ISSUE THREAD

**Issue by raonismaneoto** [aws/aws-sdk-java-v2#1274]
## Expected Behavior
I wish I could instantiate a client with login and password, and then, with this client, get the access/secret key.

## Possible Solution
Create another kind of client that allow the suggested operation.

## Context
My system provides support for clouds, and each of them allows the suggested approach. The user doesn't need to know any credentials but its login and password.

Is it already implemented? Am I missing anything?

* AWS Java SDK version used: v2. 2.5 
* JDK version used: 1.8
* Operating System and version: Ubuntu 18.04

**Comment by varunnvs92** [comment]
This feature is not currently supported. For any aws account, there can be multiple users, roles etc. Each user/role can have different credentials and different permission policies. Identifying the default creds to use using login details is tricky and can be confusing to customer.
This has to be supported at service level before SDK can add support. I would suggest opening a issue in [AWS IAM service forums](https://forums.aws.amazon.com/forum.jspa?forumID=76).

**Comment by debora-ito** [comment]
Additionally, take a look at [Amazon Cognito](https://docs.aws.amazon.com/cognito/latest/developerguide/what-is-amazon-cognito.html), maybe it's a good fit for your use case.
