### ISSUE TITLE
ExecutionAttribute does not override hashCode / equals

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-sdk-java-v2#1277]
## Expected Behavior

When writing additional `ExecutionInterceptor` implemeations, it's sometimes necessary to add items to, or retrieve items from, the `ExecutionAttributes` object. Internally, this uses a `HashMap` to store values against keys, which are instances of `ExecutionAttribute`.

However, two `ExecutionAttribute` keys with the same name are not considered equal (nor do they hash the same) so for example the following doesn't work:

```java
ExecutionAttributes attr = new ExecutionAttributes();

ExecutionAttribute key1 = new ExecutionAttribute<String>("MyKey");
attr.putAttribute(key1, "VALUE");

ExecutionAttribute key2 = new ExecutionAttribute<String>("MyKey");
String value = attr.getAttribute(key2);
```

After this code executes, `value` should contain the String `"VALUE"` but instead is `null`.

## Possible Solution

The `ExecutionAttribute` class should override the `hashCode()` and `equals()` methods using only the `name` member variable.

## Context
Writing some additional wrappers for `ExecutionInterceptor` and it's sometimes necessary to extract values that are set into `ExecutionAttributes` by existing AWS SDK classes - but if they don't make their `ExecutionAttribute` keys public, we cannot reuse those same instances so have to create our own.

## Your Environment
* AWS Java SDK version used: 2.5.53
* JDK version used: 1.8.202
* Operating System and version: MacOS X

**Comment by millems** [comment]
Our documentation is not sufficient in this area, sorry about that. Reference equality is used, instead of name equality, to allow for encapsulation via standard language mechanisms.

Make sure to reuse the same execution attribute reference and you should be good to go. We'll try to clarify the documentation in this area.

**Comment by ashleymercer** [comment]
@millems ah that makes sense.

Is there then an expectation that classes make their `ExecutionAttribute` instances public, so they can be used consistently? For example, a bunch of useful public keys are exposed here:

https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/SdkExecutionAttribute.java

but in my specific use case I want to access an X-Ray trace `Entity` but I can't get hold of it because the corresponding `AttributeKey` is private:

https://github.com/aws/aws-xray-sdk-java/blob/master/aws-xray-recorder-sdk-aws-sdk-v2/src/main/java/com/amazonaws/xray/interceptors/TracingInterceptor.java#L53

(This being Java, of course, I can get hold of it by reflection but...le sigh...)

**Comment by millems** [comment]
There's no expectation that they're public - it's up to the library developer to make that decision. That's one of the reason for using reference equality. Some people may want the freedom to remove or change the fields they use in the future without backwards-compatibility concerns.

You could consider asking X-Ray to expose this publicly (and therefore commit to never remove it) or you could attempt to get the information you need through other means (e.g. if the information you need was added to a header).

**Comment by ashleymercer** [comment]
Raised an issue for the X-Ray project, so will close this issue.
