### ISSUE TITLE
Not possible to disable netty read timeout

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-sdk-java-v2#1281]
## Expected Behavior
Netty allows the read timeout (and other timeouts) to be [set to 0 to disable them](https://github.com/netty/netty/blob/4.1/handler/src/main/java/io/netty/handler/timeout/IdleStateHandler.java#L177). This should be accessible through the AWS wrappers.

## Current Behavior
The AWS SDK `NettyNioAsyncHttpClient` classes [forces timeouts to be positive](https://github.com/aws/aws-sdk-java-v2/blob/edf8f9f4a1cba5fbb268eab32b07f2ad0b058553/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.java#L386) which means it can't be disabled.

## Possible Solution
Allow `Duration.ZERO` to be passed to `NettyNioAsyncHttpClient.Builder.readTimeout()` and other similar functions where appropriate.

## Context
Trying to disable read timeouts when invoking long-running lambda functions. In general read timeouts are probably a good thing (we wouldn't, for example, expect s3 to take more than 30 seconds to respond) but for lambda functions we can rely on whatever timeout is configured on the lambda function itself, so additionally specifying a read timeout on the client side isn't useful.

## Your Environment

* AWS Java SDK version used: 2.5.53
* JDK version used: 1.8.202

**Comment by zoewangg** [comment]
Implemented via #1286 and released in [2.5.59](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#2559-2019-06-07).

**Comment by ashleymercer** [comment]
@zoewangg thanks for the super-quick turnaround on this!
