### ISSUE TITLE
Add S3 Select APIs in the S3 client

### ISSUE THREAD

**Issue by humanzz** [aws/aws-sdk-java-v2#1290]
I'm using the S3 client from AWS SDK v2 and was surprised that it lacks support for S3 Select.

Going through the SDK v1, I can see it supports it as evidenced by the API doc at https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3.html#selectObjectContent-com.amazonaws.services.s3.model.SelectObjectContentRequest-

Unfortunately, I did not manage to find any counter-part in the SDK v2 client.

This is a feature request to add support for S3 Select in the S3 client APIs.

## Expected Behavior
S3 client have APIs enabling the use of S3 Select

## Current Behavior
S3 client does not have APIs for using S3 Select

## Context
I'm using SDK v2 in a Java Lambda which uses the S3 client to access S3 objects which have JSON records. The Lambda does some filtering of the records - to find records matching certain criteria - which discards the majority of the JSON records and it then proceeds to process the filtered records.

**Comment by jhg023** [comment]
#859 already seems to be an issue for this.

**Comment by humanzz** [comment]
@jhg023 thanks for this. Looks like I did miss the issue you pointed out.
Closing this in favour of the other one then.
