### ISSUE TITLE
Missing Fat Jar in Bundle

### ISSUE THREAD

**Issue by joshuaRosales** [aws/aws-sdk-java-v2#1294]
In the Version 1 AWS Java SDK, I was able to get a ~127MB fat jar (a jar that contains all the AWS services and their dependencies) under aws-java-sdk-bundle when I built using Maven. When I build in the Version 2 AWS Java SDK, I don't get the fat jar. 

Is there something that I have to modify in the pom.xml to make it work?

Version 1: 
![image](https://user-images.githubusercontent.com/4998183/59389855-1f55a380-8d35-11e9-82e9-fffc99aac378.png)
Version 2:
![image](https://user-images.githubusercontent.com/4998183/59389877-33010a00-8d35-11e9-9f10-57357f4e1214.png)

No fat Jar. =(
_

## Expected Behavior
I expect the fat jar to be generated.

## Current Behavior
The fat jar is not generated.

## Possible Solution
I don't know how to fix this. Probably involves changes to pom.xml in the bundle directory.

## Steps to Reproduce (for bugs)
mvn clean install -DskipTests

## Context
My project is not using Maven. I want to get a fat jar of the AWS Java SDK that I can use in Wildfly.

## Your Environment
C:\Users\josh\Downloads\aws-sdk-java-v2-2.5.62\aws-sdk-java-v2-2.5.62>mvn --version
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T13:33:14-05:00)
Java version: 1.8.0_161, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_161\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by zoewangg** [comment]
Hmm, I was able see the bundle jar from `mvn install`, not sure if this is related to specific maven version or OS. Can you download the bundle jar from maven? https://search.maven.org/search?q=g:%22software.amazon.awssdk%22%20AND%20a:%22bundle%22

**Comment by joshuaRosales** [comment]
Yes, I'm able to download that jar. I'm not sure why I wasn't able to build it using Maven. But I'm happy being able to download it. lol.

I'll download the latest Maven version and try again. Although, it is also odd that I was able to build it for  Version 1 of the AWS SDK but can't build the jar for Version 2.

**Comment by joshuaRosales** [comment]
Trying again with new mvn version:
C:\Users\josh>mvn --version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T14:00:29-05:00)
Maven home: C:\Maven\apache-maven-3.6.1-bin\apache-maven-3.6.1\bin\..
Java version: 1.8.0_161, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_161\jre
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

![image](https://user-images.githubusercontent.com/4998183/59632404-c52b5880-910f-11e9-8b53-51a7d84ccb3a.png)

I get the same result. No fat Jar. I'll just use the jar I downloaded.

**Comment by dagnir** [comment]
hi @joshuaRosales, the uber JAR requires the use of the `maven-shade-plugin` which is only included when using the [`publishing` profile](https://github.com/aws/aws-sdk-java-v2/blob/bedbb13ded73fc318aff1808fdd998a99af76098/bundle/pom.xml#L141).

If you'd still like to build it locally, you can do the following:

```
mvn clean install -P quick,publishing -Dgpg.skip=true -pl :bundle -am
```

Going to go ahead and close this. Please feel free to reopen if you have further questions.
