### ISSUE TITLE
Allow users to configure NioEventLoop thread pool size

### ISSUE THREAD

**Issue by pranaydalmia** [aws/aws-sdk-java-v2#13]
As a user of the AWS SDK, I want to be able to configure the number of threads used assigned to the EventLoopGroup. 

Currently, this is not configurable and the library relies on Netty to pick the number of threads. Netty defaults to 2 * number of cores, as the thread pool size: https://github.com/netty/netty/blob/4.1/transport/src/main/java/io/netty/channel/MultithreadEventLoopGroup.java#L40-L41

While this is good for most users, some users would want to configure this based on application requirements and available resources on client's host.

**Comment by shorea** [comment]
Picking this up
