### ISSUE TITLE
s3 java sdk, advancedconfiguration has no effect.

### ISSUE THREAD

**Issue by gpj1** [aws/aws-sdk-java-v2#130]
I'm using aws java s3 sdk 2.0.0-preview-2 and building s3client like below

`S3Client.builder().credentialsProvider(newStaticCredentialsProviderWithBasicCredentials("xxxx", "yyyy"))											.advancedConfiguration(S3AdvancedConfiguration.builder().accelerateModeEnabled(true).pathStyleAccessEnabled(true).build()).endpointOverride(new URI("https://mys3compatible.storage:8082")) .build();`

But, what I observed while using such s3 client is, the advanced configuration is not taking any effect at all.
When I debugged, I found that, `software.amazon.awssdk.client.ClientHandlerImpl#execute(ClientExecutionParams<InputT, OutputT> executionParams)` is losing the advanced configuration while building `SdkHttpFullRequest`

This is causing a blocker for one of our implementation and I'm thinking to switch back to 1.x version of sdk. Could some please guide me?

**Comment by shorea** [comment]
Taking a look, must be a regression.

**Comment by shorea** [comment]
Identified the bug, discussing a fix with the team.

**Comment by shorea** [comment]
Just a quick update, very nearly have this done, just finishing up some tests. Should have this out by tomorrow.

**Comment by gpj1** [comment]
Thanks for the update @shorea

**Comment by shorea** [comment]
Got a PR out for this, https://github.com/aws/aws-sdk-java-v2/pull/142

**Comment by shorea** [comment]
This has been released in 2.0.0-preview-4

**Comment by gpj1** [comment]
Great work.. Thanks
