### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [aws/aws-sdk-java-v2#1317]
Hi
The following lines have cryptographic API misuses. <br> File name => utils/src/main/java/software/amazon/awssdk/utils/Md5Utils.java: Line number => 81: API name => MessageDigest:<BR> File name => utils/src/main/java/software/amazon/awssdk/utils/Md5Utils.java: Line number => 81: API name => MessageDigest:<BR> File name => utils/src/main/java/software/amazon/awssdk/utils/Md5Utils.java: Line number => 53: API name => MessageDigest:<BR> File name => utils/src/main/java/software/amazon/awssdk/utils/Md5Utils.java: Line number => 80: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => utils/src/main/java/software/amazon/awssdk/utils/Md5Utils.java: Line number => 47: API name => MessageDigest:Unexpected call to method <java.security.MessageDigest: byte[] digest()> on object of type java.security.MessageDigest. Expect a call to one of the following methods <java.security.MessageDigest: void update(byte[])>,<java.security.MessageDigest: void update(byte[],int,int)>,<java.security.MessageDigest: byte[] digest(byte[])>,<java.security.MessageDigest: void update(java.nio.ByteBuffer)>,<java.security.MessageDigest: void update(byte)><BR> File name => test/test-utils/src/main/java/software/amazon/awssdk/testutils/InputStreamUtils.java: Line number => 36: API name => MessageDigest:First parameter (with value "MD5") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => test/test-utils/src/main/java/software/amazon/awssdk/testutils/InputStreamUtils.java: Line number => 41: API name => MessageDigest:<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AwsChunkedEncodingInputStream.java: Line number => 120: API name => MessageDigest:Operation on object of type java.security.MessageDigest object not completed. Expected call to digest, update<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AwsChunkedEncodingInputStream.java: Line number => 123: API name => SecretKeySpec:<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsSigner.java: Line number => 146: API name => SecretKeySpec:<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AbstractAwsSigner.java: Line number => 146: API name => SecretKeySpec:<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AwsChunkedEncodingInputStream.java: Line number => 122: API name => Mac:Operation on object of type javax.crypto.Mac object not completed. Expected call to update, doFinal<BR> File name => core/auth/src/main/java/software/amazon/awssdk/auth/signer/internal/AwsChunkedEncodingInputStream.java: Line number => 123: API name => SecretKeySpec:<BR>

**Comment by debora-ito** [comment]
Hi @mhp0rtal, as I mentioned in https://github.com/aws/aws-sdk-java/issues/2039 some of the entries are about using MD5, which is being used by the APIs as a checksum to verify data integrity and not as a cryptographic hash function, so this is not a security issue.

A lot of entries have no detailed description, what is not very helpful in a code analysis report.

Closing this since there's no issue with the SDK. Please feel free to reopen if you have further questions.
