### ISSUE TITLE
Cant find API to trigger Lambda on S3Event

### ISSUE THREAD

**Issue by rvankacloud** [aws/aws-sdk-java-v2#1319]
We are trying to upgrade the AWS java S3 API from 1.11.452 to 2.5.62 , and one of the functionality we use currently  is invoking a Lambda function when an object is updated to S3.
Currently we use aws-lambda-java-events (2.2.6) to trigger the Lambda when an object in S3 bucket is updated.

Here is the class that we use com.amazonaws.services.lambda.runtime.events.S3Event to read the S3 events from Lambda, what is the equivalent in the AWS SDK v2 for this?

## Expected Behavior
Should have an AWS lambda-java-events API that is compatible with AWS S3 API  2.5.62.

## Current Behavior
Cant find an API in the newer SDK to handle S3 upload events  which trigger Lambda execution that is compatible with AWS S3 API  2.5.62

## Possible Solution
May be I overlooked and there is  S3 Event handling API for Lambda for the Version V2.

## Steps to Reproduce (for bugs)
Create a AWS Lambda 
public class SomeLambda implements RequestHandler<S3Event, String> with AWS S3(version 1.11.452) and aws-lambda-java-events (version 2.2.6) .
Now try to upgrade the S3 SDK to 2.5.62.

## Context
Can't upgrade to AWS Version 2 (2.5.62) without a compatible Lambda event handling for S3 object updates.
## Your Environment

* AWS Java SDK version used: 2.5.62
* JDK version used: 1.8
* Operating System and version: Serverless Lambda's

**Comment by varunnvs92** [comment]
`aws-lambda-java-events` is not managed by the SDK team ([This](https://github.com/aws/aws-lambda-java-libs/tree/master/aws-lambda-java-events) is the repo). Looking at their issues, there is already an [open issue](https://github.com/aws/aws-lambda-java-libs/issues/74) for this. Please engage on that issue. Thank you.
