### ISSUE TITLE
S3 SDK Region Not Found

### ISSUE THREAD

**Issue by klonhj2015** [aws/aws-sdk-java-v2#1324]
Many regions can  not be found in the class BucketLocationConstraint, for examle cn-northwest-1. Maybe this class is auto-generated from services/s3/src/main/resources/codegen-resources/service-2.json, but we can not find some ways to solve the promble. Please check it!!!

**Comment by varunnvs92** [comment]
You are correct. This class is auto-generated from the service model. I will cut a ticket a service team about the issue.
Java SDK provides _String_ alternative methods for all methods that takes enum. I would suggest using them for now.

**Comment by rodel0723** [comment]
How about the region that is not currently supported on Region class like the ap-northeast-3 (Osaka)? How can we create S3Client for that region or any client for that matter?

**Comment by debora-ito** [comment]
Both regions `cn-northwest-1` and `ap-northeast-3` are now present in the BucketLocationConstraint enum.
