### ISSUE TITLE
Upgrade httpcomponents:httpcore version from 4.4.10 to 4.4.11

### ISSUE THREAD

**Issue by josephlbarnett** [aws/aws-sdk-java-v2#1326]
## Expected Behavior
When importing aws sdk, maven enforcer's dependency convergence warning should not detect anything.

## Current Behavior
the enforcer rule fails with:
```
Dependency convergence error for org.apache.httpcomponents:httpcore:4.4.11 paths to dependency are:
  +-software.amazon.awssdk:kms:2.7.0
    +-software.amazon.awssdk:apache-client:2.7.0
      +-org.apache.httpcomponents:httpclient:4.5.9
        +-org.apache.httpcomponents:httpcore:4.4.11
and
  +-software.amazon.awssdk:kms:2.7.0
    +-software.amazon.awssdk:apache-client:2.7.0
      +-org.apache.httpcomponents:httpcore:4.4.10
```

## Possible Solution
Bump httpcomponents:httpcore version from 4.4.10 to 4.4.11

## Steps to Reproduce (for bugs)
Enable the dependency convergence rule of the maven enforcer plugin in a project that depends on an aws sdk component that pulls in apache-client:
```
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>${version.maven.enforcer}</version>
                    <executions>
                        <execution>
                            <id>enforcer</id>
                            <phase>validate</phase>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                        </execution>
                    </executions>
                    <configuration>
                        <rules>
                            <dependencyConvergence/>
                        </rules>
                    </configuration>
</plugin>
```

## Context
We have dependency convergence enabled to help us track down potential version mismatches in transitive dependencies.  depending on httpclient:4.5.9 and httpcore:4.4.10 causes the issue as httpclient depends on httpcore:4.4.11

## Your Environment
* AWS Java SDK version used:  2.7.0
* JDK version used: 11.0.2
* Operating System and version:  circle ci's circleci/openjdk:11-jdk docker image

**Comment by varunnvs92** [comment]
Seems like a straightforward upgrade. Are there any breaking changes between these versions? Can you send us a pull request?

**Comment by josephlbarnett** [comment]
looks like a bugfix/maintenance release according to https://www.apache.org/dist/httpcomponents/httpcore/RELEASE_NOTES-4.4.x.txt
