### ISSUE TITLE
SDK should support https.proxyHost and https.proxyPort system properties

### ISSUE THREAD

**Issue by stamhankar999** [aws/aws-sdk-java-v2#1334]
## Expected Behavior

http.proxyHost and http.proxyPort system properties are supported for hitting an http proxy, but https.proxyHost and https.proxyPort are not supported.

## Current Behavior
https.proxyHost and https.proxyPort are not supported.

## Possible Solution
* Update ProxySystemSetting to have new enum values for https.proxyHost, https.proxyPort, and https.nonProxyHosts. Not sure if it makes sense to duplicate proxyUser and proxyPassword enums.

* Update ProxyConfiguration to resolve host/port by checking for https proxy properties first, and if not set then check for http proxy properties, else no proxy. Update resolveScheme to set the scheme to 'http' or 'https' depending on which system properties are set (if any).

## Context
I have an https proxy in one deployment environment, and no proxy in another environment.

## Your Environment
* AWS Java SDK version used: 2.5.44
* JDK version used: 1.8.0_192
* Operating System and version: Amazon Linux 4.14.72-73.55.amzn2.x86_64 (from uname)

**Comment by tenjaa** [comment]
We ran into this issue today as well.
Would you be open for a pull-request to fix this?
