### ISSUE TITLE
S3AsyncClient NullPointerException

### ISSUE THREAD

**Issue by zoewangg** [aws/aws-sdk-java-v2#1343]
I'm still getting the error with 2.7.4 here is the code.

    `final Path tempFile = Files.createTempFile(workDirectory, tempFilePrefix, "tmp");
        AwsCredentialsProvider creds = StaticCredentialsProvider.create(AwsBasicCredentials.create(awsKey, 
    awsSecret));
        S3AsyncClient client = S3AsyncClient.builder().credentialsProvider(creds).build();
        
        final CompletableFuture<GetObjectResponse> futureGet = client.getObject(
                GetObjectRequest.builder()
                        .bucket(s3Bucket)
                        .key(s3Path)
                        .build(),
                AsyncResponseTransformer.toFile(tempFile.toFile()));
    
        futureGet.whenComplete((resp, err) -> {
            try {
                if (resp != null) {
                    System.out.println(resp);
                } else {
                    err.printStackTrace();
                }
            } finally {
                client.close();
            }
        });
    
        futureGet.join();`

Here is the stack trace.
`16:32:23,432 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4) java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException
16:32:23,432 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.utils.CompletableFutureUtils.errorAsCompletionException(CompletableFutureUtils.java:61)
16:32:23,432 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage.lambda$execute$0(AsyncExecutionFailureExceptionReportingStage.java:51)
16:32:23,433 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncExecutionFailureExceptionReportingStage$$Lambda$260/1366089113.apply(Unknown Source)
16:32:23,433 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture$HandleCompletion.run(CompletableFuture.java:1403)
16:32:23,433 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
16:32:23,434 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
16:32:23,434 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
16:32:23,434 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
16:32:23,434 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.internalComplete(CompletableFuture.java:210)
16:32:23,434 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture$ThenApply.run(CompletableFuture.java:723)
16:32:23,435 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
16:32:23,435 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2361)
16:32:23,435 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryErrorIfNeeded(AsyncRetryableStage.java:175)
16:32:23,435 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:126)
16:32:23,436 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.lambda$execute$0(AsyncRetryableStage.java:107)
16:32:23,436 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor$$Lambda$256/24632579.accept(Unknown Source)
16:32:23,436 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture$WhenCompleteCompletion.run(CompletableFuture.java:1298)
16:32:23,437 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:193)
16:32:23,437 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2361)
16:32:23,437 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onError(MakeAsyncHttpRequestStage.java:249)
16:32:23,437 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.lambda$exceptionCaught$0(ResponseHandler.java:142)
16:32:23,437 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$$Lambda$362/1655983226.run(Unknown Source)
16:32:23,438 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:180)
16:32:23,439 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.exceptionCaught(ResponseHandler.java:142)
16:32:23,440 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:285)
16:32:23,440 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.notifyHandlerException(AbstractChannelHandlerContext.java:856)
16:32:23,440 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:364)
16:32:23,441 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
16:32:23,441 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
16:32:23,441 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at com.typesafe.netty.HandlerPublisher.channelRead(HandlerPublisher.java:356)
16:32:23,441 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
16:32:23,442 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
16:32:23,442 ERROR [stderr] (aws-java-sdk-NettyEventLoop-1-4)   at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
`
`Caused by: software.amazon.awssdk.core.exception.SdkClientException
        at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:97) [sdk-core.jar:]
        at software.amazon.awssdk.core.internal.util.ThrowableUtils.asSdkException(ThrowableUtils.java:98) [sdk-core.jar:]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.AsyncRetryableStage$RetryExecutor.retryIfNeeded(AsyncRetryableStage.java:125) [sdk-core.jar:]
        ... 71 more
Caused by: java.lang.NullPointerException
        at software.amazon.awssdk.core.internal.http.async.AsyncStreamingResponseHandler.onHeaders(AsyncStreamingResponseHandler.java:56) [sdk-core.jar:]
        at software.amazon.awssdk.core.internal.http.async.AsyncAfterTransmissionInterceptorCallingResponseHandler.onHeaders(AsyncAfterTransmissionInterceptorCallingResponseHandler.java:67) [sdk-core.jar:]
        at software.amazon.awssdk.core.internal.http.pipeline.stages.MakeAsyncHttpRequestStage$ResponseHandler.onHeaders(MakeAsyncHttpRequestStage.java:235) [sdk-core.jar:]
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.channelRead0(ResponseHandler.java:94) [netty-nio-client.jar:]
        at software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.channelRead0(ResponseHandler.java:65) [netty-nio-client.jar:]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport.jar:4.1.33.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport.jar:4.1.33.Final]
        ... 58 more
`

_Originally posted by @kranthigurram in https://github.com/aws/aws-sdk-java-v2/issues/1122#issuecomment-510957982_

**Comment by zoewangg** [comment]
I was able to reproduce the issue with an incorrect credential. Looks similar to #1268

**Comment by kranthigurram** [comment]
But my credentials are correct, i just replaced my code with S3AsyncClient.

     `final Path tempFile = Files.createTempFile(workDirectory, tempFilePrefix, "tmp");
    final TransferManager s3 = new TransferManager(new BasicAWSCredentials(awsKey, awsSecret));
    final Download download = s3.download(s3Bucket, s3Path, tempFile.toFile());
    s3.shutdownNow();`

**Comment by zoewangg** [comment]
The issue is that `AsyncStreamingResponseHandler#prepare` was not invoked before `#onHeaders` as described on javadoc, so `transformFuture` was null, and there was an exception thrown from `onHeaders` and it was trying to complete the `transformFuture`, which caused NPE. I'm not sure what the underlying exception was for your case, but I'll work on fixing the NPE.

https://github.com/aws/aws-sdk-java-v2/blob/393687dc177a3c94814490a9847b1abaaf2fed9d/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/async/AsyncStreamingResponseHandler.java#L55-L56

**Comment by dagnir** [comment]
Fixed by #1360. Closing.
