### ISSUE TITLE
Use auto generated attributes in dynamodb documents

### ISSUE THREAD

**Issue by jogee** [aws/aws-sdk-java-v2#1345]
I'm looking for similar functionality to automatically generate UUID's for embedded documents as was being discussed in the dynamodb mapper improvements topic.

Issue reported external to github: @DynamoDBGeneratedUuid does not work for nested list objects.

```Java
@DynamoDBTable(tableName="XYZ")
class A {
    @DynamoDBAttribute
    List<B> listOfB;
}

@DynamoDBDocument
class B {
    @DynamoDBGeneratedUuid(DynamoDBAutoGenerateStrategy.CREATE)
    UUID id;
} 
```

_Originally posted by @millems in https://github.com/aws/aws-sdk-java-v2/issues/35#issuecomment-332958299_

**Comment by dagnir** [comment]
Hi @jogee could you add this as a comment to #35? We would prefer to track all new Mapper features in a single issue.
