### ISSUE TITLE
S3 object with expire date it is not deleted

### ISSUE THREAD

**Issue by zoraida** [aws/aws-sdk-java-v2#1348]
Hi,

I am uploading a file by using the multipart upload feature. I am setting the expire date at the moment of creating the multipart upload. When the expire date arrives, the object is not deleted.

## Expected Behavior
I would expect the object to be deleted when expire date arrives
## Current Behavior

The expire date is set but the object is not deleted.

## Steps to Reproduce (for bugs)

The code used to created the multipart upload with the expire date(`expiration` is a Long):

```
            s3.createMultipartUpload(
              CreateMultipartUploadRequest
                .builder
                .bucket(bucket)
                .key(key)
                .expires(Instant.ofEpochSecond(expiration))
                .build
            )
```

## Your Environment
AWS SDK version 2.5.53
JDK version 8
Linux RedHat

**Comment by debora-ito** [comment]
Hi @zoraida, the `expires` date is actually the date and time at which the object should no longer be cached. You can read more details in the  S3 Multipart Upload [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html) or in the CreateMultipartUploadRequest [javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CreateMultipartUploadRequest.html#expires--).

**Comment by zoraida** [comment]
Hi @debora-ito,
I see, thanks. Then, is there any programmatic way of setting a "live cycle" for the object rather than a bucket rule?

**Comment by debora-ito** [comment]
You can specify a lifecycle configuration with expiration actions, defining rules that can be applied to all or a subset of objects in a bucket, based on filters that you define.

Take a look at the Object Lifecycle Management [documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/object-lifecycle-mgmt.html) and let us know if that helps.

**Comment by debora-ito** [comment]
Closing, feel free to reopen if you have further questions.
