### ISSUE TITLE
Checking an empty stream for messages takes a really long time

### ISSUE THREAD

**Issue by danotorrey** [aws/aws-sdk-java-v2#1351]
We have code that attempts to read a sample message from a Kinesis stream. This works well for streams that have lots of messages in them. However, it is very slow for empty streams (that contained messages at one time). Hundreds and hundreds of getRecords calls with subsequent new shardIterators are needed to iterate through the entire stream only to find out it does not contain messages.

Here's what the code does:

1. Iterates through the shards in a stream
2. Gets an initial shard iterator with the `TRIM_HORIZON` shardIteratorType
2. For each shard, getRecords is called iteratively with subsequent shard iterator. 

Full code:
https://github.com/Graylog2/graylog-plugin-integrations/blob/dc91a60bd823312835b6df80799c1189002dde3b/src/main/java/org/graylog/integrations/aws/service/KinesisService.java#L259-L306

Is there a more efficient way to pick one single message from a stream? We just need one (Totally ok to be the first or last message in the stream). Do we really have to iterate through the entire shard to do this? Is there a request that we can execute to find out the sequence of the first or last message in the stream? Thanks in advance!

* AWS Java SDK version used: 2.5.33
* JDK version used: 8
* Operating System and version: macOS

**Comment by danotorrey** [comment]
Hi, I am just checking in on this issue to see if anyone has any ideas. Thanks in advance.

**Comment by zoewangg** [comment]
Sorry for the delay. You can probably try `subscribeToShard` [sample code](https://github.com/aws/aws-sdk-java-v2/blob/master/services/kinesis/src/it/java/software/amazon/awssdk/services/kinesis/SubscribeToShardIntegrationTest.java#L90) with a response handler that cancel the subscription once it receives one message.

This is more like a service specific question and could you post it on stackoverflow or AWS forums  https://forums.aws.amazon.com/forum.jspa?forumID=169? The service team might provide a better answer.

**Comment by danotorrey** [comment]
@zoewangg Thank you!
