### ISSUE TITLE
amazon-sqs-java-messaging-lib and aws-sdk-java-v2

### ISSUE THREAD

**Issue by AlexisCothenet** [aws/aws-sdk-java-v2#1374]
Hello,

There exists a library used for communicating with sqs [amazon-sqs-java-messaging-lib](https://github.com/awslabs/amazon-sqs-java-messaging-lib) . 
It has been written with the sdk version 1.11. 
I can' t find the equivalent for the SDK 2.0. Do you know if it's planned to have an equivalent or not ?
Thank you.
Best regards

**Comment by zoewangg** [comment]
Hi, `amazon-sqs-java-messaging-lib` is not maintained by our team. Looks like there is already a feature request open on that repo. https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/78  Could you +1 on that issue?

**Comment by AlexisCothenet** [comment]
> Hi, `amazon-sqs-java-messaging-lib` is not maintained by our team. Looks like there is already a feature request open on that repo. [awslabs/amazon-sqs-java-messaging-lib#78](https://github.com/awslabs/amazon-sqs-java-messaging-lib/issues/78) Could you +1 on that issue?

done. Thanks.

**Comment by ericknet** [comment]
Any plants to add support JMS into SDK v.2?
