### ISSUE TITLE
Incompatibility with Netty 4.1.39.Final

### ISSUE THREAD

**Issue by cescoffier** [aws/aws-sdk-java-v2#1399]
The async client extend internal classes from Netty and the `ForkedHttp2MultiplexCodec` is not compatible with Netty 4.1.39.Final. 

## Steps to Reproduce (for bugs)

An update of the Netty version will show compilation issues.

## Context

This is related to Quarkus (https://quarkus.io), where we have a dynamodb extension that blocks the update of netty.

**Comment by cescoffier** [comment]
I did a quick hack that may work...
[ForkedHttp2MultiplexCodec.txt](https://github.com/aws/aws-sdk-java-v2/files/3559454/ForkedHttp2MultiplexCodec.txt)

**Comment by dagnir** [comment]
Hey @cescoffier, thanks for the bug report. We have an open PR that addresses this: https://github.com/aws/aws-sdk-java-v2/pull/1391. There's an existing open issue for this (https://github.com/aws/aws-sdk-java-v2/issues/1344) so I'm going to go ahead and close this as a duplicate.

**Comment by cescoffier** [comment]
Thanks for the feedback @dagnir. Looking forward to having the fix released!
