### ISSUE TITLE
Used a named thread factory for the EventLoop threads

### ISSUE THREAD

**Issue by pranaydalmia** [aws/aws-sdk-java-v2#14]
As a user of the SDK, having a formal name for the EventLoop threads, will make it easier to debug and troubleshoot production issues. 

For example, a named thread pool is easier to find in a thread dump or while doing some CPU profiling. 

Threads could be named something like: 
"AWS-SDK-EventLoopThread-\<GroupNumber>-\<WorkerNumber>". 

GroupNumber is the EventLoopGroup number. Typically most clients will have one instance of the AWS SDK instantiated per JVM and this will always be 1. For some reason, they do spin up multiple, having different GroupNumber will avoid thread name collisions. 

WorkerNumber is the thread number within an EventLoopGroup.

**Comment by zoewangg** [comment]
EventLoop threads are being prefixed with `aws-java-sdk-NettyEventLoop` now. Closing the issue. 

https://github.com/aws/aws-sdk-java-v2/blob/5e0725b88489eb4deca5d5c760dee15f6846c1f6/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/SdkEventLoopGroup.java#L117
