### ISSUE TITLE
"unchecked generic array creation" warnings when using sdk methods that take Consumer<Builder> varargs

### ISSUE THREAD

**Issue by lestephane** [aws/aws-sdk-java-v2#1400]
I'm getting warnings when using sdk methods that take varargs (`Consumer<Builder>...`). Those methods are the sanest and least verbose way I found to use the sdk.

But these methods cause warnings at compile time, so I'm forced to switch to more verbose alternatives, since warning are flagged as errors in my builds.

I also haven't been able to find to a way to suppress the warning. Did I miss something? 

```java
final CreateTableResponse response = ddb.createTable(req -> req
    .billingMode(BillingMode.PAY_PER_REQUEST)
    .tableName(customerTable().tableName())
    .attributeDefinitions(
            customerIdAttr -> customerIdAttr.attributeName(customerId).attributeType(S),
            identityUserIdAttr -> identityUserIdAttr.attributeName(identityUserID).attributeType(S))
    .keySchema(primaryKey -> primaryKey.attributeName(customerId).keyType(HASH))
    .globalSecondaryIndexes(idx -> idx.indexName(customerTable().identityUserIdIndexName())
            .keySchema(attr -> attr.keyType(HASH).attributeName(identityUserID))
            .projection(project -> project.projectionType(ProjectionType.KEYS_ONLY))));
``` 

And the warnings:
```text
Warning:(114, 38) java: unchecked generic array creation for varargs parameter of type java.util.function.Consumer<software.amazon.awssdk.services.dynamodb.model.AttributeDefinition.Builder>[]
Warning:(117, 27) java: unchecked generic array creation for varargs parameter of type java.util.function.Consumer<software.amazon.awssdk.services.dynamodb.model.KeySchemaElement.Builder>[]
Warning:(119, 35) java: unchecked generic array creation for varargs parameter of type java.util.function.Consumer<software.amazon.awssdk.services.dynamodb.model.KeySchemaElement.Builder>[]
Warning:(118, 40) java: unchecked generic array creation for varargs parameter of type java.util.function.Consumer<software.amazon.awssdk.services.dynamodb.model.GlobalSecondaryIndex.Builder>[]
```

## Expected Behavior

No warnings

## Current Behavior

Warnings

## Possible Solution

Not that I know of. `@SafeVarargs` can't be added to interfaces.

## Your Environment

* AWS Java SDK version used: 2.7.35
* JDK version used: 12.0.2-open

**Comment by varunnvs92** [comment]
`@SafeVarargs` is added to implementation of all these methods during code generation. I am not sure why you are seeing this warning. Did this started happening recently?

**Comment by lestephane** [comment]
@varunnvs92 hard to say, i wrote that code this week for the first time...

**Comment by lestephane** [comment]
I was using `-Xlint:all` without `fork = true` in my `pom.xml`, so I was getting this warning in Intellij, but not maven CLI, which threw me off. When I don't use `Xlint:all`, everything is fine. If I want to use `-Xlint:all`, then I need to `@SuppressWarnings("unchecked")` for the line in question. I don't believe there is a way for the SDK to avoid such warnings at the call site.

Have you considered adding additional non-varargs methods that take `Iterable`

* java.lang.Iterable<AttributeDefinition.Builder>
* java.lang.Iterable<KeySchemaElement.Builder>
* java.lang.Iterable<KeySchemaElement.Builder>
* java.lang.Iterable<GlobalSecondaryIndex.Builder>
* etc...

Having this would allow me to wrap my problematic varargs array with List.of() (or some other shorter alias of mine), which would be an improvement.

**Comment by varunnvs92** [comment]
I am glad you figured out the issue. 

> Have you considered adding additional non-varargs methods that take Iterable...

The classes in SDK are already verbose with builders and Consumer methods. We don't want to add more overloaded methods unless required. If this gets reported by more customers, we can revisit the decision.
