### ISSUE TITLE
S3 GetObjectResponse.eTag() is returning a String within a String

### ISSUE THREAD

**Issue by lbarry** [aws/aws-sdk-java-v2#1417]
When getting the response value for eTag from the GetObjectResponse, it is returning an embedded string. I.E.:

eTag = ""352b49bca53a81ddd8ab25e0f9b431d9""

## Expected Behavior
Is should just return a String. I.E.

eTag = "352b49bca53a81ddd8ab25e0f9b431d9"

* AWS Java SDK version used: 2.8.1
* JDK version used: 1.8.0_192
* Operating System and version: varies

**Comment by debora-ito** [comment]
Hi @lbarry, the ETag value is enclosed in double-quotes because it follows the specification - https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.19

According to the specs, the ETag is a quoted string or `W/` followed by a quoted string.

**Comment by debora-ito** [comment]
Closing this. Feel free to reopen if you have any other question.

**Comment by imtdeepak** [comment]
Use EntityTag
`String eTag = EntityTag.valueOf(putObjectResponse.eTag()).getValue();`

**Comment by DVader666** [comment]
If the ETag should be quoted by the mentioned spec then why PutObjectResponse's eTag() method returns the String without the quotes?

<groupId>software.amazon.awssdk</groupId>
<artifactId>s3</artifactId>
<version>2.13.20</version>
