### ISSUE TITLE
software.amazon.awssdk.http.SdkHttpService error for modular project

### ISSUE THREAD

**Issue by adityasrini** [aws/aws-sdk-java-v2#1429]
## Expected Behavior

The app starts and runs.

## Current Behavior

A stacktrace is produced and the app crashes.

## Possible Solution
The `S3Client` seems to be the problematic piece of code here.

## Steps to Reproduce (for bugs)

- Create a modular project
- Create a jlinked image (Using the [badass plugin](https://badass-jlink-plugin.beryx.org/releases/latest/))
- run `./build/image/bin/hello`

Full code here:
https://github.com/adityasrini/modular-hello

Stacktrace here:
https://gist.github.com/adityasrini/780d73126863cbecea9fd524151f9df6

## Context

This is in the context of building a modularized java application. I am using jlink to generate the modularized app through Gradle and the Badass plugin. This seems to be the only project causing this issue as can be seen in the exception that's thrown when only the `S3Client` is initialized with dummy credentials.

## Your Environment
* AWS Java SDK version used: 2.8.1
* JDK version used: 12.0.2
* Operating System and version: macOS 10.14.6

**Comment by zoewangg** [comment]
You might need to explicitly adding http client because by default, the SDK will try to detect the http client from the class path if it is not specified, and it might not work for module path.

```java
S3AsyncClient.builder()
                        .region(Region.US_WEST_2)
                        .httpClientBuilder(NettyNioAsyncHttpClient.builder())
                        .credentialsProvider(CREDENTIALS_PROVIDER_CHAIN)
                        .build();
```

Here is the sample code to use the SDK via module path: https://github.com/aws/aws-sdk-java-v2/tree/master/test/module-path-tests

**Comment by adityasrini** [comment]
@zoewangg It worked! Documentation specifying how modular Java should be configured would be helpful.
