### ISSUE TITLE
Improved client side introspection of the SDK

### ISSUE THREAD

**Issue by dagnir** [aws/aws-sdk-java-v2#143]
This is somewhat related to #23. We've talked in the past about providing better debugging/introspection capabilities in the SDK, and this would be a great time to implement them. Not sure exactly what the scope or features are, but some ideas include showing (e.g. via JMX) the effective client configuration(s), number of active connections, number of threads spawned, etc.

**Comment by dagnir** [comment]
Related v1 request: https://github.com/aws/aws-sdk-java/issues/1289

**Comment by millems** [comment]
Tracking as part of #23
