### ISSUE TITLE
Netty Client Does Not Support Proxy Authentication

### ISSUE THREAD

**Issue by bsamartins** [aws/aws-sdk-java-v2#1432]
Netty client does not support proxy authentication.
Attempted to prefix credentials in proxy host but that it is not supported.

This makes the SDK nearly impossible to use from dev environments behind company proxies.

https://github.com/aws/aws-sdk-java-v2/blob/9a9a8717a9d8bebca27f561bda0733326c2c73ad/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/AwaitCloseChannelPoolMap.java#L213-L219

**Comment by bsamartins** [comment]
Is this issue open to PR?

**Comment by fazizyan** [comment]
@dagnir  do you have an ETA on this feature ?

**Comment by guillepb10** [comment]
Hi, a few days ago I've open a new PR with this feature. https://github.com/aws/aws-sdk-java-v2/pull/2517
Althought I've not received any feedback about it

**Comment by debora-ito** [comment]
@guillepb10 I'm sorry for the delay in response, I'll take an initial look.

**Comment by guillepb10** [comment]
Thanks @debora-ito for your reply. Do you have any idea of when I could get any feedback about PR?
