### ISSUE TITLE
Downloading files from s3 - GetObjectRequest

### ISSUE THREAD

**Issue by rachitpant** [aws/aws-sdk-java-v2#1437]
## Expected Behavior
Being able to send a file stored in S3 object back without transforming it to a file on the application server.

## Current Behavior
Returned S3 ResponseInputStream results in a file with size greater than the actual uploaded file.

## Code that I tried.
Here is the code to fetch from AWS.

    public ResponseInputStream<GetObjectResponse> downloadFile(String key){
    
    
         return s3client.getObject(GetObjectRequest.builder().bucket(bucketName).key(key).build(),ResponseTransformer.toInputStream());

    }

And here is the spring boot controller that is trying to send this response stream back.

```
       @RequestMapping(path = "/download", method = GET)
        public ResponseEntity<Resource> downloadOld(@RequestParam String key, Authentication authentication) throws IOException {
            ResponseInputStream<GetObjectResponse> responseStream = this.amazonClient.downloadFile(key);
            InputStreamResource resource = new InputStreamResource(responseStream);
            HttpHeaders headers = new HttpHeaders(); 

           //responseStream.response().contentDisposition() is null ??
            headers.add(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=\"" + key.substring(key.lastIndexOf('/') + 1) + "\"");
            return ResponseEntity.ok()
                    .headers(headers)
                    .contentLength(responseStream.response().contentLength())
                    .contentType(MediaType.parseMediaType(responseStream.response().contentType()))
                    .body(resource);
        }
```

I have partial sucess this controller, the axios response.data does have a response. And text files do download correctly , However when the content type is anything other than plain text ( eg application/pdf etc ) , the size of the downloaded file is 1.5 times the original file size. And needless to saw it is corrupted. ( pdf / zip / png ) nothing would open in my app ( cordova app ).

What am I doing wrong. When I look at the [GetObjectResponse](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/GetObjectResponse.html) Javadocs , I see that there are methods to get different metadata associated with the object , but not the actual object itself. Is that the reason why the returned file size is more ( actual object + metadata > actual object ). But then why does the above code work for plain text. **I couldn't find an example on the aws blog on how to achieve this.** 

I tried a few more things ( [stackoverflow](https://stackoverflow.com/questions/58106581/download-large-files-through-s3-java-sdk-2-without-writing-to-server) ) but nothing worked. When we decided to use S3, I convinced everyone to use the newer sdk because it seems to have better support to asynchrounously download , but havent been able to get anything working other than saving file to the application server using `ResponseTransformer.toFile(..)`

## Context
I am trying to download a large file from S3 without downloading it on the application server. Couldn't find an example on the aws blog , so I played around with the sdk (v2)  , but nothing worked.

## Your Environment

* AWS Java SDK version used: 2.7.22
* JDK version used: 1.8.0_211
* Operating System and version: Mac Os 10.14.5
* Application server env.: Spring Boot. 2.0 , spring core; 5.0.9

**Comment by rachitpant** [comment]
I tried `client.getObjectAsBytes` and the same filesizse increase  issue happens , but when I save the `ResponseBytes` to a file on the server , it saves fine. That means the issue has something to do with how I am returning the inputStream back to the client through spring.

**Comment by rachitpant** [comment]
For anyone else landing here, the above code works fine, the only change I had to make was add responseType: Blob in the axios request. Without that `response.data` was the entire http response , including header and anything else , which was the reason for the 1.5 times files size.

**Comment by peter-ponzel** [comment]
@rachitpant so this ticket can be closed ?

**Comment by rachitpant** [comment]
Yeah it can be closed. Before closing, can you tell me more about ‘GetResponse’ . What exactly does it hold ( Both object and its metadata ) . Is there a way to get just the object contents from it. In SdK v1 there were methods to get object contents.

**Comment by zoewangg** [comment]
@rachitpant Apologies for the late response. Just to clarify, are you asking what s3 `ResponseInputStream` holds? 

Basically, it's just a decorator of `InputStream` which has a method to provide the `GetObjectResponse`.  `GetObjectResponse` contains the metadata and the raw httpResponse. (`SdkHttpResponse`).

Currently, `ResponseInputStream` does not expose the underlying inputstream and I can see how it would work for your use case. I'll discuss with my team and report back.
