### ISSUE TITLE
hard time to configure a bucket LifecycleRule using Java SDK

### ISSUE THREAD

**Issue by peter-ponzel** [aws/aws-sdk-java-v2#1438]
Hello,
can someone please give me a helping hand to understand how to properly use `putBucketLifecycleConfiguration(...)` 
I'm fairly new to aws-sdk-java and s3 so I guess I'm missing something.
I want to create a `LifecycleRule` that cleans up failed/aborted multipart uploads after one day.
Here is what I tried
```java
final PutBucketLifecycleConfigurationRequest lifecycleConfigurationRequest = PutBucketLifecycleConfigurationRequest.builder()
                .bucket("some_bucket")
                .lifecycleConfiguration(BucketLifecycleConfiguration.builder()
                        .rules(LifecycleRule.builder()
                                .status(ExpirationStatus.ENABLED)
                                .id("abort_incomplete_uploads")
                                .abortIncompleteMultipartUpload(AbortIncompleteMultipartUpload.builder()
                                        .daysAfterInitiation(1)
                                        .build())
                                .build())
                        .build())
                .build();

return client.putBucketLifecycleConfiguration(lifecycleConfigurationRequest);
```
according to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-lifecycleconfig-rule.html this should be enough.. but I always get
```
Internal Server Error: The XML you provided was not well-formed or did not validate against our published schema (Service: S3, Status Code: 400, Request ID: ....)
```
Any hint or help is very much appreciated, thank you.

I've been trying `software.amazon.awssdk:aws-sdk-java` and `software.amazon.awssdk:s3` both in version `2.9.2` and `2.9.5`

Best Regards,
Peter

**Comment by debora-ito** [comment]
Transferred issue to the Java V2 repo.

@peter-ponzel according to the [Lifecycle Configuration Elements docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/intro-lifecycle-rules.html), each rule consists of an ID, a status, a filter and one or more elements to describe Lifecycle Actions. Your lifecycle rule is missing a filter:
> You can specify an empty filter, in which case the rule applies to all objects in the bucket.

So if you add an empty prefix to the `LifecycleRule` this error should go away.

**Comment by peter-ponzel** [comment]
thank you very much, now it works
