### ISSUE TITLE
Copy objects between S3 buckets - Specific version (Like SDK 1)

### ISSUE THREAD

**Issue by mani100101** [aws/aws-sdk-java-v2#1452]
## Current Behavior
In the original SDK, there is a support to copy only the specific version of a object from source to destination.

`new CopyObjectRequest(sourceBucketName, sourceKey, sourceVersionId, destinationBucketName, destinationKey)`

In SDK2, support for copying an object of specific version is removed. 

## Expected Behavior
`CopyObjectRequest.Builder` should have methods like `sourceVersionId(sourceVersionId)` to copy a specific version of the object.

## Context
Need to copy or move a specific version of object between buckets instead of duplicating all versions of the object.

**Comment by zoewangg** [comment]
Hi @mani100101, you can pass the version in `copySource`, something like the following: `bucket/key/?versionId=1` 

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CopyObjectRequest.Builder.html#copySource-java.lang.String-

**Comment by mani100101** [comment]
@zoewangg, thanks for helping out. It would be great if the same is captured in doc as well.

Anyways, will check and close the issue.

**Comment by debora-ito** [comment]
@mani100101 Thank you for your feedback, I've forwarded it to our documentation team.

Please feel free to reopen this if you have any further questions.

**Comment by Bennett-Lynch** [comment]
Hi @mani100101. Please take a look at the new copy source support introduced by https://github.com/aws/aws-sdk-java-v2/pull/2612 and let me know if this helps satisfy your use case.
