### ISSUE TITLE
Missing ECS artifacts

### ISSUE THREAD

**Issue by IkeOTL** [aws/aws-sdk-java-v2#1464]
I cannot find the ECS module artifacts in https://search.maven.org/search?q=g:software.amazon.awssdk.

Is the ECS module ready for use?

**Comment by debora-ito** [comment]
https://search.maven.org/search?q=g:software.amazon.awssdk%20a:ecs

Is this the one you're looking for?

**Comment by IkeOTL** [comment]
Yep that was it. I must be blind... Thanks a lot!!
