### ISSUE TITLE
HTTP Host header not set with Netty/Native Java implementations

### ISSUE THREAD

**Issue by sworisbreathing** [aws/aws-sdk-java-v2#1467]
Originally reported in #429. Also reported at https://github.com/findify/s3mock/issues/147. Per my investigation on that ticket, it [appears to be a bug in the AWS SDK v2](https://github.com/findify/s3mock/issues/147#issuecomment-540371087), not in s3mock.

## Expected Behavior
All HTTP client implementations should implicitly set the Host header when communicating via HTTP 1.1 (this is a mandatory header)

## Current Behavior
Only the Apache implementation sets this header

## Possible Solution
1. Implicitly set the host header in netty-nio-client and url-connection-client, and/or
1. Implicitly set the host header in SdkHttpRequest

## Steps to Reproduce (for bugs)
1. Follow the instructions in the SDK documentation for setting up the Netty Client
1. Enable request logging (or configure it to go through a logging proxy such as charles proxy)
1. Observe the missing Host headers

## Context
I have an app that was originally developed against the v1 SDK, which has automated integration tests that use https://github.com/findify/s3mock. After switching to the v2 sdk I observed the same issue reported in https://github.com/findify/s3mock/issues/147. Stepping through the code in a debugger session I could see my app was using the Netty implementation. Digging through the code I was able to find that the Apache implementation sets the host header but Netty and UrlConnection do not.

## Your Environment
* AWS Java SDK version used: 2.9.15 (however the issue still exists in 2.9.17)
* JDK version used: OpenJDK 12
* Operating System and version: Windows 10

**Comment by dagnir** [comment]
Closed by #1500.
