### ISSUE TITLE
S3Client can not get range bytes of object.

### ISSUE THREAD

**Issue by zhongyiio** [aws/aws-sdk-java-v2#1472]
## Expected Behavior
Get first 500 bytes of s3 object

## Current Behavior
Get all bytes of s3 object.

## Steps to Reproduce (for bugs)
```java
var rangeGetObjectRequest = GetObjectRequest.builder().range("0-499").bucket(bucket).key(key).build();
var response = this.s3Client.getObject(rangeGetObjectRequest);
```

## Your Environment

* AWS Java SDK version used: 2.9.17
* JDK version used: openjdk version "11.0.2" 2019-01-15
* Operating System and version: macOS 10.15

**Comment by debora-ito** [comment]
@zhongyiio the range field needs to be prefixed with "bytes=" (e.g. `bytes=0-499`), this is according to the Range header [spec](http://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.35) linked in the range field [documentation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/GetObjectRequest.html#range--).

So in your example we would have
```java
var rangeGetObjectRequest = GetObjectRequest.builder().range("bytes=0-499").bucket(bucket).key(key).build();
```

**Comment by zhongyiio** [comment]
@debora-ito thanks
