### ISSUE TITLE
ProcessCredentialsProvider default processOutputLimit is too low

### ISSUE THREAD

**Issue by RhodesBrownAmazon** [aws/aws-sdk-java-v2#1490]
ProcessCredentialsProvider.Builder uses a default value for processOutputLimit that is too restrictive when the command generates session credentials with a long session token.
Because the default is too small, uses in, for example aws-toolkit-jetbrains won't work.

## Expected Behavior

By default, allow at least 2048 bytes of output from a credentials generating command.

## Current Behavior

When using builder default, ProcessCredentialsProvider.resolveCredentials() throws an exception for command input with, say, 1200b of JSON including the session token.

## Possible Solution

Just raise the default value to, say, 2048 bytes. Or, whatever would be a reasonable limit for credentials JSON that include session tokens as per https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

## Steps to Reproduce (for bugs)

def provider = ProcessCredentialsProvider.builder()
  .command('<generate JSON with more than 1024b of JSON, including session token>')
  .build()
  .resolveCredentials()

## Context

I cannot use the JetBrains AWS Toolkit plugin for IntelliJ with command-generated credentials that include a long session token.

Note that the session credentials are coming from Amazon's Conduit system, if that provides any useful insight as to why the session tokens are large enough to break the default.

## Your Environment

* AWS Java SDK version: The limit is clearly apparent in the source for 2.10.3-SNAPSHOT (https://github.com/aws/aws-sdk-java-v2/blob/master/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/ProcessCredentialsProvider.java#L225)

**Comment by zoewangg** [comment]
Seems reasonable. Would you like to create a PR? :)

**Comment by RhodesBrownAmazon** [comment]
Members of the https://github.com/aws/aws-toolkit-jetbrains project pointed me to  https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html which suggests the default should be much larger. Should the limit be more like 32KB or 64KB to provide plenty of overhead for STS changes, while still capping a rogue command?

**Comment by zoewangg** [comment]
64KB sounds good to me. @millems any concerns?

**Comment by millems** [comment]
:shipit:

**Comment by zoewangg** [comment]
Closed via #1517
