### ISSUE TITLE
AmazonSQS sqs =  AmazonSQSClientBuilder.defaultClient()  NoSuchFieldError

### ISSUE THREAD

**Issue by Sajeenthiran** [aws/aws-sdk-java-v2#1497]
Android connect with AWS SQS java sdk issue
`AmazonSQS sqs =  AmazonSQSClientBuilder.defaultClient() `

java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar:classes2.dex)

**Comment by zoewangg** [comment]
Are you using AWS Java SDK v2 on Andriod? The SDK does not support that use case unfortunately.

We have a designated mobile SDK you can use. https://docs.aws.amazon.com/sdk-for-android/index.html

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen if you have further questions.
