### ISSUE TITLE
BUILD FAILURE - AWS SDK for Java 2.0 

### ISSUE THREAD

**Issue by jtheanalytica** [aws/aws-sdk-java-v2#1499]
BUILD FAILURE - AWS SDK for Java 2.0 

## Expected Behavior

Build Succeeded

## Current Behavior

Build Failure

## Context

Hello everyone.
I have followed the instructions - in the "Compiling the SDK" section- in the following link:
https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/setup-install.html

I used the command:  mvn clean install

I got "Build Failure".

## Your Environment

* AWS Java SDK version used: V2
* JDK version used: jdk1.8.0_221
* Operating System and version: Oracle Virtual Machine. Host and Guest both Win10 Ent.

**Comment by jtheanalytica** [comment]
I've attached here three txt files:
mvn.clean.install.txt - contains the output after running the command: mvn clean install.
mvn.-e.txt - running the command: mvn -e
mvn.-X.txt : running the command: mvn -X

[mvn clean install.txt](https://github.com/aws/aws-sdk-java-v2/files/3810412/mvn.clean.install.txt)
[mvn -e.txt](https://github.com/aws/aws-sdk-java-v2/files/3810413/mvn.-e.txt)
[mvn -X.txt](https://github.com/aws/aws-sdk-java-v2/files/3810414/mvn.-X.txt)

**Comment by zoewangg** [comment]
There is a known issue with the SDK building on Windows. tracking in  #986

You can still build the SDK by skipping the tests. 

`mvn clean install -P quick`

**Comment by jtheanalytica** [comment]
Thank yoo @zoewangg. 
That worked!

However running the following command: mvn javadoc:javadoc 
gives "Build Failure" (See attached txt file). 

Thanks

[mvn javadoc javadoc.txt](https://github.com/aws/aws-sdk-java-v2/files/3812511/mvn.javadoc.javadoc.txt)
