### ISSUE TITLE
BUILD FAILURE- AWS Rekognition and SDK for JAVA 2.0

### ISSUE THREAD

**Issue by jtheanalytica** [aws/aws-sdk-java-v2#1503]
## Expected Behavior

Build Success. 

## Current Behavior

BUILD FAILURE
## Steps to Reproduce (for bugs)

Hi:
I followed the instructions in https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/setup-project-maven.html
Step1) Create a New Maven Package
mvn archetype:generate -DgroupId=org.myjavasdk01.example01 -DartifactId=myjavasdk01 -DarchetypeArtifactId=maven-archetype-quickstart -DinteractiveMode=false

step2) I added the following to POM file created above:
<build>
  <plugins>
    <plugin>
      <groupId>org.apache.maven.plugins</groupId>
      <artifactId>maven-compiler-plugin</artifactId>
      <configuration>
         <source>1.8</source>
         <target>1.8</target>
      </configuration>
    </plugin>
  </plugins>
</build>

Step3) Configure the SDK as a Maven Dependency
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>bom</artifactId>
      <version>2.10.9</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

Step4)     
<dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-json-protocol</artifactId>
            <version>2.10.9</version>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>protocol-core</artifactId>
            <version>2.10.9</version>
        </dependency>
</dependencies>

Step5) I want - for example perform the List operation in the following link:
https://docs.aws.amazon.com/rekognition/latest/dg/list-collection-procedure.html

So I first delete the "App" class and create a new one and name it: ListCollections and add the following to it:
 
package org.myjavasdk01.example01;

import java.util.List;
import com.amazonaws.services.rekognition.AmazonRekognition;
import com.amazonaws.services.rekognition.AmazonRekognitionClientBuilder;
import com.amazonaws.services.rekognition.model.ListCollectionsRequest;
import com.amazonaws.services.rekognition.model.ListCollectionsResult;

public class ListCollections {

   public static void main(String[] args) throws Exception {

      AmazonRekognition amazonRekognition = AmazonRekognitionClientBuilder.defaultClient();
 

      System.out.println("Listing collections");
      int limit = 10;
      ListCollectionsResult listCollectionsResult = null;
      String paginationToken = null;
      do {
         if (listCollectionsResult != null) {
            paginationToken = listCollectionsResult.getNextToken();
         }
         ListCollectionsRequest listCollectionsRequest = new ListCollectionsRequest()
                 .withMaxResults(limit)
                 .withNextToken(paginationToken);
         listCollectionsResult=amazonRekognition.listCollections(listCollectionsRequest);
         
         List < String > collectionIds = listCollectionsResult.getCollectionIds();
         for (String resultId: collectionIds) {
            System.out.println(resultId);
         }
      } while (listCollectionsResult != null && listCollectionsResult.getNextToken() !=
         null);
     
   } 
}

Step6)
Save everything and from cmd I run mvn package

I get the following output:

[INFO] Scanning for projects...
[WARNING]
[WARNING] Some problems were encountered while building the effective model for org.myjavasdk01.example01:myjavasdk01:jar:1.0-SNAPSHOT
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 13, column 15
[WARNING]
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING]
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING]
[INFO]
[INFO] ---------------< org.myjavasdk01.example01:myjavasdk01 >----------------
[INFO] Building myjavasdk01 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ myjavasdk01 ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ myjavasdk01 ---
[WARNING] Using platform encoding (Cp1252 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] skip non existing resourceDirectory C:\Users\IEUser\awsProjects\myjavasdk01\src\main\resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ myjavasdk01 ---
[INFO] Changes detected - recompiling the module!
[WARNING] File encoding has not been set, using platform encoding Cp1252, i.e. build is platform dependent!
[INFO] Compiling 1 source file to C:\Users\IEUser\awsProjects\myjavasdk01\target\classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[4,42] package com.amazonaws.services.rekognition does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[5,42] package com.amazonaws.services.rekognition does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[6,48] package com.amazonaws.services.rekognition.model does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[7,48] package com.amazonaws.services.rekognition.model does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[14,9] cannot find symbol
  symbol:   class AmazonRekognition
  location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[14,47] cannot find symbol
  symbol:   variable AmazonRekognitionClientBuilder
  location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[19,9] cannot find symbol
  symbol:   class ListCollectionsResult
  location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[25,13] cannot find symbol
  symbol:   class ListCollectionsRequest
  location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[25,65] cannot find symbol
  symbol:   class ListCollectionsRequest
  location: class org.myjavasdk01.example01.ListCollections
[INFO] 9 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.265 s
[INFO] Finished at: 2019-11-07T06:52:30-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project myjavasdk01: Compilation failure: Compilation failure:
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[4,42] package com.amazonaws.services.rekognition does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[5,42] package com.amazonaws.services.rekognition does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[6,48] package com.amazonaws.services.rekognition.model does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[7,48] package com.amazonaws.services.rekognition.model does not exist
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[14,9] cannot find symbol
[ERROR]   symbol:   class AmazonRekognition
[ERROR]   location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[14,47] cannot find symbol
[ERROR]   symbol:   variable AmazonRekognitionClientBuilder
[ERROR]   location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[19,9] cannot find symbol
[ERROR]   symbol:   class ListCollectionsResult
[ERROR]   location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[25,13] cannot find symbol
[ERROR]   symbol:   class ListCollectionsRequest
[ERROR]   location: class org.myjavasdk01.example01.ListCollections
[ERROR] /C:/Users/IEUser/awsProjects/myjavasdk01/src/main/java/org/myjavasdk01/example01/ListCollections.java:[25,65] cannot find symbol
[ERROR]   symbol:   class ListCollectionsRequest
[ERROR]   location: class org.myjavasdk01.example01.ListCollections
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

C:\Users\IEUser\awsProjects\myjavasdk01>

## Context

I'm trying to follow along with Amazon Rekognition using JAVA. 

## Your Environment

* AWS Java SDK version used: V2
* JDK version used: 1.8
* Operating System and version: Oracle VM: Host and Guest both are Win10  Ent.

Thanks

**Comment by zoewangg** [comment]
Hi @jtheanalytica, the sample code you were using is actually using v1 client. V2 client has differnet APIs and it also supports auto pagination so you don't need to write your own pagination function.

```
        RekognitionClient client = RekognitionClient.create();

        client.listCollectionsPaginator().forEach(b -> System.out.println(b.collectionIds()));

```

**Comment by jtheanalytica** [comment]
Hi @zoewangg. 
Thank you.
Please let me know where I can find the full sample codes that work with V2 - for ListCollections and other operations pertaining to Rekognition. As it seems all the other codes listed there in he link (https://docs.aws.amazon.com/rekognition/latest/dg/programming.html) are for V1! 

Thanks

**Comment by zoewangg** [comment]
I'd recommend submitting feedback for adding Java SDK v2 sample code through that page you linked. (the feedback button in the bottom)

**Comment by jtheanalytica** [comment]
Sure thing. Thank you @zoewangg.
