### ISSUE TITLE
No SocketTimeoutException with ApacheHttpClient

### ISSUE THREAD

**Issue by MarkusKramer** [aws/aws-sdk-java-v2#1505]
When uploading objects to S3 I've noticed that I don't get a SocketTimeoutException when the network is gone. I’ve investigate this a bit and there seems to be an issue with the SDK’s ApacheHttpClient.

The issue can be reproduced with this code. It uploads a 100MB object. Once the upload starts disable your network connection. The expected behavior is to get a SocketTimeoutException but it just keeps running.

```java
import org.junit.jupiter.api.Test;
import software.amazon.awssdk.awscore.presigner.PresignedRequest;
import software.amazon.awssdk.http.ContentStreamProvider;
import software.amazon.awssdk.http.HttpExecuteRequest;
import software.amazon.awssdk.http.HttpExecuteResponse;
import software.amazon.awssdk.http.SdkHttpClient;
import software.amazon.awssdk.http.apache.ApacheHttpClient;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;
import software.amazon.awssdk.services.s3.presigner.S3Presigner;
import software.amazon.awssdk.services.s3.presigner.model.PutObjectPresignRequest;

import java.io.IOException;
import java.io.InputStream;
import java.time.Duration;

import static org.junit.jupiter.api.Assertions.assertTrue;

public class SocketTimeoutTest {

    @Test
    public void uploadSomethingBig() throws IOException {
        String bucketName = "somebucket";
        String key = "uploadtest";

        S3Presigner presigner = S3Presigner.create();
        PresignedRequest presignedRequest = presigner.presignPutObject(PutObjectPresignRequest.builder()
                .putObjectRequest(PutObjectRequest.builder().bucket(bucketName).key(key).build())
                .signatureDuration(Duration.ofMinutes(60))
                .build());

        SdkHttpClient httpClient = ApacheHttpClient.builder()
                .connectionTimeout(Duration.ofSeconds(5))
                .socketTimeout(Duration.ofSeconds(5))
                .build();

        ContentStreamProvider contentToUpload = () -> new InputStream() {
            int contentSize = 100 * 1024 * 1024;
            int deliveredBytes = 0;

            @Override
            public int read() throws IOException {
                return deliveredBytes++ < contentSize ? 0 : -1;
            }
        };

        HttpExecuteRequest uploadRequest = HttpExecuteRequest.builder()
                .request(presignedRequest.httpRequest())
                .contentStreamProvider(contentToUpload)
                .build();

        HttpExecuteResponse response = httpClient.prepareRequest(uploadRequest).call();
        assertTrue(response.httpResponse().isSuccessful());
    }

}
```

Using the apache http client directly gives the expected exception.

Reproduced with AWS SDK 2.7.5 and 2.10.12. Java version 11.0.4.

**Comment by debora-ito** [comment]
Hi @MarkusKramer apologies for the long silence on this issue, I'm investigating it now.

Let me know if you got any new findings or if you are not seeing this anymore.

**Comment by debora-ito** [comment]
Here I am, months after my last comment, I'm sorry for the delayed response.

I'm able to see this same behavior, here's what I found out based on the logs of my local tests:

1-  The socket factory starts a handshake and a secure connection is established
2- The PUT request is sent; the service responds with `100 Continue`, meaning the client can continue by sending the remainder of the request
```
>> "PUT /uploadtest?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210818T221742Z&X-Amz-SignedHeaders=host&X-Amz-Expires=3600&X-Amz-Credential=XXX%2F20210818%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=XYZ HTTP/1.1[\r][\n]"
>> "Host: somebucket.s3.us-west-2.amazonaws.com[\r][\n]"
>> "Expect: 100-continue[\r][\n]"
>> "Content-Length: 3145728[\r][\n]"
>> "Connection: Keep-Alive[\r][\n]"
>> "User-Agent: [\r][\n]"
>> "[\r][\n]"
<< "HTTP/1.1 100 Continue[\r][\n]"
<< "[\r][\n]"
```

3- Next, the object start to be uploaded. After this, I disable the network connection, and no exception is thrown until the whole object is sent. 
4- When the upload is finished, an error is thrown: `javax.net.ssl.SSLException: Broken pipe (Write failed)`.

This is expected behavior for a blocking connection protocol. Even if the server did send some response right after the network connection was disabled, the client would not get it until the outgoing request has finished being sent.

Let me know if this makes sense.

**Comment by MarkusKramer** [comment]
Thanks for investigating! Being blocked indefinitely is the expected behavior? When you're looking at any other software, uploads usually fail if the connection goes away.
Could this be solved with the async client?

**Comment by debora-ito** [comment]
> Could this be solved with the async client?

In theory yes, I'll work on an async example.

**Comment by debora-ito** [comment]
@MarkusKramer Do you still need the example? 

It's 2024 and I'm going through the list of old open issues.
Let me know if this is still pending, otherwise it'll autoclose.
