### ISSUE TITLE
Support for Amazon Incentives API (AGCOD)

### ISSUE THREAD

**Issue by MattFromGer** [aws/aws-sdk-java-v2#1508]
Hey guys,
I need to use the Amazon Incentives API or Amazon Gift Card on Demand (AGCOD) API ([Link](https://developer.amazon.com/apps-and-games/incentives-api), [Spec](http://s3.amazonaws.com/AGCOD/tech_spec/AGCODTechSpec_WC-FAQ-Appendix_EN.pdf)). The service is not yet supported in v2.

Ideally the result will be similar to the following code:

        AgcodClient client = AgcodClient.builder()
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("akid", "skid")))
                .region(Region.US_EAST_1)
                .build();

        CreateGiftCardResponse response = client.createGiftCard(CreateGiftCardRequest.builder()
                .creationRequestId("123")
                .partnerId("1234")
                .value(Value.builder()
                        .amount(10)
                        .currencyCode("USD")
                        .build())
                .build());

I could try to implement it and open a PR, but it will be WIP, because I'll probably need some guidance. Or should I do my own lib? What do you think?

**Comment by klaytaybai** [comment]
Hi @MattFromGer, thanks for the interest in this feature.  Unfortunately for your use case, this SDK is only for Amazon Web Services APIs.  Amazon Incentives does not fall under AWS, so we cannot add this in at this time.  Please contact Amazon Incentives at https://www.amazon-incentives.com/api/contact-us to learn more about next steps for your use case.
