### ISSUE TITLE
Async S3 object reading

### ISSUE THREAD

**Issue by yaitskov** [aws/aws-sdk-java-v2#1521]
Async S3 gets whole file. What if the file is too big.
I would like to see way to pass a callback to consume byte buffers (NIO) 

## Your Environment

* AWS Java SDK version used: 
* JDK version used:
* Operating System and version:

**Comment by KaibaLopez** [comment]
Hi @yaitskov , 
I recommend using transfer manager for that kind of oprations. See [here](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-s3-transfermanager.html) for more information.

**Comment by zoewangg** [comment]
Hi @yaitskov, you can create your own `AsyncResponseTransfermer` to consume the object.

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3AsyncClient.html#getObject-software.amazon.awssdk.services.s3.model.GetObjectRequest-software.amazon.awssdk.core.async.AsyncResponseTransformer-

Sample code: 
https://github.com/aws/aws-sdk-java-v2/blob/66a166394f4999fc0047b4b1a23376a8b40db046/services/s3/src/it/java/software/amazon/awssdk/services/s3/GetObjectAsyncIntegrationTest.java#L104
