### ISSUE TITLE
Retry execution for asynchronous client

### ISSUE THREAD

**Issue by timbaer** [aws/aws-sdk-java-v2#1526]
Hi there,

I need your guidance: I'm trying to setup a retry mechanism for my asynchronous DynamoDb client. However, I don't see any retries taking place for a failed request. When I debug the sdk code, I see that `AsyncRetryableStage.java:114` is calling "isDone()" on the target completableFuture and returns immediately, instead of retrying the execution. The reason for this is, that the completableFuture does have the exception already set as "result" AltResult(SomeException). 

Now, I'm asking myself if this is the desired behavior? Am I missing something? It would also be very helpful if some documentation could be added for setting up retries.

My client config looks like this:

```

DynamoDbAsyncClient.builder()
            .region(Region.EU_WEST_1)
            .httpClientBuilder(NettyNioAsyncHttpClient.builder()
                .maxConcurrency(dynamoDbProperties.getMaxConnections())
                .maxPendingConnectionAcquires(10_000)
            )
            .asyncConfiguration(b -> b.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR, executor))
            .overrideConfiguration(ClientOverrideConfiguration.builder()
                .apiCallTimeout(Duration.ofMillis(dynamoDbProperties.getClientTimeoutMillis()))
                .apiCallAttemptTimeout(Duration.ofSeconds(10))
                .retryPolicy(RetryPolicy.builder()
                    .numRetries(dynamoDbProperties.getNumRetries())
                    .backoffStrategy(
                      
 FixedDelayBackoffStrategy.create(Duration.of(dynamoDbProperties.getRetryBackoffMillis(), ChronoUnit.MILLIS))
                    )
                    .throttlingBackoffStrategy(BackoffStrategy.none())
                    .retryCondition(RetryCondition.defaultRetryCondition())
                    .build()
                ).build()
            )
            .build();
```

The api-call looks like this:

`dynamoDBAsync.getItem(getItemRequest)`

Any help/guidance is highly appreciated

Regards,

Stefan

* AWS Java SDK version used: implementation platform("software.amazon.awssdk:bom:2.10.24")
* JDK version used: openjdk version "11.0.2" 2019-01-15
* Operating System and version: MacOS 10.13.6 (High Sierra)

**Comment by Scoppio** [comment]
If it worths anything, we also have this problem in our product where we want to add a retry in case it loses communication with the dynamoDB for any reason whatsoever (like during an auto-scaling process).

**Comment by asargsya** [comment]
you can try this

`
S3AsyncClient.builder()
               .overrideConfiguration(
                        ClientOverrideConfiguration.builder()
                        .retryPolicy(
                                RetryPolicy.builder()
                                        .backoffStrategy(BackoffStrategy.defaultStrategy())
                                        .throttlingBackoffStrategy(BackoffStrategy.defaultThrottlingStrategy())
                                        .numRetries(5)
                                        .retryCondition(RetryCondition.defaultRetryCondition())
                                        .build()
                        )
                        .apiCallTimeout(Duration.ofSeconds(120))
                        .build())
`
The API call attempt timeout is the amount of time to wait for the HTTP request to complete before timing out.

Hope this helps.

**Comment by aaoswal** [comment]
Hi @timbaer,
Have you tried using `BackoffStrategy.defaultThrottlingStrategy()` instead of `BackoffStratergy.none()` as it avoids retires within 1 millisecond.

Can you please confirm the following:
- `dynamoDbProperties.getNumRetries()` is not returning `0`?
- How are you checking the number of retries?
- Can you please also attach your stack-trace if you are still facing the issue?
