### ISSUE TITLE
AWS Batch ContainerDetail missing getLogStreamName() 

### ISSUE THREAD

**Issue by bchernicoff** [aws/aws-sdk-java-v2#153]
The Batch codegen for ContainerDetail and AttemptContainerDetail are missing getLogStreamName().
https://github.com/aws/aws-sdk-java-v2/blob/master/services/batch/src/main/resources/codegen-resources/service-2.json

This addition to Batch was announced here https://forums.aws.amazon.com/ann.jspa?annID=4908
and is present in the 1.11 SDK.

**Comment by spfink** [comment]
While releases for service updates to 1.11.x are automated and occur regularly, we have not yet finalized release automation for 2.0. We will have this by GA.

I can do a one-off update of Batch for you to master and we will continue to make progress towards automated updates for all services in 2.0
