### ISSUE TITLE
CONTRIBUTING.md references a non-existent aws-cla repo

### ISSUE THREAD

**Issue by filmaj** [aws/aws-sdk-java-v2#1536]
This section: https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md#code-contributions

References this repo: https://github.com/aws/aws-cla

Which 404s for me.

I am investigating contributing to this repository on behalf of my employer, so I need to understand the contribution requirements and terms of a CLA, if required. Could you please assist me in figuring that out?

**Comment by KaibaLopez** [comment]
Hi @filmaj ,
First, thanks for pointing this. I'll see about the cla.
As far as contributing goes, so long as the contribution is under a 100 lines of code, and is made under the terms of Apache 2.0  license (you'll notice that our PR template has a check box for you to agree to this) then there should be no problem.

**Comment by filmaj** [comment]
I have let the my colleague who wanted to contribute to this project know about the contribution size requirements. Worth noting that I think at this point they may not know for sure about  contribution size (often it is hard to gauge that until the solution / patch comes together). As such, I would appreciate more information on getting a full corporate CLA on file with AWS (if AWS requires it). I'd like to get that signed by The Right People on our end so that future Adobe engineers have their paths to contribution paved more completely.

Cheers!

**Comment by KaibaLopez** [comment]
makes sense, I'll look into it and update you as soon as I get more info.
