### ISSUE TITLE
Use Java 8 language features

### ISSUE THREAD

**Issue by jeffalder** [aws/aws-sdk-java-v2#1541]
## Expected Behavior
Since the SDK has a minimum Java 8 requirement, it should be using Java 8 language features.

## Current Behavior
The SDK code has [redundant type parameters](https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/main/java/software/amazon/awssdk/codegen/customization/processors/ShapeModifiersProcessor.java#L202), [comparisons replaceable with Objects.equals](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/ConfiguredS3SdkHttpRequest.java#L66), and others that are indicative of older Java language levels. 

## Possible Solution
I suggest using IntelliJ's tools to update the code style to leverage Java 8.

## Steps to Reproduce (for bugs)
n/a

## Context
If the code is going to build for a minimum of Java 8, then those available language features should be used throughout the code.
IntelliJ provides pretty good inspection tools. The results still need to be reviewed, but it's pretty easy to go through and fix a bunch of these.

## Your Environment
* JDK version used: 1.8

**Comment by zoewangg** [comment]
Thanks for reporting the issue. Would you like to submit a PR? :)

**Comment by jeffalder** [comment]
Sounds good. I've got two others stacked up (hasItem and S3 destination
bucket) so this will be next.

**Comment by jeffalder** [comment]
Sounds good. I've got two others stacked up (hasItem and S3 destination bucket) so this will be next.

**Comment by aristosh** [comment]
Yes, if you are targeting java8, the installation is breaking
