### ISSUE TITLE
Using RequestBody.fromInputStream only supports resettable InputStreams

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-sdk-java-v2#1544]
## Expected Behavior

Any valid `InputStream` implementation should work with `RequestBody.fromInputStream`

## Current Behavior

An `InputStream` that doesn't support mark/reset will throw an exception when calling `RequestBody.fromInputStream`.

## Possible Solution

The `fromInputStream` method optionally `mark`s the `InputStream` before wrapping it (e.g. it uses `software.amazon.awssdk.utils.IoUtils#markStreamWithMaxReadLimit` which is gated on `InputStream#markSupported`; however it then blindly calls `reset()` on every stream (regardless of whether it supports mark/reset). A possible solution would be to do similar gating on the reset as follows:

```
return fromContentProvider(() -> {
    if (inputStream.markSupported()) {
        invokeSafely(nonCloseable::reset);
    }
    return nonCloseable;
}, contentLength, Mimetype.MIMETYPE_OCTET_STREAM);
```

## Steps to Reproduce (for bugs)

```
val fis = Files.newInputStream(path)

val client = S3Client.create()

client.putObject(
    PutObjectRequest.builder().bucket("xxxxx").key("kjlhg").build(),
    RequestBody.fromInputStream(fis, path.size())
)
```

## Context

Trying to create a progress indicator for S3 uploads inside the AWS Toolkit for JetBrains (changing from File to InputStream so reads can be recorded).

## Your Environment

* AWS Java SDK version used: 2.10.20
* JDK version used: JDK8
* Operating System and version: Mac

**Comment by KaibaLopez** [comment]
Hi @kiiadi , 
thanks for pointing this and for the PR!
