### ISSUE TITLE
XMLStreamException during unmarshal of SendMessageResponse

### ISSUE THREAD

**Issue by Wogan** [aws/aws-sdk-java-v2#155]
See stack trace here https://gist.github.com/Wogan/b99d31fdcbdc25d91c9dcb8a5f99f787

The CompletableFuture returned from MakeAsyncHttpRequestStage.execute is never completed when this occurs, as MakeAsyncHttpRequestStage.ResponseHandler.complete doesn't catch handleReponse and just dies instead.

**Comment by Wogan** [comment]
Looks like the exception handling was fixed in https://github.com/aws/aws-sdk-java-v2/commit/ff791bd2e0868d4c190f3bfe713efb41889f2bef

Still not sure why the XML parsing problem is occuring though.

**Comment by spfink** [comment]
Are you getting XML parsing issues even with the latest build of master?

**Comment by Wogan** [comment]
With master I get a [completely different exception](https://gist.github.com/Wogan/bc40377814fc0b0ae5781f5f3bfd8661).

**Comment by Wogan** [comment]
Seems to work fine in preview-4 so I'm closing this.
