### ISSUE TITLE
DAX client

### ISSUE THREAD

**Issue by cmelean** [aws/aws-sdk-java-v2#1576]
Is there support for a DAX client wrapper. We were trying to use the DAX client but apparently that is still based on the legacy driver (v1), is there a way to "wrap" our v2 code with a DAX or any other way to use DAX?

thanks

**Comment by debora-ito** [comment]
Hi @cmelean we still don't have DAX support in V2, we are tracking the issue in #473. Feel free to add any comments and +1 on the issue.
