### ISSUE TITLE
GetBucketPolicy with async S3 client doesn't work

### ISSUE THREAD

**Issue by avgdorom** [aws/aws-sdk-java-v2#1577]
I'm trying to use the `S3AsyncClient` in order to get bucket policies from my AWS account.
I created a client, giving it the correct credentials and region, but I keep getting `null` in the content of the response.

Just to be sure that I initialized the client correctly, I tried other requests like, `getBucketPolicyStatus`, `listBuckets` and more. Every other request I tried returned the expected data, except for `getBucketPolicy`... In that case the response body is always null, which then causes an XML parsing error (I debugged until I came to `GetBucketPolicyInterceptor.modifyHttpResponseContent()`).

**NOTE**: For Exactly the same request, the S3 **sync** client works like a charm.

**Comment by debora-ito** [comment]
Transferred the issue to Java V2 repo.

**Comment by debora-ito** [comment]
@avgdorom thank you for reporting this, we'll investigate.

**Comment by avgdorom** [comment]
@bmaizels Thanks! This is great. One question though: how do I get the fix? Do I need to wait for the next Java SDK release? If so, when is that due?

**Comment by bmaizels** [comment]
This should be included with the 2.10.47 release on 1/10.

**Comment by avgdorom** [comment]
@bmaizels Thanks, but in that case, I don't think it works... Tried it again twice, with version 2.10.47, and it just doesn't work. I get exactly what I reported in the bug in the first place.
Can you please check?

**Comment by debora-ito** [comment]
@avgdorom actually it is available in today's release, version `2.10.48` - https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#21048-2020-01-13

Apologies for the confusion.

**Comment by bmaizels** [comment]
@avgdorom That was my fault, sorry about that confusion. I've retested it to be sure and I see broken in 2.10.47 and fixed in 2.10.48. Please let me know if you have any more problems with it.

**Comment by avgdorom** [comment]
@bmaizels It's fine, it happens 😄 Works like a charm now! thank you.
