### ISSUE TITLE
AsyncRequestProvider for Strings

### ISSUE THREAD

**Issue by SimplyAmuthan** [aws/aws-sdk-java-v2#159]
Hi ... is there a `AsyncRequestProvider` that stream from String, basically I would like to use the `S3AsyncClient` to put string object into s3
I only have option to write string into a file system and and upload from there using something like this `s3AsyncClient.putObject(putObjectRequest, AsyncRequestProvider.fromFile(Paths.get("myfile.json")))`
but I would like to have something like `s3AsyncClient.putObject(putObjectRequest, AsyncRequestProvider.fromObject(myOBject.toString))`

**Comment by millems** [comment]
+1: Support for `byte[]` would be nice! Having explicit `String` support would probably just be an alias for `toBytes(Charset)`, since we probably want people to specify the encoding explicitly.

**Comment by shorea** [comment]
Got a potential solution in PR

https://github.com/aws/aws-sdk-java-v2/pull/161/files

**Comment by shorea** [comment]
Merged into master.
