### ISSUE TITLE
Inconsistent behavior between ListObjects and ListObjectVersions APIs with respect to encoding key field

### ISSUE THREAD

**Issue by fmbz** [aws/aws-sdk-java-v2#1601]
## Expected Behavior
When encodingType of url is specified as a request parameter, with respect to the key field in Contents section of ListObjects (v1 + v2), and key fields in DeleteMarker and Versions sections of ListObjectVersions, either one of the following should be true:
1) They are all encoded after unmarshalling
2) They are all decoded after unmarshalling

## Current Behavior
What happens instead is that the key field is decoded in Contents section ListObjects apis (v1 + v2), but NOT the key field in neither DeleteMarker nor Versions section in ListObjectVersions apis.  This results in having to handle the unmarshalled response differently when using the different apis, even though they both have the same encoding-type request parameter.

## Possible Solution
In https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/internal/handlers/DecodeUrlEncodedResponseInterceptor.java#L51-L57, have another if block to check if the response is `instanceof` ListObjectVersionsResponse, and have corresponding `modifyListObjectVersionsResponse` method that does decoding on keys in the delete marker and versions sections.  This method should work similarly to `modifyListObjectsResponse`.  Also, it should decode the KeyMarker, NextKeyMarker, Prefix, and Delimiter fields as well.

## Steps to Reproduce (for bugs)
Send ListObjects request with encoding-type "url" request parameter and ensure that it returns results that have XML special characters in the key name.  Unmarshall into the Java object and when looking at the key field in the contents object, it is decoded.

Send ListObjectVersions request with encoding-type "url" request parameter and ensure that it returns results that have XML special characters in the key name.  Unmarshall into the Java object and when looking at the key field in the deleteMarkers or versions objects, it is still encoded.  (Same for KeyMarker, NextKeyMarker, etc as mentioned above)

## Context
Usage of ListObjects api and ListObjectVersions api (to ensure consistency between them)

## Your Environment

* AWS Java SDK version used: 2.9.10 (but I still see it in latest master version)
* JDK version used: Java 8
* Operating System and version: Mac OS Mojave.

Thanks!

**Comment by debora-ito** [comment]
Thank you for the detailed report @fmbz, it helped a lot in expediting the repro process.

I can confirm I'm seeing this, marking as a bug.

**Comment by zoewangg** [comment]
Fixed via #1630 and the fix has been released as part of `2.10.57` https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#21057-2020-02-04

**Comment by fmbz** [comment]
Great, thank you!
