### ISSUE TITLE
MDC Context coming as null 

### ISSUE THREAD

**Issue by polavishnu4444** [aws/aws-sdk-java-v2#1613]
When trying to contain the MDC context on thread switch it is being lost. 

I have a wrapper extending ExecutorService that works taking an executor. In that I have tried to copy and set the MDC context on function call to submit or execute and other ExecutorService functions. But when I see the value for MDC.getgetCopyOfContextMap() in the flow after SDK call I see the result as null.

I have overridden the executor using the advanceOption config of FUTURE_COMPLETION_EXECUTOR. 

## Expected Behavior
- To have the MDC context.

## Current Behavior
Getting null.

## Your Environment
* AWS Java SDK version used: 2.10.50
* JDK version used:11
* Operating System and version: Mac OS Mojave (version: 10.14.6)

**Comment by debora-ito** [comment]
Can you give more context on your use case, telling us how you are using the SDK, which services you're calling (a sample code would help) and why do you expect the MDC context map to be not null.

**Comment by debora-ito** [comment]
Closing this due to no response. Please feel free to reopen if you have further comments or questions.

**Comment by polavishnu4444** [comment]
Hi,
Sorry, missed the notification of your reply. 
Currently when a request comes, we have some key values set in the MDC context for that thread. When calls made using aws SDK and wanting to process the response on different executor thread, the MDC context is getting missed there in that thread. As this is a known problem we have overwritten the executor submit function to first get the copy of current context and then when triggering the actual submit explicitly setting the function.
I have set to use the different executor for response as mentioned in the advanced section of this doc here - - > https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/basics-async.html

**Comment by polavishnu4444** [comment]
This is how I am instantiating the client
`this.asyncClient =
        asyncClientBuilder
            .asyncConfiguration(b ->
                b.advancedOption(
                    FUTURE_COMPLETION_EXECUTOR, this.dynamoResponseExecutor))
            .build();`
For now I am doing it as below
`Map<String, String> mdcContext = MDC.getCopyOfContextMap();
    asyncClient
        .batchGetItem(batchGet)
        .thenAccept(resp -> {
          MDC.setContextMap(mdcContext);`
I wanted to avoid this explicit setting at each of the function call and instead wanted override the context when the executor submit or execute gets triggered. For that reason I have implemented ExecutorService and overriding the submit function as below
`@Override
    public <T> Future<T> submit(Callable<T> task) {
        Map<String, String> mdcContext = MDCContext.getCopyOfContextMap();
        return executor.submit(() ->{
            T resp = null;
            try {
                MDCContext.setContextMap(mdcContext);
                resp = task.call();
            } catch (Exception e) {
                throw e;
            } finally {
                MDCContext.unset();
            }
            return resp;
        });
    }`
The MDCContext.getCopyOfContextMap() is returning null.

@debora-ito 👆 Please find the usage above.
