### ISSUE TITLE
Enable global access for S3 client

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java-v2#1618]
Is there any way to enable global access to S3 client(like SDK V1) so that it can access buckets across the region.

**Comment by debora-ito** [comment]
Not currently, no. Marking as a feature request.

**Comment by aComanche** [comment]
@debora-ito do you mind if I work on this?

**Comment by debora-ito** [comment]
@miguelhrocha we need to coordinate efforts with the S3 team on this, to make sure we cover all options like Access Points, Outposts, etc. 

This is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/52, let's keep track of this feature over there. Closing this.
