### ISSUE TITLE
NullPointerException when an error occurs with the execute-api

### ISSUE THREAD

**Issue by robertgehring1** [aws/aws-sdk-java-v2#1625]
Using the AmazonHttpClient to interact with the @Connections API. If there is a problem with the request (say sending a message) then a NullPointerException is thrown. This is problematic because we need to know the status code of the response to know why.

**Comment by robertgehring1** [comment]
com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)

**Comment by debora-ito** [comment]
Hi @robertgehring1, I need more information to understand your issue. 

The New Issue template offered good guidelines on the info we usually ask:

```
## Steps to Reproduce (for bugs)
<!--- Provide a self-contained, concise snippet of code that can be inserted into a -->
<!--- For more complex issues provide a repo with the smallest sample that reproduces the bug -->
<!--- Including business logic or unrelated code makes diagnosis more difficult -->

<!--- Include full errors, uncaught exceptions, stack traces, and relevant logs -->
```

**Comment by robertgehring1** [comment]
@debora-ito here's the info you requested.

## Steps to Reproduce (for bugs)

```
    Request<Object> request = new DefaultRequest<>("execute-api");
    request.setHttpMethod(HttpMethodName.POST);
    request.setEndpoint(<insert connections URL>);
    request.setContent(new ByteArrayInputStream(contentString.getBytes()));

    String awsRegion = resolveAwsRegion(request.getEndpoint().toString());
    AWS4Signer signer = new AWS4Signer();
    signer.setRegionName(awsRegion);
    signer.setServiceName(request.getServiceName());
    signer.sign(request, new BasicAWSCredentials(<insert accessKey>, <insert secretKey>));

      amazonHttpClient
          .requestExecutionBuilder()
          .request(request)
          .execute();
```

If the connection in the connections url (the url of the request) does not exist a NullPointerException is thrown. The response from the API has a 410 status code. The code NPE is thrown on this line:

com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1742)

**Comment by debora-ito** [comment]
@robertgehring1 Can you provide the full stacktrace?

**Comment by debora-ito** [comment]
Closing this due to no response. Feel free to reopen if you can provide the stacktraces or have further questions.
