### ISSUE TITLE
Media convert:  Create GetJobTemplateResponse with jobTemplate and sdkHttpResponse

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java-v2#1631]
GetJobTemplateResponse getJobTemplateResponse = GetJobTemplateResponse.builder().jobTemplate(JobTemplate.builder().name("template-x").build()).build() ; 

works fine.
However if i want to include the sdkHttpResponse its showing error::

GetJobTemplateResponse getJobTemplateResponse1 = GetJobTemplateResponse.builder().jobTemplate(JobTemplate.builder().name("template-x").build()).sdkHttpResponse(SdkHttpResponse.builder().build()).build();

Is there any way to chain the sdkHttpResponse .

**Comment by debora-ito** [comment]
Hi @MkJha, you usually don't have to build the GetJobTemplateResponse object, it is used as the return of the GetJobTemplate API call, something like:
```
GetJobTemplateRequest jobTemplateRequest = GetJobTemplateRequest.builder()
        .name("template-name")
        .build();

GetJobTemplateResponse getJobResponse = mediaConvertClient.getJobTemplate(jobTemplateRequest);
```

Can you tell us more about your use case?

**Comment by MkJha** [comment]
The use case is to mock the mediaconvert client methods like getJob, createjob, getJobTemplate for unit testing. I am able to set template details but not finding anyway(perhaps due to lack of understanding of the sdk) to set sdkhttpResponse attrubutes.

**Comment by debora-ito** [comment]
Going through the list of old guidance issues, found this one.

@MkJha let us know if you are still blocked by this. There's no builder for SdkHttpResponse, you may want to check testing tools like localstack.
