### ISSUE TITLE
DescribeBudgetPerformanceHistory actualAmount always returns null

### ISSUE THREAD

**Issue by choweiyuan** [aws/aws-sdk-java-v2#1634]
Trying to use DescribeBudgetPerformanceHistory to return actual amount, it's always null 

## Expected Behavior
Trying to use DescribeBudgetPerformanceHistory to return actual amount, it's always null when we have actual amount. Budgeted amounts are returned though.
https://docs.aws.amazon.com/aws-cost-management/latest/APIReference/API_budgets_DescribeBudgetPerformanceHistory.html

## Current Behavior
DescribeBudgetPerformanceHistory returns null for actualAmount rather than the actual amount.

## Steps to Reproduce (for bugs)
Using Kotlin:
```
val request = DescribeBudgetPerformanceHistoryRequest.builder()
    .accountId(1234567)
    .budgetName("myBudgetName")
    .timePeriod(TimePeriod.builder()
        .start(Instant.now().minus(365, ChronoUnit.DAYS))
        .end(Instant.now())
        .build())
    .build()
val describeBudgetPerformanceHistory = budgetsClient.describeBudgetPerformanceHistory(request)
val budgetPerformanceHistory = describeBudgetPerformanceHistory.budgetPerformanceHistory()
budgetPerformanceHistory.budgetedAndActualAmountsList().forEach{ budgetedAndActualAmount ->
    logger.info(budgetedAndActualAmount) //actualAmount() is null
}
```
Tried without timePeriod too, same result.
## Context
Trying to get hold of budget history, but getting incorrect (null actual amount) information.

## Your Environment

* AWS Java SDK version used: both 2.7.8 and 2.10.57
* JDK version used: 1.8.0.241
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
@choweiyuan I could not reproduce the issue. I created a Usage Budget for monthly DDB data transfer, and its actual amount would be zero GB in my case, and the API call returned `{Amount: 0, Unit: GB}` in the actualAmount field.

Can you tell us more about your budget specification, so I can try to recreate it? Also, does the console show a value instead of null?

**Comment by choweiyuan** [comment]
Hi @debora-ito  thanks for getting back to me.

1. yes, AWS console shows non-zero amounts for both budgeted and actual amounts since the budget was created in July 2019
2. This is a Monthly Cost budget with Fixed budgeted amount
![Screenshot 2020-02-06 at 09 46 08](https://user-images.githubusercontent.com/4201614/73925594-351c6800-48c6-11ea-88b0-55e23990e20e.png)
3. Filtering on a Single "Tag" 
4. Aggregate costs by: Unblended costs
Include costs related to
* Refunds 
* Credits
* Upfront reservation fees 
* Recurring reservation charges 
* Other subscription costs 
* Taxes 
* Support charges 
![Screenshot 2020-02-06 at 09 50 08](https://user-images.githubusercontent.com/4201614/73925592-3483d180-48c6-11ea-8048-0bc6772e6ef6.png)

**Comment by debora-ito** [comment]
Still cannot reproduce it... can I ask you to turn the [wire logs](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/java-dg-logging.html) on and provide the response content? Please be sure to redact any sensitive information - but do provide a RequestId, it will be used in case we need to contact the service team.

We would be able to see if the ActualAmount is present in the response. You don't have to provide us the logs with you don't want to, you can simply check if the data is being sent in the response.

**Comment by choweiyuan** [comment]
"x-amzn-RequestId: 2542ff61-72a2-432c-93ac-9d6d559f6e06[\r][\n]"
```
{
  "BudgetPerformanceHistory": {
    "BudgetName": "redacted",
    "BudgetType": "COST",
    "BudgetedAndActualAmountsList": [
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5646176E9,
          "Start": 1.5619392E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.567296E9,
          "Start": 1.5646176E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.569888E9,
          "Start": 1.567296E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5725664E9,
          "Start": 1.569888E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5751584E9,
          "Start": 1.5725664E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5778368E9,
          "Start": 1.5751584E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5805152E9,
          "Start": 1.5778368E9
        }
      },
      {
        "BudgetedAmount": {
          "Amount": "redacted",
          "Unit": "USD"
        },
        "TimePeriod": {
          "End": 1.5830208E9,
          "Start": 1.5805152E9
        }
      }
    ],
    "CostFilters": {
      "TagKeyValue": [
        "user:Application$redacted"
      ]
    },
    "CostTypes": {
      "IncludeCredit": true,
      "IncludeDiscount": true,
      "IncludeOtherSubscription": true,
      "IncludeRecurring": true,
      "IncludeRefund": true,
      "IncludeSubscription": true,
      "IncludeSupport": true,
      "IncludeTax": true,
      "IncludeUpfront": true,
      "UseAmortized": false,
      "UseBlended": false
    },
    "TimeUnit": "MONTHLY"
  }
}
```

**Comment by debora-ito** [comment]
So the ActualAmount is not being sent in the response. I'll contact the service team behind the Bugdets API, will let you know when we hear back.

**Comment by choweiyuan** [comment]
hi @debora-ito , do you have an ETA or update from the service team for this?

**Comment by debora-ito** [comment]
No updates from the team yet.

**Comment by choweiyuan** [comment]
Hi again, just tested with a personal account (Not part of an Organisation), same issue

IAM Attached directly

>  Billing - AWS managed policy
>  AdministratorAccess - AWS managed policy
>  IAMUserChangePassword -AWS managed policy
> 

```
fun main(args: Array<String>) {
  val budgetsClient = BudgetsClient.builder().region(Region.AWS_GLOBAL).build()
  try {
    val request = DescribeBudgetPerformanceHistoryRequest.builder()
      .accountId("REDACTED")
      .budgetName("test-budget")
      .build()
    val describeBudgetPerformanceHistory = budgetsClient.describeBudgetPerformanceHistory(request)
    val budgetPerformanceHistory = describeBudgetPerformanceHistory.budgetPerformanceHistory().budgetedAndActualAmountsList()
  } catch (ex: Exception) {
  }
}
```

```10:38:37.280 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amzn-RequestId: f887984d-777f-4098-9266-616c84293a95[\r][\n]"```

```10:38:37.280 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "{"BudgetPerformanceHistory":{"BudgetName":"test-budget","BudgetType":"COST","BudgetedAndActualAmountsList":[{"BudgetedAmount":{"Amount":"10","Unit":"USD"},"TimePeriod":{"End":1.5856992E9,"Start":1.5830208E9}}],"CostFilters":{},"CostTypes":{"IncludeCredit":false,"IncludeDiscount":true,"IncludeOtherSubscription":true,"IncludeRecurring":true,"IncludeRefund":false,"IncludeSubscription":true,"IncludeSupport":true,"IncludeTax":true,"IncludeUpfront":true,"UseAmortized":false,"UseBlended":false},"TimeUnit":"MONTHLY"}}"```

**Comment by choweiyuan** [comment]
![Capture](https://user-images.githubusercontent.com/4201614/76411087-f8da9c80-6388-11ea-9691-e74a60834ec1.PNG)
![Capture2](https://user-images.githubusercontent.com/4201614/76411089-f9733300-6388-11ea-8432-9f82e3f133d3.PNG)

**Comment by debora-ito** [comment]
@choweiyuan the ticket was updated saying you started to see the ActualAmount, is that correct?

**Comment by choweiyuan** [comment]
Yes that's correct, thanks for your help :)
