### ISSUE TITLE
Mediaconvert : Deserialization of sdk v2 POJOs are not happening

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java-v2#1635]
Taking a clue from https://aws.amazon.com/blogs/developer/aws-sdk-for-java-2-0-developer-preview/  
on how to perform serializing/deserializing of sdk v2 claases.

Serialization is working, but deserialization is not working.

Sample :: 
ObjectMapper mapper = new ObjectMapper();
	 GetJobResponse jobResponse = GetJobResponse.builder().job(Job.builder().id("job-x").build()).build();
String y = mapper.writeValueAsString(jobResponse.toBuilder());
The above serialization works fine. 

But attempt to deserialize doesn't work
	 GetJobResponse jobResponse1 = mapper.readValue(y, GetJobResponse.serializableBuilderClass()).build();

**Comment by debora-ito** [comment]
> But attempt to deserialize doesn't work

Can you give us more details on why it doesn't work, or provide the stacktrace?

**Comment by MkJha** [comment]
It works fine. You can mark it invalid.

**Comment by debora-ito** [comment]
Closing. Feel free to reach out if you have any further questions.
