### ISSUE TITLE
Two Way Messaging - Virtual Queues 

### ISSUE THREAD

**Issue by sashokbg** [aws/aws-sdk-java-v2#1647]
This is a question about a feature that is present in sdk v1 but not in sdkv2:

I would like to implement a virtual queue for a two way communication as described in this document -> https://aws.amazon.com/blogs/compute/simple-two-way-messaging-using-the-amazon-sqs-temporary-queue-client/

I however cannot find any trace of the mentioned classes nor documentation in the java sdk v2.
Has this feature been abandoned or it is just not yet implemented ?

Is there another convenient way to implement the two way messaging pattern in sdk v2 ?

**Comment by debora-ito** [comment]
Hi @sashokbg you may have figured this out already, but I'm leaving a comment here for anyone that stumbles across this issue: the SQS Temporary Queues Client is a library managed in its own repository - https://github.com/awslabs/amazon-sqs-java-temporary-queues-client

**Comment by sashokbg** [comment]
Hello @debora-ito yes it turned out it is a separate tool. There is already a question on their issues page about SDK v2 support: 
https://github.com/awslabs/amazon-sqs-java-temporary-queues-client/issues/9
