### ISSUE TITLE
SDK is fine at compile time, but can't find class at runtime

### ISSUE THREAD

**Issue by crazyeightlikesapples** [aws/aws-sdk-java-v2#1650]
I am attempting to run boilerplate code with dynamo db. I am using maven shade and everything works fine at compile time, but I get java.lang.NoClassDefFoundError: software/amazon/awssdk/services/dynamodb/DynamoDbClient  at run time. I have spent at least 5 hours trying different versions of the sdk and nothing helps. I am able to see the library in my external libraries area of Intellije.

Error:
java.lang.NoClassDefFoundError: software/amazon/awssdk/services/dynamodb/DynamoDbClient

Pom.xml
https://pastebin.com/wwaTm8yq

Code causing error:

		DynamoDbClient ddb = DynamoDbClient.builder().build();

		Map<String, AttributeValue> item = new HashMap<>();
		item.put("uuid", AttributeValue.builder().s("test").build());
		ddb.putItem(PutItemRequest.builder().item(item).build());

**Comment by debora-ito** [comment]
Hi @crazyeightlikesapples NoClassDefFound Errors usually indicate conflicting versions of the same dependency in your environment. Can you run `mvn dependency:tree` and post the relevant output?

**Comment by debora-ito** [comment]
Closing due to no response. Feel free to reopen if problem persists.
