### ISSUE TITLE
IAM access key, secret key Vs STS for media convert client

### ISSUE THREAD

**Issue by MkJha** [aws/aws-sdk-java-v2#1659]
Document suggest media convert supports STS. 

I have a few queries regrading the same : 

a. What is the widely used mechanism to make API request ? Via access/secret key or through STS. ?
b. Even to request STS credentials, i believe we need to pass access and secret key  needs to be used. Anyway the user needs to secure the access key and secret key in the client side, what is the advantage then , except in actual media convert api request calls STS crdentials will be used.
c. As STS are temporary credentials, how long maximum they will be valid ? Are they ideal to use for media convert ?
d. Are there any other way to instantiate media convert client apart from access/secret and STS credentials ?

**Comment by debora-ito** [comment]
@MkJha please refer to the AWS IAM User Guide; in the Temporary Security Credentials section they explain the advantages of using temporary credentials and give examples of different scenarios -  https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp.html

The duration of the temporary credentials are specified by you when you call the STS operations. See, for example, the GetSessionToken operation here: https://docs.aws.amazon.com/STS/latest/APIReference/API_GetSessionToken.html

For ways to provide credentials to the SDK, see the Developer Guide: https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/credentials.html

We'd like to keep our issues focused on problems with the SDK itself, so for further questions about STS features and adoption, please ask them in communities such as StackOverflow or the AWS Developer Forums. You can also reach out to the AWS Customer Support.
