### ISSUE TITLE
Serialization and deserialization for request/response POJOs with enum fields

### ISSUE THREAD

**Issue by zoewangg** [aws/aws-sdk-java-v2#1672]
## Expected Behavior
Serialization and deserialization for any request/response POJOs should work 

## Current Behavior
If a POJO contain an enumeration, serializing .toBuilder() will produce a field called <enumname>AsString, and then depending on your object mapper configuration, either it will fail deserialization or silently ignore the bad field.

## Possible Solution
introduce a `.toSerializableBuilder()`

## Steps to Reproduce (for bugs)
```
import software.amazon.awssdk.services.dynamodb.model.Record;

val orig = Record.builder().eventName(OperationType.INSERT).build();
val str = mapper.writeValueAsString(orig.toBuilder());
val deser = mapper.treeToValue(mapper.readTree(str), Record.serializableBuilderClass()).build()
```

**Comment by debora-ito** [comment]
Closing this via #1789.
