### ISSUE TITLE
I experienced the same problem. I am using Java 13. May I know how I can resolve the issue? Thanks

### ISSUE THREAD

**Issue by tsnchan** [aws/aws-sdk-java-v2#1683]
I experienced the same problem. I am using Java 13. May I know how I can resolve the issue? Thanks

_Originally posted by @tsnchan in https://github.com/aws/aws-sdk-java-v2/issues/1660#issuecomment-594471278_

**Comment by debora-ito** [comment]
Hi @tsnchan let's keep track of this in the original issue, where we have more context of the problem.
