### ISSUE TITLE
Refactor: Retry Policies

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#17]
Review the inherited state of V1 retry policies and determine whether any changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by millems** [comment]
Throttled retries are also not currently configurable as they were in 1.11.x. This should be addressed as part of the retry policy refactor.

**Comment by shorea** [comment]
Implemented

**Comment by OlegZhukov** [comment]
How is this implemented? There doesn't seem to be a way to configure `CapacityManager` used for throttled retries.
