### ISSUE TITLE
Seems still the issue with empty values for dynamo in sdk v2

### ISSUE THREAD

**Issue by alexmnyc** [aws/aws-sdk-java-v2#1736]
https://github.com/aws/aws-sdk-java/issues/1189

**Comment by debora-ito** [comment]
Hi @alexmnyc this is a DynamoDB limitation. As said in the issue you referenced, the DynamoDB team is aware of this feature request and is considering adding support for empty strings. If DynamoDB adds support for this, you'll be able to use it with the SDK. 

I'll go ahead and close this, feel free to reopen if you have any other question.
