### ISSUE TITLE
What was the desing decision that lead to the need for AttributeBooleanValue

### ISSUE THREAD

**Issue by NavidMitchell** [aws/aws-sdk-java-v2#1739]
First I want to say thank you for building the SDK 2 I really like the true Async support! :) 

Is there a reason why the AttributeBooleanValue  is required vs a standard boolean value? It seems a little unnecessary and is rather cumbersome to use.

Thank you,
Navid Mitchell

**Comment by debora-ito** [comment]
Hi @NavidMitchell, can you elaborate on what AttributeBooleanValue you are asking about?

**Comment by NavidMitchell** [comment]
Hello,

The 

software.amazon.awssdk.services.ec2.model.AttributeBooleanValue

It is required with some requests like so 

` ModifyVpcAttributeRequest request =
                                ModifyVpcAttributeRequest.builder()
                                 .enableDnsHostnames(AttributeBooleanValue.builder().value(true).build())
                                                         .vpcId(vpc.vpcId())
                                                         .build()`

Thank you :)

**Comment by zoewangg** [comment]
Hi @NavidMitchell apologies for the delayed response. Glad you like the async client! 😄 

To answer your question, all service POJOs are generated based on model files provided/owned by service teams. While I agree that having to provide `AttributeBooleanValue` is not a good customer experience in this case, there is not much we can do unfortunately.

To make it less verbose, you can try the "consumer builder" way to pass the value.

```
    ModifyVpcAttributeRequest request = ModifyVpcAttributeRequest.builder()
                                                                 .enableDnsHostnames(e -> e.value(true))
                                                                 .build();
```

**Comment by NavidMitchell** [comment]
Hello @zoewangg  thank you for the response. I figured you would say something like that. The only reason I asked is I noticed some "request" objects have support for primitives without using a "builder DTO".  Your suggestion is a more terse, I will use that. Thank you again. :)

**Comment by debora-ito** [comment]
Great @NavidMitchell, I'll go ahead and close this. Feel free to reach out if you have any other question.
