### ISSUE TITLE
Unable to create a presigned URL to upload object to S3 when using an ACL

### ISSUE THREAD

**Issue by bobbyphilip** [aws/aws-sdk-java-v2#1742]
I am using the AWS v2 java SDK. I am trying to upload an object to my bucket. I want the object to be publicly readable.

What I have done is as follows:

  `PresignedPutObjectRequest presignedRequest =S3Presigner.create()
                .presignPutObject(z -> z.signatureDuration(Duration.ofMinutes(10))
                    .putObjectRequest(
                                por -> por.bucket("MYBUCKET")
                                    .key("MYOBJECTKEY")
                                    .acl(ObjectCannedACL.PUBLIC_READ)));
   URL url = presignedRequest.url();`

I then use this URL to upload a file. I am getting a 403 response when I do this.
If I remove the line adding the acl, then the upload works.
If I change the ACL to PRIVATE, that too fails.

After some more debugging from my end, it looks to be a problem with the way the URL is being built.
This is part of the URL when I dont add an ACL

`&X-Amz-SignedHeaders=host&X-Amz-Expires=120  `

And this is the similar part of the URL with an ACL

`&X-Amz-SignedHeaders=host%3Bx-amz-acl&X-Amz-Expires=120`  

It looks to me that the acl is not added properly.

* AWS Java SDK version used: 2.11.2
* JDK version used:  openjdk version "1.8.0_242"
* Operating System and version: Debian

**Comment by bobbyphilip** [comment]
This is not a bug, when using the presigned URL, the     x-amz-acl=public-read header needs to be set

**Comment by AudiVehicle** [comment]
https://github.com/aws/aws-sdk-java-v2/issues/1849
