### ISSUE TITLE
Updating tags for API Key in API Gateway

### ISSUE THREAD

**Issue by hinews** [aws/aws-sdk-java-v2#1747]
Updating tags for API Key in API Gateway

## Describe the Feature
AWS SDK provides creation of API Key with tags fields by CreateApiKeyRequest.
But UpdateApiKeyRequest doesn't provide the same behavior for updating tags.
So, feature request is to provide the same behavior.

## Is your Feature Request related to a problem?
I have to use other request TagResourceRequest to update tags for API Key. But this request requires ARN instead of API Key Id. And there is no way to get ARN for API Key, only hardcoding it in this way: 
```
String arn = String.format("arn:aws:apigateway:%s::/apikeys/%s", RunEnvironment.awsRegion, existedApiKey.id());
// AWS API doesn't provide API to update tags as API Key but as ARN Resource
        TagResourceRequest tagResourceRequest = TagResourceRequest.builder()
                .resourceArn(arn)
                .tags(newTags).build();
        TagResourceResponse tagResourceResponse = apiGatewayClient.tagResource(tagResourceRequest);
```

## Proposed Solution
To add  "patchOperations" by path /tags as implemented for stages in UpdateApiKeyRequest 

## Describe alternatives you've considered
Provide service to get ARN for API Key by API Key Id.

## Your Environment
* AWS Java SDK version used: 2.11.4
* JDK version used: Oracle 8 build 191
* Operating System and version: EKS

**Comment by debora-ito** [comment]
Hi @hinews this is a feature request for the API Gateway service, I will forward it to the API Gateway service team. I would also suggest you post it in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199) to get the team's attention.

**Comment by debora-ito** [comment]
Looking at the API Gateway documentation I could not find an API that returns API key ARNs, so the workaround of building the ARN by hand is a good one.

As for the feature request, the API Gateway team acknowledged it so I'll go ahead and close this, it is now in their backlog. Feel free to reach out if you have further questions.
