### ISSUE TITLE
Unable to unmarshall response - S3 List Buckets Contents

### ISSUE THREAD

**Issue by chimbida** [aws/aws-sdk-java-v2#175]
I'm having this issue since preview 1, now testing with preview 4.
Some buckets is not listing and i get this error:

`2017-09-22 09:38:13.381 ERROR 2235 --- [nio-8080-exec-1] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is software.amazon.awssdk.SdkClientException: Unable to unmarshall response (For input string: "2160142290"). Response Code: 200, Response Text: OK] with root cause`

full error: [https://gist.github.com/chimbida/d4974e138a9f5f2540a54bda6a0b10d4](https://gist.github.com/chimbida/d4974e138a9f5f2540a54bda6a0b10d4)

The line with error is:

```java
ListObjectsV2Response listObjectsResponse = s3.listObjectsV2(listObjectsRequest);
```
...here is a piece of my code:

```java 

    public List<Status> UpdateStatus() {

        Region region = Region.US_EAST_1;
        S3Client s3 = S3Client.builder().region(region).build();

        List<CopyData> copydata = copyDataRepository.findAllByAtivoIsTrue();
        List<Status> dados = new ArrayList<Status>();

        copydata.forEach((CopyData cp) -> {
            Dados salvaDados = new Dados();
            Status alerta = new Status();
            final Date[] dataNovo = {null};
            final Date[] dataVelho = {null};
            final long[] volume = {0};
            final Integer[] qt = {0};

            ListObjectsV2Request listObjectsRequest =
                    ListObjectsV2Request.builder().bucket("bucket-name").prefix(cp.getCopydataGib()+"/").build();

            ListObjectsV2Response listObjectsResponse = s3.listObjectsV2(listObjectsRequest);

            List<S3Object> buckets = listObjectsResponse.contents();

            System.out.println("\n" + buckets);

```

**Comment by shorea** [comment]
Looks like a modeling error. In the S3 service model "Size" is an integer but can obviously be larger than what integer allows. In V1 we handwrite the unmarshaller and are correctly parsing as a Long (https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/model/transform/XmlResponsesSaxParser.java#L691) but in V2 we generate the unmarshaller from the service model. I'm very surprised this hasn't been an issue for other SDKs that use the service model.

I will follow up with the service team to get this patched, in the meantime I'll fix it manually on master.

**Comment by shorea** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/176

**Comment by chimbida** [comment]
Thanks @shorea this fix the problem!

**Comment by shorea** [comment]
Merged into master.
