### ISSUE TITLE
S3AsyncClient slower than S3Client

### ISSUE THREAD

**Issue by geniusit** [aws/aws-sdk-java-v2#1750]
## Describe the issue
It takes longer to get an object from a S3 bucket with S3AsyncClient than an S3Client

## Steps to Reproduce
Create a simple class that implements RequestHandler.
Get an object from a S3 bucket with a S3Client.
Check Cloudwatch logs : Duration : 280ms

Get the same object with a S3AsyncClient.
Check Cloudwatch logs : Duration : 2600ms

Where does the difference come from ?

## Your Environment

* AWS Java SDK version used: 2.10.78 for S3Event and 1.11.754 for S3EventNotification
* JDK version used: 11-open
* Operating System and version: Linux Fedora 31

**Comment by geniusit** [comment]
do it in this way was the solution for me :+1: 
`public S3AsyncClient getS3Client(){

        ClientOverrideConfiguration overrideConfiguration =
                ClientOverrideConfiguration.builder()
                        .apiCallTimeout(Duration.ofSeconds(30))
                        .apiCallAttemptTimeout(Duration.ofSeconds(20))
                        .build();

        SdkAsyncHttpClient httpClient = NettyNioAsyncHttpClient.builder()
                //.maxConcurrency(100)
              //  .maxPendingConnectionAcquires(10_000)
                .connectionTimeout(Duration.ofSeconds(20))
                .connectionAcquisitionTimeout(Duration.ofSeconds(20))
                .build();


        return S3AsyncClient.builder()
                .region(Region.of( System.getenv("AWS_REGION") ) )
                .overrideConfiguration(overrideConfiguration)
                .httpClient(httpClient)
                .asyncConfiguration(
                        b -> b.advancedOption(SdkAdvancedAsyncClientOption
                                        .FUTURE_COMPLETION_EXECUTOR,
                                Executors.newFixedThreadPool(2)
                        )
                )

                .build();
    }`

**Comment by geniusit** [comment]
doing in this way is right for me : 
`public S3AsyncClient getS3Client(){

        ClientOverrideConfiguration overrideConfiguration =
                ClientOverrideConfiguration.builder()
                        .apiCallTimeout(Duration.ofSeconds(30))
                        .apiCallAttemptTimeout(Duration.ofSeconds(20))
                        .build();

        SdkAsyncHttpClient httpClient = NettyNioAsyncHttpClient.builder()
                //.maxConcurrency(100)
              //  .maxPendingConnectionAcquires(10_000)
                .connectionTimeout(Duration.ofSeconds(20))
                .connectionAcquisitionTimeout(Duration.ofSeconds(20))
                .build();


        return S3AsyncClient.builder()
                .region(Region.of( System.getenv("AWS_REGION") ) )
                .overrideConfiguration(overrideConfiguration)
                .httpClient(httpClient)
                .asyncConfiguration(
                        b -> b.advancedOption(SdkAdvancedAsyncClientOption
                                        .FUTURE_COMPLETION_EXECUTOR,
                                Executors.newFixedThreadPool(2)
                        )
                )

                .build();
    }`

**Comment by geniusit** [comment]
Exactly, billing time are now well calculated.

**Comment by debora-ito** [comment]
Great. I'll go ahead and close this, feel free to reopen if you have any other question.
