### ISSUE TITLE
SimulatePrincipalPolicyRequest returns different results than online policy simulator

### ISSUE THREAD

**Issue by ryantse** [aws/aws-sdk-java-v2#1751]
## Describe the bug
SimulatePrincipalPolicyRequest returns results that don't match with what is seen on policy simulator.

```
IamClient iamClient = IamClient.builder().region(Region.AWS_GLOBAL).build();
ContextEntry.Builder contextEntry = ContextEntry.builder()
                .contextKeyName("ec2:ResourceTag/some_tag")
                .contextKeyType(ContextKeyTypeEnum.STRING)
                .contextKeyValues("true");

SimulatePrincipalPolicyRequest.Builder request = SimulatePrincipalPolicyRequest.builder()
                .policySourceArn("arn:aws:iam::ACCOUNT_ID:role/ROLE_NAME")
                .actionNames("ec2:DeleteVolume")
                .resourceArns("arn:aws:ec2:us-west-2:ACCOUNT_ID:volume/*")
                .contextEntries(contextEntry.build());
```

This simulation returns an implicitDeny. However, testing in the online policy simulator, this returns allowed as expected.

The following is an excerpt of the relevant IAM policy associated
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:DeleteVolume",
      "Resource": "arn:aws:ec2:*:*:volume/*",
      "Condition": {
        "StringEquals": {
          "ec2:ResourceTag/some_tag": "true"
        }
      }
    },
   ....
```

## Expected Behavior
The policy simulator should return allowed.

## Current Behavior
The policy simulator returns implicitDeny.

## Steps to Reproduce
See above.

## Your Environment
* AWS Java SDK version used: 2.10.56
* JDK version used: 8
* Operating System and version: macOS

**Comment by debora-ito** [comment]
@ryantse the `MatchedStatements` and `MissingContextValues` values included in the response should help to determine how the decision was achieved. 
https://docs.aws.amazon.com/IAM/latest/APIReference/API_EvaluationResult.html

Do they help in your case?

**Comment by ryantse** [comment]
@debora-ito: The SimulatePolicyResponse was:
```
SimulatePrincipalPolicyResponse(EvaluationResults=[EvaluationResult(EvalActionName=ec2:DeleteVolume, EvalResourceName=arn:aws:ec2:us-west-2:ACCOUNT_ID:volume/*, EvalDecision=implicitDeny, MatchedStatements=[], MissingContextValues=[aws:ResourceTag/some_other_tag, aws:RequestTag/some_other_tag, ec2:CreateAction], EvalDecisionDetails={}, ResourceSpecificResults=[ResourceSpecificResult(EvalResourceName=arn:aws:ec2:us-west-2:ACCOUNT_ID:volume/*, EvalResourceDecision=implicitDeny, MatchedStatements=[], MissingContextValues=[aws:ResourceTag/some_other_tag, aws:RequestTag/some_other_tag, ec2:CreateAction], EvalDecisionDetails=software.amazon.awssdk.core.util.DefaultSdkAutoConstructMap@1de5f0ef)])], IsTruncated=false)
```
Unless it's necessary to fill out the other tags that don't apply to ec2:DeleteVolume action statement that are in other parts of the IAM policy, it seems like this is still a bug.

**Comment by debora-ito** [comment]
Here's what the [documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_SimulatePrincipalPolicy.html) says about `PolicySourceArn`:
> PolicySourceArn
> The Amazon Resource Name (ARN) of a user, group, or role whose policies you want to include in the simulation. If you specify a user, group, or role, the simulation includes all policies that are associated with that entity. If you specify a user, the simulation also includes all policies that are attached to any groups the user belongs to.

**Comment by ryantse** [comment]
@debora-ito: We've provided a PolicySourceArn with a specific role we are trying to simulate which has the policy in the originally reported case. We are still unable to use SimulatePrincipalPolicyRequest to replicate what we see in the online AWS policy simulator.

**Comment by debora-ito** [comment]
I was pointing out that when you specify a role, the simulation includes all policies associated with the role. You highlighted the EC2:DeleteVolume, but maybe the other MissingContextValues listed in the response are part of the PolicySourceArn you're providing? 

I'm working in a repro case on my side.

**Comment by ryantse** [comment]
@debora-ito: Thank you for trying to reproduce this issue on your side. I'd be happy to provide more details like the full policy privately if you can provide me a way to communicate that to you. We are seeing this in other actions as well, and it's not limited to ec2:DeleteVolume.

To provide more details about the policy: The other MissingContextValues are used in statements that cover other AWS actions -- however, in my sample case here, ec2:DeleteVolume is only referenced in this single statement. There are also no other wildcard actions that would apply to this, i.e. no ec2:* statements.

**Comment by debora-ito** [comment]
Ok, I can reproduce it, minimally with only the ec2:DeleteVolume action. Just to confirm, here's what I did:
1) created a new role `ec2-delete-volume` with only the following policy attached:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "ec2:DeleteVolume",
      "Resource": "arn:aws:ec2:*:*:volume/*",
      "Condition": {
        "StringEquals": {
          "ec2:ResourceTag/some_tag": "true"
        }
      }
    }
  ]
}
```
2) I provided `ec2-delete-volume` role as policySourceArn using the same sample code you provided (but with my ACCOUNT_ID) and called the simulatePrincipalPolicy operation.
3) I get a `implicitDeny` eval decision.

But providing the same inputs to the Policy Simulator, I get a permission allowed:

![Screen Shot 2020-04-07 at 4 26 13 PM](https://user-images.githubusercontent.com/476307/78728665-c6bb4c80-78ec-11ea-993d-f01395de093d.png)

I tried different combinations of wildcards in the policy and in the resource, still no success.
Is this what you are experiencing?

**Comment by ryantse** [comment]
@debora-ito: Yes. I believe the reproduction as you describe captures an example of the issue I am seeing. This issue is seen in other combinations of actions/resources/conditions as well.

**Comment by debora-ito** [comment]
This looks like a service side issue then, I'll contact the team behind the PolicySimulator API.

I'm still concerned that your use case may be different from the one I reproduced, based on the MissingContextValues you are seeing, but let's see what the service team will say. Can you provide a requestID of a problematic call, in case they need one to investigate?

**Comment by ryantse** [comment]
@debora-ito: The MissingContextValues are applicable only to other policy statements. For example, the policy would have:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "ec2:DeleteVolume",
            "Resource": "arn:aws:ec2:*:*:volume/*",
            "Condition": {
                "StringEquals": {
                    "ec2:ResourceTag/some_tag": "true"
                }
            }
        },
        {
            "Effect": "Allow",
            "Action": "elasticfilesystem:CreateFileSystem",
            "Resource": "*",
            "Condition": {
                "StringEquals": {
                    "aws:RequestTag/other_tag": "true"
                }
            }
        },
        ...
```
In the above policy, the MissingContextValues would still return as aws:RequestTag/other_tag even though it isn't applicable to the action that we are trying to simulate with the AWS SimulatePrincipalPolicy API call.

Below are the request and event IDs:
Request ID: 9ce0d532-46bf-421f-aa43-e62c73df2ace
Event ID: 5132a5bd-4438-4bda-ac87-33c3630d9a0b

**Comment by ryantse** [comment]
@debora-ito: Is there any update as to when this might be fixed? Also, could you mark this as a bug since this is an inconsistency with the API usage and its expected output?

**Comment by debora-ito** [comment]
No response from the service team yet. I'll update here when I hear back.

**Comment by debora-ito** [comment]
@ryantse The service team released a fix, I rerun my local tests and I get an `allowed` eval decision now. 

Can you confirm if it fixes your use case?

**Comment by ryantse** [comment]
@debora-ito: We were able to validate that the fix appears to be working on our end. Thank you so much for helping us to raise this issue and for getting it resolved!
