### ISSUE TITLE
Feature Request: Add Extended Request Id to AwsServiceException

### ISSUE THREAD

**Issue by bhelm-zoccam** [aws/aws-sdk-java-v2#1776]
When opening a case with AWS Support about an S3 error, the first thing they ask for is the request id and extended request id. However, when an exception occurs, the extended request id is not provided in the exception. A way to get it was provided in AWS SDK 1 (documented here: [https://docs.aws.amazon.com/AmazonS3/latest/dev/troubleshooting.html#sdk-request-ids]) but is not present in AWS SDK 2. Documentation says the only way to find it is to turn on Verbose Wire Logging, and says not to do it in production, which is where things that get reported to AWS Support normally happen. It seems that code similar to the code that gets the request id could easily get the extended request id as well. That code is in software.amazon.awssdk.services.s3.internal.handlers.ExceptionTranslationInterceptor lines 47 to 50 in v2.11.9:

        String requestIdFromHeader = exception.awsErrorDetails()
                                              .sdkHttpResponse()
                                              .firstMatchingHeader("x-amz-request-id")
                                              .orElse(null);

The extended request id is in header "x-amz-id-2", so the code could be repeated for that, and the field added to the exception, and the frustration of developers asked to provide a value they cannot get would be reduced.

**Comment by bhelm-zoccam** [comment]
I was able to get the extended request id within my application from the SDKServiceException thrown by the S3 client (which was an AWSServiceException). However, having it in the SDK would be more convenient.

`		if( ase instanceof AwsServiceException ) {
		    AwsServiceException awsse = (AwsServiceException)ase;
		    String extendedRequestIdFromHeader = awsse.awsErrorDetails()
		            .sdkHttpResponse()
		            .firstMatchingHeader("x-amz-id-2")
		            .orElse(null);
		    if( extendedRequestIdFromHeader == null ) {
		        log.error("No extended request id available in exception.");
		    } else {
		        log.error("Extended request id: {}", extendedRequestIdFromHeader);
		    }
		}
`

**Comment by debora-ito** [comment]
@bhelm-zoccam this is a reasonable ask, marking as a feature request to add the extended request ID  to the exception.

**Comment by millems** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/1798 was created for this

**Comment by debora-ito** [comment]
This is now available in SDK version `2.13.17`.
