### ISSUE TITLE
jackson-annotations dependency mismatch

### ISSUE THREAD

**Issue by msailes** [aws/aws-sdk-java-v2#1787]
## Describe the bug

The dynamodb module has a dependency on sdk-core and regions. Each of these modules uses a different version of jackson-annotations.

+-com.amazonaws:aws-sam-java-rest:1.0.0
  +-software.amazon.awssdk:dynamodb:2.12.0
    +-software.amazon.awssdk:sdk-core:2.12.0
      +-com.fasterxml.jackson.core:jackson-databind:2.10.0
        +-com.fasterxml.jackson.core:jackson-annotations:2.10.0
and
+-com.amazonaws:aws-sam-java-rest:1.0.0
  +-software.amazon.awssdk:dynamodb:2.12.0
    +-software.amazon.awssdk:regions:2.12.0
      +-com.fasterxml.jackson.core:jackson-annotations:2.9.0

## Expected Behavior
They should use the same version.

## Current Behavior
regions v2.12.0 uses jackson-annotations:2.9.0
sdk-core v2.12.0 uses jackson-annotations:2.10.0 because it has a dependency on jackson-databind:2.10.0

## Steps to Reproduce
Any project which has a dependency on dynamodb

        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
            <version>${aws.sdk.version}</version>
        </dependency>

## Possible Solution
It looks like there are two different properties used to track the jackson version
https://github.com/aws/aws-sdk-java-v2/blob/master/bom-internal/pom.xml#L60
https://github.com/aws/aws-sdk-java-v2/blob/master/bom-internal/pom.xml#L65

## Context
Mismatching dependencies lead to obscure bugs where new methods are in one version but not another. They're really hard to track down and super annoying.

This was found with the help of: http://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html

**Comment by debora-ito** [comment]
Hi @msailes in SDK version `2.13.0` we upgraded to jackson-annotation 2.10.0. This at least keep the jackson dependencies in the same minor version but it does not prevent conflicts in the future when we upgrade the versions again.

We'll investigate if the same version property can be used for all jackson dependencies. Changing this to feature request.

**Comment by msailes** [comment]
Unfortunately the same problem has occurred again. 

+-com.amazonaws:aws-sam-java-rest:1.0.0
  +-software.amazon.awssdk:dynamodb:2.13.0
    +-software.amazon.awssdk:sdk-core:2.13.0
      +-com.fasterxml.jackson.core:jackson-databind:2.10.3
        +-com.fasterxml.jackson.core:**jackson-annotations:2.10.3**
and
+-com.amazonaws:aws-sam-java-rest:1.0.0
  +-software.amazon.awssdk:dynamodb:2.13.0
    +-software.amazon.awssdk:regions:2.13.0
      +-com.fasterxml.jackson.core:**jackson-annotations:2.10.0**
