### ISSUE TITLE
@DynamoDBDocument not working for a Map<Object, Object>

### ISSUE THREAD

**Issue by namral** [aws/aws-sdk-java-v2#179]
I tried to use @DynamoDBDocument to serialize a POJO that looks like this : 

`
@DynamoDBDocument
    public class Metadata {
        Map<Object, Object> metadata;
    
        public Metadata() {
        }
    
        public Metadata(Map<Object, Object> metadata) {
            this.metadata = metadata;
        }
    
        @DynamoDBAttribute
        public Map<Object, Object> getMetadata() {
            return stateMetadata;
        }
    
        public void setMetadata(Map<Object, Object> metadata) {
            this.metadata = metadata;
        }
    }

   @DynamoDBTable(tableName = "REPLACED_BY_CONFIG")
   public class ProductItem {
          private Metadata metadata;

         @DynamoDBAttribute
         public Metadata getMetadata() {
               return metadata;
         }
   }
`

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.Annotations.html#DynamoDBMapper.Annotations.DynamoDBDocument

It throws the following exception : 
Caused by: com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMappingException: not supported; requires @DynamoDBTyped or @DynamoDBTypeConverted

I was able to get this to work by adding the following annotation to the getter method in ProductItem
`    @DynamoDBTypeConverted(converter = MetadataTypeConverter.class)`

I was wondering why I see this behavior ?

**Comment by kiiadi** [comment]
At present the DynamoDB Mapper has not been fully ported to the v2 code-base. We do have a tracking issue for this: https://github.com/aws/aws-sdk-java-v2/issues/35

**Comment by namral** [comment]
Good to know. I mistakenly opened it under the v2 version. It was mean't for v1

**Comment by biniama** [comment]
> `@DynamoDBTypeConverted(converter = MetadataTypeConverter.class)`

Is `MetadataTypeConverter.class` your custom implementation?
