### ISSUE TITLE
API Gateway: GetUsagePlanKeysResponse doesn't return value of API Key

### ISSUE THREAD

**Issue by ShemTovYosef** [aws/aws-sdk-java-v2#1792]
API Gateway: GetUsagePlanKeysResponse doesn't return value of API Key

## Describe the bug
GetUsagePlanKeysResponse doesn't return value of API Key. It's always null.
While GetApiKeysResponse returns value when includeValues enabled in GetApiKeysRequest but GetUsagePlanKeysRequest doesn't have this field.

## Expected Behavior
GetUsagePlanKeysResponse doesn't return value of API Key. Should be value of API Key

## Current Behavior
GetUsagePlanKeysResponse doesn't return value of API Key. It's always null.

## Possible Solution
Add boolean field _includeValues_ as for GetApiKeysRequest

**Comment by debora-ito** [comment]
Hi @hinews, I can see the issue, the service is returning id, type and name in the response, but not value. I'll contact the API Gateway team internally and ask them to clarify. Reiterating, you can also reach out directly to the API Gateway team by posting this in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=199).

I will update here when they respond.

**Comment by debora-ito** [comment]
@hinews the response from GetUsagePlanKeys now returns the value.

```
> aws apigateway get-usage-plan-keys --usage-plan-id xxx
{
    "items": [
        {
            "id": "abc123",
            "type": "API_KEY",
            "value": "012356789",
            "name": "key"
        }
    ]
}
```

I'll go ahead and close this, feel free to reach out if you have any other question.
