### ISSUE TITLE
java.lang.invoke.LambdaConversionException: Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair

### ISSUE THREAD

**Issue by Baratam** [aws/aws-sdk-java-v2#1795]
## Describe the issue
I have two lambdas, the 1st lambda invokes the 2nd and I am using aws sdk bom to 2.13.5 (software.amazon.awssdk) in my pom, but unable to invoke a lambda from another lambda. received the below error while lambda invoke.I used the same piece of java code which is mentioned in the aws docs, but still getting the error.
The same mentioned in aws docs: https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/setup-project-maven.html
I couldn't reopen the above thread, so creating this new thread, i also reached aws support, but the support engineer suggested to post the issue over here.
Below are the dependencies i used in my pom, I also tried all scenarios discussed in this chain : https://github.com/aws/aws-sdk-java-v2/issues/652 (updating httpcore, httclient etc..but nothing works)
**Please find the attached zip for dependencies used in my project.**
**Please find the attached zip for java code used in my project to invoke .**
**Please find the attached image for my mvn dependency tree .**

**Error while invoking lambda:**
{
  "errorMessage": "call site initialization exception",
  "errorType": "java.lang.BootstrapMethodError",
  "stackTrace": [
    "java.lang.invoke.CallSite.makeSite(CallSite.java:341)",
    "java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)",
    "java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)",
    "software.amazon.awssdk.http.apache.ApacheHttpClient.transformHeaders(ApacheHttpClient.java:268)",
    "software.amazon.awssdk.http.apache.ApacheHttpClient.createResponse(ApacheHttpClient.java:253)",
    "software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:233)",
    "software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:98)",
    "software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:213)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:66)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:51)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:35)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)",
    "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)",
    "software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)",
    "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)",
    "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)",
"software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)",
    "software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)",
    "software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)",
    "software.amazon.awssdk.services.lambda.DefaultLambdaClient.invoke(DefaultLambdaClient.java:1645)",
    "com.abnamro.nl.solution.polar.application.utils.AwsLambdaInvokeUtil.invoke(AwsLambdaInvokeUtil.java:80)",
    "com.abnamro.nl.solution.polar.application.controllers.SegmentController.getSegments(SegmentController.java:64)",
    "com.abnamro.nl.solution.polar.application.GetSegmentsApplication.handleRequest(GetSegmentsApplication.java:65)",
    "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
    "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
    "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
    "java.lang.reflect.Method.invoke(Method.java:498)"
  ],
  "cause": {
    "errorMessage": "Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair",
    "errorType": "java.lang.invoke.LambdaConversionException",
    "stackTrace": [
      "java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:233)",
      "java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:303)",
      "java.lang.invoke.CallSite.makeSite(CallSite.java:302)",
      "java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:307)",
      "java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:297)",
      "software.amazon.awssdk.http.apache.ApacheHttpClient.transformHeaders(ApacheHttpClient.java:268)",
      "software.amazon.awssdk.http.apache.ApacheHttpClient.createResponse(ApacheHttpClient.java:253)",
      "software.amazon.awssdk.http.apache.ApacheHttpClient.execute(ApacheHttpClient.java:233)",
      "software.amazon.awssdk.http.apache.ApacheHttpClient.access$500(ApacheHttpClient.java:98)",
      "software.amazon.awssdk.http.apache.ApacheHttpClient$1.call(ApacheHttpClient.java:213)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.executeHttpRequest(MakeHttpRequestStage.java:66)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:51)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.MakeHttpRequestStage.execute(MakeHttpRequestStage.java:35)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)",
      "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)",
      "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)",
      "software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)",
      "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)",
      "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)",
      "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)",
(https://github.com/aws/aws-sdk-java-v2/files/4552736/dependencies.xml.zip)
"software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)",
      "software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)",
      "software.amazon.awssdk.services.lambda.DefaultLambdaClient.invoke(DefaultLambdaClient.java:1645)",
      "com.abnamro.nl.solution.polar.application.utils.AwsLambdaInvokeUtil.invoke(AwsLambdaInvokeUtil.java:80)",
      "com.abnamro.nl.solution.polar.application.controllers.SegmentController.getSegments(SegmentController.java:64)",
      "com.abnamro.nl.solution.polar.application.GetSegmentsApplication.handleRequest(GetSegmentsApplication.java:65)",
      "sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)",
      "sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)",
      "sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)",
      "java.lang.reflect.Method.invoke(Method.java:498)"
    ]
  }
}

## Steps to Reproduce
Create two lambdas within VPC, invoke 2nd lambda from 1st lambda.
Use these in pom groupid: software.amazon.awssdk, version: 2.13.5, artifactId:bom

## Current Behavior
**Receives error:**
"errorMessage": "Invalid receiver type interface org.apache.http.Header; not a subtype of implementation type interface org.apache.http.NameValuePair",
"errorType": "java.lang.invoke.LambdaConversionException",
**Please find the attached zip for dependencies used in my project.**
## Your Environment
* AWS Java SDK version used:  groupid: software.amazon.awssdk, version: 2.13.5, artifactId:bom
* JDK version used: v8
* Operating System and version: AWS lambda service
**Please find the attached zip for dependencies used in my project.**
**Please find the attached zip for java code used in my project to invoke .**
**Please find the attached image for my mvn dependency tree .**

[dependencies.xml.zip](https://github.com/aws/aws-sdk-java-v2/files/4552781/dependencies.xml.zip)
[AwsLambdaInvokeUtil.java.zip](https://github.com/aws/aws-sdk-java-v2/files/4552804/AwsLambdaInvokeUtil.java.zip)
<img width="1100" alt="mvn dpn tree" src="https://user-images.githubusercontent.com/8440489/80617978-0801d080-8a43-11ea-96db-e231a4cf3f2e.png">

**Comment by bmaizels** [comment]
The error itself looks related to this change : https://github.com/apache/httpcomponents-core/commit/6abc8da24f906fb3c72a8175008ee3414d9a03c3

The SDK was compiled using a version of httpcore that was built after this change, and your lambda appears to be executing code from a dependency that was built before this change, hence the incompatability.

**Comment by Baratam** [comment]
hi @bmaizels 
Thanks for the quick reply but could you please let me what needs to be done now to resolve my issue
 i used httpcore version 4.4.13.

**Comment by bmaizels** [comment]
That's the rub, I believe that you believe you are using httpcore 4.4.13, but the error message is clearly telling us you are not. I believe any version >=4.4.9 would work, but you must be actually using a version earlier than that. I would focus on debugging your dependency tree, or finding a way to prove definitively that you are in fact using 4.4.13. The screenshot you gave shows httpcore version 4.4.4

**Comment by Baratam** [comment]
that's good cath @bmaizels , i will check this, i have to force it to use 4.4.9

**Comment by bmaizels** [comment]
@Baratam please use whatever version apache httpclient lists as their dependencies. So, for example, if you are using httpclient 4.5.9 then you should be using httpcore version 4.4.11. Always force both versions together.

**Comment by Baratam** [comment]
hi @bmaizels 
the httpcore 4.4.4 is downloaded because of I am using aws x-ray 2.4.0, after removing the bom of x-ray, the issue is solved and able to invoke the lambda.
<dependencyManagement>
	  <dependencies>
	    <dependency>
	      <groupId>com.amazonaws</groupId>
	      <artifactId>aws-xray-recorder-sdk-bom</artifactId>
	      <version>2.4.0</version>
	      <type>pom</type>
	      <scope>import</scope>
	    </dependency>
	  </dependencies>
	</dependencyManagement>

**Comment by bmaizels** [comment]
Awesome, thanks for getting back to us. Good luck!

**Comment by Baratam** [comment]
yes, thanks @bmaizels for the very quick responses. 
i am doing this change for a different issue i.e. lambda to lambda invocation time which is taking 3secs. its been suggested by aws support engineer to upgrade our aws sdk version form v1.xx.xxx to v2.xx.xx to resolve the lambda invocation time, i will post the issue in detail if it is allowed in this thread ? otherwise i will create a new thread & continue there.

**Comment by bmaizels** [comment]
@Baratam Please create a new thread, thanks.

**Comment by raviranjandutta** [comment]
add this in pom.xml.  it will fix the error.

<dependency>
    <groupId>org.apache.httpcomponents</groupId>
    <artifactId>httpcore</artifactId>
    <version>4.4.9</version>
</dependency>
