### ISSUE TITLE
DynamoDB Enhanced Client - QueryConditional does not support reserved characters : and #

### ISSUE THREAD

**Issue by dhegberg** [aws/aws-sdk-java-v2#1806]
## Describe the bug
The reserved characters : and # are not "scrubbed" from expression key/value mappers when the QueryConditional calls cleanAttributeName

Example QueryConditional:
https://github.com/aws/aws-sdk-java-v2/blob/1a1eb6e8a1359210d14b06ec6157b492de1f9b36/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/conditional/EqualToConditional.java#L36-L37

cleanAttributeName:
https://github.com/aws/aws-sdk-java-v2/blob/1a1eb6e8a1359210d14b06ec6157b492de1f9b36/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/EnhancedClientUtils.java#L48-L60

## Expected Behavior
Attribute names with : and # characters would be replaced with placeholders, allowing for successful query of table with those attribute names.

## Current Behavior
The reserved characters are not replaced, resulting in a 400 due to "ExpressionAttributeNames contains invalid key" during query request.

**Comment by bmaizels** [comment]
Thanks for the bug report. Working on a fix.
