### ISSUE TITLE
DynamoDB Enhanced: impossible to retrieve unprocessed items from BatchWriteResult when using async client

### ISSUE THREAD

**Issue by denyskonakhevych** [aws/aws-sdk-java-v2#1831]
Currently BatchWriteResult requires DynamoDbTable to retrieve unprocessed put or delete items.
So there is no way to retrieve this data with DynamoDbAsyncTable.

## Possible Solution
As a solution, instead of DynamoDbTable methods can accept MappedTableResource, just like it do for BatchGetResultPage::resultsForTable

## Your Environment
* AWS Java SDK version used: 2.13.14

**Comment by denyskonakhevych** [comment]
Added PR: https://github.com/aws/aws-sdk-java-v2/pull/1832

**Comment by debora-ito** [comment]
PR is being reviewed. Thank you for the contribution!

**Comment by debora-ito** [comment]
The fix is now available in SDK version `2.13.18`.
