### ISSUE TITLE
Mismatch between HttpStatusCode.THROTTLING (429) and S3 REST "SlowDown" (503)?

### ISSUE THREAD

**Issue by tijmenr** [aws/aws-sdk-java-v2#1834]
## Describe the issue
Class `software.amazon.awssdk.http.HttpStatusCode` defines a.o. the following HTTP response codes for SDK service calls:
```
THROTTLING = 429;
SERVICE_UNAVAILABLE = 503;
```

The first of these is used in `software.amazon.awssdk.core.exception.SdkServiceException`:
```
public boolean isThrottlingException() {
    return statusCode == HttpStatusCode.THROTTLING;
}
```

which propagates to `software.amazon.awssdk.core.retry.RetryUtils`:
```
public static boolean isThrottlingException(SdkException exception) {
    return isServiceException(exception) && toServiceException(exception).isThrottlingException();
}
```
which is used by `software.amazon.awssdk.core.internal.http.pipeline.stages.utils.RetryableStageHelper` in combination with `software.amazon.awssdk.core.retry.RetryPolicy`, to enable a different handling of throttling errors from other errors (in terms of retry count and backoff strategy). 

Looking at the S3 [List of Error Codes](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList), an S3 will reply not with HTTP 429, but with HTTP 503 if it wants the client to throttle (the list doesn't even mention 429):
```
ServiceUnavailable    Reduce your request rate.   503 Service Unavailable
SlowDown              Reduce your request rate.   503 Slow Down
```

HTTP 503 responses during large bursts of requests are indeed what I see on our on-premise S3 compliant Netapp StorageGrid.

Shouldn't HTTP 503 then also be considered a response requesting for throttling (rather than a more general service exception), and handled accordingly by the SDK?
 
## Steps to Reproduce

- Configure SDK client with a `RetryPolicy` of `RetryMode.LEGACY` (so throttling errors should not count against the maximum number of retries).
- Submit a sufficiently large burst of requests to an S3 compliant storage (so that the S3 will start responding with HTTP 503 to some requests).

## Current Behavior
Some requests fail due to `software.amazon.awssdk.services.s3.model.S3Exception: Please reduce your request rate. (Service: S3, Status Code: 503, Request ID: ...)`

## Desired Behavior
Throttling policy becomes effective, requests are retried (with increasing back-off) rather than failed after the normal retry count.

## Your Environment
* AWS Java SDK version used: 2.13.13
* JDK version used: OpenJDK 11.0.6
* Operating System and version: Linux x64

**Comment by debora-ito** [comment]
S3 uses 503 as code for rate limiting, but marking 503 as a throttling error in the SDK would be a change in behavior for all the other AWS services that send 503 as Service Unavailable, with possible repercussions in retry strategies. So I feel this is more of an issue with S3 not sending a 429 error code in this case. Does it make sense?

**Comment by varming** [comment]
FYI: SlowDown is on the list of throttling error codes. https://github.com/aws/aws-sdk-java-v2/blob/e971765bb6be61e3fb510357154279c555f7e521/core/aws-core/src/main/java/software/amazon/awssdk/awscore/internal/AwsErrorCode.java#L41, so the client should already consider 503 SlowDown a throttling exception.
