### ISSUE TITLE
Support colon (:) in profile names

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sdk-java-v2#1847]
This is a feature request from a customer using the JetBrains toolkit (https://github.com/aws/aws-toolkit-jetbrains/issues/1751)

They would like to be able to use a colon in their profile name to match the CLI:

```
aws s3 ls --profile foo:bar
2020-05-01 14:47:55 ajnbjanbjanbjanbjanbj
```

**Comment by debora-ito** [comment]
Marking as a feature request.

**Comment by jeffalder** [comment]
@abrooksv This is not a difficult PR - I did the last round: https://github.com/aws/aws-sdk-java-v2/pull/1538
