### ISSUE TITLE
S3: Presigned URLs with canned ACL missing `x-amz-acl` query parameter

### ISSUE THREAD

**Issue by markkolich** [aws/aws-sdk-java-v2#1849]
`Java 14.0.1+7 (OpenJDK Runtime Environment)`
`Linux (4.14.171-105.231.amzn1.x86_64)`

I'm attempting to migrate over to the SDK v2 Presigned URL generators added under https://github.com/aws/aws-sdk-java-v2/issues/203.

### Java SDK v1 (1.11.784)

In the SDK v1, I'm able to invoke `request.addRequestParameter()` which allows me to add custom request parameters to the request (such as `x-amz-acl=public-read`):

```java
final GeneratePresignedUrlRequest request =
  new GeneratePresignedUrlRequest("foo", "bar.jpg")
    .withMethod(HttpMethod.PUT)
    .withExpiration(new Date(...));

request.addRequestParameter("x-amz-acl", "public-read"); // <<--!!
```

This results in a presigned URL which looks like:

```
https://foo.s3.us-west-1.amazonaws.com/bar.jpg?
  x-amz-acl=public-read&
  X-Amz-Algorithm=AWS4-HMAC-SHA256&
  X-Amz-Date=20200518T221231Z&
  X-Amz-SignedHeaders=host&
  X-Amz-Expires=60&
  X-Amz-Credential=BAZ%2F20200518%2Fus-west-1%2Fs3%2Faws4_request&
  X-Amz-Signature=b677332742ac54c6a21bb827ac22376fdc674b06ae360bb63793b61666d774f9
```

Note the `x-amz-acl=public-read` query parameter, which allows me to apply a canned ACL to the object once uploaded.

### Java SDK v2 (2.13.19)

However, in the SDK v2, there does not appear to be way to attach such custom parameters to the presigned request. Instead, in an attempt to get the same canned ACL behavior, I'm setting `request.acl(ObjectCannedACL.PUBLIC_READ)` on my `PutObjectRequest`:

```java
final PutObjectRequest putObjectRequest = PutObjectRequest.builder()
  .bucket("foo")
  .key("bar.jpg")
  .acl(ObjectCannedACL.PUBLIC_READ) // <<--!!
  .build();

final PutObjectPresignRequest request = PutObjectPresignRequest.builder()
  .signatureDuration(Duration.ofMillis(...))
  .putObjectRequest(putObjectRequest)
  .build();
```

Unfortunately though, this does not generate an equivalent URL:

```
https://foo.s3.us-west-1.amazonaws.com/bar.jpg?
  X-Amz-Algorithm=AWS4-HMAC-SHA256&
  X-Amz-Date=20200518T221231Z&
  X-Amz-SignedHeaders=host%3Bx-amz-acl&
  X-Amz-Expires=60&
  X-Amz-Credential=BAZ%2F20200518%2Fus-west-1%2Fs3%2Faws4_request&
  X-Amz-Signature=af576cc66199a649df8010aceb86e44b3d16a347438be39cb0df0dd9579b9684
```

Note the absence of the `x-amz-acl=public-read` query parameter on the presigned URL generated by the Java SDK v2 (2.13.19), even though I have set `.acl(ObjectCannedACL.PUBLIC_READ)` on my `PutObjectRequest`.

Unfortunately, I now have to set the `x-amz-acl: public-read` HTTP request header on the `PUT` in order for this presigned URL to work, which does not match the behavior of the SDK v1.

Is it expected that setting `.acl(ObjectCannedACL.PUBLIC_READ)` on the SDK v2 `PutObjectRequest` does not set the `x-amz-acl=public-read` query parameter on the presigned request URL? Is there anyway to override this behavior? For parity with the SDK v1, I conjecture the SDK v2 should also set the `x-amz-acl` query parameter on the generated presigned URL when using a canned ACL.

**Comment by markkolich** [comment]
Should the `location` here be `querystring`?

https://github.com/aws/aws-sdk-java-v2/blob/24f99c8a7bcc545e6f3fffcc75c460a94b870be9/services/s3/src/main/resources/codegen-resources/service-2.json#L6834-L6839

**Comment by debora-ito** [comment]
@markkolich yes I can repro the issue, thank you for the detailed report. Marking as a bug.

**Comment by debora-ito** [comment]
Hey @markkolich actually there is a way to add the `x-amz-acl` query param to the PutObjectRequest: using `AwsRequestOverrideConfiguration` -
```
AwsRequestOverrideConfiguration override = AwsRequestOverrideConfiguration.builder()
        .putRawQueryParameter("x-amz-acl", "private")
        .build();

PutObjectRequest putObjectRequest = PutObjectRequest.builder()
        .bucket(BUCKET)
        .key(KEY)
        .overrideConfiguration(override)
        .build();

PutObjectPresignRequest request = PutObjectPresignRequest.builder()
        .signatureDuration(Duration.ofMinutes(5))
        .putObjectRequest(putObjectRequest)
        .build();
```

Using `.acl()` in the PutObjectRequest adds `x-amz-acl` as a request header, which does not work for presigned urls. Adding it as a query param seems to work just like it works in v1. 

I'm changing this to a guidance issue, as I'm not sure if this is the expected behavior of S3 presigned url. I will confirm with the S3 service team and update here when I hear back. I'm sorry it took this long to find a solution.

**Comment by markkolich** [comment]
Thanks @debora-ito!

That worked perfectly &mdash; tested and verified with the SDK v2 version `2.13.35`.

Based on your comments re: waiting for guidance, I'll leave this open. My immediate issue is now fixed, you're welcome to close this as you see fit.

**Comment by debora-ito** [comment]
@markkolich I'll go ahead and close this issue, as the operation is working fine now. If I have more information about the presigner behavior I'll post it here.

**Comment by Deepakj333** [comment]
Hi i am using AWS v3 unable to upload object to s3 with public access using presigned URL

**Comment by cihati** [comment]
I just hit this issue with the 2.15.50 version of the SDK. In my opinion, this should not be closed. @debora-ito did provide a way to mitigate the symptom and present an alternative, but the actual issue still persists.

**Comment by riteshs-cashify** [comment]
Issue is not resolved yet. I'm using sdk with version 1.11.201. @debora-ito provided patch class(AwsRequestOverrideConfiguration) is also not available in this version.

**Comment by igorrohal** [comment]
Unfortunately, this issue is still present in version `2.17.191`

**Comment by mamundh** [comment]
Unfortunately, this issue is still preset(2023) in version 2.20.45

**Comment by hanswesterbeek** [comment]
Still present in today's latest version: `2.26.20`
