### ISSUE TITLE
 overrideConfiguration should merge when called multiple times.

### ISSUE THREAD

**Issue by anuraaga** [aws/aws-sdk-java-v2#1850]
## Describe the Feature

`overrideConfiguration` should merge when called multiple times.

## Is your Feature Request related to a problem?

Currently, it is not possible for multiple frameworks to configure an SDK client, for example to add an `ExecutionInterceptor` that does not have a no-args constructor for use with service loader, the last one wins. 

This can be quite problematic, for example if using the opentelemetry agent, it injects bytecode during the `build()` call which calls this

https://github.com/open-telemetry/opentelemetry-auto-instr-java/blob/master/instrumentation/aws-sdk/aws-sdk-2.2/src/main/java8/io/opentelemetry/auto/instrumentation/awssdk/v2_2/TracingExecutionInterceptor.java#L109

so any use using the agent has absolutely no way of setting configuration overrides, it's always overwritten by the agent.

## Proposed Solution

Multiple calls to `overrideConfiguration` could merge instead of replace configs. This may be backwards incompatible, but I feel that the current behavior is generally a problem rather than useful

## Additional Context

I would like to add my own execution interceptors in addition to using the one from the agent, but it's not possible.

- [X] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by millems** [comment]
It's intended that you to pass the `ClientOverrideConfiguration.Builder` to all components that need to configure the client, and only actually set the configuration on the client when you're done initializing the configuration. Is this not sufficient?

**Comment by anuraaga** [comment]
Thanks for the comment - that does actually seem like a reasonable API too. After thinking, I guess it's the agent being too hacky rather than something to change in this API so it's probably fine as is.

For reference, I'm working around the hack with more hacks in the agent in https://github.com/open-telemetry/opentelemetry-auto-instr-java/pull/453 :)

**Comment by millems** [comment]
Fixing hacks with hacks is a time honored tradition!
