### ISSUE TITLE
Support parallel scan in DynamoDB Enhanced client

### ISSUE THREAD

**Issue by Gtofig** [aws/aws-sdk-java-v2#1851]
## Describe the Feature
Allow parallel scan via DynamoDBEnhanced client and modify ScanEnhancedRequest to support totalSegments and segment parameters.

## Is your Feature Request related to a problem?
Unable to do parallel scan using DynamoDB enhanced client

## Proposed Solution
Underlying DynamoDbClient already supports parallel scan, so shouldn't be hard to wire in

## Describe alternatives you've considered
I can do parallel scan using DynamoDbClient directly, but then I lose some nice things like automatic marshalling of items to the domain class.

- [ ] I may be able to implement this feature request

**Comment by debora-ito** [comment]
Noted, marking as a feature request.

**Comment by driverpt** [comment]
Do we have any ETA on this?

**Comment by debora-ito** [comment]
Support for segment and totalSegments in ScanEnhancedRequest was added via #2614.
