### ISSUE TITLE
how to set a listener at the sqs 

### ISSUE THREAD

**Issue by huoshidehua** [aws/aws-sdk-java-v2#1864]
## Describe the issue

how to set a listener at the sqs 

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@huoshidehua please refer to the SQS documentation: https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-how-it-works.html

For service specific questions like this we recommend you post it in the [AWS Developer Forums](https://forums.aws.amazon.com/forum.jspa?forumID=12) or in communities like StackOverflow.

If you have any questions or issues using the AWS SDK for Java, feel free to reopen.
