### ISSUE TITLE
Lambda invocation throws ApiCallAttemptTimeoutException with no logs in CloudWatch/Xray

### ISSUE THREAD

**Issue by brenden-t-r** [aws/aws-sdk-java-v2#1873]
## Describe the bug

I'm receiving occasional timeouts when attempting Lambda invocations from Java. These happen seemingly randomly, and a retry with the same input will result in it working again. What's odd is there are no logs in CloudWatch or even in X-Ray showing any indication that the invocation request was received by AWS. However, on my side the invocation still waits the full 15 minutes before receiving the timeout error. Worse is that after this we have no way of knowing if this was the result of the function not being invoked at all or if the function actually took >15 minutes to complete.

Lambda invocation - ApiCallAttemptTimeoutException with no logs

Here are some code excerpts:

```
ClientOverrideConfiguration configuration = ClientOverrideConfiguration.builder()
				.retryPolicy(RetryPolicy.builder().numRetries(2).build())
				.apiCallAttemptTimeout(Duration.ofMinutes(15))
				.apiCallTimeout(Duration.ofMinutes(15))
				.build();
lambdaClient = LambdaClient.builder()
				.region(region)
				.credentialsProvider(stsCredentialsProvider)
				.overrideConfiguration(configuration)
				.httpClient(new JavaHttpClient())
				.build(); 
InvokeRequest request = InvokeRequest.builder()
					.functionName(functionName)
					.invocationType(InvocationType.REQUEST_RESPONSE)
					.payload(SdkBytes.fromUtf8String(payload))
					.build();
lambdaClient.invoke(request);
```

And we're using this HttpClient implementation. 

```
class JavaHttpClient implements SdkHttpClient {

	private HttpClient client;

	JavaHttpClient() {
		client = HttpClient.newBuilder()
				.connectTimeout(Duration.ofSeconds(30))
				.version(HttpClient.Version.HTTP_2)
				.build();
	}

	@Override
	public ExecutableHttpRequest prepareRequest(HttpExecuteRequest request) {
		HttpRequest.Builder builder = HttpRequest.newBuilder()
				.uri(request.httpRequest().getUri())
				.method(request.httpRequest().method().name(), HttpRequest.BodyPublishers.ofInputStream(() -> request.contentStreamProvider().get().newStream()))
				.timeout(Duration.ofMinutes(14));
		request.httpRequest().headers().forEach((k, v) -> {
			if (!List.of("host").contains(k.toLowerCase())) {
				builder.header(k, String.join(";", v));
			}
		});
		HttpRequest req = builder.build();
		var bh = HttpResponse.BodyHandlers.ofInputStream();
		return new ExecutableHttpRequest() {

			AbortableInputStream canCancel;

			@Override
			public void abort() {
				try {
					if (canCancel != null) canCancel.abort();
				} catch (Exception e) {
					log.error(e.getLocalizedMessage(), e);
				}
			}

			@Override
			public HttpExecuteResponse call() throws IOException {
				try {
					HttpResponse<InputStream> resp = client.send(req, bh);
					canCancel = AbortableInputStream.create(resp.body());
					return HttpExecuteResponse.builder()
							.response(SdkHttpFullResponse.builder()
									.headers(resp.headers().map())
									.content(canCancel)
									.statusCode(resp.statusCode())
									.build())
							.responseBody(canCancel)
							.build();
				} catch (InterruptedException e) {
					throw new IOException(e);
				}
			}
		};
	}

	@Override
	public void close() {
	}
}
```

## Expected Behavior

Should invoke lambda function and show success or failure logs in CloudWatch and X-Ray. 

## Current Behavior

Currently no logs are recorded in CloudWatch or X-Ray when this intermittent issue occurs. A retry of the same function with same payload will result in success.

## Steps to Reproduce

Difficult to reproduce since it is intermittent.

## Your Environment

* AWS Java SDK version used: SDK 2.7.28
* JDK version used: JDK 11
* Operating System and version: Ubuntu EC2 machine

**Comment by zoewangg** [comment]
If there were no Lambda logs, my guess is that the request did not reach the service side. I see you have `connectionTimeout` set to 30 seconds, which indicates the request was either reusing a connection from connection pool or able to establish a new connection to the service within 30 seconds. 

Also`HttpRequest#timeout`, the timeout for receiving the response,  is set to 14 mins, but you didn't get `HttpTimeoutException`, which further suggests that the request might not be sent to the service.

I'd recommend enabling http wirelogs and SDK request logging, which will provide more insights.

https://github.com/aws/aws-sdk-java-v2/blob/d0e6099e03e360d654986663437faea25c3c8940/core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkStandardLogger.java#L31

**Comment by brenden-t-r** [comment]
Thank @zoewangg, those are good suggestions. I also agree that likely AWS isn't receiving the request for whatever reason. In my case, I disabled the use of our custom HttpClient as no one on the team was sure what the purpose of it was. With that removed the issue appeared to go away (hard to tell due to intermittency). If it returns, I will enable the logging you suggested.
