### ISSUE TITLE
Ability to customize stsClient in `StsWebIdentityCredentialsProvider` 

### ISSUE THREAD

**Issue by marcinczeczko** [aws/aws-sdk-java-v2#1881]
At the moment if using client for any AWS service with `WebIdentityTokenFileCredentialsProvider` as credentials provider it forces to use sync HTTP client. Additionally, STS client instead always assumes region based on the `DefaultAwsRegionProviderChain` without the ability to override it via the code. In majority cases it's fine as it can be controlled at some extent via system properties or env variables. However, the use case I have
-  Using e.g. DynamoDB Async client with `WebIdentityTokenFileCredentialsProvider` as credentials provider
- It forces me to add any sync HTTP client (URL connection or Apache HTTP client) on the classpath, as the `StsWebIdentityCredentialsProviderFactory` uses sync client only.
- Additionally, if my code uses Dynamodb client has configured that client to use specific region via the code, I need to repeat the same via sysprops or env vars for sts client.
- For local testing I can't define STS endpoint override as there is no way to customize/configure sts client used by credentials provider.

## Describe the Feature
Ability to specify STS client built in my code or STS client builder in the `WebIdentityTokenFileCredentialsProvider.Builder`

## Is your Feature Request related to a problem?
Explained at the top

## Proposed Solution
- The best would be to extend the `WebIdentityTokenFileCredentialsProvider.Builder` to accept stsClient built somewhere else or stsClient builder instead, so I can build either sync or async client.

## Describe alternatives you've considered
N/A

## Additional Context
I was implementing Quarkus extensions to support AWS SDK v2 client and the web identity token file credentials provider causes troubles to make it easily configurable. And since `StsWebIdentityCredentialsProviderFactory` is final with private methods it's hard to override it's logic to control how stsClient is being created.

- [x] I may be able to implement this feature request

## Your Environment
* AWS Java SDK version used: 2.13.27
* JDK version used: 1.8, 11, Graalvm 19.3.1
* Operating System and version: macOs Catalina

**Comment by debora-ito** [comment]
It's a reasonable ask, marking as a feature request.

**Comment by nhoughto** [comment]
It also prevents using a non-AWS STS endpoint, we are trying to override it for local testing (calling localstack) and the current approach makes that hard.

**Comment by hawkpatrick** [comment]
We have the same problem when using IAM RDS authentication. We use WebIdentityTokenFileCredentialsProvider to get the credentials but we now and then see problems when calling the STS API (socket timeout). This has a tremendous impact as our application is not able to communicate with the database anymore. 

The AWS support says: 
ClientConfiguration

**Comment by sp13ceg** [comment]
Just checking. Is there any update on this request ?
