### ISSUE TITLE
software.amazon.awssdk.services.s3.S3AsyncClient#putObject does not detect Content-Type

### ISSUE THREAD

**Issue by adrian-skybaker** [aws/aws-sdk-java-v2#1883]
If the synchronous S3 client is used to put an object into a bucket, the `Content-Type` metadata property is set based an auto-detection of mime type (`software.amazon.awssdk.core.sync.RequestBody#fromFile(java.nio.file.Path)`).

If the asynchronous client is used to put the same object, it's `Content-Type` is always set to `binary/octet-stream`, no auto-detection is done.

* AWS Java SDK version used: 2.13.23

**Comment by debora-ito** [comment]
Can you provide a reproducible code sample?

**Comment by adrian-skybaker** [comment]
No, sorry. All that's required though is a call to `software.amazon.awssdk.services.s3.S3AsyncClient#putObject`

**Comment by debora-ito** [comment]
@adrian-skybaker I finally got some time to repro this and I can confirm I see the issue, thank you for reporting it.

**Comment by SergeyBrenko** [comment]
@debora-ito do you any updates on this issue?

**Comment by debora-ito** [comment]
@SergeyBrenko no updates at this time.

**Comment by Quanzzzz** [comment]
A new support to fix this has been added in #2239.
