### ISSUE TITLE
Unable to load AWS credentials from any provider in the chain

### ISSUE THREAD

**Issue by poonamtr** [aws/aws-sdk-java-v2#189]
I have my application running on EC2. Trying to access dynamoDB from my Java application. But for every operation, I get "Unable to load AWS credentials from any provider in the chain".

* I have added dynamoDB permissions in the IAM role that gets attached to EC2 instance
* And also configured EC2 to assume that role in trust relationship.

Code:
```
try {
            AWSCredentialsProvider provider = new DefaultAWSCredentialsProviderChain();
            AWSCredentials credentials = provider.getCredentials();
            if(credentials != null) {
                LOG.info("Credentials Key: " + credentials.getAWSAccessKeyId());
                LOG.info("Credentials secret: " + credentials.getAWSSecretKey());
            }
        } catch (Exception e) {
            LOG.info("Exception in credentials cause:" + e.getCause() +";message: " + e.getMessage() +";stack: " +e.getStackTrace());
        }
```
The getCredentials() line itself throws an Exception with message: "Unable to load AWS credentials from any provider in the chain".
If I do not try to get credentials here and pass it to the DynamoDB client: 
```
dynamoDBClient = builder.withEndpointConfiguration(new 
                AwsClientBuilder.EndpointConfiguration(url, region.getName()))
                .withCredentials(credentialProvider())
                .withClientConfiguration(clientConfig)
                .build();
```

Then it throws the same exception when I try to do any operation.

I tried setting up the proxy too: 

```
ClientConfiguration clientConfig = new ClientConfiguration();
        clientConfig.setProxyHost("yyy");
        clientConfig.setProxyPort(port);
        clientConfig.setNonProxyHosts("xxx");
        clientConfig.setProtocol(Protocol.HTTP);
```

and then passing it while creating the client:

```        
dynamoDBClient = builder.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(url, region.getName()))
                .withCredentials(credentialProvider())
                .withClientConfiguration(clientConfig)
                .build();
```
But no success.

Can someone @here guide me what am I missing here?

**Comment by MatteCarra** [comment]
Try with
`DefaultCredentialsProvider.builder().build()`
It's working fine for me on ec2

**Comment by MatteCarra** [comment]
I think you are not using aws-sdk-java-v2
It looks like https://github.com/aws/aws-sdk-java

**Comment by poonamtr** [comment]
Hi Matte,

Thanks for response.
I am using aws-sdk-java-v2.

But digging some more into this, I realized that I am unable to access the
EC2 metadata information from my app running on EC2.
Doing curl for the metadata endpoint on the actual EC2 box where my app is
running is working fine.

**Comment by millems** [comment]
Please let us know if this is still an issue.
