### ISSUE TITLE
SQS's ReceiveMessageRequest.Builder#AttributeName generated with wrong arg type

### ISSUE THREAD

**Issue by rhernandez35** [aws/aws-sdk-java-v2#1892]
## Describe the bug
[`ReceiveMessageRequest.Builder#attributeNames`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/ReceiveMessageRequest.Builder.html#attributeNames-java.util.Collection-) accepts a single `QueueAttributeName` or `Collection<QueueAttributeName>`. This enum contains queue attributes and not the [message attribute names](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/MessageSystemAttributeName.html) described in the documentation. If you want message attributes with your receive requests, you're forced to use `QueueAttributeName.ALL` or `attributeNamesWithStrings`.

## Expected Behavior
The API should accept [MessageSystemAttributeName](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/MessageSystemAttributeName.html) values.

## Steps to Reproduce
see javadocs linked above

## Your Environment

* AWS Java SDK version used: latest (see latest javadocs linked above)
* JDK version used: irrelevant
* Operating System and version: irrelevant

**Comment by rhernandez35** [comment]
[SQS's ReceiveMessage API docs](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_ReceiveMessage.html) show that all of the values for `QueueAttributeName` and `MessageSystemAttributeName` are valid for this API. Maybe you need to generate a combined enum or overloads for both types (which is a bit unwieldy).

**Comment by debora-ito** [comment]
Hi @rhernandez35, this was reported in https://github.com/aws/aws-sdk-java-v2/issues/1117. As mentioned over there the service team owns the model but it's been more than one year without a response from them, let me check again with the service team.

Let's keep track of this in the other issue.
