### ISSUE TITLE
[Question] Using RetryPolicy with CloudWatchLogsClient together  

### ISSUE THREAD

**Issue by ShahmirAhmed** [aws/aws-sdk-java-v2#1894]
Hey team, I had a general question on the usage of using a `RetryPolicy` object with a `CloudWatchLogsClient` object. Essentially, I am looking to use a `CloudWatchLogsClient` to send logs to my CloudWatch instance (Log Group & Log Stream) using the [putLogEvents() function](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudwatchlogs/CloudWatchLogsClient.html#putLogEvents-software.amazon.awssdk.services.cloudwatchlogs.model.PutLogEventsRequest-) and I wanted to configure a `RetryPolicy` so that whenever any error/malfunction/issue occurs and there is a halt to publish logs, I can retry sending those logs that may have gotten dropped. So I'm wondering, how does one attach a `RetryPolicy` to their specific `CloudWatchLogsClient` that sends logs? 

Edit:
Also I've taken a look at the [AWS code examples repository](https://github.com/awsdocs/aws-doc-sdk-examples) and couldn't find any examples of using the `RetryPolicy`. If you have any code samples/examples of using the `RetryPolicy`, I would appreciate it if you could share those with me.

Edit pt. 2:
Does the [putLogEvents() function](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cloudwatchlogs/CloudWatchLogsClient.html#putLogEvents-software.amazon.awssdk.services.cloudwatchlogs.model.PutLogEventsRequest-) have its own retry default configurations when a log gets dropped or there is some throttling to the network?

## Your Environment

* AWS Java SDK version used: v2.13.15
* JDK version used: Java 11
* Operating System and version: macOS Mojave v10.14.6

**Comment by debora-ito** [comment]
Hi @ShahmirAhmed, thank you for reaching out. The SDK does have a default retry behavior, take a look at [SdkRetryCondition](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/conditions/SdkRetryCondition.java) and [SdkDefaultRetrySetting](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java) to see the list of retryable error codes and exceptions. So depending on the error you're seeing with putLogEvents() maybe the request is being retried already.

You can customize your retry policy in the client level, by specifying a [RetryPolicy](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/retry/RetryPolicy.html) via `ClientOverrideConfiguration`:
```
CloudWatchLogsClient client = CloudWatchLogsClient.builder()
                .overrideConfiguration(c -> c.retryPolicy(RetryPolicy.builder()
                                .numRetries(5)
                                .build()))
                .build();
```

This is a good call-out on the lack of examples for the SDK for Java 2.x, we will work on more guides and examples.

**Comment by ShahmirAhmed** [comment]
Thank you for the assistance, I found this to be the approach that I took. Closing the ticket now
