### ISSUE TITLE
DynamoDbEnhancedClient: @DynamoDBGeneratedUuid support

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#1919]
From https://github.com/aws/aws-sdk-java-v2/issues/35:

V1 can automatically generate UUIDs for newly created records with the @DynamoDBGeneratedUuid annotation. This could be added as an extension to V2.

**Comment by debora-ito** [comment]
Implemented via PR https://github.com/aws/aws-sdk-java-v2/pull/4810, released in SDK version `2.23.5`.
