### ISSUE TITLE
DynamoDbEnhancedClient: @DynamoDBAutoGeneratedTimestamp support

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#1920]
From https://github.com/aws/aws-sdk-java-v2/issues/35:

V1 can automatically generate timestamps for newly created or updated records with the @DynamoDBAutoGeneratedTimestamp annotation. This could be added as an extension to V2.

**Comment by gakinson** [comment]
Hello,

Curious what your timeline is on this?

Thank you,
Geoffrey Kinson

**Comment by gakinson** [comment]
Hello,

I created an implementation for this, feel free to modify and integrate into your SDK. Works the same as the v 1.11 DynamoDB Mapper implementation.

https://github.com/gakinson/dyanamodb-enhanced-DynamoDbAutoGeneratedTimestamp-annotation

Thank you,
Geoffrey Kinson

**Comment by gakinson** [comment]
Just wanted to add a note on my previous implementation, the Strategy ALWAYS does not work because I was unable to set an update expression on the WriteModification since it only supports the updated item and CONDITIONAL expressions. 

Do you plan on supporting update expressions on the WriteModification class?

**Comment by bmaizels** [comment]
Hi @gakinson , can you explain why you needed to be able to modify the update expression instead of just providing an updated item map with the timestamp set in it? UpdateItem for example will take the updated item and build an update expression from it.

**Comment by gakinson** [comment]
Hello @bmaizels , 

I might be wrong about it, but for the strategy CREATE you need to only set the timestamp on the creation of an  object which would require an update expression such as "SET CreationTimestamp = if_not_exists(CreationTimestamp, :t)" to only place the value if it does not exist.

If you were to just return the updated item then you would overwrite the original timestamp.

**Comment by bmaizels** [comment]
@gakinson, Oh right, yes, we need to support if_not_exists , I remember now. Thanks for the reminder! I've refreshed this in our backlog, stay tuned.

**Comment by bmaizels** [comment]
@gakinson Just to confirm, it's actually CREATE that is broken because that depends on 'if_not_exists', whereas ALWAYS is supposed to overwrite it every time there is an update and should be achievable using the current extension framework?

**Comment by gakinson** [comment]
@bmaizels Yes, the CREATE is broken, but the ALWAYS works fine since it is always a replace.

For CREATE, we need to support if_not_exists which falls into an update expression instead of what is currently supported which are conditional expressions.

**Comment by vahAAA** [comment]
any news on this?

**Comment by OsmanthusPi** [comment]
keep monitoring official support.

**Comment by bmaizels** [comment]
We haven't delivered this annotation yet but I wanted to point out that 'if_not_exists' behavior is now supported as per https://github.com/aws/aws-sdk-java-v2/pull/2076

**Comment by radhag** [comment]
@bmaizels 

What is the timeline on delivering this annotation? I think this is a pretty widely used feature.

**Comment by RushinNaik** [comment]
Please let us know about the timleline for this. Thanks.

**Comment by blindpirate** [comment]
+1

**Comment by millems** [comment]
Sorry, I can confirm that this is in our backlog, but we aren't able to commit to a timeline for when it will be released.
