### ISSUE TITLE
Resiliency Algorithms

### ISSUE THREAD

**Issue by mohanr** [aws/aws-sdk-java-v2#1922]
Pluggable algorithms using https://github.com/resilience4j/resilience4j

## Describe the Feature
There is a backoff strategy built into the JMS library. More algorithms for resiliency from a library
like https://github.com/resilience4j/resilience4j are needed.

## Additional Context
There may be some support for Resiliency4J  that I am not aware of and support for such additional
algorithms may be needed for interactions with many services.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Transferred the issue to AWS SDK for Java 2.x repository.

Take a look at the [CONTRIBUTING](https://github.com/aws/aws-sdk-java-v2/blob/master/CONTRIBUTING.md) page.

**Comment by millems** [comment]
Do you have an example of how you would expect this to be implemented in the SDK? We have resiliency built into the SDK, and it can be modified using the [retry policy](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.Builder.html#retryPolicy-software.amazon.awssdk.core.retry.RetryPolicy-). You can use resilience4j if you want to build your own retry policy, for whatever reason.
