### ISSUE TITLE
S3 HeadObject throws S3Exception: null instead of NoSuchKeyException when no object exists.

### ISSUE THREAD

**Issue by dhegberg** [aws/aws-sdk-java-v2#1941]
## Expected Behavior
Documentation states HeadObject will throw NoSuchKeyException if the object does not exist.

## Current Behavior
HeadObject throws S3Exception: null instead.

## Steps to Reproduce

For a key that does not exist.

            final HeadObjectRequest request = HeadObjectRequest.builder()
                    .bucket(bucket)
                    .key(objectKey)
                    .build();
            final HeadObjectResponse response = s3.headObject(request)

## Context
Documentation states HeadObject will throw NoSuchKeyException (https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#headObject-software.amazon.awssdk.services.s3.model.HeadObjectRequest-) but a S3Exception: null is thrown instead.

This is stated to be fixed in https://github.com/aws/aws-sdk-java-v2/issues/544

## Your Environment
* AWS Java SDK version used: 2.13.25

**Comment by debora-ito** [comment]
@dhegberg I was not able to reproduce, I get 
`Exception in thread "main" software.amazon.awssdk.services.s3.model.NoSuchKeyException: The specified key does not exist. (Service: S3, Status Code: 404, Request ID: xxx, Extended Request ID: null)`

Can you provide the full stacktrace with the error you're seeing?
And a code snippet showing how your s3 client is being constructed?

**Comment by dhegberg** [comment]
The s3 client is being created as part of a dagger module:

   @Provides
    @Singleton
    static S3Client getS3Client() {
        return S3Client.builder().build();
    }

Stack Trace (This is being run in a Java8 lambda):
`
software.amazon.awssdk.services.s3.model.S3Exception

Cause

{
  "errorMessage": "null (Service: S3, Status Code: 403, Request ID: null, Extended Request ID: D08D8ysH68NGgukI780pV3NZKFu06OQOIkP7H9q56MlnVlXgXaFgxPk1QSbienVjrjT9iPJmIvE=)",
  "errorType": "software.amazon.awssdk.services.s3.model.S3Exception",
  "stackTrace": [
    "software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)",
    "software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:106)",
    "software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:84)",
    "software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:42)",
    "software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler$Crc32ValidationResponseHandler.handle(AwsSyncClientHandler.java:94)",
    "software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$4(BaseClientHandler.java:214)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:73)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallAttemptTimeoutTrackingStage.execute(ApiCallAttemptTimeoutTrackingStage.java:42)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:77)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.TimeoutExceptionHandlingStage.execute(TimeoutExceptionHandlingStage.java:39)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:64)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.RetryableStage.execute(RetryableStage.java:34)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:56)",
    "software.amazon.awssdk.core.internal.http.StreamManagingStage.execute(StreamManagingStage.java:36)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.executeWithTimer(ApiCallTimeoutTrackingStage.java:80)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:60)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ApiCallTimeoutTrackingStage.execute(ApiCallTimeoutTrackingStage.java:42)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.RequestPipelineBuilder$ComposingRequestPipelineStage.execute(RequestPipelineBuilder.java:206)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:37)",
    "software.amazon.awssdk.core.internal.http.pipeline.stages.ExecutionFailureExceptionReportingStage.execute(ExecutionFailureExceptionReportingStage.java:26)",
    "software.amazon.awssdk.core.internal.http.AmazonSyncHttpClient$RequestExecutionBuilderImpl.execute(AmazonSyncHttpClient.java:189)",
    "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.invoke(BaseSyncClientHandler.java:121)",
    "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:147)",
    "software.amazon.awssdk.core.internal.handler.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:101)",
    "software.amazon.awssdk.core.client.handler.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)",
    "software.amazon.awssdk.awscore.client.handler.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:55)",
    "software.amazon.awssdk.services.s3.DefaultS3Client.headObject(DefaultS3Client.java:4080)"
`

**Comment by dhegberg** [comment]
This seems to be a problem with the execution environment rather than the client.

Local runs were successful, the issue only occurred in a Lambda.

**Comment by jeffzoch** [comment]
I actually have this exact issue. I run in EKS and am seeing this happen regularly.

**Comment by jeffzoch** [comment]
I should clarify that this request fails very frequently (think thousands of times per week) but also succeeds frequently. There are random 8 hour periods where we dont see one of them and then other 8 hour periods where we see 500 an hour.

**Comment by magJ** [comment]
For what it's worth, in my case at least, S3 seems to respond with these errors when specifying a non-existent versionId.  
So seems like a bug on the service side, rather than the client implementation.

**Comment by Dharmesh2015** [comment]
My application create files on S3 if its not exist , which is dependent  s3.headObject call , suddenly function started throwing error with null, any suggested solution ? we are running code through lambda

**Comment by makarthikeyan1** [comment]
happened to me when i used "us-east-1" instead of "us-east-2" where the bucket was located.

**Comment by fredex42** [comment]
In case anyone else finds it useful, I got this same error when I was updating a lambda to work with versioned objects. In my case, I needed to add the `s3:GetObjectVersion` permission to the lambda's role in order to fix.

**Comment by selalerercapitolis** [comment]
And I got it when I was using S3Proxy in a docker (out testing environment), was putting a file in S3 and the file key started with a slash /

**Comment by campidelli** [comment]
If it helps, I was having this issue with my Springboot v3 application when I tried to call `headBucket` using the async client. I think it was an authentication issue that was fixed after I added the following to my `pom.xml`:
````
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sso</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>ssooidc</artifactId>
        </dependency>
````

**Comment by reed53** [comment]
Was running into this, my fix was to add the ListBucket permission for the bucket I was trying to read from.
