### ISSUE TITLE
Support client calls fails with UnknownHostException

### ISSUE THREAD

**Issue by netzu** [aws/aws-sdk-java-v2#1952]
I'm getting UnknownHostException when calling support client methods. 

`Caused by: java.net.UnknownHostException: support.eu-west-1.amazonaws.com`

Command in terminal:
`ping support.eu-west-1.amazonaws.com`

results with: `support.eu-west-1.amazonaws.com: Name or service not known`

where the command `ping ec2.eu-west-1.amazonaws.com` resolves DNS name properly.

V1 of AWS SDK works fine.

AWS SDK: 2.10.86
Operating System: Ubuntu 18.04.4 LTS
JDK:  AdoptOpenJDK(build 1.8.0_252-b09)

**Comment by debora-ito** [comment]
Hi @netzu AWS Support has a single endpoint `support.us-east-1.amazonaws.com` according to the AWS Service endpoint docs: https://docs.aws.amazon.com/general/latest/gr/awssupport.html
