### ISSUE TITLE
Allow to get array from BytesWrapper without copying

### ISSUE THREAD

**Issue by mar-kolya** [aws/aws-sdk-java-v2#1959]
In performance sensitive applications in is important to reduce number of data-copies that happen during processing.
Unfortunately currently when we get data from S3 and then try to use response byte array we have to:
* Either do an array copy
* Get a readonly ByteBuffer - which doesn't provide access to array and forces us to do an array copy later

## Describe the Feature
Provide a method in `BytesWrapper` that allows users to get either underlying array directly or a non-read-only `ByteBuffer`

## Is your Feature Request related to a problem?
Current S3 client implementation does multiple data copies - this is just one more of them, and this reduces performace.

## Describe alternatives you've considered
Unfortunately there are not many alternatives: in some cases one needs access to arrays, for example if one tries top use JNI compression implementations.

## Additional Context

- [x] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
This is a reasonable feature request @mar-kolya, thank you for reporting it. If you submit a PR we will take a look.
