### ISSUE TITLE
DynamoDbEnhancedClient: Delete table operation

### ISSUE THREAD

**Issue by alexfuksenko-toast** [aws/aws-sdk-java-v2#1966]
The DynamoDbEnhancedClient returns a DynamoDbTable<T> that allows you to do various dynamodb operations, including createTable(), but there is no way to delete the table. 

This means for repeated cases, especially for integration tests, I need to maintain a DynamoDbClient and a DynamoDbEnhancedClient reference. 

Even the enhanced client unit tests need to use a the normal client for only delete table operations like:
https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/functionaltests/AsyncBasicQueryTest.java#L139

## Describe the Feature

I think it would be nice if the DynamoDbEnhancedClient was able to delete tables itself, either through the table reference or through the enhanced client

## Is your Feature Request related to a problem?

Awkward to create two different DynamoDbClients (enhanced and regular for usage)

## Additional Context

- [x] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Thank you for reaching out @alexfuksenko-toast, marking as a feature request.

**Comment by amrittuladhar** [comment]
Similarly, other table-level operations also seem to be missing from the v2 API, e.g. "describe table".

**Comment by hiramf** [comment]
+1

**Comment by bigunyak** [comment]
Are there any plans on implementing support for deleteTable operation yet?

**Comment by debora-ito** [comment]
No timeline for it yet, will comment here when we have an update.
