### ISSUE TITLE
S3AsyncClient putObject throwing status code 100 exception

### ISSUE THREAD

**Issue by IvoMajic** [aws/aws-sdk-java-v2#1969]
## Describe the bug
When doing uploads to S3 as of recently I am getting the following exception:

software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 100, Request ID: null, Extended Request ID: null)

The exception is not very informative as you see. Is there any way to debug this further? All was working correctly up until a few days ago.

Code example:

client.putObject(
    PutObjectRequest.builder()
        .bucket(properties.s3.bucketName)
        .key(formKey(path, imageId))
        .acl(if (isPublic) ObjectCannedACL.PUBLIC_READ else null)
        .build(),
    AsyncRequestBody.fromBytes(imageData)
)

The first response I get is:

HTTP/1.1 100 CONTINUE
Date: Sun, 02 Aug 2020 09:55:11 GMT
Connection: keep-alive

and then

HTTP/1.1 200 OK
Content-Length: 0
ETag: "d1aafcb9635d94434c4370260f956000"
Accept-Ranges: bytes
x-amz-request-id: tx0000000000000021ee840-005f268d7f-7c9455-default
Date: Sun, 02 Aug 2020 09:55:11 GMT
Connection: close that reached at the tail of the pipeline. Please check your pipeline configuration.

I am guessing it happens because the last 200 message is discarded, from the log:

2020-08-02T11:55:11,775 DEBUG [aws-java-sdk-NettyEventLoop-1-4] i.n.c.DefaultChannelPipeline: Discarded inbound message DefaultHttpResponse(decodeResult: success, version: HTTP/1.1)

Seems to me it has something to do with Nettys handing of HTTP 100-Continue
## Expected Behavior
The upload finishing successfully.

## Your Environment

* Spring Boot 2.2.7
* AWS Java SDK version used: 2.13.65
* JDK version used: 1.8.0_262
* Operating System and version: Arch Linux

**Comment by debora-ito** [comment]
Hi @IvoMajic I was not able to reproduce the issue. My logs show 

`HTTP/1.1 100 Continue`

and then

```
```

**Comment by danielGz** [comment]
@IvoMajic  How did you fix it? I have the same problem

**Comment by IvoMajic** [comment]
I also could not find a fix in the meantime.
