### ISSUE TITLE
Guideline on using java sdk with AWS SSO credentials?

### ISSUE THREAD

**Issue by ragebiswas** [aws/aws-sdk-java-v2#1970]
## Describe the issue
Hi, feel free to close if this is a naive / obvious question  - but I'm not able to find documentation on how to use Java SDK (V1 or V2) if my org uses AWS SSO to login.

## Steps to Reproduce
I currently am using the default credential provider, but that does not seem to work an says that none of the tried authentication methods (including AWS_* env vars) are found and hence aborts.

I am able to work around by copy pasting env vars from the AWS SSO portal (via the "Command  Line / Programmatic Access" link) but this is fairly inconvenient.

Is there a credential provider that works with AWS SSO named profiles?

**Comment by froderick** [comment]
I have the same question. 👍

**Comment by debora-ito** [comment]
@ragebiswas @froderick you are right, currently the SDK does not support any form of integration with AWS Single Sign-On. This is a feature that needs to be supported across all the AWS SDKs so it requires more planning and design process than usual.

Marking as a feature request.

**Comment by ragebiswas** [comment]
Thanks @debora-ito . It seems the `boto3` library in Python has added support: https://github.com/boto/botocore/pull/2070

It would be great if this could be prioritized soon as well.

For those coming to this page, I've used [yawsso](https://github.com/victorskl/yawsso) as a workaround - a bit easier than copy pasting env vars from the AWS SSO browser page.

**Comment by gdhananjay** [comment]
It will be great if this support is added soon, I am also waiting for the same.

**Comment by debora-ito** [comment]
Apologies for the late update in here.

Support for SSO Credential Provider was added via #2118 and is available in SDK version `2.15.33`. 
We are tracking an issue in #2190 when the aws cli SSO is used first and then the Java SDK SSO fails with a timestamp format error.
