### ISSUE TITLE
IdleConnectionReaper prints a misleading exception when the logging level is set to debug

### ISSUE THREAD

**Issue by carlspring** [aws/aws-sdk-java-v2#1982]
I'm assuming that based on the fact that the class' name is `com.amazonaws.http.IdleConnectionReaper` and the package is `software.amazon.awssdk.http.apache.internal.conn`, that you guys have this class in multiple libraries. However, the code appears to be the same (and I didn't manage to find your other project on Github, so I'm assuming it's Amazon-internal only and, hence, reporting it here).

In `software.amazon.awssdk.http.apache.internal.conn.IdleConnectionReaper`, the following [code block](https://github.com/aws/aws-sdk-java-v2/blob/cdfb7d3f6a7dafb37be84f6e95e49feb0d0af273/http-clients/apache-client/src/main/java/software/amazon/awssdk/http/apache/internal/conn/IdleConnectionReaper.java#L146-164):

```java
        @Override
        public void run() {
            while (!stopping) {
                try {
                    Thread.sleep(sleepPeriod);

                    for (Map.Entry<HttpClientConnectionManager, Long> entry : connectionManagers.entrySet()) {
                        try {
                            entry.getKey().closeIdleConnections(entry.getValue(), TimeUnit.MILLISECONDS);
                        } catch (Exception t) {
                            log.warn("Unable to close idle connections", t);
                        }
                    }
                } catch (Throwable t) {
                    log.debug("Reaper thread: ", t);
                }
            }
            log.debug("Shutting down reaper thread.");
        }
```

Causes:

```
22:57:44.967 09-08-2020 | DEBUG | tp-connection-reaper | com.amazonaws.http.IdleConnectionReaper            | Reaper thread: 
java.lang.InterruptedException: sleep interrupted
	at java.lang.Thread.sleep(Native Method)
```

So... the issue here is that due to the fact that I have `tearDown()` method in my test which invokes:

```java
    com.amazonaws.http.IdleConnectionReaper.shutdown();
```

... the exception above is thrown. It's actually not really an error, _**but**_ when you have the logging level set to `DEBUG` it prints out the exception. To me, this makes little sense the way that it currently is. If you would like to debug things, either use `trace`, or fine tune it by adding whatever checks you need. Also, the exception states that the `Reaper thread` is `XYZ` whereas this is actually a `Throwable`.

Could you please make this only throw/print an exception, if this is really required?

## Expected Behavior

No exception should be printed in `DEBUG`. if you really care about the exception, please throw/re-throw it

## Your Environment

* AWS Java SDK version used:
`com.amazonaws:aws-java-sdk-core:1.11.837`
* JDK version used:
```
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```
* Operating System and version:
```
# uname -a 
Linux carlspring 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by carlspring** [comment]
Is this the right issue tracker for this? If so, any updates? Do you need anything else from me?

**Comment by debora-ito** [comment]
Hi @carlspring just a clarification: you are not using any AWS Java SDK v2 dependency, you are using only AWS Java SDK v1 `1.11.837` correct?

If you are using only SDK v1 the related IdleConnectionReaper class would be this one: https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/IdleConnectionReaper.java#L174

**Comment by carlspring** [comment]
The code for the method is exactly the same in both projects, so, while we may be using the `1.x` version, this is also valid for the `2.x` version to which we intend to upgrade, so the problem is there in both places. Could you please look into it? I will raise a separate issue for this in the other project as well.

**Comment by dagnir** [comment]
Hey @carlspring thanks for the feedback. Could you explain why `DEBUG` level is not appropriate in this case? Typically, within the Java SDK (v1 and v2), we use `DEBUG` to log things that are not necessary to surface when running normally (which is usually anything `INFO` or higher), but may be useful when troubleshooting or debugging since typically production applications use `INFO` or higher logging levels. As you mentioned, this isn't an error, so the SDK just swallows the exception in this case rather than rethrowing it. We typically reserve `TRACE` for really fine grained tracing of operation and the steps they take, such as https://github.com/aws/aws-sdk-java-v2/blob/39a9b4824e00285b6f2dcecb7d56d26b0a4327ca/core/sdk-core/src/main/java/software/amazon/awssdk/core/io/ResettableInputStream.java#L244-L246.

**Comment by debora-ito** [comment]
@carlspring marking this to auto close soon, simply add a comment if you still want to track this.
