### ISSUE TITLE
Incomplete Field Mapping for S3ControlException via S3ControlClient.createJob()

### ISSUE THREAD

**Issue by LukeHornibrookHaventec** [aws/aws-sdk-java-v2#1986]
## Describe the bug
A failed request to `S3ControlClient.createJob()` results in an `S3ControlException` with null message and error code. However, the API response body has the expected `<Code>` and `<Message>` elements, eg:

```
<Error><Code>InvalidRequest</Code><Message>Invalid job manifest</Message><RequestId>****</RequestId><HostId>****</HostId></Error>
```

## Expected Behavior
The response should be marshalled to an `InvalidRequestException` (or equivalent based on the error code) and the `AwsErrorDetails` fully populated.

## Steps to Reproduce
Call `S3ControlClient.createJob()` with only the `accountId` populated, eg:

```
S3ControlClient.create().createJob(x -> {
	x.accountId("123456789012");
});
```

## Possible Solution
Hopefully there is a generalised solution that could resolve other related issues, eg #1983.

## Your Environment
* AWS Java SDK version used: 2.13.41

**Comment by debora-ito** [comment]
Thank you for reporting @LukeHornibrookHaventec, I can reproduce it. Although I see a 
```
<Code>InvalidRequest</Code><Message>Missing role arn</Message>...
```
with the sample code you provided, I think it falls under the same issue with unmarshalling.

**Comment by cenedhryn** [comment]
@LukeHornibrookHaventec 
This issue is now fixed; you will get an S3ControlException back with an InvalidRequest error code.
