### ISSUE TITLE
Highly discouraging documentation of AWS SDK 2.x dynamoDb 

### ISSUE THREAD

**Issue by beaero** [aws/aws-sdk-java-v2#2011]
## Describe the issue
The documentation doesnt provide proper information to even set custom access key config. How to tune timeouts for dynamo and also dynamo queries are one line. Nothing more descriptive.

**Comment by debora-ito** [comment]
Hi @beaero thank you for the feedback. To help us improve the documentation, can you post the link of the DynamoDB documentation you are referring to? 

Would that be the DynamoDB service API or the high-level DynamoDB Enhanced Client?
