### ISSUE TITLE
Parameter names of streaming input/output methods of synchronous clients do not match javadocs

### ISSUE THREAD

**Issue by Alexander-Kiselyov** [aws/aws-sdk-java-v2#2022]
## Describe the bug
Names of formal parameters in javadocs of "simple methods" (the ones, which stream objects to/from files given as Path instances), such as `getObject`/`putObject` in `software.amazon.awssdk.services.s3.S3Client`, are misaligned with the actual implementation (please see the screenshots attached for an example).
While not a real problem by itself, it signifies that there is no SSoT principle applied to parameter names generated by code and javadoc generation mechanisms.

## Expected Behavior
Parameter names in code must match the javadoc ones and preferably aligned with the ones used in asynchronous clients, i.e. must be `sourcePath`/`destinationPath` instead of `filePath`.

## Current Behavior
Parameter names in the signature/body of streaming methods generated by `software.amazon.awssdk.codegen.poet.client.SyncClientInterface` do not match their javadoc and `software.amazon.awssdk.codegen.poet.client.AsyncClientInterface`.

![image](https://user-images.githubusercontent.com/1223303/92339257-de764700-f0bd-11ea-9808-16d5a5bb7bda.png)
![image](https://user-images.githubusercontent.com/1223303/92339282-fa79e880-f0bd-11ea-89cc-412df4fc4605.png)

## Steps to Reproduce
Look into the javadoc :)

## Possible Solution
Use the same parameter names in `software.amazon.awssdk.codegen.docs.SyncOperationDocProvider` and `software.amazon.awssdk.codegen.poet.client.SyncClientInterface`.

## Context
Confuses the analysis of the generated source code a bit.

## Your Environment

* AWS Java SDK version used: 2.14.12
* JDK version used: 1.8, u265
* Operating System and version: Windows 10

**Comment by Alexander-Kiselyov** [comment]
Hi, 

Could someone please assign this issue to me - I'm ready to submit a patch fixing this?

Thanks in advance.

**Comment by debora-ito** [comment]
Thank you for reaching out @Alexander-Kiselyov. Feel free to send us pull requests even if the issues are not assigned to you.

**Comment by Alexander-Kiselyov** [comment]
Hi @debora-ito , thanks for assigning it! I was just trying to follow the contribution guide: "...create a new Bug Report then ask to be assigned to it." :)
PR has been created (#2028), please take a look (Travis CI build fails, but I see the same failures: `RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE` and `codegen-generated-classes-test`'s failures - in prior builds as well, so are not introduced by my changes).
