### ISSUE TITLE
Configuring DynamoDB Tables for Development and Production

### ISSUE THREAD

**Issue by user20161119** [aws/aws-sdk-java-v2#2029]
Is there plan to support this feature in sdk v2.0?
https://aws.amazon.com/blogs/developer/configuring-dynamodb-tables-for-development-and-production/

**Comment by debora-ito** [comment]
@user20161119 just to be clear on your feature request, you're looking for a way to add prefixes to DynamoDB tables using the DynamoDB Enhanced client?

**Comment by user20161119** [comment]
yes,global config the table prefix

**Comment by debora-ito** [comment]
It's not supported in the default DynamoDB Client no.

**Comment by debora-ito** [comment]
@user20161119 there's no plan to add this feature to the Java SDK. 

I'll go ahead and close this, feel free to reach out if you have any other question.
