### ISSUE TITLE
SdkHttpFullRequest builder.URI removes query parameters

### ISSUE THREAD

**Issue by zyrain** [aws/aws-sdk-java-v2#2034]
When calling the SdkHttpFullRequest builder using the URI default method, and query parameters already in your URI are removed.

## Expected Behavior
Existing query parameters in the URI should be kept.

## Current Behavior
	default Builder uri(URI uri) {
            return this.protocol(uri.getScheme())
                       .host(uri.getHost())
                       .port(uri.getPort())
                       .encodedPath(SdkHttpUtils.appendUri(uri.getRawPath(), encodedPath()));

Calling getRawPath() returns only the path without parameters, and encodedPath() is empty if this is your first builder call.  

## Steps to Reproduce
Create a URI with query parameters.
Call the builder.

## Possible Solution
call URI.getQuery, create a map, then call rawQueryParameters

## Context
We are calling a callback url, provided already fully formed.  Without this we need to tear apart the input url and put it back together to call it.

## Your Environment
* AWS Java SDK version used: 2.14.15
* JDK version used: 11
* Operating System and version: AWS Lambda

**Comment by debora-ito** [comment]
Hi @zyrain thank you for reaching out. That is actually the designed behavior of the `uri` method, as documented in the SdkHttpFullRequest [javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/SdkHttpFullRequest.Builder.html#uri-java.net.URI-):

> Convenience method to set the protocol(), host(), port(), and encodedPath() from a URI object.

But I can see in your use case that you work with a fully formed URI, so this is something we can improve in the SDK. Changing this to a feature request.

**Comment by Strat1987** [comment]
I took a stab to aid with this. please be gentle as this is my first contribution.

**Comment by Strat1987** [comment]
@zyrain I was unable to properly merge the upstream master branch and keep only my single squashed commit as a diff so I started over which closed the previous pull request automatically. still not sure how this should typically be tackled.
