### ISSUE TITLE
Create S3 Client with endpointOverride and no Region 

### ISSUE THREAD

**Issue by RStapley** [aws/aws-sdk-java-v2#2037]
## Describe the Feature
I would like to be able to create a S3 client without the region if I provide the endpoint configuration. 

With the V1 SDK I can create and use a client without a region when I provide the endpoint configuration.

``` 
EndpointConfiguration epc = new EndpointConfiguration("http://" + overrideHost + ":" + httpsPort, null);
    AmazonS3 s3Client = AmazonS3Client.builder().withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(ACCESS_KEY_ID, SECRET_KEY)))
        .withEndpointConfiguration(epc).withPathStyleAccessEnabled(true).build();
```

With the V2 SDK I get an exception:

```
    S3ClientBuilder builder = S3Client.builder();
    builder.credentialsProvider(
        StaticCredentialsProvider.create(AwsBasicCredentials.create(ACCESS_KEY_ID, SECRET_KEY)));
    builder.endpointOverride(URI.create("http://" + overrideHost + ":" + httpsPort));
    S3Configuration confBuilder = S3Configuration.builder().pathStyleAccessEnabled(true).build();
    builder
        .serviceConfiguration(confBuilder)
        .httpClient(
            UrlConnectionHttpClient.builder().build());

    S3Client client = builder.build();
```

[ERROR]   Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@29caf222: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@5fcacc0: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@5b6813df: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@1d572e62: Unable to contact EC2 metadata service.]

## Is your Feature Request related to a problem?

Trying to set configuration to leverage different S3 compatible data sources using this SDK. 

## Describe alternatives you've considered
Use the V1 SDK, but would like to stay on the latest. Also considered leaving a default region in there, but that makes the code more confusing as the value is meaningless when the endpoint is provided. 

## Additional Context

Have the requirement to be able to switch between S3 endpoints based on configuration. With the requirement of a region I will either be plugging in a dummy value that will make the code more confusing, or using the older SDK. 

- [ ] I may be able to implement this feature request

## Your Environment
* AWS Java SDK version used: 2.13.45 and 1.11.860
* JDK version used: 1.8
* Operating System and version: Windows and Linux

**Comment by debora-ito** [comment]
@RStapley I'm trying to better understand your use case. I see your endpoint has a host and a port, so I'm assuming it's not a standard AWS service endpoint.

The region needs to be provided for the request signature and it needs to match the regional endpoint... if your endpoint changes based on configuration, can't the region also be provided based on configuration?

**Comment by RStapley** [comment]
Hello @debora-ito 

One example of my use case is I stand up a Docker image locally that hosts S3 and leverage it for integration testing. That way I do not have a network dependency during automated integration tests. In this case my override URL would be localhost and I can configure the port. 

Even when providing the localhost URL and port the SDK still requires a region even though I am not accessing AWS. 

I also have a use case to do the same in prod. Due to some contractual obligations I may not be able to leverage AWS S3 in all use cases, but would like to in many. For example if I have 10 clients and 3 of them have contracts that I store their data I would need to use an on-prem S3 offering, for the remaining 7 I could leverage AWS S3. 

I would prefer to have a configuration representing the proper URL weather that be AWS or otherwise and not have to configure the region, since the region will be in the URL anyway.

**Comment by debora-ito** [comment]
This is a tricky one because your use case doesn't require signing when using localhost, but the signing region is needed when accessing an AWS endpoint, which is the main use of the SDK. For this reason, we don't feel like adding support for this feature right now.

I'll go ahead and close this. Feel free to reach out if you have further questions/comments, or if anyone wants to contribute to the discussion describing a use case.

**Comment by scotty-g** [comment]
Even though using a non-AWS endpoint doesn't seem to be officially supported by the v2 SDK based on the conversation above, we've been able to use it up to this point by configuring a dummy region. With a [recent change in 2.17.79](https://github.com/aws/aws-sdk-java-v2/commit/4656690aed8effe36fcf31cec695778992ee8228#diff-e54f09e0d313a4de0a7e7590ad1dcd7a7d36a943aece2f74e2c41592f74dd081R72), this is no longer possible either as using a non-AWS region name results in a `NullPointerException`.

Should we update the README of this project to explicitly indicate this SDK is only usable with AWS S3?

**Comment by debora-ito** [comment]
@scotty-g seeing a NPE is not good, we should look into that. Can you open a new issue?

**Comment by scotty-g** [comment]
@debora-ito

> This is a tricky one because your use case doesn't require signing when using localhost, but the signing region is needed when accessing an AWS endpoint, which is the main use of the SDK. For this reason, we don't feel like adding support for this feature right now.

Is the intention for this sdk to support non-aws s3 providers now? If so I'd be happy to open an issue and document the NPE.

**Comment by mping** [comment]
I think it's a good idea to support non-aws s3 providers, because S3 is a protocol and there are already multiple industry implementations, thus everybody wins if an SDK supports many implementations of the standard. Likewise, it would be awkward if a non-aws client library didn't work with specifically AWS S3.

**Comment by scotty-g** [comment]
> Is the intention for this sdk to support non-aws s3 providers now?

Any followup to this question?

**Comment by scotty-g** [comment]
Thanks @debora-ito. I was able to confirm as well that the NPE is gone.
