### ISSUE TITLE
Uploading files in S3 through presigned url makes them private by default

### ISSUE THREAD

**Issue by abhishekjain2604** [aws/aws-sdk-java-v2#2053]
Creating presigned url for file upload in itself is working fine.
But uploading the file through the generated URL by default makes it private and hence cannot be accessed through it's URL

I have to manually go to the console and make the file public to be accessible from it's URL

Here is my code
```java
String bucketName = "<bucket-name>";
String keyName = "<file-name>";

S3Presigner presigner = S3Presigner.builder().region(Region.AP_SOUTH_1).build();

PutObjectRequest objectRequest = PutObjectRequest.builder()
        .bucket(bucketName)
        .key(keyName)
        .build();

PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
        .signatureDuration(Duration.ofMinutes(3))
        .putObjectRequest(objectRequest)
        .build();

PresignedPutObjectRequest presignedRequest = presigner.presignPutObject(presignRequest);

System.out.println("Pre-signed URL to upload a file to: " +
        presignedRequest.url());
System.out.println("Which HTTP method needs to be used when uploading a file: " +
        presignedRequest.httpRequest().method());	

presigner.close();
```

In NodeJs we specify that we want the file to be publicly accessible so I found it's java sdk equivalent like this
```java
PutObjectRequest objectRequest = PutObjectRequest.builder()
        .bucket(bucketName)
        .key(keyName)
        .acl(ObjectCannedACL.PUBLIC_READ)
        .build();
```

But when uploading through the URL thus generated, I'm getting a singature mismatch error
```
The request signature we calculated does not match the signature you provided. Check your key and signing method
```

What am I doing wrong? Is it not the correct way to make the file publicly accessible? If not, how should I do it?

**Comment by debora-ito** [comment]
@abhishekjain2604 for the ACL take effect on the presigned URL it needs to be added as a `x-amz-acl` query param. Take a look at this comment to see how to do this: https://github.com/aws/aws-sdk-java-v2/issues/1849#issuecomment-642919219

Let us know if you have further questions.

**Comment by abhishekjain2604** [comment]
@debora-ito It worked perfectly. Thanks a lot

A small follow up question: I am new to Java and I have often found the aws-sdk documentation for Java to be a little lacking when compared to, say, NodeJs
I am mostly relying on stackoverflow and other articles to get things done. There are fewer examples to show how a particuar service can be configured to suite different use-cases

Any reason why?

**Comment by debora-ito** [comment]
@abhishekjain2604 the documentation is something we are actively working on to make it more discoverable and structured in a more instinctive way, so stay tuned! Also, you may already know this but you can find some examples here: https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2

Thank you for your feedback.
