### ISSUE TITLE
use SSO to collect data from cloudwatch without expiry

### ISSUE THREAD

**Issue by gdhananjay** [aws/aws-sdk-java-v2#2071]
We can generate Access/Secret/Session key from SSO login and use it to collect cloudwatch data. But my data collection process is continuous process and generated credentials expires after an hour. So i have to regenerate Access/Secret/Session . Is there any way in SDK to auto generate these credentials or can we have a "SSO credential provider" which will do work of regenerating expired credentials. 

Current Behavior
Unable to use SSO access to collect data from cloudwatch continuously.

 Environment

* java 8
* aws sdk 2.14.27
* Linux

**Comment by debora-ito** [comment]
Hi @gdhananjay we have an open feature request to integrate AWS SSO to the SDK, let's track this over there: https://github.com/aws/aws-sdk-java-v2/issues/1970
