### ISSUE TITLE
DynamoDB Enhanced mapping does not support Date nor ByteBuffer

### ISSUE THREAD

**Issue by ceven** [aws/aws-sdk-java-v2#2092]
While trying to map properties `java.nio.ByteBuffer` and `java.util.Date` using DynamoDb Enhanced mapper within Kotlin code, I get an exception.

## Describe the bug

The following exceptions occur with both the `@DynamoDbBean` mapper and the `TableSchema.builder`:

- `org.springframework.beans.BeanInstantiationException: Failed to instantiate [service.account.Account]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Converter not found for EnhancedType(java.nio.ByteBuffer)`
- `org.springframework.beans.BeanInstantiationException: Failed to instantiate [service.account.Account]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Converter not found for EnhancedType(java.util.Date)`

Sample Kotlin code:

```
class Account {
    constructor() {}

    constructor(pKey: String, bb: ByteBuffer?, created: Date?) {
        this.pKey = pKey
        this.byteBuf = bb
        this.created = created
    }

    var pKey: String = ""

    var byteBuf: ByteBuffer? = null

    var created: Date? = null
}

val ACCOUNT_TABLE_SCHEMA: TableSchema<Account> = TableSchema.builder(Account::class.java)
        .newItemSupplier { Account() }
        .addAttribute(String::class.java) { a: StaticAttribute.Builder<Account, String> ->
            a.name("pKey")
                    .getter { obj: Account -> obj.pKey }
                    .setter { obj: Account, d: String -> obj.pKey = d }
                    .tags(StaticAttributeTags.primaryPartitionKey())
        }
// FIXME instantiation error:
// Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate: Constructor threw exception; nested exception is java.lang.IllegalStateException: Converter not found for EnhancedType(java.nio.ByteBuffer)
        .addAttribute(ByteBuffer::class.java) { a: StaticAttribute.Builder<Account, ByteBuffer?> ->
            a.name("byteBuf")
                    .getter { obj: Account -> obj.byteBuf }
                    .setter { obj: Account, d: ByteBuffer? -> obj.byteBuf = d }
        }
// FIXME instantiation error:
        // Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate: Constructor threw exception; nested exception is java.lang.IllegalStateException: Converter not found for EnhancedType(java.util.Date)
        .addAttribute(Date::class.java) { a: StaticAttribute.Builder<Account, Date?> ->
            a.name("created")
                    .getter { obj: Account -> obj.created }
                    .setter { obj: Account, d: Date? -> obj.created = d }

        }
        .build()
```

## Your Environment

* AWS Java SDK version used: `2.15.7`
* JDK version used: Kotlin `1.4.10` and Java `11`
* Operating System and version: macOS Catalina `10.15.7`

**Comment by debora-ito** [comment]
Hi @ceven, thank you for reaching out. Date and ByteBuffer converters are not provided by default. You can use one of the Java types that has an attribute converter provided (you can see a list [here](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/package-summary.html)) or you can write a custom converter and specify it with a `converterProviders` annotation. For more details and examples check the DynamoDB Enhanced Client [overview](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/README.md#control-attribute-conversion).

Let us know if that helps.

**Comment by ceven** [comment]
Thank you @debora-ito , that's helpful to unblock me!
Is it possible to add this as a feature request? Would be great to have these converters in the SDK.

**Comment by debora-ito** [comment]
For ByteBuffer maybe, yes. For Date I believe we have good substitutes like Instant, LocalDate, LocalTime, LocalDateTime, Period, etc.

**Comment by debora-ito** [comment]
`ByteBufferAttributeConverter` was added in SDK version `2.16.35`. 

Closing this, feel free to reach out if there's any other question.
