### ISSUE TITLE
Step function 2.x API is still in preview 2.0 version , Needs an update for compatibility

### ISSUE THREAD

**Issue by harry9111985** [aws/aws-sdk-java-v2#2094]
The AWS Step functions API for 2.x Java SDK needs an update 

In maven central for the below dependency

software.amazon.awssdk:stepfunctions  , the latest version is 2.0.0-preview-11 . This version is incompatible with all the netty fixes which have been done for the more latest versions in the sdk java 2.x stack . 

The version (2.0.0-preview-11) is also incompatible with the latest AWS runtime core marshallers/unmarshallers.

Examples of upgrades are 

Netty versions upgrades to 4.1.46
Proxy support in NettyAsync

Kindly publish a new jar with all the netty and aws core runtime dependencies please . Otherwise we are forced to use 1.x which is big fat jar and blocking in nature.

Regards,
Harish

**Comment by debora-ito** [comment]
@harry9111985 the Step Functions module is now called `sfn`: https://mvnrepository.com/artifact/software.amazon.awssdk/sfn

**Comment by harry9111985** [comment]
> @harry9111985 the Step Functions module is now called `sfn`: https://mvnrepository.com/artifact/software.amazon.awssdk/sfn

Thanks .. all good now

**Comment by jjayaraman** [comment]
Thanks guys really helped.... at last after big struggle of using  outdated dependency  :-)
