### ISSUE TITLE
How config dynamodb enhanced client return consumed capacity?

### ISSUE THREAD

**Issue by user20161119** [aws/aws-sdk-java-v2#2095]
How to config dynamodb enhanced client return consumed capacity? including table-based config and global config?

this request param `ReturnConsumedCapacity` in the api description.
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html#API_PutItem_RequestSyntax

**Comment by zoewangg** [comment]
Hi @user20161119 this is not currently supported in the DDB Enhanced client. Marking it as a feature request. 

As a workaround, you can create an [ExecutionInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/interceptor/ExecutionInterceptor.java) that records the `PutItemResponse` and then configure it on the DynamoDbClient Builder via [ClientOverrideConfiguration#addExecutionInterceptor](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/config/ClientOverrideConfiguration.java#L318)

**Comment by debora-ito** [comment]
@user20161119 Consumed Capacity is now returned in new methods `putItemWithResponse` and `updateItemWithResponse`. 

See the DynamoDbTable javadoc for more info: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html
