### ISSUE TITLE
Refactor: Request Handlers

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#21]
Request handlers have become particularly messy in 1.11.x. There are multiple versions of request handlers and none are feature complete enough to support features that make sense to be implemented as request handlers, like metrics, signing and encryption. This makes add-on features like the API gateway clients require more significant changes in the core than could usually be required.

Update the request handler abstraction to support the expected current and future use-cases.

(Feel free to comment on this issue with desired changes).

**Comment by spfink** [comment]
Fixed by #97
