### ISSUE TITLE
SQS listQueus() returns null instead of empty List

### ISSUE THREAD

**Issue by tddmonkey** [aws/aws-sdk-java-v2#210]
## Expected Behavior
When calling listQueues() when no queues are present I would expect an empty list of queue urls to be returned.  The equivalent call for DynamoDb (listing tables) returns and empty list of table names.

## Current Behavior

`client.listQueues().queueUrls().forEach(System.out::println);`

The above code throws a NullPointerException as `queueUrls()` is null.  This should just complete silently.

## Possible Solution

Have `listQueues().queueUrls()` return an empty List

## Steps to Reproduce (for bugs)
`client.listQueues().queueUrls().forEach(System.out::println);`

This must be run on an account with no queues.

## Your Environment

* AWS Java SDK version used: 2.0.0-preview-4.  Also tested against master
* JDK version used: java version "1.8.0_144"
* Operating System and version: macOS 10.12.6

**Comment by spfink** [comment]
Discussing this with the team this week. There are cases where null vs empty list can make a difference of request objects so we want to be careful with how we proceed here. Should be able to safely return empty collections on response objects though.

**Comment by kiiadi** [comment]
I think consistency is important, users of the API should not have to treat model objects differently depending on whether they originated from the service (i.e.: a response object and its sub-objects) or whether they originated in the client (i.e.: a request object and its member objects).

I think we can get good mileage out of the SDK creating `NotSetCollection` class implementation that allows customers to interact directly with the collections without doing null checks, but also allows the SDK to understand when a collection has been set explicitly by the customer vs not being set at all.

**Comment by tddmonkey** [comment]
Thanks @shorea.  I noticed today that the message response also contains null for failed messages when none are present, instead of an empty List like the v1 client.  Would that be covered by this feature or do you need a fresh issue opening for that?

**Comment by shorea** [comment]
This would be a code generator change so it will fix all occurences of null lists in POJOs.

**Comment by tddmonkey** [comment]
That's awesome, thanks.

**Comment by shorea** [comment]
Lists are now empty.
