### ISSUE TITLE
cannot support chinese

### ISSUE THREAD

**Issue by 437024677** [aws/aws-sdk-java-v2#2106]
I am currently working on a speech recognition project, but the enumeration type in the languagecode class is not Chinese. Can I add the enumeration type “zn-CH” to the transcribeStreaming service?
## Proposed Solution

add "zn-CH" languageCode in service of transcribeStreaming
## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@437024677 thank you for reaching out. Chinese is not available for streaming transcription yet, here's a list of the available languages: https://docs.aws.amazon.com/transcribe/latest/dg/streaming.html

This is a feature request for the Amazon Transcribe service team, I will forward this to them and will update when we hear back.
