### ISSUE TITLE
Add DetectProtectiveEquipment support for Amazon Rekognition 

### ISSUE THREAD

**Issue by deki** [aws/aws-sdk-java-v2#2112]
Please add support for the new DetectProtectiveEquipment capability
https://aws.amazon.com/blogs/machine-learning/automatically-detecting-personal-protective-equipment-on-persons-in-images-using-amazon-rekognition/

## Describe the Feature
DetectProtectiveEquipment addition to the Rekognition API should be reflected in the SDK

## Is your Feature Request related to a problem?
Customers have to use SDK v1 currently where this is already supported

## Proposed Solution
implement based on https://docs.aws.amazon.com/rekognition/latest/dg/API_DetectProtectiveEquipment.html

## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: 2.15.13
* JDK version used: 11
* Operating System and version: Win 10

**Comment by zoewangg** [comment]
Hi @deki, `DetectProtectiveEquipment` is supported in the latest version of v2. https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/rekognition/RekognitionClient.html#detectProtectiveEquipment-java.util.function.Consumer- 

Could you try with the latest version?

**Comment by deki** [comment]
Thanks for the pointer, found it.
