### ISSUE TITLE
Better implementation for the toString method of the S3Event object

### ISSUE THREAD

**Issue by powerful23** [aws/aws-sdk-java-v2#2128]
Hi AWS SDK team,

We are using the java sdk to implement the lambda function which is triggered by the S3 event. When triggered, we want to print out the S3 event details in the cloudwatch log. However, the `toString` of the event is not well implemented, it just use the default `toString` method of the Java object. We want to ask if you have a plan to provide a better implementation.

## Describe the Feature

To print out the lambda s3 event with details like records when using the lambda logger.

## Proposed Solution

To provide a better `toString` method.

## Additional Context

- [ ] I may be able to implement this feature request

**Comment by debora-ito** [comment]
@powerful23 question: are you talking about this [S3Event](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/src/main/java/com/amazonaws/services/lambda/runtime/events/S3Event.java) object from `aws-lambda-java-libs` library?

On a side note, please don't mention names of internal packages on public channels like github, for security reasons.

**Comment by powerful23** [comment]
Not exactly but most similar.

**Comment by debora-ito** [comment]
> Not exactly but most similar.

Can you provide a link to which S3Event you mean exactly?

**Comment by powerful23** [comment]
As I mentioned this is an internal package, I cannot paste the link here.

**Comment by debora-ito** [comment]
@powerful23 I could not find any S3Event class in the Java SDK [API Reference](https://sdk.amazonaws.com/java/api/latest/), so I'm not fully clear on what you are asking. Please reach out to us internally if you still want to track this.

**Comment by patrickwilliamconway** [comment]
hi @debora-ito, I think I'm running into the same thing. 

For this object `com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification.S3EventNotificationRecord`, the default `toString` yields a log like this:

```
2024-08-08T09:42:26.720+0000 INFO [main] t=aeb2ca4356b33ad4 c=32 - processing S3 Event Notification: com.amazonaws.services.lambda.runtime.events.models.s3.S3EventNotification$S3EventNotificationRecord@4e4f4092
```

which is not particularly helpful. It would be ideal if there was an option to print the JSON format like is described here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/notification-content-structure.html
