### ISSUE TITLE
DynamoDB Enhanced: Field converter failure not propagated to the caller on async

### ISSUE THREAD

**Issue by wem** [aws/aws-sdk-java-v2#2135]
Field converter failure not propagated to the caller on async (Exception get lost and caller hangs).

## Describe the bug
On a query for an item/document with the table client (software.amazon.awssdk.enhanced.dynamodb.DynamoDbAsyncTable) and a (field) converter ends up exceptionally, the call will never end and the caller hangs. To note, this happens at least with a custom executor.

## Expected Behavior
Any kind of failure should reach the caller 

## Current Behavior
See description

## Steps to Reproduce
- Define a DynamDB bean.
- Define a property with a custom converter.
- Implement the converter this way that an exception will get thrown on its execution.
- Execute a query with software.amazon.awssdk.enhanced.dynamodb.DynamoDbAsyncTable.

## Context / Workaround
- Our solution is to do querying and mapping in 2 separate steps. So we query with the software.amazon.awssdk.services.dynamodb.DynamoDbAsyncClient and map the item(s) with software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema afterwards.

## Your Environment

* AWS Java SDK version used: 2.13.+
* JDK version used: AWS Corretto 11
* Operating System and version: Linux Mint 20

**Comment by debora-ito** [comment]
Hi @wem I could not reproduce the issue with a simple DynamoDB bean. Could you provide a repro code?
