### ISSUE TITLE
Unable to marshall request to JSON: null

### ISSUE THREAD

**Issue by bclar-accesso** [aws/aws-sdk-java-v2#2138]
## Describe the bug

I'm getting a NullPointerException when I try to send a message batch to SQS:

```
		SendMessageBatchRequest sendMessageBatchRequest = SendMessageBatchRequest.builder()
				.queueUrl(queueUrl)
				.entries(new SendMessageBatchRequestEntry[sendMessageBatchRequestEntries.size()])
				.build();

		SendMessageBatchResponse sendMessageBatchResponse = sqsClient.sendMessageBatch(sendMessageBatchRequest);
```

## Expected Behavior
I expect the messages to transmit without error.

## Current Behavior
I get a NullPointerException with no explanation as to what field is null:

## Your Environment

* AWS Java SDK version used:  2.15.21
* JDK version used:  Amazon Corretto 1.8.222
* Operating System and version:  EC2 instance, Linux/Unit, r5.large

**Comment by debora-ito** [comment]
@bclar-accesso in your sample code you are not really specifying any message entry in the `SendMessageBatchRequest` builder with `new SendMessageBatchRequestEntry[sendMessageBatchRequestEntries.size()]`.

Try something like this:

```
ArrayList<SendMessageBatchRequestEntry> messageEntries = new ArrayList<>();
messageEntries.add(SendMessageBatchRequestEntry.builder()
        .id("1")
        .messageBody("Hello from the Java SDK")
        .build());

SendMessageBatchRequest sendMessageBatchRequest = SendMessageBatchRequest.builder()
        .queueUrl(queueUrl)
        .entries(messageEntries)
        .build();

SendMessageBatchResponse sendMessageBatchResponse = sqsClient.sendMessageBatch(sendMessageBatchRequest);
```

**Comment by bclar-accesso** [comment]
@debora-ito 

That solved my issue.  Thank you!

**Comment by debora-ito** [comment]
No problem!
