### ISSUE TITLE
S3Client- shuts down after exception. 

### ISSUE THREAD

**Issue by CoolCommando** [aws/aws-sdk-java-v2#2140]
Hi,

In one of my older projects, I had made use of the S3Client in a multi-threaded scenario. Initially I had created a single instance of the S3Client and used it across threads, but noticed the following issue: 
If there is an exception in one of the threads eg.. an Object doesn't exist in the bucket, then all subsequent requests made via the S3Client instance fail, I believe with 'Connection Exception'. I got around this issue by creating a new instance of the client for each thread.

I do not have logs as this was some time ago, and I'm going to be using the client in a new project in a similar multi-threaded environment again, so wanted to know if I've missed something, or if this is the expected behavior/known or fixed bug.

Also any suggestions would be greatly helpful.

Thanks!

**Comment by debora-ito** [comment]
All SDK clients are thread safe, so sharing a single instance is highly recommended. What you described is not expected behavior, facing exceptions should not cause issues with the client, but without logs and reproducible code samples is hard to investigate it further or make suggestions. 

What version of the SDK are you using?

**Comment by CoolCommando** [comment]
Hi,

I managed to recreate the issue- please find the logs attached.
[S3ClientLog.txt](https://github.com/aws/aws-sdk-java-v2/files/5522184/S3ClientLog.txt)

In this case I'm trying to copy objects to a different location.
I deleted the object 'SDL_PDF/pdf/pdf_865432_en-US.pdf' so that's the only copy request that's expected to fail.
All other keys exist, but if you check the logs there are 'File not found..' exceptions for other keys as well- even though they exist.

I used the latest version of the client to re-create this- 2.15.21.

Thanks.

**Comment by debora-ito** [comment]
@CoolCommando thank you for the logs. They show `RejectedExecutionException`, which indicates that a task was added to the `ThreadPoolExecutor` but it got rejected because the pool is shutting down.

How are you creating the S3 clients, can you provide a code sample?
Are you defining specific http client configurations?
Do you think it's possible the shared S3Client is being closed prematurely when the first NoSuchKeyException is returned?

**Comment by CoolCommando** [comment]
Hi @debora-ito,

Please find my responses:

'They show RejectedExecutionException, which indicates that a task was added to the ThreadPoolExecutor but it got rejected because the pool is shutting down'
 -- I've made use of a ThreadPoolExecutor, and use CompletableFutures to spawn new threads. I've tested my code sample enough times to say with certainty that the issue lies with the S3Client, since the same code works as expected when separate S3Client instances are created for each worker thread.  

'How are you creating the S3 clients, can you provide a code sample?'
-- Creating a configuration as follows:
         final ClientOverrideConfiguration  s3ClientConfiguration = ClientOverrideConfiguration.builder().apiCallTimeout(Duration.ofSeconds(30)).apiCallAttemptTimeout(Duration.ofSeconds(10)).retryPolicy(RetryPolicy.builder().numRetries(3).build()).build();

And then creating S3Client instances as follows:
final S3Client s3Client = S3Client.builder().overrideConfiguration(s3ClientConfiguration).region(Region.US_EAST_1).build();

'Are you defining specific http client configurations?'
-- Nope, should I?

'Do you think it's possible the shared S3Client is being closed prematurely when the first NoSuchKeyException is returned?'
-- That's exactly what seems to be happening- upon encountering an exception, the client instance seems to be closing/shutting down itself so all subsequent requests made via the instance also throw exceptions.

Please let me know if I can do anything differently to get around this, as I would prefer creating a single S3Client instance and using it across the application.

Thanks!

**Comment by debora-ito** [comment]
@CoolCommando sorry for the long pause in reply. I think we need additional info to investigate this issue. Can you provide [wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose)? Please remove any sensitive information before sharing the logs.

**Comment by CoolCommando** [comment]
Hi @debora-ito,

It looks like I've got to the bottom of this after all- the client was being closed in a finally block inside the worker threads- so therefore any exception would close the client. 
This isn't a bug after all!
Thank you for your time, and sorry for wasting it!

Regards.
