### ISSUE TITLE
 Proxy for Async Http client.

### ISSUE THREAD

**Issue by gkankanh** [aws/aws-sdk-java-v2#2197]
Need some guidance on which async http client to use when behind a proxy for async S3 ops.
Netty client does not support proxy for async yet.

**Comment by debora-ito** [comment]
@gkankanh Providing proxy host and port is supported, you need to configure the Netty client on the S3 client's httpClientBuilder  - see this [comment](https://github.com/aws/aws-sdk-java-v2/issues/858#issuecomment-542454986) for an example.  Proxy authentication is not supported yet, we're tracking in https://github.com/aws/aws-sdk-java-v2/issues/1432.

Let us know if this helps.
