### ISSUE TITLE
Translate: terminology can only contain 256 terms?

### ISSUE THREAD

**Issue by avdv** [aws/aws-sdk-java-v2#2208]
Hi.

I don't know where the service models come from, so I figured I could open an issue here.

## Describe the issue
According the documentation of the `TranslateTextRequest` method's `TerminologyNames` parameter, a custom terminology list "can contain a maximum of 256 terms". Is that true? Or, what does it mean?

I see that (according to https://docs.aws.amazon.com/translate/latest/dg/what-is-limits.html) the memory limit of a custom terminology file is 10 MB. How does that relate?

N.B. I have uploaded a terminology file with more than one thousand terms, and it seems to work flawlessly.

Thanks!

## Links

https://github.com/aws/aws-sdk-java-v2/blob/8e4fb6d45e3cf29918361ed791a6bbba8e1598d1/services/translate/src/main/resources/codegen-resources/service-2.json#L1263-L1266

**Comment by debora-ito** [comment]
Hey @avdv I'll forward your questions to the Amazon Translate team, will update when we hear back.

**Comment by debora-ito** [comment]
@avdv The Amazon Translate team replied. That part of `TerminologyNames` description should say something like "each terminology name has a maximum length of 256 characters".

They agreed that the documentation is confusing, they'll work to get it fixed. Let us know if you have any other question.

**Comment by avdv** [comment]
@debora-ito thank you, that clears it up for me! 👍
