### ISSUE TITLE
DynamoDbEnhancedClient support for multiple type mapping

### ISSUE THREAD

**Issue by rossginn** [aws/aws-sdk-java-v2#2211]
Allow inserting into a single table multiple types that implement a generic record interface defining PK and SK. 

## Describe the Feature
For tables containing many to one relationships, a SK convention such as type#id can be used to link adjacent documents. 
For example, if GenericRecord interface defined PK and SK getters:
```
PK: Amazon SK: company#123abc -> Company implements GenericRecord
Pk: Amazon SK: employee#789xyz -> Employee implements GenericRecord
```
Ability to create single flexible mapper/client and insert both types in order. 

## Is your Feature Request related to a problem?
It appears this may be possible with StaticTableSchema, but seems like a lot of unintuitive setup. It appears v1 SDK approach is simpler.

**Comment by debora-ito** [comment]
@rossginn is this the same ask as https://github.com/aws/aws-sdk-java-v2/issues/2151?
