### ISSUE TITLE
DeepArchive storage class is missing in S3 v2

### ISSUE THREAD

**Issue by rmunna** [aws/aws-sdk-java-v2#2228]
DeepArchive storage class `com.amazonaws.services.s3.model.StorageClass` which is available in v1 is not available in v2 `software.amazon.awssdk.services.s3.model.StorageClass`

## Your Environment

* AWS Java SDK version used: 2.5.15
* JDK version used: 11
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
It's all uppercase now but it's there: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/StorageClass.html

**Comment by rmunna** [comment]
@debora-ito  thank you. It is available in the latest version.
