### ISSUE TITLE
[getObject] NoSuchKeyException is not thrown when key does not exist AND a versionId is provided

### ISSUE THREAD

**Issue by scotty-g** [aws/aws-sdk-java-v2#2235]
## Describe the bug

When calling `S3Client#getObject(GetObjectRequest)` there is different behavior for the error thrown depending on whether a version is provided or not.

For example, on a versioned bucket
* Providing only a `key` and no `versionId` results in `NoSuchKeyException: The specified key does not exist`.
* Providing both a `key` and a `versionId` results in `S3Exception: The specified version does not exist.`

I'm guessing that the version is considered a subresource of the key, but it seems strange that we get a message about the version not existing when the key doesn't exist either.

## Expected Behavior

A `NoSuchKeyException` is thrown whenever the specified key does not exist, regardless whether a version is provided or not.

## Current Behavior

* Providing only a `key` and no `versionId` results in `NoSuchKeyException: The specified key does not exist`.
* Providing both a `key` and a `versionId` results in `S3Exception: The specified version does not exist.`

## Steps to Reproduce

* Create a versioned bucket.
* Invoke `S3Client#getObject(GetObjectRequest)` using an invalid key and any versionId.
* Note exception returned is `S3Exception` instead of `NoSuchKeyException`.

## Context

I would like accurately tell my consumer that the key is invalid. Telling them the version does not exist is "true" but missing the context that the `key` is actually missing.

## Your Environment

* AWS Java SDK version used: `2.15.63`
* JDK version used: 

  ```
   openjdk version "1.8.0_242"
   OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_242-b08)
   OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.242-b08, mixed mode)
  ```

* Operating System and version: OSX 10.15.7

**Comment by debora-ito** [comment]
Hi @scotty-g, thank you for reaching out. Both error messages are sent by S3, so I'll forward your request to the service team. Will update here when I hear back from them.

**Comment by pkgonan** [comment]
@debora-ito Hi, is there any update?

**Comment by debora-ito** [comment]
No updates from the service here, but I want to point out that changing the error code or the error message is a breaking change, so this cannot be changed at this point.

I'll go ahead and close this, as there's no pending action on the Java SDK. Feel free to reach out if you have other questions.
