### ISSUE TITLE
DynamoDB enhanced creates invalid requests

### ISSUE THREAD

**Issue by productivityindustries** [aws/aws-sdk-java-v2#2243]
When using a mapped bean class having a Map attribute, creating or updating the map with a null value produces an invalid PutObjectRequest/UpdateObjectRequest

## Describe the bug
Bean:

```
@DynamoDbBean
public static class Book {

  private String id;
  private Map<String, String> map;

  public Book() { }
  public Book(String id) { setId(id); }

  @DynamoDbPartitionKey public String getId() {return id;}
  public void setId(String id) {this.id = id;}
  public Map<String, String> getMap() {return map;}
  public void setMap(Map<String, String> map) {this.map = map;}
}
```

Use a `DynamoDbTable<Book>` to put an item:

```
    Book b = new Book(id);
    b.setMap(Collections.singletonMap("a", null));
    TABLE.putItem(b);
```

fails with `DynamoDbException: Supplied AttributeValue is empty`.
The created PutObjectRequest is:
`PutItemRequest(TableName=books, Item={id=AttributeValue(S=id), map=AttributeValue(M={a=AttributeValue()})})`

The AttributeValue of `map.a` is invalid.

The same process using low-level client works, using a null AttributeValue:

```
    DB.putItem(b -> b
      .tableName("books")
      .item(new HashMap<String, AttributeValue>() {{
        put("id", AttributeValue.builder().s(id).build());
        put("metadata", AttributeValue.builder()
          .m(Collections.singletonMap("a", AttributeValue.builder().nul(true).build()))
          .build());
      }})
    );
```

A similar behavior is present on update operations.

## Expected Behavior
The enhanced request should be valid, having a null Attribute value.

tested on
* AWS Java SDK version 2.15.65
* JDK version used: 1.8

**Comment by debora-ito** [comment]
Hi @productivityindustries I can reproduce the issue. Marking as a bug.
