### ISSUE TITLE
DynamoDbEnhancedClient: batchWrite request is not honoring @DynamoDbUpdateBehavior annotation

### ISSUE THREAD

**Issue by radhag** [aws/aws-sdk-java-v2#2246]
I added the DynamoDbUpdateBehavior annotation on date fields. From the enhanced-dynamodb client behavior, it seems like that annotation is only being read for UpdateItem but not for batchWrite

**Comment by debora-ito** [comment]
Hi @radhag please provide the following:

- A self-contained, concise snippet of code that can be used to reproduce the issue
- Your Environment:
 -- AWS Java SDK version used:
 -- JDK version used:
 -- Operating System and version:

**Comment by radhag** [comment]
@debora-ito 

Yes, sorry for not including it earlier. Here is the code snippet:

Below is the example to define the dates:

 `public class TestDto {
 @Getter(onMethod = @__({@DynamoDbAttribute(value = "createdOn"), @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)}))
    private Date createdOn;

    @Getter(onMethod = @__({@DynamoDbAttribute(value = "updatedOn"), @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_ALWAYS)}))
    private Date updatedOn;
    }`
    
Below is how I am using it to batchWrite:

` WriteBatch.Builder builder = WriteBatch.builder(TestDto.class)
                .mappedTableResource(this.table);
            request.stream().forEach(item -> {
                Date now = new Date();
                item.setCreatedOn(now);
                item.setUpdatedDate(now);
                builder.addPutItem(item);
            });

            BatchWriteItemEnhancedRequest batchWriteItemEnhancedRequest =
                BatchWriteItemEnhancedRequest.builder()
                    .writeBatches(builder.build())
                    .build();
            enhancedClient.batchWriteItem(batchWriteItemEnhancedRequest);`
    
    I noticed that both created and updated time are getting updated. The UpdateBehavior annotation is being honored only for updateItem call and not for batchUpdate.
    
    The other issue is, there is no auto-generated timestamp as in dynamodbMapper but there seems to be another open issue related to that

**Comment by debora-ito** [comment]
Hi @radhag I'm sorry for the long delay in response.

This is the intended behavior. `UpdateBehavior` applies to update operations, not put operations.
Note that `WriteBatch` only supports `deleteItem` and `putItem`.
