### ISSUE TITLE
S3Client.utilities.getUrl() ignore overrideEndpoint()

### ISSUE THREAD

**Issue by RaphaelSanamyan** [aws/aws-sdk-java-v2#2266]
Hello! I faced a problem while writing tests. When overwriting an endpoint with "endpointOverride" at S3Client and calling s3Client.utilities().getUrl() the overwriting will be ignored. 

```
S3Client s3Client = S3Client.builder().region(Region.AWS_GLOBAL)
    .endpointOverride(URI.create("https://s3.custom.host"))
    .build();

GetUrlRequest getUrlRequest = GetUrlRequest.builder()
    .bucket("bucket")
    .key("key")
    .build();
```

## Expected Behavior
    s3Client.utilities().getUrl(getUrlRequest).toURI(); // https://s3.custom.host/bucket/key

## Current Behavior
    s3Client.utilities().getUrl(getUrlRequest).toURI(); // https://s3.amazonaws.com/bucket/key

## Context
I am writing tests and I need to check if the builder is created correctly, including the "endpointOverride" property. But in the second version of sdk this method doesn't work correctly, although methods like "getObject" work as expected. The first version of the sdk did not have this problem.

    AwsClientBuilder.EndpointConfiguration endpointConfiguration =
        new AwsClientBuilder.EndpointConfiguration("https://s3.custom.host", "aws-global");
    AmazonS3 amazonS3 = AmazonS3ClientBuilder.standard()
        .withEndpointConfiguration(endpointConfiguration)
        .build();
    amazonS3.getUrl("bucket", "key").toURI(); // https://s3.custom.host/bucket/key

## Environment

* aws_java_sdk2_version = "2.13.54"
* Java 8
* Ubuntu 20.04

**Comment by debora-ito** [comment]
@RaphaelSanamyan I see how you'd expect S3Utilities to use the client's `endpointOverride` value, but you can use `GetUrlRequest #endpoint`:

```
GetUrlRequest getUrlRequest = GetUrlRequest.builder()
    .endpoint(URI.create("https://s3.custom.host"))
    .bucket("bucket")
    .key("key")
    .build();
```

**Comment by RaphaelSanamyan** [comment]
This workaround won't work in my situation, because I want to check that the URL will be changed automatically on all requests. But overwriting on the `GetUrlRequest` is independent of the `S3Client` state. But thanks anyway for the answer and the suggested workaround.
