### ISSUE TITLE
software.amazon.awssdk.core.exception.SdkClientException: Unable to marshall request to JSON: baseUri must not be null.

### ISSUE THREAD

**Issue by Steely57** [aws/aws-sdk-java-v2#2274]
Upload file to S3 bucket with AWS Java 2 SDK version 2.15.73  (quite new).
Java version 1.8.0_211
Operating system: IBM AIX 7.1

In S3Client.**putObject** method comes an exception:

See file Exception-20210204.txt

[Exception-20210204.txt](https://github.com/aws/aws-sdk-java-v2/files/5928433/Exception-20210204.txt)

-- --------------------------

**Java code:**

String endPointURL = appParms.getProxyServer() + ":" + appParms.getProxyServerPort();

URI endPointUri = new URI(endPointURL); 

ProfileCredentialsProvider credentialsProfile = 
	ProfileCredentialsProvider.builder().profileName(appParms.getProfileName()).build();

S3Client s3NonEncryption = null;

Region region = Region.EU_CENTRAL_1;
s3NonEncryption = S3Client.builder()
		.credentialsProvider(credentialsProfile)
		.region(region)
		.endpointOverride(endPointUri)
		.build();

String folderKey = appParms.getBucketFolder() + "/" + appParms.getFileName();
File aFile = new File(appParms.getFilePath() + "/" + appParms.getFileName());

PutObjectRequest putOb = PutObjectRequest.builder()
		.bucket(appParms.getBucketNameSSE())
		.key(folderKey)
		.build();

PutObjectResponse response = s3NonEncryption.**putObject**(putOb, aFile.toPath());

Exception comes in this last line.

**In Maven pom file:**

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.15.73</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
    <dependencies>

**Comment by debora-ito** [comment]
@Steely57 I found your [post](https://forums.aws.amazon.com/message.jspa?messageID=972275) in the AWS Forum and it looks like you are now seeing a different error? What's the status of this issue?

**Comment by Steely57** [comment]
Evening

Yes, this "baseUri must not be null" has disappeared.

Latest errors in attachement **Exception-20210210.txt.**

It seems that some kind of mismatch in classes in final jar produced by Maven.

[Exception-20210210.txt](https://github.com/aws/aws-sdk-java-v2/files/5961252/Exception-20210210.txt)

**Comment by debora-ito** [comment]
Found the cause of the confusion. `ApacheSdkHttpClientFactory` class  was substituted by `ApacheHttpClient` in the first GA release of the SDK. Try:

```java
SdkHttpClient httpClient = ApacheHttpClient.builder()
                .proxyConfiguration(
                        ProxyConfiguration.builder()
                                .endpoint(URI.create("http://myproxy.com:1234"))
                                .build())
                .build();
```

with the pom.xml showed in step 2 of the Exception-20210210.txt file:

```xml
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.15.77</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>s3</artifactId>
        </dependency>
    <dependencies>	

```

**Comment by Steely57** [comment]
Thanks for this clarification.

Now the mismatch errors in classes have disappeared.

Still "Connection time out" error.
See stacktrace in appendix 

[Exception-20210211-1.txt](https://github.com/aws/aws-sdk-java-v2/files/5966776/Exception-20210211-1.txt)

We have this same use case executing with no problems based on Java SDK 1.1.128 version since year 2017 
to same bucket thru same proxy server.  So the firewalls etc. are open.

I added timeout parameter as 

		SdkHttpClient httpClient = ApacheHttpClient.builder()
                .proxyConfiguration(proxyConfig)
                **.connectionTimeout(Duration.ofMillis(30000))**
                .build();                                
                
and this works and application stucks for 30 secs before timeout exception.

In Java code above we do not have this ".endpointOverride(endPointUri)" because that caused the error "URI must no be null".

What else to change in code ?
Maybe stack trace shows some error in addresses.

**Comment by debora-ito** [comment]
The stacktrace indicates that the SDK client could not connect to the `bdw-landing-sse-test-s3.s3.eu-central-1.amazonaws.com` host. Double check your environment network configurations, like proxy settings. Test if you can reach the host with a ping command in the same environment for example.

**Comment by Steely57** [comment]
The bucket is **bdw-landing-sse-test-s3**
As said, we have in use this same bucket, proxy server and port with AWS Java SDK 1.1.128 version.

I suppose that this Java 2.x implementation generates wrong addresses to proxy or it requires new mapping configuration to proxy ?

Is this postfix ".s3.eu-central-1.amazonaws.com:443" correct ?
( bdw-landing-sse-test-s3.s3.eu-central-1.amazonaws.com:443 )

Region setting is correct "eu-central-1" and configured in S3Client class instantiation ( Region region = Region.EU_CENTRAL_1 )

**Comment by Steely57** [comment]
Some progress.
SDK 2  requires explicit definition of used  http protocol (scheme) 
in URI class creation ( URI endPointUri = new URI("http",null,. . . ).
In this case protocol is plain http, not https.

Next problem is related to credentials, that is created with 
software.amazon.aws.sdk.auth.credentials.ProfileCredentialsProvider 

ProfileCredentialsProvider credentialsProfile = ProfileCredentialsProvider.builder().profileName(appParms.getProfileName()).build();

When referring "credentialsProfile.resolveCredentials().accessKeyId()" comes an exception

java.lang.IllegalStateException: To use assumed roles in the 'access-s3-dev-landing-role-v2' profile, the 'sts' service module must be on the class path.
        at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.stsCredentialsProviderFactory(ProfileCredentialsUtils.java:277)
        at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.roleAndSourceProfileBasedProfileCredentialsProvider(ProfileCredentialsUtils.java:222)
        at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.credentialsProvider(ProfileCredentialsUtils.java:118)
        at software.amazon.awssdk.auth.credentials.internal.ProfileCredentialsUtils.credentialsProvider(ProfileCredentialsUtils.java:92)
        at software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider.lambda$new$0(ProfileCredentialsProvider.java:72)

This application does not require any STS ( AWS Single Token Service) and actual error is related to something else.

Credentials are configured to environment in default way eg. with files
~/.aws/config and ~/.aws/credentials.

SDK 1.x version Java application is using these same configuration without any problems last four years.

**Comment by debora-ito** [comment]
Hi @Steely57 apologies for the long pause in response. 

The stacktrace shows that the profile credential provider found `role_arn` and `source_profile` information, and they are going to be used to assume the role specified by the role_arn. To be able to call AssumeRole you need to add STS as a dependency to your project, [AssumeRole is an STS operation](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html).

Let us know if you have more questions.
