### ISSUE TITLE
Enhanced Dynamodb not support List<CustomObject> type?

### ISSUE THREAD

**Issue by user20161119** [aws/aws-sdk-java-v2#2277]
In my table schema there is List<CustomeObject> property,try to save the object,got following error
```java
Converter not found for EnhancedType(java.util.List<com.kjds.table.common.OperationLog>)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.lambda$findConverter$2(DefaultAttributeConverterProvider.java:155)
	at java.util.Optional.orElseThrow(Optional.java:290)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.findConverter(DefaultAttributeConverterProvider.java:155)
	at software.amazon.awssdk.enhanced.dynamodb.DefaultAttributeConverterProvider.converterFor(DefaultAttributeConverterProvider.java:133)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.converterFrom(ImmutableAttribute.java:167)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.ImmutableAttribute.resolve(ImmutableAttribute.java:163)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.lambda$new$0(StaticImmutableTableSchema.java:153)`

**Comment by kevcodez** [comment]
Annotating the child class, in your cass OperationLog with `@DynamoDbBean` solved this issue for me *but* when retreiving the saved data from dynamo db, the items in the list are all null.

**Comment by debora-ito** [comment]
By default, the SDK provides attribute converters for all primitive and many common Java types, you can see the list and the converters implementation here: 
https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute

If you are using a custom object, you need to write a custom AttributeConverter so the enhanced client can know how to transform the custom type to a DynamoDB supported type, and transform it back. Then use the @DynamoDbBean 'converterProviders' annotation to indicate which providers must be used for that Bean. Check "Control attribute conversion" in the [DynamoDB Enhanced Client overview](https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#control-attribute-conversion) for more detailed info.

**Comment by kevcodez** [comment]
@debora-ito If I understand correctly, this should work out-of-the-box, if I annotate both classes with `@DynamoDbBean`.

```kotllin
@DynamoDbBean
data class Customer(
 var id: String ? = null,
 var quota: List<Quota>? = null
)

@DynamoDbBean
data class Quota(
  var type: String? = null,
  var quota: Int? = null
)
```

Shouldn't that be enough to successfully save and retrieve the customer DTO? At least it sounded like that in other Github issues

**Comment by user20161119** [comment]
> @debora-ito If I understand correctly, this should work out-of-the-box, if I annotate both classes with `@DynamoDbBean`.
> 
> ```
> @DynamoDbBean
> data class Customer(
>  var id: String ? = null,
>  var quota: List<Quota>? = null
> )
> 
> @DynamoDbBean
> data class Quota(
>   var type: String? = null,
>   var quota: Int? = null
> )
> ```
> 
> Shouldn't that be enough to successfully save and retrieve the customer DTO? At least it sounded like that in other Github issues

not work with java sdk either

**Comment by debora-ito** [comment]
@kevcodez @user20161119 Can you provide a repro code? I ran some simple tests locally and it works for me, for both putItem and getItem.

**Comment by user20161119** [comment]
> @kevcodez @user20161119 Can you provide a repro code? I ran some simple tests locally and it works for me, for both putItem and getItem.

thanks,my test result is when the collection property is ` private Set<OperationLog> orderItemList = new HashSet<>();`
not work
but `List<OperationLog> ` work

**Comment by debora-ito** [comment]
@user20161119 Noted. Can you provide a minimal reproducible code?

**Comment by user20161119** [comment]
> @user20161119 Noted. Can you provide a minimal reproducible code?

check here https://github.com/user20161119/practice_demo/tree/master/aws/src/test/java/com/example/aws/dynamodb

**Comment by debora-ito** [comment]
@user20161119 the link gives a Page Not Found error. Is that a private repo?

**Comment by user20161119** [comment]
[aws.zip](https://github.com/aws/aws-sdk-java-v2/files/5996275/aws.zip)

sorry,i read the java sdk source code,but i did not understand the java set type process logic
```java
if (type.rawClass().isAssignableFrom(Map.class)) {
            converter = createMapConverter(type);
        } else if (type.rawClass().isAssignableFrom(Set.class)) {
            converter = createSetConverter(type);
        } else if (type.rawClass().isAssignableFrom(List.class)) {
            EnhancedType<T> innerType = (EnhancedType<T>) type.rawClassParameters().get(0);
            AttributeConverter<?> innerConverter = findConverter(innerType)
                .orElseThrow(() -> new IllegalStateException("Converter not found for " + type));
            return Optional.of((AttributeConverter<T>) ListAttributeConverter.create(innerConverter));
        } else if (type.rawClass().isEnum()) {
            return Optional.of(EnumAttributeConverter.create(((EnhancedType<? extends Enum>) type).rawClass()));
        }
```

**Comment by user20161119** [comment]
@debora-ito hi did you try my sample code? i did not solve the issue yet.thanks

**Comment by user20161119** [comment]
as the document said https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.DataTypes.html
java set just support string type,other collection support customeobject
```java
private Set<String> orderItemSet = new HashSet<>();
 private List<OrderItem> itemList = new ArrayList<>();
```
