### ISSUE TITLE
Provide release of cognitoidp

### ISSUE THREAD

**Issue by barnesm999** [aws/aws-sdk-java-v2#2278]
## Describe the Feature
It seems that a v2 for cognitoidp is not available in Maven Central if I am looking in the right place: https://mvnrepository.com/artifact/software.amazon.awssdk/cognitoidp/2.0.0-preview-11. The last update was in 2018 even though other parts of the v2 SDK seem to be receiving regular releases. We would like to see cognitoidp made available as a proper release. 

## Is your Feature Request related to a problem?
We want to fully migrate to v2 SDK but have been blocked by this missing release.

## Proposed Solution
Release v2 SDK of cognitoidp or provide a timeline of when this functionality is expected to be ready for the v2 SDK.

## Describe alternatives you've considered
Mixing v1 and v2 SDKs in the same project is possible but not ideal.

## Your Environment

* AWS Java SDK version used: 2.15.79
* JDK version used: 11
* Operating System and version: Amazon Linux 2

**Comment by debora-ito** [comment]
The artifactId has changed, now it's `cognitoidentityprovider`: https://mvnrepository.com/artifact/software.amazon.awssdk/cognitoidentityprovider
