### ISSUE TITLE
DynamoDbEnhancedClient: BeanTableSchema.mapToItem returns null when given an empty map or an all-null map, should return an uninitialized bean

### ISSUE THREAD

**Issue by bill-phast** [aws/aws-sdk-java-v2#2280]
## Expected Behavior
A map with all null attributes, or with no non-null attributes, should return an uninitialized bean. Instead it returns null. Especially when beans contain other beans, this differences is significant and can be hard to work around.

## Current Behavior
This application shows the problem. It takes an all-null bean, encodes it, then decodes it; instead of getting an all-null bean back, it gets just null:
```
import software.amazon.awssdk.enhanced.dynamodb.TableSchema;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;

import java.util.Map;

public class MainClass {
    @DynamoDbBean
    public static class BeanClass {
        private String name;
        public String getName() { return name; }
        public void setName(String name) { this.name = name; }
    }
    public static void main(String[] args) {
        TableSchema<BeanClass> schema = TableSchema.fromBean(BeanClass.class);
        BeanClass b = new BeanClass();
        System.out.println("All-null bean cannot be decoded, returns null instead: " +
                               schema.mapToItem(schema.itemToMap(b, true)));
        System.out.println("Should print an empty bean, will print null: " +
                               schema.mapToItem(Map.of()));
    }
}
```
Output:
```
All-null bean cannot be decoded, returns null instead: null
Should print an empty bean, will print null: null
```

## Possible Solution
The bug is in StaticImmutableTableSchema.mapToItem. It lazily constructs the bean, which means that if no setters ever need to be called, the bean is never constructed and null is returned. If it is changed to construct the bean at the start of the call, then the problem is solved.

If this seems acceptable I would be happy to write a pull request.

## Steps to Reproduce (for bugs)
Compile and run the example code above.

## Context
This is blocking us from moving to SDK 2. SDK 1 does not have this bug, and we do store objects with uninitialized beans, and we need to preserve the objects as-is, not null out these beans.

## Your Environment
* AWS Java SDK version used: 2.15.79
* JDK version used: 1.3
* Operating System and version: MacOS, and whatever AWS Lambdas runs

**Comment by debora-ito** [comment]
Hi @bill-phast can you tell us more about your use case? Please be as specific as you can. 

I see you do store objects with uninitialized beans, I'm trying to understand how these items are stored in DynamoDB. An item must have at least a primary key, a simple `BeanClass b = new BeanClass();` is not a valid item.

**Comment by bill-phast** [comment]
An item doesn't need a primary key. Each dynamo entry needs a primary key, but because items can contain other items, only the outer item needs a primary key. Our full code is huge, it is hundreds of line per class that is stored in dynamo, but look at this subset of our code:
```
@DynamoDbBean
public class Case {

    private String id;

    public Qc qc;

    @DynamoDbPartitionKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    public Qc getQc() {
        return qc;
    }
    public void setQc(Qc qc) {
        this.qc = qc;
    }
}

@DynamoDbBean
public class Qc {
    // QC has many getters, setters, and member variables.
    // But it is not unusual for all of these to be null.
}
```
Hopefully that makes sense. As you can see, the Case class is persisted to dynamo, and it has a key as needed. It also contains a QC object. A null qc value means that no QC run was done; an all-null QC run means that the run was done, but there was no data pertinent to this particular case. SDK v1 serialized/deserialived this correctly. V2 turns the empty qc run into "null."

Regardless of all this, the serialization system is broken. The purpose of a serialize/deserialize step is to save a data structure, then re-create a copy later. The SDK v2 does not do that. When an object is all null, it is not deserialized correctly, it turns into "null."

**Comment by bill-phast** [comment]
Hi @debora-ito - have you had a chance to return to this yet? Does my additional explanation make sense? Like I said originally, if taking out the lazy constructor in StaticImmutableTableSchema is acceptable, I'm willing to make a pull request.

**Comment by debora-ito** [comment]
@bill-phast I'm sorry for the delayed response in here. 

Solution design discussions are happening in PR #2334. 

I'll change this to a feature request, as more customers seem to be impacted by this issue.

**Comment by bill-phast** [comment]
Thanks so much Zoe! We appreciate your work here, it will let us switch
over to SDK v2 much more easily.

If I have questions, then is it OK to ask you directly, or on github, or
elsewhere? E.g., I can't figure out why DynamoDbTable.query() returns a
PageIterable, but DynamoDbIndex.query() returns a SdkIterable<Page>. It
would be much more straightforward if they returned the same thing. (It
would be really nice if Table and Index were the same class, so we could
use primary indexes and GSIs interchangeably in the code, but it doesn't
seem to be set up that way.)

**Comment by zoewangg** [comment]
Hey Bill, that's a good question. We should've supported returning `PageIterable` from `DynamoDbIndex#query`, but we can't change it now unfortunately for backwards compatibility reasons. :( We could introduce a `queryV2` that returns `PageIterable` in the future if we get more questions like this.

For now, you can wrap the `SdkIterable` with `PageIterable` to iterate through all items. `PageIterable.create(sdkIterable)`. Sorry about the confusion. We will update the javadocs.
