### ISSUE TITLE
DynamoDbEnhancedClient transaction write missing support for return values

### ISSUE THREAD

**Issue by openwebsolns** [aws/aws-sdk-java-v2#2283]
Support for [ReturnValuesOnConditionCheckFailure](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Put.html#DDB-Type-Put-ReturnValuesOnConditionCheckFailure) is missing from the `PutItemEnhancedRequest` object, but exists in the vanilla `PutItemRequest`.

## Describe the bug

Unlike V1's `DynamoDBMapper` or V2's plain `DynamoDbClient`, there is no way to specify `returnValues` on a put item request in `DynamoDbEnhancedClient`. Specifically, the `PutItemEnhancedRequest` object [is missing the field](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedRequest.Builder.html) which otherwise exists in [PutItemRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/PutItemRequest.Builder.html#returnValues-software.amazon.awssdk.services.dynamodb.model.ReturnValue-).

## Expected Behavior

I should be able to specify `ALL_OLD` (or `NONE`) for return values in a transaction write using `DynamoDbEnhancedClient`:

```java
TransactionWriteItemsEnhancedRequest request = TransactionWriteItemsEnhancedRequest.builder()
    .addPutItem(
        itemTable, // MappedTableResource
        PutItemEnhancedRequest.builder()
            .item(someItem)
            .conditionExpression(someExpression)
            .returnValues(ReturnValues.ALL_OLD)    // <<<< MISSING FUNCTIONALITY
            .build()
    ).build();
```

## Current Behavior

There is no way to specify `returnValues` [as can be done in plain PutItemRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/PutItemRequest.Builder.html#returnValues-software.amazon.awssdk.services.dynamodb.model.ReturnValue-).

## Steps to Reproduce

See above.

## Possible Solution

Add support as part of the `PutItemEnhancedRequest`; not sure if depending on `services.dynamodb` package is considered correct when working in `enhanced.dynamodb`.

## Context

Unable to migrate from `DynamoDBMapper` in V1 to `DynamoDbEnhancedClient` because of this missing functionality.

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@openwebsolns acknowledged!

**Comment by marcdejonge** [comment]
We have a similar problem for the `UpdateItemEnhancedRequest`, which is missing the option for a `returnValue`. This is a nice feature to check if an update actually changed anything and what the old values were.
