### ISSUE TITLE
Commons Lang NOTICE.txt missing

### ISSUE THREAD

**Issue by hyandell** [aws/aws-sdk-java-v2#2285]
## Describe the bug

The NOTICE.txt identifies code from Apache Commons Lang is included in the SDK, but it does not replicate Lang's NOTICE.txt file.

## Expected Behavior

It should include the Lang NOTICE.txt contents in the NOTICE.txt.

## Current Behavior

Not present.

**Comment by debora-ito** [comment]
Thank you @hyandell, we'll work on it.
