### ISSUE TITLE
Increasing timeout in LambdaAsyncClient 

### ISSUE THREAD

**Issue by sebarys** [aws/aws-sdk-java-v2#2287]
I was trying to increase timeout for `LambdaAsyncClient` unfortunately using builder I wasn't able to increase it.

## Describe the issue

I've tried to increase timeout by providing custom `ClientOverrideConfiguration`.

Example code snippet in Scala:
```
    val clientOverrideConfiguration = ClientOverrideConfiguration.builder()
      .apiCallTimeout(java.time.Duration.ofSeconds(180))
      .apiCallAttemptTimeout(java.time.Duration.ofSeconds(180))
      .build()

    val lambdaAsyncClient =
      LambdaAsyncClient.builder
        .region(Region.of(awsRegion))
        .overrideConfiguration(clientOverrideConfiguration)
        .credentialsProvider(StaticCredentialsProvider.create(awsCredentials))
        .build
```
When I deployed above changes unfortunately it seems that timeout didn't change and I'm still receiving:
```
Unable to execute HTTP request: Read timed out
```

Could anyone point me or tell how increasing socket/connection timeout should be done properly?

**Comment by debora-ito** [comment]
The timeout didn't change, or the api call is taking even more than 180 seconds?
You can try to increase the socket timeout:

```
LambdaAsyncClient lambda = LambdaAsyncClient.builder()
    .region(Region.of(awsRegion))
    .overrideConfiguration(clientOverrideConfiguration)
    .credentialsProvider(StaticCredentialsProvider.create(awsCredentials))
    .httpClient(NettyNioAsyncHttpClient.builder()
        .readTimeout(Duration.ofSeconds(60))
        .build())
    .build();
```

**Comment by sebarys** [comment]
We have one lambda that is triggered very rarely but execution takes ~60seconds. 

Thanks I will try this *httpClient* configuration!
You can consider attach snippet of code that show how override default timeouts somewhere in documentation, I saw `httpClient` option in builder but didn't have idea about `NettyNioAsyncHttpClient.builder()`

**Comment by debora-ito** [comment]
We have a small example in the Java SDK Dev Guide showing [Netty-based HTTP Client configuration](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-netty.html), but yes I think we can improve it.
