### ISSUE TITLE
Add support for update expressions when using the enhanced Dynamo client

### ISSUE THREAD

**Issue by kruez** [aws/aws-sdk-java-v2#2292]
The non-enhanced Dynamo client supports [atomic attribute incrementing](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/WorkingWithItems.html#WorkingWithItems.AtomicCounters) as provided by the [UpdateItemRequest.updateExpression](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/UpdateItemRequest.Builder.html#updateExpression-java.lang.String-). By contrast the enhanced Dynamo client's [UpdateItemEnhancedRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedRequest.Builder.html) requires the entire item be provided in order to fully overwrite an existing row.  No attribute incrementing supported.

This lack of feature parity leads to situations where the enhanced and non-enhanced clients usage are intermixed in a single project, or even a single class/method.

## Describe the Feature
The enhanced Dynamo client should support taking update requests that allow for atomic attribute incrementing, same as the non-enhanced client supports.

## Is your Feature Request related to a problem?
Mixing usage of enhanced and non-enhanced Dynamo client usage in a single class/method leads to messier code. Developers will assume that by adopting the enhanced client it should make their interactions with Dynamo simpler, but that isn't the case in all situations.

## Proposed Solution
* `UpdateItemEnhancedRequest` should be further enhanced to support update expressions.
*  Or the enhanced Dynamo client can be updated to take either an `UpdateItemEnhancedRequest` or an `UpdateItemRequest` object.

## Describe alternatives you've considered
At this time I either need to ditch use of the enhanced client altogether, or use both clients and add comments to explain why this is necessary.

## Additional Context
Ideally, whatever the solution is, would allow me to use the enhanced version of the Dynamo client for all use cases.

## Your Environment
* AWS Java SDK version used: v2
* JDK version used: n/a
* Operating System and version: n/a

**Comment by debora-ito** [comment]
Thank you for reaching out @kruez. Acknowledged as a feature request.

**Comment by aswindjs** [comment]
+1 , we have a use case where we need to atomically increment or decrement a field in a @DynamodbBean class. 
Two options I can think of are,
1. Having a new annotation type to indicate atomic variables and having update/putItem request include the operation to perform on the atomic variable.  
2. Expanding WriteModification to include an option to return additional Expressions to include in your request. This would allow users to build their own logic. As long as the expressions are on attributes marked with @DynamodbIgnoreWrite it shouldn't interfere with auto generated expression from the EnhancedClient.

**Comment by ihar-knyshau** [comment]
+1, unable to add item in array attribute through single operation

**Comment by devhak2** [comment]
+1, If we append an item into a list, it's needed to get the entity, merge it into new one and then update it. With update expression, it can reduce useless RCU.

**Comment by mmunareto** [comment]
+1, Hello! This feature would be of great value to our team, because today we cannot migrate to dynamodb-enhanced because we use atomic counter in our operations.

**Comment by bstoilov** [comment]
+1 this is a major feature, I also can't see the reasoning behind removing it in v2..

**Comment by cenedhryn** [comment]
Since DDB Enhanced is written from the ground up, these features were not removed, but were just not included in the GA release due to limitations in resources. This feature request is an important indicator for us to know what feature to prioritize both within DDB Enhanced as well as within the SDK as a whole. Thanks for letting us know what you need!

**Comment by marcogramy** [comment]
+1 for this feature!

**Comment by faizanmd** [comment]
+1

**Comment by changshuo1989** [comment]
+1

**Comment by davidemarrone** [comment]
+1

**Comment by itzbhushan** [comment]
+1

**Comment by debora-ito** [comment]
Please please stop adding +1 comments, they are not helpful, they only add noise. If you want to show support for any feature request in the SDK add a 👍  in the original description. We use the reaction count to help us prioritize and plan for next features.

Update expression is in the works, we are actively working on it - https://github.com/aws/aws-sdk-java-v2/pull/3036.

**Comment by debora-ito** [comment]
Update expressions and atomic counter for DynamoDB Enhanced Client are now available, starting in Java SDK version `2.17.194`.

Check out our blog post showing how to use: https://aws.amazon.com/blogs/developer/using-atomic-counters-in-the-enhanced-dynamodb-aws-sdk-for-java-2-x-client/

**Comment by dlepe** [comment]
@debora-ito kudos to the team for delivering this feature! I've been actively waiting for this PR to get merged. So far, I'm pleased to see it even works with TransactUpdate statements.

Anywhere I can help or contribute to any documentation on how to use this new feature in the enhanced client documentation or read me? I've spent a couple of days playing around with the new API now.
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-dynamodb-enhanced.html

**Comment by hungthai-retudo** [comment]
Hi @debora-ito ,

Would update expression available for `TransactUpdateItemEnhancedRequest`?
Our use case is that we need to append item to list while update item. Without that, we need to getItem then merge object then updateItem, but more important, we can't use transactWriteItems for these steps.
Thank you

**Comment by vivek-rao-1985** [comment]
@debora-ito is it possible to append to a list of objects? I have the following document structure -
```
{
    "Items": [
        {
            "id": {
                "S": "123"
            },
            "list": {
                "L": [
                    {
                        "M": {
                            "some_field": {
                                "S": "some_value"
                            }
                        }
                    }
                ]
            }
        }
    ],
    "Count": 1,
    "ScannedCount": 1,
    "ConsumedCapacity": null
}
```
I'm trying to create an ```UpdateExpression``` that appends an object to the "list" above. So far I have this -
```
final AttributeValue newValue = AttributeValue.builder().m(appendValue).build();
final AddAction addAction = AddAction.builder()
        .path("#results")
        .value(":b")
        .putExpressionName("#results", "results")
        .putExpressionValue(":b", newValue)
        .build();
return UpdateExpression.builder()
        .addAction(addAction)
        .build();
```
But I get the following error -
```
Two document paths overlap with each other; must remove or rewrite one of these paths;
```

**Comment by carvantes** [comment]
I feel like this was closed without addressing the main request: "Add support for update expressions when using the enhanced Dynamo client"

Is there are a reason to not simply accept an `UpdateExpression` as a parameter for `updateItem`?

btw, my use case is that I want to atomically increase a counter, but not always by one, and not on every uppdateItem call. so the `@DynamoDbAtomicCounter` nor the "UpdateExpression extension" work

**Comment by dlepe** [comment]
Hey @carvantes, I ran into the same exact problem myself. In my use case, I needed to atomically decrement a counter by a specific value and simultaneously check that I had sufficient count for that decrement (inventory reservation, in other words).

I have a workaround I'm using here but I opened a feature request to allow `UpdateExpression` to be passed into the `UpdateItem` request. 
https://github.com/aws/aws-sdk-java-v2/issues/3218

**Comment by cenedhryn** [comment]
Thanks for your engagement with this feature. We intentionally released it with schema level support only, and we knew that not all update use cases would work (such as updating lists) from the get-go. Because it's a mechanism that partly bypasses the inherent functions of the enhanced library, and is also somewhat counter to its abstractions, it made sense to add it to the extensions framework and gauge how users were applying it. Your feedback on request level support is valuable, and we encourage anyone who wants to see it added to plus one on this issue.

**Comment by davidemarrone** [comment]
+1 to implement this issue

**Comment by Hasan-Jawaheri** [comment]
For anyone who is still stuck on this, the extension feature works like this for list append:
```
public final class TransactUpdateRequestMetadataDDBClientExtension implements DynamoDbEnhancedClientExtension {

    @Override
    public WriteModification beforeWrite(final DynamoDbExtensionContext.BeforeWrite context) {
        if (context.tableSchema().equals(LaborAdjustmentRequestMetadataDDBItem.LABOR_ADJUSTMENT_REQUEST_METADATA_SCHEMA) &&
                context.operationName().equals(OperationName.UPDATE_ITEM) &&
                context.items().containsKey(LaborAdjustmentRequestMetadataDDBItem.RECORDS_LIST_ATTRIBUTE_NAME)) {

            // this is an update operation for LaborAdjustmentRequestMetadataDDBItem and contains the records attribute
            final AttributeValue newRecords = context.items().get(LaborAdjustmentRequestMetadataDDBItem.RECORDS_LIST_ATTRIBUTE_NAME);
            final UpdateExpression expression = UpdateExpression.builder()
                    .addAction(SetAction.builder()
                        .path("#a_records")
                        .value("list_append(#a_records, :v_records)") // create a list_append for the 'records'
                        .putExpressionName("#a_records", LaborAdjustmentRequestMetadataDDBItem.RECORDS_LIST_ATTRIBUTE_NAME)
                        .putExpressionValue(":v_records", newRecords)
                        .build())
                    .build();

            return WriteModification.builder()
                    // remove 'records' attribute from the original item, otherwise there will be 2 updates on the same attribute
                    .transformedItem(context.items()
                        .entrySet()
                        .stream()
                        .filter((e) -> !e.getKey().equals(LaborAdjustmentRequestMetadataDDBItem.RECORDS_LIST_ATTRIBUTE_NAME))
                        .collect(ImmutableMap.toImmutableMap(Map.Entry::getKey, Map.Entry::getValue)))
                    .updateExpression(expression)
                    .build();
        }

        return WriteModification.builder().build();
    }
}

```

Notice that you need to remove the attribute from the item before returning (using `.transformedItem()`) to avoid the `Two document paths overlap with each other; must remove or rewrite one of these paths;` error.

**Comment by roccopolimen** [comment]
It's been over a year, any updates on this or somewhere to see this being tracked?

**Comment by fbokovikov** [comment]
Any updates on that? Would be nice to have this feature
