### ISSUE TITLE
The right way to serialize and deserialize dynamodb lastEvaluatedKey Map<String, AttributeValue>?

### ISSUE THREAD

**Issue by user20161119** [aws/aws-sdk-java-v2#2295]
I want to add pagination on my app like the aws dynamodb console
![image](https://user-images.githubusercontent.com/123967/108619848-97f58880-7462-11eb-9911-140cb63615ee.png)

tried serialize the lastEvaluatedKey use the following code
```java
 Map<String, AttributeValue> lastEvulateKey = new HashMap<>();
        lastEvulateKey.put("shopID", AttributeValue.builder().s("xyz").build());
        lastEvulateKey.put("itemID", AttributeValue.builder().n("123").build());
        System.out.println(JsonUtils.writeValue(lastEvulateKey));
```
but the attribute is empty as follow
```java
{"itemID":{},"shopID":{}}
```
any advice about to serialize lastEvaluateKey to front web and deserialize the lastEvaluateKey from fron web like aws dynamodb console dose ,thanks

**Comment by tuckerbuchy** [comment]
+1

**Comment by debora-ito** [comment]
@user20161119 I'm not clear on why do you need to serialize/deserialize the hashmap in order to use the SDK.
Can you give a sample code of what you're trying to do? How are you getting the info from the front web? You're not calling the APIs?

**Comment by user20161119** [comment]
> @user20161119 I'm not clear on why do you need to serialize/deserialize the hashmap in order to use the SDK.
> Can you give a sample code of what you're trying to do? How are you getting the info from the front web? You're not calling the APIs?

think the pagination flow on the web page
1. web page get the lastevaluatedkey from server
2. pass the lastedevaluatedkey to the server for next page
3. set the lastevaluatedkey to the sdk
so i need to serialize/deserialize the hashmap

**Comment by defoo** [comment]
+1
