### ISSUE TITLE
Thoughts on exposing endpoint prefix in client interface

### ISSUE THREAD

**Issue by abrooksv** [aws/aws-sdk-java-v2#2301]
## Describe the Feature
Add new public String to each generated client interface containing the endpoint prefix

## Is your Feature Request related to a problem?
If we look at ECR we get the service name (or ID) is "ecr":

```
public interface EcrClient extends SdkClient {
    String SERVICE_NAME = "ecr";
```

but ECRs endpoint data is "api.ecr"
https://github.com/aws/aws-sdk-java-v2/blob/41a86004660eb94974b8a1459bf5254c59248806/core/regions/src/main/resources/software/amazon/awssdk/regions/internal/region/endpoints.json#L324
https://github.com/aws/aws-sdk-java-v2/blob/8db24fd31b68207fa0a001995c4608dfc5bcbce2/services/ecr/src/main/resources/codegen-resources/service-2.json#L5

## Proposed Solution
```
public interface EcrClient extends SdkClient {
    String SERVICE_NAME = "ecr";
	String REGION_ENDPOINT_PREFIX = "api.ecr";
```

This is similar to what is exposed in .NET: https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Services/ECR/Generated/AmazonECRConfig.cs#L54

This string can then be passed to the public API: 
https://github.com/aws/aws-sdk-java-v2/blob/93f2f1389d0811f06c7d5e58c9643629b96d517a/core/regions/src/main/java/software/amazon/awssdk/regions/ServiceMetadataProvider.java#L32

We can bikeshed on the name later

## Additional Context

- [x] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@abrooksv it's a reasonable ask, marking as a feature request. Looking forward to see your PR 😃

**Comment by abrooksv** [comment]
PR created #2327
