### ISSUE TITLE
Invalid example date on HeadObjectResponse.restore()

### ISSUE THREAD

**Issue by pwinckles** [aws/aws-sdk-java-v2#2302]
## Describe the issue

There's an invalid date in the documentation for `HeadObjectResponse.restore()`:

> If the object is an archived object (an object whose storage class is GLACIER), the response includes this header if either the archive restoration is in progress (see RestoreObject  or an archive copy is already restored.
>
> If an archive copy is already restored, the header value indicates when Amazon S3 is scheduled to delete the object copy. For example:
>
> x-amz-restore: ongoing-request="false", expiry-date="Fri, 23 Dec 2012 00:00:00 GMT"
>
> If the object restoration is in progress, the header returns the value ongoing-request="true".
>
> For more information about archiving objects, see Transitioning Objects: General Considerations.

December 23, 2012 was a **Sunday**.

`Fri, 23 Dec 2012 00:00:00 GMT` should either be `Sun, 23 Dec 2012 00:00:00 GMT` or `Fri, 21 Dec 2012 00:00:00 GMT`

## Links

https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/resources/codegen-resources/service-2.json#L4606

**Comment by debora-ito** [comment]
Thank you for reporting this @pwinckles, I will forward to the S3 documentation team.

**Comment by debora-ito** [comment]
@pwinckles the docs are now fixed, they read `Fri, 21 Dec 2012 00:00:00 GMT`. Thank you again.
