### ISSUE TITLE
"IN" Statement doesn't work with StringSet

### ISSUE THREAD

**Issue by driverpt** [aws/aws-sdk-java-v2#2306]
## Describe the bug
We are trying to do a query with a `IN` Statement and setting a StringSet in Query Expression

e.g.:

```
--filter-expression 'field1 IN (:fieldList)'
--expression-attribute-values '{":fieldList": {"SS":["value1", "value2"]}}'
```

Documentation isn't clear about this scenario

## Expected Behavior
The Query to actually return some values

## Current Behavior

We need to manually set value1 and value2 as variables, e.g.:
```
--filter-expression 'field1 IN (:fieldValue1,:fieldValue2)'
--expression-attribute-values '{":fieldValue1": {"S":"value1"}, ":fieldValue2": {"S":":value2"}}'
```

## Steps to Reproduce
See Description

## Possible Solution
I believe it's DynamoDb backend related

## Context

We are trying to execute a query

## Your Environment

* AWS Java SDK version used: 2.15.63
* JDK version used: 11
* Operating System and version: N/A

**Comment by debora-ito** [comment]
@driverpt I found a documentation page in the [Condition Expressions Syntax Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Expressions.OperatorsAndFunctions.html) and it describes the current behavior:

Use the BETWEEN and IN keywords to compare an operand against a range of values or an enumerated list of values:
- `a BETWEEN b AND c` - true if a is greater than or equal to b, and less than or equal to c.
- `a IN (b, c, d)` - true if a is equal to any value in the list — for example, any of b, c or d. The list can contain up to 100 values, separated by commas.

So this behavior is expected. Let us know if you have any further questions.

**Comment by driverpt** [comment]
So if I switch to type `L` it will work? It should work with a String set as well, as it's a list

**Comment by driverpt** [comment]
Update: Tried with 
```
'{":fieldList": {"L":[{"S": "value1"}, {"S": "value2"}]}}'
```
And it doesn't work.

This may be an expected behaviour, but it's poorly documented

**Comment by debora-ito** [comment]
Yeah I agree, the doc is confusing. I will reach out to the documentation team and ask to clearly describe the usage of IN statements.

**Comment by driverpt** [comment]
@debora-ito , doesn't make sense for DynamoDb to support `SS` and `L` as Parameter Values for an `IN` statement?

**Comment by debora-ito** [comment]
Closing this old ticket, as it's a service documentation issue and there's nothing pending on the SDK side.
