### ISSUE TITLE
More client customization options on TranscribeStreamingAsyncClient

### ISSUE THREAD

**Issue by JRasteiro** [aws/aws-sdk-java-v2#2315]
For larger spikes in concurrent calls to Transcribe I'm getting the following error:

```Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.If the above mechanisms are not able to fix the issue, try smoothing out your requests so that large traffic bursts cannot overload the client, being more efficient with the number of times you need to call AWS, or by increasing the number of hosts sending requests.```

Looking at the client code, which seems to be generated, it looks like the underlying netty HTTP client is configured with a maximum of 50 concurrent connections. However, this value cannot be configured with `ClientAsyncConfiguration` nor the builder for the Transcribe client.
Therefore the pool here: https://github.com/aws/aws-sdk-java-v2/blob/35267ca707c3fb5cdf7e3e98758a8ef969269183/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/utils/BetterFixedChannelPool.java will always be of size 50.

Looking at some other clients for other services such as SQS it seems like the client's builder offers more configurations options in the builder.

## Describe the Feature

Expand the builder's configuration possibilities for the use case of:
```
public TranscribeStreamingAsyncClient buildTranscribeStreamingAsyncClient() {
        return TranscribeStreamingAsyncClient.builder()
            .credentialsProvider(new CredentialsProvider(keyId, keySecret))
            .region(Region.of(region))
            .build();
}
```

## Proposed Solution

Have some more customization that are used by `BetterFixedChannelPool` such as:
```
public TranscribeStreamingAsyncClient buildTranscribeStreamingAsyncClient() {
        return TranscribeStreamingAsyncClient.builder()
            .credentialsProvider(new CredentialsProvider(keyId, keySecret))
            .region(Region.of(region))
            .asyncConfiguration(ClientAsyncConfiguration.builder()
                          .maxConnections()
                          .connectionTimeout()
                          .acquireTimeout()
                          .maxConnectionAcquires()
                          .writeTimeout()
                          .connectionTimeToLive()
                          .build()
             )
            .build();
}
```

## Describe alternatives you've considered
The only alternative considered would be to not use the SDK and call the API directly, effectively having to write what the SDK does.

- [ ] I may be able to implement this feature request

## Your Environment
* AWS Java SDK version used: 2.16.5
* JDK version used: OpenJDK 11.0.7
* Operating System and version: MacOS Catalina (10.15.7)

**Comment by zoewangg** [comment]
You can apply custom HTTP configurations via `TranscribeStreamingAsyncClientBuilder#httpClientBuilder` or `TranscribeStreamingAsyncClientBuilder#httpClient`

```java
TranscribeStreamingAsyncClient.builder()
                              .httpClientBuilder(NettyNioAsyncHttpClient.builder()
                                                                        .maxConcurrency(100)
                                                                        .connectionTimeout(xxx))
                              .build();
```

**Comment by JRasteiro** [comment]
Thanks for the quick answer, that's exactly what I was looking for.
However I can't seem to actually use that builder.

I can see the dependency in our dependency tree, being brought in by transcirbestreaming, but I can't actually import `software.amazon.awssdk.http.nio.netty`

I'm using the following in our pom:
```
(...)
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>software.amazon.awssdk</groupId>
                <artifactId>bom</artifactId>
                <version>2.16.5</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
(...)

<dependencies>
(...)
    <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>transcribestreaming</artifactId>
    </dependency>
(...)
</dependencies>
```

Do I need to manually add the dependency regardless?

**Comment by zoewangg** [comment]
Hmm, weird, `netty-nio-client` dependency should be included automatically. Did you exclude it somewhere by any chance?

Can you try explicitly adding `netty-nio-client` to see if it works?

```
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>netty-nio-client</artifactId>
        </dependency>
```

**Comment by JRasteiro** [comment]
Yes, only by explicitly adding the dependency does it solve the issue.
I'm just not sure if this is the expected usage, or if simply having `transcribestreaming` should have been enough.

**Comment by debora-ito** [comment]
Hi @JRasteiro to test this, I started a new project in Intellij and declared only `transcribestreaming` as a dependency, and `netty-nio-client` does show up in the dependency tree. Please check if you are not excluding it unintentionally. It may also worth it to try cleaning your local maven repository and force it to download the dependencies again.
