### ISSUE TITLE
Manual pagination with dynamodb scan

### ISSUE THREAD

**Issue by pacozaa** [aws/aws-sdk-java-v2#2320]
## Anyone knows how to Manual pagination with dynamodb scan?

I can't seem to find the solution to disable auto-pagination for the scan method in dynamodb library. 

Any help would be appreciate!

**Comment by debora-ito** [comment]
@pacozaa take a look at the documentation page about pagination and see if it helps - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/pagination.html

In case you have further questions, can you share a code sample?
