### ISSUE TITLE
Proxy configurations for different SDK http clients doesn't have feature parity. 

### ISSUE THREAD

**Issue by kra3** [aws/aws-sdk-java-v2#2321]
Netty and Amazon CRT Http client's proxy configurations are not aware of system proxy settings. Such as those passed in via [JDK properties](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/net/doc-files/net-properties.html) (eg: `http.proxyHost`, `http.proxyPort`). However Apache proxy configuration is aware of those properties.

Also, there are other issues to make `ProxyConfigurations` to feature parity with older aws-sdk-java's Proxy configuration (eg: #1793)

**Comment by debora-ito** [comment]
Thank you for reaching out @kra3, this is a reasonable feature request.

**Comment by erin889** [comment]
@debora-ito Since it's tagged with **hacktoberfest**, do you mind I jump in and contribute to it?

**Comment by Bennett-Lynch** [comment]
Resolved via https://github.com/aws/aws-sdk-java-v2/pull/2771.
