### ISSUE TITLE
Having the url-connection-client dependency on the class path breaks URL presigning for S3

### ISSUE THREAD

**Issue by wscsprint3r** [aws/aws-sdk-java-v2#2325]
[comment]: <> (Having the url-connection-client dependency on the class path breaks URL presigning for S3)

## Describe the bug
Not sure if this is some expected behavior that I don't understand but 
using the 2.6.13 S3 SDK together with "software.amazon.awssdk:url-connection-client" 
and the Default credential provider chain breaks S3 presigned URLs. 

I ran across this issue in a Quarkus project that has a SES extension which requires the url-connection-client or apache-client to enable DI and we also have a module that writes to S3 which is configured manually using the Default Credential Provider.

I did not investigate why exactly this happens.

## Expected Behavior
S3 presigning should work normally when the **url-connection-client** dependency is present. 

## Current Behavior
Trying to upload a file to using an S3 PUT presigned URL generated by the 2.0 Java SDK returns **code 403** instead of 200. 

Start with the current code, based on the SDK samples:

```java

    public static void main(String[] args) {
        String bucketName = args[0];
        String keyName = args[1];
        Region region = Region.EU_WEST_1;
        S3Presigner presigner = S3Presigner.builder()
        .region(region)
        .credentialsProvider(DefaultCredentialsProvider.create())
        .build();
        signBucket(presigner, bucketName, keyName);
        presigner.close();
    }

    public static void signBucket(S3Presigner presigner, String bucketName, String keyName) {

        try {
            PutObjectRequest objectRequest = PutObjectRequest.builder()
                    .bucket(bucketName)
                    .key(keyName)
                    .build();

            PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
                    .signatureDuration(Duration.ofMinutes(10))
                    .putObjectRequest(objectRequest)
                    .build();

            PresignedPutObjectRequest presignedRequest = presigner.presignPutObject(presignRequest);

            System.out.println("Presigned URL to upload a file to: " +
                    presignedRequest.url());
            System.out.println("Which HTTP method needs to be used when uploading a file: " +
                    presignedRequest.httpRequest().method());

            // Upload content to the Amazon S3 bucket by using this URL
            URL url = presignedRequest.url();

            // Create the connection and use it to upload the new object by using the presigned URL
            HttpURLConnection connection = (HttpURLConnection) url.openConnection();
            connection.setDoOutput(true);

            connection.setRequestMethod("PUT");
            OutputStreamWriter out = new OutputStreamWriter(connection.getOutputStream());
            out.write("This text was uploaded as an object by using a presigned URL.");
            out.close();

            connection.getResponseCode();
            System.out.println("HTTP response code is " + connection.getResponseCode());

        } catch (S3Exception | IOException e) {
            e.getStackTrace();
        }
    }
```

build.gradle dependencies:
```groovy
    
    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
        implementation platform('software.amazon.awssdk:bom:2.16.13')
        implementation 'software.amazon.awssdk:s3'
        implementation 'software.amazon.awssdk:sts'
    }
```

**OUTPUT: HTTP response code is 200 as expected**

_**Now add the extra dependency because it's needed somewhere else, no other code changes**_:

```groovy

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.6.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine'
        implementation platform('software.amazon.awssdk:bom:2.16.13')
        implementation 'software.amazon.awssdk:s3'
        implementation 'software.amazon.awssdk:sts'
        implementation 'software.amazon.awssdk:url-connection-client'
        
    }
```

**OUTPUT: HTTP response code is 403**

## Workaround
Using _**software.amazon.awssdk:apache-client**_ does not break S3 presigning. 

## Environment
* AWS Java SDK version used: 2.6.13
* JDK version used:11 
* Operating System and version: Linux 5.11.1-arch1-1
* Actual provider used for authentication: WebIdentityTokenFileCredentialsProvider

**Comment by debora-ito** [comment]
Hi @wscsprint3r having `url-connection-client` as a dependency should not be a problem. I was not able to reproduce the issue, but I'm not using Quarkus.

Can you share the stacktrace of the error?

**Comment by debora-ito** [comment]
Actually, 403 is _Forbidden_, this is probably an issue with permissions to access the bucket. This troubleshooting guide provides some directions to solve it - https://aws.amazon.com/premiumsupport/knowledge-center/s3-troubleshoot-403/

**Comment by wscsprint3r** [comment]
Hello @debora-ito. Thanks for the reply!

There is no error/stacktrace. The return code is 403/**AccessDenied** indeed. 

Here is my tiny debug project which for me is enough to reproduce the problem:
https://github.com/wscsprint3r/AWS-SDK-2-DEBUG-2325

In production we have a bucket with all public access restricted, we have an IAM role with an attached policy that gives R/W access to the bucket. The service assumes that role in order to write to the bucket.

To emulate what we do in production for the small debug project we use the WebIdentityTokenFileCredentialsProvider and steal the token and do:
```

export AWS_WEB_IDENTITY_TOKEN_FILE=$(pwd)/token
export AWS_ROLE_ARN=arn:aws:iam::..........
export AWS_REGION=eu-west-1

```

I run the project and I can successfully upload the file. Then I un-comment the `url-connection-client` dependency from the build.gradle file, without changing anything else the return code turns to **403**.

**Comment by debora-ito** [comment]
Since you are using the default credentials provider chain, when you add the `url-connection-client` maybe a different credential is being picked up. Can you run STS GetCallerIdentity in both cases and compare them?

Also seeing DEBUG logs or verbose wire logs may give more insights. Please remember to redact any sensitive information if you choose to share the verbose wire logs with us.

**Comment by fmusayev** [comment]
I have experienced the same issue, glad to find this issue. Somehow url-connection-client breaks something, don't want to lose time debugging this, will try apache-client. I have added url-connection-client to use sqs
