### ISSUE TITLE
Cannot retrieve savings plans from us-east-2

### ISSUE THREAD

**Issue by krachwal** [aws/aws-sdk-java-v2#2330]
We have been using 2.16.7 extensively in our product. This is the first time I've had an issue with specifying the region to the client builder. The following works from our server in us-east-1, but not from a server in us-east-2.
```java
InstanceProfileCredentialsProvider credProvider = InstanceProfileCredentialsProvider.builder().build();

savingsplansClient = SavingsplansClient.builder()
                                .credentialsProvider(credProvider)
                                .build();
                                
DescribeSavingsPlansRequest request = DescribeSavingsPlansRequest.builder()
                                .build();
                                
DescribeSavingsPlansResponse response = savingsplansClient.describeSavingsPlans(request);
```

## Expected Behavior
I expect to get savings plans regardless of hosting region, since savingsplans is global.

## Current Behavior
On the instance of our application that runs in us-east-1, whether there is a region specified or not we get the savings plan data back. On a similar instance running in us-east-2 we get:
```
software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. This specific service is global in the same partition as the region configured on this client (us-east-2). If this is the first time you're trying to talk to this service in this region, you should try configuring the global region on your client, instead: aws-global
```
I tried setting the region on the client to the cred region for the savingsplan service (us-east-1) and to aws-global (per the error message) but I still get the error above, including the bit about us-east-2, which makes it seem like the .region() gets ignored by the SavingsplanClient builder altogether.

I also tried the CLI to see if it was a networking issue.
```bash
aws savingsplans describe-savings-plans # works fine
```

## Your Environment

* AWS Java SDK version used: 2.16.7
* JDK version used: 11
* Operating System and version: Ubuntu on EC2

**Comment by debora-ito** [comment]
Hi @krachwal thank you for reaching out, I'm sorry for the delayed response. 

Setting the region to `aws-global` should have fixed the issue, I'm curious why it didn't in your case. Can you turn on the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) and share them? Please make sure to redact any sensitive information.

**Comment by krachwal** [comment]
Sorry for the delay. I appreciate the confirmation that setting the region to global should work. In getting back onto the server with one of our admins to get you additional debug information, it turned out that the binary in which we had applied the global region patch was not the binary that had been deployed... :grimacing: :facepalm:
