### ISSUE TITLE
EnumAttributeConverter default constructor SDK 2.16

### ISSUE THREAD

**Issue by mlhrAnjaria** [aws/aws-sdk-java-v2#2335]
When using `EnumAttributeConveter` for enums in `DynamoDbTypeConvertedBy`, TableSchema generation fails for the class / bean.

## Describe the bug
I am trying to use EnumAttributeConverter on Enum attributes of a DynamoDbBean with `DynamoDbTypeConvertedBy` as following:
```
@DynamoDbBean
public class SourceEntity implements Serializable
{
    @Getter(onMethod_ = {@DynamoDBAttribute(attributeName = "recentSyncHistory")})
    private List<SyncEntity> recentSyncHistory;

.....
}

@DynamoDbBean
@DynamoDBDocument
public class SyncEntity implements Serializable
{

    @Getter(onMethod_ = {@DynamoDBAttribute(attributeName = "id")})
    private UUID id;

    @Getter(onMethod_ = {@DynamoDBAttribute(attributeName = "trigger"),
        @DynamoDbConvertedBy(EnumAttributeConverter.class)
    })
    private SyncTrigger trigger;
```

## Expected Behavior
EnumAttributeConverter should take care of initialisation and enum coversion to and from String value.

## Current Behavior
Exception is thrown as:
```
java.lang.IllegalArgumentException: Class 'class software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.EnumAttributeConverter' 
appears to have no default constructor thus cannot be used with the BeanTableSchema
    at 
software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(
BeanTableSchema.java:333)
```

## Your Environment

* AWS Java SDK version used: 2.16.16
* JDK version used: 1.8
* Operating System and version: Mac OS 10.15.7

**Comment by debora-ito** [comment]
Hi @mlhrAnjaria apologies for the long delay in response here. 

To use the AttributeConverters provided by the SDK you don't need to explicitly declare `@DynamoDbConvertedBy`, you only need to use this annotation when using a custom AttributeConverter.

Let us know if this helps.

**Comment by RushinNaik** [comment]
@debora-ito What will be a replacement of "@DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)" while using the SDK v2 ?

**Comment by debora-ito** [comment]
@RushinNaik a Java String attribute will be automatically converted to a DynamoDB String type, no annotation is needed. Take a look at the [DDB Enhanced Client overview](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/README.md) for more info.

**Comment by mlhrAnjaria** [comment]
@debora-ito Yes figured it out. Conversion was failing due to other error and wasn't clear from log. Thanks.

**Comment by debora-ito** [comment]
Great! Feel free to reach out if you have any more questions.
