### ISSUE TITLE
Any change needed to use Signature Version 4?

### ISSUE THREAD

**Issue by joaodias14** [aws/aws-sdk-java-v2#2336]
We are now changing credentials to use Signature Version 4, but using software.amazon.awssdk.ses version 2.15.58 we get an exception.

## Describe the issue
We get the following error:
`Exception in thread "DefaultDispatcher-worker-2" software.amazon.awssdk.services.ses.model.SesException: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.`

In the link below we see the following but is it really that simple or anything is needed to have it working with Signature Version 4?
`Important
If you are using one of the AWS SDKs (including the SDK for Java, .NET, Python, Ruby, or JavaScript), you do not have to manually perform the steps of deriving a signing key and adding authentication information to a request. The SDKs perform this work for you. You need to manually sign requests only if you are directly making HTTP or HTTPS requests.`

## Links
https://docs.aws.amazon.com/ses/latest/DeveloperGuide/using-ses-api-authentication.html

**Comment by debora-ito** [comment]
@joaodias14 Java SDK 2.x uses signature v4 by default, no additional configuration should be needed. 

A signature mismatch error can have several causes, you can troubleshoot it by looking at the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html) and compare the returned strings with calculated string to sign sent in the request. More info in this troubleshooting guide: https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

Let us know if this helps.

**Comment by joaodias14** [comment]
Many thanks for the fast feedback. We will check this. 
Is it possible that the error has anything to do with an incorrect credentials generation? I am asking this because the credentials (access key ID and secret access key) are handed over to us by the platform team, so we are not aware of the generation process.

**Comment by joaodias14** [comment]
We fixed our issue. The problem was the secret access key. We were using the wrong value.
