### ISSUE TITLE
Leading spaces in S3 metadata causes "The request signature we calculated does not match the signature you provided"

### ISSUE THREAD

**Issue by vladimirtiukhtin** [aws/aws-sdk-java-v2#2344]
## Describe the bug
I guess it is similar to https://github.com/aws/aws-sdk-go/issues/2448

## Expected Behavior
This is a good question. Should users be trimming their metadata or SDK???

## Current Behavior
Error received
```
The request signature we calculated does not match the signature you provided
```

**Comment by debora-ito** [comment]
Hi @vladimirtiukhtin thank you for reaching out. Can you share a repro code?
