### ISSUE TITLE
S3 Select Object Content

### ISSUE THREAD

**Issue by DiaGitHub** [aws/aws-sdk-java-v2#2345]
## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by DiaGitHub** [comment]
We've done a migration from sdk v1 to sdk v2 and we've noticed that **selectObjectContent** method is still not supported in sdk v2.
Is there any specific problem to not add this feature please?

**Comment by debora-ito** [comment]
It's not supported yet, we are keeping track of this issue here: https://github.com/aws/aws-sdk-java-v2/issues/859.

You can upvote in the original description of the issue, it helps us with prioritization.
