### ISSUE TITLE
DynamoDB Enhanced client should ignore @Transient properties

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#2347]
The DynamoDB Enhanced client, when building a `TableSchema.fromClass`, lists the properties and then tries to map them onto DynamoDB attributes. However, the code as it currently stands is incompatible with Groovy, because it looks for a mapping from the `groovy.lang.MetaClass metaClass` property, predictably does not find it, and throws an exception.

This property (more specifically the `getMetaClass()` accessor) is annotated with `@java.beans.Transient`, which is a standard JDK annotation and automatically sets the attribute `transient=true` on the `PropertyDescriptor`.

The client should, in `createStaticTableSchema`, filter out properties that are annotated `@Transient`. In addition to preserving compatibility, this is the general semantic expectation for the annotation.

SDK version: 2.16.20

**Comment by debora-ito** [comment]
@chrylis thank you for the report, and apologies for the delayed response. Marking this as a bug.

**Comment by marcusvoltolim** [comment]
> Para quem procura. Encontrei 2 soluções:
> 
> 1. Versão groovy rebaixada para 2 (2.5.15 é o que eu usei)
> 2. Adicionando a propriedade e anotando-a com DynamoDBIgnore
>    `   @DynamoDBIgnore MetaClass metaClass;`

How do you annotate a field if the annotation is for method only?

**Comment by marcusvoltolim** [comment]
> For anyone else looking. I found 2 solutions:
> 
> 1. Downgraded groovy version to 2 (2.5.15 is what I used)
> 2. Adding the property and annotating it with DynamoDBIgnore
>    `   @DynamoDBIgnore MetaClass metaClass;`

How do you annotate a property if the annotation is for method only?

**Comment by marcusvoltolim** [comment]
What I've been doing in Groovy projects is creating the classes mapped as .java and using lombok @Getter/@Setter annotations and just adding getter methods for @DynamoDbPartitionKey and @DynamoDbSortKey.
Example:
`import java.util.List;

@Getter
@Setter
@DynamoDbBean
public class User {

    private String id;
    private String authority;
    private String name;
    private String email;
    private List<Address> addresses;

    @DynamoDbPartitionKey
    public String getId() {
        return id;
    }

    @DynamoDbSortKey
    @DynamoDbAttribute("authorityLevel")
    public String getAuthority() {
        return authority;
    }
    
}
`
