### ISSUE TITLE
DynamoDB Enhanced mapping annotations should be @Inherited

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#2348]
In attempting to work around #2347, I added an abstract method for the problem property and applied `@DynamoDbIgnore` to it. However, because this annotation is not marked `@Inherited`, it's not propagated and therefore not picked up by the mapper.

The mapping annotations should be meta-annotated with `@Inherited`.

SDK version: 2.16.20

**Comment by debora-ito** [comment]
@chrylis according to the `@Inherited`  [documentation](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/annotation/Inherited.html) :

> Note that this meta-annotation type has no effect if the annotated type is used to annotate anything other than a class.

So it would not apply to `@DynamoDbIgnore`.
