### ISSUE TITLE
nextMarker() returns null on ListObjectsResponse - even though isTruncated() indicates otherwise

### ISSUE THREAD

**Issue by peter-ponzel** [aws/aws-sdk-java-v2#2350]
## Describe the bug
when trying to fetch objects using `ListObjectsRequest` from a bucket that contains more than 1000 objects the method `nextMarker()` from `ListObjectsResponse` returns `null` although it indicates that more objects should be available because `isTruncated()` returns `true`.

## Expected Behavior
`nextMarker()` should return a proper next marker that can be used with `ListObjectsRequest` in order to get the next results.

## Current Behavior
`nextMarker()` returns `null`

## Steps to Reproduce
simplified code snipped to demonstrate
```
final ListObjectsRequest request = ListObjectsRequest.builder()
            .bucket("any-bucket-with-containing-more-than-1000-objects")
            .prefix("")
            .marker(null)
            .build();

final ListObjectsResponse response = client.listObjects(request);
response.isTruncated(); // true
response.nextMarker(); // null
``` 

## Possible Solution
`nextMarker()` should return a proper next marker

## Context
I don't know if this of any importance but we have versioning enabled in our bucket.
In this use case -however- we don't want to use `ListObjectVersionsRequest` because we're not interested in any versions.

## Your Environment

* AWS Java SDK version used: `2.16.29`
* JDK version used: `11.0.10 2021-01-19`
* Operating System and version: `Ubuntu 20.04.2 LTS`

**Comment by debora-ito** [comment]
Hi @peter-ponzel here's what the [ListObjects](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjects.html) API Reference says about nextMarker:

NextMarker
When response is truncated (the IsTruncated element value in the response is true), you can use the key name in this field as marker in the subsequent request to get next set of objects. Amazon S3 lists objects in alphabetical order. 
**Note: This element is returned only if you have delimiter request parameter specified. If response does not include the NextMarker and it is truncated, you can use the value of the last Key in the response as the marker in the subsequent request to get the next set of object keys.**

Your code sample does not have a delimiter field set in the request, so this is expected.
Let us know if you have any further questions.

**Comment by peter-ponzel** [comment]
Hello @debora-ito,

thanks for pointing that out, I'll try that out.

But why does it behave differently to `ListObjectVersionsRequest` ? Because this works as described above

```
final ListObjectVersionsRequest request = ListObjectVersionsRequest.builder()
            .bucket("any-bucket-with-containing-more-than-1000-objects")
            .prefix("")
            .keyMarker(null)
            .versionIdMarker(null)
            .build();

final ListObjectsResponse response = client.listObjects(request);
response.isTruncated(); // true
response.nextKeyMarker(); // contains key
response.nextVersionIdMarker(); // contains versionId
```

Best regards,
Peter

**Comment by debora-ito** [comment]
I don't know why they have different behaviors, but it's a good practice to consult the documentation in case you experience issues like this.
