### ISSUE TITLE
Documentation lacks information on thread safety

### ISSUE THREAD

**Issue by xCASx** [aws/aws-sdk-java-v2#2351]
SDK v1 had a [similar issue](https://github.com/aws/aws-sdk-java/issues/632) which was resolved, e.g. AmazonS3Client [had a @ThreadSafe annotation](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-s3/src/main/java/com/amazonaws/services/s3/AmazonS3Client.java#L420).

In SDK v2 the clients aren't marked with this annotation. I also wasn't able to find any information about thread safety in the documentation.

Would be nice to have this information easily accessible.

**Comment by debora-ito** [comment]
Hi @xCASx thank you for reaching out. Yes, using `@ThreadSafe` would make the documentation more clear, we'll add the annotation to the client classes.

To answer your question, all SDK clients are thread safe.

**Comment by xCASx** [comment]
Thank you @debora-ito

**Comment by debora-ito** [comment]
@xCASx the documentation now shows `@ThreadSafe` in the service clients, added via https://github.com/aws/aws-sdk-java-v2/pull/2443.
