### ISSUE TITLE
Document correct behavior for AttributeConverterProvider

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#2353]
I am attempting to write a custom `AttributeConverterProvider` for handling a specific type, and I intend to use it in conjunction with `DefaultAttributeConverterProvider` as described in the documentation. However, the Javadoc for `AttributeConverterProvider#converterFor(EnhancedType)` does not specify the correct behavior when my custom converter is asked about an unknown type (i.e., a built-in). The only example is the default implementation, which throws on an unknown type, and this does not seem like the correct behavior. Should I simply return null? (`ChainConverterProvider` suggests this.) 

The Javadoc needs to cover the case for "not found".

**Comment by debora-ito** [comment]
`DefaultStringConverterProvider` seems to throw IllegalArgumentException.

https://github.com/aws/aws-sdk-java-v2/blob/71dfc2c7a93da29c0045a1ab23ce420b1f2aaae7/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/string/DefaultStringConverterProvider.java#L150-L156

Would this be reasonable in your case?

**Comment by chrylis** [comment]
The default converter does throw, but the `ChainConverterProvider` seems to expect that it will return null, and that the exception is merely the questionably-handled undocumented last-resort provider.
