### ISSUE TITLE
LEAK: ByteBuf.release() was not called before it's garbage-collected. See https://netty.io/wiki/reference-counted-objects.html for more information.

### ISSUE THREAD

**Issue by JonathanBond** [aws/aws-sdk-java-v2#2359]
## Describe the bug
Occasionally we see this exception when using the AWS SDK v2.  While not a big problem, we think it should be fixed.

## Expected Behavior
Not to leak native byte buffers

## Current Behavior
Warning that a native byte buffer is being released.

## Steps to Reproduce
It's not a directly reproducible bug.

## Possible Solution
In Http2GoAwayEventListener

It appears the debugdata is being retained and not released.

 Http2MultiplexedChannelPool channelPool = parentChannel.attr(ChannelAttributeKey.HTTP2_MULTIPLEXED_CHANNEL_POOL).get();
        GoAwayException exception = new GoAwayException(errorCode, debugData.retain());

I think that a retain here is not necessary.

## Context
Nothing direct, but error message - and the fact it's causing a memory leak.
On line 73 in [leak.txt](https://github.com/aws/aws-sdk-java-v2/files/6232493/leak.txt) it shows a reference being retained, and I can't find a subsequent release of it.

## Your Environment
AWS SDK V2.13.56

**Comment by zoewangg** [comment]
Fixed via #2366 

The fix has been released as part of `2.16.37`
