### ISSUE TITLE
Add list of Java Types that have automatic conversions

### ISSUE THREAD

**Issue by RushinNaik** [aws/aws-sdk-java-v2#2361]
## Describe the issue

It would be helpful to add the list of Java types that have default DDB converters available. The documentation says "many common Java types" instead of mentioning a specific list. 

## Links

https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#control-attribute-conversion

**Comment by debora-ito** [comment]
You can see the list in the AttributeConverter javadoc: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/AttributeConverter.html

Will add the list to the overview.

**Comment by RushinNaik** [comment]
Thanks for sharing the link. I can get some guidance from it.
