### ISSUE TITLE
How to configure Save Behavior for DDB Enhanced client 

### ISSUE THREAD

**Issue by RushinNaik** [aws/aws-sdk-java-v2#2362]
## Describe the issue

I need to understand how can we enforce the following SDK v1 DynamoDbMapperConfig settings while implementing SDK v2 Enhanced DDB client.

DynamoDBMapperConfig.TableNameOverride(tableName)
DynamoDBMapperConfig.SaveBehavior.UPDATE_SKIP_NULL_ATTRIBUTES
DynamoDBMapperConfig.SaveBehavior.UPDATE
DynamoDBMapperConfig.ConsistentReads.CONSISTENT

## Steps to Reproduce

- Implement SDK v2 version for Initializing the DynamoDBMapper using above configs or use these configs for a SDK v2 query

## Current Behavior

Not able to use SDK V2 client with above mentioned settings.

## Your Environment

* AWS Java SDK version used: 2
* JDK version used: 11
* Operating System and version: macOS 10.15.7

**Comment by debora-ito** [comment]
`UpdateItemEnhancedRequest` has a `ignoreNulls` flag - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedRequest.html#ignoreNulls--

It's also possible to customize the behavior for specific attributes using `@DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)`. For examples see: https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#changing-update-behavior-of-attributes

Let us know if this helps.

**Comment by RushinNaik** [comment]
It is feasible to use `ignoreNulls` in the `UpdateItemEnhancedRequest`. But, for  `@DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)`, is there a way to implement it for all the operations that enhanced client does ? Similar to how its available in DDBMapper: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/DynamoDBMapperConfig.SaveBehavior.html

**Comment by debora-ito** [comment]
I believe that was the intention when `UpdateBehavior.WRITE_IF_NOT_EXISTS` was added. Differently from V1's SaveBehavior, when using the DDB EnhancedClient you can specify which attributes you want to have this behavior.

We can change this to a feature request if you'd like to see this configuration in the client level for all attributes.

**Comment by vivek-rao-1985** [comment]
@debora-ito I'm not sure if the intention of the op is to configure ```DynamoDBMapperConfig``` to ignore null values when writing to dynamo db, but if that's the case ```WRITE_IF_NOT_EXISTS``` is not the correct solution. As per the docs -
```
Write the new value if there is no existing value in the persisted record or a new record is being written, otherwise leave the existing value.
```
So if we had a POJO like -
```
class MyObj {
    @Getter
    @Setter
    private String a;
    @Getter
    @Setter
    private String b;
}
```
And let's say 'a' has some value set and 'b' is set to null, on the first write to dynamo using the enhanced client both 'a' and 'b' will be written and 'b' will be set to null since it's a new record. What the op wants to accomplish is to only write 'a' and skip 'b' since it's null regardless of whether the object exists or not in dynamo.
