### ISSUE TITLE
DynamoDB or S3 write performance degraded when moving from 2.15.10 to 2.15.11

### ISSUE THREAD

**Issue by nikitsenka** [aws/aws-sdk-java-v2#2365]
During update we found that our integration tests time increased from 3 min to 8 min
We are using AWS SDK for writing  data into DynamoDB and S3

## Expected Behavior
Performance to be the same

## Steps to Reproduce
Run the same code using 2.15.10 and 2.15.11 and compare performance

## Context
We can't update to version greater then 2.15.10 because the issue exist in all version up to 2.16.32

## Your Environment
* AWS Java SDK version used:2 .15.11
* JDK version used: openjdk version "14.0.2" 2020-07-14
* Operating System and version: MacOs/Linux

**Comment by debora-ito** [comment]
Hi @nikitsenka thank you for reaching out.

How are you perceiving the performance degradation? Can you provide a sample code we can use to reproduce?

Also, can you enable the client-side metrics and compare before/after changing the version? The metrics can provide more insight on where the change in performance is happening. For more info on client-side metrics see:
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html
- https://aws.amazon.com/blogs/developer/using-the-new-client-side-metrics-feature-in-the-aws-sdk-for-java-v2/

**Comment by nikitsenka** [comment]
the issue was gone when LoggingPublisher was applied https://aws.amazon.com/blogs/developer/using-the-new-client-side-metrics-feature-in-the-aws-sdk-for-java-v2/
The reason of the issue is unknown, but due to unreproducible anymore we can close the ticket
Will keep on eye on it
