### ISSUE TITLE
OnExecutionFailure is not called when ApiCallTimeout occurs

### ISSUE THREAD

**Issue by ndejaco2** [aws/aws-sdk-java-v2#2367]
## Describe the bug
I am attempting to use a custom execution interceptor to track concurrent executions on an async client. However, when the client call times out the onExecutionFailure callback is not made so the count of executions does not get decremented correctly. 

## Expected Behavior
When a call fails with api call timeout it should execute the onExecutionFailed callback in the interceptor. 

## Current Behavior
Currently, the callback is not executed. 

## Steps to Reproduce
Create a lambda function that will sleep for 5 seconds. Set api call timeout and apiCallAttemptTimeout to 1 second. Make a request with the client to invoke the function which should timeout. Verify that the callback is not executed. 

## Context
I am attempting to use a custom execution interceptor to track concurrent executions on an async client. 

## Your Environment

* AWS Java SDK version used: latest
* JDK version used: 11
* Operating System and version: al2

**Comment by debora-ito** [comment]
Hi @ndejaco2 I believe this is duplicate of https://github.com/aws/aws-sdk-java-v2/issues/806. Let's keep track in that other issue, and please upvote the original description to show you are impacted by this. Apologies for taking this long to reply.
