### ISSUE TITLE
Add `content()` to `s3Client.getObject(getObjectRequest).response()` and return `S3Object`

### ISSUE THREAD

**Issue by eddumelendez** [aws/aws-sdk-java-v2#2371]
Currently, I am working on spring cloud aws integration with s3, moving the existing implementation from sdk v1 to v2 and I would like to perform some operations in a friendly way. In this case, if the user is working with objects use `S3Object` instead of `*Response` classes. 

The sdk allow me to do this in order to get a list of s3 objects `this.s3Client.listObjects(listObjectsRequest).contents()` which returns `List<S3Object>`. However, when try `this.s3Client.getObject(getObjectRequest).response()` there is no method that returns `S3Object`, instead it provides a `metadata()` method.
## Proposed Solution

In order to have consistency between operations would be great that `this.s3Client.getObject(getObjectRequest)` provides `content()` which returns `S3Object`
## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: 2.16.1
* JDK version used: 11
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @eddumelendez, the SDK v2 clients are generated based on [service models](https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/resources/codegen-resources/service-2.json#L500), this change would need to come from S3. In v1 the S3 client was hand-written so we didn't have this restriction.

It would be good to see consistency between operations, but I don't think this is something S3 can change now unfortunately. I'll go ahead and close this. Thank you for reaching out.
