### ISSUE TITLE
Improve and add new operation `S3Client`

### ISSUE THREAD

**Issue by eddumelendez** [aws/aws-sdk-java-v2#2372]
Currently, I am working on spring cloud aws integration with s3, moving the existing implementation from sdk v1 to v2 and I would like to perform some operations in a friendly way. In this case, if the user is working with buckets use `S3Bucket` and if it is using objects then use `S3Object` instead of `*Response` classes. 
## Proposed Solution

Currently, there is a model class `S3Object`, would be great to have a similar one for `S3Bucket` which contains information about the bucket and can be use it when performing `this.s3Client.createBucket(CreateBucketRequest.builder().build())`. Also, add a new method `this.s3Client.getBucket(GetBucketRequest);` which also return `S3Bucket`.
## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used: 2.16.1
* JDK version used: 11
* Operating System and version:

**Comment by debora-ito** [comment]
@eddumelendez Same case of #2371, this change would need to be made upstream in the S3 service model. Changing the current `createBucket` operation would be a breaking change though, a new operation would need to be created. And `headBucket` is the operation equivalent to `getBucket` but it does not return a S3Bucket.

I'll close this for now, feel free to reach out with more discussions about the Spring integration.
