### ISSUE TITLE
AsyncS3Client cannot getLocation of buckets not in us-east-1 when the client is in us-east-1

### ISSUE THREAD

**Issue by markjschreiber** [aws/aws-sdk-java-v2#2381]
## Describe the bug
Calling `getBucketLocation(request)` using a client in us-east-1 will fail for any bucket not in us-east-1. Changing the client location to another region such as `us-west-2` will allow it to work for any bucket. 

## Expected Behavior
I think `getLocation(request)` should work from any region otherwise code is less portable and the method has little value.

## Current Behavior
The following error occurs with a client in us-east-1 and a bucket in another region. This suggests an issue with signing the request?

```
The authorization header is malformed; the region 'us-east-1' is wrong; expecting 'us-west-2' (Service: S3, Status Code: 400, Request ID: ****, Extended Request ID: ****)
```

## Steps to Reproduce
```
package org.example.asyncS3expt;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import software.amazon.awssdk.auth.credentials.AwsSessionCredentials;
import software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider;
import software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain;
import software.amazon.awssdk.services.s3.S3AsyncClient;
import software.amazon.awssdk.services.s3.model.ListBucketsResponse;

import java.util.Collection;

public class App {
	@SuppressWarnings("unused")
	private static final Logger LOGGER = LoggerFactory.getLogger(App.class);

	public static void main(String[] args) throws Exception {
		new App().proceed();
	}

	public void proceed() throws Exception{
		LOGGER.info("Listing Buckets and regions");

		final var defaultCredentialsProvider = DefaultCredentialsProvider.create();
		final var regionProviderChain = DefaultAwsRegionProviderChain.builder().build();

		// uncomment different regions to observe the error
		final var client = S3AsyncClient.builder()
			.credentialsProvider(defaultCredentialsProvider)
			//.region(Region.US_WEST_2)
			//.region(Region.US_EAST_1)
			//.region(Region.EU_WEST_1)
			.region(regionProviderChain.getRegion())	
			.build();

		client.listBuckets()
				.thenApply(ListBucketsResponse::buckets)
				.thenApply(Collection::parallelStream)
				.join()
				.map(bucket -> client.getBucketLocation(builder -> builder.bucket(bucket.name()))
						.handleAsync((r, e) -> r != null ? bucket.name()+": "
								  +(r.locationConstraintAsString().equals("") ? "us-east-1" : r.locationConstraintAsString())
								: bucket.name()+": "+e.getCause().getMessage())
						.join())
				.forEach(LOGGER::info);
	}


}
```
## Possible Solution
A fix may be required in signing these calls?

## Context
Building a simple async Java app to list all buckets and regions

## Your Environment

* AWS Java SDK version used: 2.16.34
* JDK version used: 

```
java --version
openjdk 11.0.8 2020-07-14 LTS
OpenJDK Runtime Environment Corretto-11.0.8.10.1 (build 11.0.8+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.8.10.1 (build 11.0.8+10-LTS, mixed mode)
```

* Operating System and version:
Mac OSX 10.15.7

**Comment by debora-ito** [comment]
Hi @markjschreiber thank you for the report. S3 has a weird behavior around its regions because `us-east-1` is the legacy global endpoint. You can read more about legacy endpoints in the dev guide: https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html#VirtualHostingBackwardsCompatibility

That said, the docs don't mention that it should be a problem hitting the `us-east-1` endpoint with a bucket in `us-west-2`.

Can you provide the [verbose wire logs ](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose)of the call? I'd like to see which endpoint and path style is being used. Please make sure to redact any sensitive information the logs might contain.

**Comment by markjschreiber** [comment]
After some more digging it seems to be only one specific bucket. I can
create test buckets in us-west-2 and successfully get their regions.

The only difference that I can see between the two us-west-2 buckets is the
AWS-KMS key (SSE-KMS). It may be more of a KMS issue than S3?

**Comment by debora-ito** [comment]
I believe you would see a different error if it was a KMS issue, but I'm not sure.
