### ISSUE TITLE
Replace Jackson Afterburner with Blackbird

### ISSUE THREAD

**Issue by dsvensson** [aws/aws-sdk-java-v2#2383]
The use of Afterburner was introduced with #1202 and this only works on Java 8 and older JVMs, 8 major versions behind current JVM. As this project already uses Jackson 2.12, consider relying on Blackbird instead.

https://github.com/FasterXML/jackson-modules-base/tree/master/blackbird

**Comment by debora-ito** [comment]
Hi @dsvensson the SDK does not use Afterburner, I double checked with `mvn dependency:tree`. Are you seeing otherwise?

**Comment by dsvensson** [comment]
You are absolutely right, been reading myself blind from dependencies output in all directions, sorry for the noise :D
