### ISSUE TITLE
CloudWatch client doesn't always format the timestamps correctly

### ISSUE THREAD

**Issue by brharrington** [aws/aws-sdk-java-v2#2389]
## Describe the bug

When performing a `GetMetricStatisticsRequest` some values of `Instant` used for the start and end times will result in an error:

```
timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: ..., Extended Request ID: null)
```

## Expected Behavior

I would expect it to convert any value of `java.time.Instant` into a string that could be understood by the CloudWatch service.

## Current Behavior

It fails with an error:

```
timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: ..., Extended Request ID: null)
```

## Steps to Reproduce

This appears to be due to sub-second data on the timestamp sometimes when using `Instant.now()`. Sample code to reproduce:

```scala
    val client = CloudWatchClient.builder()
      .region(Region.US_EAST_1)
      .build()

    // Using an explicit time to force the behavior, on some systems Instant.now() is enough to usually
    // reproduce
    val e = Instant.parse("2021-04-07T19:45:55.126591836Z")
    // A workaround it to explicitly truncate the times: .truncatedTo(ChronoUnit.SECONDS)
    val s = e.minus(Duration.ofMinutes(5))
    val request = GetMetricStatisticsRequest.builder()
      .startTime(s)
      .endTime(e)
      .period(60)
      .statistics(Statistic.SUM)
      .namespace("AWS/EC2")
      .dimensions(Dimension.builder()
        .name("AutoScalingGroupName")
        .value("test-v000")
        .build())
      .metricName("CPUUtilization")
      .build()
    println(request)

    val response = client.getMetricStatistics(request)
    response.datapoints()
      .asScala
      .toList
      .sortWith(_.timestamp() isBefore _.timestamp())
      .foreach(println)
```

## Possible Solution

A work-around is to explicitly truncate the value before passing to the request object, e.g.:

```
val e = Instant.now().truncatedTo(ChronoUnit.SECONDS)
```

## Your Environment

* AWS Java SDK version used: 2.16.10
* JDK version used: 11.0.10-zulu
* Operating System and version: Linux, 18.04.1-Ubuntu

**Comment by debora-ito** [comment]
Hi @brharrington thank you for the detailed issue. This was previously reported in https://github.com/aws/aws-sdk-java-v2/issues/1820, let's keep track of the issue over there.

I'll ping the service team again to see if there's an update.
