### ISSUE TITLE
ResourceNotFoundException for DynamoDbItemTable.query(queryEnhancedRequest) 

### ISSUE THREAD

**Issue by RushinNaik** [aws/aws-sdk-java-v2#2415]
## Describe the issue

I am working on fetching items using paginated queries. For this, I have implemented the query request which uses exclusive start key to fetch the remaining result. When all the results are fetched and there are no items left in DB after the exclusive start key, I was expecting that the request would return an empty result instead of exception.

## Steps to Reproduce
1. Save two items in a table
2. Now fetch both at once by using DynamoDbItemTable.query(queryEnhancedRequest) 
3. Use the lastPage.lastEvaluatedKey() from the result as exclusive start key for the next DynamoDbItemTable.query(queryEnhancedRequest) operation. 

## Current Behavior
Step 3 throws ResourceNotFoundException. Should it be returning an empty list like result instead of throwing exception as there are no further items left to be fetched? 

## Your Environment

* AWS Java SDK version used: 2
* JDK version used: 11
* Operating System and version: macOS 10.15.7

**Comment by debora-ito** [comment]
@RushinNaik can you provide a reproducible code sample?

**Comment by RushinNaik** [comment]
1. Insert
enhancedDDbClient.transactWriteItems(transactWriteItemsEnhancedRequest); // For item 1
enhancedDDbClient.transactWriteItems(transactWriteItemsEnhancedRequest2); // For item 2

2. Fetch both at once
DynamoDbTable.query(queryEnhancedRequest); // Save last evaluated key (would be Item 2) . Call it LE1

3. Fetch results again by setting LE1 as exclusive start key for queryEnhancedRequest2.
DynamoDbTable.query(queryEnhancedRequest2); // Its returning ResourceNotFound.

**Comment by debora-ito** [comment]
@RushinNaik I'm sorry for taking this long to reply with a question :)

Any particular reason why you are manually paginating through the results? Query returns a PageIterable, and the SDK can automatically make the additional service calls to retrieve the next page of results, it will automatically bring all results:

```
1) Iterating through pages

 
 PageIterable<MyItem> results = table.query();
 results.stream().forEach(p -> p.items().forEach(item -> System.out.println(item)))
 
 
2) Iterating through items
 
 PageIterable<MyItem> results = table.query();
 results.items().stream().forEach(item -> System.out.println(item));
```


If you want us to further investigate the `ResourceNotFoundException` please send us a code snippet showing how you are retrieving the results and getting the next page. Turning on the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) also may help in the investigation, we can get additional insights on what is being sent in the wire. Make sure to redact any sensitive information the wire logs might contain.

**Comment by debora-ito** [comment]
Great. So we'll wait for your code sample and wire logs to investigate it further.
