### ISSUE TITLE
Create a Lambda Events lib like the one provided in v1 of the sdk

### ISSUE THREAD

**Issue by bowersj27** [aws/aws-sdk-java-v2#2422]
v1 sdk had aws-lambda-java-events lib to support implementing lambdas with models defined for the lambda runtime and predefined aws events. It'd be nice to have this in v2 of the sdk as well.

## Describe the Feature

A lambda runtime sdk for lambda functions. Migrate v1 -> v2. 

## Is your Feature Request related to a problem?

I don't like having dependencies on both awssdk v1 AND v2 for implementing lambda functions that are compatible with the lambda runtime for predefined aws specific events. 

## Additional Context

It'd be nice if from v1 -> v2 of the sdk, I don't lose support/confidence implementing lambdas triggered by AWS events

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
Hi @bowersj27.

The `aws-lambda-java-events` lib is owned not by the Java SDK team but by the Lambda team, and it lives in a different repo: https://github.com/aws/aws-lambda-java-libs. 

And according to its [README](https://github.com/aws/aws-lambda-java-libs/blob/master/aws-lambda-java-events/README.md), the latest version is not bundled with SDK v1 anymore (see this [comment](https://github.com/aws/aws-lambda-java-libs/issues/74)):

> As of version 3.0.0, users are no longer required to pull in SDK dependencies in order to use this library.

I'll go ahead and close this. Feel free to reach out if you have any other question related to the SDK.
