### ISSUE TITLE
Out of Memory Error with com.amazonaws.http.IdleConnectionRepear

### ISSUE THREAD

**Issue by murali-krishnamoorthy** [aws/aws-sdk-java-v2#2427]
We are getting an Java OutOfMemory Error in our spring boot application and on analyzing the heap dump we see issues with the "com.amazonaws.http.IdleConnectionRepear". We have this AWS Dependency for connecting to secret manager during bootstrap.

## Describe the issue
We are getting an Java OutOfMemory Error in our spring boot application and on analyzing the heap dump we see issues with the "com.amazonaws.http.IdleConnectionRepear". We have this AWS Dependency for connecting to secret manager during bootstrap.

## Steps to Reproduce
Attached Heap Dump Image

## Your Environment

Spring Boot Version :  '2.3.4.RELEASE'

AWS Dependencies 
compile "org.springframework.cloud:spring-cloud-aws-autoconfigure:2.1.0.RELEASE"
compile "org.springframework.cloud:spring-cloud-starter-aws-secrets-manager-config:2.1.0.RELEASE"
implementation 'com.amazonaws:aws-java-sdk-core'
implementation 'com.amazonaws:aws-java-sdk-secretsmanager'

I am not able to attach the heap dump because of size limitation , but i have attached the image.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/56832545/115394456-6a2d8580-a200-11eb-94d5-f871befcb7f8.png)

**Comment by debora-ito** [comment]
How are you using the Secrets Manager client, are you creating a new client for every request or is it shared?
We recommend sharing the client when possible. For more best practices check: https://github.com/aws/aws-sdk-java-v2/blob/master/docs/BestPractices.md

**Comment by murali-krishnamoorthy** [comment]
Its bootstrapped , so we gets all properties from Secret Manager once on startup . Have other experienced similar issue.

**Comment by murali-krishnamoorthy** [comment]
here is heap dump , https://heaphero.io/my-heap-report.jsp?p=YXJjaGl2ZWQvMjAyMS8wNC8yMS8tLXRmYW0tdXNlci1wcm9maWxlLXJlYWQtNTU2Zjk4NzRmNy1zajc0ZC10ZmFtLXByb2ZpbGUuaHByb2YuZ3otNy01LTQ4Lmpzb24=

**Comment by debora-ito** [comment]
@murali-krishnamoorthy I cannot access the link, my browser says there's a potential security risk with heaphero.io. How big is the dump file, can you provide it in another way?

**Comment by murali-krishnamoorthy** [comment]
[ft-report-api-hh-cxn7a95795a-bbb5-452b-b32f-ec753e89f578.pdf](https://github.com/aws/aws-sdk-java-v2/files/6355770/ft-report-api-hh-cxn7a95795a-bbb5-452b-b32f-ec753e89f578.pdf)
[heapReport-2021-04-22-11-13.pdf](https://github.com/aws/aws-sdk-java-v2/files/6355771/heapReport-2021-04-22-11-13.pdf)

I have attached the pdf heap and thread dump report , as dump is 30 MB after compression

**Comment by debora-ito** [comment]
@murali-krishnamoorthy 
- Can you share a sample code showing how you are creating the client?
- Are you creating a new client for every call or is it reused among the requests?

**Comment by murali-krishnamoorthy** [comment]
The client is being bootstrapped and there is no explicit code to create client , other than providing the required configuration in bootstrap.yaml

The properties are fetched once when the application starts up

This blog explain bootstrap process for spring secret manger.
https://stackoverflow.com/questions/56194579/how-to-integrate-aws-secret-manager-with-spring-boot-application

**Comment by debora-ito** [comment]
@murali-krishnamoorthy thank you for the link. After the SecretsManager client is bootstrapped, we don't have visibility on how the client is being used by Spring Cloud so I can't offer a lot of recommendations. Try reaching out to Spring Cloud support.

`IdleConnectionReaper` is a thread responsible for closing idle HTTP connections periodically in the background. We have seen previous reports showing IdleConnectionReaper as a leak suspect but they were all caused by other factors, like the client not being properly closed, or something else in the application code that bypasses the connection cleanup process.
