### ISSUE TITLE
getCurrentRegion is not supported

### ISSUE THREAD

**Issue by DiaGitHub** [aws/aws-sdk-java-v2#2428]
## Describe the issue

Hello,
I'm migrating a project to sdk v2 and I'm encountering a problem with `getCurrentRegion` method. It is no longer supported in this version.
So, I'm looking for another way to bypass this problem. 

Is `EC2MetadataUtils.getEC2InstanceRegion();` correct to retrieve the current region?

Thank you

## Environment

* AWS Java SDK version used: v2
* JDK version used: 11
* Operating System and version: MacOs

**Comment by debora-ito** [comment]
@DiaGitHub [`EC2MetadataUtils.getEC2InstanceRegion()`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.html#getEC2InstanceRegion--) gets the region in which the instance is running, from EC2 Instance Metadata. If that's your use case, then yes.

**Comment by DiaGitHub** [comment]
thank you @debora-ito
