### ISSUE TITLE
Java Dynamodb enhanced client - putItem - creating duplicate records with auto increment Sort Key (SK) value

### ISSUE THREAD

**Issue by Kamatam** [aws/aws-sdk-java-v2#2441]
## Describe the issue
I am using DynamoDbEnhancedClient:putItem to insert simple item into the table with Partition key(String) and sort Key (Number). But observed duplicate record is created with auto incremented on actual item's sort key provided as part of putItem call. Here I am using Instant.now().getEpochSecond() for sort key. Please find the following code snippet.

// build object/item

TestTable  item = new TestTable() 
          item.setSessionId()  // Session id is unique and it is  Partition key
          item.setMessageId(Instant.now().getEpochSecond()) //  Sorted key 
           item.message(request.getMessage())

Putitem call
--------------
DynamoDbTable<TestTable> table = dbdClient.table("test_table",
                    TableSchema.fromBean(TestTable.class));
            table.putItem(item);

After this call, I found two entries/items with same partition key and different sk values ,  item with sk 1619427621 (actual item), second item with sk 1619427622  (this item is not provided as part of putItem call but observed its auto incremented on actual item sorted key value).

Bean
----
@DynamoDbBean
public class TestTable {
    private String sessionId;
    private long messageId;
    private String message;

   @DynamoDbPartitionKey
    @DynamoDbAttribute("session_id")
    public String getSessionId() {
        return sessionId;
    }
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    @DynamoDbSortKey
    @DynamoDbAttribute("message_id")
    public long getMessageId() {
        return messageId;
    }
    public void setMessageId(long messageId) {
        this.messageId = messageId;
    }
    // Attributes
    @DynamoDbAttribute("message")
    public String getMessage() {
        return message;
    }
    public void setMessage(String message) {
        this.message = message;
    }
}

## Your Environment

* AWS Java SDK version used: 2.16.44
* JDK version used:  From EC2 instance
     openjdk version "11.0.9" 2020-10-20
    OpenJDK Runtime Environment (build 11.0.9+11-alpine-r1)
    OpenJDK 64-Bit Server VM (build 11.0.9+11-alpine-r1, mixed mode)
* Operating System and version: AWS EC2

Please let correct me if I missed anything.

Thank you.

**Comment by debora-ito** [comment]
@Kamatam one `putItem` call does not add two items to the table. Check if you don't have any running process that might be calling a second `putItem` or  incrementing the sort key (maybe via ADD updateExpression?).

**Comment by Kamatam** [comment]
Thank you for your comments. There is no other process running. And this issue is not consistent or frequent as well.

**Comment by debora-ito** [comment]
@Kamatam The issue being intermittent indicates it's not a problem with DynamoDBEnhancedClient#putItem, or else the duplication would occur with every call.

If you turn on the [verbose wire logs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) you can check the HTTP request and response data for one call of `putItem`. If you choose to provide us the wire logs, please make sure to redact any sensitive information it may contain.
