### ISSUE TITLE
getItems() to support Global Secondary Index without full table projection

### ISSUE THREAD

**Issue by brianzhangassembled** [aws/aws-sdk-java-v2#2446]
For larger tables that have several GSI specified, we have a pretty common usage pattern of : 

1. Run query against GSI to get results in form of bare-bone item object, since GSI projections are "key-only"
2. Fire .getItem(item) for each individual item
3. return the combined results

Previously the batchGet() api from V1 supported this usage pattern well. 
Would love to see something similar, or even better, some function that does this, like a ".fluff()"? 

## Additional Context

- [ ] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by debora-ito** [comment]
@brianzhangassembled DynamoDBEnhancedClient batchGetItem does not work in your case?

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.html
