### ISSUE TITLE
[New Feature]Expose aws_mqtt_client_connection_set_reconnect_timeout in Java SDK

### ISSUE THREAD

**Issue by guoziy** [aws/aws-sdk-java-v2#2454]
__
## Expected Behavior
Clients are able to call AwsIotMqttConnectionBuilder.newDefaultBuilder().withReconnectTimeout(min, max) to set reconnection minimum and maximum timeout. 

## Current Behavior
Currently, while attempting reconnect, MqttClientConnection starts at 1 second by default and multiply the time between next attemption by 2 until maximum reconnection timout(128 second by default).  For SDK in c++, clients are able to call aws_mqtt_client_connection_set_reconnect_timeout to customize the min an max reconnection timout. However, this functioanlity is not available to SDK for Java users.

## Possible Solution
Expose aws_mqtt_client_connection_set_reconnect_timeout in SDK Java.

## Context
For some productive use cases, the default maximum timout 128s are too long for next reconnection attempts. By exposing  aws_mqtt_client_connection_set_reconnect_timeout in Java SDK, users are able to assign the min and max reconnection timeout based on their use cases.

## Your Environment

* AWS Java SDK version used:  SDK v2
* JDK version used: openjdk 11.0.10
* Operating System and version:  macOS Majave 10.14.6

**Comment by debora-ito** [comment]
Hi @guoziy it looks like you are using the `aws-iot-device-sdk` for Java library. If that's the case, please open a new issue in https://github.com/aws/aws-iot-device-sdk-java-v2

**Comment by guoziy** [comment]
Thank you @debora-ito for the response.

Created a new issue: https://github.com/aws/aws-iot-device-sdk-java-v2/issues/160
