### ISSUE TITLE
Remove Jackson-databind requirement, make databinding pluggable

### ISSUE THREAD

**Issue by MikeDombo** [aws/aws-sdk-java-v2#2466]
## Describe the Feature

Jackson databind is required by SDK-core package. Jackson databind adds ~10MB to the runtime memory requirement and should be replaceable by jackson-jr or other smaller databinding packages such as gson. I believe that only the JacksonUtils class would need to be changed https://github.com/aws/aws-sdk-java-v2/blob/584ccb59e770177aeaa4c3b6bda4e24015b8ece9/core/sdk-core/src/main/java/software/amazon/awssdk/core/util/json/JacksonUtils.java#L32, as long as the API was changed so that `JsonNode` type isn't needed. The parent class `TreeNode` should be fine as a replacement.

## Is your Feature Request related to a problem?
The AWS SDK adds a large amount of additional memory requirement which is a large requirement for IoT use cases.

## Proposed Solution
Just like how the SDK HTTP clients are pluggable, jackson-databind should not be a hard requirement. Even better, Jackson-core shouldn't be required and instead there should be APIs for generic serialization and deserialization.

## Additional Context

- [x] I may be able to implement this feature request

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by MikeDombo** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/66#issuecomment-315453360
Looks like this was talked about 4 years ago. Looking through the code usages of databind seems like hardly anything actually uses it. So it should be fairly trivial to drop it completely.

**Comment by debora-ito** [comment]
Hi @MikeDombo, I'm sorry for the delayed reply.

We discussed this as a team, and in fact we have plans to remove all the jackson dependencies from the Java SDK v2. The discussion was about if we should incorporate the changes you're proposing since we are going to remove it altogether later on, and we decided not to merge the PR. 

We appreciate your work and thank you for submitting it.

**Comment by MikeDombo** [comment]
Thank you, that's really great to hear. Is there any timeline for that change?

**Comment by debora-ito** [comment]
No timeline for it yet.

**Comment by millems** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/2522

**Comment by millems** [comment]
We've removed Jackson as a user-visible SDK dependency in 2.17.0. 

JSON unmarshalling isn't pluggable, but I'm not sure we have a reason for SDK users to change the way JSON marshalling/unmarshalling works. Is it worth keeping this feature request around, or is the primary reason for this feature resolved?

**Comment by MikeDombo** [comment]
#2522 was closed, is there a different PR which removes Jackson?

Really the request is to remove jackson-databind as a runtime dependency. Has that been accomplished?

**Comment by millems** [comment]
Jackson-databind is no longer a runtime dependency of the SDK. Jackson-core and Jackson-dataformat-cbor are still runtime dependencies, but they are shaded in the SDK, so they are not visible to the customer. https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-2-17-removes-its-external-dependency-on-jackson/

This was the PR that removed Jackson: https://github.com/aws/aws-sdk-java-v2/pull/2598

**Comment by MikeDombo** [comment]
OK, sounds good. Not ideal that they are shaded honestly because my project also needs core and size is a huge concern for us, so de-duplicating that would be good.

Thank you for removing databind though, that will help out a ton.

**Comment by millems** [comment]
Yeah, shading is not optimal, but our primary reason for the change was to allow us to upgrade Jackson without breaking customers, which requires shading. Removing Jackson-databind was just something we did in the process to decrease the binary size impact of shading.
