### ISSUE TITLE
getJourney(): SdkClientException: Unable to unmarshall response

### ISSUE THREAD

**Issue by johnmilimo** [aws/aws-sdk-java-v2#2477]
## Describe the bug

When I use the AWS Pinpoint JAVA SDK to fetch an existing journey, the SDK fails as it is unable to parse the timestamp ( End Date ) that is set on the journey

<img width="828" alt="end-date-journey" src="https://user-images.githubusercontent.com/2853404/117922186-c44ed180-b2fa-11eb-9bfb-9da6a1c652e9.png">

ERROR:
```
software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text '2022-10-25T06:09:55+00:00' could not be parsed at index 19). Response Code: 200, Response Text: OK
```

## Expected Behavior

The `getJourney()` request should return the journey response without failing

## Current Behavior

The SDK is unable to parse the timestamp set on the journey, causing it to throw an error.
`software.amazon.awssdk.core.exception.SdkClientException: Unable to unmarshall response (Text '2022-10-25T06:09:55+00:00' could not be parsed at index 19). Response Code: 200, Response Text: OK`

## Steps to Reproduce

```
       PinpointClient pinpoint = PinpointClient.builder()
                .region(Region.US_EAST_1)
                .build();

        try {
            GetJourneyRequest request = GetJourneyRequest.builder()
                .journeyId(journeyId)
                .applicationId(existingApplicationId)
                .build();

            GetJourneyResponse response = pinpoint.getJourney(request);
            JourneyResponse journeyResponse =  response.journeyResponse();
            System.out.println("The name of the journey is "+journeyResponse.name());

       } catch (PinpointException e) {
        System.err.println(e.awsErrorDetails().errorMessage());
        System.exit(1);
    }
```

## Context
I am unable to fetch my journeys using the SDK

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by zoewangg** [comment]
Hi @johnmilimo thank you for reporting the issue. Taking a look

**Comment by zoewangg** [comment]
Hi @johnmilimo Thank you for your patience. #2499 is created to fix this issue
