### ISSUE TITLE
Optimistic Locking did not bump the record version while using Enhanced DDB Client 

### ISSUE THREAD

**Issue by AInoob** [aws/aws-sdk-java-v2#2489]
## Describe the bug

When using DynamodbMapper (com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMapper), when I annotate a field as DynamoDBVersionAttribute, it's value will be updated after mapper.save. However, in sdk v2, when a getter is annotate with DynamoDbVersionAttribute, it will not update the value after putItem.

## Expected Behavior

Value that has getter annotate with DynamoDbVersionAttribute will be incremented after putItem (it's incremented in ddb, but in the java runtime)

## Current Behavior

Value that has getter annotate with DynamoDbVersionAttribute will increment value in ddb, but not in java runtime.

## Steps to Reproduce

1. Create a model with DynamoDbVersionAttribute
2. PutItem(Object a)
3. In ddb, the version is bumped, however, Object a.version is not updated after putItem. This is different behavior compare with DynamodbMapper

## Your Environment

* AWS Java SDK version used: 2
* JDK version used: JDK11
* Operating System and version: macOS Big Sur

**Comment by AInoob** [comment]
Well, looks like VersionedRecordExtension will do the job. Confirming...

**Comment by AInoob** [comment]
After using saveItem instead of putItem, the version is updated. Resolving.

**Comment by knuspertante** [comment]
> After using saveItem instead of putItem, the version is updated. Resolving.

From where did you get the method saveItem?
