### ISSUE TITLE
"Spring on AWS" Survey - Open until 6/15

### ISSUE THREAD

**Issue by ik130** [aws/aws-sdk-java-v2#2492]
Hello AWS Java SDK community!

We are conducting a survey on your experience with Spring on AWS. It will take less than 5 minutes to answer just a few questions. We look forward to hearing from you!

**[Click HERE to take the survey](https://amazonmr.au1.qualtrics.com/jfe/form/SV_0MOoeogs4lhLTKe).**

**Comment by ik130** [comment]
This survey is now closed.

**Comment by eddumelendez** [comment]
@ik130 the results of the survey will be shared?
