### ISSUE TITLE
Lambda triggers are not being configured correctly

### ISSUE THREAD

**Issue by leandroalvesbsi** [aws/aws-sdk-java-v2#2494]
On creating or updating an user pool on Cognito the Lambda triggers never got triggered.

## Describe the bug

The same bug happens on both versions of the SDK (v1/v2), on creating an user pool via SDK the Lambda triggers has been sent using the LambdaConfigType class and looking though the AWS Web Console (Cognito -> User Pool -> General Settings -> Triggers) they are there, but on authenticating they never got triggered.
On my tests I'm using the UserMigration and PreTokenGeneration Lambdas.

The most strange thing is that the issue got sorted if I click on the "Save" button at the bottom of the Trigger page without changing anything. (Cognito -> User Pool -> General Settings -> Triggers -> "Click Save")

## Expected Behavior
After creating a pool programmatically the Lambda triggers has to be triggered as usual.

## Current Behavior
After creating a pool programmatically the Lambda triggers never got triggered.

## Steps to Reproduce

1. First create a Lambda for Cognito test purposes.
2. Create a User Pool programatically using the Java SDK with a Lambda trigger .
3. Create a Domain programatically using the Java SDK.
4. Create a User Pool Client programatically using the Java SDK.
5. Try authenticate against this poll and see if the lambda got triggered.

## Possible Solution
It seems that even with the interface showing that the Lambda Triggers were added to the User pool programmatically created, they are only persisted by clicking the "Save" button on the UI. Maybe there is some issue on persisting the objects.

## Context
I'm trying to integrate the user pool creation with the current Corporate creation I have on my business workflow.

## Your Environment

* AWS Java SDK version used: groupId = software.amazon.awssdk, artifactId = cognitoidentityprovider, version = 2.16.69
* JDK version used: 1.8.0_231
* Operating System and version: macOS Big Sur 11.2.3

**Comment by debora-ito** [comment]
@leandroalvesbsi to clarify, the issue you are seeing is that you create the User Pool and associate the Lambda functions with the events using the Java SDK, but then the Lambda functions are not triggered. They only start to be triggered after you click "Save" in the console. Is this the issue?

**Comment by leandroalvesbsi** [comment]
@debora-ito Yes, exactly. Looking at the Web Console, the triggers are there (I can see the names on the right place) but they don't get triggered until you click in "Save". This is a pain because the process of creating a pool can't be fully automated.

**Comment by leandroalvesbsi** [comment]
I think I found the source of the issue. 

The root of this issue seems to be the fact that the policy allowing requests coming from the programmatic created pool has not been added to the lambda. 

I've created multiple pools that are attached to the same lambdas, so what I did to mitigate the issue was create a policy using a wildcard allowing access from all user pools on my account.

That solves the issue but I noticed that even with a more permissive police using the wildcards it still creates another policy entry on the lambda when the save button is clicked on the Cognito triggers session, don't know if it is expected though.

**Comment by debora-ito** [comment]
@leandroalvesbsi I'm going through the list of old bugs, and found this one. So the issue seems to be related to the lack of necessary permissions.

Closing, as this is not an issue with the Java SDK. Feel free to reach out if you have any other question.
