### ISSUE TITLE
Confused about Maven Dependencies for software.amazon.awssdk vs. com.amazonaws

### ISSUE THREAD

**Issue by AlKoch** [aws/aws-sdk-java-v2#2498]
Hello,

I have been using a range of Java SDKs and in each case have used the Maven dependency I think is required. However, as part of trying move from specifying each dependency version to using a BOM I need to understand the difference.

For example, in the pom for a Lambda function I have 
	<dependency>
	    <groupId>com.amazonaws</groupId>
	    <artifactId>aws-lambda-java-events</artifactId>
	    <version>3.8.0</version>
	</dependency>

and 
	<dependency>
	    <groupId>software.amazon.awssdk</groupId>
	    <artifactId>lambda</artifactId>
	    <version>2.16.7</version>
	</dependency>

It has been very confusing to determine what GroupID and dependency to use when I start using a new service. The explanation for each in the Maven repo is very limited.

Can someone explain the differences in the two GroupIDs and what decision criteria to use to determine what dependency to fetch from the Maven repo?

Thank you!

**Comment by debora-ito** [comment]
Hi @AlKoch thank you for reaching out. I see how this can be confusing. You have to consider both GroupId and ArtifactId.

GroupId `software.amazon.awssdk` is the groupId used for the Java SDK version 2.x. All the service modules supported by the Java SDK 2.x are present in the BOM module [bom](https://github.com/aws/aws-sdk-java-v2/tree/master/bom), `lambda` being one of them. Each of these modules provides the service APIs you see in the [Java SDK API Reference](https://sdk.amazonaws.com/java/api/latest/overview-summary.html) - for example, here's the Lambda Client [docs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/LambdaClient.html).

GroupId `com.amazonaws` is used for the Java SDK 1.11.x. Same thing, all the supported service modules are present in the 1.11.x BOM module [aws-java-sdk-bom](https://github.com/aws/aws-sdk-java/tree/master/aws-java-sdk-bom). But in this case, you are using the `aws-lambda-java-events` artifactId, which is a "standalone" library not under the Java SDK 1.11.x. project - https://github.com/aws/aws-lambda-java-libs. The `aws-lambda-java-events` is a support library that provides classes/methods to handle event sources that AWS Lambda natively accepts. It's also distributed under the `com.amazonaws` groupId.

About adding a new dependency, we have more information in the Developer Guide - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html#modules-dependencies. 

Let us know if this helps a little or if you have more questions.

**Comment by debora-ito** [comment]
@EDGESoftware thank you for your patience, apologies for the delay in response.

The core of your questions 1 and 2 relies in the definition of [Transitive Dependencies](http://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html), you can learn more about it in the maven documentation. Very succinctly, projects like AWS Toolkit for Eclipse and the Lambda Java Events use the Java SDK as a dependency in their projects. If your own project is using those projects and using the Java SDK, you are adding levels of dependencies required for your project to run, and the versions of each dependency will probably mismatch. Maven has mechanisms to determine which version to use when multiple versions are encountered in the dependency tree. I recommend you read the Maven documentation if you haven't already. 


> 3. Locating something in the Maven Repo is very confusing. I start at https://mvnrepository.com/ but there is no item for "AWS". Searching for "AWS" yields https://mvnrepository.com/search?q=AWS. Under Groups on the left side I see com.amazonaws but not software.amazon.awssdk.

> 3a) Why can't I see the latest Java SDK version2 (software.amazon.awssdk)?

I agree that Maven Repository doesn't have the best search/discoverability experience. `AWS` is a pretty broad search keyword and there's a lot of other AWS projects distributed in Maven besides the Java SDK. What I usually do is first go the documentation of the project I want to use and read how to obtain its packages, and only use the Maven Repository search if I really need to. 

If you use an IDE like Intellij, the autocomplete is your friend.

![Screen Shot 2021-06-11 at 11 43 52 AM](https://user-images.githubusercontent.com/476307/121735979-c055d100-caab-11eb-8ad7-7792459ef33a.png)


> 3b) If I search for software.amazon.awssdk the list is filtered for software.amazon.awssdk but how in the world would someone figure out what they need to include in a Project? (For example, the 1st item is "AWS Java SDK :: Core :: Protocols :: Protocol Core" - sounds important! However, none of my existing projects use it!)

You only have to include the Java SDK service modules you want to use, like `dynamodb` and `lambda`. Each service module will include the core modules automatically, you don't have to worry about them. You can read more about this in our [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html).

> 3c) If I search the repo for say aws-lambda-java-events and aws-lambda-java-core it appears that all that is available are v1. Why is the main Java SDK called "v2" but Java SDK for particular services is v1?

> In general, when I am learning how to use Java with a new service I have been going through the following (very inefficient and frustrating) steps. While I've gotten Lambda mostly working I'll use it as an example

I see the source of the confusion now. The Java sample apps showed [here](https://docs.aws.amazon.com/lambda/latest/dg/java-samples.html) in the Lambda Dev Guide use https://github.com/aws/aws-lambda-java-libs, and even though their GroupId is `com.amazonaws` they are not under the Java SDK project, they are a separate project as I said in my last comment, so the SDK v1 or v2 context does not apply for these libs.

The search for the Lambda Invoke is not that bad for a first time using the Java SDK. If you check the top right of the [LambdaClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/LambdaClient.html#invoke--) javadoc you'll read "AWS SDK for Java API Reference - " and a version number. This version number is usually the latest released version. How to be sure? Check our GitHub repository: https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md.

Using a combination of the Javadocs and the knowledge that `software.amazon.awssdk` is the package name used in Java SDK v2 (plus Intellij autocomplete), you can assume that `software.amazon.awssdk.services.lambda` is part of the `lambda` SDK module (defined in the pom.xml as the ArtifactId). Later, if you decide to use EC2 APIs in your project and stumble in the [Ec2Client](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/Ec2Client.html) javadocs, you can see the package for the Ec2Client is `software.amazon.awssdk.services.ec2`, which means it's in the `ec2` module. And so on. 

I hope this helps clarify some of the confusion. Let us know if you have any more questions.

**Comment by AlKoch** [comment]
Hi Debora,

Sorry for such a long wait for a response but I never got an email indicating you had responded. Thank you for the long and detailed response. What you said helps and it clarified a couple of questions. I think that this is a case where a person has to just work with all of this for a long time and answer a lot of "how do I find" questions along the way.

Thank you again I appreciate your help.
