### ISSUE TITLE
[Help]Getting error in WellArchitected aws service

### ISSUE THREAD

**Issue by niraj-ranjan-comprinno** [aws/aws-sdk-java-v2#2510]
I am getting error while calling listWorkloads.
Error is ``Unsupported Media Type (Service: WellArchitected, Status Code: 415, Request ID: 8acd63db-8a7f-4adf-9188-3b060da968d6, Extended Request ID: null)``
## Steps to Reproduce

AwsCredentials credentials = AWSCustomCredentialHandler.getCredential(credential);

WellArchitectedClient wellArchitectedClient = WellArchitectedClient.builder()
.credentialsProvider(new AWSStaticCredentialsProvider(credentials)).region(Region.AP_SOUTH_1)
.build();

ListWorkloadsRequest.Builder listWorkloadsRequest = ListWorkloadsRequest.builder();
ListWorkloadsResponse listWorkloadsResponse = wellArchitectedClient.listWorkloads(listWorkloadsRequest.build());

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:

**Comment by niraj-ranjan-comprinno** [comment]
@joviegas Please help

**Comment by debora-ito** [comment]
Hi @niraj-ranjan-comprinno thank you for reporting this, we'll work on a fix.

**Comment by joviegas** [comment]
Hi @niraj-ranjan-comprinno 
Appreciate your patience 👍 
The issue is fixed and available in  Release version 2.16.82.

**Comment by niraj-ranjan-comprinno** [comment]
> Hi @niraj-ranjan-comprinno
> Appreciate your patience 
> The issue is fixed and available in Release version 2.16.82.

Hi @joviegas , Many many thanks
