### ISSUE TITLE
DynamodbEnhanced Client - Transact Write clientRequestToken

### ISSUE THREAD

**Issue by rajithd-aurea** [aws/aws-sdk-java-v2#2518]
I would like to get a proper recommendation for this issue.

## Describe the issue
I'm using DynamoDbEnhancedAsyncClient and use TransactWrite to save items to dynamodb. 
I have configured my dynamodb sdk client with following retry config.
```
ClientOverrideConfiguration.builder()
                .retryPolicy(dynamoClientRetryPolicy)
                .apiCallTimeout(Duration.ofMillis(dynamodbProperties.getApiCallTimeout()))
                .apiCallAttemptTimeout(Duration.ofMillis(dynamodbProperties.getApiCallAttemptTimeout()))
                .build()
```
`dynamoClientRetryPolicy` is configured to retry for failures. This include ApiCallAttempTimeoutException.class.

## Current Behavior
If we are running with higher TPS, then sometimes I can see 
```
software.amazon.awssdk.services.dynamodb.model.TransactionInProgressException: Transaction from previous request is still in progress (Service: DynamoDb, Status Code: 400, Request ID: 1CIJS95U5OGPQHDCU5FSGTINGRVV, Extended Request ID: null)
```
It starts with `ApiCallAttemptTImeout` exception. Then retrying and getting the second error as `TransactionInProgressException.java`. But in the code we are populating `clientRequestToken` before the request. Based on the documentation this is an idempotent request. 

So the question is why we can see `TransactionInProgressException` even though we are executing the retry with same client token ?

## Your Environment
openjdk version "11.0.11" 2021-04-20 LTS

**Comment by debora-ito** [comment]
You called TransactWrite the first time and got an `ApiCallAttemptTImeout` exception. This means the client didn't received a response in time before the configured timeout.

When you provided the clientRequestToken the second time, DynamoDB responded with `TransactionInProgressException`, this is the service saying it received the request the last time and it's still in progress. It is making sure the transaction is not being submitted again.

Additional info from the [Dev Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/transaction-apis.html) about Idempotency:

> Idempotency
You can optionally include a client token when you make a TransactWriteItems call to ensure that the request is idempotent. Making your transactions idempotent helps prevent application errors if the same operation is submitted multiple times due to a connection time-out or other connectivity issue.
> 
> If the original TransactWriteItems call was successful, the subsequent TransactWriteItems calls with the same client token return successfully without making any changes. If the ReturnConsumedCapacity parameter is set, the initial TransactWriteItems call returns the number of write capacity units consumed in making the changes. Subsequent TransactWriteItems calls with the same client token return the number of read capacity units consumed in reading the item.
> 
> Important Points about Idempotency
> 
> A client token is valid for 10 minutes after the request that uses it finishes. After 10 minutes, any request that uses the same client token is treated as a new request. You should not reuse the same client token for the same request after 10 minutes.
> 
> If you repeat a request with the same client token within the 10-minute idempotency window but change some other request parameter, DynamoDB returns an IdempotentParameterMismatch exception.

Let us know if this helps.

**Comment by rajithd-aurea** [comment]
@debora-ito thank you for the explanation. 
Is it possible to resubmit the transaction write request again ? Lets say our application received `ApiCallAttempTimeout` exception at the first time. Then we retry and resubmit the transaction write request and ask AWS to discard the previous one and retry this again with new request ?
Or any other recommendation to handle this issue ? This is not that frequent but still we are getting issues with this approach. 
E.g.
apiCallTimeoutAttemp configured as 1 second.
Normal flow -> Submit transact write API request -> Dynamo is taking time to respond and after 1 second throw `ApiCallAttempTimeout` 
1st retry -> Submit same request again with same client token as normal flow -> `TransactionInProgressException`

**Comment by debora-ito** [comment]
There's no way to say to DynamoDB to discard the first transaction after the service say it's in progress. 

Note that seeing `TransactionInProgressException` does not mean that your transaction has failed. The client should be sending retries for these exceptions, if not you can configure to retry it using the same client token until it gets a successful response.
