### ISSUE TITLE
Allow for object deletion via a presigned URL

### ISSUE THREAD

**Issue by hashpyrit** [aws/aws-sdk-java-v2#2520]
There appears to be no way to generate a pre-signed URL to delete an object from S3 using the V2 Java SDK.  This feature exists in the V1 Java SDK https://docs.amazonaws.cn/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html

## Your Environment
* AWS Java SDK version used: 2.16.78
* JDK version used: 8
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
Thank you for reaching out @hashpyrit, adding this feature request to our backlog.
Out of curiosity, can you tell us more about your use case?

For others who want us to support DELETE presigned urls please upvote the issue description, it help us with prioritization.

**Comment by hashpyrit** [comment]
Hi @debora-ito .  My use case is as follows:
We send messages via RabbitMQ to a service that writes files.  Sometimes these files are quite large and thus exceed the max recommended size for RabbitMQ messages so we want to put the files in S3 for retrieval via a presigned URL.  It would also be convenient for the file writer service to be able to delete the files from S3 once it's done writing via a presigned URL.  Using the presigned URL is great because the file writer doesn't need to know anything about S3 APIs, it just needs to be able to make standard HTTP operations.
Just to confirm, deleting via a presigned URL is supported in the V1 Java SDK correct?  It appears as so from looking at the Java doc but I haven't tried it myself yet.  It would be good to have feature parity between the two.

**Comment by debora-ito** [comment]
Yes it's possible to generate a delete presigned URL, I didn't know either so I tested :)

**Comment by hashpyrit** [comment]
Fantastic thanks for checking.  I assume that you used the V1 SDK to do the delete?  It would be great if this feature were be put into V2 so it has at least as many features as V1 :).
