### ISSUE TITLE
Java-V2 AWS S3 - Cannot Create a Bucket 

### ISSUE THREAD

**Issue by aravind-25-gopinath** [aws/aws-sdk-java-v2#2534]
## Describe the bug

I am currently using the Java AWS SDK 2.x and trying to create a bucket using an URI (for a company endpoint). I am able to list my existing buckets and objects but CANNOT create a new one bucket (I am following all naming guidelines). I was able to successfully create buckets with the s3 service in python using boto3 but NOT in java. 

## Expected Behavior

The bucket should be successfully created in my namespace

## Current Behavior

Right now, whenever I create my bucket I get the error "The specified bucket is not valid. (Service: S3. Status Code: 400..) etc"

## Context

I am trying to create a use case guide on how to utilize object storage but this is hindering my process. 

## Your Environment

* AWS Java SDK version used:
* JDK version used:
* Operating System and version:
Using Java 8, on Windows 10

**Comment by aravind-25-gopinath** [comment]
package com.example.s3;

import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.core.waiters.WaiterResponse;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.*;
import software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable;
import software.amazon.awssdk.services.s3.waiters.S3Waiter;

import java.net.URI;
import java.net.URISyntaxException;

public class CreateBucket {

    public static void main(String[] args) throws URISyntaxException {
        URI myURI = new URI("https://s3-object.ford.com");
        AwsBasicCredentials awsCreds = AwsBasicCredentials.create(
                Credentials.access_key,
                Credentials.secret_access_key);

        S3Client s3 = S3Client.builder()
                .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
                .endpointOverride(myURI)
                .build();
        CreateBucketRequest request = CreateBucketRequest.builder()
                .bucket("32ara")
                .build();
        try {
            s3.createBucket(request);
        } catch (Exception exception){
            System.out.println(exception.getMessage());
        }

        

    }


}

**Comment by aravind-25-gopinath** [comment]
I am able to use URI  to connect to my company endpoint to list existing buckets and objects but will not create a new bucket no matter what name is provided

**Comment by debora-ito** [comment]
Can you provide the verbose wire logs? This link has more info on how to turn on the verbose wire logging - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

**Comment by aravind-25-gopinath** [comment]
Ok I talked with memebers of my team and they seem to think this is the fix:
final ClientConfiguration config = new ClientConfiguration().withProtocol(Protocol.HTTPS); config.setSignerOverride("S3SignerType");

final ApacheHttpClientConfig apacheConfig = config.getApacheHttpClientConfig();
apacheConfig.setSslSocketFactory(SSLSocketFactory.getSystemSocketFactory());
/*
* if the above line by itself does not work, uncomment this block

final SSLContext ctx = new SSLContextBuilder().useTLS().build();
apacheConfig.setSslSocketFactory(new SSLSocketFactory(ctx, new String[] {"TLSv1.2"}, new String[] {"SSL_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384" "SSL_ECDHE_RSA_WITH_AES_256_GCM_SHA384", "SSL_DHE_RSA_WITH_AES_256_GCM_SHA384", "SSL_RSA_WITH_AES_256_GCM_SHA384", "SSL_RSA_WITH_AES_256_CBC_SHA256", "SSL_ECDH_ECDSA_WITH_AES_128_GCM_SHA256", "SSL_DHE_DSS_WITH_AES_128_GCM_SHA256"}, SSLSocketFactory.BROWSER_COMPATIBLE_HOSTNAME_VERIFIER));
*/
client = new AmazonS3Client(creds, config);

**Comment by aravind-25-gopinath** [comment]
all of that is in V1, would you be able to help me convert this to V2

**Comment by debora-ito** [comment]
- The SDK uses HTTPS protocol by default, but in this case it will depend on the protocol used in "myURI" you are setting in the endpointOverride ("http://" or "https://").

- `config.setSignerOverride("S3SignerType")` would be an advanced option in v2 ClientOverrideConfiguration:
```
ClientOverrideConfiguration.Builder overrideConfig = ClientOverrideConfiguration.builder();
overrideConfig.advancedOption(SdkAdvancedClientOption.SIGNER, ...)
```
but note that `S3SignerType` I think it's S3 Sigv2 implementation and Sigv2 is on deprecation path - it would not be the cause for the error if the response is coming from S3.

- In v2 ApacheHttpClient you can configure the TLS key managers and trust managers in the client builder - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/apache/ApacheHttpClient.Builder.html

**Comment by debora-ito** [comment]
Forgot to mention, we have a Java V1 to V2 Changelog that can be helpful in these cases: https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md

**Comment by aravind-25-gopinath** [comment]
Thanks for the help so far! Do you think the issue lies in with the code I pasted above, or somewhere else? I still cannot find a solution to this issue and I need it delivered on tomorrow.
