### ISSUE TITLE
Java Doc error in ResourcesAffected in AWS Macie2 API

### ISSUE THREAD

**Issue by TanveshT** [aws/aws-sdk-java-v2#2552]
AWS Macie Findings revolve around a particular S3 Object if the finding type belongs to `SensitiveData:S3Object/<Finding-Type>` ( [reference](https://docs.aws.amazon.com/macie/latest/user/findings-types.html) ). So a particular finding will show a particular S3 object as a resource affected instead of an array of s3 objects. The `software.amazon.awssdk.services.macie2.model.ResourcesAffected` gives the resources affected for a particular finding and works as per the requirement but `ResourcesAffected.s3Object` and `ResourcesAffected.s3Bucket` has a java doc bug as stated below

## Describe the issue

As you can see the return types for `ResourcesAffected.s3Object` and `ResourcesAffected.s3Bucket` is a single object and not an array of objects, the java doc needs to change accordingly.

<img width="1322" alt="Screenshot 2021-06-23 at 2 45 05 PM" src="https://user-images.githubusercontent.com/36622194/123070708-9c8e7580-d431-11eb-8312-a7b5a7ceb387.png">

## Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/macie2/model/ResourcesAffected.html

**Comment by TanveshT** [comment]
I can contribute in fixing the bug too.

**Comment by debora-ito** [comment]
Hi @TanveshT thank you for reaching out. The Javadocs are auto-generated based on service models, which are owned by the service teams, so the change must be made upstream. 

I'll contact the Macie team internally and ask them to fix the documentation. Will add an update when I hear back.

**Comment by TanveshT** [comment]
Hello @debora-ito , Thank you for replying. Happy to help. If any contributions are needed to change the docs in the code. I could help in doing so too!

**Comment by TanveshT** [comment]
## Update

The issue exits in the API-reference too
Link: [here](https://docs.aws.amazon.com/macie/latest/APIReference/findings-describe.html#findings-describe-model-resourcesaffected)

<img width="721" alt="Screenshot 2021-06-25 at 9 26 21 AM" src="https://user-images.githubusercontent.com/36622194/123367455-93b7b400-d597-11eb-932b-913478d46d6c.png">

**Comment by debora-ito** [comment]
@TanveshT the Macie team updated the documentation in both [API Reference](https://docs.aws.amazon.com/macie/latest/APIReference/findings-describe.html#findings-describe-model-resourcesaffected) and the [Javadocs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/macie2/model/ResourcesAffected.html).

I'll go ahead and close this. Thank you again for the feedback.

**Comment by TanveshT** [comment]
Thank you @debora-ito for updating. Glad to see that it got fixed.
