### ISSUE TITLE
Security Hub issue

### ISSUE THREAD

**Issue by niraj-ranjan-comprinno** [aws/aws-sdk-java-v2#2555]
API to get security score
## Describe the bug

Hi, i am working with security hub apis. I want to calculate overall security score or based on security standard.
I have attached the image below. 

![image](https://user-images.githubusercontent.com/64660855/123224353-5f88b880-d4ef-11eb-8cf3-db60eea4a851.png)

## Your Environment

* AWS Java SDK version used: 2
* JDK version used: 8
* Operating System and version: Linux based

**Comment by debora-ito** [comment]
Hi @niraj-ranjan-comprinno I see you opened this is a bug, can you give us more information on what you've tried to do and what is not working as you expected? I'm not clear on what is the ask here.
