### ISSUE TITLE
501 Not Implemented when creating a bucket as static web host

### ISSUE THREAD

**Issue by aravind-25-gopinath** [aws/aws-sdk-java-v2#2561]
I am trying to set a static website host for a bucket using my company endpoint but run into issues. 

## Describe the bug

When I use the code in the aws-sdk-docs under JavaV2 and S3, I copied and pasted the code the allows you to set a website configuration for the bucket. However, I run into an HTTPS Status Code Error: 501 Not Implemented error. After speaking with Scott MacDonald, he tried running the same code without an endpoint override and it seems to work fine.  

## Expected Behavior

It should create a website configuration for a specified bucket. 

## Current Behavior

I get a HTTPS Status Code Error: 501 Not Implemented 

## Steps to Reproduce

ackage com.example.s3;

public class SetStaticWebsiteHost {
public static void main(String[] args) throws URISyntaxException {
    
    URI myURI = new URI("<company URL>");

    AwsBasicCredentials awsCreds = AwsBasicCredentials.create(
            Credentials.access_key,
            Credentials.secret_access_key);

    S3Configuration config = S3Configuration.builder()
            .pathStyleAccessEnabled(true)
            .build();

    //Creating the s3 Client that will utilize the credentials and the endpoint provided
    S3Client s3 = S3Client.builder()
            .credentialsProvider(StaticCredentialsProvider.create(awsCreds))
            .endpointOverride(myURI)
            .serviceConfiguration(config)
            .build();

    setWebsiteConfig(s3, "java-test-bucket", "index.html", "error.html");
}
public static void setWebsiteConfig( S3Client s3,
                                     String bucketName,
                                     String indexDoc,
                                     String errorDoc) {

    try {
        WebsiteConfiguration websiteConfig = WebsiteConfiguration.builder()
                .indexDocument(IndexDocument.builder().suffix(indexDoc).build())
                .errorDocument(ErrorDocument.builder().key(errorDoc).build())
                .build();

        PutBucketWebsiteRequest pubWebsiteReq = PutBucketWebsiteRequest.builder()
                .bucket(bucketName)
                .websiteConfiguration(websiteConfig)
                .build();

        s3.putBucketWebsite(pubWebsiteReq);

    } catch (S3Exception e) {
        System.err.println(e.awsErrorDetails().errorMessage());
        System.exit(1);
    }
}

## Your Environment

* AWS Java SDK version used: V2
* JDK version used: 8
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
Here's what the [S3 API Reference](https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html) says about error code 501 Not Implemented:

> 
Error Code | Description | HTTP Status Code
-- | -- | --
NotImplemented | A header you provided implies functionality that is not implemented. | 501 Not Implemented

If sending the request directly to the S3 endpoint does not throw the error, then your custom endpoint must be adding a header to the request that S3 is not recognizing.


Always check first the list of error responses in the API References, services usually list the possible error codes and add a small description to help with troubleshooting.

https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by aravind-25-gopinath** [comment]
so does this mean as of now there is a bug when I use my custom endpoint with this s3 operation and I cannot use it as of now?

**Comment by aravind-25-gopinath** [comment]
because I used exactly the code in the aws-sdk-docs java V2 s3 github repo and the only thing different is my custom endpoint

**Comment by debora-ito** [comment]
Yes, the application running in your custom endpoint is probably adding the unsupported header. This does not look like an issue with the SDK.

Enabling logs like wirelogs should help in the investigation of which headers are being sent in the requests - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose
