### ISSUE TITLE
BatchGetItemRequest does not support consistent read

### ISSUE THREAD

**Issue by reed53** [aws/aws-sdk-java-v2#2562]
Although consistent read can be used with a batch get item request, as seen here:
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html
The current BatchGetItemRequest class does not allow the user to set consistent read

## Describe the bug

Consistent read is a field that is present within the BatchGetItem request that is sent to dynamo, however it is missing within the java BatchGetItemRequest class

## Expected Behavior

Add a functionality that supports consistent read with the BatchGetItemRequest class

## Current Behavior

The BatchGetItemRequest class does not have a consistent read field.

## Steps to Reproduce

N/A
## Context

On SDK1, our team had used consistent read with a BatchGetItem request, however we cannot do that on SDK2

## Your Environment

* AWS Java SDK version used: 2.6.21
* JDK version used: 11

**Comment by debora-ito** [comment]
@reed53 consistentRead can be provided in the `requestItems` map, using the BatchGetItemRequest.Builder - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/BatchGetItemRequest.Builder.html#requestItems-java.util.Map-

```java
Map<String, KeysAndAttributes> item = new HashMap<>();
item.put("myBooks", KeysAndAttributes.builder()
                .keys(Map.of("id", AttributeValue.builder().s("ABC").build()))
                .projectionExpression("title")
                .consistentRead(true)
                .build());

BatchGetItemResponse response = client.batchGetItem(BatchGetItemRequest.builder()
                .requestItems(item)
                .build());
```

**Comment by debora-ito** [comment]
Let us know if you have any questions.

**Comment by reed53** [comment]
> @reed53 consistentRead can be provided in the `requestItems` map, using the BatchGetItemRequest.Builder - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/BatchGetItemRequest.Builder.html#requestItems-java.util.Map-
> 
> ```java
> Map<String, KeysAndAttributes> item = new HashMap<>();
> item.put("myBooks", KeysAndAttributes.builder()
>                 .keys(Map.of("id", AttributeValue.builder().s("ABC").build()))
>                 .projectionExpression("title")
>                 .consistentRead(true)
>                 .build());
> 
> BatchGetItemResponse response = client.batchGetItem(BatchGetItemRequest.builder()
>                 .requestItems(item)
>                 .build());
> ```

Ah I see. Sorry for the misunderstanding. Thank you!
