### ISSUE TITLE
writeGetObjectResponse() implementation

### ISSUE THREAD

**Issue by anirtek** [aws/aws-sdk-java-v2#2569]
## Where is writeGetObjectResponse() implemented?

I am trying to understand how exactly writeGetObjectResponse() passes transformed data to getObject() operation? But I could not find any clear implementation of the method defined in the interface s3Client. Where exactly do I find the implementation of this new API? 

## Links

I am referring to these links - 

- https://docs.aws.amazon.com/AmazonS3/latest/API/API_WriteGetObjectResponse.html
- https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/

**Comment by debora-ito** [comment]
Hi @anirtek the auto-generated resources are not stored in the repo anymore. If you want to take a look at the code you can build the project locally, this page in the Contributing guide can help you with that - https://github.com/aws/aws-sdk-java-v2/blob/master/docs/GettingStarted.md

As an alternative, IDEs like Intellij can also decompile and download the code of dependency modules.

**Comment by anirtek** [comment]
@debora-ito oh great! I think this should solve my problem. thank you very much. I am particularly looking forward to understand how requestToken is mapped with WriteGetObjectRequest so that it can respond to original getObject() request.

**Comment by debora-ito** [comment]
I'll go ahead and close this, feel free to reach out with any other question.
