### ISSUE TITLE
Add service endpoint metric like the one provided in v1 SDK

### ISSUE THREAD

**Issue by 4423** [aws/aws-sdk-java-v2#2579]
## Describe the Feature
In v1, AWS SDK request metrics included service endpoint metric which can be used to identify a service.
It would be nice to have this in v2 SDK as well.

Below are the concrete code to get this metric in v1 and the expected code in v2.

```kt
// v1
class SampleRequestMetricCollector : RequestMetricCollector() {
    override fun collectMetrics(request: Request<*>, response: Response<*>) {
        val metrics = request.awsRequestMetrics
        val serviceEndpoints = metrics.getProperty(AWSRequestMetrics.Field.ServiceEndpoint)
        ...
    }
}
```

```kt
// v2
class SampleMetricPublisher : MetricPublisher {
    override fun publish(metricCollection: MetricCollection) {
        val serviceEndpoints = metricCollection.metricValues(CoreMetric.SERVICE_ENDPOINT)
        ...
    }
}
```

Is there any solution to get a metric corresponds to the service endpoint in v2?
In particular, I want to know the bucket name of S3 included in the service endpoint.

## Your Environment
* AWS Java SDK version used: 2.16.92
* JDK version used: 11
* Operating System and version: macOS Catalina

**Comment by debora-ito** [comment]
@4423 thank you for reaching out. This is a reasonable feature to add since it's available in v1.
