### ISSUE TITLE
How to fetch the public ip for ECS's task?

### ISSUE THREAD

**Issue by kevinchan0319** [aws/aws-sdk-java-v2#2580]
Where can I find the public ip for a task? I have tried method DescribeTasksResponse but only private Ip and mac address are found.

**Comment by debora-ito** [comment]
Hi @kevinchan0319 this is a service-specific question, and this repo is not the best place for asking those.
This repo is a channel for bug reports and feature requests around the SDK itself. 

I recommend you reach out to communities like StackOverflow.
