### ISSUE TITLE
SNS Signature Verifier in sdk-java-v2?

### ISSUE THREAD

**Issue by ph4r05** [aws/aws-sdk-java-v2#2581]
Is there going to be a class providing SNS signature verification in aws-sdk-java-v2?

## Describe the Feature
It would be great to have class doing signature verification on SNS received messages as SDK v1 had it.
Its absence in v2 makes usage quite cumbersome. It can lead developers to omit signature verification, do it somehow in their own (increasing risk of error, as devs are usually not best with crypto code). 

## Is your Feature Request related to a problem?
SNS signature verification by developer is pain and I think it should be part of the SDK.

## Proposed Solution
Port https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-sns/src/main/java/com/amazonaws/services/sns/message/SnsMessageManager.java or similar feature to v2

## Describe alternatives you've considered
Not much tbh.

## Additional Context
I am trying to implement SNS subscription on https endpoint. SNS can be spoofed so signature verification is a must and I cannot find anything doing the verification in v2.

**Comment by debora-ito** [comment]
@ph4r05 thank you for reaching out. We have an issue asking to add support for an equivalent of SnsMessageManager in v2, we are tracking here: https://github.com/aws/aws-sdk-java-v2/issues/1302.

Closing this as a duplicate.
