### ISSUE TITLE
DynamoDbEnhancedClient: Describe table operation 

### ISSUE THREAD

**Issue by reply2srij** [aws/aws-sdk-java-v2#2609]
The DynamoDbEnhancedClient returns a DynamoDbTable that allows you to perform various dynamodb operations. Good to have an operation similar to Describe table as well. 

## Your Environment
* AWS Java SDK version used: 2.16.99
* JDK version used: java-openjdk-11.0.8.10
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
@reply2srij thank you for reaching out, marking as a feature request.

**Comment by zoewangg** [comment]
@reply2srij thank you for your patience. We have implemented the feature in #2844. Please try with the latest Java SDK.
