### ISSUE TITLE
Usage of STS in China regions

### ISSUE THREAD

**Issue by kwakiutlCS** [aws/aws-sdk-java-v2#2620]
The SDK fails to connect to sts endpoint in China, in this case sts.cn-north-1.amazonaws.com.cn:443. It timeouts after sometime.

## Describe the issue
I try to perform some S3 actions. I have a kubernetes pod configured with IRSA authentication. When the SDK tries to reach the sts endpoint it timeouts in cn-north-1 region (when I try the same in other region from the global infrastructure, it works fine). 
I don't explicitely do any call to STS, I just have the STS dependency in the pom file. 

Also when I call the sts service from cn-north-1 with the command line client it works, so I think it is not me not having access.
Should the authentication work on china regions? Or it is necessary to configure anything else extra?
Thank you for your help

## Your Environment
* AWS Java SDK version used: 2.16.104
* JDK version used: 11.0.9
* Operating System and version: Linux Amazon2

**Comment by debora-ito** [comment]
Hi @kwakiutlCS, 

according to the AWS Endpoints doc page, STS does not have a regional endpoint in `cn-north-1` - 
https://docs.aws.amazon.com/general/latest/gr/sts.html.

Using the global endpoint `sts.amazonaws.com` is recommended in this case.

**Comment by kwakiutlCS** [comment]
Thank you for your help, @debora-ito 

I'm a bit confused by the docs. I thought those docs didn't make reference to the cn-north-1 endpoint because being the documentation for the global infrastructure only, but I see the S3 section has the cn-north-1 endpoint there.

But I was going mainly by https://docs.amazonaws.cn/en_us/aws/latest/userguide/endpoints-Beijing.html, which does make reference to sts.cn-north-1.amazonaws.com.cn. Doesn't this documentation apply for this situation?

Also when I make a call in cn-north-1 "aws sts get-caller-identity --debug" I see logs like
MainThread - urllib3.connectionpool - DEBUG - https://sts.cn-north-1.amazonaws.com.cn:443 "POST / HTTP/1.1" 200 463

this is an endpoint that the client uses by default (same as in my application where I just try some S3 action and the STS endpoint I selected by the SDK, as I don't make explicit calls to STS). Shouldn't the SDK select the correct endpoint?

**Comment by debora-ito** [comment]
You are absolutely correct, I've assumed `cn-north-1` regional endpoint would be listed, thank you for pointing out the Beijing Region Endpoints page.

In this case, please provide a sample code we can use to reproduce the issue.
Can you also enable verbose wire logging and provide the wire logs? Please make sure to redact any sensitive information it may contain (like access keys).
