### ISSUE TITLE
DynamoDBIgnoreNulls - propagation to list of inner classes

### ISSUE THREAD

**Issue by reply2srij** [aws/aws-sdk-java-v2#2621]
I am using @DynamoDbIgnoreNulls on list of InnerClass, but the get responses do contain attributes that are null. Refered to #2303[](https://github.com/aws/aws-sdk-java-v2/issues/2303), the difference being what I have is a List of InnerClasses. 

@DynamoDbBean
public class OuterClass {	
	private String outerClassPrimaryKey;	
	private List<InnerClass> innerClassList;

	@DynamoDbPartitionKey
	public String getOuterClassPrimaryKey() { return outerClassPrimaryKey; }
	public void setOuterClassPrimaryKey(String outerClassPrimaryKey) { this.outerClassPrimaryKey = outerClassPrimaryKey;	}

	@DynamoDbIgnoreNulls
	public List<InnerClass> getInnerClassList() { return innerClassList; }
	public void setInnerClassList(List<InnerClass> innerClassList) { this.innerClassList = innerClassList; }
}

@DynamoDbBean
public class InnerClass {
	private String innerClassPrimaryKey;
	private String innerClassAttribute1;
	private String innerClassAttribute2;
	
	@DynamoDbPartitionKey
	public String getInnerClassPrimaryKey() { return innerClassPrimaryKey; }
	public void setInnerClassPrimaryKey(String innerClassPrimaryKey) { this.innerClassPrimaryKey = innerClassPrimaryKey; }
	public String getInnerClassAttribute1() { return innerClassAttribute1; }
	public void setInnerClassAttribute1(String innerClassAttribute1) { this.innerClassAttribute1 = innerClassAttribute1; }
	public String getInnerClassAttribute2() { return innerClassAttribute2; }
	public void setInnerClassAttribute2(String innerClassAttribute2) { this.innerClassAttribute2 = innerClassAttribute2; }
}

* AWS Java SDK version used: 2.16.99
* JDK version used: Open JDK 11
* Operating System and version: Windows 10

**Comment by debora-ito** [comment]
@reply2srij The `@DynamoDbIgnoreNulls` annotation should be working in this case.

Can you provide a sample code where you use the bean classes you showed in the description, and describe exactly what you are seeing and what you expected to see?
