### ISSUE TITLE
Release 2.17 wrongfully removed EC2MetadataUtils#getInstanceInfo

### ISSUE THREAD

**Issue by slandelle** [aws/aws-sdk-java-v2#2625]
## Describe the bug

[This commit](https://github.com/aws/aws-sdk-java-v2/commit/51cf791235c6bf408d40df35411eb11f12839eef#diff-aa35187dc0d550f218a761a04b65ab1c79c6804221535a1c66da49feb8475a1aL227), described as some internal clean up in order to remove Jackson dependencies.

Sadly, it also performed some other unrelated **functional** changes. In particular, it removed `EC2MetadataUtils#getInstanceInfo` (and some other methods too).

## Expected Behavior

* No functional change should occur in a PR that claims to just be a refactoring in order to change the JSON parser.
* Removing features shouldn't be performed without providing a migration path.

## Current Behavior

We contributed a change in `EC2MetadataUtils` 2 years ago in order to expose the AWS MarkerPlace product codes that were in the response payload but not mapped in the POJO.

This data is critical for us as AWS MarketPlace vendors.
This feature was removed without any further notice, without considering impacts (in particular for us who appear in the git history of this class) and without providing a migration path.

## Steps to Reproduce

Please read the changes in [EC2MetatadataUtils](https://github.com/aws/aws-sdk-java-v2/commit/51cf791235c6bf408d40df35411eb11f12839eef#diff-aa35187dc0d550f218a761a04b65ab1c79c6804221535a1c66da49feb8475a1aL227).

## Possible Solution

Someone might argue that this method is an internal and users shouldn't it it. However:

* using this REST API was the means the AWS MarketPlace people told us to use to fetch the AWS MarketPlace product codes
* the AWS Java SDK doesn't provide any other means to achieve this
* our contributions were reviewed and merged, you can't just simply remove them without considering the impact

Ideally, this SDK should provide a public stable API for fetching Marketplace ProductCodes. Or make `EC2MetatadataUtils` a stable API.

In the meantime, please restore this method.

## Context

We've been using this class for years as it's the only way for AWS MarketPlace AMI vendors to fetch the AWS MarketPlace product codes. We even [contributed](https://github.com/aws/aws-sdk-java-v2/commit/f6e9cca46e7744b31ce6fbf263fc7e9287dc01b3#diff-aa35187dc0d550f218a761a04b65ab1c79c6804221535a1c66da49feb8475a1a) to expose the field in the `InstanceInfo` object.

`EC2MetadataUtils#getInstanceInfo` was removed and we're left with no means of fetching the AWS MarketPlace product codes from the instance. As a result, we can't upgrade the software we sell on the AWS MarketPlace.

## Your Environment

Irrelevant

**Comment by debora-ito** [comment]
Hi @slandelle, thank you for reaching out.

The change was not made by accident, those APIs were intentionally removed as part of the Jackson dependency removal. As you mentioned, they were internal APIs, annotated with [@SdkInternalApi](https://github.com/aws/aws-sdk-java-v2/blob/master/core/annotations/src/main/java/software/amazon/awssdk/annotations/SdkInternalApi.java), and the annotation documentation makes clear that breaking changes are expected to occur in elements marked as `@SdkInternalApi`. I'm sorry that the AWS MarketPlace people told you could use that internal utility class, but we don't have the intention to add them back.

That said, we feel the pain of not having another method to obtain the same info. The EC2 Metadata Client (https://github.com/aws/aws-sdk-java-v2/issues/61) is in our backlog and would be the stable substitute. Other options include using the Java SDK v1 [EC2MetadataUtils](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/util/EC2MetadataUtils.java) (reminding that v1 and v2 can be used side-by-side) or forking the SDK and writing back the APIs.

In the meantime please upvote 👍  the original description EC2 Metadata Client feature request in #61 and add a comment describing your use case. We don't have a timeline for it, as we are currently working on other big v1 parity features, but it help us with prioritization.

**Comment by slandelle** [comment]
Hi @debora-ito 

Thanks for your insights.

I've ended implementing my own stuff. But it's definitely not right that customers have to pay for implementing and maintaining their own client **to be able to use services they're paying for**. AWS has definitely the financial means of providing client features for its APIs.

My honest feedback is that for more than 1 year we've upgraded, I've been utterly disappointed with the SDK v2 and regret upgrading. One would expect a v2 to be superior to a v1: less bugs, better design and more features, **not less**. Here, it's definitely not the case, eg:

* no credentials auto-refresh (available in v1)
* non-blocking API is supposed to be the grand new feature of v2 but it lacks proxy support, see #1432 (mentioning for reference, I'm aware you're the one currently reviewing). It looks like it's going to be implemented at last, just sad a billion $ revenue company wasn't able to pull this off and decided to wait for 2 years for an external contribution.
* now this code removal

> we are currently working on other big v1 parity features

THAT! v2 missing features should be highlighted in the documentation, so users are aware of what they are and will be missing when picking v1 or v2. As is, v2 should be flagged as experimental.

> In the meantime please upvote 👍 the original description EC2 Metadata Client feature request in #61 and add a comment describing your use case.

I will. Hopefully it will help. 

> We don't have a timeline for it

Sadly, the lack of visibility on ETA doesn't make me raise my hopes very high.

Regards

**Comment by millems** [comment]
@slandelle Thanks for your honest feedback. I truly appreciate it. 

We've restored this method until #61 can be implemented, but we also recognize that isn't really "the point" of your feedback. We'll continue to try to improve our delivery of features and as well our communication so that you can be happy with your choice to use 2.x.

Please don't hesitate to reach out more if you have any other feedback.
