### ISSUE TITLE
DNS IP resolution failover

### ISSUE THREAD

**Issue by sybeck2k** [aws/aws-sdk-java-v2#2627]
## Describe the Feature
When calling an AWS service, it is possible that the corresponding DNS name of the service returns multiple IPs. The SDK Http clients should retry to use different IP addresses when there are connectivity issues. This would increase reliability of the applications using the SDK.

## Is your Feature Request related to a problem?
For resiliency, DNS returns multiple IP addresses for AWS services. For example, if you deploy a VPC Endpoint for an AWS service in multiple AZs and enable private DNS integration, the DNS name of the service will return 1 IP per AZs. The SDK currently uses a random IP address - and in case of errors with a default retry logic - the SDK will reiterate the request to the same IP address. For example, during an AZ failure it is possible that one IP address returned by the DNS is temporarily out of service. If the retry strategy could also be configured to try a different IP address, this could allow the application to transparently failover.

## Proposed Solution
Some HTTP clients like Apache Http Client allow [some configuration over the DNS resolvers](https://www.javadoc.io/static/org.apache.httpcomponents/httpclient/4.5.8/index.html?org/apache/http/conn/DnsResolver.html) - I need to investigate more, but it could be a way to implement a client-side round-robin DNS resolution.

## Additional Context
During one recent AZ failure, we've experienced a high error count in a Lambda function connecting to an AWS service through the private VPC endpoint. The errors could have been avoided if the SDK tried to connect to ENIs of the VPC Endpoint in healthy AZ. Since the Lambda context is stateful, subsequent executions of the Lambda functions consistently returned errors, as the SDK was always trying to connect to the same (non-working) IP address of the VPC Endpoint of a depending service.

- [X ] I may be able to implement this feature request

## Your Environment
* AWS Java SDK version used: 2.x
* JDK version used: 8/11
* Operating System and version: Lambda on Java 8/11

**Comment by sybeck2k** [comment]
I've tried building a custom `SdkHttpClient` that uses a CloseableHttpClient with a `DnsResolver` that returns one random entry at each call. This allows to have a random IP address from the DNS entries at each retry in case of failure. I've built a test scenario where 1 ENI of my VPC Endpoint is blocked by NACL, and I can confirm that this simple solution reduces effective error rates.

**Comment by debora-ito** [comment]
Hi @sybeck2k, after a quick discussion with the team the conclusion is: yes, the Apache Client provides a DnsResolver configuration (although it's not round-robin) so we suggest its use for now. Don't know how easy it would be to implement this in the other HTTP Clients like Netty and URLConnection, some research is needed. But we see the benefit of having a better reliability. Marking this as a feature request.

**Comment by sybeck2k** [comment]
Thanks @debora-ito - I didn't find a way to provide a DnsResolver to the Apache Client provided in the SDK. The only solution I had was to create a (very basic) custom implementation of the Apache Client. So if you have a hint on how to achieve that it would be great.

I've tested also the NodeJS SDK (v2 and v3) and Boto3 - and I can confirm that they provide this capability out of the box (not sure if this was intended - as there is nothing specific in the SDK code itself)

**Comment by debora-ito** [comment]
@sybeck2k you're right, I didn't check before making my previous reply, only Java SDK v1 [ClientConfiguration](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html#withDnsResolver-com.amazonaws.DnsResolver-) has a DnsResolver setter

**Comment by debora-ito** [comment]
@sybeck2k  

Support for DnsResolver override in the Apache Client was released in `2.17.79` via #2834.

Please try it out and let us know if you have further questions.

**Comment by sybeck2k** [comment]
great job - closing the issue!
