### ISSUE TITLE
storage gateway DescribeCachediSCSIVolumes bug

### ISSUE THREAD

**Issue by kedbirhan** [aws/aws-sdk-java-v2#2632]
DescribeCachediSCSIVolumes API does not include in the response volumes that are detached from the gateway
## Describe the bug

I had two cached volumes for a gateway and one of the volumes is detached from the gateway. when calling DescribeCachediSCSIVolumes providing the arn of the gateway it only returns  volumes that is attached to the API only

## Expected Behavior

it should return both the detached and attached volumes
## Current Behavior

`AwsErrorDetails(errorMessage=Cannot describe volumes of multiple gateways, errorCode=InvalidGatewayRequestException, serviceName=StorageGateway)`

## Steps to Reproduce

create a volume gateway and attach two volumes to it and detach one of the volume. and try to make the following call. 
it will return just the attached volume.

` if(gatewayInfo.gatewayType().equalsIgnoreCase(GateWayType.CACHED.name())){
            List<String> volumeARNs= client.listVolumes(ListVolumesRequest.builder()
                    .gatewayARN(gatewayInfo.gatewayARN())
                    .build()).volumeInfos().stream().map(VolumeInfo::volumeARN).collect(Collectors.toList());
            if(!volumeARNs.isEmpty()){
                return Optional.ofNullable(client.describeCachediSCSIVolumes(DescribeCachediScsiVolumesRequest.builder()
                        .volumeARNs(volumeARNs)
                        .build()).cachediSCSIVolumes());`
## Your Environment

* AWS Java SDK version used:
2.17.5
* JDK version used:
11
* Operating System and version:
MAC OS 10.15

**Comment by kedbirhan** [comment]
never mind,  once a volume is detached its association with the gateway is not valid

**Comment by debora-ito** [comment]
@kedbirhan glad you were able to figure things out. Closing.
