### ISSUE TITLE
DynamoDbExtensionContext information lacks of the Class being read/wrote

### ISSUE THREAD

**Issue by jonathannaguin** [aws/aws-sdk-java-v2#2634]
The DynamoDbExtensionContext class does not offer any information about the object being wrote or read.

## Describe the Feature
The old [Parameters](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/datamodeling/AttributeTransformer.Parameters.html ) class has a `getModelClass()` that returns the Class being serialised by the converter.
This information hasn't been available on the new [Context](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbExtensionContext.Context.html ) which means that extensions can't introspect the class of the object being wrote or read. This is extremely useful when the logic of the operation depends on a annotation for example.

## Is your Feature Request related to a problem?
Described above.

## Proposed Solution
It should be simple by adding a `getModelClass()` to the Context that returns a Class or alternatevly a `getModelType()` that returns an EnhancedType.
I can provide a PR if it's welcome.

## Describe alternatives you've considered
This is a limitation on the SDK.

## Additional Context
We had a converter in SDK1 that was looking at the Class for a particular annotation to decide how we write/read to DynamoDB on a project that we are trying to migrate to SDK2.

## Your Environment
* AWS Java SDK version used: software.amazon.awssdk:dynamodb-enhanced:2.16.92
* JDK version used: 11
* Operating System and version: Mac OS

**Comment by debora-ito** [comment]
Hi @jonathannaguin, 

I'm wondering if it's possible to obtain the info you need via DynamoDbExtensionContext customMetadataObject. As an example, look at the `VersionedRecordExtension` class [here](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java) and see how the `@DynamoDbVersionAttribute` is obtained.

You can check the Overview for more info on Extensions: https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/README.md#using-extensions

**Comment by jonathannaguin** [comment]
Hello @debora-ito , that would return a field that belongs to the class being read/wrote, however we couldn't use it to inspect any nested objects.
For example:
```
@DynamoDbBean
public class Customer {
    @DynamoDbPartitionKey
    public String getId() { ... };
    public void setId(String id) { ... };
    
    public String getName() { ... };
    public void setName(String name) { ... };
    
    public List<Book> getBooks() { ... };
    public void setBooks(List<Book> books) { ... };
}

@DynamoDbBean
public class Book {
    @Something
    String someProp;
}
```

In this case, we want to alter the serialization of the data depending on "@ Something" inside Book when Customer get written or read. If I am not mistaken, I can't do that using `StaticAttributeTag`.

**Comment by dagnir** [comment]
@debora-ito This seems like a reasonable feature request to me. Removing the `needs-review`.

**Comment by jonathannaguin** [comment]
@dagnir  Will a PR be welcomed for this change?

**Comment by jonathannaguin** [comment]
Closing as it's all resolved.
