### ISSUE TITLE
Which SDK should be used to connect S3 server com.amazonaws vs software.amazon.awssdk

### ISSUE THREAD

**Issue by yuzhangyi** [aws/aws-sdk-java-v2#2675]
## Describe the issue
Today it has different S3 SDK in maven, if we just want to connect S3 server to read data, which one should be used?

- The AWS Java SDK for Amazon S3 module holds the client classes that are used for communicating with Amazon Simple Storage Service  https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-s3/1.12.52
	
- Amazon Web Services SDK for JAVA  https://mvnrepository.com/artifact/software.amazon.awssdk/aws-sdk-java/2.17.24

- The Amazon Web Services SDK for Java provides Java APIs for building software on AWS' cost-effective, scalable, and reliable infrastructure products   https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk/1.12.52

At the same time, could you help provide all the dependency list if we use the SDK?

When we directly use Azure Databricks cluster (it has default AWS packages) to run notebook with following settings, it can successfully read data.

![image](https://user-images.githubusercontent.com/44692931/130551943-e0aa2152-2ce6-4a25-b9ea-b5687d2a6abc.png)

## Your Environment
scala: 2.11.12
spark: 2.4.4
IDE: IntelliJ

**Comment by yuzhangyi** [comment]
@debora-ito , thanks for your information. After downloading the software.amazon.awssdk.s3, we find it does not use filesystem to access the S3, it seems like you are using Rest API to get file content, do we have similar SDK like "hadoop-aws" to provide S3A support?
![image](https://user-images.githubusercontent.com/44692931/131276221-cd382ff3-31ee-47ff-b3c6-4f10535174c8.png)

**Comment by debora-ito** [comment]
That's correct, `software.amazon.awssdk:s3` uses the APIs to communicate with S3. 
`S3AFileSystem` is a class from the `hadoop-aws` library, we don't have support for `S3AFileSystem` in the AWS SDK for Java.

**Comment by yuzhangyi** [comment]
@debora-ito , thanks for your information. It seems like I have to use "hadoop-aws" to solve our problem, thanks.

**Comment by debora-ito** [comment]
Great, in this case I'm closing the issue.
