### ISSUE TITLE
Request: S3AsyncClient.putObjectTorrent similar to S3AsyncClient.getObjectTorrent

### ISSUE THREAD

**Issue by alessio-santacroce** [aws/aws-sdk-java-v2#269]
For issue https://github.com/aws/aws-sdk-java-v2/issues/159 the method 'putObjectTorrent' has been implemented to read an s3 file into a byte array asynchronously. 
It would be really useful to have a similar method to write an s3 file from a byte array asynchronously.

What I actually have to do is copying a file from a bucket to another bucket. 
Is it too much asking to have also a method that does the copy asynchronously and start writing the destination file without have to wait that the source file has been read completely?

Many thanks,
Alessio

**Comment by millems** [comment]
We recommend the S3 copy-object API for copying files between buckets, because it does not require a round-trip to the client. 

Tracking this issue in #37
