### ISSUE TITLE
Remove AWS-specific code from the "core" module

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#27]
Clients generated for API gateway customers use the "core" module for transmission and other pieces of core functionality. This means that such clients also pull in AWS-specific functionality, like credential providers, regions, etc. 

These AWS-specific pieces of functionality should be moved to a separate "aws-core" module that depends on "core" so that API gateway clients do not need to include them.

**Comment by zoewangg** [comment]
closed by #475 , #484
