### ISSUE TITLE
DynamoDBSaveExpression alternative in DynamoDBEnhancedClient

### ISSUE THREAD

**Issue by deepak0004** [aws/aws-sdk-java-v2#2712]
Hi Team

I intend to update a record if a certain criterion is met in the initial record, a feature provided in DynamoDBSaveExpression.

```
DynamoDBSaveExpression saveExpression = new DynamoDBSaveExpression();

if (condition) {
    expected.put("timestamp", new ExpectedAttributeValue(false));
} else {
    expected.put("timestamp",
                    new ExpectedAttributeValue(new AttributeValue(123)).withExists(true));
} 
saveExpression.setExpected(expected);
dynamoDBMapper.save(updatedObject, saveExpression);
```

I want to achieve the same in enhanced clients. 

Any leads for the same?

**Comment by debora-ito** [comment]
Hi @deepak0004 apologies for the delay in reply.

There is a `conditionExpression` method in [PutItemEnhancedRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/PutItemEnhancedRequest.Builder.html), [UpdateItemEnhancedRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedRequest.Builder.html) and [DeleteItemEnhancedRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/DeleteItemEnhancedRequest.Builder.html) builders:

```
Expression someExpression = Expression.builder()
                .expression("#a = :b")
                .putExpressionName("#a", "status")
                .putExpressionValue(":b", AttributeValue.builder().s("READY").build())
                .build();

UpdateItemEnhancedRequest.builder()
            .item(myBook)
            .conditionExpression(someExpression)
            .build()
```

Let us know if this helps.

**Comment by deepak0004** [comment]
Thanks for the answer @debora-ito
