### ISSUE TITLE
S3Presigner Adds Metadata Elements as Headers Causing Portability Issues

### ISSUE THREAD

**Issue by iheffernan** [aws/aws-sdk-java-v2#2722]
## Describe the issue
The `S3Presigner` seems to add elements as HTTP request Headers. This results in issues with the portability of the presigned URL if, for example, one wants to provide _just_ the URL and not the entire `PresignedRequest` object to an external. Without access to the original `PresignedRequest` object it's impossible for an external to use the presigned URL and always results in a 403 - SignatureDoesNotMatch.

This appears to contrast with the JavaScript SDK which adds these elements as query string parameters and, as such, makes the resulting presigned URL portable.

Hoping there is a reason for this as I'd like to use the Java SDK, but require the behavior of the JavaScript SDK.

## Steps to Reproduce
Here is a simple unit test to demonstrate the issue...

```
PutObjectRequest.Builder builder = PutObjectRequest.builder()
        .bucket(bucket)
        .key("foo.txt")
        .acl(ObjectCannedACL.BUCKET_OWNER_FULL_CONTROL)
        .storageClass(StorageClass.REDUCED_REDUNDANCY)
        .metadata(Map.of("foo", "bar"));
PutObjectPresignRequest putObjectPresignRequest = PutObjectPresignRequest.builder()
        .putObjectRequest(builder.build())
        .signatureDuration(Duration.ofSeconds(60L))
        .build();
PresignedPutObjectRequest presignedRequest = s3Presigner.presignPutObject(putObjectPresignRequest);

HttpClient httpClient = HttpClient.newHttpClient();
HttpRequest request = HttpRequest.newBuilder(presignedRequest.url().toURI())
        .PUT(HttpRequest.BodyPublishers.ofByteArray("this is a test".getBytes(StandardCharsets.UTF_8)))
        .build();
HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
assertEquals(403, response.statusCode());
```

In this case I'm adding an ACL, Storage Class, and simple Metadata to the PUT request. I'm using the stock Java 11 HttpClient to then try to use the presigned URL to PUT a simple string to S3.

## Current Behavior
It is possible to make this work by repopulating the new HTTP request object with the headers from the `PresignedRequest`, as indicated in the [JavaDocs](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/presigner/S3Presigner.html)

Here's the tweak necessary on the above code to make it work...

```
PutObjectRequest.Builder builder = PutObjectRequest.builder()
        .bucket(bucket)
        .key("foo.txt")
        .acl(ObjectCannedACL.BUCKET_OWNER_FULL_CONTROL)
        .storageClass(StorageClass.REDUCED_REDUNDANCY)
        .metadata(Map.of("foo", "bar"));
PutObjectPresignRequest putObjectPresignRequest = PutObjectPresignRequest.builder()
        .putObjectRequest(builder.build())
        .signatureDuration(Duration.ofSeconds(60L))
        .build();
PresignedPutObjectRequest presignedRequest = s3Presigner.presignPutObject(putObjectPresignRequest);

HttpClient httpClient = HttpClient.newHttpClient();
HttpRequest.Builder reqBuilder = HttpRequest.newBuilder(presignedRequest.url().toURI())
        .PUT(HttpRequest.BodyPublishers.ofByteArray("this is a test".getBytes(StandardCharsets.UTF_8)));

presignedRequest.httpRequest().headers().forEach((key, values) ->
        values.forEach(v -> {
            try {
                reqBuilder.header(key, v);
            } catch (IllegalArgumentException e) {
                // ignore special headers
            }
        })
);
HttpResponse<String> response = httpClient.send(reqBuilder.build(), HttpResponse.BodyHandlers.ofString());
assertEquals(200, response.statusCode());
```

But again, this is only possible if I have access to the original `PresignedRequest` object, which I will not in many situations.

As a comparison, when using the JavaScript SDK v3.27.0 those same ACL, Storage Class, and Metadata elements are converted to query string parameters in the presigned URL when using `getSignedUrl` from `@aws-sdk/s3-request-presigner`. Here's a quick snippet and a lightly edited resulting presigned URL...

```
let params = {
    Bucket: bucket,
    Key: key,
    Metadata: {
        'foo': 'bar'
    },
    ACL: 'bucket-owner-full-control',
    StorageClass: 'REDUCED_REDUNDANCY'
};

const command = new PutObjectCommand(params);
const presignedUrl = await getSignedUrl(s3, command, { expiresIn: 60 });
```
results in...
```
https://<my_bucket>.s3.us-east-1.amazonaws.com/foo.txt
?X-Amz-Algorithm=AWS4-HMAC-SHA256
&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD
&X-Amz-Credential=XXXXXXXXXX%2Fus-east-1%2Fs3%2Faws4_request
&X-Amz-Date=20210916T185743Z
&X-Amz-Expires=60
&X-Amz-Security-Token=XXXXXXXXXX
&X-Amz-Signature=XXXXXX
&X-Amz-SignedHeaders=host
&x-amz-acl=bucket-owner-full-control
&x-amz-meta-foo=bar
&x-amz-storage-class=REDUCED_REDUNDANCY
&x-id=PutObject
```

This approach allows for complete portability of the presigned URL.

Again, looking to see if maybe there's a way to deal with this in Java that I've overlooked.

If this is by design, I would be curious to understand why this deviates from the approach taken in other languages. Thanks...

## Your Environment

* AWS Java SDK version used: 2.16.79
* JDK version used: OpenJDK Runtime Environment Zulu11.48+21-CA (build 11.0.11+9-LTS)
* Operating System and version: MacOS 11.5.2

**Comment by iheffernan** [comment]
A couple additional notes. The presigned PUT request does work/is portable if you remove everything except the bucket and key. For example, here's the same code from above that was getting the 403 signature mismatch. If I simply comment out the ACL, Storage Class, and Metadata directives the request succeeds.

```
PutObjectRequest.Builder builder = PutObjectRequest.builder()
                .bucket(bucket)
                .key("foo.txt");
//                .acl(ObjectCannedACL.BUCKET_OWNER_FULL_CONTROL)
//                .storageClass(StorageClass.REDUCED_REDUNDANCY)
//                .metadata(Map.of("foo", "bar"));
PutObjectPresignRequest putObjectPresignRequest = PutObjectPresignRequest.builder()
        .putObjectRequest(builder.build())
        .signatureDuration(Duration.ofSeconds(60L))
        .build();
PresignedPutObjectRequest presignedRequest = awsService.s3Presigner.presignPutObject(putObjectPresignRequest);

HttpClient httpClient = HttpClient.newHttpClient();
HttpRequest request = HttpRequest.newBuilder(presignedRequest.url().toURI())
        .PUT(HttpRequest.BodyPublishers.ofByteArray("this is a test".getBytes(StandardCharsets.UTF_8)))
        .build();
HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
assertEquals(200, response.statusCode());
```

For reference/comparison, I tried the same using SDK v1.12.62. The `GeneratePresignedUrlRequest` object doesn't allow you to specify an ACL, Storage Class, or much else, so this more closely resembles the example above with those items commented out. With the v1 SDK, the request does succeed...

```
AmazonS3 s3 = AmazonS3ClientBuilder.standard()
                .withCredentials(DefaultAWSCredentialsProviderChain.getInstance())
                .withRegion(Regions.US_EAST_1)
                .build();

Date expiration = new Date();
long expTimeMillis = expiration.getTime();
expTimeMillis += 1000 * 60 * 60;
expiration.setTime(expTimeMillis);
GeneratePresignedUrlRequest presignedRequest = new GeneratePresignedUrlRequest(bucket, "foo.txt")
        .withMethod(HttpMethod.PUT)
        .withExpiration(expiration);

URL url = s3.generatePresignedUrl(presignedRequest);
HttpClient httpClient = HttpClient.newHttpClient();
HttpRequest request = HttpRequest.newBuilder(url.toURI())
        .PUT(HttpRequest.BodyPublishers.ofByteArray("this is a test".getBytes(StandardCharsets.UTF_8)))
        .build();
HttpResponse<String> response = httpClient.send(request, HttpResponse.BodyHandlers.ofString());
System.out.println(response.body());
assertEquals(200, response.statusCode());
```

So, I suppose that modifies the issue to URL portability for a presigned PUT request when specifying any elements beyond the bucket/key.

**Comment by debora-ito** [comment]
Does this example work in your use case? https://github.com/aws/aws-sdk-java-v2/issues/2200#issuecomment-743390102

**Comment by iheffernan** [comment]
Yes, that will work in my use case. Thank you for the quick response and solution.

Apologies that I didn't find that issue myself. I searched issues for '_presign_' and '_presigner_', but that ticket only comes up when searching '_presign**ed**_'

It would be appreciated if the documentation - Java SDK Developer Guide, S3 User Guide, and/or JavaDocs - were updated to reflect this situation. Seems like it is pretty useful.

Maybe in a future release you could add a utility function to `PutObjectPresignRequest.Builder` to allow you to specify metadata being added as Headers or Query String parameters, e.g. `PutObjectPresignRequest.Builder.metadataLocation(MarshallLocation.QUERY_PARAM)`. There aren't any constants defined for these header names and I worry about something changing or getting fat-thumbed and these failing to work down the road.

Otherwise, this will work. Thanks again...
