### ISSUE TITLE
DynamodbVersionAttribute is not honoured in enhanced client

### ISSUE THREAD

**Issue by yrajnis321** [aws/aws-sdk-java-v2#2742]
Optimistic locking not working with enhanced dynamodb client.

## Describe the bug
I am applying     @Getter(onMethod_ = {@DynamoDbVersionAttribute}) on attribute name but enchanced client is not working on this, it is throwing conditon check failed even for first time put request

## Expected Behavior
It should work as V1 DynamodbMapper, Take care of version attribute itself

## Current Behavior
Currently Dynamodb version attribute is not working with SDK2

## Steps to Reproduce
1.Create a DO with attribute
@Getter(onMethod_ = {@DynamoDbVersionAttribute}) 
private String version
2. Try to put a new item 

## Your Environment

* AWS Java SDK version used: AwsJavaSdk-DynamoDb-Enhanced = 2.0;
* JDK version used: JDK8
* Operating System and version: Linux

**Comment by aaoswal** [comment]
Hi @yrajnis321 ,
Thank you for submitting the issue. On looking closely to the information you provided, it seems to be a guidance problem and not a bug.

I noticed that you are using `private String version` to put a new item, however going through the source code https://github.com/aws/aws-sdk-java-v2/blob/ec1f194744bff84ad48d69e05be4c4f40a522403/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/extensions/VersionedRecordExtension.java#L43-L44 it mentions that for utilizing optimistic record locking  the expected `VersionAttribute` value is of numeric type (long or integer) which might be the root cause of your issue.

We will work on making the [DynamoDbVersionAttribute](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/extensions/annotations/DynamoDbVersionAttribute.html) documentation more clear to reflect the same.
Hope this helps and solves the issue you have been facing.

Thanks,
Anish.

**Comment by knuspertante** [comment]
Hey @debora-ito ,

could you please provide a working example for using dynamodb enhanced client, a Table with DynamoDBVersionAttribute annotation? 

In my opinion, currently it also does not work with an integer or long type.

**Comment by debora-ito** [comment]
@knuspertante Sure! Here's an example using a Bean:
```java
@DynamoDbBean
public class CatalogItemWithVersion {

    private Integer id;
    private String title;
    private Long version;

    @DynamoDbPartitionKey
    public Integer getId() {...}
    public void setId(Integer id) {...}

    public String getTitle() {...}
    public void setTitle(String title) {...}

    @DynamoDbVersionAttribute
    public Long getVersion() {...}
    public void setVersion(Long version) {...}
}
```

The first time you add an item, it will be created with version = 1:

```java
DynamoDbEnhancedClient enhancedClient = DynamoDbEnhancedClient.create();
DynamoDbTable<CatalogItemWithVersion> table = enhancedClient.table("CatalogItem", 
        TableSchema.fromBean(CatalogItemWithVersion.class));

CatalogItemWithVersion item = new CatalogItemWithVersion();
item.setId(111);
item.setTitle("The Matrix");
table.putItem(item);
```

Result:
```
{
 "id": 111,
 "version": 1,
 "title": "The Matrix"
}
```

Subsequent changes to the item must include the version, or else the operation will fail. The version value must match the value that is currently in the table.

```java
CatalogItemWithVersion item = table.getItem(Key.builder().partitionValue(111).build());
item.setTitle("The Matrix rulez");
table.putItem(item); //this will work

CatalogItemWithVersion newItem = new CatalogItemWithVersion();
newItem.setId(111);
newItem.setTitle("The Matrix rulez");
table.updateItem(newItem); //this will not work
```

**Comment by knuspertante** [comment]
Hey @debora-ito,

thank you very much! 

My fault was, that I expected the object attributes will be changed as in SDK version 1 (like pass by reference in other languages). 

There I could used the item without to request them again or to use updateItem (which return a new object). 

Is there any possibility to do that in SDK version 2?

**Comment by untaljohanperez** [comment]
Make you to use `DynamoDbVersionAttribute` instead of `@DynamoDBVersionAttribute` 

Wrong Import: 
```
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBVersionAttribute;
```

Right import:
```
package software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbVersionAttribute;
```

**Comment by manojkondisetti** [comment]
> Member

Instead of performing getItem() to get the latest version number which can be used in subsequent updateItem(), can you suggest any way to disable the check while using DynamoDbEnhancedClient.

**Comment by ashwiniabhishek** [comment]
Incase some body is facing this issue while using this SDK in kotlin: Initially when I was using `@get:DynamoDbVersionAttribute
    var ver: Int = 0`, it was failing, but when I made the Int nullable and assigned a null value, it started working e.g. `@get:DynamoDbVersionAttribute
    var ver: Int? = null`

**Comment by suzannebecker-toast** [comment]
@ashwiniabhishek I was having the same issue when inserting a brand new item, and your solution worked for me. Thank you.

**Comment by tuyennta** [comment]
@ashwiniabhishek 's solution worked for me on Java SDK too.

**Comment by eliana404** [comment]
Hmm.. I am using the following in Kotlin:

```kotlin
  @get:DynamoDbVersionAttribute
  @get:DynamoDbAttribute("version")
  var version: Int? = null,
```
Unfortunately, I'm having problems creating records via `putItem` and `PutItemEnhancedRequest`. The client is not auto-populating the version attribute and it remains null.
