### ISSUE TITLE
S3TransferManager Download doesn't include ObjectMetadata

### ISSUE THREAD

**Issue by dbadami** [aws/aws-sdk-java-v2#2774]
### Describe the issue

I'm using the sample code provided to download an object using the `S3TransferManager`:
```
Download download = 
    transferManager.download(b -> b.destination(path)
                                   .getObjectRequest(r -> r.bucket("bucket")
                                                           .key("key")));
CompletedDownload completedDownload = download.completionFuture().join(); // modified by me
```

I'm running into an issue where if I try to get the metadata from the `GetObjectResponse` I get an empty map.

```
Map<String, String> metadata = completedDownload.response().metadata() // empty map
```

I confirmed that the object does have metadata associated with it because I use the S3Client to get the object and its metadata and see the expected result.

### Steps to Reproduce

```
GetObjectRequest request = GetObjectRequest.builder()
                .bucket(bucketName)
                .key(key)
                .build();
            
DownloadRequest downloadRequest = DownloadRequest.builder()
                .destination(file)
                .getObjectRequest(request)
                .build();

Map<String, String> s3ClientMetadata = S3Client.create().getObject(request).response().metadata(); 

Download download = transferManager.download(downloadRequest);
CompletedDownload completedDownload = download.completionFuture().join();

Map<String, String> transferManagerMetadata = completedDownload.response().metadata();
                
```
This is the test code I'd used and saw that the response from the S3Client had the metadata as expected but the response from the S3TransferManager doesn't.

### Current behavior

The response from S3 when using TransferManager doesn't include the metadata as expected.

### AWS Java SDK version used

2.17.61

### JDK version used

openjdk version "11.0.12" 2021-07-20 LTS

### Operating System and version

Mac OSx

**Comment by zoewangg** [comment]
Hi @dbadami thank you for your patience. The fix is available in the latest release, `2.17.81` as of today. Please try it out and let us know if you continue to see the issue.

Note that we have made some refactoring on the Transfer Manager APIs via #2817. You can check out the [README](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/s3-transfer-manager/README.md) to see the code snippet. Please let us know if you have any feedback. :)
