### ISSUE TITLE
Maven pom file with SDK in ec2 instance is not running java code

### ISSUE THREAD

**Issue by nicklaboy** [aws/aws-sdk-java-v2#2784]
### Describe the issue

I wrote out my code in Eclipse and it works completely fine. I am now trying to run the same code in an EC2 instance. The error I am getting is when I want to compile, it is saying:
error: package com.amazonaws.auth does not exist

I have the exact same layout for the pom file in Eclipse as well as in the EC2 instance maven project.

Any help would be great!

### Links

https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/setup-project-maven.html

**Comment by debora-ito** [comment]
@nicklaboy Apologies for the long silence in here. Are you still experiencing the error?

If so, can you share your dependency tree? You can obtain by running `mvn dependency:tree`.
