### ISSUE TITLE
Cannot map a List<>

### ISSUE THREAD

**Issue by jfarjona** [aws/aws-sdk-java-v2#2789]
### Describe the bug

When I use a List<> inside a @DynamoDbBean, I get the error  Class does not appear to be a valid DynamoDb annotated class. [class = "interface java.util.List"].  How can I map Lists, Sets, Maps, Collections in general?

### Expected behavior

Collections should be mapped as arrays...

### Current behavior

Exception is thrown.

### Steps to Reproduce

@DynamoDbBean
public class Company {
    /**
     * The legal name of the company
     */
    private String name;

    /**
     * The main contact.  The id of the main person.
     */
    private List<User> people;
}

@DynamoDbBean
public class User {
   private String name;
}

### AWS Java SDK version used

2.17.65

### JDK version used

11.0.3

### Operating System and version

Win 10

**Comment by debora-ito** [comment]
@jfarjona marking this issue to auto close soon, but feel free to reach out with further questions or concerns.
