### ISSUE TITLE
DynamoDB: Allow to modify globalSecondaryIndexes list in the CreateTableRequest builder

### ISSUE THREAD

**Issue by pieterjanpintens** [aws/aws-sdk-java-v2#279]
I'm trying to use the DynamoDbMapper.generateCreateTableRequest to set up my table for local testing. This provides a good start but it does not fill some of the required properties as described in the documentation of this method. That is it does not fill in provsioned troughput and uses some defaults for projects of sgi.

I hoped that it would be possible to enhance the request by filling in the properties after. But i cannot modify the global secondary indexes created by the mapper. I can add new ones but there is no way to modify existing ones.
``
// in junit setup code
// create the mapper
fMapper = new DynamoDbMapper(gClient);

// ask for its proposition of the table creation code
final CreateTableRequest initialRequest = fMapper.generateCreateTableRequest(Task.class);

// set some default for testing
final ProvisionedThroughput troughPut = ProvisionedThroughput.builder().readCapacityUnits(5L).writeCapacityUnits(5L).build();

// pimp the request so that we have all things required
final Builder request = initialRequest.toBuilder();

request.provisionedThroughput(troughPut);
initialRequest.globalSecondaryIndexes().forEach(c -> {
//this adds this as a new global Index but actually i need to modify the current one but i cannot
	request.globalSecondaryIndexes(c.toBuilder().provisionedThroughput(troughPut).build());
});
``

It would help a lot if the build allowed this. I saw that the actual builder implementation allows this but this is private static class so i cannot use it.

* AWS Java SDK version used: 2.0 beta 1
* JDK version used: Java 8
* Operating System and version: Mac OSX

**Comment by millems** [comment]
Tracking this feature request in #35

As some background, we're backing off of heavy control-plane support in the SDK hand-written libraries for now as we believe the [AWS CDK](https://github.com/awslabs/aws-cdk) can do it much better than us. That said, we know there's still value in doing this in the SDK.
