### ISSUE TITLE
Refactor: Signers

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#28]
Review the inherited state of V1 signers and determine which changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by amihaiemil** [comment]
Big outlines, about signing the HTTP requests: 

  * The signer (e.g. Aws4Signer) should be a decorator for a HTTP request object. 
  * Less injection through setters, in favor of injection through the ctor (less configurable objects)
  * Better encapsulation of classes which require a lot of knowledge about the SDK (e.g. classes such as ``ExecutionContext``)

I wrote a post about it [here](http://www.amihaiemil.com/2017/02/18/decorators-with-tunnels.html). Any effort towards a similar, composable design, based on interfaces, would be an advance, from my point of view.

**Comment by shorea** [comment]
Implemented
