### ISSUE TITLE
S3AsyncClient netty issue 

### ISSUE THREAD

**Issue by snehal-kolte** [aws/aws-sdk-java-v2#2832]
### Describe the issue

java.lang.NoClassDefFoundError: io/netty/bootstrap/FailedChannel at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:320) ~[task/:?]at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:155) ~[task/:?]at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:116) ~[task/:?]at io.netty.channel.pool.SimpleChannelPool.connectChannel(SimpleChannelPool.java:267) ~[task/:?]at io.netty.channel.pool.SimpleChannelPool.acquireHealthyFromPoolOrNew(SimpleChannelPool.java:177) ~[task/:?]at io.netty.channel.pool.SimpleChannelPool.acquire(SimpleChannelPool.java:162) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.HonorCloseOnReleaseChannelPool.acquire(HonorCloseOnReleaseChannelPool.java:50) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.IdleConnectionCountingChannelPool.acquire(IdleConnectionCountingChannelPool.java:78) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.utils.BetterFixedChannelPool.acquire0(BetterFixedChannelPool.java:187) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.utils.BetterFixedChannelPool.acquire(BetterFixedChannelPool.java:144) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.acquire0(HttpOrHttp2ChannelPool.java:86) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.http2.HttpOrHttp2ChannelPool.lambda$acquire$0(HttpOrHttp2ChannelPool.java:75) ~[task/:?]at software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils.lambda$doInEventLoop$3(NettyUtils.java:163) ~[task/:?]at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[task/:?]at io.netty.util.concurrent.PromiseTask.run(PromiseTask.java:106) ~[task/:?]at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[task/:?]at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469) ~[task/:?]at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[task/:?]at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[task/:?]at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[task/:?]at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_312]
--
thrown.cause.cause.localizedMessage | io/netty/bootstrap/FailedChannel
thrown.cause.cause.message | io/netty/bootstrap/FailedChannel

### Steps to Reproduce

Use dependencies below 

   "com.amazonaws" % "aws-java-sdk-core" % "1.12.100",
    "org.scala-lang.modules" %% "scala-java8-compat" % "1.0.2",
    "software.amazon.awssdk" % "s3" % "2.17.71",
    "io.netty" % "netty-all" % "4.1.68.Final",
    "io.netty" % "netty-transport" % "4.1.68.Final",

and try to s3.putObjectTagging(putObjectTaggingRequest) for more than 1000k s3 objects 

  private val httpClient = NettyNioAsyncHttpClient
    .builder()
    .connectionMaxIdleTime(Duration.ofSeconds(180))
    .connectionAcquisitionTimeout(Duration.ofSeconds(60))
    .connectionTimeout(Duration.ofSeconds(120))
    .maxConcurrency(1000)
    .build()

  private val s3 = S3AsyncClient.builder.httpClient(httpClient).build

### Current behavior

java.lang.NoClassDefFoundError: io/netty/bootstrap/FailedChannel 

### AWS Java SDK version used

    "com.amazonaws" % "aws-java-sdk-core" % "1.12.100",

### JDK version used

scalaVersion := "2.12.10"

### Operating System and version

Windows

**Comment by debora-ito** [comment]
@snehal-kolte `NoClassDefFoundError` indicates some runtime incompatibilities on the version of the netty. The stacktrace shows `software.amazon.awssdk.http.nio.netty.internal.utils.NettyUtils` so the error is coming from the SDK 2.x.

Can you provide the gradle dependency tree?

**Comment by snehal-kolte** [comment]
@debora-ito Thank you for your response. 
[dependencyTree.txt](https://github.com/aws/aws-sdk-java-v2/files/7517875/dependencyTree.txt)

**Comment by snehal-kolte** [comment]
@debora-ito Did you get a chance to look into this issue?

 "com.fasterxml.jackson.core" % "jackson-databind" % "2.13.0",
    "org.scala-lang.modules" %% "scala-java8-compat" % "1.0.2",
    "software.amazon.awssdk" % "s3" % "2.17.81",
    "software.amazon.awssdk" % "netty-nio-client" % "2.17.81",

**Comment by snehal-kolte** [comment]
Any update on this issue? cc @debora-ito

**Comment by debora-ito** [comment]
@snehal-kolte I'm sorry for loosing track of this. Are you still seeing the error?

The `io.netty.bootstrap.FailedChannel` class is present in the `io.netty:netty-transport` dependency, which is included in `software.amazon.awssdk" % "netty-nio-client` - 
https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/netty-nio-client/pom.xml

So there's something weird going on in your classpath. Please check for any dependency version mixes or conflicts with other libraries that use netty.
