### ISSUE TITLE
Exceptions raised by Cognito are not Serializable

### ISSUE THREAD

**Issue by mishka81** [aws/aws-sdk-java-v2#2852]
### Describe the bug

Hi, 

I have an issue with the SDK version 2.17.56, using the "AdminLinkProviderForUser" action.
Exception raised by the SDK is not serializable (in particular objects of class "UnmodifiableMapOfLists", see attached capture).
The consequence is such exceptions cannot be propagated in an EJB environment (through Remote interfaces).
We use a lot the SDK 1.x in our application (mostly S3 and Cognito services) and we never encountered such an error.

Is this a bug, or AWS exceptions of SDK 2.x are not meant to be serializable ?

Thanks in advance for you support.

![2021-11-10+14_37_49-N9-7+-+org jboss marshalling cloner SerializingCloner+-+D__Git_workspace_N9-7+-+](https://user-images.githubusercontent.com/2773527/142013106-f7b39c8c-bf83-435f-adf6-28880fd61dbb.png)

### Expected behavior

Exceptions raised should be serializable in order to catch them in an EJB environment and pass it through remote interfaces.

### Current behavior

NotSerializableException is raised by the EJB container when propagating the exception.

### Steps to Reproduce

In a remote EJB :
- call the "AdminLinkProviderForUser" service with an invalid source provider, "InvalidParameterException" is raised and not serializable.

Same thing can be done in a standalone environmenent, catching the exception an trying to serialize it manually.

### AWS Java SDK version used

2.17.56

### JDK version used

1.8.x

### Operating System and version

Windows 10 Pro

**Comment by debora-ito** [comment]
Taking a look.

**Comment by debora-ito** [comment]
Not able to reproduce locally. Using the sample code below, I was expecting to see a serialization error in the catch:

```java
try {
    client.adminLinkProviderForUser(c -> c.userPoolId(USER_POOL_ID)
        .sourceUser(u -> u.providerAttributeName("NameId").providerAttributeValue("xxxx_account").providerName("Provider1"))
        .destinationUser(d -> d.providerAttributeName("Identity").providerAttributeValue("user").providerName("Provider2"))
     );
}
catch (InvalidParameterException e) {
    Map<String, List<String>> headers = e.awsErrorDetails().sdkHttpResponse().headers();
    System.out.println(headers);
}
```

The headers were printed out:

> 2021-11-18 13:08:59 [main] DEBUG software.amazon.awssdk.request:84 - Received error response: software.amazon.awssdk.services.cognitoidentityprovider.model.InvalidParameterException: SourceProviderName must match a Provider that is configured for the User Pool (Service: CognitoIdentityProvider, Status Code: 400, Request ID: xxx, Extended Request ID: null)
{Connection=[keep-alive], Content-Length=[128], Content-Type=[application/x-amz-json-1.1], Date=[Thu, 18 Nov 2021 21:08:59 GMT], x-amzn-ErrorMessage=[SourceProviderName must match a Provider that is configured for the User Pool], x-amzn-ErrorType=[InvalidParameterException:], x-amzn-RequestId=[b533b027-169f-4948-9c8e-5829852ff339]}

You said you can see the same error in a standalone environment, not in EJB. Can you share a repro code?

**Comment by mishka81** [comment]
@debora-ito, to reproduce in an EJB environment the code must be put in an EJB remote method, and called from a remote client (in my case client is in the same JVM).
Serialization is done by the EJB container when calling that method from the remote client, both parameters / exceptions eventually thrown are serializeed.

In a standalone environment sorry I did not reproduce but I assume there is the same problem, if you serialize the exception manually with ObjectOutputStream.writeObject(e).

**Comment by debora-ito** [comment]
@mishka81 since I can't repro locally my guess is probably some classpath or JDK misconfiguration in the EJB container or some other environmental issue. Unless you can provide a code sample I can use to repro locally I don't think I'm able to help.
