### ISSUE TITLE
Missing methods in the CopyObjectRequest builder

### ISSUE THREAD

**Issue by hectorvent** [aws/aws-sdk-java-v2#2860]
### Describe the bug

Missing two methods in the builder:
```
 builder.sourceBucket("source-bucket");
 builder.sourceKey("test-documents/test.pdf");
```

I following the documentation from [here](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/CopyObjectRequest.Builder.html) , I created this:

```
CopyObjectRequest copyObjectRequest = CopyObjectRequest.builder()
           .destinationBucket("destination-bucket")
           .destinationKey("documents/test.pdf")
           .sourceBucket("source-bucket")
           .sourceKey("test-documents/test.pdf")
           .build();
```

### Expected behavior

Be able to set `source bucket and key`.

### Current behavior

missing methods in the version `<aws.java.sdk.version>2.15.0</aws.java.sdk.version>`

### Steps to Reproduce

1. Try the version I specified
2. Create this code:
```
CopyObjectRequest copyObjectRequest = CopyObjectRequest.builder()
           .destinationBucket("destination-bucket")
           .destinationKey("documents/test.pdf")
           .sourceBucket("source-bucket")
           .sourceKey("test-documents/test.pdf")
           .build();
```

### Possible Solution

Add missing methods

### AWS Java SDK version used

2.15.0

### JDK version used

openjdk 11.0.10 2021-01-19

### Operating System and version

MacOs Catalina, 10.15.7

**Comment by Bennett-Lynch** [comment]
Hi @hectorvent. Support for these parameters was added as part of https://github.com/aws/aws-sdk-java-v2/pull/2612, which was released in version 2.17.3 on 2021-07-22.

**Comment by hectorvent** [comment]
Thanks @Bennett-Lynch

**Comment by debora-ito** [comment]
Let us know if you have any other question.
