### ISSUE TITLE
S3 Transfer Manager doesn't support bucket names with dots (.). 

### ISSUE THREAD

**Issue by anca-jalbum** [aws/aws-sdk-java-v2#2864]
### Describe the bug

When using the S3TransferManager (preview) with a bucket containing the dot char, for example "foo.bar", you get an error.

### Expected behavior

Using a bucket with dots should work, as that is a valid character in bucket names.

### Current behavior

The error you get is:

`Caused by: software.amazon.awssdk.crt.s3.CrtS3RuntimeException: Retry cannot be attempted because the maximum number of retries has been exceeded. AWS_IO_MAX_RETRIES_EXCEEDED(1069) 	at com.amazonaws.s3.S3NativeClient$1.onFinished(S3NativeClient.java:206)`

The real cause is a TLS (SSL) negotiation error. The library apparently tries to use the access point:
https://[bucketname].s3.[region].amazonaws.com
This works fine for bucketnames without dots, since the SSL certificate is tied to *.s3.[region].amazonaws.com.
With a dot (or any number of dots) the domain no longer matches the SSL certificate and the connection can't be established.

The fact that you only get a very generic error makes the cause of the error very difficult to find. Severe errors like these must be propagated all the way to the caller!

### Steps to Reproduce

Create a bucket with a dot and try to use it with the S3TransferManager.

### Possible Solution

The standard AWS Java v2 SDK (and every other tool I've used) work fine using the "dotted" bucket names, so there must be a solution for this.

### AWS Java SDK version used

2.17.75

### JDK version used

1.8

### Operating System and version

MacOS 11.6.1

**Comment by debora-ito** [comment]
Hi @anca-jalbum thank you for reporting. We'll work on a fix.
