### ISSUE TITLE
UrlConnectionHttpClient not working

### ISSUE THREAD

**Issue by Samrose-Ahmed** [aws/aws-sdk-java-v2#2870]
### Describe the bug

Following https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/lambda-optimize-starttime.html , I tried to use UrlConnectionHttpClient. After adding it to my dependencies and using it in one DDB client explicitly, another SQS client (without explicitly specifying any .httpClient in builder) started using this client and just hanged infinitely on ReceiveMessage call. After removing the dependency, the issue went away.

### Expected behavior

SQS receiveMessage should work.

### Current behavior

Hanging infinitely on SQS receiveMessage call.

### Steps to Reproduce

Add dependency
```
implementation("software.amazon.awssdk:url-connection-client:2.17+")
```
Run
```
val sqsClient: SqsClient = SqsClient.create()
val request = ReceiveMessageRequest.builder()
  .queueUrl(QUEUE_URL)
  .visibilityTimeout(6000)
  .waitTimeSeconds(3)
  .maxNumberOfMessages(10)
  .build()
val response = sqsClient.receiveMessage(request)
println("done")
```

Never gets to last line, hangs on receiveMessage.

### AWS Java SDK version used

2.17.88

### JDK version used

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Corretto-11.0.13.8.1 (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.13.8.1 (build 11.0.13+8-LTS, mixed mode)

### Operating System and version

Ubuntu 20.04.2 LTS (WSL2)

**Comment by debora-ito** [comment]
Hi @Samrose-Ahmed thank you for reaching out.

A client will only use the UrlConnectionHttpClient if specified in the .httpClient option, so the hang can be related to something else.

- Are you removing the Apache Http Client from the depedencies? Can you share your build.gradle? 
- Do you see any errors in the log?

**Comment by Samrose-Ahmed** [comment]
I am not removing the apache http client from my dependencies. 

My entire build.gradle is 

<details>
  <summary>1: build.gradle.kts</summary>
dependencies {
    implementation("org.slf4j:slf4j-simple:1.7.30")

    implementation("org.apache.httpcomponents:httpclient:4.5+")
    implementation("org.apache.httpcomponents:fluent-hc:4.5+")
    implementation("software.amazon.awssdk:dynamodb:2.17.+")
    implementation("software.amazon.awssdk:dynamodb-enhanced:2.17+")
    implementation("software.amazon.awssdk:url-connection-client:2.17+")
    implementation("com.amazonaws:aws-java-sdk-s3:1.12+")
    implementation("software.amazon.awssdk:s3:2.17.+")

    implementation ("com.fasterxml.jackson.core:jackson-core:2.13.0")
    implementation ("com.fasterxml.jackson.core:jackson-annotations:2.13.0")
    implementation ("com.fasterxml.jackson.core:jackson-databind:2.13.0")
    implementation ("com.fasterxml.jackson.module:jackson-module-kotlin:2.13.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.13.0")

    implementation("io.javalin:javalin:4.1.+")
    implementation("com.amazonaws.serverless:aws-serverless-java-container-core:1.6")
}
</details>

and

<details>
  <summary>2: build.gradle.kts</summary>
dependencies {
    implementation(project(":ATCommon"))
    implementation("org.slf4j:slf4j-simple:1.7.32")

    implementation("com.amazonaws:aws-java-sdk-s3:1.11.213") // for S3EventNotification class
    implementation("software.amazon.awssdk:dynamodb:2.17.+")
    implementation("software.amazon.awssdk:dynamodb-enhanced:2.17.+")
    implementation("software.amazon.awssdk:sqs:2.17.+")
    implementation("software.amazon.awssdk:s3:2.17.+")
}
</details>

where the second depends on the first. Removing the line:
```
implementation("software.amazon.awssdk:url-connection-client:2.17+")
```
fixed the issue.

I ran several times but I would not see any logs. I added a print before and after the receive message call and it would never get to the second print.

**Comment by debora-ito** [comment]
Can you enable the DEBUG logs or the wire logs and provide the logs of when the error occur? 
I understand you don't see any errors in the logs, but I'm hoping the DEBUG logs can give us additional info.
See instructions on how to enable the logs here: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-request-response

**Comment by Samrose-Ahmed** [comment]
So I figured it out. I don't know why the error was being swallowed originally but I was reproducing it and got it to output an error, something like "multiple http implementations detected"

I was able to resolve the issue by explicitly specifying the http client to apache when instantiating all clients.

**Comment by debora-ito** [comment]
Glad you are not blocked by this anymore.
In this case I'm closing this. Feel free to reach out if you have other questions.
