### ISSUE TITLE
Support withForceGlobalBucketAccessEnabled like aws-sdk-java-v1

### ISSUE THREAD

**Issue by pkgonan** [aws/aws-sdk-java-v2#2871]
### Describe the feature

Support withForceGlobalBucketAccessEnabled like aws-sdk-java-v1. (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#withForceGlobalBucketAccessEnabled-java.lang.Boolean-)

### Is your Feature Request related to a problem?

We have to separate client each s3 regions.

### Proposed Solution

Support withForceGlobalBucketAccessEnabled feature like aws-sdk-java-v1. (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Builder.html#withForceGlobalBucketAccessEnabled-java.lang.Boolean-)

### Describe alternatives you've considered

We consider using aws-sdk-java-v1, not v2.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.17.89

### JDK version used

11

### Operating System and version

Amazon Linux

**Comment by pkgonan** [comment]
@debora-ito Hi. Please check this feature request.

**Comment by debora-ito** [comment]
Hi @pkgonan this is related to the cross-region S3 client feature parity, which we are tracking here: https://github.com/aws/aws-sdk-java-v2/issues/52

I'll go ahead and close this, you can keep track of the progress in the other issue.
