### ISSUE TITLE
Please add DynamoDBLocal 1.16.0 artifact to repo.maven.apache.org/maven2

### ISSUE THREAD

**Issue by texlnghorn** [aws/aws-sdk-java-v2#2874]
### Describe the issue

We use the DynamoDBLocal library to unit test our dynamodb operations with the DynamoDBEmbedded object.  We have started to migrate to aws sdk v2 but DynamoDBLocal 1.15.0 that is available in repo.maven.apache.org/maven2 does not support aws sdk v2.  DynamoDBLocal 1.16.0 that is available in nexus.pentaho.org/content/groups/omni/ repo does support aws sdk v2.  However my organization does not support adding artifacts to our internal artifactory from nexus.pentaho.org.  Would it be possible to also include DynamoDBLocal 1.16.0 on repo.maven.apache.org?

### Steps to Reproduce

NA

### Current behavior

NA

### AWS Java SDK version used

aws sdk v2

### JDK version used

openjdk 11.0.2

### Operating System and version

macos 11.6

**Comment by texlnghorn** [comment]
I'm closing this issue because I see that 1.16.0 and 1.17.0 are available in the https://s3-us-west-2.amazonaws.com/dynamodb-local/release/ repo.

**Comment by debora-ito** [comment]
@texlnghorn for more info you can check the DynamoDB Local Developer Guide - https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

**Comment by texlnghorn** [comment]
> https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.DownloadingAndRunning.html

Thank you.  I did stumble across that page which is the main reason I closed this ticket.  What I'm still trying to do is figure out where my organization pulls in the artifacts to our internal artifactory.  I think we might just have a reference to where the artifacts live but we aren't referencing version 1.17.0.

**Comment by texlnghorn** [comment]
@debora-ito my admins create remote repositories to external dependencies in our companies artifactory.  They are telling me they cannot create a remote repository to https://s3-us-west-2.amazonaws.com/dynamodb-local/release/.  Do you know if this is possible?
