### ISSUE TITLE
Request ID missing in DEBUG logs

### ISSUE THREAD

**Issue by rohitnair** [aws/aws-sdk-java-v2#2876]
### Describe the bug

As per the docs, enabling DEBUG level logs for the "software.amazon.awssdk.request" package should log request IDs. However, I don't see them even after enabling and the example log output doesn't show it either. Based on my very high level code search, it seems that only response code is logged, which matches what I'm seeing in the logs - https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/http/CombinedResponseHandler.java#L96

Compare this to the SDK v1 code where it does seem like we used to log request IDs - https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/response/AwsResponseHandlerAdapter.java#L85-L87

Again, the above code pointers are just based on a quick search and may not even be accurate/relevant, so please double check. 

### Expected behavior

Request IDs should be logged since the docs clearly say - "AWS request IDs...can also be reported through the DEBUG log level in the "software.amazon.awssdk.request" logger". In addition to that, this behavior looks like a regression compared to SDK v1 behavior. 

### Current behavior

Sample logs seen on application below
`
DEBUG request - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=https, host=dynamodb.us-west-2.amazonaws.com, encodedPath=/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target, X-Amzn-Trace-Id], queryParameters=[])
--
DEBUG request - Received successful response: 200
`

### Steps to Reproduce

Enable DEBUG logs for "software.amazon.awssdk.request" package and make a call to an AWS service. 

### Possible Solution

Update the code to log request ID. 

### Context

Having request IDs is invaluable to follow up with AWS service teams on any potential issues with specific API calls. 

### AWS Java SDK version used

2.16.81

### JDK version used

Java 11 (Corretto)

### Operating System and version

AWS Lambda runtime

**Comment by zoewangg** [comment]
Apologies for the delayed response and thank you for reporting the issue. We will work on the fix

**Comment by zoewangg** [comment]
Hi @rohitnair the issues has been pushed in the latest release. Please let us know if you continue to experience the issue.

Note that you can use request ID logger `software.amazon.awssdk.requestId` directly if you only need request ID https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/SdkStandardLogger.java#L43
