### ISSUE TITLE
Use individual parameters instead of request objects

### ISSUE THREAD

**Issue by cjkent** [aws/aws-sdk-java-v2#288]
The use of request objects for every operation is not idiomatic Java and makes the AWS SDKs unlike every other Java library I've ever used. Is there a compelling reason not to use individual method parameters?

**Comment by millems** [comment]
Would you expect to have method parameters for all operations, or just ones that have a single required parameter (eg. `s3.createBucket("BucketName")`)?

All operations would be tricky because some operations have a large number of options, most of which are optional (eg. S3's `PutObjectRequest` has 25 options with only 3-4 of them being required).

We've already removed the requirement to specify a request object when there are zero required parameters (eg. `dynamodb.listTables()`), and have discussed adding them when there's only one required paramteer (eg. `s3.createBucket("BucketName")`) but haven't yet made a decision on that front.

Could you give us a link to a service client you like that doesn't use request objects? We'd be interested in seeing what you find more familiar.

**Comment by cjkent** [comment]
I would expect to see individual parameters in any method where all parameters are required. I don't see there's an important distinction between methods with one parameter and methods with more than one.

If there are a small number of optional parameters I'd expect to see overloaded versions of the method.

If there are a large number of optional parameters then it seems reasonable to have a parameter object.

Most Java libraries I've ever used follow the pattern I've just described. Here are some random examples:

https://docs.oracle.com/javase/8/docs/api/java/sql/Connection.html
Multiple overloads of `createStatement`, `prepareCall`, `prepareStatement`

https://docs.oracle.com/javaee/7/api/javax/jms/ConnectionFactory.html
Contains six methods which are all overloads of only two operations, `createConnection` and `createContext`.

https://googlecloudplatform.github.io/google-cloud-java/0.30.0/apidocs/com/google/cloud/storage/Storage.html
Google's API to their S3 equivalent. It uses parameter objects where necessary (e.g. `BlobInfo`). But doesn't use it where there are only a few parameters. Also uses overloading for many operations.

**Comment by millems** [comment]
JavaSE's `Connection` and `ConnectionFactory`'s equivalents would be difficult to nail down with the way we do our service clients today.

It would mean we'd have to model the nouns as classes and put the verbs on them:
```Java
DynamoDbTable table = DynamoDbTable.builder()
                                   .tableName("myTable")
                                   .provisionedThroughput(10)
                                   .build();

table.create();
table.waitForExists();
```

I actually really like this kind of API, but the way we model our service APIs today (via [service model files](https://github.com/aws/aws-sdk-java-v2/blob/master/services/dynamodb/src/main/resources/codegen-resources/dynamodb/service-2.json)) doesn't allow for that level of detail. 

We've done some of these APIs before. In 1.11.x we have the dynamo DB documents API that does something similar to the example above: https://aws.amazon.com/blogs/developer/introducing-dynamodb-document-api-part-1/

Unfortunately we have to hand-write these APIs, so managing a large number of them is challenging.

The `Storage` API you linked is closer to the model we used in 1.11.x and are moving towards with 2.x. If there's a small number of required parameters: don't require the request object. We never add required fields to an existing API, so it won't make the API 'out of date' over time. 

We're more nervous about doing them for optional arguments. Even if the API currently only has one or two (which is actually fairly rare), we're adding [dozens of optional arguments every week](https://github.com/aws/aws-sdk-java/blob/master/CHANGELOG.md). We already have a ton of methods on our clients, so we're trying to be careful about going too crazy with it.

This discussion is a good datapoint that we could use more of these.

**Comment by millems** [comment]
We'll take this feedback into account when we're writing the high-level libraries for dynamo DB, S3, etc. Thank you!
