### ISSUE TITLE
Setting max conenctions on LambdaAsyncClient

### ISSUE THREAD

**Issue by JuanchiRios** [aws/aws-sdk-java-v2#2881]
### Describe the issue

I couldn't find how to set the max connections on an AsyncLambdaClient. If I understood correctly the default is 50 but I'd like to change it.

### Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/lambda/LambdaAsyncClient.html

**Comment by debora-ito** [comment]
Hi @JuanchiRios you can customize the max connections in the NettyNioAsyncHttpClient builder:
```java
        LambdaAsyncClient lambdaAsyncClient = LambdaAsyncClient.builder()
                .httpClientBuilder(NettyNioAsyncHttpClient.builder()
                        .maxConcurrency(100))
                .build();
```

Check the NettyNioAsyncHttpClient doc for more setting options: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.Builder.html

**Comment by JuanchiRios** [comment]
@debora-ito thanks!!
