### ISSUE TITLE
I cannot find proxy setting to S3Client

### ISSUE THREAD

**Issue by xenogew** [aws/aws-sdk-java-v2#2890]
### Describe the issue

I tried Google how to set proxy but found only example of SDK version 1, and searched inside Java Dev guide of AWS and didn't find any related for what I'm searching.

### Steps to Reproduce

include dependencies of 
software.amazon.awssdk:bom-2.17.91
software.amazon.awssdk:s3-2.17.91

### Current behavior

Couldn't find `ClientConfigutation` class or `ProxyConfiguration.Builder` class

### AWS Java SDK version used

software.amazon.awssdk:2.17.91

### JDK version used

11

### Operating System and version

Windows 10 Update 21H1

**Comment by debora-ito** [comment]
Hi @xenogew,

Proxy configuration is now done in the httpClientBuilder:
```java
        ProxyConfiguration.Builder proxyConfig =
                ProxyConfiguration.builder()
                        .endpoint(ENDPOINT)
                        .username(USERNAME)
                        .password(PASSWORD);
        
        DynamoDbClient client = DynamoDbClient.builder()
                        .httpClientBuilder(ApacheHttpClient.builder()
                                            .proxyConfiguration(proxyConfig.build()))
                        .build();
```

If you are migrating from SDK 1.x to 2.x, this changelog page will help, it shows the changes made from version 1.x and the equivalent operations in 2.x: 
https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md

Good callout on the missing examples in the Developer Guide, I will pass this to our documentation team.

Let us know if you have any other question.
