### ISSUE TITLE
Suppot mocking of s3ClientConfiguration to build S3TransferManager for unit test Java

### ISSUE THREAD

**Issue by balajikarthickkbk** [aws/aws-sdk-java-v2#2898]
### Describe the issue

am using java aws sdk v2 S3TransferManager to upload files to s3.

 At the moment am mocking  **s3ClientConfiguration** using  mockito 2.0 as below,

`
       S3ClientConfiguration s3ClientConfiguration =mock(S3ClientConfiguration.class);

       s3TransferManager = S3TransferManager.builder().s3ClientConfiguration(s3ClientConfiguration).build();
`

 which throws me the error,

 `**java.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: Invalid response status from request**`

This is my actual code which contains the method **transferobject** for which am writing the unit test,
![image](https://user-images.githubusercontent.com/95723030/145127488-0c097ad0-398c-4e8a-a645-87f70c1e79e0.png)

and this is my unit test code,

![image](https://user-images.githubusercontent.com/95723030/145127670-38784275-6fcd-4188-887f-89a1257feddd.png)

and this is my exception,
![image](https://user-images.githubusercontent.com/95723030/145127712-1c245c02-9de0-40ca-b086-cb8184ee70c5.png)

so what is the solution to figure out what the root cause is? or what is the right way to mock "S3ClientConfiguration"  for unit test in java using aws sak v2.

Help is appreciated. Thank you.

### Steps to Reproduce

See snippet above

### Current behavior

unit test fails due to the exception, **ava.util.concurrent.CompletionException: software.amazon.awssdk.services.s3.model.S3Exception: Invalid response status from request** 

### AWS Java SDK version used

V2

### JDK version used

1.8

### Operating System and version

Windows

**Comment by zoewangg** [comment]
Hi @balajikarthickkbk, currently it's not supported to swap out the underlying S3 client used by the transfer manager, so it looks like your test is actually sending requests to S3. Marking this as a feature request. Would mocking S3TransferManager work in your use-case?

**Comment by balajikarthickkbk** [comment]
have tried mocking s3Transfermanager but it returns only Nullpointerexception,

 ![image](https://user-images.githubusercontent.com/95723030/145138526-4107c5b2-b110-4749-a709-3434a9a821e0.png)
**unit tes tcode where I have mocked  S3TransferManager,**

![image](https://user-images.githubusercontent.com/95723030/145138291-492e33c7-1e49-48cd-a19f-2375c0bb4ebc.png)

**the Null Pointer Exception in actual code when I mock S3TransferManager*,*

![image](https://user-images.githubusercontent.com/95723030/145138526-4107c5b2-b110-4749-a709-3434a9a821e0.png)
![image](https://user-images.githubusercontent.com/95723030/145138598-7a567ea2-572a-42ee-b9d0-f320558f6616.png)

so if mocking of s3ClientConfiguration is not supported now, how could we unit test S3TransferManager upload functionality, 
is that we need to unit test against actual S3-bucket by passing the actual credentials in unit test and not a mocked one?

**Comment by balajikarthickkbk** [comment]
Hi @zoewangg any update on my previous question?

**Comment by zoewangg** [comment]
I believe you would need to mock the response of the `S3TransferManager#uploadFile`, see sample code below.

```java
        S3TransferManager s3TransferManager = Mockito.mock(S3TransferManager.class);
        FileUpload fileUpload = Mockito.mock(FileUpload.class);
        UploadFileRequest uploadRequest = UploadFileRequest.builder()
                                                           .putObjectRequest(PutObjectRequest.builder().bucket("bucket").key(
                                                               "key").build())
                                                           .source(Paths.get("."))
                                                           .build();
        Mockito.when(s3TransferManager.uploadFile(uploadRequest)).thenReturn(fileUpload);
```

**Comment by balajikarthickkbk** [comment]
Thanks @zoewangg this helps in testing the upload functionality of S3TransferManager, However the actual method which am testing returns null when I mock S3TransferManager,
 
my actual method,

![image](https://user-images.githubusercontent.com/95723030/145291692-cce9922e-53d0-4230-84b9-915f03272750.png)
 
test code,

![image](https://user-images.githubusercontent.com/95723030/145291884-16cc2284-121e-4dc9-94a8-a0028bc0d71d.png)

**Comment by zoewangg** [comment]
It seems the UploadRequest mocked in the `Mokito.when(s3TrasnferManager.upload(uploadRequest)).thenReturn(fileUpload)` is not the same as the actual UploadRequest being used.

Could you make sure the request parameters are the same?

**Comment by balajikarthickkbk** [comment]
have made both the  UploadRequest mocked in the Mokito.when(s3TrasnferManager.upload(uploadRequest)).thenReturn(fileUpload) and actual UploadRequest being used parameters as same now,

![image](https://user-images.githubusercontent.com/95723030/145302343-522dcce7-6260-4a56-9d1a-1af206dd6db3.png)

but still null pointer exception occurs in this line,  **CompletedUpload completedUpload = upload.completionFuture().join();** in my actual  method as seen below,

![image](https://user-images.githubusercontent.com/95723030/145302036-324d2bb5-88ae-4bd8-ba39-9e63920e984f.png)

any final advice on this?

**Comment by zoewangg** [comment]
Yeah, I think you would need to mock the response of  `Upload#completionFuture` as well. Basically, you need to write the expected behavior for the method that returns for the mocked object because unstubbed methods return null by default You can find more information on the official mockito site https://javadoc.io/doc/org.mockito/mockito-core/2.28.2/org/mockito/Mockito.html
