### ISSUE TITLE
AWS SDK for Java v2 Performance

### ISSUE THREAD

**Issue by msailes** [aws/aws-sdk-java-v2#2923]
### Describe the issue

The AWS SDK for Kotlin is in alpha release. It has a native HTTP client which seems to give an impressive improvement to Lambda cold start latency. Are there any similar plans to do this with the Java SDK?

For example, a function which connects to DynamoDB and calls getItem:

With the Java SDK on the Java 11 managed runtime with 2GB of memory you would have a cold start latency of ~3 seconds.
With the Kotlin SDK on the Java 11 managed runtime with 2GB of memory you would have a cold start latency of ~1.5 seconds.

Thanks,

### Steps to Reproduce

Create a simple Lambda function with the Java SDK and another with the Kotlin SDK and compare the latency.

The code I used is not currently public (soon to be). But happy to share it to other AWS employees.

### Current behavior

For example, a function which connects to DynamoDB and calls getItem:

- With the Java SDK on the Java 11 managed runtime with 2GB of memory you would have a cold start latency of ~3 seconds.
- With the Kotlin SDK on the Java 11 managed runtime with 2GB of memory you would have a cold start latency of ~1.5 seconds.

### AWS Java SDK version used

Latest

### JDK version used

Lambda Java 11 Managed Runtime

### Operating System and version

AL2 on Lambda Java 11 Managed Runtime

**Comment by brharrington** [comment]
I think you are referring to the CRT client:

https://aws.amazon.com/blogs/developer/introducing-aws-common-runtime-http-client-in-the-aws-sdk-for-java-2-x/

**Comment by msailes** [comment]
Yes and no. I think it is the CRT client. But it's compiled to native code.

**Comment by zoewangg** [comment]
What HTTP client did you use with the Java SDK client? Note that the CRT HTTP client is also supported in the Java SDK (still in Preview)

**Comment by msailes** [comment]
I used the apache http one, which was stupid now I write it down. I'll rerun with CRT. But from previous experience I don't think that would account for the difference.

**Comment by zoewangg** [comment]
We've tested with CRT HTTP client and observed improved startup latency. I'd be interested to see your setup if this is not the case in your tests

**Comment by msailes** [comment]
I stand corrected. The CRT client gives a much bigger performance increase than I expected. Given there is still 500ms (25%) difference, is there anything else the Java SDK can learn from the Kotlin SDK?

Java with CRT
<img width="1016" alt="java-with-crt" src="https://user-images.githubusercontent.com/45629314/146246507-3b16adf0-ed6a-46f0-a115-931c4182437c.png">

Kotlin
![kotlin](https://user-images.githubusercontent.com/45629314/146246545-2554d3a7-43dc-4a0f-b741-a0cb2de5a13c.png)

**Comment by zoewangg** [comment]
I'm not sure if we are comparing apples to apples, but I agree there might be areas we can improve to further reduce the startup latency. 

Can you share the code where you use the Java SDK client? Did you use the settings that are optimized for faster startup latency such as using EnvironmentVariableCredentialsProvider, excluding Apache HTTP client and Netty HTTP client from the classpath? https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time/

**Comment by msailes** [comment]
https://github.com/aws-samples/serverless-graalvm-demo/tree/jvm/software/products

Yes and yes.

**Comment by zoewangg** [comment]
Do the Java code and kotlin code have the same functionalities? I noticed ObjectMapper is being used in the Java code, which is quite expensive

**Comment by msailes** [comment]
Yes, it could well be that Jackson is that much slower than the Kotlin version (kotlinx.serialization.json.Json).

I could measure the usage with an X-Ray segment, but not how much additional time it takes to load etc.

Thanks for your time Zoe, I'll close the ticket.
