### ISSUE TITLE
S3 PutObject with ObjectLockMode

### ISSUE THREAD

**Issue by JhLedesma** [aws/aws-sdk-java-v2#2924]
### Describe the issue

Hello
Our bucket have a object lock configuration with Governance Mode
When we execute the put object request, we get a 5xx error

Is there a issue in our code?

Thank you

### Steps to Reproduce

This is our code

```
fun saveFile(data: ByteArray, keyBuilder: KeyBuilder, fileType: FileType): String {
        log.info("Saving File | File Type: {} | Container: {} | Key: {}", fileType, bucket, keyBuilder.getKey())
        if (!existsKey(bucket, keyBuilder.getKey())) {
            val s3Request = PutObjectRequest.builder()
                .bucket(bucket)
                .key(keyBuilder.getKey())
                .contentType(fileType.contentType)
                .contentLength(data.size.toLong())
                .objectLockMode(ObjectLockMode.GOVERNANCE)
                .objectLockRetainUntilDate(Instant.MAX)
                .objectLockLegalHoldStatus(ObjectLockLegalHoldStatus.ON)
                .contentMD5(Md5Utils.md5AsBase64(Md5Utils.computeMD5Hash(data)))
                .build()
            s3Client.putObject(s3Request, AsyncRequestBody.fromByteBuffer(ByteBuffer.wrap(data))).join()
            log.info("Saved File | File Type: {} | Container: {} | Key: {}", fileType, bucket, keyBuilder.getKey())
        } else {
            log.info("File already exists | File Type: {} | Container: {} | Key: {}", fileType, bucket, keyBuilder.getKey())
        }
        return getUrl(keyBuilder.getKey())
    }
```

### Current behavior

We get the following error:
    ```
    software.amazon.awssdk.services.s3.model.S3Exception: We encountered an internal error. Please try again. (Service: S3, Status Code: 500, Request ID: 7PY0ZS3FRFK2F9QZ, Extended Request ID: CpUdwWM9rCBs8n06GLTl8PeHDxfduZhrcpR1GIzBYxlnpD8EYu6rBjFLmsdpkgyiVPzHsJDuhl4=)
    ```

### AWS Java SDK version used

2.17.96

### JDK version used

1.8

### Operating System and version

ubuntu 20.04

**Comment by debora-ito** [comment]
@JhLedesma status code 500 is for internal service errors. Maybe there's something in the request body that can be the issue.

Do this happen every time you call putObject or is it intermittent? It's only in this bucket? Only with this file? Have you tried uploading the same file in a different bucket?

**Comment by JhLedesma** [comment]
This happen every time I call putObject. It happen in this bucket because it's the unique that we have with object lock configuration. It happen with all the files. I resolved it changing `Instant.max` to `Instant.now().plusSeconds(172800)`, for some reason when I use `Instant.max`, I receive a 5xx error
I used `Instant.max` to lock the object as long as possible

**Comment by debora-ito** [comment]
Good catch. `Instant.MAX` is '1000000000-12-31T23:59:59.999999999Z', S3 probably could not handle a timestamp this far.

Closing this since you got unblocked. Thank you for reaching out.
