### ISSUE TITLE
user.permissionsBoundary returns NULL while retrieving information from AWS using Java SDK

### ISSUE THREAD

**Issue by jamshaid120** [aws/aws-sdk-java-v2#2944]
### Describe the issue

I am using AWS Java SDK v2 to list users using the code defined [here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/iam/src/main/java/com/example/iam/ListUsers.java) on the AWS GitHub repo. 

     public static void listAllUsers(IamClient iam) {`

        try {
            boolean done = false;
            String newMarker = null;

            while (!done) {
                ListUsersResponse response;

                ListUsersRequest request;
                if (newMarker == null) {
                    request = ListUsersRequest.builder().build();
                } else {
                    request = ListUsersRequest.builder()
                            .marker(newMarker).build();
                }

                response = iam.listUsers(request);

                for (User user : response.users()) {
                    System.out.format("\n Retrieved user %s", user.userName());
                    System.out.println("\nPermission Boundary: " + user.permissionsBoundary());
                }

                if (!response.isTruncated()) {
                    done = true;
                } else {
                    newMarker = response.marker();
                }
            }
        } catch (IamException e) {
            System.err.println(e);
            System.exit(1);
        }
    }

It returns NULL for user.permissionsBoundary(). Here is the output for print statements in the above code.     
	
`Retrieved user jamshaid
Permission Boundary: null

 Retrieved user luminadmin
Permission Boundary: null

 Retrieved user test
Permission Boundary: null

`

When I run the following command in AWS CloudShell on AWS console, it returns the PermissionBoundary for the users it is defined.
`aws iam get-user --user-name test  `

![image](https://user-images.githubusercontent.com/30922803/147866574-262128c2-c2bf-426a-9f59-319d3d3da3ee.png)

The same issue is confirmed by an other user on StackOverflow [here](https://stackoverflow.com/a/70551053/7497127) 

### Steps to Reproduce

Assign Permission Boundary to a user. Retrieve the permission boundary and user information using the code provided in this SDK example and you will find that the Permission Boundary is returned NULL.  

### Current behavior

It returns NULL for the Permission Boundary

### AWS Java SDK version used

v2

### JDK version used

 openjdk version "1.8.0_312" OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~21.10-b07) OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)

### Operating System and version

Ubuntu 21.10

**Comment by aaoswal** [comment]
Hi @jamshaid120,
This has already been answered on [StackOverflow](https://stackoverflow.com/a/70551179).

To reiterate,
In the console you are using `get-user` and not `list-users`, which is the reason why the command is returning all the information about the user, PermissionsBoundary within it.

The output for `aws iam list-users` would match the output you are currently getting for your sample code.

You can use the [`getUser`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/iam/IamClient.html#getUser-software.amazon.awssdk.services.iam.model.GetUserRequest-) method to return `PermissionsBoundary` in the response.

Example:
```
GetUserRequest request = GetUserRequest.builder()
  .userName("test")
  .build();

GetUserResponse response = iam.getUser(request);
User user = response.user();
System.out.println("\nPermission Boundary: " + user.permissionsBoundary());
```
