### ISSUE TITLE
AWS Java SDK v2 BOM incorrectly locks versions of test dependencies

### ISSUE THREAD

**Issue by wjbuys** [aws/aws-sdk-java-v2#295]
## Expected Behavior
When I declare a dependency on [the BOM for the AWS Java SDK v2](https://mvnrepository.com/artifact/software.amazon.awssdk/bom/2.0.0-preview-5), I expect it to only lock the versions of the AWS SDK's *runtime* dependencies, similarly to how the [v1 SDK BOM](https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-bom/1.11.231) did it.

## Current Behavior
However, for some reason, the BOM also declares dependency versions for many transitive dependencies, including the following test dependencies of the SDK:

- info.cukes:cucumber-java:1.2.4 
- info.cukes:cucumber-junit:1.2.4
- info.cukes:cucumber-guice:1.2.4
- org.mockito:mockito-core:1.10.19

This forces any project that pulls in the BOM to also depend on these (outdated) dependencies, unless I explicitly override those versions in a dependency management block too.

## Possible Solution
Remove these libraries from the BOM.

## Context
I tried to add the new SDK's BOM to an existing project, and was surprised that all my tests started failing without any code changes. Turns out it had forced Mockito to the 1.x version, and the tests were depending on the 2.x version.

## Your Environment

* AWS Java SDK version used: https://mvnrepository.com/artifact/software.amazon.awssdk/bom/2.0.0-preview-5 
* JDK version used: Oracle JDK 1.8.0_u151
* Operating System and version: Mac OS X 10.12.4

**Comment by wjbuys** [comment]
Looking at it a bit more, I think the problem is that [the SDK v2's BOM's `pom.xml` imports the parent `pom.xml`](https://github.com/aws/aws-sdk-java-v2/blob/master/bom/pom.xml#L25), which contains [a `dependencyManagement` block that depends on all the problematic libraries](https://github.com/aws/aws-sdk-java-v2/blob/master/pom.xml#L127). In SDK v1, the parent pom did not declare all its dependency versions in a `dependencyManagement` block, avoiding this problem.

**Comment by millems** [comment]
This should be fixed in the next release. Thanks!

**Comment by varunnvs92** [comment]
Reopening the issue as the fix has been reverted in #444 for releasing new features. I agree the issue has to be fixed. We can discuss the potential options and go with the right solution. Current options:
1) Remove parent element from BOM's pom file and add all the required elements to satisfy maven publish rules
2) Remove dependency management from parent pom and add it to a different module which can be added as a dependency to all other modules. For example, move the dependencies in parent pom to core pom file. Then add core as dependency to other modules which need those dependencies. (a bit similar to v1 SDK)

Feel free to chime in other options I might have missed.

**Comment by abatkin** [comment]
@shorea Can I request that you re-open this issue? The BOM still inherits from the parent POM, which can cause all kinds of breakage.

Here's another example of the trouble this is causing: The parent POM includes `com.google.guava:guava` but with `<scope>test</scope>`. This means that any project using the SDK BOM, that also wants to use Guava, will *not* have Guava added to the compile/runtime classpath, because of the (admittedly confusing/strange) Maven behavior around `<scope>`s in `<dependencyManagement>` blocks.

**Comment by debora-ito** [comment]
Fixed by #1066.
