### ISSUE TITLE
SignatureDoesNotMatch-error when trying to download file via Signed URL from bucket with Amazon S3 Transfer Acceleration enabled.

### ISSUE THREAD

**Issue by daghendrik** [aws/aws-sdk-java-v2#2951]
### Describe the bug

The code under **"Example Usage"** at https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/presigner/S3Presigner.html works well for creating presigned urls to S3 objects in non-accelerated buckets.  The presigner object can be instantiated like this for non-accelerated getObjectRequests:

```
S3Presigner presigner = S3Presigner.create();
```

But if we want the presigned url (presignedGetObjectRequest.url()) to point to the accelerated s3 bucket endpoint (https://{bucket_name}.s3-accelerate.amazonaws.com) then I believe we have to instantiate the S3PreSigner like this:

```
S3Presigner presigner = S3Presigner.builder()
                .serviceConfiguration(S3Configuration.builder().accelerateModeEnabled(true).build())
                .build();
```

It will produce signed URLs with the "s3-accelerate" domain part (https://{bucket_name}.s3-accelerate.amazonaws.com), but when visiting the URL you will get an XML error such as:

```
<Error>
<Code>SignatureDoesNotMatch</Code>
<Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message>
<AWSAccessKeyId>...</AWSAccessKeyId>
<StringToSign>AWS4-HMAC-SHA256 20220105T132146Z 20220105/eu-west-1/s3/aws4_request e51d6750a406f146b559fcf2f7f44b254489671dd401fdb72218599076aa725f</StringToSign>
<SignatureProvided>...</SignatureProvided>
....
```

### Expected behavior

The signature check should not fail

### Current behavior

See above

### Steps to Reproduce

See above

### AWS Java SDK version used

2.17.102

### JDK version used

coretto-11

### Operating System and version

AWS Lambda x86_69 (Lambda version 1.2.1)

**Comment by debora-ito** [comment]
@daghendrik thank you for reporting this, I can reproduce the issue.

Did some local tests and I can see that accelerated endpoints work fine using Java SDK v1 presigning. We'll investigate.

**Comment by debora-ito** [comment]
@daghendrik after some investigation it looks like it's not really a bug.

When `S3Configuration` is defined, it enables checksum validation and the url becomes incompatible to be executed by web browsers.

You can disable the checksum validation in the S3Configuration builder:
```
S3Presigner presigner = S3Presigner.builder()
                            .serviceConfiguration(S3Configuration.builder()
                                                             .accelerateModeEnabled(true)
                                                             .checksumValidationEnabled(false)
                                                             .build())
                            .build();
```

This info was hidden away, so we updated the S3Presigner javadocs and added examples, see "Browser Compatibility":
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/presigner/S3Presigner.html

Let us know if you have follow up questions.
