### ISSUE TITLE
[Security Hub] API is not available

### ISSUE THREAD

**Issue by niraj-ranjan-comprinno** [aws/aws-sdk-java-v2#2952]
### Describe the bug

getControlFindingSummary : this method is not available in securityHubAsync client.

### Expected behavior

Method must be there

### Current behavior

Method is undefined

### Steps to Reproduce

		AwsCredentials credentials = AWSCustomCredentialHandler.getCredential(credential);

		SecurityHubClient awsSecurityHubAsyncClientBuilder = SecurityHubClient.builder()
				.credentialsProvider(new AWSStaticCredentialsProvider(credentials)).region(Helper.getRegion(regionName))
				.build();

				awsSecurityHubAsyncClientBuilder.getControlFindingSummary

### AWS Java SDK version used

 <dependency>     <groupId>com.amazonaws</groupId>     <artifactId>aws-java-sdk-securityhub</artifactId>     <version>1.12.134</version> </dependency>

### JDK version used

latest

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Hi @niraj-ranjan-comprinno 

`GetControlFindingSummary` is not an API operation, it's a permission found only when defining the `Action` element on IAM policies. 

Other permission-only actions include: GetAdhocInsightResults, GetFreeTrialEndDate and GetFreeTrialUsage.

This is according to the Actions list found in the "Actions defined by AWS Security Hub" table:
https://docs.aws.amazon.com/service-authorization/latest/reference/list_awssecurityhub.html#awssecurityhub-actions-as-permissions

Will go ahead and close this. Feel free to reach out if you have any other question.
