### ISSUE TITLE
Connect transfermanager v2 to a different endpoint (not aws region endpoint)

### ISSUE THREAD

**Issue by JoeHale** [aws/aws-sdk-java-v2#2962]
### Describe the feature

We have another S3 compatible data storage system and I would like to us the java transfermanager v2 to migrate data into it. 
I can connect to it with the s3client, but the transfermanager does not allow me to specify an endpoint. 
Can this be added, or is there another way of doing this ?

### Is your Feature Request related to a problem?

Unable to connect to a non AWS S3 server/endpoint

### Proposed Solution

support setting an endpoint in the s3configuration used by the transfermanager

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.100

### JDK version used

1.8

### Operating System and version

CentOs 7

**Comment by debora-ito** [comment]
Hi @JoeHale thank you for reaching out. We have a feature request for this: https://github.com/aws/aws-sdk-java-v2/issues/2740.

Let's keep track of the progress over there.
