### ISSUE TITLE
Transfermanager - Resumable upload/downloads

### ISSUE THREAD

**Issue by JoeHale** [aws/aws-sdk-java-v2#2965]
### Describe the feature

The v1 of the transfermanager supported resumable uploads and dowloads. Can this feature be implemented. We have some users on poor networks that need to upload/download large files. The only way that can be accomplished is with this feature.

### Is your Feature Request related to a problem?

No

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.100

### JDK version used

1.8

### Operating System and version

CentOs 7

**Comment by zoewangg** [comment]
Hi @JoeHale yes, this feature is on our roadmap. We will post the PR link here when we start to implement the feature. Do you have any feedback on the implementation of pause and resume in v1, asking because this is a chance for us to improve the feature in v2 :)

**Comment by JoeHale** [comment]
Thanks for reading my request.
I would like it to update more often, it seems like it would only notify after a long time.  Maybe that could be configurable, but often there would be no notification until several minutes and nearly 90% complete. If I could give the frequency in either time or bytes, that would be a great improvement.

**Comment by zoewangg** [comment]
Thanks for the feedback! Just to be clear, are you referring to the progress listener feature in v1? Progress listeners are supported in v2 now. https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/progress/TransferListener.java You can track different events including when additional bytes have been transferred. Can you try it out to see if that works for your use-case?

**Comment by zoewangg** [comment]
Resumable downloads feature has been implemented via #3169 and released as part of `2.17.179`. We will be working on resumable uploads shortly

**Comment by zoewangg** [comment]
To provide an update, we have released the change in 2.19.0. Closing the issue.
