### ISSUE TITLE
Incorrect exception thrown for Route 53 throttling

### ISSUE THREAD

**Issue by petrp-aws** [aws/aws-sdk-java-v2#2969]
### Describe the bug

Route 53 API documentation at https://docs.aws.amazon.com/Route53/latest/APIReference/CommonErrors.html states that when a request is throttled, a ThrottlingException error is returned. AWS SDK v2 documentation indicates the same here: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/route53/model/ThrottlingException.html. 

Unfortunately, the error code that is actually returned by Route 53 service in my testing is "Throttling" and not "ThrottlingException" (see below for details). As a result, AWS SDK for Java V2 does not recognize the error as throttling and does not throw ThrottlingException as expected but throws a more generic Route53Exception.

I have not thoroughly tested how other services and SDKs behave. I know that for example AWS SDK Java v2 for KMS does not appear to have a modelled ThrottlingException which makes the situation there somewhat less confusing.

### Expected behavior

I expect AWS SDK for Java V2 to throw software.amazon.awssdk.services.route53.model.ThrottlingException and not software.amazon.awssdk.services.route53.model.Route53Exception when Route 53 throttles my request made using the SDK.

### Current behavior

AWS SDK throws software.amazon.awssdk.services.route53.model.Route53Exception instead of software.amazon.awssdk.services.route53.model.ThrottlingException. 

This is because Route 53 returns a response that looks like below. Note the code is just "Throttling". When I feed AWS SDK a Route 53 response that has "ThrottlingException" as the code, I get the correct exception class (ThrottlingException).
```xml
<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\">" +
<Error>
<Type>Sender</Type>
<Code>Throttling</Code> <!-- Note the missing "Exception" here -->
<Message>Rate exceeded</Message>
</Error>
<RequestId>...</RequestId>
</ErrorResponse>
```

### Steps to Reproduce

```java
try {
    final GetHostedZoneResponse hostedZone = route53client.getHostedZone(b -> b.id("SOMEZONEID"));
} catch (ThrottlingException e) {
    // Handle getting throttled by Route 53. This actually does not get called.
}
```

### Possible Solution

Route 53 would ideally return "ThrottlingException" as the error code when throttling. But I suspect they may not be able to do that because it's not backwards compatible. Instead, AWS SDK could recognize that "Throttling" code from Route 53 and throw the ThrottlingException as expected. This should be a backward-compatible change because route53.ThrottlingException is a subclass of the exception that was thrown before. But I'm not sure if this fits AWS SDK guaratees around backwards compatibility or not.

Another consideration is that AWS SDK for other services (e.g., KMS) do not model ThrottlingException as a class at all even though their API documentation shows those error codes. I think the ideal end-result is for those services to have ThrottlingException classes in AWS SDK as well and have the SDK throw them when throttling occurs.

### Context

I wanted to emit a separate metric to indicate that Route 53 throttling has occurred. I expected ThrottlingException to be thrown but instead I got the generic Route53Exception and I have to have additional logic to look at the exception message as well and recognize throttling is occuring.

### AWS Java SDK version used

2.17.110 

### JDK version used

openjdk version "15.0.5" 2021-10-19 (Corretto 15)

### Operating System and version

Amazon Linux 2

**Comment by debora-ito** [comment]
Hi @petrp-aws thank you for the detailed report.

> Unfortunately, the error code that is actually returned by Route 53 service in my testing is "Throttling" and not "ThrottlingException" (see below for details). As a result, AWS SDK for Java V2 does not recognize the error as throttling and does not throw ThrottlingException as expected but throws a more generic Route53Exception.

Yes, it looks like this is what's causing the issue.

And yes, ideally Route53 would return "ThrottlingException" code but changing the error code is a breaking change for customers who are already handling the error using the generic Route53Exception. In any case it's a service-side issue, the SDK would not add a customization for "Throttling" in this case.

I will pass on your feedback internally to the Route53 service team, they should be aware of this.

**Comment by petrp-aws** [comment]
Thank you for the answer, Debora! I agree it's unfortunately a breaking change to fix the error code. I think at a minimum, Route 53 API documentation should reflect the true error code. And on the SDK part I think it would be worth somehow signalling to the customers that route53.ThrottlingException is not being used and they shouldn't use it in their code. I suspect there are a few customers who are currently catching route53.ThrottlingException in their code expecting it to be thrown when it isn't (never?).

**Comment by debora-ito** [comment]
Quick follow-up: the Route53 is aware of this, looks like the same issue is also seen in other Route53 APIs. They'll research ways to make the change as it will require some level of process redesign on their side. 

I'll mark this to auto-close soon since there's nothing pending from the SDK team. Let us know if you have more questions.
