### ISSUE TITLE
Cannot find out how to config S3Client timeouts equivalent to v1

### ISSUE THREAD

**Issue by charlesritchea** [aws/aws-sdk-java-v2#2975]
### Describe the issue

Here is my v1 S3Client config:
```kotlin
        val amazonS3ClientBuilder = AmazonS3ClientBuilder.standard()
            .withPathStyleAccessEnabled(pathStyleAccess)
            .withCredentials(AWSStaticCredentialsProvider(v1AWSCredentials))
            .withClientConfiguration(
                ClientConfiguration()
                    .withMaxErrorRetry(s3MaxErrorRetry)
                    .withMaxConnections(maxNumberOfConnections)
                    .withConnectionTimeout(s3ConnectionTimeout)
                    .withSocketTimeout(s3SocketTimeout)
            )
```
I can't figure out how to do the same (in particular the ClientConfiguration part in v2 based on the documentation

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html

**Comment by debora-ito** [comment]
Hi @charlesritchea 

In Java SDK v2, the timeout configurations are now in the HTTP Client builder, it will depend on which client you are using. Here's an example using the Apache HTTP Client, which is the default client:

```java
S3Client s3Client = S3Client.builder()
        .region(region)
        .overrideConfiguration(clientOverrideConfiguration)
        .httpClientBuilder(ApacheHttpClient.builder()
                .maxConnections(maxConnectionsConfig)
                .connectionTimeout(Duration.ofSeconds(1))
                .socketTimeout(Duration.ofSeconds(15)))
        .build();
```

Other HTTP client options include [UrlConnectionHttpClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/urlconnection/UrlConnectionHttpClient.html) for sync, and [NettyNioAsyncHttpClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.html) and  [AwsCrtAsyncHttpClient (in preview mode)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/crt/AwsCrtAsyncHttpClient.html) for async. Note that not all configuration settings are supported in all HTTP clients.

The 1.11 to 2.0 Changelog is also helpful: https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#131-client-http-configuration
