### ISSUE TITLE
ChainExtension afterRead is not populating the tableSchema 

### ISSUE THREAD

**Issue by jonathannaguin** [aws/aws-sdk-java-v2#2977]
### Describe the issue

The DynamoDbExtensionContext interface contains a "tableSchema" that is being populated on the "beforeWrite" method however it's missing on the "afterRead" method on this ChainExtension.

### Steps to Reproduce

A client created like this:

```
      DynamoDbEnhancedClient client = DynamoDbEnhancedClient.builder()
                                                            .extensions(VersionedRecordExtension.builder().build(), new NewCustomExtension())
                                                            .build();
```

will initialise the client with a ChainExtension that contains both extensions, then do a getItem:

```
table.getItem(Key.builder()
                                          .partitionValue(item.getId())
                                          .build());
```

The NewCustomExtension class:

```
public class NewCustomExtension implements DynamoDbEnhancedClientExtension
{
    private static final Logger logger = LoggerFactory.getLogger(NewCustomExtension.class);
    
    @Override
    public WriteModification beforeWrite(DynamoDbExtensionContext.BeforeWrite context)
    {
        logger.info("This is not null: " + context.tableSchema());
        
        return DynamoDbEnhancedClientExtension.super.beforeWrite(context);
    }

    @Override
    public ReadModification afterRead(DynamoDbExtensionContext.AfterRead context)
    {
        logger.info("This is null: " + context.tableSchema());
        
        return DynamoDbEnhancedClientExtension.super.afterRead(context);
    }
}
```

### Current behavior

"tableSchema" is null.
This is not consistent with "beforeWrite".

### AWS Java SDK version used

2.17.109

### JDK version used

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Operating System and version

macOS

**Comment by zoewangg** [comment]
This should be fixed by https://github.com/aws/aws-sdk-java-v2/pull/2971

**Comment by zoewangg** [comment]
The fix has been released. Could you try with the latest version? (`2.17.115` as of today).
