### ISSUE TITLE
Make Netty Acquire Timeout throw a RetryableException

### ISSUE THREAD

**Issue by driverpt** [aws/aws-sdk-java-v2#2987]
### Describe the feature

Currently `NettyRequestExecutor` throws a generic SdkClientException, which makes it hard to handle a Retry with Backoff + Jitter Scenario.

We would like that `NettyRequestExecutor` thrown a different Exception when we get Acquire Timeout.

### Is your Feature Request related to a problem?

Currently we're using WebFlux along with multiple LambdaAsyncClient and sometimes we get this Acquire Timeout Exception, we would like to add specific logic to handle a Retry Scenario,

e.g.:

```
      .retryWhen(reactor.util.retry.Retry.withThrowable(reactor.retry.Retry
        .anyOf(RetryableException.class)
        .exponentialBackoffWithJitter(Duration.ofMillis(100), Duration.ofMillis(300))
        .doOnRetry(retry ->
          log.warn("Retrying because of Acquire Exception")))
      );
```

It's hard to do this when it throws a Generic `SdkClientException`

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Java SDK version used

2.17.116

### JDK version used

11.0.11

### Operating System and version

Fedora Linux 35

**Comment by debora-ito** [comment]
@driverpt Generally speaking, changing an exception is a breaking change so we avoid doing it.

Do you have a stacktrace with the exception you have in mind?
