### ISSUE TITLE
getHLSStreamingSessionURL is returning null

### ISSUE THREAD

**Issue by ap-northeast-0** [aws/aws-sdk-java-v2#3002]
### Describe the issue

I am unable to retrieve a streaming session using getHLSStreamingSessionURL. Below is my code and whether I set an existing or non-existing streamName, getHLSStreamingSessionURL returns null.

I have written my code under the steps to reproduce

On the side note, I know I have set my AWS systems credentials correctly because when I tried the code below, I was able to get the data end point. 
`KinesisVideoClient kvsClient = KinesisVideoClient.create();
GetDataEndpointRequest requestEndPoint = GetDataEndpointRequest.builder().streamName(streamName).build();
GetDataEndpointResponse responseEndPoint = kvsClient.getDataEndpoint(requestEndPoint);
System.out.println(responseEndPoint.dataEndpoint());`

Hope you guys can help me.

### Steps to Reproduce

```
public class KVSService {
    public KinesisVideoArchivedMediaClient getClient() {
        return KinesisVideoArchivedMediaClient.create();
    }
    
    public String test() {
    	KinesisVideoArchivedMediaClient kvs = getClient();
    	String url = null;
    	
    	try {
    		GetHlsStreamingSessionUrlRequest request = GetHlsStreamingSessionUrlRequest.builder()
        			.streamName(streamName)
                    .expires(1000)
        			.playbackMode(HLSPlaybackMode.LIVE)
        			.containerFormat(ContainerFormat.FRAGMENTED_MP4)
        			.discontinuityMode(HLSDiscontinuityMode.ALWAYS)
        			.displayFragmentTimestamp(HLSDisplayFragmentTimestamp.NEVER)
        			.build();
    		GetHlsStreamingSessionUrlResponse response = kvs.getHLSStreamingSessionURL(request);

        	System.out.println(response.sdkHttpResponse().statusCode()); // this always returns 200 even if streamname is not blank
        	System.out.println(response.hlsStreamingSessionURL()); // this is returning null

        	url = response.hlsStreamingSessionURL();
    	} catch (KinesisVideoArchivedMediaException e) {
    		e.printStackTrace();
    	}
    	
    	return url;
    }
}
```

### Current behavior

getHLSStreamingSessionURL always returns null

### AWS Java SDK version used

2.17.121

### JDK version used

15.0.1 2020-10-20

### Operating System and version

mac os 10

**Comment by ap-northeast-0** [comment]
I am still having this problem.

**Comment by debora-ito** [comment]
Hi @ap-northeast-0 I'm sorry, I've put the "response-requested" label without a comment for some reason.

Can you enable the verbose wirelogging and provide us the logs?
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

Please make sure to redact any sensitive information the logs might contain (like access keys).

**Comment by ap-northeast-0** [comment]
Hey @debora-ito,
Thank you for your reply.

I have enabled the debug logs and found the following error.
```
2022-02-09 20:04:30.136 DEBUG 4275 --- [nio-8080-exec-3] s.a.a.r.p.AwsRegionProviderChain         : Unable to load region from software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@285cccb0:Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region).
2022-02-09 20:04:30.138 DEBUG 4275 --- [nio-8080-exec-3] s.a.a.c.i.ExecutionInterceptorChain      : Creating an interceptor chain that will apply interceptors in the following order: [software.amazon.awssdk.core.internal.interceptor.HttpChecksumRequiredInterceptor@67a63df0, software.amazon.awssdk.awscore.interceptor.HelpfulUnknownHostExceptionInterceptor@295154f8, software.amazon.awssdk.awscore.eventstream.EventStreamInitialRequestInterceptor@560b1b76]
2022-02-09 20:04:30.139 DEBUG 4275 --- [nio-8080-exec-3] s.a.a.a.c.AwsCredentialsProviderChain    : Unable to load credentials from SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId).
```

How come I was able to get credentials when I used DefaultAWSCredentialsProviderChain but not when KinesisVideoArchivedMediaClient.create()? Am I missing a settings for this to work?

--
I was able to get credentials this way.
```
DefaultAWSCredentialsProviderChain credentials = new DefaultAWSCredentialsProviderChain();
System.out.println(credentials.getCredentials().getAWSAccessKeyId());
System.out.println(credentials.getCredentials().getAWSSecretKey());
```

**Comment by debora-ito** [comment]
Are you running the code locally, or in a virtual environment like EC2 or ECS?

Note that in the sample code you provided in Steps to Reproduce, `getClient()` returns a new instance of the client every time it's called. We recommend to share the same instance of the client whenever possible - I don't think this is related to the error though.

**Comment by ap-northeast-0** [comment]
@debora-ito I am running the code locally at the moment but will be deploying in EC2 eventually.

Yes, thank you for pointing that one out. I will be cleaning the code once it starts working.

**Comment by debora-ito** [comment]
The message `Unable to load credentials from SystemPropertyCredentialsProvider()` indicates that a service client tried to explicitly use the SystemPropertyCredentialsProvider but no system property with the credentials was found.

```
DynamoDbClient ddb = DynamoDbClient.builder()
      .credentialsProvider(SystemPropertyCredentialsProvider.create())
      .build();
```

Note that this is different than using the default credential chain.
