### ISSUE TITLE
Remove C2j models from SDK JARs

### ISSUE THREAD

**Issue by breedloj** [aws/aws-sdk-java-v2#3022]
### Describe the feature

C2j model files are currently included in service client JARs. These can be pretty hefty (in the case of EC2, around 2.5mb altogether). They do not seem to be providing any value once clients are generated and can be fetched from source. For clients this adds quite a bit of needless overhead to deployable artifacts or shipped software.

### Is your Feature Request related to a problem?

The AWS SDK dependencies within the AWS Toolkit for Jetbrains represent the largest chunk of our overall footprint (which is ~50MB). We are trying to reduce this to make it faster to distribute the Toolkit to clients and across remote machines. This change would be a good first step to trimming some fat.

### Proposed Solution
Remove C2j model JSON files from generated client JARs.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.17.76

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
Transferred to Java SDK v2 repo. Reducing size is also interesting for Lambda use cases. Will bring this up to the team.

**Comment by debora-ito** [comment]
Feature request added to the backlog.

**Comment by millems** [comment]
This has been fixed with https://github.com/aws/aws-sdk-java-v2/pull/3030

**Comment by vigoo** [comment]
Hi, the https://github.com/zio/zio-aws project was depending on these resources embedded in the JARs. Would you consider publishing them separately (maybe bundled in a single JAR)?

If not we will have to pull them directly from this repo as part of the code generation process.
