### ISSUE TITLE
Add ClientOverrideConfiguration getter to SdkClientBuilder

### ISSUE THREAD

**Issue by smswz** [aws/aws-sdk-java-v2#3023]
### Describe the feature

`ClientOverrideConfiguration` is a multipartite object used in configuration of the builder. Currently, the builder does not allow querying this object so that individual objects can be set/changed. This prevents a builder from setting different properties at different locations. An example would be: wanting to set the `apiCallTimeout` at one location, but adding an `ExecutionInterceptor` in specify cases without having to pass around both the `SdkClientBuilder` _and_ the `ClientOverrideConfiguration.Builder`.

### Is your Feature Request related to a problem?

Yes, we are not able to replicated SDKv1 behavior of configuring both execution interceptors and api call timeouts via the client builder alone.

### Proposed Solution

Add a `ClientOverrideConfiguration` getter to the `SdkClientBuilder`.

### Describe alternatives you've considered

Asking for two both a `SdkClientBuilder` and a `ClientOverrideConfiguration` (or `Builder`). But this can lead to confusing behavior where a user may set the override configuration on the builder directly, causing their changes to be overridden if other override configuration values need to be changed.

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Java SDK version used

2.17.110

### JDK version used

OpenJDK 64-Bit Server VM Corretto-8.322.06.1 (build 25.322-b06, mixed mode)

### Operating System and version

macOS 12.2.1

**Comment by debora-ito** [comment]
Hi @smswz thank you for the contribution, the PR is being reviewed.
