### ISSUE TITLE
AttributeValue object's "nul" attribute is being set to null when converting DynamoDB Json to Record object

### ISSUE THREAD

**Issue by lakshmikanthpadala** [aws/aws-sdk-java-v2#3033]
### Describe the bug

We have a DynamoDB table for which we have enabled Kinesis Stream.  The data we receive via this Kinesis Stream is of Dynamo DB JSON format.  We deserialize this json into "software.amazon.awssdk.services.dynamodb.model.Record" object and then later transform the dynamoRowImage (Map<String, AttributeValue> dynamoRowImage = record.dynamodb().newImage()) into our PoJo using TableSchema.fromBean(com.Event.class).mapToItem(dynamoRowImage) 

When we transform the DynamoDB Json to software.amazon.awssdk.services.dynamodb.model.Record object.  We observer AttributeValue object with null for "nul" attribute.

**Attribute Value's for attribute with  "NULL" data type when debugged the code.**

![Screen Shot 2022-02-15 at 1 07 48 PM](https://user-images.githubusercontent.com/87089624/154153669-584d46a8-7c26-4488-89a6-67f8f9bc1a22.png)

If you see the value of "nul" attribute is null instead of true (Corresponding to "NULL": true from above JSON).

I suspect this is due the difference in the AttributeValue object's attribute name "nul" and the json attribute name "NULL" which was given by the DynamoDB Json.

### Expected behavior

AttributeValue associated DynamoDB JSON objects "NULL" types should de-serialized properly into AttributeValue object as per the input DynamoDB JSON when transformed to software.amazon.awssdk.services.dynamodb.model.Record.

It should be like..

![Screen Shot 2022-02-15 at 1 44 00 PM](https://user-images.githubusercontent.com/87089624/154154451-d69948e4-49bc-4343-b6e4-900c7bc7a070.png)

### Current behavior

**Attribute Value's for attribute with  "NULL" data type when debugged the code.**

![Screen Shot 2022-02-15 at 1 07 48 PM](https://user-images.githubusercontent.com/87089624/154153669-584d46a8-7c26-4488-89a6-67f8f9bc1a22.png)

### Steps to Reproduce

**Example Dynamo DB JSON ( A simplified version of our json)**

```
{
  "awsRegion": "us-east-1",
  "eventID": "a3b56209-f8fe-4e86-a11e-989ec4033556",
  "eventName": "INSERT",
  "userIdentity": null,
  "recordFormat": "application/json",
  "tableName": "test-events",
  "dynamodb": {
    "ApproximateCreationDateTime": 1644593953751,
    "NewImage": {
      "event": {
        "M": {
          "value": {
            "L": [
              {
                "NULL": true
              },
              {
                "NULL": true
              },
              {
                "NULL": true
              },
              {
                "NULL": true
              },
              {
                "NULL": true
              },
              {
                "S": "2"
              }
            ]
          }
        }
      },
      "SK": {
        "S": "6f1f8ff6-d895-4158-aacc-efe15e2542f6"
      },
      "PK": {
        "S": "b75f042b-56c0-47c6-83c4-e7237ff09b38"
      }
    },
    "SizeBytes": 6132
  },
  "eventSource": "aws:dynamodb"
}
```

**How do we transform :**

    ObjectMapper objMapper = new ObjectMapper().configure(MapperFeature.ACCEPT_CASE_INSENSITIVE_PROPERTIES, true)
              .configure(DeserializationFeature.READ_DATE_TIMESTAMPS_AS_NANOSECONDS, false)
              .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);

    software.amazon.awssdk.services.dynamodb.model.Record Record record =
        objMapper.readValue(inputEvent, Record.serializableBuilderClass())
            .build();

### Possible Solution

Possible Reason : I suspect this is due the difference in the **AttributeValue** object's attribute name "nul" and the json attribute name "NULL" which was given in the **DynamoDB** Json.  And software.amazon.awssdk.services.dynamodb.model.AttributeValu class do not have required definitions to handle the transformation in a standard way supported by Jackson libraries.

### Context

We have a DynamoDB table for which we have enabled Kinesis Stream.  The data we receive via this Kinesis Stream is of Dynamo DB JSON format.  We deserialize this json into "software.amazon.awssdk.services.dynamodb.model.Record" object and then later transform the dynamoRowImage (Map<String, AttributeValue> dynamoRowImage = record.dynamodb().newImage()) into our PoJo using TableSchema.fromBean(com.Event.class).mapToItem(dynamoRowImage) 

Due to this issue, transformation of DynamoDB Json to actual Java POJO is failing when we have data with null values as shared in the example above.

We would like to know if there is any way we can fix this issue or is there any work around?

### AWS Java SDK version used

2.16.72

### JDK version used

11

### Operating System and version

Any - Tried on Mac , Linux

**Comment by debora-ito** [comment]
@lakshmikanthpadala can you share your table schema?

**Comment by lakshmikanthpadala** [comment]
@debora-ito :  Not sure if this helps considering the schema only gives Primary Key Attribute Definitions. Our java @DynamoDB Definition includes an  private Event event attribute in addition the Key attributes you see in the schema.

{
    "Table": {
        "AttributeDefinitions": [
            {
                "AttributeName": "PK",
                "AttributeType": "S"
            },
            {
                "AttributeName": "SK",
                "AttributeType": "S"
            }
        ],
        "TableName": "events",
        "KeySchema": [
            {
                "AttributeName": "PK",
                "KeyType": "HASH"
            },
            {
                "AttributeName": "SK",
                "KeyType": "RANGE"
            }
        ],
        "TableStatus": "ACTIVE",
        "CreationDateTime": "2021-10-10T11:05:31.589000-07:00",
    }
}

**Comment by debora-ito** [comment]
I'm sorry, I meant the DynamoDB Enhanced client table schema/bean.

**Comment by yujiel134** [comment]
Hi, I encountered the same issue. Not sure if the enhanced DynamoDB schema/bean will help here, since the `Map<String, AttributeValue> newImage` is created before we even try to do `tableSchema.mapToItem(newImage)`.
