### ISSUE TITLE
Use virtual host style addressing with buckets containing dots in their names.

### ISSUE THREAD

**Issue by bernalvarela** [aws/aws-sdk-java-v2#3035]
### Describe the bug

It seems that the client doesn't allow to use virtual host style addressing using buckets with dots in their names.

BucketUtil.isVirtualAddressingCompatibleBucketName // Line 156

Even though the bucket naming rules documentation says the use of periods is allowed.

https://docs.aws.amazon.com/AmazonS3/latest/userguide//bucketnamingrules.html

The V1 client allows to use virtual host style addressing with buckets with dots in their names.

### Expected behavior

A bucket with a dot in its name should be compatible with the virtual host style addressing.

https://mybucket.com.s3.eu-west-1.amazonaws.com/...

### Current behavior

A bucket with a dot in its name is placing the bucket name as a parameter in the url.

https://s3.eu-west-1.amazonaws.com/mybucket.com/...

### Steps to Reproduce

Use a bucket with a dot in its name.

### Possible Solution

Remove this check !bucketName.contains(".") in BucketUtil.isVirtualAddressingCompatibleBucketName // Line 156

### Context

The s3 naming convention allows using dots in bucket names.

https://docs.aws.amazon.com/AmazonS3/latest/userguide//bucketnamingrules.html

### AWS Java SDK version used

2.17.130

### JDK version used

openjdk version "17" 2021-09-14

### Operating System and version

Ubuntu 21.10

**Comment by debora-ito** [comment]
Hi @bernalvarela 

Virtual-host style is not compatible with buckets with dots in the name because the TLS certificate validation will not pass. The [S3 bucket naming rules](https://docs.aws.amazon.com/AmazonS3/latest/userguide//bucketnamingrules.html) mention this:

> If you include dots in a bucket's name, you can't use virtual-host-style addressing over HTTPS, unless you perform your own certificate validation.

Path-style works fine in this case. Is there a particular reason you want to use virtual-host style?

**Comment by debora-ito** [comment]
The deprecation plan was delayed, and buckets with dots in the name were specifically mentioned in the delay announcement - https://aws.amazon.com/blogs/storage/update-to-amazon-s3-path-deprecation-plan/

 While a new plan is not released, take a look at S3 solutions like [Access Points](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-points.html) and see if they fit your use case.
