### ISSUE TITLE
Remove java.beans package / java.desktop module dependency

### ISSUE THREAD

**Issue by axelfontaine** [aws/aws-sdk-java-v2#3041]
### Describe the feature

The AWS SDK currently uses the `java.beans` package which comes in the `java.desktop` module.

`jdeps` output:
```
  software.amazon.awssdk.services.ebs.model    -> java.beans    java.desktop
  software.amazon.awssdk.services.ec2.model    -> java.beans    java.desktop
  software.amazon.awssdk.http                  -> java.beans    java.desktop
```

With `jlink` this pulls in vastly more code than should be necessary.

It shouldn't be too hard to remove this.

### Is your Feature Request related to a problem?

Yes. Excessive size/modules on JREs generated with `jlink`on Java 9+.

### Proposed Solution

Remove dependency on classes in the `java.beans` package.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.17.131

### JDK version used

17.0.2

### Operating System and version

Win11 x64

**Comment by debora-ito** [comment]
@axelfontaine java.desktop is not bundled with the SDK jar module so removing it won't affect the jar size in our regular maven artifact distribution, but I don't know about `jlink`.

> Excessive size/modules on JREs generated with jlink on Java 9+.

Can you share a comparative with/without java.desktop? How excessive is the difference?

**Comment by axelfontaine** [comment]
@debora-ito For Java 17.0.0.2 Win x64:

`jlink --output base --add-modules java.base`
-> 40.3 MB

`jlink --output desktop --add-modules java.base,java.desktop`
-> 72.9 MB

In effect that one annotation (which coming from the java.beans package wasn't even originally intended for what it's used for) causes a 22.6 MB increase in JRE size to be able to support the functionality of the SDK. Removing it or replacing it with a home-grown alternative should be trivial and will yield massive savings in Java image footprint for Java 9+ users using jlink. This in turn leads to smaller Docker images, faster lambda startup, etc. This is the very definition of a low-hanging fruit.

**Comment by debora-ito** [comment]
Thank you for following-up, we'll study the possibility of removing the `@Transient` annotation.
