### ISSUE TITLE
Documentation on thread safetiness of DynamoDbIndex

### ISSUE THREAD

**Issue by arakiy117** [aws/aws-sdk-java-v2#3044]
### Describe the issue

I have found [similar inquiry](https://github.com/aws/aws-sdk-java-v2/issues/2351) for SdkClient thread safety as well as the statement (attached below for reference) on service clients' thread safety, but I am unable to find any documentation on thread safety for some of the components, such as DynamoDbIndex.

My inquiry are 
1. Is DynamoDbIndex thread safe? 
2. If so, could we have this added in official documentation and/or via annotations similar to the service clients?

Statement on service client thread safety from the developer guide:

```
Service clients in the SDK are thread-safe. For best performance, treat them as long-lived
objects. Each client has its own connection pool resource that is released when the client is
garbage collected.
```

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/aws-sdk-java-dg-v2.pdf

https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbIndex.java

**Comment by debora-ito** [comment]
@arakiy117 thank you for the suggestion, we'll look into it. 

I'm not sure if the DynamoDB Enhanced Client classes are thread safe, I'll get back with this info.
