### ISSUE TITLE
Very slow intialization of builder

### ISSUE THREAD

**Issue by shearn89** [aws/aws-sdk-java-v2#3071]
### Describe the issue

I am using the `KinesisVideoClient` chunk of the SDK to read a stream from Kinesis. I'm running in a Java 11 Lambda on ARM. I've added a bunch of debug logging, and have identified some serious bottlenecks in my code and am struggling to understand them!

What am I doing wrong? Why is this so slow?

### Steps to Reproduce

Here's my java code that reads from the stream, with logging statements removed for brevity. I'm using the SDKv2 (`software.amazon.awssdk.services.kinesisvideo...`).

```java
public static InputStream getInputStreamFromKVS(String streamName,
                                                Region region) {
    // slow 3 or 4 seconds
    KinesisVideoClient amazonKinesisVideo = KinesisVideoClient
            .builder()
            .region(region)
            .build();

    GetDataEndpointRequest gder = GetDataEndpointRequest
                    .builder()
                    .apiName(APIName.GET_MEDIA)
                    .streamName(streamName)
                    .build();

    // slow 3.5 seconds
    GetDataEndpointResponse endPointResponse = amazonKinesisVideo.getDataEndpoint(gder);
    String endPoint = endPointResponse.dataEndpoint();

    KinesisVideoMediaClient amazonKinesisVideoMedia = KinesisVideoMediaClient
            .builder()
            .region(region)
            .endpointOverride(URI.create(endPoint))
            .build();
```

### Current behavior

Those lines of code take 8 seconds to run, before I even start reading from the stream.

### AWS Java SDK version used

2.11.0

### JDK version used

openjdk version "11.0.14.1" 2022-02-08 LTS OpenJDK Runtime Environment Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.14.10.1 (build 11.0.14.1+10-LTS, mixed mode)

### Operating System and version

Mac OS 12.2.1, Apple Silicon

**Comment by shearn89** [comment]
I've created a simple demo repo [here](https://github.com/shearn89/kinesisLibraryTest).

**Comment by shearn89** [comment]
This looks to be a cold start issue, and is also improved by throwing more memory at the lambda. If I increase the RAM of the demo repo to 1024 or 2048, it starts a lot quicker. I've done some further optimizations in a branch, and can reduce the time further.

**Comment by debora-ito** [comment]
Hi @shearn89 you got it, it's a cold start issue. We listed some actions you can make to reduce startup time in Lambda in this blog post: [Tuning the AWS Java SDK 2.x to reduce startup time](https://aws.amazon.com/blogs/developer/tuning-the-aws-java-sdk-2-x-to-reduce-startup-time).

Let us know if this hels.

**Comment by shearn89** [comment]
Thanks @debora-ito - I'd already read that but re-reading it actually I think solves a problem I hit today, so that's perfect! I'll check I'm doing all those other optimizations to get the most out of it. I'll mark this as closed.
