### ISSUE TITLE
How to read current region and partition

### ISSUE THREAD

**Issue by reegnz** [aws/aws-sdk-java-v2#3078]
### Describe the issue

In AWS SDK for Java V1 there was this simple way of getting access to region metadata, which was:

```java
Region region = Regions.getCurrentRegion()
```

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html

I can't find any equivalent way for AWS SDK for Java V2.

### Links

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html

**Comment by debora-ito** [comment]
@reegnz `Regions.getCurrentRegion()` does not have an equivalent in v2.

There's a feature request to create a EC2 Metadata client, we are tracking here: https://github.com/aws/aws-sdk-java-v2/issues/61. Make sure you add a 👍 in the original description if you want to support it.

**Comment by reegnz** [comment]
In the end I've done it with `DefaultAwsRegionProviderChain`, it seems like the region also uniquely identifies the partition.
I've also done some other client metadata discovery to find the partition in the example code below (getting the partition is also possible from the caller identity ARN):

```java
import software.amazon.awssdk.arns.Arn;
import software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain;
import software.amazon.awssdk.services.sts.StsClient;

public class SdkV2 {

    public static void print() {
        final var regionProvider = DefaultAwsRegionProviderChain.builder().build();
        final var region = regionProvider.getRegion();
        System.out.println("[SDKv2] Region: " + region.id());
        System.out.println("[SDKv2] Partition (from Region): " + region.metadata().partition().id());
        final var cli = StsClient.create();
        final var identity = cli.getCallerIdentity();
        System.out.println("[SDKv2] UserId: " + identity.userId());
        System.out.println("[SDKv2] Account: " + identity.account());
        final var arn = Arn.fromString(identity.arn());
        System.out.println("[SDKv2] Partition (from Identity): " + arn.partition());
    }
}
```
