### ISSUE TITLE
semantic versioning breakage in patch versions

### ISSUE THREAD

**Issue by BusyByte** [aws/aws-sdk-java-v2#3087]
### Describe the bug

Semantic versioning break in patch versions.
We had a library depending on an older version of s3 differing by patch version only.
We had the service using a newer version of other AWS libraries on a newer AWS version differing by patch version only.
Looking into the issue it seems that regions was moved from an internal api to a public one and that S3 depended on an internal api of Regions.
When this happened a semantic versioning dictates you need to change the major version.
We were using regions version 2.17.133 with S3 version 2.17.107.
S3 version 2.17.1017  depended on version 2.17.107 of regions.  
Since this is a patch change dependency management said it should be fine and I agree given the patch version differences.
It was a mistake for s3 to depend on internal api of regions which is a good change moving it onto the public but it broke things compiled against older versions of s3. 
Here's the eviction report for regions to demonstrate:
[info]  * software.amazon.awssdk:regions:2.17.133 is selected over {2.17.107, 2.17.107}
[info]         +- software.amazon.awssdk:sqs:2.17.133                (depends on 2.17.133)
[info]         +- software.amazon.awssdk:secretsmanager:2.17.133     (depends on 2.17.133)
[info]         +- software.amazon.awssdk:sns:2.17.133                (depends on 2.17.133)
[info]         +- software.amazon.awssdk:sts:2.17.133                (depends on 2.17.133)
[info]         +- software.amazon.awssdk:auth:2.17.133               (depends on 2.17.133)
[info]         +- software.amazon.awssdk:aws-core:2.17.133           (depends on 2.17.133)
[info]         +- software.amazon.awssdk:s3:2.17.107                 (depends on 2.17.107)

If it were truly a patch then we should not see breakage.

### Expected behavior

Breakage in public api usage should only occur in major version changes.
We should have not seen errors from using regions 2.17.133 with libraries compiled against 2.17.107.

### Current behavior

We received many NoClassDefFoundError

### Steps to Reproduce

Have code in a library compiled against S3 version 2.17.107
Have a service which pulls in the above library but depends on sqs version 2.17.133 but not directly on s3

### Possible Solution

We had to go back and re-release our library on a newer version of the s3 sdk and then deploy our application.  This fixed the problem.
However I would like developers to learn from this and not repeat this breakage in the future and to follow [semantic versioning](https://semver.org/) more strictly.
Perhaps you could use something like the [Mima Plugin](https://github.com/lightbend/mima) in your continuous delivery pipeline to prevent this in the future.

### Context

We received many errors:

j.l.NoClassDefFoundError: software/amazon/awssdk/regions/internal/util/RegionScope
	at s.a.a.s.s.i.h.EndpointAddressInterceptor.modifyHttpRequest(EndpointAddressInterceptor.java:74)
	at s.a.a.c.i.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at s.a.a.c.i.h.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:139)
	at s.a.a.c.i.h.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:77)
	at s.a.a.c.i.h.BaseSyncClientHandler.doExecute(BaseSyncClientHandler.java:151)
	at s.a.a.c.i.h.BaseSyncClientHandler.lambda$execute$1(BaseSyncClientHandler.java:82)
	at s.a.a.c.i.h.BaseSyncClientHandler.measureApiCallSuccess(BaseSyncClientHandler.java:175)
	at s.a.a.c.i.h.BaseSyncClientHandler.execute(BaseSyncClientHandler.java:76)
	at s.a.a.c.c.h.SdkSyncClientHandler.execute(SdkSyncClientHandler.java:45)
	at s.a.a.a.c.h.AwsSyncClientHandler.execute(AwsSyncClientHandler.java:56)
	at s.a.a.s.s.DefaultS3Client.putObject(DefaultS3Client.java:8949)

### AWS Java SDK version used

2.17.133, 2.17.107

### JDK version used

AWS Coretto 8

### Operating System and version

Linux Container

**Comment by debora-ito** [comment]
HI @BusyByte thank you for the callout, I'll bring up the RegionScope change to the team and discuss if it should have changed the SDK version to 2.18.

That said, we don't recommend mixing versions of the SDK modules, even patch versions, as it can lead to runtime exceptions such as NoClassDefFoundError. Service modules depend on core modules like aws-core and regions, and if core and service versions don't match we cannot predict the application behavior. Ideally, all the modules should be in the same version, and using the BOM artifactId can help with this - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/setup-project-maven.html#sdk-as-dependency 

 We do use [japicmp](https://siom79.github.io/japicmp/) which seems similar to Mima.

**Comment by debora-ito** [comment]
Confirmed, it was an oversight, we should've bumped up the version to 2.18 with the RegionScope change.

We'll be more careful going forward. Hopefully this kind of issue will be avoided once we implement the Java 9 modularization.

Thank you again for reaching out. Let us know if you have more questions.
