### ISSUE TITLE
Poor performance of TransferManager downloadDirectory

### ISSUE THREAD

**Issue by saso5** [aws/aws-sdk-java-v2#3092]
### Describe the issue

`TransferManager.downloadDirectory` execution is really slow in comparison with AWS CLI execution.  

I believe the performance is due to sequential file download. Adding an option of parallel execution would speed the download significantly (setting the S3TransferManagerOverrideConfiguration executor does not help).  

### Steps to Reproduce

By replacing the code in DownloadDirectoryHelper.doDownloadDirectory with this code snippet, the download speed increases significantly.  

```
private void doDownloadDirectory(DownloadDirectoryRequest downloadDirectoryRequest) {
	String bucket = downloadDirectoryRequest.bucket();
	String delimiter = downloadDirectoryRequest.delimiter().orElse(null);
	String prefix = downloadDirectoryRequest.prefix().orElse(DEFAULT_PREFIX);

	ListObjectsV2Request request = ListObjectsV2Request.builder()
		.bucket(bucket)
		.prefix(prefix)
		.delimiter(delimiter)
		.build();

	Queue<FailedFileDownload> failedFileDownloads = new ConcurrentLinkedQueue<>();

	List<CompletableFuture<CompletedFileDownload>> filesToDownload = Collections.synchronizedList(
		new ArrayList<>());

	listObjectsHelper.listS3ObjectsRecursively(request)
		.map(s3Object -> determineDestinationPath(downloadDirectoryRequest, s3Object))
		.filter(downloadDirectoryRequest.filter())
		.subscribe(dfc -> filesToDownload.add(
			downloadSingleFile(downloadDirectoryRequest, failedFileDownloads, dfc, transferManager)))
		.join();

	CompletableFuture.allOf(filesToDownload.toArray(new CompletableFuture[0])).join();
}
```

### Current behavior

Slow download speed

### AWS Java SDK version used

s3-transfer-manager:2.17.146-PREVIEW

### JDK version used

Java 11

### Operating System and version

Windows 10

**Comment by saso5** [comment]
🙇‍♂️

**Comment by nithril** [comment]
@saso5, out of curiosity, does the fix solve your issue?

**Comment by saso5** [comment]
@nithril yes it is much faster now
