### ISSUE TITLE
Refactor: Profile File Support

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#31]
Review the inherited state of V1 profile file support and determine which changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by uriahcarpenter** [comment]
Parity with the CLI configuration would be very helpful. I added some details and a workaround in https://github.com/aws/aws-sdk-java/issues/803

**Comment by clintoncampbell** [comment]
- Should be able to read `role_arn` and `mfa_serial` properly from .aws/config 
- Implement a default stdin MFA input provider as with the other SDKs, e.g., https://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/#StdinTokenProvider

**Comment by shorea** [comment]
Implemented
