### ISSUE TITLE
Facing BatchResultErrorEntry(Id= {some-value} , SenderFault=true, Code=ReceiptHandleIsInvalid, Message=The receipt handle {some-value} is not valid for this queue.))

### ISSUE THREAD

**Issue by sharmanalin59** [aws/aws-sdk-java-v2#3101]
### Describe the bug

We are polling (async) using aws 2 java sdk, and deleting async but facing 

```
BatchResultErrorEntry(Id=
b44c34dc-7996-4484-9380-030dea2b299c
, SenderFault=true, Code=ReceiptHandleIsInvalid, Message=The receipt handle 
"AQEBkjED7Xgp6B53esXUf/WHmV95+u/aECqESTJxPflwwHN0icHW7fVT5+BzRgtolaZWhKNygi6AFdQGEAQ//t4zG6wioKhk4HgZqK+HFMUGObc9Hh8pGabDIyaK7z7mDbP2MNWChRdiYEwr8jd4uTbi8CHPw9p8JxEL2fPRbp/yJ4R6na+xJahqy/wIwMFys+dhjGsNgh9HUSoLu/QR9/6GCW94OF8yXa1KH2cprHa7FDy5vewAyfeiQHNADwRVTQhluVD3dh6H9lgNNvGm9jFWzT4fHg3s3CGlSpvYEOd+YWanOJU8jM1QXxHXskjD3CyUEMB31AkmJH72pjoROmHxMhQdv+x5FxTyRFkRlLjYCRDjL1wMT5z/YDBH8A7yCRHfyJFoajkpqbgNK4GX9ZP1zZe4qF4WdbTq1qYU5vGXPhI=" is not valid for this queue.)
```
code to batch receive-:
`awsSqsAsyncClient.receiveMessage(receiveMessageRequest)`
code to batch delete-:
`awsSqsAsyncClient.deleteMessageBatch(deleteMessageBatchRequest)`

ReceiptHandle and messageId are being sent in deleteMessageBatchRequest.
 
Sqs has 30 sec visibility timeout, we are overriding it with 300, and time taken between fetch and delete is under 100 ms. We are getting BatchResultErrorEntry with some failed and some success on every request. Even after retrying one more time we are still getting many failures(many failed many success with 200 Http status) Why is this happening?

### Expected behavior

Expect failed entries to be low

### Current behavior

Failed entries are higher even after retrying batch delete

### Steps to Reproduce

Code sample share above

### AWS Java SDK version used

2.17.101

### JDK version used

8

### Operating System and version

mac os, amazon linux ec2

**Comment by debora-ito** [comment]
@sharmanalin59 not sure what could the cause, besides the receipt handle being invalid. Are you using SQS in Lambda? I found some references that might help:
- https://aws.amazon.com/premiumsupport/knowledge-center/sqs-receipt-handle-error/
- https://www.reddit.com/r/aws/comments/chyspx/is_my_lambda_processing_duplicate_messages_from_a/
