### ISSUE TITLE
Resource conflict from 's3' and 'sts' module

### ISSUE THREAD

**Issue by linzebing** [aws/aws-sdk-java-v2#3107]
### Describe the issue

I'm trying to add `software.amazon.awssdk:sts` dependency to my pom.xml, as usage of `WebIdentityTokenFileCredentialsProvider ` requires `sts` module on the class path https://github.com/aws/aws-sdk-java-v2/blob/7121f4fa604a1863b866bce7ea0d07d986db40a1/core/auth/src/main/java/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.java#L29-L34.

However, this created a resource conflict with `software.amazon.awssdk:s3`:
```
[INFO] --- duplicate-finder-maven-plugin:1.5.0:check (default) @ trino-exchange ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different resources in [software.amazon.awssdk:s3:2.17.102, software.amazon.awssdk:sts:2.17.102]:
[WARNING]   codegen-resources/customization.config
[WARNING]   codegen-resources/paginators-1.json
[WARNING]   codegen-resources/service-2.json
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate and different resources in [software.amazon.awssdk:s3:2.17.102, software.amazon.awssdk:sts:2.17.102]:
[WARNING]   codegen-resources/customization.config
[WARNING]   codegen-resources/paginators-1.json
[WARNING]   codegen-resources/service-2.json
[WARNING] Found duplicate classes/resources in test classpath.
```

I guess it's pretty common to have `software.amazon.awssdk:s3` and `software.amazon.awssdk:sts` together as dependencies, what's the best approach I should take here?

### Steps to Reproduce

Include `software.amazon.awssdk:s3` and `software.amazon.awssdk:sts` in any maven project with `duplicate-finder-maven-plugin`

### Current behavior

```
[INFO] --- duplicate-finder-maven-plugin:1.5.0:check (default) @ trino-exchange ---
[INFO] Checking compile classpath
[INFO] Checking runtime classpath
[INFO] Checking test classpath
[WARNING] Found duplicate and different resources in [software.amazon.awssdk:s3:2.17.102, software.amazon.awssdk:sts:2.17.102]:
[WARNING]   codegen-resources/customization.config
[WARNING]   codegen-resources/paginators-1.json
[WARNING]   codegen-resources/service-2.json
[WARNING] Found duplicate classes/resources in runtime classpath.
[WARNING] Found duplicate and different resources in [software.amazon.awssdk:s3:2.17.102, software.amazon.awssdk:sts:2.17.102]:
[WARNING]   codegen-resources/customization.config
[WARNING]   codegen-resources/paginators-1.json
[WARNING]   codegen-resources/service-2.json
[WARNING] Found duplicate classes/resources in test classpath.
```

### AWS Java SDK version used

2.17.102

### JDK version used

openjdk 11.0.12 2021-07-20 OpenJDK Runtime Environment Homebrew (build 11.0.12+0) OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Operating System and version

MacOS Monterrey

**Comment by linzebing** [comment]
Doesn't seem to be an issue anymore after I upgraded to 2.17.151

**Comment by debora-ito** [comment]
@linzebing starting in SDK version `2.17.131` we removed the codegen-resources from the service jars (https://github.com/aws/aws-sdk-java-v2/pull/3030), `duplicate-finder-maven-plugin` should stop finding the conflicts.

Those files are used to generate the service clients, they're unique for each service module. For example: 
- S3 resources: https://github.com/aws/aws-sdk-java-v2/tree/master/services/s3/src/main/resources/codegen-resources
- STS resources: https://github.com/aws/aws-sdk-java-v2/tree/master/services/sts/src/main/resources/codegen-resources

So even though `duplicate-finder-maven-plugin` flags them as duplicate they're not.
