### ISSUE TITLE
Add configuration to overwrite existing file in S3TransferManager.downloadFile

### ISSUE THREAD

**Issue by TheKeveloper** [aws/aws-sdk-java-v2#3108]
### Describe the feature

Add a configuration option in `DownloadFileRequest` to overwrite the existing local file if it already exists. Currently if the destination file already exists locally, an exception is thrown. 

This seems similar to this PR: https://github.com/aws/aws-sdk-java-v2/pull/2595 and this corresponding issue: https://github.com/aws/aws-sdk-java-v2/issues/2300

### Is your Feature Request related to a problem?

I often need to retrieve a file from S3 that may have been updated and use that to update my local copy of the file. This feature existed in the v1 sdk but does not seem to exist in the v2 sdk.

One way around this is by saving to a temp file and then moving the temp file to replace the existing file. However, this requires a lot of additional effort to make sure that the temp file gets cleaned up properly.

Another possibility is to use a `getObject` request with `AsyncResponseTransformer.toBytes()` and doing a `Files.copy` on the `InputStream` with `StandardCopyOptions.REPLACE_EXISTING`. However, this doesn't allow using TransferManager and seems like a level of abstraction that should already exist. 

### Proposed Solution

It seems like merging https://github.com/aws/aws-sdk-java-v2/pull/2595 would be a good first step, and then just configuring TransferManager to use the corresponding `toFile` implementation based on a configuration option in the `DownloadFileRequest` should get us there. 

### Acknowledge

- [X] I may be able to implement this feature request

### AWS Java SDK version used

2.17.151-PREVIEW

### JDK version used

15.0.3

### Operating System and version

MacOSX 10.15.7

**Comment by zoewangg** [comment]
Hi @TheKeveloper, good timing! We are working on this feature right now. We are planning to make overwriting existing file the default behavior in the TM since it seems to be more intuitive.

**Comment by zoewangg** [comment]
We have changed the default behavior to replacing existing file if it exists in the transfer manager. This change has been released in `2.17.179`.  This behavior can be configured in `FileTransformerConfiguration` https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/FileTransformerConfiguration.java
