### ISSUE TITLE
Adding software.amazon.awssdk Streaming Transcribe causes duplicate duplicaterelativefileexception(short issue description)

### ISSUE THREAD

**Issue by taouichaimaa** [aws/aws-sdk-java-v2#3109]
### Describe the bug

I've added `implementation("software.amazon.awssdk:transcribestreaming:2.17.121")` in my gradle to use the transcribeStreaming service in my android app. However, it's causing an exception during build:

`DuplicateRelativeFileException: 10 files found with path 'META-INF/io.netty.versions.properties' from inputs:`
the inputs are ten files . I've tried using the exclude packaging options like this:

```
 packagingOptions {
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/io.netty.versions.properties'
        exclude 'META-INF/DEPENDENCIES'
        }
```
But I'm using cameraX and it must need something from netty because it gives :

`no implementation found for int io.netty.internal.tcnative.library.aprmajorversion() (tried java_io_netty_internal_tcnative_library_aprmajorversion and java_io_netty_internal_tcnative_library_aprmajorversion__)`
and the app crashes after it. I deleted the amazon dependency from my build and the camera works correctly. Any idea on how can I fix this?

### Expected behavior

add `implementation("software.amazon.awssdk:transcribestreaming:2.17.121")` in gradle
run app
no crash

### Current behavior

On run, when the camera starts, the app crashes with this error: 
`no implementation found for int io.netty.internal.tcnative.library.aprmajorversion() (tried java_io_netty_internal_tcnative_library_aprmajorversion and java_io_netty_internal_tcnative_library_aprmajorversion__)`

### Steps to Reproduce

add `implementation("software.amazon.awssdk:transcribestreaming:2.17.121")`
add   implementation 'androidx.camera:camera-view:1.0.0-alpha32'
    implementation 'androidx.camera:camera-video:1.1.0-alpha12'
    implementation 'androidx.camera:camera-lifecycle:1.1.0-alpha12'
    implementation "androidx.camera:camera-camera2:1.1.0-alpha12"
build

### AWS Java SDK version used

com.amazonaws:aws-android-sdk-core:2.38.0"

### JDK version used

11

### Operating System and version

mac-OS

**Comment by debora-ito** [comment]
@taouichaimaa can you share the full exception?

**Comment by taouichaimaa** [comment]
Hi, that is the full exception. What follows are the names of the files duplicated.

**Comment by debora-ito** [comment]
Well, can you provide the list of the files?
