### ISSUE TITLE
How to describe single stack using DescribeStacks API

### ISSUE THREAD

**Issue by lakmehdi** [aws/aws-sdk-java-v2#3116]
### Describe the issue

Hi, 

I am trying to describe a particular stack using DescribeStacks API in order to get the stack's outputs.

It is unclear from the documentation how the StackName parameter works with pagination. 

Does the API generate the pages and only then filter them based on stack name, in which case we may receive an empty page followed by the page actually containing our stack, or does it guarantee that the stack we are looking for is always in the first page?

### Links

https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStacks.html

**Comment by debora-ito** [comment]
@lakmehdi If you provide a `StackName` it will return the description of that specific stack.

**Comment by lakmehdi** [comment]
Thank you, just to confirm that means it will always return a single page and nextToken in the response will always be null?

**Comment by debora-ito** [comment]
That's what the documentation says, yes.

**Comment by lakmehdi** [comment]
Thanks. Can you point me exactly to where the documentation says this? Maybe I misread it?

**Comment by debora-ito** [comment]
https://docs.aws.amazon.com/AWSCloudFormation/latest/APIReference/API_DescribeStacks.html

> DescribeStacks
>
>Returns the description for the specified stack; if no stack name was specified, then it returns the description for all the stacks created.

>Response Elements
>
>NextToken
If the output exceeds 1 MB in size, a string that identifies the next page of stacks. If no additional page exists, this value is null.

Closing this, feel free to reach out if you have any other question regarding the AWS SDK for Java.
