### ISSUE TITLE
Is parallel uploading possible in uploadDirectory?

### ISSUE THREAD

**Issue by jingjingeatmore** [aws/aws-sdk-java-v2#3117]
### Describe the issue

Hi!
I was wondering is uploadDirectory parallelized?  I know that downloadDirectory is parallelized with max concurrency of 100 as in #3092 , may I inquire whether it is the same for uploadDirectory?
I checked the code in DownloadDirectoryHelper.java#downloadDirectory() and it looks like all uploads will be done with single thread, and I didn't find relevant configurations on concurrency.
If concurrency is supported, would you please guide me to the related configuration? 

### Steps to Reproduce

NA

### Current behavior

When uploading a directory with uploadDirectory, it seems all uploads were handled by a single thread.

### AWS Java SDK version used

2.17.151-PREVIEW

### JDK version used

1.8.0_291

### Operating System and version

MacOS 11.4

**Comment by zoewangg** [comment]
Hi @jingjingeatmore, uploadDirectory does send requests in parallel. As you can see from the code below, Transfer Manager sends out requests as it walks the file tree. There's no limit on the concurrency right now; it really depends on how fast Java directory traversal is. We may consider adding a limit if there is such feature request.

https://github.com/aws/aws-sdk-java-v2/blob/c8c1fd4a138d8602cd2905b0f59d2a3913efb5df/services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/UploadDirectoryHelper.java#L109-L117

**Comment by jingjingeatmore** [comment]
Hi @zoewangg , thanks for the reply! I could be wrong but here is how I am understanding the code and what I discovered with my testing.
I know that we are sending out upload request in a non-blocking way as we are walking through the file directory - we are utilizing Files.walk if we want to upload a directory recursively. From my searching online, it seems Files.walk itself is not parallelized. Does that mean we are sending out request as walking the file tree, but all requests are handled by a single thread?
I did tests with the following code for upload:
```java
private static void uploadFilesWithTransferManager(String prefix) {
        String baseDir = "<mypath_to_dir>";
        S3ClientConfiguration s3ClientConfiguration = S3ClientConfiguration.builder()
                .credentialsProvider(getCredentialProvider(accessKey, secretKey)).region(region).build();
        S3TransferManager tm = S3TransferManager.builder().s3ClientConfiguration(s3ClientConfiguration).build();
        UploadDirectoryRequest uploadDirectoryRequest = UploadDirectoryRequest.builder()
                .sourceDirectory(Paths.get(baseDir)).bucket(bucketName).prefix(prefix).build();
        CompletedDirectoryUpload completedUpload = tm.uploadDirectory(uploadDirectoryRequest).completionFuture().join();
    }
```
and I noticed all requests are handled by one thread.
Compared to downloadDirectory:
```java
public static void downloadDir() {
    S3ClientConfiguration s3ClientConfiguration = S3ClientConfiguration.builder()
            .credentialsProvider(getCredentialProvider(accessKey, secretKey)).region(region).build();
    S3TransferManager tm = S3TransferManager.builder().s3ClientConfiguration(s3ClientConfiguration).build();
    DownloadDirectoryRequest downloadDirectoryRequest = DownloadDirectoryRequest.builder()
            .bucket(bucketName)
            .prefix("someprefix")
            .destinationDirectory(Paths.get("<my_local_dir>")).build();
    CompletedDirectoryDownload completedDirectoryDownload = tm.downloadDirectory(downloadDirectoryRequest).completionFuture().join();
  }
```
and requests are handled by different threads from logs.

Please let me know if I am misunderstanding things, and thanks for helping!

**Comment by zoewangg** [comment]
Yes, your understanding is correct. Directory traversal and invoking uploadFile (return immediately) are done in one thread, and under the hood, uploadFile requests are executed by event loop threads, so there could be multiple in-flight requests.

**Comment by jingjingeatmore** [comment]
Thanks @zoewangg !!
