### ISSUE TITLE
Equivalent of ClientConfiguration::setCacheResponseMetadata ?

### ISSUE THREAD

**Issue by daveagill** [aws/aws-sdk-java-v2#3121]
### Describe the issue

Hi,

I am migrating from the V1 to the V2 SDK and cannot find the equivalent of setCacheResponseMetadata.

I want to disable any caching because we do no need the debug data.

Is there a way to do this in the V2 SDK?

I do not see anything to indicate this was moved, removed or renamed so I expected to find something similar to it in ClientOverrideConfiguration and maybe it does belong there but I am unsure how to set it.

### Steps to Reproduce

N/A

### Current behavior

N/A

### AWS Java SDK version used

N/A

### JDK version used

N/A

### Operating System and version

N/A

**Comment by zoewangg** [comment]
Hi @daveagill, we don't cache response metadata anymore in the Java SDK v2 :), so you don't need to disable it.
