### ISSUE TITLE
Some CloudWatch APIs return exception "timestamp must follow ISO8601" when running on JRE11

### ISSUE THREAD

**Issue by umike72** [aws/aws-sdk-java-v2#3126]
### Describe the bug

I've hit an odd bug whereby attempting to retrieve metrics from cloudwatch would always return this exception when developing a simple application on top of JRE 11:

```
timestamp must follow ISO8601
software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: 09247139-5874-4393-9b7d-06987cc79c8a)
```
I've then noticed that the error doesn't occur when the very same code is run on JRE8. This behavior can also be reproduced with CloudWatch sample code, for example the GetMetricData example.

The error occurs on JRE OpenJDK 64-Bit Server VM Microsoft-22268 (build 11.0.11+9, mixed mode). I suspect that there might haven been changes between JRE in how Instant gets de-serialized?

### Expected behavior

The exception should not be thrown.

### Current behavior

When running on JRE 11, the exception

software.amazon.awssdk.services.cloudwatch.model.CloudWatchException: timestamp must follow ISO8601 (Service: CloudWatch, Status Code: 400, Request ID: 09247139-5874-4393-9b7d-06987cc79c8a)

is thrown.

### Steps to Reproduce

Try to execute the sample application 

https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/cloudwatch/src/main/java/com/example/cloudwatch/GetMetricData.java

on JRE 11. You should then be able to reproduce the issue.

### AWS Java SDK version used

2.17.143

### JDK version used

OpenJDK 64-Bit Server VM Microsoft-22268 (build 11.0.11+9, mixed mode

### Operating System and version

Windows 10

**Comment by brharrington** [comment]
See https://github.com/aws/aws-sdk-java-v2/issues/1820

**Comment by debora-ito** [comment]
@umike72 thank you for the detailed analysis. Yes, it's the same issue reported in #1820, the workaround is to truncate the value:
```
Instant endTime = Instant.now().truncatedTo(ChronoUnit.MILLIS);
```

I'll go ahead and close this one since it's a duplicate, let's keep track of this issue in one place
