### ISSUE TITLE
 Support Uploading to S3 using an OutputStream

### ISSUE THREAD

**Issue by SamStephens** [aws/aws-sdk-java-v2#3131]
### Describe the feature

Provide the ability for the S3 client to expose an OutputStream that can be written to in order to write to a S3 object.

It appears that it's a fairly normal idiom for a class to expose a save/write method that takes an OutputStream parameter in order to allow the class to serialize something to a stream.

Note this was previously discussed a few years ago via https://github.com/aws/aws-sdk-java/issues/1139, however the discussion never really went anywhere, and no one really tried to justify this as a feature. I've created this as a new Issue as the last issue was treated as a request for guidance rather than a feature request.

### Is your Feature Request related to a problem?

I've found in two Java Lambdas I've recently been working on, I have a component that wants to write its output to an OutputStream. I'm having to hack around the fact S3 only will accept an InputStream by using the workaround shown at https://stackoverflow.com/a/36961688/792238.

One is writing an image to S3 using [ImageIO#write](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/javax/imageio/ImageIO.html#write(java.awt.image.RenderedImage,java.lang.String,java.io.OutputStream)).

The other is writing a PDF document using [PDDocument#save](https://pdfbox.apache.org/docs/2.0.13/javadocs/org/apache/pdfbox/pdmodel/PDDocument.html#save-java.io.OutputStream-).

Currently the hack looks something like:

```
    public static class CopyStream extends ByteArrayOutputStream {
        public CopyStream() { super(); }

        public InputStream toInputStream() {
            return new ByteArrayInputStream(this.buf, 0, this.count);
        }

        public int size() {
            return this.count;
        }
    }

[...]

        PDFDocument outputDocument = generateDocument();
        CopyStream outputStream = new CopyStream();
        outputDocument.save(outputStream);
        outputDocument.close();
        InputStream inputStream = outputStream.toInputStream();
        long size = outputStream.size();
        // Do S3 upload using inputStream and size
```

### Proposed Solution

I'm not super familiar with Java streams and the correct idioms to use, but I'm guessing that we'd want usage to be something like this:

```
        PDFDocument outputDocument = generateDocument();
        PutObjectRequest putRequest = buildS3PutRequest();

        try (OutputStream outputStream = S3_CLIENT.putObjectOutputStream(putRequest)) {
            outputDocument.save(outputStream);
            outputDocument.close();
        }
```

### Describe alternatives you've considered

The only other alternative I can see is the kind of hack I'm currently having to use.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2.17.44

### JDK version used

11

### Operating System and version

AWS Lambda

**Comment by SamStephens** [comment]
Replaces https://github.com/aws/aws-sdk-java-v2/issues/3131, which was creating against the wrong repository.

**Comment by debora-ito** [comment]
@SamStephens thank you for opening a new issue in v2. We got the same request in https://github.com/aws/aws-sdk-java-v2/issues/3128 and I believe it's asking for the same feature.

If so, I'll mark this to auto-close soon so we keep track of the feature in one place.

**Comment by SamStephens** [comment]
> @SamStephens thank you for opening a new issue in v2. We got the same request in #3128 and I believe it's asking for the same feature.
> 
> If so, I'll mark this to auto-close soon so we keep track of the feature in one place.

I agree, this is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/3128. Closing this. Thanks.
