### ISSUE TITLE
AWS SDK API call failure metrics

### ISSUE THREAD

**Issue by HimalayPatel** [aws/aws-sdk-java-v2#3134]
### Describe the issue

Hello, I was setting up monitoring for one of our dependencies - AWS AppConfig, specifically on Availability, Latency and Retries. I am using AWS SDK metrics to do this.
I am using `ApiCallDuration` as latency metrics and `RetryCount` for retries, but since there is no straightforward metric for Availability, I am using the `ApiCallSuccessful` metric. Taking the `SampleCount` of `ApiCallSuccessful` metric ( from and subtracting that with the `Sum` of the same metric, since `ApiCallSuccessful` is a boolean metric and it being 0 means the API call failed. See attached screenshot.

When I do this, I see several failed calls regularly and consistently (about 32 every 2 minutes). I checked all our service logs and there are no signs of any failed calls.

Does this mean there is a bug in how these metrics are collected? Or this isn't how these metrics are supposed to be used? Please let me know how I get Availability metrics reliably using this.
<img width="1537" alt="Screen Shot 2022-03-28 at 12 21 41 PM" src="https://user-images.githubusercontent.com/12826166/160687648-b7aaccdd-8420-4b32-a825-cb4b0684339e.png">

### Steps to Reproduce

Not completely sure if this is a bug.

### Current behavior

32 "errors" every 2 minutes on reverting `ApiCallSuccessful` metric and using it as a failed calls metric, but no corresponding errors anywhere in the logs.

### AWS Java SDK version used

2

### JDK version used

1.8

### Operating System and version

Amazon Linux 2

**Comment by HimalayPatel** [comment]
Hi @debora-ito, all the operations are AWS AppConfig's `GetConfiguration` operation. So yes, all the `ApiCallSuccessful` = false (as well as `ApiCallSuccessful` = true) are for the same operation. Also I checked client-side logs but there is no indication whatsoever of any failed calls.
We only have dimensions for `OperationName` and `ServiceId`, not `HttpStatusCode` as you say. Is there a way to turn it on?

**Comment by debora-ito** [comment]
@HimalayPatel if you're using the default CloudWatchMetricPublisher you should be getting `HttpStatusCode` - see the list of metrics here: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics-list.html

Sorry for the long delay in reply.

**Comment by debora-ito** [comment]
Thank you for the follow-up.
