### ISSUE TITLE
Export/Import table definition as JSON

### ISSUE THREAD

**Issue by wise-coders** [aws/aws-sdk-java-v2#3144]
### Describe the feature

For automation reasons, we would like to be able to export and import the table definition as JSON. 
We would like to export/import from Java. Is this possible?

### Is your Feature Request related to a problem?

Automation request. Also, it would be a standard in manipulating the table definition as String from Java.

### Acknowledge

- [ ] I may be able to implement this feature request

### AWS Java SDK version used

2

### JDK version used

15

### Operating System and version

Windows 10

**Comment by yasminetalby** [comment]
Hello @wise-coders ,

Thank you very much for your submission.
I apologize for the delay of answer. If this is still a feature you would be interested in, could you please describe in detail your use case and need for this feature?

My understanding is that you are talking about a new feature for DynamoDB for the AWS Java SDK v2 similar to what is described here for the .NET SDK : https://docs.aws.amazon.com/sdk-for-net/v3/developer-guide/dynamodb-json.html

Thank you very much for your time and collaboration. We really appreciate your feedback and input on the AWS Java SDK.

Sincerely,

Yasmine

**Comment by yasminetalby** [comment]
Hello @wise-coders ,

Thank you very much for the specification.
This is not currently supported by the AWS Java SDK v1 and v2. This feature-request will be discussed by the team and I will post an update here

Best regards,

Yasmine.

**Comment by yasminetalby** [comment]
Hello @wise-coders ,

I have brought up the feature request to the team for review as potential new feature to the SDK.
This will not be added to our backlog at this time as we are focusing on feature request that have larger use cases and that there are existing work-around to the behavior.

I will close this request for now. 
However, if anyone want the AWS Java SDK v2 to support this feature you can showcase your interest by upvoting this submission using the 👍 reaction.

We really appreciate your feature request. Thank you very much for your submission.
 
Sincerely,

Yasmine
