### ISSUE TITLE
SQS attributeNames not pulling out the values

### ISSUE THREAD

**Issue by Miriam-Asenjo** [aws/aws-sdk-java-v2#3148]
### Describe the bug

I am trying to retrieve the attribute "ApproximateReceiveCount" out of a SQS Message when receiving the message but I always get a null value

### Expected behavior

I would expect attribute ApproximateReceiveCount to give me the number of times a message has been received across all queues but not deleted.

### Current behavior

The value of attribute ApproximateReceiveCount is always null. 

### Steps to Reproduce

My ReceiveMessage code looks like the following 

	public Message ReceiveMessage(String queueUrl, int waitTimeSeconds, int visibilityTimeout)
	{

		ReceiveMessageRequest msgRequest= ReceiveMessageRequest.builder()
                .queueUrl(queueUrl)
                .attributeNamesWithStrings("ApproximateReceiveCount")
                .waitTimeSeconds(waitTimeSeconds)
                .visibilityTimeout(visibilityTimeout)
                .maxNumberOfMessages(1)
                .build();
		
		List<Message> msgs = this.sqsClient.receiveMessage(msgRequest).messages();
		
		if (!msgs.isEmpty())
			return msgs.get(0);
		
		return null;
		
	}

When trying to access the attribute from the message I got  it seems the attribute is there but the value is null

queueMessage = ReceiveMessage(this.requestsQueueUrl, 20, this.defaultVisibilityTimeout); 

 			
        		if (queueMessage != null) //message has been retrieved
        		{
        			System.out.println ("Accesing queMessage attributes");
        			if (queueMessage.hasAttributes())
        			{
        				
        				for (MessageSystemAttributeName keySet:queueMessage.attributes().keySet()){
        					System.out.println (keySet.toString() + " " + queueMessage.attributes().get(keySet.toString()));
        				}
        			}
                        }

Output is "ApproximateReceiveCount null"

### AWS Java SDK version used

2.17.102

### JDK version used

11

### Operating System and version

Dont apply

**Comment by debora-ito** [comment]
@Miriam-Asenjo null isn't a possible value in this case, were you expecting a value > 0?

If you enable the verbose wirelogs, they will show the values sent by the service in the response, and you can check if the value for `ApproximateReceiveCount` is null. For more info on how to enable wirelogs see: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

If you choose to provide us the wirelogs, please redact any sensitive information they may contain, like access key ids.
