### ISSUE TITLE
PathEncoding encodes special charaters like "@", but should not

### ISSUE THREAD

**Issue by matsluni** [aws/aws-sdk-java-v2#3154]
### Describe the bug

Hi,

I am investigating an issue, which was first raised in aws/aws-sdk-java-v2#3113 and also in matsluni/aws-spi-akka-http#164. 

It is about the `describeUser` operation in the `Quicksight` service. The issue occurs, if the provided `UserName` for the operation is e.g. an email address: "some@email.com". It works without problems in the Netty Async client (and also sync clients), but runs into an error in the [akka Http client](https://github.com/akka/akka-http) used in [aws-spi-akka-http](https://github.com/matsluni/aws-spi-akka-http). The problem which occurs is: `"The request signature we calculated does not match the signature you provided..."`

In the original issue report, the underlying problem of the different path encodings `some%40email.com` vs. `some@email.com` for the `describeUser` operation was also discovered, which leads to the request signing issue.

I looked further into this and could confirm that the akka-http client encodes an email address in a path (not a query) as `some@email.com`. 

The same is true for `java.net.URI`:
`URI.create("http://localhost:80/path-with-@gmail.com")` returns `/path-with-@gmail.com"` for `uri.getPath()`.

I also looked into https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 what characters in the path are allowed and to me the encoding of akka-http and java.net.URI seem to be according to the RFC.

For me it looks like the use of `SdkHttpUtils.urlEncode` in [PathMarshaller](https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/PathMarshaller.java#L63) encodes the `@`, where it should not.

Can you confirm from your side, that the path encoding has a bug on your side for some special characters like `@`?

### Expected Behavior

A path with a `@` character is not encoded. E.g. `some@email.com` 

### Current Behavior

A path with a `@` character is encoded. E.g. `some%40email.com` 

### Reproduction Steps

See the discussion and investigation steps in #3113.

### Possible Solution

For me it looks like the use of `SdkHttpUtils.urlEncode` in [PathMarshaller](https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/PathMarshaller.java#L63) encodes the `@`, where it should not.

### AWS Java SDK version used

2.17.48

### JDK version used

AdoptOpenJDK Java 14.0.2

### Operating System and version

MacOS 10.14.5

**Comment by debora-ito** [comment]
Hi @matsluni I don't understand the question. Yes, the SDK url-encodes special characters and it works fine when using the Netty Async client. Why are you saying the SDK should not encode?

**Comment by matsluni** [comment]
Hi @debora-ito,

thanks for your quick feedback.

Sorry, if I did not describe the problem understandable.

In my opinion the [PathMarshaller](https://github.com/aws/aws-sdk-java-v2/blob/master/core/protocols/protocol-core/src/main/java/software/amazon/awssdk/protocols/core/PathMarshaller.java#L63) is using logic for `path`-marshalling that is actually created for `query`-marshalling. I guess the error which was reported here #3113 is a rare case where special characters are used in the `path`, not in `query` parameters. Thats why it was probably not seen before.

If I take the Url from #3113 and the `describeUser` operation (`https://quicksight.us-west-2.amazonaws.com/accounts/xxx/namespaces/default/users/email@email.com`) and pass it to `java.net.URI#create`, alá `URI.create("https://quicksight.us-west-2.amazonaws.com/accounts/xxx/namespaces/default/users/email@email.com")` the email in the path is not encoded. 

If I try to do the same with `PathMarshaller`, e.g.: `PathMarshaller.NON_GREEDY.marshall("/accounts/xxx/namespaces/default/users/{UserName}", "UserName", "email@email.com")` this path is computed: `/accounts/xxx/namespaces/default/users/email%40email.com`.

The `PathMarshaller` is used to marshall the `path` according to my understanding of the code base.

In my opinion, looking specifically at the path marshalling logic should make the problem visible.

I hope I could clarify my situation a bit more and that specifically the `path`-marshalling logic encodes `@` where it according to https://datatracker.ietf.org/doc/html/rfc3986#section-3.3 should not do it, because a `@` is an allowed character in the path.

Thanks for your help.

**Comment by debora-ito** [comment]
I see it now, you're saying that according to RFC3986 `@` is a valid character in path so we shouldn't have to encode it.

The problem is that Quicksight expect it to be encoded as `email%40email.com` on the service side, as the logs in #3113 show:
```
The Canonical String for this request should have been
'GET
/accounts/ACCOUNT_ID/namespaces/default/users/some%40email.com
```

Not url-encoding `username` is the reason why you're seeing a signature error.

**Comment by matsluni** [comment]
Hi @debora-ito,

I am a bit surprised, that you removed the bug label. To me this still qualifies as a bug, as it is not http conform and breaks other clients such as the one I am mainaining https://github.com/matsluni/aws-spi-akka-http. The sdk might also be not aligned with the Go or JavaScript sdk.

Furthermore I wonder if the message `The Canonical String for this request should have been...` is really coming from the upstream server or is more a output from the signing code. But this is a bit of a guess.

**Comment by debora-ito** [comment]
`The Canonical String for this request should have been...` is the service response for a failed signature verification step. If the signature sent in the request does not match the signature expected by the service, the service respond with the canonical string they were expecting. You can read more about the Sigv4 process and troubleshooting here: https://docs.aws.amazon.com/general/latest/gr/signature-v4-troubleshooting.html

```
The Canonical String for this request should have been
'GET
/accounts/ACCOUNT_ID/namespaces/default/users/some%40email.com
```

In this case, it's Quicksight saying in the response that they were expecting the username `some@email.com` to be encoded as `some%40email.com`. The SDK native HTTP clients Apache and NettyNioAsync do the encoding, that's why we don't see signature errors and that's why I think it's not a bug on the SDK. The error is only seen when the aws-spi-akka-http client is used.

We could say that the current behavior in Quicksight is wrong and they should accept `some@email.com` in the path. Unfortunately this would be a breaking change and it won't be made.
