### ISSUE TITLE
EventBridge PutEvent Successful with Invalid EventBridge ARN or EventBus name

### ISSUE THREAD

**Issue by vkemthur-luna** [aws/aws-sdk-java-v2#3155]
### Describe the bug

Following this reference code to push event to EventBridge
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html

I configure an invalid EventBridge ARN in `resources` of `PutEventsRequestEntry`

 Iterate over `PutEventsResultEntry` and `eventId` is not null.

```
for (PutEventsResultEntry resultEntry : result.entries()) {
                if (resultEntry.eventId() != null) {
                    System.out.println("Event Id: " + resultEntry.eventId());
                } else {
                    System.out.println("Injection failed with Error Code: " + resultEntry.errorCode());
                }
            }
```

EventBridge is configured with a rule/target and event never reaches target as intended. 

Is there any way to handle this scenario better? Is the SDK expected to report a failure/ `errorCode` in this scenario.

As of now, if we treat presence of `eventId` as `success` - there is no guarantee that this event was successfully pushed to EventBridge.

### Expected Behavior

Error Code in `PutEventsResultEntry` based on a invalid EventBridge ARN configured in request.

### Current Behavior

Wrong resource configured in `PutEventsRequestEntry` does not fail the request.

### Reproduction Steps

https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/eventbridge/src/main/java/com/example/eventbridge/PutEvents.java

### AWS Java SDK version used

2.17.155

### JDK version used

17.0.2

### Operating System and version

MacOS Monterey

**Comment by debora-ito** [comment]
@vkemthur-luna thank you for reaching out.

The [PutEvents](https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-putevents.html) doc say that:

 "Each entry in the response array corresponds to an entry in the request array in order from the beginning to the end of the request and response".

```
{
    "FailedEntryCount": 1, 
    "Entries": [
        {
            "EventId": "11710aed-b79e-4468-a20b-bb3c0c3b4860"
        },
        {   "ErrorCode": "InternalFailure",
            "ErrorMessage": "Internal Service Failure"
        },
        {
            "EventId": "d804d26a-88db-4b66-9eaf-9a11c708ae82"
        }
    ]
}
```
The eventId that you received in the response was in the same position of the invalid ARN?
Have you checked the FailedEntryCount?

**Comment by vkemthur-luna** [comment]
`PutEventsRequest`
<img width="572" alt="image" src="https://user-images.githubusercontent.com/97245708/162499827-2354277b-d19a-4675-ab4a-5d90b911f0d6.png">

I have an invalid cooked up Resource Arn and Event Bus name here and this is the response

<img width="628" alt="image" src="https://user-images.githubusercontent.com/97245708/162500157-0b3b2981-829d-40a2-9e73-2dfbb069af6f.png">

`FailedEntryCount` is 0 and seems to indicate that the PutEvent was successful.

**Comment by debora-ito** [comment]
If the resource ARN is matching the event pattern I believe PutEvents won't thrown an error. And the event not reaching the target is probably caused by the invalid ARN. 

Have you set a Dead-Letter Queue in the event rule? When an event delivery fails, the event is sent to a dead-letter queue with an error code and error message.

For more detailed info on DLQs for troubleshooting errors, check the EventBridge Dev Guide: https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-rule-dlq.html

This blog post can be helpful too:
https://aws.amazon.com/blogs/compute/improved-failure-recovery-for-amazon-eventbridge/

**Comment by mohit224** [comment]
This issue needs to be reopened as this does not work correctly, as stated in the original post the putEvent method generates the event id with invalid event bus name, or incorrect event pattern. Also since the event bus name is wrong it doesn't even reach the event rule DLQ.
