### ISSUE TITLE
The AWS SDK for Java team is hiring software engineers

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#3156]
We currently have [three open software development engineer positions on the AWS SDK for Java team](https://www.amazon.jobs/en/jobs/2021120/software-development-engineer-aws-sdk-for-java)! The position says virtual, but we're open to working virtually within the United States or with relocation to our offices in Seattle or New York City.

Be the change you want to see in the world!

**Comment by valyli** [comment]
I see this job info from java SDK documentation at AWS. :)
I am living in China. Is it Ok?

**Comment by deshdeepmandal-powerschool** [comment]
> I see this job info from java SDK documentation at AWS. :) I am living in China. Is it Ok?

High five Valy. AWS Credentials brought me here. I used to think people provide these links in their webpage's html code.

**Comment by millems** [comment]
> I see this job info from java SDK documentation at AWS. :) I am living in China. Is it Ok?

For these specific positions, we're looking for people within the US. Relocation is definitely an option we could discuss, but there's also a lot of other great AWS positions open that don't require relocation you can search for at https://amazon.jobs.

**Comment by vlaskz** [comment]
Hello people! If you don't mind, I would like to apply to these positions. Any how-to's? Also, I'm brazilian, but willing to relocate!

**Comment by millems** [comment]
Hi @vlaskz, all of the AWS SDK for Java roles have just been filled, but we still have other exciting opportunities in the AWS SDKs.

Here's some of our other Java-focused opportunities:
* [AWS Smithy](https://www.amazon.jobs/en/jobs/1895372/software-development-engineer-aws-smithy-team) - A new foundational code generation framework and modeling language that the AWS SDKs are moving toward.
* [AWS SDK Metrics](https://www.amazon.jobs/en/jobs/1822843/senior-software-development-engineer) - A big data system responsible for aggregating SDK metric data across AWS services
* [AWS SDK Platform](https://www.amazon.jobs/en/jobs/1902792/software-development-engineer-aws-sdks-platform-aws-sdks-and-tools) - The foundational systems that AWS services use to release changes to every AWS SDKs every day

Not married to Java? How about these other SDK languages?
* [AWS SDK for .NET](https://www.amazon.jobs/en/jobs/2086145/software-development-engineer-aws-net-sdk)
* [AWS SDK for Rust](https://www.amazon.jobs/en/jobs/2126871/software-development-engineer-aws-sdks-and-tools)
* [AWS SDK for Go](https://www.amazon.jobs/en/jobs/1813731/software-development-engineer-aws-sdk-for-go)
* [AWS SDK for Swift](https://www.amazon.jobs/en/jobs/2095229/software-development-engineer-aws-sdks-and-tools)

**Comment by vlaskz** [comment]
> * amework and

Thank u!
