### ISSUE TITLE
Unable to save user defined metadata with S3TransferManager V2

### ISSUE THREAD

**Issue by ashleymisr** [aws/aws-sdk-java-v2#3168]
### Describe the bug

While uploading file to S3 using the S3 Transfer Manager, user-defined metadata is not getting saved.

Map<String, String> metadata = new HashMap<>();
metadata.put("x-amz-meta-xmymetadata1", "some value");
Upload upload = transferManager
			    .upload(u -> u.source(Paths.get(objectPath))
			    .putObjectRequest(p -> p.bucket(bucketName)
							            .key(objectKey)
							            .contentType(contentType)
							            .metadata(metadata)
							    )
					    );
The same works well when using the putObject method.

### Expected Behavior

User-defined metadata should get saved when using S3TransferManager V2

### Current Behavior

There are no errors. The expected metadata doesn't get saved.

### Reproduction Steps

Map<String, String> metadata = new HashMap<>();
metadata.put("x-amz-meta-xmymetadata1", "some value");
Upload upload = transferManager
			    .upload(u -> u.source(Paths.get(objectPath))
			    .putObjectRequest(p -> p.bucket(bucketName)
							            .key(objectKey)
							            .contentType(contentType)
							            .metadata(metadata)
							    )
					    );

### AWS Java SDK version used

2.17.16-PREVIEW

### JDK version used

JDK8

### Operating System and version

Windows 10

**Comment by debora-ito** [comment]
@ashleymisr thank you for reporting this, I'm able to reproduce.

**Comment by debora-ito** [comment]
@ashleymisr after initial investigation we found that in the latest version `2.17.176-PREVIEW` the upload with user-defined metadata works as expected for small files.

But if the file is bigger than 5 MB (I think) it will use multipart upload, and the latest version is throwing an error: `java.util.concurrent.CompletionException: software.amazon.awssdk.core.exception.SdkClientException: Failed to send the request. CRT error code: 1069.`

We've reached out to the CRT team to investigate, will update here when we know more.

**Comment by zoewangg** [comment]
Hi @ashleymisr, we have released a fix in `2.17.188`. Please let us know if you still experience the issue with the latest version.

**Comment by ashleymisr** [comment]
🎉 Yipppeeeee....  Working now. 🥳
Confirming that user-defined metadata is getting saved with S3TransferManager V2.
👍 Good

**Comment by zoewangg** [comment]
Thank you for verifying. Closing the issue.
