### ISSUE TITLE
S3TransferManager throws exception for the URLEncoded source object

### ISSUE THREAD

**Issue by wendyxie8724** [aws/aws-sdk-java-v2#3172]
### Describe the feature

The native s3Client.copyObject(CopyObjectRequest) work with URLEncoded special character in the S3 source object, but the S3TransferManager.copy(CopyObjectRequest) throws CompleteException with underneath S3Exception: null (error status 403)

### Use Case

I need to perform the large file s3 copy for the source object that contains special character "+" in its filename. While I can solve the issue by encoding the source URL in the CopyObjectRequest's copySource parameter, while calling S3Client.copyObject(copyObjectRequest), the S3TransferManager.copy(copyObjectRequest) throws me exception. So I cannot utilize the S3TransferManager API to perform the copy of a large s3 bucket object that contains the special character in the filename.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

software/amazon/awssdk/s3-transfer-manager/2.17.175-PREVIEW

### JDK version used

11

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Thank you for reaching out @wendyxie8724. I can reproduce, changing to a bug.

Looks like the CRT client is not url-encoding the fields automatically, like the native S3Client does. I'll reach out to the CRT team and report this.
