### ISSUE TITLE
EventBridge PutEvent Successful with Invalid EventBus name or Event Pattern

### ISSUE THREAD

**Issue by mohit224** [aws/aws-sdk-java-v2#3173]
### Describe the bug

This issue is related to https://github.com/aws/aws-sdk-java-v2/issues/3155 since I cannot reopen the issue. 
The putevent method always returns an event id with invalid event bus or invalid event pattern. Also unsuccessful events like wrong event pattern do not send the request to DLQ. 

### Expected Behavior

1. EventId is not generated and an error is reported on wrong event bus name or wrong event pattern. 
2. Incorrect events goes to DLQ. 

### Current Behavior

Always generates a successful event id without delivering the events to the event bus. 

### Reproduction Steps

Invoke the putevents method by passing invalid event bus name or invalid event pattern so that no rules are matched. 

### AWS Java SDK version used

aws-sdk-java-v2

### JDK version used

11

### Operating System and version

macOS Monterey Version 12.3.1

**Comment by andrewcylaw** [comment]
Yes, at the moment the entire EventBridge system can fail silently while the PutEvents call returns a false-positive "success". This issue needs to be reopened, either to change the current behaviour or provide a valid workaround as the DLQ approach doesn't work.

**Comment by debora-ito** [comment]
Can you share repro codes?
And the version of the SDK you're using?

**Comment by andrewcylaw** [comment]
For Java, we're using `2.17.79` right now. It's also reproducible via the AWS CLI, eg

```
aws events put-events --entries file://./sample_evb.json
```

Where the `sample_evb.json` looks like:

```json
[
  {
    "Source": "com.org.whatever",
    "DetailType": "my event",
    "Detail": "{ \"config_id\": \"testconfig\", \"some_other_field\": \"testvalue\" }",
    "EventBusName": "this_bus_does_not_exist"
  }  
]
```

**Comment by mohit224** [comment]
I am using 2.17.176 version. 
<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>eventbridge</artifactId>
			<version>2.17.176</version>
</dependency>

**Comment by mohit224** [comment]
@debora-ito  Do you have any updates? We are really considering eventbridge service for our clients use case but if it does not have proper error handling lot of questions will be raised by the clients. Any help will be really appreciated on this issue.

**Comment by debora-ito** [comment]
@mohit224 @andrewcylaw @vkemthur-luna apologies for the delay in response.

Researching a little deeper, it looks like this was also reported by users of the SDK for Ruby. The EventBridge service team is aware of the issue, more context is provided in the link - https://github.com/aws/aws-sdk-ruby/issues/2657. I'll let the service team know that we got more reports of impact. 

We have a tracking issue in the cross-SDK repo, we'll post any updates over there: https://github.com/aws/aws-sdk/issues/186. Marking this to close soon.

**Comment by mohit224** [comment]
Closing this as this has been tracked under separate issue: 
https://github.com/aws/aws-sdk-ruby/issues/2657
