### ISSUE TITLE
Throwing exception when call createReceiptRule/listReceiptRule

### ISSUE THREAD

**Issue by TDtianzhenjiu** [aws/aws-sdk-java-v2#3191]
### Describe the bug

Hello
I encounter an issue when I try to use create receipt rule in  **SES**

### Expected Behavior

200

### Current Behavior

software.amazon.awssdk.services.ses.model.SesException: Unavailable Operation (Service: Ses, Status Code: 400, Request ID: f63bd7a2-3153-459f-9d6e-d812ca4ad65a)

### Reproduction Steps

 
@Test
    public void createRule(){

        client.createReceiptRule((builder) -> {
            builder.ruleSetName("rule-test2");
            builder.rule(ReceiptRule.builder().recipients("xxx1@xxx.com")
                    .actions(ReceiptAction.builder().snsAction(SNSAction.builder().topicArn("arn:aws:sns:us-east-1:935626433462:xxx").build())
                            .build()).build());
            builder.build();
        });

    }

### AWS Java SDK version used

software.amazon.awssdk:ses:2.17.136

### JDK version used

11

### Operating System and version

mac

**Comment by debora-ito** [comment]
Hi @TDtianzhenjiu 

SES Email receiving rules are only supported in a sub-set of aws regions, you're probably using a non-supported region. You can find more info here: https://docs.aws.amazon.com/ses/latest/dg/regions.html#region-receive-email

**Comment by TDtianzhenjiu** [comment]
Hi @debora-ito 
Thanks, it is working now
It seems not a bug, will close this issue
