### ISSUE TITLE
TransferManager upload bytes from an inputstream with known length

### ISSUE THREAD

**Issue by ysn2233** [aws/aws-sdk-java-v2#3196]
### Describe the feature

Hi, I want to use TransferManager to upload a large object . It is read from an HTTP source as an InputStream. The content-length is known but I dont want to buffer all bytes into memory or download it to disk first. Currently ` AsyncRequestBody` 's methods `fromFile()`, `fromBytes()` does not satisfy my need and `fromPublisher()` seems to set content-length to Empty. Can V2 SDK support upload from an InputStream?

I found that the V1 SDK supports to pass an InputStream with a ObjectMetadata(Include size).

### Use Case

Needs to upload large file without buffer all bytes or predownload.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.191

### JDK version used

8

### Operating System and version

linux/mac/windows

**Comment by zoewangg** [comment]
Hi @ysn2233, sorry for the delayed response. You can try to adapt an InputStream to a Publisher and then use `AsyncRequestBody.fromPublisher`. Note that you'd need to specify content length in the PutObjectRequest.
```java
        tm.upload(UploadRequest.builder()
                               .putObjectRequest(b -> b.bucket(TEST_BUCKET)
                               .key(TEST_KEY)
                               .contentLength(contentLength))
                               .requestBody(AsyncRequestBody.fromPublisher(publisher)))
                               .build())
```
