### ISSUE TITLE
add api "copyObjects"

### ISSUE THREAD

**Issue by Tarrowren** [aws/aws-sdk-java-v2#3205]
### Describe the feature

batch method of `copyObject`

### Use Case

```java
  for (String key : keys) {
      client.copyObject(
        CopyObjectRequest
          .builder()
          .sourceBucket(TEMPORARY)
          .sourceKey(key)
          .destinationBucket(PERMANENT)
          .destinationKey(key)
          .build()
      );
  }
```

### Proposed Solution

```java
client.copyObjects(
    CopyObjectsRequest
        .builder()
        .sourceBucket(TEMPORARY)
        .destinationBucket(PERMANENT)
        .copy(
            Copy
                .builder()
                .objects(
                    keys
                        .stream()
                        .map(key -> ObjectIdentifier.builder().sourceKey(key).destinationKey(key).build())
                        .collect(Collectors.toList())
                )
                .build()
        )
        .build()
)
```

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.191

### JDK version used

8

### Operating System and version

windows10

**Comment by debora-ito** [comment]
@Tarrowren 

Batch Copy operations is already supported by S3Control CreateJob requests.

Take a look at the S3 Control Dev Guide for more info and code examples: https://docs.aws.amazon.com/AmazonS3/latest/userguide/batch-ops-copy-object.html
