### ISSUE TITLE
S3TransferManager JNI Source Removed

### ISSUE THREAD

**Issue by jidol** [aws/aws-sdk-java-v2#3213]
### Describe the bug

When using the transfer manager in unit testing, I create transfer managers.  While the tests run in parallel, managers are created and removed on each test.  Sometimes when trying to use the manager the "crt-jni.so" gets removed and everything starts failing.

I assume this is due to the shared "tmp" location in java. 

### Expected Behavior

Creating and destroying the transfer manager in parallel in different vm's should not fail.

### Current Behavior

Multiple VM's conflict causing SO to be removed.

### Reproduction Steps

Create Transfer managers in multiple JVM and have them exit/start at random times.  Some will work others fail depending on the SO being created.

### Possible Solution

Allow configuration of the SO location.

### AWS Java SDK version used

2.17.196-PREVIEW

### JDK version used

openjdk 17 2021-09-14

### Operating System and version

AME="Amazon Linux" VERSION="2" ID="amzn" ID_LIKE="centos rhel fedora" VERSION_ID="2" PRETTY_NAME="Amazon Linux 2"

**Comment by ashishdhingra** [comment]
@jidol Could you please share the sample code to reproduce the issue?

Thanks,
Ashish
