### ISSUE TITLE
DynamoDbEnhancedClient: @QueryEnhancedRequest limit parameter is not limiting the search results as expected 

### ISSUE THREAD

**Issue by molBR** [aws/aws-sdk-java-v2#3226]
### Describe the bug

I am reopening the issue https://github.com/aws/aws-sdk-java-v2/issues/1951 because the solution given is not of optimal performance. 

### Expected Behavior

If you consider the raw dynamoQuery: `Query(hash_key=..., ScanIndexForward=True, limit=1)` it returns only one item ordered by whatever the index key is.

### Current Behavior

If you use the semantically similar function, you get a paginated response and not actual singular documents from dynamoDB

### Reproduction Steps

Anything such as:
 `mappedTable.query(
    QueryEnhancedRequest
        .builder()
        .queryConditional(
            QueryConditional.keyEqualTo {
                Key.builder()
                    .partitionValue(clientId)
                    .build()
            }
        ).limit(1)
        .scanIndexForward(true)
        .build()
).items()`

### Possible Solution

I am not familiar on how the "engines work under the hood"  but maybe just provide a way to get the most recent document would suffice. 

### Additional Information/Context

The provided solution mentioned on the closed issue lacks performance and should not be considered as indeed a solution in my opinion

### AWS Java SDK version used

AWS Java SDK version used: SDK version 2.13.52

### JDK version used

JDK version used:11

### Operating System and version

Operating System and version:Linux 5.0.0-37-generic x86_64

**Comment by debora-ito** [comment]
Hi @molBR looking back at the closed issue, my suggestion is not quite right.

The query limit is taking effect, but the PageIterable will send a new request to obtain more items if asked for more pages. To prevent that you can limit the PageIterable to 1 page while iterating. 

In this example, the query limit is 5 items, and limiting the iterator to 1 will return one page with 5 items:

```java
        SdkIterable<Page<Customer>> customersPartition =
                customerTable.query(r -> r.queryConditional(keyEqualTo(k -> k.partitionValue("001")))
                                          .limit(5)
                                          .scanIndexForward(true)
                );

        PageIterable<Customer> results = PageIterable.create(customersPartition);

        results.stream()
                .limit(1)
                .forEach(p -> p.items().forEach(customer -> System.out.println(customer.getName())));
```

Let us know if this is not what you're looking for.

**Comment by molBR** [comment]
Got it! But in this case you are grabbing 5 itens and then ordering these 5 items right? 
My idea was to get the whole set of a partition order and only get one item, but I guess dynamo is designed to not work this way.
Thanks for the feedback!

**Comment by debora-ito** [comment]
Query results are always sorted by the sort key value, according to the [DynamoDB Dev Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Query.html).

Closing this. Feel free to reach out if you have more questions.

**Comment by HasithaM** [comment]
I need to clarify one thing about this `limit` parameter,

The Java Doc says the following for the `limit` parameter,

> Note: The limit does not refer to the number of items to return, but how many items the database should evaluate while executing the query. Use limit together with Page.lastEvaluatedKey() and exclusiveStartKey in subsequent query calls to evaluate limit items per call.

I have a Single Table which has many types of data for example let's say Customer, Cart, Payment, Product etc. So all are in that single table. I have altogether 10, 000 records and I am going to query customers by a GSI, and there are 1000 customer records are matching that query, which means if I query using GSI it should return 1000 records. Let's say I need to get 20 records at a time. So according to the above Java Doc will the database only evaluate just 20 items first from all record types (Customer, Cart, Payment, Product) and returned the matching records according to the GSI query? For example, first evaluate 20 records which have 4 * Customer, 6 * Cart, 2 * Payment, and 8 * Product records and then return just 4 Customer records according to the GSI?

**Comment by tomoaki3284** [comment]
Hi @debora-ito, I am still not clear of "PageIterable will send a new request to obtain more items if **asked for more pages**". Assuming ddbTable has 1k records, users want to get 10 items for one page. By simply setting limit on PageIterable, it will prevent fetching 1k items? e.g.:

```
DynamoDbTable<Object> table = this.ddbClient.table(TABLE_NAME, TABLE_SCHEMA);
QueryEnhancedRequest request = QueryEnhancedRequest.builder().queryConditional(
                        QueryConditional.sortBeginsWith(
                                Key.builder()
                                        .partitionValue(pv)
                                        .sortValue(sv)
                                        .build()))
                .consistentRead(true)
                .scanIndexForward(false)
                .limit(10)
                .exclusiveStartKey(token)
                .build();
PageIterable<Object> result = table.query(request);
List<Object> page1 = result.iterator().next().items();
```
or 
```
QueryEnhancedRequest request = QueryEnhancedRequest.builder().queryConditional(
                        QueryConditional.sortBeginsWith(
                                Key.builder()
                                        .partitionValue(pv)
                                        .sortValue(sv)
                                        .build()))
                .consistentRead(true)
                .scanIndexForward(false)
                .limit(10)
                .exclusiveStartKey(token)
                .build();
PageIterable<Object> result = table.query(request);
List<Object> result.stream().limit(1).forEach(o -> o.items());
```
I am concern about the performance too (fetching 1k items is too much), and hoping this will only fetch 10 data from the table.

**Comment by anikoiau** [comment]
Hi @tomoaki3284 Were you able to find an answer?
