### ISSUE TITLE
When a  DynamoDbBean class use  primitive types as setter's parameter, it will not be called.

### ISSUE THREAD

**Issue by mikeyan123** [aws/aws-sdk-java-v2#3228]
### Describe the bug

As say, I have a order class:
@DynamoDbBean
public class Order {
	private Long id;
	private Integer amount;

	public Order() {
	}

	public Order(long l, int i) {
		this.id = l;
		this.amount = i;
	}

	@DynamoDbPartitionKey
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Integer getAmount() {
		return amount;
	}

	public void setAmount(int amount) {
		this.amount = amount;
	}
}
In this class, I use int other than Integer as the parameter of setAmount, strangely, when I try to retrieve the order I put before , the value of amount is null.

class OrderRepositoryTest {

	@Autowired
	DynamoDbEnhancedClient enhancedClient;

	@Test
	void findById() {
		DynamoDbTable<Order>  table = enhancedClient.table("order", TableSchema.fromBean(Order.class));
		try {
			table.createTable();
		}
		catch (Exception e){System.out.println(e.getMessage());}
		table.putItem(new Order(1L, 10));
		var order = table.getItem(Key.builder().partitionValue(1L).build());
		assertThat(order.getAmount()).isEqualTo(10);
	}
}

Is that a bug?

### Expected Behavior

I think even use primitive type as the parameter, it should work, or throw an exception.

### Current Behavior

It don't call the setAmount method.

### Reproduction Steps

See the code.

### Possible Solution

I think even use primitive type as the parameter, it should work, or throw an exception.

### AWS Java SDK version used

2.17.201

### JDK version used

18

### Operating System and version

macOS Monterey 12.4

**Comment by monika-sivamoorthy** [comment]
Can I work on this bug?

**Comment by debora-ito** [comment]
This is now addressed in the "Learn the basics of the DynamoDB Enhanced Client API" [documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ddb-en-client-use.html#ddb-en-client-use-types):

> The attribute types (properties) of your Java data classes should be objects types, not primitives. For example, always use Long and Integer object data types, not long and int primitives.
