### ISSUE TITLE
software.amazon.awssdk:bom-internal should have <packaging>pom</packaging> declared

### ISSUE THREAD

**Issue by ppalaga** [aws/aws-sdk-java-v2#3231]
### Describe the bug

software.amazon.awssdk:bom-internal is apparently a Bill of Materials that is supposed to be imported in end users' dependencyManagement section. For that usecase solely the pom is relevant and the jar does not need to exist at all.

Although the jar https://repo1.maven.org/maven2/software/amazon/awssdk/bom-internal/2.17.203/bom-internal-2.17.203.jar exists, it contains just some auto-generated Maven metadata, license file, etc. but no useful java classes or resources.

So unless I am missing something, software.amazon.awssdk:bom-internal can be declared as pom and AWD SDK can stop publishing the jar.

### Expected Behavior

[software.amazon.awssdk:bom-internal:pom](https://repo1.maven.org/maven2/software/amazon/awssdk/bom-internal/2.17.203/bom-internal-2.17.203.pom) should have <packaging>pom</packaging>

### Current Behavior

[software.amazon.awssdk:bom-internal:pom](https://repo1.maven.org/maven2/software/amazon/awssdk/bom-internal/2.17.203/bom-internal-2.17.203.pom) has no <packaging> element which makes it to have the default <packaging>jar</packaging>.

### Reproduction Steps

This is a general Maven setup issue, that has to be understood by pure thought ;)

### Possible Solution

Add <packaging>pom</packaging> to software.amazon.awssdk:bom-internal

### AWS Java SDK version used

2.17.203

### JDK version used

any

### Operating System and version

any

**Comment by debora-ito** [comment]
Hi @ppalaga thank you for reaching out.

Can you elaborate on why publishing the `bom-internal` jar is a problem? I'm not clear on the advantages of stopping doing so.

On a side note, stopping to publish the `bom-internal` jar would be technically a breaking change, so I'm not sure we would do it.

**Comment by ppalaga** [comment]
Hi @debora-ito, sorry for the late answer, I travelling and busy with other stuff.

> Can you elaborate on why publishing the bom-internal jar is a problem? I'm not clear on the advantages of stopping doing so.

The fact that you publish bom-internal jar is not such a big problem. You can keep publishing it and I (as well as the vast majority of AWS SDK users) will happily ignore it, because it not needed for anything. Esp. it does not contain any java code or other useful resources, because of which anybody would need it.

This issue is much more about the missing `<packaging>` in the published `bom-internal` pom.xml file. No `<packaging>` means `<packaging>jar</packaging>` for Maven. That's wrong for this artifact, because there is no Java code or resources you want to publish through a jar. The sole reason for which this artifact exists is dependency management and for that kind of use, `<packaging>pom</packaging>` is the right one. So what I am asking for is to add `<packaging>pom</packaging>` to the pom.xml you publish. 

> On a side note, stopping to publish the bom-internal jar would be technically a breaking change, so I'm not sure we would do it.

As I said you can keep publishing the associated jar if you want to be this extremely careful for backwards compatibility. But I really doubt anybody would be impacted if you stop doing so. Maven (or any other build tools) just do not expect the jar to exist when the packaging is `pom`.
