### ISSUE TITLE
STS async credential update disabled by default

### ISSUE THREAD

**Issue by snmueller** [aws/aws-sdk-java-v2#3237]
### Describe the bug

When using `StsAssumeRoleWithWebIdentityCredentialsProvider`, we noticed that credentials were not being updated asynchronously. According to the documentation on [StsCredentialsProvider](https://github.com/aws/aws-sdk-java-v2/blob/d249c11aa8396650f832887ec25e4ab470998cc9/services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java#L36), credentials should be updated asynchronously. 

### Expected Behavior

STS Token credentials should be updated asynchronously in a background thread 

### Current Behavior

STS credentials are not updated in the background and requests block on the STS call when the token expires

### Reproduction Steps

Create a client using the `WebIdentityTokenFileCredentialsProvider`, ex:
 ```
     val credentialsProvider = WebIdentityTokenFileCredentialsProvider.create()
     val dynamoDbClient: DynamoDbAsyncClient =
        DynamoDbAsyncClient.builder.credentialsProvider(credentialsProvider).build()
```

Wait until the expiration time of the token and make an SDK call. The request blocks on the STS call, confirming that the token is not refreshed in the background.

### Possible Solution

Update the flag `asyncCredentialUpdateEnabled` to be [enabled by default](https://github.com/aws/aws-sdk-java-v2/blob/d249c11aa8396650f832887ec25e4ab470998cc9/services/sts/src/main/java/software/amazon/awssdk/services/sts/auth/StsCredentialsProvider.java#L127). Another option could be to have this flag be configurable through the `WebIdentityTokenFileCredentialsProvider `.

### AWS Java SDK version used

2.17.205

### JDK version used

openjdk11

### Operating System and version

Amazon Linux 2018.03

**Comment by debora-ito** [comment]
Hi @snmueller thank you for reaching out.

`StsAssumeRoleWithWebIdentityCredentialsProvider` and `WebIdentityTokenFileCredentialsProvider` are two different providers.

You can set the async update to true when using `StsAssumeRoleWithWebIdentityCredentialsProvider`:

```
StsAssumeRoleWithWebIdentityCredentialsProvider provider = StsAssumeRoleWithWebIdentityCredentialsProvider.builder()
                .asyncCredentialUpdateEnabled(true)
                .build();
```

But the background thread for update is not available in [`WebIdentityTokenFileCredentialsProvider`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/WebIdentityTokenFileCredentialsProvider.html)
