### ISSUE TITLE
AwsCrtAsyncHttpClient - Support customization of connectionTimeout

### ISSUE THREAD

**Issue by debora-ito** [aws/aws-sdk-java-v2#3251]
### Discussed in https://github.com/aws/aws-sdk-java-v2/discussions/3249

<div type='discussions-op-text'>

<sup>Originally posted by **mmflys** June 14, 2022</sup>
What's the default value for connectionTimeout, readTimeout in AwsCrtAsyncHttpClient and how can i change the timeout setting?</div>

**Comment by mmflys** [comment]
Hi debora, could I take this feature request to implement?

**Comment by zoewangg** [comment]
Hi @mmflys PRs are always welcome! :)

**Comment by vaisiri** [comment]
is there any way we can set connection timeout and read timeout for AwsCrtAsyncHttpClient?

**Comment by zoewangg** [comment]
This is supported now. Please try with the latest version.
