### ISSUE TITLE
Add support for client side sqs buffering and request batching

### ISSUE THREAD

**Issue by softprops** [aws/aws-sdk-java-v2#3271]
### Describe the feature

Add support for https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-client-side-buffering-request-batching.html as the v1 sdk does.

the current docs state

> The AWS SDK for Java 2.x isn't currently compatible with the AmazonSQSBufferedAsyncClient

### Use Case

While migrating a codebase from the v1 to v2 aws sdk, I realized there is no support for something like AmazonSQSBufferedAsyncClient in the v2 sdk

this would be useful for the same reason it was useful in the v1 sdk

> Client-side buffering allows up to 10 requests to be buffered and sent as a batch request, decreasing your cost of using Amazon SQS and reducing the number of sent requests.

### Proposed Solution

Similar approach to v1 sdk

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.x latest

### JDK version used

Java 11

### Operating System and version

OS X/linux

**Comment by debora-ito** [comment]
Hi @softprops thank you for reaching out.

We are tracking this in https://github.com/aws/aws-sdk-java-v2/issues/165. I'll go ahead and close this one, please feel free to comment with your use case and add a 👍 to the original description to help us with prioritization.
