### ISSUE TITLE
DynamodbVersionAttribute does not update version number in DynamoDbEnhancedClient

### ISSUE THREAD

**Issue by jeffrohlman** [aws/aws-sdk-java-v2#3278]
### Describe the bug

The DynamoDbEnhancedClient does not update the version number of the local copy of the object after calling putItem. This means the local copy now does not match what is in the table. This is different than the behavior in the v1 DynamoDBMapper and does not make sense.

### Expected Behavior

The local copy should reflect what was put in the Table. Then the same object can be modified multiple times without retrieving the object from the table or manually bumping the version number.

```java
CatalogItem item = table.getItem(Key.builder().partitionValue(111).build());
item.setName("Jeff");
table.putItem(item);

item.setName("Tom");
table.putItem(item);
```

Both putItem should succeed because the local copy of the item has the version updated.

### Current Behavior

The current behavior is to 
```java
CatalogItem item = table.getItem(Key.builder().partitionValue(111).build());
// The item looks like this and matches what is in the table:
// { id: 111, name: Jack, version: 1}

item.setName("Jeff");
table.putItem(item);
// After the putItem call the item no longer matches the version number of the item in the table
// item = { id: 111, name: Jeff, version: 1}
// table = { id: 111, name: Jeff, version: 2}

item.setName("Tom");
table.putItem(item); // This call fails because the version number does not match.
```

### Reproduction Steps

See above to reproduce the failure. And to prove that the version number is not being updated the below code can be used and succeeds:
```java
CatalogItem item = table.getItem(Key.builder().partitionValue(111).build());
item.setName("Jeff");
table.putItem(item);

item.setVersion(item.getVersion() + 1);
item.setName("Tom");
table.putItem(item);
```
Manually updating the version is a backwards paradigm when the client is responsible for handling the versioning.

### Possible Solution

I combed through the code and I have two ideas.

First, [in the Extension Context](https://github.com/aws/aws-sdk-java-v2/blob/master/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/DynamoDbExtensionContext.java#L39) it only provides the transformed AttributeMap instead of the full POJO.

Second, another option is to ensure that after the PutItem succeeds the underlying object is modified to reflect any changes made by extensions.

### AWS Java SDK version used

v2

### JDK version used

11

### Operating System and version

Amazon Linux 2

**Comment by debora-ito** [comment]
@jeffrohlman the current behavior is the expected behavior, the second call of `table.putItem(item);` is expected to fail exactly because the attribute version won't match the current version in the database.

I don't recall this being the behavior in DynamoDBMapper. Can you share a code sample using v1 DynamoDBMapper that shows that?

**Comment by jeffrohlman** [comment]
@debora-ito Sorry I forgot to follow up with this. The expectation is that the item matches what is in the table after calling Update/Put. The EnhancedClient/Table modifies what it writes to the table by incrementing the version number. But it does not reflect this modification in the local item.

Here is an example from the V1 SDK:
```java
DynamoDBMapperConfig mapperConfig = new DynamoDBMapperConfig.Builder()
                .withTableNameOverride(DynamoDBMapperConfig.TableNameOverride.withTableNameReplacement(tableName))
                .withConsistentReads(DynamoDBMapperConfig.ConsistentReads.CONSISTENT)
                .build();

DynamoDBMapper mapper = new DynamoDBMapper(dynamoDBClient, mapperConfig);

CatalogItem localItem = mapper.load(CatalogItem.class, 111);
// The item looks like this and matches what is in the table:
// { id: 111, name: Jack, version: 1}

localItem.setName("Jeff");
mapper.save(localItem);
// After the save call the localItem was updated to match the version number of the item in the table
// localItem = { id: 111, name: Jeff, version: 2}
// table = { id: 111, name: Jeff, version: 2}

localItem.setName("Tom");
mapper.save(localItem); // This call succeeds because the version number matches
```

If we compare that to the Current Behavior section above the behavior has changed. From what I can tell we aren't able to get this behavior back. 

For now we have gotten around this by switching to UpdateItem instead of PutItem and then reassigning the local variable to what is returned. This is extremely error prone though and has caught us multiple time where we forgot to reassign after calling update item.
