### ISSUE TITLE
Native image build fails due to CachedSupplier/SplittableRandom

### ISSUE THREAD

**Issue by MarkusKramer** [aws/aws-sdk-java-v2#3323]
### Describe the bug

Building a native image with Graal fails with the latest AWS SDK 2.17.238
The issue did not yet exist with AWS SDK 2.16.51.

I was able to work around it by using ` --initialize-at-run-time=software.amazon.awssdk.utils.cache.CachedSupplier`.

### Expected Behavior

No error

### Current Behavior

```
Error: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Detected an instance of Random/SplittableRandom class in the image heap. Instances created during image generation have cached seed values and don't behave as expected.  To see how this object got instantiated use --trace-object-instantiation=java.util.Random. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Detailed message:
Trace: 
        at parsing software.amazon.awssdk.utils.cache.CachedSupplier.jitterTime(CachedSupplier.java:326)

```

### Reproduction Steps

Can be reproduced with Graal 21.3.0 and 'GraalVM 22.1.0.0-Final Java 17 Mandrel Distribution'.

### AWS Java SDK version used

2.17.238

### JDK version used

11 and 17

### Operating System and version

Linux

**Comment by MarkusKramer** [comment]
Hi. Okay interesting. Maybe an important aspect is that I'm using the url-connection-client (because I'm using the AWS SDK with Quarkus). I'm including the SDK like this in my Gradle build.gradle.kt file:
```
    implementation(enforcedPlatform("software.amazon.awssdk:bom:2.17.238"))
    implementation("software.amazon.awssdk:url-connection-client")
    fun awsImplementation(artifactId: String) {
        implementation("software.amazon.awssdk:$artifactId") {
            exclude("software.amazon.awssdk", "netty-nio-client")
            exclude("software.amazon.awssdk", "apache-client")
        }
    }
    awsImplementation("s3")
    awsImplementation("sts")
```

Hope that helps to reproduce. At least one other person also got the same issue as reported here https://github.com/quarkusio/quarkus/issues/14904#issuecomment-1057799863

**Comment by yasminetalby** [comment]
Hello @MarkusKramer,

Thank you very much for your response and for sharing your build.gradle.kt file.
We have added this bug fix to our backlog.

Best,

Yasmine

**Comment by Chexpir** [comment]
Thanks!
Yes, I also have the same problem, my relateddependencies are:
```
    implementation("software.amazon.awssdk:url-connection-client:${awsPluginVersion}") {
        exclude(group: "software.amazon.awssdk", module: "netty-nio-client")
        exclude(group: "software.amazon.awssdk", module: "apache-client")
    }
    implementation("software.amazon.awssdk:apache-client:${awsPluginVersion}") {
        exclude(group: "commons-logging", module: "commons-logging")
    }
...
    testImplementation "software.amazon.awssdk:netty-nio-client:${awsPluginVersion}"
```

**Comment by L-Applin** [comment]
Hello!
We think we might have a fix for this issue that would make it so `-initialize-at-run-time=software.amazon.awssdk.utils.cache.CachedSupplier` is not required, but I cannot seem to reproduce the problem described in this issue. Therefore I cannot really test our solution. 

I have put together **[a small demo project](https://github.com/L-Applin/RandomGraalvm
)** to try to reproduce it, using the same Gradle dependencies. I have tried to compile and run this small project with `GraalVM 22.2.r17-grl` and `22.1.0.r11-grl`, both working fine on my end.

Is it still problematic? Which java version and GraamVM were you using?

Again, thanks for submitting this issue to our attention!

**Comment by yaseenbit** [comment]
I am also getting this issue
