### ISSUE TITLE
AWS Java on CRaC

### ISSUE THREAD

**Issue by xeard** [aws/aws-sdk-java-v2#3336]
### Describe the feature

Hello all,
As the progress continues on the GraalVM native image side its clear that it will never provide a pain free Java development experience for the serverless architectures. Now a new and more promising solution is emerging on the surface; Java on CRaC.

It as an OpenJDK project ([project page](https://openjdk.org/projects/crac/)). The idea is to make Java processes fire immidiately (fighting against cold start) without compromising the full benefit of JIT performance.

Here is the detailed presentation link for the project
[https://www.youtube.com/watch?v=0evEs_3yaEI&t=5s](https://www.youtube.com/watch?v=0evEs_3yaEI&t=5s)

### Use Case

The benefits of CRaC over GraalVM native image are;

- No need to native compilation for the target platform (complile once, run everywhere applies again)
- All of the existing java libraries are available for use again, no need to wait them to support native compilation
- No reflection configuration and no proxy condiguration hell
- No need to allocate at least 16 GB ram for the compilation process itself and wait 10 min for the compilation
- No need to maintain custome Lambda runtime for native image, use the ofiicial Java runtime (of course Corretto also need to support CRac) 
- Utilize JIT preformance instead of lower AOT performance

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.246

### JDK version used

17.0.2

### Operating System and version

Linux 5.18.4

**Comment by zoewangg** [comment]
Hi @xeard, thanks for reaching out! Project CRaC is definitely a promising alternative approach to solve the slow startup issue. 

I'm not sure if it's going to be the replacement of static images though since there are additional benefits such as smaller footprint in addition to faster startup time and they will be evolved as part of [Project Leyden](https://openjdk.org/projects/leyden/).

**Comment by xeard** [comment]
Hello Zoe,

Leyden project is in conception phase. Lets wait and see how both projects wıil evolve.
If you are open to possibility of implementing CRaC we can keep this issue ticket open to discuss the future of these projects.

**Comment by xeard** [comment]
Hello to all, good news from AWS Lambda team.
With the new feature called SnapStart Java Lambda functions can start 10x faster.
Here is the blog post about the new fature.
`https://aws.amazon.com/blogs/aws/new-accelerate-your-lambda-functions-with-lambda-snapstart/`

I think we can close this issue without doing any change.
Thank you.

**Comment by debora-ito** [comment]
@xeard thank you for the circle back. Closing.
