### ISSUE TITLE
AppConfigDataClient requests cannot be recognized by Localstack (APPConfig)

### ISSUE THREAD

**Issue by MatejNedic** [aws/aws-sdk-java-v2#3342]
### Describe the bug

When trying to use `AppConfigDataClient.startConfigurationSession()` and `AppConfigDataClient.getLatestConfiguration()` with Localstack error happens that call cannot be resolved.
When using `AppConfigClient` to create Application, Environment, and ConfigurationProfile everything works normally and I can access configuration with deprecated call `AppConfigClient.getConfiguration()`.

### Expected Behavior

The call should be working without an issue for a new client.

### Current Behavior

When checking Localstack logs I noticed the following:

`Error in proxy handler for request POST http://127.0.0.1:58767/configurationsessions: no provider exists for service appconfigdata Traceback (most recent call last):`

When Localstack is being called with `AppConfigClient` call works since it makes a call to `appconfig` service.

### Reproduction Steps

Simply run Localstack (I ran it with testscontainers) and try to use  `AppConfigDataClient.startConfigurationSession()` and `AppConfigDataClient.getLatestConfiguration()`. 
(This will require a Localstack Pro license.)

### Possible Solution

I did some digging and found the following:
In AppConfigDataClient [endpointPrefix](https://github.com/aws/aws-sdk-java-v2/blob/60d6217853a90609d418d1c1360d34ccf47d0681/services/appconfigdata/src/main/resources/codegen-resources/service-2.json#L5) is different than in AppConfigClient [endpointPrefix](https://github.com/aws/aws-sdk-java-v2/blob/60d6217853a90609d418d1c1360d34ccf47d0681/services/appconfig/src/main/resources/codegen-resources/service-2.json#L5) I suspect this might be an issue when Localstack is being called since Localstack cannot determine handler for service `appconfigdata`.

I am willing to contribute to solving this problem if someone can guide me through it.

### AWS Java SDK version used

2.17.172

### JDK version used

1.8

### Operating System and version

Win32n 10.0.19044.0

**Comment by debora-ito** [comment]
Hi @MatejNedic looks like Localstack doesn't support AppConfigData - https://docs.localstack.cloud/aws/feature-coverage/.

You should reach out to the Localstack team in https://github.com/localstack/localstack.
