### ISSUE TITLE
Add support for sync client APIs to CRT Client

### ISSUE THREAD

**Issue by sebastian-zero** [aws/aws-sdk-java-v2#3343]
### Describe the feature

Current CRT client only supports async clients and that requires to rewrite existing sync logic. While it's often just adding .join(), other parts are more complicated to rewrite, e.g. paging logic. Sync client APIs are often much easier to use and still cover most use cases, especially for lambdas.

### Use Case

Use cases:
1) make migration of workloads using sync clients APIs to CRT easier, avoiding rewriting sync logic
2) make use of easier sync client APIs when implementing new projects against CRT

### Proposed Solution

Add sync client APIs to to CRT client.

### Other Information

Also see discussion here: [https://github.com/aws/aws-sdk-java-v2/issues/2939](https://github.com/aws/aws-sdk-java-v2/issues/2939)

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

latest

### JDK version used

all currently supported

### Operating System and version

all currently supported

**Comment by zoewangg** [comment]
AWS CRT sync HTTP client, `AwsCrtHttpClient`, has been released as part of `2.22.0`. It's in the same CRT module as the CRT async HTTP client, `aws-crt-client`. Closing the issue
