### ISSUE TITLE
Outdated documentation for converting non standard types to DynamoDB types

### ISSUE THREAD

**Issue by protyay** [aws/aws-sdk-java-v2#3355]
### Describe the issue

The documentation seems to be outdated. 
`DynamoDBTypeConverter` interface doesn't exist on v2 Java SDK. 

This should use new class `AttributeConverter` and provide implementation. 

### Links

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html

**Comment by protyay** [comment]
Thanks for your response. 
I would like to contribute towards this documentation. Please let me know how to go about it.

**Comment by yasminetalby** [comment]
Hello @protyay ,

You can contribute towards this documentation by submitting a PR in the [aws-doc/amazon-dynamodb-developer-guide ](https://github.com/awsdocs/amazon-dynamodb-developer-guide) repository. 
Here is a [link](https://github.com/awsdocs/amazon-dynamodb-developer-guide/blob/master/CONTRIBUTING.md) on guidelines regarding contribution.

When submitting a PR, you can direct the team that your submission has for purpose to update the example on : https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBMapper.ArbitraryDataMapping.html

I have also informed the Java Doc team about your update inquiry. You can also submit an issue to the amazon-dynamodb-developer-guide about the update. 

Let me know if you have any other questions.

Best,

Yasmine

**Comment by protyay** [comment]
Thanks @yasminetalby . I'll check this. :)
