### ISSUE TITLE
endpointOverride with altered URI from S3 serviceMetadata

### ISSUE THREAD

**Issue by A4L** [aws/aws-sdk-java-v2#3356]
### Describe the bug

I am trying to override the s3 service endpoint as to not use TLS. I have a region configured which I use with [ServiceMetadata#endpointFor](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/regions/ServiceMetadata.html#endpointFor-software.amazon.awssdk.regions.Region-)  to get the original endpoint:

    URI endpoint = S3Client.serviceMetadata().endpointFor(region);

Then I create the new URI using the components found in the orignal/default endpoint for the given region:

    URI nonTlsEndpoint = new URI("http",
          endpoint.getUserInfo(),
          endpoint.getHost(),
          endpoint.getPort(),
          endpoint.getPath(),
          endpoint.getQuery(),
          endpoint.getFragment());

With the newly created URI connection to the service fail, which is expected when looking at the string representation thereof:

    http:s3.eu-central-1.amazonaws.com

Further inspecting the original endpoint URI with:

    log.info("Endpoint: Scheme={}, UserInfo={}, Host={}, Port={}, Path={}, Query={}, Fragement={}",
          endpoint.getScheme(),
          endpoint.getUserInfo(),
          endpoint.getHost(),
          endpoint.getPort(),
          endpoint.getPath(),
          endpoint.getQuery(),
          endpoint.getFragment());

shows the following:

    Endpoint: Scheme=null, UserInfo=null, Host=null, Port=-1, Path=s3.eu-central-1.amazonaws.com, Query=null, Fragement=null

`s3.eu-central-1.amazonaws.com` which seems to be the hostname seems to be at the wrong place, the path component. 

Am I missing something? Is this the correct approach the override a service endpoint using sdk v2?

### Expected Behavior

Generated new URI should serialize to `http://s3.eu-central-1.amazonaws.com`

### Current Behavior

Generated new URI serializes to `http:s3.eu-central-1.amazonaws.com`

### Reproduction Steps

    public S3Client s3Client() throws URISyntaxException {

        Region region = Region.of("eu-central-1");

        URI endpoint = S3Client.serviceMetadata()
            .endpointFor(region);

        URI nonTlsEndpoint = new URI("http",
            endpoint.getUserInfo(),
            endpoint.getHost(),
            endpoint.getPort(),
            endpoint.getPath(),
            endpoint.getQuery(),
            endpoint.getFragment());

        return S3Client.builder()
            .endpointOverride(nonTlsEndpoint)
            .credentialsProvider(DefaultCredentialsProvider.create())
            .region(region)
            .build();
    }

### AWS Java SDK version used

2.17.226

### JDK version used

11.0.3

### Operating System and version

debian stretch

**Comment by debora-ito** [comment]
@A4L Apologies for the long silence in this.

I see that behavior too but I don't know why the whole service endpoint is in the URI path. A workaround is to use the URI String:

```Java
S3Client client = S3Client.builder()
                .region(Region.EU_CENTRAL_1)
                .endpointOverride(URI.create("http://"+ endpoint.toString()))
                .build();
```

Please note that we don't recommend using HTTP protocol as it's not secure - in fact some AWS services will refuse the connection if it's not made with HTTPS.

**Comment by A4L** [comment]
HI @debora-ito , sorry form my side too, I almost forgot about this issue. I ended up implementing a workaroung similar to what you have described. As of the use of non secure HTTP, I totally agree, it was just a requirement from our infrastructure team which I have questionned but did not get a convincing answer. Anyways, no further actions required here, the issue can remain closed. Thanks!

**Comment by NazarioJL** [comment]
Why is this bug closed? I have seen this same behavior which _feels_ incorrect in the Java V2 SDK. Consider the following code:

```java
final var endpoint = Ec2Client.serviceMetadata().endpointFor(Region.US_EAST_1);
final var client = Ec2Client.builder().endpointOverride(endpoint).build();
```
This will fail with:

```
java.lang.NullPointerException: The URI scheme of endpointOverride must not be null.
```
If I try to rebuild the URI by hand, it will not match the original URI. 

```java
@Test
void testEndpointHost() {
    final var endpoint = Ec2Client.serviceMetadata().endpointFor(Region.US_EAST_1);
    final var endPointWithScheme = URI.create("https://ec2.us-east-1.amazonaws.com");
    assertThat(endPointWithScheme.getHost()).isEqualTo(endpoint.getHost());  // 💥 Fails! Since endpoint.getHost() is 'null'
}
```
