### ISSUE TITLE
CHANGELOG.md does not load in the GitHub UI

### ISSUE THREAD

**Issue by rickie** [aws/aws-sdk-java-v2#3360]
### Describe the issue

As of the last release, the contents of the [`CHANGELOG.md`](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md) became too large for GitHub to handle. When I try to open the `CHANGELOG.md` in the GitHub UI, I get the message: `This page is taking too long to load`. 

I verified within my team that I'm not the only one facing this issue.

Would it be possible for you to look into this? 

### Links

https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md

**Comment by yasminetalby** [comment]
Hello @rickie ,

Thank you very much for informing us the [CHANGELOG.md](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md) is displaying the same behavior on my end. I will be investigating this issue and provide updates here.

Best,

Yasmine

**Comment by yasminetalby** [comment]
Hello @rickie ,

Are you and your team able to access the[ CHANGELOG.md](https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md) file now?

Best,

Yasmine

**Comment by Stephan202** [comment]
For me it works again :+1:

**Comment by rickie** [comment]
Hi @yasminetalby ,

Yes I'm able to see the `CHANGELOG.md` again!
Thank you for looking into the problem.

I'm curious, how did you fix it :)?
