### ISSUE TITLE
S3TransferManager AWS JAVA SDk V 2.X downloadDirectory() method downloading objects with wrong file name

### ISSUE THREAD

**Issue by ShashankGupta28** [aws/aws-sdk-java-v2#3366]
### Describe the bug

S3TransferManager AWS JAVA SDk V 2.X **downloadDirectory()** method downloading objects with wrong file name, it ommits first charater of file-name downloaded.

observed with Java 1.8 or Java 11 and

    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3</artifactId>
      <version>2.17.255</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>auth</artifactId>
      <version>2.17.255</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3-transfer-manager</artifactId>
      <version>2.17.247-PREVIEW</version>
    </dependency>

S3 bucket structure

```
a-valid-bucket :
    abc
          def
               image.jpg
               title.png
               ghi/
                    xyz.txt
```

code 
```
          S3TransferManager s3TransferManager = S3TransferManager.create();

           DirectoryDownload directoryDownload = s3TransferManager
                        .downloadDirectory(DownloadDirectoryRequest.builder()
                        .destinationDirectory(Paths.get("/home/shashank/Documents"))
                        .bucket("a-valid-bucket")
                        .prefix("abc/def/")
                        .build());

        // Wait for the transfer to complete
        CompletedDirectoryDownload completedDirectoryDownload = directoryDownload.completionFuture().join();

        // Print out the failed downloads
        completedDirectoryDownload.failedTransfers().forEach(System.out::println);
```

### Expected Behavior

Actual objects downloaded from S3 must have correct file-name / directory-name  image.jpg, title.png, ghi/

### Current Behavior

 Download files are renamed to mage.jpg, itle.png, hi/ , first charter from file-name/ directory-name is omitted.

### Reproduction Steps

observed with Java 1.8 or Java 11 with  

  <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3</artifactId>
      <version>2.17.255</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>auth</artifactId>
      <version>2.17.255</version>
    </dependency>

    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>s3-transfer-manager</artifactId>
      <version>2.17.247-PREVIEW</version>
    </dependency>

```
          S3TransferManager s3TransferManager = S3TransferManager.create();

           DirectoryDownload directoryDownload = s3TransferManager
                        .downloadDirectory(DownloadDirectoryRequest.builder()
                        .destinationDirectory(Paths.get("/home/shashank/Documents"))
                        .bucket("a-valid-bucket")
                        .prefix("abc/def/")
                        .build());

        // Wait for the transfer to complete
        CompletedDirectoryDownload completedDirectoryDownload = directoryDownload.completionFuture().join();

        // Print out the failed downloads
        completedDirectoryDownload.failedTransfers().forEach(System.out::println);
```

### AWS Java SDK version used

s3-transfer-manager : 2.17.247-PREVIEW

### JDK version used

1.8

### Operating System and version

Ubuntu 18.04.6 LTS

**Comment by ShashankGupta28** [comment]
https://stackoverflow.com/questions/73444340/s3transfermanager-aws-java-sdk-v-2-x-downloaddirectory-method-downloading-obje

**Comment by zoewangg** [comment]
Thanks for creating the issue. Could you let us know what your bucket structure looks like and the prefix you provided?

**Comment by ShashankGupta28** [comment]
updated bug description

**Comment by zoewangg** [comment]
Thanks you for the additional information. We will work on the fix
