### ISSUE TITLE
Verifying of S3 putObject()-method does not work with Mockito

### ISSUE THREAD

**Issue by j-l1nk** [aws/aws-sdk-java-v2#3368]
### Describe the bug

When mocking `software.amazon.awssdk.services.s3.S3Client` with Mockito its not possible to verify `PutObjectResponse putObject(PutObjectRequest putObjectRequest, RequestBody requestBody)`-method.

Following error-message is appearing:
`Caused by: Argument(s) are different! Wanted:
s3Client.putObject(
    PutObjectRequest(Bucket=***, Key=***),
    software.amazon.awssdk.core.sync.RequestBody@2591f310
);
-> at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Actual invocations have different arguments:
s3Client.putObject(
    PutObjectRequest(Bucket=***, Key=***),
    software.amazon.awssdk.core.sync.RequestBody@4bbddcc8
);`

### Expected Behavior

Verifying putObject()-method should run without erros when arguments are equal.

### Current Behavior

An error occures despite arguments are equal.

### Reproduction Steps

Example Test:
```java
package com.demo;

import org.junit.Test;
import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;

import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

public class AwsS3Test {
    S3Client s3Client = mock(S3Client.class);

    @Test
    public void s3Client_test() {
        String bucketName = "bucket-name";
        String key = "key";
        PutObjectRequest putObjectRequest = PutObjectRequest.builder().bucket(bucketName).key(key).build();
        RequestBody requestBody = RequestBody.fromString("file-content");

        s3Client.putObject(putObjectRequest, requestBody);

        verify(s3Client, times(1)).putObject(putObjectRequest, RequestBody.fromString("file-content"));
    }
}
```

This is a simple example. In my real code I had a class which is using S3Client to store files in S3. I tested a method of my class and verified putObject()-method from s3Client like in the example above.

### Possible Solution

Implement equals()-method in `software.amazon.awssdk.core.sync.RequestBody`.

### Additional Information/Context

I would like to work on this. You can assign it to me.

### AWS Java SDK version used

2.17.73

### JDK version used

14.0.1

### Operating System and version

Windows 10

**Comment by yasminetalby** [comment]
Hello @j-l1nk ,

Thank you very much for your submission.
We always welcome PR from the community on new features for the AWS Java SDK.
However, since RequestBody has an inputStream, we will end up reading the input stream every time while doing the Equals. Thus implementing equals in RequestBody might end up unnecessary reading of inputStreams and is not a solution we would consider in this case.

We recommend that you use the same requestBody instead of creating a new one while verifying. 

Thank you very much for your collaboration.

Best,

Yasmine
