### ISSUE TITLE
ProcessCredentialsProvider does not indicate why the process failed

### ISSUE THREAD

**Issue by Avinm** [aws/aws-sdk-java-v2#3377]
### Describe the feature

ProcessCredentialsProvider fails on non-zero exit code without providing any useful debugging info.
The provider could capture the stderr into the exception message/description

### Use Case

To load credentials from an external process using the credential_process attribute in aws config file.

### Proposed Solution

Capture the stderr into the exception message/description thrown from ProcessCredentialsProvider

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2,x

### JDK version used

1.8

### Operating System and version

Mac OS 12.3.1

**Comment by achaphiv** [comment]
To anyone stumbling on this issue, I was getting this error because of a `command not found`.

In my case, I was running intellij via flatpak. The command I was using only existed in my host `/usr/bin/`.

**Comment by debora-ito** [comment]
Added support for this in SDK version `2.18.20`.
