### ISSUE TITLE
S3 TransferManager getBytesTransferred & getPercentTransferred method always return 0

### ISSUE THREAD

**Issue by Akshayc9** [aws/aws-sdk-java-v2#3379]
### Describe the bug

We have a use case where we are performing a s3 object copy from the source bucket to the destination bucket. While performing the transfer, TransferStateChangeListener is used and in that, we are checking the state of transfer, % transferred & bytes transferred for the current transfer. Though we are getting the correct value for total bytes to transfer. Following 2 issues we had observed,

1. **transfer.getProgress().getPercentTransferred()** always returns **0% transferred** though the transfer is complete.

2. **transfer.getProgress().getBytesTransferred()** always returns **0 Bytes transferred** though the transfer is complete.

For this aws-java-sdk and version 1.11.930 were used. After discussing the issue with AWS support we have upgraded to the latest sdk.

We have updated the aws-sdk-java to 2.17.257 and tried with the latest version but still facing the same issue.

To test with latest version, we have created

**CopyObjectRequest** with **setGeneralProgressListener** having following print statement 

**System.out.println(progressEvent.getBytes() + " - " + progressEvent.getEventType() + " - "+ progressEvent.getBytesTransferred());**

For this transfer, the file used was 66 MB. And following is the console output.

Though the file copying operation was successful.

### Expected Behavior

We should get the bytes transferred and the % transferred for the current transfer when using Transfer manager for s3 transfer.

### Current Behavior

Following is the console output for above statement : 
0 - CLIENT_REQUEST_STARTED_EVENT - 0
0 - HTTP_REQUEST_STARTED_EVENT - 0
0 - HTTP_REQUEST_COMPLETED_EVENT - 0
234 - RESPONSE_CONTENT_LENGTH_EVENT - 0
0 - HTTP_RESPONSE_STARTED_EVENT - 0
234 - RESPONSE_BYTE_TRANSFER_EVENT - 234
0 - HTTP_RESPONSE_COMPLETED_EVENT - 0
0 - CLIENT_REQUEST_SUCCESS_EVENT - 0

### Reproduction Steps

`public static void main(String[] args) throws Exception {

		String sourceBucketName = "abc-demo-bucket";
		String sourceKeyName = "testfile.mp4";
		String destinationBucketName = "abc-store";
		String destinationKeyName = "testfile.mp4";

		TransferManager tm = TransferManagerBuilder.standard().withS3Client(s3).build();
      
		CopyObjectRequest request = new CopyObjectRequest(sourceBucketName, sourceKeyName, destinationBucketName,
				destinationKeyName);

		request.setGeneralProgressListener(new ProgressListener() {

			@Override
			public void progressChanged(ProgressEvent progressEvent) {
				// System.out.println("Bytes : "+ progressEvent.getBytes());
				System.out.println("***"+progressEvent.getBytes() + " - " + progressEvent.getEventType() + " - "
						+ progressEvent.getBytesTransferred()+"***");
			}
		});

		Copy copy = tm.copy(request);

		try {
			copy.waitForCompletion();
		} catch (AmazonClientException amazonClientException) {
			System.out.println("Unable to upload file, upload aborted.");
			amazonClientException.printStackTrace();
		}
	}`

### AWS Java SDK version used

2.17.257

### JDK version used

jdk1.8.0_144

### Operating System and version

Windows 10

**Comment by Akshayc9** [comment]
Hi Yasmin,

We have used aws-java-sdk and version 1.11.930 for the application. As AWS support asked to upgrade and try we have used AWS Java SDK v2 and tried with the above sample code first.

If you could try with aws-java-sdk 1.11.930 and these are the logs for the transfer.

2022-08-23 06:36:38.059  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 0.0% transferred
2022-08-23 06:36:38.060  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 10512956 Total Bytes to transfer
2022-08-23 06:36:38.060  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 0 Bytes transferred
2022-08-23 06:36:38.060  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : tranferStateChange Listener state :InProgress
2022-08-23 06:36:38.103  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Message successfully sent to SQS response.fifo
2022-08-23 06:36:38.103  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Progress sendResponseSqsMessage sent to response Q
2022-08-23 06:36:38.103  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 0 Bytes transferred
2022-08-23 06:36:38.690  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 0.0% transferred
2022-08-23 06:36:38.690  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 10512956 Total Bytes to transfer
2022-08-23 06:36:38.690  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Copying object from xxxxxx to xxxxxx : 0 Bytes transferred
2022-08-23 06:36:38.690  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : tranferStateChange Listener state :Completed
2022-08-23 06:36:38.705  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Message successfully sent to SQS response.fifo
2022-08-23 06:36:38.705  INFO 18 --- [anager-worker-1] c.s.s.m.s.service.S3ServiceImpl  : Success sendResponseSqsMessage sent to response Q

While performing this transfer, **TransferStateChangeListener** is used.

In the logs, the transfer state was initially **inProgress** that time % transferred and bytes transferred is 0. After the state is changed to **Completed** and still, the % transferred and bytes transferred is 0. Whereas we are getting the total bytes transfer correctly.

**Comment by yasminetalby** [comment]
Hello @Akshayc9 ,

Thank you very much for your answer. 

The behavior you experience with the provided code sample in v1 is as expected:
1. [`progressEvent.getBytes()` ](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEvent.html#getBytes--)Returns the number of bytes associated with the event. The number of bytes are not necessarily the same as the number of bytes transferred, and it's meaning depends on the specific event type. For example, the bytes of a [ProgressEventType.REQUEST_CONTENT_LENGTH_EVENT](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEventType.html#REQUEST_CONTENT_LENGTH_EVENT) refers to the expected number of bytes to be sent to AWS, not the actual number of bytes that have been transferred.
If you are looking at the definition of all event associated with `progressEvent.getBytes()`, only [ProgressEventType.REQUEST_CONTENT_LENGTH_EVENT](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEventType.html#REQUEST_CONTENT_LENGTH_EVENT)  and [ProgressEventType.RESPONSE_BYTE_TRANSFER_EVENT](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEventType.html#RESPONSE_BYTE_TRANSFER_EVENT) should return a non 0 value as they are byte associated events.

2. [`progressEvent.getBytesTransferred()`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEvent.html#getBytesTransferred--) is a method to returns the number of bytes transferred in this event, or the number of bytes reset (or discarded) if negative. In particular, bytes of a content-length event is excluded. If you look at the definition of all event associated with `progressEvent.getBytes()`, only  [ProgressEventType.RESPONSE_BYTE_TRANSFER_EVENT](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/event/ProgressEventType.html#RESPONSE_BYTE_TRANSFER_EVENT) should return a non 0 value as it is the only event during which bytes are transferred.

Regarding the TransferStateChangeListener usage, I don't see it being used within your code sample.
While reproducing your case using transfer.getProgress().getPercentTransferred() and transfer.getProgress().getBytesTransferred(), I am able to get expected value of 0% and 0.0 prior to transfer and 100% and xxxx bytes after my transfer completed. 
Could you please provide a code sample that leads to your experience with the TransferStateChangeListener? 

The following documentation could be helpful, it provides guidance in[ methods to track transfer manager operations progress](https://docs.aws.amazon.com/code-samples/latest/catalog/java-s3-src-main-java-aws-example-s3-XferMgrProgress.java.html ) with AWS Java SDK v1.

Best,

Yasmine
