### ISSUE TITLE
DynamoDbEnhancedClient swallows ValidationException in BatchGetItem

### ISSUE THREAD

**Issue by epheat** [aws/aws-sdk-java-v2#3382]
### Describe the bug

DynamoDb documentation states that DynamoDb will throw a ValidationException when you attempt to call BatchGetItem with more than 100 items ([source](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html)). However, the DynamoDbEnhancedClient swallows this exception meaning that iterating over the BatchGetResultPageIterable could cause an infinite loop.

### Expected Behavior

I expect the call to `DynamoDbEnhancedClient.batchGetItem` with a ReadBatch over size 100 to throw a ValidationException "Too many items requested for the BatchGetItem call.".

### Current Behavior

The DynamoDbEnhancedClient.batchGetItem method swallows the ValidationException from DynamoDb service when the ReadBatch exceeds size 100. If the code attempts to iterate over all the results in BatchGetResultPageIterable, this will cause an infinite loop.

### Reproduction Steps

The following code causes an infinite loop:
```java
// assume the existence of:
// DynamoDbEnhancedClient enhancedClient;
// DynamoDbTable<MyBean> table

final List<Key> keysToGet = new ArrayList<>();
for (int i = 0; i < 101; i++) {
  keysToGet.add(Key.builder()
                   .partitionValue(i)
                   .build())
}

final ReadBatch.Builder<MyBean> readBatch = ReadBatch.builder(MyBean.class)
                                                     .mappedTableResource(table);
keysToGet.forEach(readBatch::addGetItem);

final BatchGetResultPageIterable result = enhancedClient.batchGetItem(BatchGetItemEnhancedRequest.builder()
                                                                                                 .readBatches(readBatch.build())
                                                                                                 .build());

result.resultsForTable(table).forEach(System.out::println);
```

### Possible Solution

DynamoDbEnhancedClient should not swallow the ValidationException, instead propagate it up to the caller.

### AWS Java SDK version used

2.0

### JDK version used

8

### Operating System and version

AL2

**Comment by yasminetalby** [comment]
Hello @epheat ,

Thank you very much for your submission.
I am not able to reproduce this issue. Following the reproduction steps you have provided, I received the proper validation exception as described by the documentation.
I am using the AWS Java SDK v2.17.261.
Which version of the SDK are you using?
