### ISSUE TITLE
AquisitionTimeout is a factor of 1000 off.

### ISSUE THREAD

**Issue by loosemoose** [aws/aws-sdk-java-v2#340]
The following line should return milliseconds, not seconds:

https://github.com/aws/aws-sdk-java-v2/blob/32a5c48d2403bad54eb38b995d331f04dc63d542/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java#L88

**Comment by dagnir** [comment]
Fixed in #345
