### ISSUE TITLE
S3TransferManager.copy fails on large keys

### ISSUE THREAD

**Issue by joviegas** [aws/aws-sdk-java-v2#3404]
### Describe the bug

S3TransferManager.copy fails for keys with large size,

### Expected Behavior

S3TransferManager.copy should pass  for keys with any size.

### Current Behavior

S3Exception as below

`[software.amazon.awssdk.services](http://software.amazon.awssdk.services/) .s3.model.S3Exception: Part number must be an integer between 1 and 10000, inclusive (Service: S3, Status Code: 400, Request ID: 0AE1BAXS2MG17XEW, Extended Request ID: g1fVALMD+mqWfZgp63MXBlqU0f1tlu/7/s6ZQSie7C7FsVp3yPmLhE/nKuz62bDfdqT1TQ/uas8=)`

### Reproduction Steps

Bucket name: someBucket
key: LARGE FILE OF 700GB
keySize: 701037789115
partSize: 268435456
targetRate: null
concurrency: 1

### Possible Solution

https://github.com/aws/aws-sdk-java-v2/blob/feature/master/transfermanager-GA/services-custom/s3-transfer-manager/src/main/java/software/amazon/awssdk/transfer/s3/internal/DefaultS3TransferManager.java#L353-L380

    Invoke headObject on the source object
    Use multipart copy if the source object size is larger than the configured threshold otherwise use single part copy

### AWS Java SDK version used

2.X

### JDK version used

1.8

### Operating System and version

NA

**Comment by zoewangg** [comment]
Should be fixed as part of https://github.com/aws/aws-sdk-java-v2/pull/3403

**Comment by zoewangg** [comment]
Just a quick update, the PR has been merged but we have not released it yet. We will post it here once the change is released

**Comment by zoewangg** [comment]
To provide an update, the change has been released. Please try with the latest version.
