### ISSUE TITLE
When used with Springboot, the Content-type becomes: application/cbor;  Charset =UTF-8, not application/json;  Charset =UTF-8

### ISSUE THREAD

**Issue by RunInto** [aws/aws-sdk-java-v2#3411]
### Describe the bug

When I integrated the AWS Java SDK V2-based class library into the Springboot Web project, the data responding to the front end became application/ CBOR;  Charset = utF-8, which should be application/json;  Charset =UTF-8, why does this happen?  How do I fix this? 

![1](https://user-images.githubusercontent.com/33835360/188840512-4d35675d-7e9a-48e4-b6fb-ffd615c63263.png)
![2](https://user-images.githubusercontent.com/33835360/188840735-5319f061-dc84-4dbf-91f6-9dec4c58a652.png)

### Expected Behavior

The correct result is to return a JSON-based packet

### Current Behavior

The current packet returned is based on CBOR, which is not recognized by the front end

### Reproduction Steps

none

### AWS Java SDK version used

2.17.230 && 1.11.837 concurrence 

### JDK version used

1.8

### Operating System and version

windows 10

**Comment by maciejwalkowiak** [comment]
@RunInto can you share a sample project that reproduces this issue?

Sidenote: I work on Spring Cloud AWS (Spring Boot + AWS SDK integrations) so I should be able to help

**Comment by RunInto** [comment]
> @RunInto can you share a sample project that reproduces this issue?
> 
> Sidenote: I work on Spring Cloud AWS (Spring Boot + AWS SDK integrations) so I should be able to help

Sorry, I can't provide an example, because I did a demo that did not reproduce the problem when using SpringBoot to integrate my AWS Java SDK-based class libraries.
After investigation, it may be that there is a dependency conflict. The solution in the project is as follows:

`@Configuration
public class FastjsonConfig implements WebMvcConfigurer {
    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        Iterator<HttpMessageConverter<?>> iterator = converters.iterator();
        while (iterator.hasNext()) {
            HttpMessageConverter<?> converter = iterator.next();
            if (converter instanceof MappingJackson2HttpMessageConverter) {
                iterator.remove();
                continue;
            }
            if (converter instanceof MappingJackson2SmileHttpMessageConverter) {
                iterator.remove();
                continue;
            }
            if (converter instanceof MappingJackson2CborHttpMessageConverter) {
                iterator.remove();
                continue;
            }
        }
        FastJsonHttpMessageConverter fastConverter = new FastJsonHttpMessageConverter();

        FastJsonConfig config = new FastJsonConfig();
        config.setSerializerFeatures(SerializerFeature.PrettyFormat,SerializerFeature.DisableCircularReferenceDetect);
        config.setCharset(StandardCharsets.UTF_8);
        config.setDateFormat("yyyyMMdd HH:mm:ss");
        List<MediaType> mediaTypes = new ArrayList<>();
        mediaTypes.add(MediaType.APPLICATION_JSON_UTF8);
        fastConverter.setSupportedMediaTypes(mediaTypes);

        StringHttpMessageConverter stringHttpMessageConverter = new StringHttpMessageConverter();
        fastConverter.setFastJsonConfig(config);

        converters.add(fastConverter);
        converters.add(stringHttpMessageConverter);
    }
}
`

I added this code：
`while (iterator.hasNext()) {
            HttpMessageConverter<?> converter = iterator.next();
            if (converter instanceof MappingJackson2HttpMessageConverter) {
                iterator.remove();
                continue;
            }
            if (converter instanceof MappingJackson2SmileHttpMessageConverter) {
                iterator.remove();
                continue;
            }
            if (converter instanceof MappingJackson2CborHttpMessageConverter) {
                iterator.remove();
                continue;
            }
        }`

**Comment by maciejwalkowiak** [comment]
@RunInto it does not seem that the problem you're facing is related to AWS SDK but rather either another dependency or just your project misconfiguration. You can try to run any sample from https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-samples and you won't run into this issue. 

If you're able to reproduce it in isolation I am happy to have a look.

**Comment by RunInto** [comment]
> @RunInto it does not seem that the problem you're facing is related to AWS SDK but rather either another dependency or just your project misconfiguration. You can try to run any sample from https://github.com/awspring/spring-cloud-aws/tree/main/spring-cloud-aws-samples and you won't run into this issue.
> 
> If you're able to reproduce it in isolation I am happy to have a look.

Thank you very much. I have solved the problem. The issue can be turned off now. Good luck!
