### ISSUE TITLE
EfsClient doesn't support waiters

### ISSUE THREAD

**Issue by rbsamoht** [aws/aws-sdk-java-v2#3419]
### Describe the bug

Hi AWS team,

I noticed that the **aws-java-sdk-efs** module of the *AWS SDK for Java* doesn't support [waiters](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/waiters.html) (I am using software.amazon.awssdk:bom:2.17.270): is there any reason why it was not implemented? The waiters are supported in others AWS SDK modules like **aws-java-sdk-efs**.

Also, is the *AWS SDK for Java* providing a workaround to implement a waiter function for the EfsClient, to wait for a created File System to be ready and that wouldn't imply to build a new waiter logic from scratch?

### Expected Behavior

`aws-java-sdk-efs` should support provide a `EfsWaiter` class, that would be instantiated by calling `EfsClient.waiter()`. This waiter could be used to wait for a File System to be ready for example.

For example, `aws-java-sdk-rds` provides a `RdsWaiter` that can  be instantiated by calling `RdsClient.waiter()`

### Current Behavior

There is no `EfsWaiter` provided in the `aws-java-sdk-efs` module and the  `EfsClient.waiter()` method doesn't exist

### Reproduction Steps

Try to compile the class below:
```java
import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.efs.EfsClient;
import software.amazon.awssdk.services.rds.RdsClient;
import software.amazon.awssdk.services.rds.waiters.RdsWaiter;

public class AwsBug {
    public static void main(String[] args) {
        RdsClient rdsClient = RdsClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(ProfileCredentialsProvider.create())
                .build();
        RdsWaiter rdsWaiter = rdsClient.waiter();
        EfsClient efsClient = EfsClient.builder()
                .region(Region.US_EAST_1)
                .credentialsProvider(ProfileCredentialsProvider.create())
                .build();
        efsClient.waiter();
    }
}
```
The compiler returns:
```
java: cannot find symbol
  symbol:   method waiter()
  location: variable efsClient of type software.amazon.awssdk.services.efs.EfsClient
```

### AWS Java SDK version used

2.17.270

### JDK version used

openjdk version "17.0.4" 2022-07-19 LTS OpenJDK Runtime Environment Zulu17.36+13-CA (build 17.0.4+8-LTS) OpenJDK 64-Bit Server VM Zulu17.36+13-CA (build 17.0.4+8-LTS, mixed mode, sharing)

### Operating System and version

macOS Monterey 12.5.1

**Comment by debora-ito** [comment]
Hi @rbsamoht, thank you for reaching out.

Waiters in the SDK are created based on models provided by each service team - the RDS model is in [here](https://github.com/aws/aws-sdk-java-v2/tree/master/services/rds/src/main/resources/codegen-resources), for example. This would be a request for the EFS Team to release a waiter model.

We got the same ask in the past, let's use it to track progress - https://github.com/aws/aws-sdk/issues/236.
