### ISSUE TITLE
Waiter for GlobalSecondaryIndex to be ACTIVE

### ISSUE THREAD

**Issue by viv-dh** [aws/aws-sdk-java-v2#3421]
### Describe the feature

Currently we have waiters for table to be active as described here - https://aws.amazon.com/blogs/developer/using-waiters-in-the-aws-sdk-for-java-2-x/.

However, if I am creating a GlobalSecondaryIndex, there is not equivalent method on the waiter, to wait for the index to be ACTIVE.

Such a method was present in the v1 SDK - Index.waitForActive() - https://aws.amazon.com/blogs/developer/create-update-and-delete-global-secondary-indexes-using-the-amazon-dynamodb-document-api/

This seems to have been missed out in v2 SDK

### Use Case

I need to create multiple indexes on an existing table and need one index create operation to be completed before I trigger the next index creation. Hence need a waiter for this.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.15.0

### JDK version used

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Operating System and version

WINDOWS 11

**Comment by debora-ito** [comment]
@viv-dh the GlobalSecondaryIndex waiter was part of v1's DynamoDB Document API, which is not supported yet in v2. I've added your request to the thread, let's track the progress over there - https://github.com/aws/aws-sdk-java-v2/issues/36

**Comment by DaltonWorsnup** [comment]
Is there any documentation for this change? I cannot find the desired behavior in the SDK version 2.25.14
