### ISSUE TITLE
Enhanced DynamoDB: Allow ignoreNulls to be configurable with Put Item 

### ISSUE THREAD

**Issue by robertisnapper** [aws/aws-sdk-java-v2#3445]
### Describe the feature

Proposing to allow the user to configure whether ignoreNulls is set when building a PutItemEnhancedRequest. This would work much the same as it currently does in the UpdateItemEnhancedRequest.Builder for example:

```Java
        PutItemEnhancedRequest<MyEntity> request = PutItemEnhancedRequest.builder(MyEntity.class)
            .item(myItem)
            .ignoreNulls(false)
            .build();
            
            myTable.putItem(request);
```

### Use Case

We're experiencing issues where some of our later data pipelines are expecting fields that don't exist which causes errors. 
This change would allow us to have the fields existing, albeit as nulls, at the start of our pipeline so we don't have to handle potentially missing fields.

### Proposed Solution

Proposing adding a `ignoreNulls(boolean)` method to the `PutItemEnhancedRequest.Builder`, matching the method in the `UpdateItemEnhancedRequest.Builder`.

Then also updating the `PutItemOperation.generateRequest(...)` method to check the configuration from the request.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.16.101

### JDK version used

OpenJDK Runtime Environment Corretto-8.292.10.1

### Operating System and version

Microsoft Windows 11 Pro

**Comment by yasminetalby** [comment]
Hello @robertisnapper ,

Thank you very much for your submission. 

By definition, [ignoreNulls(Boolean ignoreNulls)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/UpdateItemEnhancedRequest.Builder.html#ignoreNulls(java.lang.Boolean)) Sets if the update operation should ignore attributes with null values. By default, the value is false.

If set to true, any null values in the Java object will be ignored and not be updated on the persisted record. This is commonly referred to as a 'partial update'. If set to false, null values in the Java object will cause those attributes to be removed from the persisted record on update.

PutItemEnhancedRequest defines parameters used to write an item to a DynamoDb table using the putItem() operation (such as [DynamoDbTable.putItem(PutItemEnhancedRequest)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbTable.html#putItem(software.amazon.awssdk.enhanced.dynamodb.model.PutItemEnhancedRequest)) or [DynamoDbAsyncTable.putItem(PutItemEnhancedRequest)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbAsyncTable.html#putItem(software.amazon.awssdk.enhanced.dynamodb.model.PutItemEnhancedRequest))). 
This operation calls the [low-level DynamoDB API PutItem operation](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_PutItem.html) which as per the documentation has the following limitation: "_When you add an item, the primary key attributes are the only required attributes. Attribute values cannot be null. Empty String and Binary attribute values are allowed. Attribute values of type String and Binary must have a length greater than zero if the attribute is used as a key attribute for a table or index. Set type attributes cannot be empty._"

Could you please clarify your expectation for "ignoreNulls" configuration with PutItemEnhancedRequest? From my understanding, you would like to be able to use putItems with all null attributes (except the primary key attributes).

Best,

Yasmine
