### ISSUE TITLE
Missing details on max batch size for batchWriteItem operations in DynamoDbEnhancedClient

### ISSUE THREAD

**Issue by bigunyak** [aws/aws-sdk-java-v2#3476]
### Describe the issue

I've checked several classes related to DynamoDbEnhancedClient and non of them provide any details on the max allowed batch size and what is the recommended approach to handle batches of bigger sizes. The classes I checked:
* [DynamoDbEnhancedClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.html)
* [BatchWriteItemEnhancedRequest.Builder](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/BatchWriteItemEnhancedRequest.Builder.html)
* [WriteBatch.Builder](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/WriteBatch.Builder.html)

From DynamoDB API Reference docs for [BatchWriteItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) operation, I know that the limit is 25 items put or delete operations. But looking at the library docs, it's not clear at all if the library makes any effort to hide the API operation limit behind the scenes and work around it. From my testing it doesn't appear to be so, but would be great to make it clear in the docs.

### Links

* https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/DynamoDbEnhancedClient.html
* https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/BatchWriteItemEnhancedRequest.Builder.html
* https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/model/WriteBatch.Builder.html

**Comment by debora-ito** [comment]
Thank you @bigunyak this is a great feedback. I'll do some investigation and clarify this.

**Comment by debora-ito** [comment]
@bigunyak after browsing through the code and running some local tests it looks like there's no special handling of the batch size done by the SDK, so the BatchWriteItemEnhancedRequest is bound by the service-side validations of the low-level BatchWriteItem API. I created a batch request with 30 items and got an exception in the response:
```
Map value must satisfy constraint: [Member must have length less than or equal to 25, Member must have length greater than or equal to 1]
```

This seems to match what you've experienced, so we'll add this info to the BatchWriteItemEnhancedRequest Javadoc.
