### ISSUE TITLE
S3Client.putObjectAcl() issue

### ISSUE THREAD

**Issue by gustavotemple** [aws/aws-sdk-java-v2#3478]
### Describe the bug

Like https://github.com/aws/aws-sdk-java-v2/issues/1488, calling S3Client.putObjectAcl() with an AccessControlPolicy triggers a S3Exception with error message "The XML you provided was not well-formed or did not validate against our published schema".

### Expected Behavior

PutObjectACL requests should complete successfully.

### Current Behavior

The request fails with an S3Exception and message "The XML you provided was not well-formed or did not validate against our published schema"

### Reproduction Steps

This is the code I used:

```java
            // add new grantee to acl
            Grantee grantee = Grantee.builder()
                    .type(Type.CANONICAL_USER)
                    .id("xxxxxxxxxxxxxxxxxxxxxxxx") // canonical id
                    .build();
            Grant newGrantee = Grant.builder()
                    .grantee(grantee)
                    .permission(Permission.FULL_CONTROL)
                    .build();

            AccessControlPolicy acl = AccessControlPolicy.builder()
                    .grants(newGrantee)
                    .build();

            //put the acl
            PutObjectAclRequest putAclReq = PutObjectAclRequest.builder()
                    .bucket("bucket") // bucket
                    .accessControlPolicy(acl)
                    // .contentType("application/xml") <-- not work too
                    .key("key") // key
                    .build();

            s3.putObjectAcl(putAclReq);
```

And I tried this one too:

```java
            PutObjectAclRequest putAclReq = PutObjectAclRequest.builder()
                    .bucket("bucket") // bucket
                    .grantFullControl("xxxxxxxxxxxxx") // canonical id
                    // .contentType("application/xml") <-- not work too
                    .key("key") // key
                    .build();

            s3.putObjectAcl(putAclReq);
```

In both cases the error log was: `software.amazon.awssdk.services.s3.model.S3Exception: The XML you provided was not well-formed or did not validate against our published schema` 

Using CLI works fine:

```console
/usr/local/bin/aws s3api put-object-acl --bucket bucket --key key --grant-full-control id=xxxxxxxxxxxx
```

### AWS Java SDK version used

2.17.285

### JDK version used

1.8

### Operating System and version

Ubuntu 18.04.6 LTS

**Comment by yasminetalby** [comment]
Hello @gustavotemple ,

Thank you very much for your submission.

If you look at the PutObjectAcl [API reference](https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutObjectAcl.html), your [AccessControlPolicy](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/AccessControlPolicy.html) is missing the owner.

Here is a code snippet for reference:
```
 AccessControlPolicy acl = AccessControlPolicy.builder()
                .owner(id)
                .grants(grantlist)
                .build();
```
With : 
`id` : The ID of the owner of this bucket. 
`grantlist`: A list of grants.

[Here](https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/s3/src/main/java/com/example/s3/SetAcl.java) is a full example which demonstrates how to set a new access control list (ACL) to an Amazon Simple Storage Service (Amazon S3) bucket using the AWS Java SDK v2 that might be helpful as well.

Let me know if this solves your issue and if you have any further question!

Sincerely,

Yasmine
