### ISSUE TITLE
getObjectAttributes 500 internal error

### ISSUE THREAD

**Issue by namcorka** [aws/aws-sdk-java-v2#3483]
### Describe the bug

Hi team,

we are facing some issues with the latest SDK version `2.17.290`, when using S3AsyncClient.getObjectAttributes. The SDK is returning the following error details:

`{"class":"software.amazon.awssdk.services.s3.model.S3Exception","msg":"We encountered an internal error. Please try again. (Service: S3, Status Code: 500, Request ID: 9GKB9VZ6WNQY2B7S, Extended Request ID: 0lGd5on1EHoT/MPphTJXR9SHtx1h3Nqrs7pJxBN2091S4tv9IaGd52F4WmcroywrHxq2WqnLdcxRhDHa1o0Dmw==)"`

We are aware that the S3 key contains some special characters, but other methods like `getObjectTagging` are working for the same key.

Please help. Thanks in advance.

### Expected Behavior

To return the GetObjectTaggingResponse succesfully.

### Current Behavior

`{"timestamp":"2022-10-12T11:39:05,317Z","level":"ERROR","thread":"sdk-async-response-1-7","message":"Error while processing message with id d1eddd65-4c95-4590-aba7-70e35ea073fd: ","logger":"XXX.SqsDeduplicationListener","throwable":{"class":"software.amazon.awssdk.services.s3.model.S3Exception","msg":"We encountered an internal error. Please try again. (Service: S3, Status Code: 500, Request ID: 9GKB9VZ6WNQY2B7S, Extended Request ID: 0lGd5on1EHoT/MPphTJXR9SHtx1h3Nqrs7pJxBN2091S4tv9IaGd52F4WmcroywrHxq2WqnLdcxRhDHa1o0Dmw==)","stack":["software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)","software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleResponse(AwsXmlPredicatedResponseHandler.java:108)","software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:85)","software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handle(AwsXmlPredicatedResponseHandler.java:43)","software.amazon.awssdk.core.internal.handler.BaseClientHandler.lambda$successTransformationResponseHandler$7(BaseClientHandler.java:264)","software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler.lambda$prepare$0(AsyncResponseHandler.java:89)","java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)","java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)","java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)","software.amazon.awssdk.core.internal.http.async.AsyncResponseHandler$BaosSubscriber.onComplete(AsyncResponseHandler.java:132)","software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$DataCountingPublisher$1.onComplete(ResponseHandler.java:513)","software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.runAndLogError(ResponseHandler.java:250)","software.amazon.awssdk.http.nio.netty.internal.ResponseHandler.access$600(ResponseHandler.java:75)","software.amazon.awssdk.http.nio.netty.internal.ResponseHandler$PublisherAdapter$1.onComplete(ResponseHandler.java:371)","software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.complete(HandlerPublisher.java:447)","software.amazon.awssdk.http.nio.netty.internal.nrs.HandlerPublisher.handlerRemoved(HandlerPublisher.java:435)","io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)","io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)","io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:477)","io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:423)","software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.removeHandlerIfActive(HttpStreamsHandler.java:361)","software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.handleReadHttpContent(HttpStreamsHandler.java:223)","software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsHandler.channelRead(HttpStreamsHandler.java:199)","software.amazon.awssdk.http.nio.netty.internal.nrs.HttpStreamsClientHandler.channelRead(HttpStreamsClientHandler.java:173)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","software.amazon.awssdk.http.nio.netty.internal.LastHttpContentHandler.channelRead(LastHttpContentHandler.java:43)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)","io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324)","io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296)","io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)","io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)","io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)","io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)","io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)","io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)","io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)","io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)","io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)","io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)","io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)","io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)","io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)","io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)","io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)","io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)","java.lang.Thread.run(Thread.java:834)"]}}`

### Reproduction Steps

```
var request = GetObjectAttributesRequest.builder()
                .bucket("test")
                .key("Test/Test/‘00s/MEX+LAT/test.png)
                .objectAttributes(ObjectAttributes.CHECKSUM)
                .build();

        return s3AsyncClient.getObjectAttributes(request);
```

### AWS Java SDK version used

2.17.290

### JDK version used

java version "11.0.6" 2020-01-14 LTS

### Operating System and version

macOs Monterey, 12.3

**Comment by yasminetalby** [comment]
Hello @namcorka ,

Thank you very much for your submission.

The error code 500 Internal Error indicates that Amazon S3 is unable to handle the request at that time.

All requests that return 5xx errors from Amazon S3 can be retried. Therefore, it's a best practice to have a fault-tolerance mechanism or to implement retry logic for any applications making requests to Amazon S3. That way, S3 can recover from these errors.

Here is some troubleshooting documentation that goes over [How to troubleshoot a HTTP 500 or 503 error from Amazon S3](https://aws.amazon.com/premiumsupport/knowledge-center/http-5xx-errors-s3/) as well as [How to troubleshoot intermittent 500 Internal Error responses from Amazon S3?](https://aws.amazon.com/premiumsupport/knowledge-center/s3-intermittent-500-internal-error/).

Let me know if you have any other questions!

Best,

Yasmine

**Comment by namcorka** [comment]
Hi Yasmine, 

thank you for your quick response.
I’m pretty sure that this issue has nothing to do with the temporary unavailability of the server, becuase this is happening only on s3 folders with the special character - it happens all the time (we have a retry mechanism at our end). Keys without special characters are passing the method.

Can you please recheck the request.

**Comment by yasminetalby** [comment]
Hello @namcorka ,

Thank you very much for your reply. 

I have attempted to reproduce your behavior following your reproduction steps (and using the same key `Test/Test/‘00s/MEX+LAT/test.png`") and have experienced the same behavior which occurs also at retry. 

I have attempted to run the same request with different version of the key name provided :  it seems that the behavior is only present with the character `‘` in the key name 

I have also attempted the `getObjectTagging` request with the key `Test/Test/‘00s/MEX+LAT/test.png` which completed successfully. 

Using the CLI with all use case above and was able to reproduce the same behavior. It seems that this is a service issue.

Thank you very much for bringing this up to our attention!
I will reach out to the service team and will on this issue update here.

Best regards,

Yasmine

**Comment by mazamachi** [comment]
I am facing the same problem.
I am using aws-sdk-node-v3, but similarly GetObjectAttributes fails if the filename contains Japanese (i.e., multi-byte characters) and S3 returns a 500 error response.

I would like to know if there is any progress on this issue.

Thank you in advance.

**Comment by yasminetalby** [comment]
Hello @mazamachi ,

Regarding this issue: There is a ticket open to the service-team regarding the behavior above as this is not a Java SDK issue but rather a service issue. There is no resolution on their end for now. I will post an update and resolve this issue once I get a resolution update. Because this is a service issue, the behavior will impact all SDKs.

Regarding the behavior you experience I have a few questions to make sure this is the same issue reported here:
1. Are other methods other methods like `getObjectTagging` working for the same key?
2. Have you attempted to use the CLI? If yes is the behavior the same as with the SDK?

On another note, this is the repository for the `aws-java-sdk-v2`. For general issue submission, I would recommend to open an issue in the appropriate repository as each SDK is supported by different teams. 

Thank you very much for your submission.
Sincerely,

Yasmine

**Comment by palemieux** [comment]
I am experiencing the same issue with keys that contain [non-breaking space characters](https://www.compart.com/en/unicode/U+00A0): `get-object` succeeds but `get-object-attributes` fails with _An error occurred (InternalError) when calling the GetObjectAttributes operation (reached max retries: 2): We encountered an internal error. Please try again._

**Comment by yasminetalby** [comment]
Hello @palemieux ,

Thank you very much for your feedback. Unfortunately this issue hasn't yet been addressed by the service team. I'll forward this right away. 

Thank you again for your time and collaboration.

Sincerely,

Yasmine

**Comment by dhhoang** [comment]
Hi, we are also experiencing this issue (using .NET SDK)
Sharing our current work-around for getting the checksum: Use `GetObjectMetadata()` instead of `GetObjectAttributes`:  
```csharp
var objectMdResponse = await _s3Client.GetObjectMetadataAsync(new GetObjectMetadataRequest
{
    BucketName = bucket,
    Key = key,
    ChecksumMode = ChecksumMode.ENABLED
});
var sha256 = objectMdResponse.ChecksumSHA256;
```

**Comment by debora-ito** [comment]
Hi everyone, I tried to reproduce this on the latest version of the SDK (2.29.0) but I can't reproduce the error 500, the getObjectAttributes returns successfully for the key `Test/Test/‘00s/MEX+LAT/leaves.jpeg`.

If you still are experiencing the issue, please generate the verbose wirelogs ([instructions here](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose)) and check if the special characters in the object name are being encoded automatically by the Java SDK as expected. For example, the wirelogs of my local tests:

```
GET /Test/Test/%E2%80%9800s/MEX%2BLAT/analyze.png?attributes HTTP/1.1
Host: debora-bucket.s3.us-west-2.amazonaws.com
amz-sdk-invocation-id: 28d4cacd-f0f7-9446-5884-5d82a1425ed7
amz-sdk-request: attempt=1; max=4
Authorization: AWS4-HMAC-SHA256 Credential=xxx/20241025/us-west-2/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-request;host;x-amz-content-sha256;x-amz-date;x-amz-object-attributes;x-amz-security-token, Signature=xxx
User-Agent: xxx
x-amz-content-sha256: UNSIGNED-PAYLOAD
X-Amz-Date: 20241025T205737Z
x-amz-object-attributes: Checksum
```

Note how the object name is encoded in the request.

If you still see the 500 error code, please provide a repro code and the verbose wirelogs, and we'll take a look.
