### ISSUE TITLE
Unable to make service call on KinesisClient

### ISSUE THREAD

**Issue by pjonnlagadda** [aws/aws-sdk-java-v2#3498]
### Describe the bug

I am working on the migration of aswsdkjava from V1 to V2 and  Using the below code trying to make an api call to kinesisClient and ending up with the error. But the same thing is working as expected in the V1 with the same config values
I cannot see any headers in the sending request. But even in the V1 we did not set any external headers but observed some headers. Can anyone help on the goforward?

**V2 log statements**

> 2022-10-17 19:01:43.375 [main         ] DEBUG software.amazon.awssdk.request                :  85 - Sending Request: DefaultSdkHttpFullRequest(httpMethod=POST, protocol=http, host=localhost, port=62542, encodedPath=/stream/, headers=[amz-sdk-invocation-id, Content-Length, Content-Type, User-Agent, X-Amz-Target], queryParameters=[])

> 2022-10-17 19:01:43.376 [main         ] DEBUG _ s_.a.a.c.internal.io.SdkLengthAwareInputStream :  85 - Specified InputStream length of 4441 has been reached. Returning EOF.__

**V1 Log statements**

> Sending Request: POST http://localhost:59628/stream / 
Headers: (amz-sdk-invocation-id: 6acc15ee-c89c-132a-267e-279842498c99, 
			Content-Length: 41, 
			Content-Type: application/x-amz-json-1.1, 
			User-Agent: aws-sdk-java/1.12.308 Windows_10/10.0 OpenJDK_64-Bit_Server_VM/25.322-b06 java/1.8.0_322 vendor/Amazon.com_Inc. cfg/retry-mode/legacy, X-Amz-Target: Kinesis_20131202.DescribeStream, ) 

**Error on V2:-**

> javax.ws.rs.NotSupportedException: RESTEASY003065: Cannot consume content type

**The code used to make an api call**

> AwsBasicCredentials awsCreds = AwsBasicCredentials.create(accessKey, secertKey);
StaticCredentialsProvider credentialsProvider = StaticCredentialsProvider.create(awsCreds);
KinesisClient kinesisClient = KinesisClient.builder()
.region(Region.of(region))
.endpointOverride(URI.create(endpoint))
.credentialsProvider(credentialsProvider)
.build();

> DescribeStreamRequest describeStreamRequest = DescribeStreamRequest.builder().streamName(streamName).build();
> DescribeStreamResponse response = kinesisClient.describeStream(describeStreamRequest);

### Expected Behavior

Should make an api call as expected in the V1

### Current Behavior

Ending up with an error

`2022-10-17 19:01:43.389 [main         ] ERROR lid://infor.streaming.kinesis                 : 207 - Received error response : null (Service: Kinesis, Status Code: 415, Request ID: null)
software.amazon.awssdk.services.kinesis.model.KinesisException: null (Service: Kinesis, Status Code: 415, Request ID: null)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)`

### Reproduction Steps

Make an api call to using the below sample code

`AwsBasicCredentials awsCreds = AwsBasicCredentials.create(accessKey, secertKey);
StaticCredentialsProvider credentialsProvider = StaticCredentialsProvider.create(awsCreds);
KinesisClient kinesisClient = KinesisClient.builder()
.region(Region.of(region))
.endpointOverride(URI.create(endpoint))
.credentialsProvider(credentialsProvider)
.build();

DescribeStreamRequest describeStreamRequest = DescribeStreamRequest.builder().streamName(streamName).build(); DescribeStreamResponse response = kinesisClient.describeStream(describeStreamRequest);`

### AWS Java SDK version used

V2

### JDK version used

1.8

### Operating System and version

Windows OS

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you very much for your submission.

I have attempted to recreate the request in both v1.12.308 and v2.17.295 and both request were successful and worked as expected.

A few things:
1. Could you please provide the verbose wire logs. [Here](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html) is some documentation to enable verbose wire log in AWS Java SDK v2. This would help us to get more information on what is the exact request being sent.
2. Could you potentially specify which version of the SDK v2 you are using as well for reference?
3. It would also be helpful to see the full stack trace associated with the issue.

Thank you for your time and collaboration.
Sincerely,

Yasmine

**Comment by pjonnlagadda** [comment]
It has been observed that, content type is differed from V1 to V2.
In the V1 it is **Content-Type: application/x-amz-json-1.1** and in the V2 is it changed to **Content-Type=[application/x-amz-cbor-1.1]**?
After making this change in my local code, it went fine for me. Can you please clarify is something changed?

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

When attempting to recreate the request in both v1.12.308 and v2.17.295, both use case had `Content-Type: application/x-amz-cbor-1.1.
`

If you look at the code for the AmazonKinesis client in v1, cbor is enabled by default as content-type since AWS Java SDK v1.11.71 (12/2016 release) ([see](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-kinesis/src/main/java/com/amazonaws/services/kinesis/AmazonKinesisClient.java#L82h))

Is it possible that you have disabled the use of CBOR in v1? This forces the request to be sent over the wire as a AWS JSON. ([see](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/SDKGlobalConfiguration.html#AWS_CBOR_DISABLE_ENV_VAR))

If you look at the [migration guide documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-client-changes.html), The `AWS_CBOR_DISABLED`  environment variables related to default client creation  in v1 have been changed ` CBOR_ENABLED` in v2 and the `com.amazonaws.sdk.disableCbor` system properties related to default client creation in v1 has been changed to `aws.cborEnabled` in v2.

This might be the reason why you have noticed a change of behavior between AWS Java SDK v1 and v2.

Let me know if this helps and/or if you have any further questions.

Sincerely,

Yasmine

**Comment by pjonnlagadda** [comment]
Yes in the V1 we have disabled the CBOR and for V2 i have replaced the system property accordingly 
`//System.setProperty("com.amazonaws.sdk.disableCbor", "true");`
`System.setProperty("aws.cborEnabled", "true");`

Where as i have mock service method like below 
> @POST
	@Consumes("application/x-amz-cbor-1.1")
	@Produces(MediaType.APPLICATION_JSON)
	// This method just acts as mock of Actual amazon kinesis stream.
	// Processes the data to specified stream according to limitations.
	// Otherwise throws relevant exceptions.
	**public Response stream(final InputStream inputStream, @Context final HttpHeaders headers)
			throws IOException {**	
				**String  jsonResult  = new String (SdkBytes.fromInputStream(inputStream).asByteArray(), Charset.forName("UTF-8"));**
				PutRecordRequest putRecordRequest = JsonConverter.fromJson(sdkBytes, PutRecordRequest.class);

and in the string **jsonResult**  from inputStream getting as **�jStreamNamexxxx_xxx_xxx_xxxxxxdDataY{** instead of 
**{"StreamName":"xxx_xxx_xxx_xxxxxx","Data":"xxxxxx"}**
Due to the special characters i am not able to parse properly into the PutRecordRequest

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

Thank you for your response. I apologize for any confusion.

Setting `cborEnabled` to true enables Cbor. Setting `disableCbor` to true disables Cbor.

Therefore to disable cbor in v2, you have to set `cborEnabled` to false.

I hope this provides more clarity.
Let me know if this solves your issue or if you need me to provide further guidance.

Sincerely,

Yasmine

**Comment by pjonnlagadda** [comment]
No Problem we can close the issue as its got resolved from my end.

**Comment by yasminetalby** [comment]
Hello @pjonnlagadda ,

I am glad to hear! I will close this issue now.

Best regards,

Yasmine
