### ISSUE TITLE
DynamoDbIgnoreNulls is not respected

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#3499]
### Describe the bug

This is a duplicate of https://github.com/aws/aws-sdk-java-v2/issues/2938, which was closed without being fixed.

I am using the DynamoDB Enhanced Client's `@DynamoDbIgnoreNulls` exactly as demonstrated in the documentation:

```
@DynamoDbBean
class Dispatch {
  @DynamoDbIgnoreNulls
  Status getStatus() { return status; }
}
```

When the `Dispatch` object is written using the enhanced client, all of the properties on `Status` with null values are written as `AttributeValue(NUL=true)` instead of omitted.

### Expected Behavior

I expected null values not to be included at all.

### Current Behavior

`NUL` attributes are inserted.

### Reproduction Steps

```
@DynamoDbBean
class Status {
  String status
}

class Dispatch {
  Status status

  @DynamoDbIgnoreNulls
  Status getStatus() { return status; }
}
```

### Possible Solution

The `ignoreNulls` flag appears not to be applied recursively.

### AWS Java SDK version used

2.17.284

### JDK version used

AdoptOpenJDK-11.0.11+9

### Operating System and version

Gentoo Linux

**Comment by debora-ito** [comment]
Hi @chrylis apologies for the long delay in response here.

I'm not able to repro, can you share a sample code with the DynamodbEnhanced operation?

Are you using flattened beans?

**Comment by dariellbowo** [comment]
I am having the same issue with this configuration
```
@DynamoDbBean
public abstract class Parent {
    private Integer id;
    private Instant createdTimestamp;
    
    @DynamoDbPartitionKey
    @DynamoDbAttribute("id")
    public Integer getAccountId() {
        return id;
    }

    @DynamoDbAttribute("created_timestamp")
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @DynamoDbAutoGeneratedTimestampAttribute
    public Instant getCreatedTimestamp() {
        return createdTimestamp;
    }
}
public class Child{
    private String attribute1;
    private String attribute2;

    @DynamoDbAttribute("attribute_1")
    @DynamoDbIgnoreNulls
    public String getAttribute1() {
        return attribute1;
    }

    @DynamoDbAttribute("attribute_2")
    @DynamoDbIgnoreNulls
    public String getAttribute2() {
        return attribute2;
    }
}

client = enhancedAsyncClient.table(tableName, TableSchema.fromBean(Child.class));

Child child = new Child(777, "someValue1", "someValue2");
client.updateItem(child);

Child updatedChild = new Child(777, "someValue3");
enhancedAsyncClient.table(tableName, TableSchema.fromBean(Child.class)).updateItem(child);
client.updateItem(updatedChild);
// After this statement attribute2 will be empty while attribute1 is updated to "someValue3"
```
