### ISSUE TITLE
LoggingMetricPublisher not logging client side dynamodb metrics for Query Operation

### ISSUE THREAD

**Issue by OlofNiko** [aws/aws-sdk-java-v2#3500]
I am using LoggingMetricPublisher to log dynamodb client side performance and it is working for GetItem and UpdateItem requests but not working for Query operation.

This is how I'm creating DynamoDbEnhancedAsyncClient bean.
```
@Bean("OnlineMetricsQuery")
  DynamoDbEnhancedAsyncClient dynamoDbEnhancedAsyncClientQuery(ExecutorService executorService,
      LoggingMetricPublisher loggingMetricPublisher, TimeoutConfig timeoutConfig) {
    DynamoDbAsyncClient dynamoDbAsyncClient = DynamoDbAsyncClient.builder()
        .asyncConfiguration(getClientAsyncConfiguration(executorService))
        .httpClientBuilder(getHttpClientConfig())
        .overrideConfiguration(o -> o.addMetricPublisher(loggingMetricPublisher))
        .overrideConfiguration(o -> o.apiCallTimeout(Duration.ofMillis(timeoutConfig.getQueryTimeoutInMillis())))
        .build();
    return DynamoDbEnhancedAsyncClient.builder().dynamoDbClient(dynamoDbAsyncClient).build();
  }
```

For update and get requests I can see logs like below but can't find anything when I perform query operation.
`LoggingMetricPublisher : Metrics published: MetricCollection(name=ApiCall, metrics=[MetricRecord(metric=MarshallingDuration, value=PT0.009273805S), MetricRecord(metric=RetryCount, value=0), MetricRecord(metric=ApiCallSuccessful, value=true), MetricRecord(metric=OperationName, value=UpdateItem), MetricRecord(metric=ApiCallDuration, value=PT0.051049545S), MetricRecord(metric=CredentialsFetchDuration, value=PT0.000024885S), MetricRecord(metric=ServiceId, value=DynamoDB)], children=[MetricCollection(name=ApiCallAttempt, metrics=[MetricRecord(metric=HttpStatusCode, value=200), MetricRecord(metric=BackoffDelayDuration, value=PT0S), MetricRecord(metric=SigningDuration, value=PT0.003313071S), MetricRecord(metric=AwsRequestId, value=DV1T44N6A7BJBFN8UQ7SM0BC7FVV4KQNSO5AEMVJF66Q9ASUAAJG), MetricRecord(metric=UnmarshallingDuration, value=PT0.020949084S)], children=[MetricCollection(name=HttpClient, metrics=[MetricRecord(metric=AvailableConcurrency, value=1), MetricRecord(metric=LeasedConcurrency, value=0), MetricRecord(metric=ConcurrencyAcquireDuration, value=PT0.007133S), MetricRecord(metric=PendingConcurrencyAcquires, value=0), MetricRecord(metric=MaxConcurrency, value=300), MetricRecord(metric=HttpClientName, value=NettyNio)], children=[])])]) `

`Metrics published: MetricCollection(name=ApiCall, metrics=[MetricRecord(metric=MarshallingDuration, value=PT0.000776901S), MetricRecord(metric=RetryCount, value=0), MetricRecord(metric=ApiCallSuccessful, value=true), MetricRecord(metric=OperationName, value=GetItem), MetricRecord(metric=ApiCallDuration, value=PT0.177394059S), MetricRecord(metric=CredentialsFetchDuration, value=PT0.004702933S), MetricRecord(metric=ServiceId, value=DynamoDB)], children=[MetricCollection(name=ApiCallAttempt, metrics=[MetricRecord(metric=SigningDuration, value=PT0.005833326S), MetricRecord(metric=UnmarshallingDuration, value=PT0.010095607S), MetricRecord(metric=ServiceCallDuration, value=PT0.15321378S), MetricRecord(metric=HttpStatusCode, value=200), MetricRecord(metric=BackoffDelayDuration, value=PT0S), MetricRecord(metric=AwsRequestId, value=R7GR0EG59NFHBELJSSQJRMJI93VV4KQNSO5AEMVJF66Q9ASUAAJG)], children=[MetricCollection(name=HttpClient, metrics=[MetricRecord(metric=AvailableConcurrency, value=0), MetricRecord(metric=LeasedConcurrency, value=0), MetricRecord(metric=ConcurrencyAcquireDuration, value=PT0.053934S), MetricRecord(metric=PendingConcurrencyAcquires, value=0), MetricRecord(metric=MaxConcurrency, value=300), MetricRecord(metric=HttpClientName, value=NettyNio)], children=[])])])`

Does client side performance metrics support query operation? Can't find anything regarding this [here](https://docs.amazonaws.cn/en_us/sdk-for-java/latest/developer-guide/metrics.html)

### Expected Behavior

LoggingMetricPublisher  should log dynamodb client side performance metrics for query operation as well.

### Current Behavior

LoggingMetricPublisher doesn't log dynamodb client side performance metrics for query operation as well.

### Reproduction Steps

1. Create a DynamoDbAsyncClient add LoggingMetricPublisher as a metric publisher
2. Perform a query operation and check if any logs are logged by LoggingMetricPublisher regarding the client side performance

### AWS Java SDK version used

2.17.257

### JDK version used

11

### Operating System and version

Linux64

**Comment by debora-ito** [comment]
```
DynamoDbAsyncClient dynamoDbAsyncClient = DynamoDbAsyncClient.builder()
        .asyncConfiguration(getClientAsyncConfiguration(executorService))
        .httpClientBuilder(getHttpClientConfig())
        .overrideConfiguration(o -> o.addMetricPublisher(loggingMetricPublisher))
        .overrideConfiguration(o -> o.apiCallTimeout(Duration.ofMillis(timeoutConfig.getQueryTimeoutInMillis())))
```

The second `overrideConfiguration` is replacing the first parameter. Try concatenating the two override configurations:

```
DynamoDbAsyncClient dynamoDbAsyncClient = DynamoDbAsyncClient.builder()
        .asyncConfiguration(getClientAsyncConfiguration(executorService))
        .httpClientBuilder(getHttpClientConfig())
        .overrideConfiguration(o -> o.addMetricPublisher(loggingMetricPublisher)
                .apiCallTimeout(Duration.ofMillis(timeoutConfig.getQueryTimeoutInMillis()))
        )
```

**Comment by OlofNiko** [comment]
Ohh! I see, overrideConfiguration method is passing a new ClientOverrideConfigurationBuilder each time and earlier changes are overridden. Thanks for the help 👍.

https://github.com/aws/aws-sdk-java-v2/blob/40b8869c5a24ceae5c41e520ab43e7fbfd06187a/core/sdk-core/src/main/java/software/amazon/awssdk/core/client/builder/SdkClientBuilder.java#L47
