### ISSUE TITLE
How to detect bucket region

### ISSUE THREAD

**Issue by paleloser** [aws/aws-sdk-java-v2#3554]
### Describe the issue

Reading the [documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html) on how to use the SDK, I find that in order to initialize the client I previously must know which region am I going to talk to.

Let's say I have a program whose job is receiving a bucket URL,`S3://bucket-name`, plus the credentials to write objects on it (`AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`). With that info. my program writes an object in the bucket. Currently my program doesn't accept more parameters.

Thus, it would try to instantiate an `S3Client` the following way:

```java
final String bucket = "bucket-name";
final String awsAccessKeyId = "...";
final String awsSecretAccessKey = "..."

final S3ClientBuilder clientBuilder = S3Client.builder();

// Configures the credentials
final AwsCredentials credentials = AwsBasicCredentials.create(awsAccessKeyId, awsSecretAccessKey);
final AwsCredentialsProvider credentialsProvider = StaticCredentialsProvider.create(credentials);
clientBuilder.credentialsProvider(credentialsProvider);

// Configures the region
try (final S3Client client = clientBuilder.build()) {
  final GetBucketLocationResponse response = client.getBucketLocation(GetBucketLocationRequest.builder().bucket(bucket).build());
  clientBuilder.region(Region.of(response.locationConstraintAsString()));
}

// Builds the client
this.client = clientBuilder.build()
```

However, when the program attempts so detect the region, it throws with the following exception:

> Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@353efdbf: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@4c0884e8: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@7b208b45: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@2fc07784: Unable to contact EC2 metadata service.]

Which in theory says that again, either the program must know previously in which region the bucket is located, or it won't be able to detect it dynamically.

Is that the expected behavior? Should I change my program input parameters to accept the bucket region as well? I find this very weird, since the URL `S3://` is the suggested way in the docs, and it doesn't contain all of the info about the target bucket.

Thanks in advance.

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/home.html
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/region-selection.html
https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-bucket-intro.html

**Comment by paleloser** [comment]
First of all, thank you for such quick and detailed response. It looks like your proposal does the job for me, unless for `us-east-1` as you mentioned, in which case I get a `403`. I'll just fallback to that region by default in case the detection failed.

I've also 👍🏼 -ed the feature request as well.

Regarding to possible documentation improvements on the AWS Java SDK v2, it'd be nice to have a section dedicated to this part in the S3 site. I mean, by reading the docs, I supposed that unless I already knew the region of the bucket, I couldn't perform any operation. But after this conversation I found out that some operations (like `GetBucketLocationRequest` here) don't really have that constraint; they just need a _random_ region to work.

On the other side, having this _restriction_ seems very weird to me (maybe I'm not enough familiar with how does the AWS API work). Because I've been able to connect to MinIO instances locally with the client, where the region didn't made any sense at all. So it would be also good to have some references on that.

Again thank you.

**Comment by yasminetalby** [comment]
Hello @paleloser ,

Thank you very much for your detailed feedback.
I am glad to hear this work around worked for you. 

I will bring up the documentation improvement for the S3 portion of the developer guide to the docs team. I agree that this behavior should be documented for better visibility. 
I also will look into improving our current documentation of [GetBucketLocation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#getBucketLocation(software.amazon.awssdk.services.s3.model.GetBucketLocationRequest)) with more details.

Thank you very much again for your feedback and contribution.

Sincerely,

Yasmine

**Comment by paleloser** [comment]
Great to hear that. From my side, we can close this issue now.
