### ISSUE TITLE
DynamoDbException is taking precedence over TransactionCanceledException.

### ISSUE THREAD

**Issue by aaronzhang1234** [aws/aws-sdk-java-v2#3561]
### Describe the bug

According to the documentation, if a `transactwriteitems` call fails for certain reasons a `TransactionCanceledException` would be returned with the specific items that failed and the reasons. However what is being returned back is a generic `DynamoDBException`
https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_TransactWriteItems.html#API_TransactWriteItems_Errors

### Expected Behavior

For a `TransactionCanceledException` to be returned back with a `CancellationReasons` field when bad data is being sent to DynamoDB.

### Current Behavior

We are getting a generic DynamoDB exception instead.

```
Caused by: software.amazon.awssdk.services.dynamodb.model.DynamoDbException: 2 validation errors detected: Value null at 'transactItems.1.member.update.updateExpression' failed to satisfy constraint: Member must not be null; Value null at 'transactItems.3.member.update.updateExpression' failed to satisfy constraint: Member must not be null (Service: DynamoDb, Status Code: 400, Request ID: RNCLR38M22543L85J8PA5ETFGBVV4KQNSO5AEMVJF66Q9ASUAAJG)
	at software.amazon.awssdk.services.dynamodb.model.DynamoDbException$BuilderImpl.build(DynamoDbException.java:95)

```

### Reproduction Steps

```java
  @Override
  public Void writeItemsBatch(Iterable items) {
    return Mono.just(items)
        .map(this::getTransactWriteItemsEnhancedRequest)
        .map(dynamoDbEnhancedAsyncClient::transactWriteItems)
        .transform(resultMono -> resultMono.flatMap(Mono::fromFuture))
        .timeout(Duration.ofSeconds(backoffDuration))
        .doOnNext(dbResponse -> log.info("Successfully saved event to Dynamo {} \n"))
        .doOnError(
            (Throwable e) ->
                standardDoOnError("Exception occurred when saving an event to Dynamo", e))
        .block();
  }

  public TransactWriteItemsEnhancedRequest getTransactWriteItemsEnhancedRequest(
      Iterable<Payment> paymentList) {
    TransactWriteItemsEnhancedRequest.Builder builder = TransactWriteItemsEnhancedRequest.builder();
    Payment payment = new Payment();
    payment.setPartitionKey(null);
    payment.setSortKey("sort");
    paymentList.add(payment);
    paymentList.forEach(
        payment -> {
          TransactUpdateItemEnhancedRequest<Payment> updateItemEnhancedRequest =
              TransactUpdateItemEnhancedRequest.builder(Payment.class)
                  .item(payment)
                  .ignoreNulls(true)
                  .build();
          builder.addUpdateItem(paymentTable, updateItemEnhancedRequest);
        });
    return builder.build();
  }
  ```

### Possible Solution

The `TransactionCancelledException` error should be returned or there should be a way to get it.

### Additional Information/Context

When adding a `conditionExpression` which fails onto the `TransactUpdateItemEnhancedRequest` the `TransactionCanceledException` is thrown, however it should be thrown for all reasons explained on the documentation..

### AWS Java SDK version used

2.18.3

### JDK version used

openjdk 18.0.2.1 2022-08-18

### Operating System and version

MacOS Monterey 12.6.1

**Comment by debora-ito** [comment]
@aaronzhang1234 apologies for the delay in replying here.

Who defines the type of exception is the service. To illustrate, I enabled the verbose wirelogs in my local tests:

(1) For the same error you provided in the description, here's the wirelogs with the actual message sent in the response by DynamoDB:

```
<< "HTTP/1.1 400 Bad Request[\r][\n]"
<< "Server: Server[\r][\n]"
<< "Date: Fri, 28 Apr 2023 01:20:20 GMT[\r][\n]"
<< "x-amzn-RequestId: xxx[\r][\n]"
<< "[\r][\n]"
<< "{"__type":"com.amazon.coral.validate#ValidationException","message":"1 validation error detected: Value null at 'transactItems.1.member.update.updateExpression' failed to satisfy constraint: Member must not be null"}"
```

`ValidationException` is not an error type listed in the [DynamoDB model](https://github.com/aws/aws-sdk-java-v2/blob/4aa623c338c83708391209777ebfa31ef7b18e5e/services/dynamodb/src/main/resources/codegen-resources/dynamodb/service-2.json#L735) for the TransactWriteItems operation, so the SDK will fallback to the more generic service exception `DynamoDbException`.

(2) Depending on the validation, DynamoDB will send a response with `TransactionCanceledException`, like when the data type of the partition key does not match the data type sent in the request:
```
<< "HTTP/1.1 400 Bad Request[\r][\n]"
<< "Server: Server[\r][\n]"
<< "Date: Fri, 28 Apr 2023 01:39:17 GMT[\r][\n]"
<< "x-amzn-RequestId: xxx[\r][\n]"
<< "[\r][\n]"
<< "{"__type":"com.amazonaws.dynamodb.v20120810#TransactionCanceledException","CancellationReasons":[{"Code":"ValidationError","Message":"The provided key element does not match the schema"}],"Message":"Transaction cancelled, please refer cancellation reasons for specific reasons [ValidationError]"}"
```

In this case, the SDK will throw `TransactionCanceledException`:
> software.amazon.awssdk.services.dynamodb.model.TransactionCanceledException: Transaction cancelled, please refer cancellation reasons for specific reasons [ValidationError] (Service: DynamoDb, Status Code: 400, Request ID: xxx)

**Comment by debora-ito** [comment]
We could ask DynamoDB to change the exception type to `TransactionCanceledException` but this would be a breaking change at this point.
