### ISSUE TITLE
Convenience Type Getters

### ISSUE THREAD

**Issue by spfink** [aws/aws-sdk-java-v2#359]
Follow up on #336 and add getters for convenience types.

## Expected Behavior
While you can set using a convenience type you can't get the convenience type back out. Adding a getter would be easy other than what to do with the naming of the getter.

## Possible Solution
Add a field to name the getter to the customization config? get[Field]Convenience?

## Context
#336

**Comment by millems** [comment]
Closing until someone asks for this directly.
