### ISSUE TITLE
DynamoDB Document API

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#36]
Review the inherited state of V1 Dynamo DB document API and determine which changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by jaymell** [comment]
Hi. I'm hoping it goes without saying, but it would be wonderful if this API would be updated to support the use of the async client and CompletableFutures.

**Comment by dagnir** [comment]
Feedback from v1: https://github.com/aws/aws-sdk-java/issues/1528

**Comment by bamapookie** [comment]
Any progress on this?

**Comment by martel** [comment]
"Feel free to comment on this issue with desired changes"

Document API had its downsides (like no Java 8 streams support, etc) but at this point I would rather have it with all the downsides than not have it at all. Is there an ETA for it?

**Comment by arashbi** [comment]
The state of documentation on dynamo, at least on java lang side, is very confusing.

**Comment by millems** [comment]
In 2.x, we're thinking of combining the Document APIs and DynamoDB Mapper. We're created prototype APIs we're interested in feedback on. See https://github.com/aws/aws-sdk-java-v2/issues/35#issuecomment-468435660 for how you can check our these prototypes and help us deliver the right thing for you.

**Comment by mwfpope** [comment]
I appreciated that the Document API in v1.11 had methods for converting from json to AttributeValue & vice versa because it made it possible to use DynamoDB for complicated data models without having to use DynamoDB Mapper.

Whatever happens in the new SDK, I would like to see a similar capability so that customers like me who don't want to use DynamoDB Mapper don't have to do all the heavy lifting of converting a complex data model.

**Comment by gibbonsj** [comment]
Is there a status on this now the DDB enhanced client is released?

I plus'd 1 on @mwfpope comment... item to/from json was a greatly appreciated feature in DDB.

**Comment by millems** [comment]
@gibbonsj The document client is high on our priority list. We should probably to a to/from json API as a separate feature request. I don't think our plans for the document client currently include a to/from JSON API in scope.

**Comment by bykka** [comment]
5 years without any updates. what a shame.

**Comment by millems** [comment]
We're aware this is a blocker for many people to move to 2.x, and it remains high on our priority list.

**Comment by bykka** [comment]
Version 1 does not support properly java modules. Version 2 does not provide full API. Great choice.
https://github.com/aws/aws-sdk-java/issues/1658

**Comment by debora-ito** [comment]
Feature request: support Global Secondary Indexes waiters - https://github.com/aws/aws-sdk-java-v2/issues/3421.

**Comment by mikhail-edk** [comment]
Bump

**Comment by joviegas** [comment]
Note that we have added Document API with EnhancedDocument APIs in V2 with [PR#3849](https://github.com/aws/aws-sdk-java-v2/pull/3849)
And then Strongly typed interface: EnhancedDocument provides a strongly typed interface for working with documents. This makes it easier for developers to work with documents and ensures that the data is correctly typed. Thus the Dynamic Unsafe API which accessed args and returns as Object are not added intentionally to make it strongly typed interface and avoid runtime issues,
