### ISSUE TITLE
Netty HTTP client blocking on DNS resolution

### ISSUE THREAD

**Issue by yanns** [aws/aws-sdk-java-v2#3629]
### Describe the bug

Netty threads are being blocked when calling InetAddress.getByName  (https://docs.oracle.com/javase/6/docs/api/java/net/InetAddress.html#getByName(java.lang.String))

<img width="783" alt="Screenshot 2022-12-15 at 14 43 28" src="https://user-images.githubusercontent.com/51669/207884323-3a161223-d5a0-4d90-a363-3029b867729c.png">

This impacts the scalability of the AWS java library.

### Expected Behavior

Netty threads should not be blocked

### Current Behavior

Netty threads are being blocked

### Reproduction Steps

Using the `NettyNioAsyncHttpClient`
```scala
  val builder = NettyNioAsyncHttpClient.builder()
  val httpClient: SdkAsyncHttpClient = builder.build()
```

### Possible Solution

A possible solution is to use netty-resolver-dns like in https://github.com/netty/netty/blob/4.1/example/src/main/java/io/netty/example/dns/tcp/TcpDnsClient.java

### AWS Java SDK version used

2.18.35

### JDK version used

17.0.5_8

### Operating System and version

linux

**Comment by martinKindall** [comment]
Hi @yanns , which tool are you using to show the graphics you attached?

**Comment by yanns** [comment]
The JVM is profiled with https://github.com/async-profiler/async-profiler.
The profile file is then opened by JDK mission control where the screenshot is coming from.

**Comment by martinKindall** [comment]
Thanks @yanns, I installed JDK mission and async-profiler and both work. I already took a flamegraph profile. 

I am having issues reproducing your results though using the .jfr format for the profile output. I can see the stacktrace correctly but the profiler is not saving the "Total Blocked" time, here's my command

`./profiler.sh -d 20 -i 5ms -f result3.jfr <PID>`

Would you mind sharing your command? So I can compare the args you used. Thanks.

**Comment by yanns** [comment]
It's a long time ago, but I think I used the following flags:
`-e cpu,alloc,lock,itimer`

**Comment by debora-ito** [comment]
Scanning through some old open issues, I believe this was addressed in PR https://github.com/aws/aws-sdk-java-v2/pull/3990, which added the `useNonBlockingDnsResolver` option to [NettyNioAsyncHttpClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/nio/netty/NettyNioAsyncHttpClient.Builder.html#useNonBlockingDnsResolver(java.lang.Boolean)).

Closing this.
