### ISSUE TITLE
Cannot invoke the `close` method on DynamoDBLocal client (aws-sdk-java-v2)

### ISSUE THREAD

**Issue by oleksii-syromolotov** [aws/aws-sdk-java-v2#3633]
### Describe the bug

We are using  `com.amazonaws:DynamoDBLocal:1.16.0`.
We have the IllegalArgumentException when trying to invoke method `close` on DynamoDBLocal client (instance of `com.amazonaws.services.dynamodbv2.local.shared.access.LocalDBClient`).

### Expected Behavior

The client should be closed, the test should be marked as passed.the 

### Current Behavior

```
object is not an instance of declaring class
java.lang.IllegalArgumentException: object is not an instance of declaring class
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.amazonaws.services.dynamodbv2.local.embedded.DDBExceptionMappingInvocationHandler.invoke(DDBExceptionMappingInvocationHandler.java:85)
	at com.sun.proxy.$Proxy35.close(Unknown Source)
	at com.company.aws.services.dynamodbv2.local.embedded.MyTestClass.closeShouldWork(MyTestClass.java:55)
```

### Reproduction Steps

Dependencies
```
implementation "software.amazon.awssdk:sdk-core:2.18.38"
implementation "software.amazon.awssdk:dynamodb:2.18.38"
implementation "com.amazonaws:DynamoDBLocal:1.16.0"
```

MyTestClass:
```
@Test
public void closeShouldWork() {
    DynamoDbClient dynamoDbClientEmbedded = DynamoDBEmbedded.create().dynamoDbClient();
    dynamoDbClientEmbedded.close();
}
```

### Possible Solution

In `com.amazonaws.services.dynamodbv2.local.embedded.DDBExceptionMappingInvocationHandler#invoke` we can see some conditional logic:
```
if (AmazonDynamoDB.class.equals(method.getDeclaringClass())) {
    result = method.invoke(this.impl.amazonDynamoDB(), args);
} else if (AmazonDynamoDBStreams.class.equals(method.getDeclaringClass())) {
    result = method.invoke(this.impl.amazonDynamoDBStreams(), args);
} else if (DynamoDbClient.class.equals(method.getDeclaringClass())) {
    isAWSSdkV2 = true;
    result = method.invoke(this.impl.dynamoDbClient(), args);
} else if (DynamoDbAsyncClient.class.equals(method.getDeclaringClass())) {
    isAWSSdkV2 = true;
    result = method.invoke(this.impl.dynamoDbAsyncClient(), args);
} else if (DynamoDbStreamsClient.class.equals(method.getDeclaringClass())) {
    isAWSSdkV2 = true;
    result = method.invoke(this.impl.dynamoDbStreamsClient(), args);
} else if (DynamoDbStreamsAsyncClient.class.equals(method.getDeclaringClass())) {
    isAWSSdkV2 = true;
    result = method.invoke(this.impl.dynamoDbAsyncClient(), args);
} else {
    result = method.invoke(this.impl, args);
}
```
Here we can see that the client choice for method invocation depends on what class the method belongs to. And the default case is to invoke method on this.impl (instance of `LocalDBClient` and obviously has not `close` method).

### AWS Java SDK version used

2.18.38

### JDK version used

```
openjdk version "1.8.0_322"
OpenJDK Runtime Environment Corretto-8.322.06.1 (build 1.8.0_322-b06)
OpenJDK 64-Bit Server VM Corretto-8.322.06.1 (build 25.322-b06, mixed mode)
```

### Operating System and version

Windows 10

**Comment by oleksii-syromolotov** [comment]
P.S. I know that this is not DynamoDbLocal repo, but I wasn`t able to find one. But I also saw that some people found help here in their issues with DynamoDbLocal. Like here - [issue 982](https://github.com/aws/aws-sdk-java-v2/issues/982)

**Comment by yasminetalby** [comment]
Hello @oleksii-syromolotov ,

Thank you very much for reaching out. 
You are right DynamoDbLocal is not owned by the AWS Java SDK Team but we can definitely reach out to the team owner.
I have opened a ticket to the service team regarding this behavior and will post all update here.

Thank you for your submission!

Sincerely,

Yasmine.

**Comment by debora-ito** [comment]
@oleksii-syromolotov The DynamoDB Local team released a fix, it's available as of today. 

Closing this issue.
