### ISSUE TITLE
transfer-manager not part of the bom

### ISSUE THREAD

**Issue by steven-aerts** [aws/aws-sdk-java-v2#3645]
### Describe the bug

Transfer manager [became GA](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-transfer-manager-aws-sdk-java-2-x/), nice work.

In the documentation however it is stated that [it became part of the `bom`](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html#transfer-manager-prerequisites).  

But this is not the case, is it possible you missed this?

### Expected Behavior

I can create a mvn project with the transfer manager as specified in the [getting started documentation of transfer manager](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html#transfer-manager-prerequisites).

### Current Behavior

`s3-transfer-manager` is not found in `bom`.

### Reproduction Steps

Take `pom.xml` from[ transfer manager getting started guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/transfer-manager.html#transfer-manager-prerequisites).
```
$ mvn package
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] 'dependencies.dependency.version' for software.amazon.awssdk:s3-transfer-manager:jar is missing. @ line 21, column 16
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project example.org:transfer-man-not-released:0.0.1-SNAPSHOT (/tmp/mvnproj/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for software.amazon.awssdk:s3-transfer-manager:jar is missing. @ line 21, column 16
```

Other way to reproduce:
```
curl https://repo.maven.apache.org/maven2/software/amazon/awssdk/bom/2.19.0/bom-2.19.0.pom | grep transfer-
```

### Possible Solution

Add transfer manager to the `bom`.

### AWS Java SDK version used

2.19.0

### JDK version used

Corretto-17.0.4.8.1

### Operating System and version

Linux ubuntu 20.04

**Comment by yasminetalby** [comment]
Hello @steven-aerts ,

Thank you very much for reporting this issue. It seems that the `s3-transfer-manager` is in deed not present in the `bom` as mentioned in the documentation. The team is aware and will make the necessary fix.

We really appreciate you bringing this up!

Sincerely,

Yasmine

**Comment by zoewangg** [comment]
Hi @steven-aerts thanks for reporting the issue. We have released [a fix](https://github.com/aws/aws-sdk-java-v2/commit/b06d8856ea2d852b8d434a17f3a0c7f725547d55) as part of `2.19.1`. Could you try with the latest version?

**Comment by steven-aerts** [comment]
@zoewangg I confirm it is present in `2.19.1` thanks for quickly fixing this.
