### ISSUE TITLE
CloudFrontUtilities is not including the original query params correctly when signing resource url

### ISSUE THREAD

**Issue by lx223** [aws/aws-sdk-java-v2#3655]
### Describe the bug

When using the new CloudFrontUtilities class to sign resource urls, the query params of the original urls are dropped and `&` is incorrectly appended.

### Expected Behavior

Original query params should be kept like in v1 and `&` should be appended correctly.

e.g. `https://google.com?a=b` -> `https://google.com?a=b&...`

### Current Behavior

signing `https://google.com?a=b` would give `<host>&...` 

### Reproduction Steps

Try include a url with query param in tests.

### Possible Solution

Fix these lines: https://github.com/aws/aws-sdk-java-v2/blob/71bf79354ade93aff26ffadf732e0a4d28db1ef3/services/cloudfront/src/main/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilities.java#L148-L149

### AWS Java SDK version used

2.18.33

### JDK version used

11

### Operating System and version

win 11

**Comment by mikand13** [comment]
Can confirm that this is an issue.

**Comment by satamas** [comment]
It happens because `uri.getPath()` is used [here](https://github.com/aws/aws-sdk-java-v2/blob/71bf79354ade93aff26ffadf732e0a4d28db1ef3/services/cloudfront/src/main/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilities.java#L148). I suppose that it should be replaced with `request.resourceUrl()`

**Comment by debora-ito** [comment]
Thank you everyone for reaching out, we'll work on a fix.

**Comment by debora-ito** [comment]
The fix is available in SDK version `2.19.14`. Please let try it out and let us know of any other problem.
