### ISSUE TITLE
S3 Parallel Downloads

### ISSUE THREAD

**Issue by vardhanv** [aws/aws-sdk-java-v2#366]
Hi,

As per [1303](https://github.com/aws/aws-sdk-java/issues/1303) the older Java SDK used an undocumented feature to accelerate downloads. I am wondering if this has been fixed in the new v2 API's ? 

I am also struggling to browse the code base, which seems to be autogenerated, and would appreciate any guidance, so I can find the answer myself in future if required.

Best Regards
Vishnu

**Comment by dagnir** [comment]
@vardhanv This functionality is not yet present in v2. We have a tracking issue to implement a utility like `TransferManager` in v1 here: https://github.com/aws/aws-sdk-java-v2/issues/37

**Comment by abhimanyu4211** [comment]
When can we expect the v2 TransferManager to be ready?

**Comment by millems** [comment]
Tracking in #37
