### ISSUE TITLE
Presigned URL 403 with custom query parameters

### ISSUE THREAD

**Issue by pablo-iglesias** [aws/aws-sdk-java-v2#3689]
### Describe the bug

We wanted to get a presigned URL to download an S3 file, and we need to add a custom parameter to this URL for internal reasons.

In the old AWS SDK there was the [addRequestParameter](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/GeneratePresignedUrlRequest.html#addRequestParameter-java.lang.String-java.lang.String-) method of the GeneratePresignedUrlRequest class, but the modern S3 presigner object does not have an equivalent method.

We have tried the following approach (example in Kotlin)

```
val override = AwsRequestOverrideConfiguration.builder()
    .putRawQueryParameter("param", "value")
    .build()

val getObjectRequest: GetObjectRequest = GetObjectRequest.builder()
    .bucket(bucketName)
    .key(keyName)
    .overrideConfiguration(override)
    .build()

val getObjectPresignRequest: GetObjectPresignRequest = GetObjectPresignRequest.builder()
    .signatureDuration(Duration.ofMinutes(60))
    .getObjectRequest(getObjectRequest)
    .build()
```

The resulting URL includes the parameter, but will yield a 403 error, maybe due to the parameter not being computed into the signature. I think that this approach should work, if you pass to the presigner a get request that has custom query parameters they should be used for calculating the signature.

### Expected Behavior

The presigned url triggers the download

### Current Behavior

HTTP 403

### Reproduction Steps

Use the SDK as depicted in the description to generate the presigned URL

### Possible Solution

Compute raw query parameters into the signature

### AWS Java SDK version used

2.17.282

### JDK version used

17

### Operating System and version

Windows/Linux

**Comment by debora-ito** [comment]
403 as in 403 Forbidden?

I would say this is something to do with the credential used to generate the URL, does it have sufficient permission to access the object?

> if you pass to the presigner a get request that has custom query parameters they should be used for calculating the signature.

Not necessarily. A query param does not need to be a signed header for the URL to work.

How are you using the URL to make the download?
And can you show the full error you are seeing?

**Comment by pablo-iglesias** [comment]
```
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>SignatureDoesNotMatch</Code>
	<Message>The request signature we calculated does not match the signature you provided. Check your key and signing
		method.</Message>
	<RequestId>2d4bf068</RequestId>
	<HostId>c5c5587c</HostId>
	<AWSAccessKeyId>test</AWSAccessKeyId>
	<StringToSign></StringToSign>
	<SignatureProvided>a450b26d9cafab7f52b52c2c8a8be5f554f8ea8227fe78dc6971304cb0bd8a5a</SignatureProvided>
	<StringToSignBytes>
		61343530623236643963616661623766353262353263326338613862653566353534663865613832323766653738646336393731333034636230626438613561
	</StringToSignBytes>
</Error>
```

**Comment by pablo-iglesias** [comment]
My aplogies, finally I got to test in a real AWS scenario. The presigned URL with the query parameter works correctly and is tied to the signature. The problem must be related to our test environment. Hope didn't take much of your time.
