### ISSUE TITLE
Presigned CloudFront URL Generator

### ISSUE THREAD

**Issue by marekzebrowski** [aws/aws-sdk-java-v2#370]
1.11.x has `com.amazonaws.services.cloudfront.CloudFrontUrlSigner` used to generate pre-signed urls
also `com.amazonaws.services.cloudfront.CloudFrontCookieSigner` does not have a counterpart

2.x lacks this functionality

**Comment by selvakumar-invicara** [comment]
Is it solved ? Recently we migrated to Java 11 and trying to use AWS SDK 2.x. But couldn't find replacements for CloudFrontUrlSigner.

**Comment by thereisnospoon** [comment]
Hey,
What's the status of it? We use sdk V2 and we need this feature.

**Comment by debora-ito** [comment]
No updates here.

You can track the features we're currently working on and some of what we're planning to work in our backlog of public features: https://github.com/aws/aws-sdk-java-v2/projects/1

**Comment by jbauerrfid** [comment]
Found the same problem today.

A possible workaround: try to generate the signed URL yourself, instructions are on https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-creating-signed-url-custom-policy.html

I see that this is not nice, but this feature will probably a bit longer to complete, and I can't wait...

**Comment by jotamusik** [comment]
@jbauerrfid did you managed to do it by yourself?? 🤔 If you did, could you please share the solution? 
Thanks in advance and hope that this feature comes as soon as posible 🙌🏻

**Comment by reply2srij** [comment]
Another vote for this feature. Important feature to have.

**Comment by yamakz5555** [comment]
#242 
CloudFront utility has been removed.
I hope it will come back.

**Comment by nowucca** [comment]
I'm trying buiild a private content repository on top of the cloudfront signing capability.
Why is this use case so difficult to bring back?
+1 for working on this.

**Comment by xps2** [comment]
+1

**Comment by marcolorefice** [comment]
+1

**Comment by debora-ito** [comment]
Good news, everyone!

This has been released in Java SDK version `2.18.33`.

See our Blog Post that goes through the new SDK 2.x CloudFront Signed URLs and Cookies feature - https://aws.amazon.com/blogs/developer/amazon-cloudfront-signed-urls-and-cookies-are-now-supported-in-aws-sdk-for-java-2-x/

Please check it out and let us know if you have any feedback.
