### ISSUE TITLE
Restore StepFunctionBuilder API

### ISSUE THREAD

**Issue by md5** [aws/aws-sdk-java-v2#3707]
### Describe the feature

The V1 API includes the `StepFunctionBuilder` "fluent API" as introduced in [this blog post](https://aws.amazon.com/blogs/developer/stepfunctions-fluent-api/). It looks like this was originally included in the preview versions of the V2 API as well, but it was removed in 707ced821ef1c3e2bf52597bc4cfc99fd9d8e61b with the comment that it was being removed "for now".

It would be great to see this fluent API reintroduced, either as part of the SDK or as a separate package.

### Use Case

Creating and maintaining step function JSON definitions by hand is tedious and error-prone. The fluent API that exists in V1 would be great alternative to have in V2 as well.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

All

### JDK version used

Any

### Operating System and version

Any

**Comment by debora-ito** [comment]
Hi @md5 thank you for reaching out. 

We are tracking the feature here: https://github.com/aws/aws-sdk-java-v2/issues/40.

Closing this as a duplicate.
