### ISSUE TITLE
`AsyncRequestBody#fromInputStream` doesn't close the provided input stream when consumed

### ISSUE THREAD

**Issue by StephenFlavin** [aws/aws-sdk-java-v2#3709]
### Describe the bug

I would expect that the provided input stream is closed once the put request completes but in testing `InputStream#close` is never called.

### Current Behavior

When `AsyncRequestBody.fromInputStream(inputStream, contentLength, executor)` is used as an argument on `S3AsyncClient#putObject` the stream is never closed.

Not sure if this is a bug or desired behaviour but I would expect it to be closed.

### Reproduction Steps

Tested with `org.mockito.Mockito.spy`
```java
    @Test
    void inputStreamIsClosed() {
        byte[] data = {0};
        var executor = Executors.newSingleThreadExecutor();
        try (final InputStream inputStream = spy(new ByteArrayInputStream(data))) {
            assertThat(inputStream.available(), is(1));

            var s3AsyncClient = S3ClientBuilder.getS3AsyncClient(1);

            s3AsyncClient.putObject(PutObjectRequest.builder()
                                    .bucket("test_minio_bucket")
                                    .key("test_object")
                                    .contentLength((long) data.length)
                                    .build(),
                            AsyncRequestBody.fromInputStream(inputStream, (long) data.length, executor))
                    .get();

            assertThat(inputStream.available(), is(0));
            verify(inputStream).close(); // fails here
        } catch (Throwable t) {
            fail(t);
        }
    }
```

### AWS Java SDK version used

2.19.21

### JDK version used

11.0.16.1

### Operating System and version

macOS Monterey 12.6.1

**Comment by StephenFlavin** [comment]
On second thought... maybe it shouldn't closing this issue, sorry 😓

**Comment by arikogan** [comment]
@StephenFlavin why do you think it shouldn't close the InputStream? Asking as I'm implementing v2 and in v1 the InputStream is closed by the finally in [AmazonHttpClient.RequestExecutor#doExecute](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/http/AmazonHttpClient.java#L829C17-L829C49)

**Comment by StephenFlavin** [comment]
@arikogan I can't quite remember the exact reason, I think I just came to the conclusion that handling of closing resource which has been provided should be up to the developer.

Ultimately I moved away from this method and started using `AsyncRequestBody#fromByteBufferUnsafe(ByteBuffer)` and mapped bytebuffers for better performance.
