### ISSUE TITLE
Make ClientOverrideConfiguration setters/getters consistent with SdkHttpFullRequest.Builder

### ISSUE THREAD

**Issue by dagnir** [aws/aws-sdk-java-v2#371]
Make the setter and getter names consistent, e.g. setting the headers should be `headers` like in [`SdkHttpFullRequest.Builder`](https://github.com/aws/aws-sdk-java-v2/blob/f63b71b2ec89bdce6c2ab404a819a9ea4bf857d8/http-client-spi/src/main/java/software/amazon/awssdk/http/SdkHttpFullRequest.java#L44) instead of [`additionalHttpHeaders`](https://github.com/aws/aws-sdk-java-v2/blob/f63b71b2ec89bdce6c2ab404a819a9ea4bf857d8/core/src/main/java/software/amazon/awssdk/core/config/ClientOverrideConfiguration.java#L333)

**Comment by spfink** [comment]
Probably something we need to do a once over of the entire SDK before we go GA.
