### ISSUE TITLE
Presigned request does not take expectedBucketOwner into account while generating signature.

### ISSUE THREAD

**Issue by kamesh95** [aws/aws-sdk-java-v2#3715]
### Describe the bug

Presigned request does not take expectedBucketOwner into account while generating signature.

### Expected Behavior

Put object request to the presigned URL would succeed

### Current Behavior

I am generating a PUT object signed URL and I am using the expectedBucketOwner method to verify bucket ownership while writing objects. But when I try to upload objects to the generated presigned url, it throws 403 and I can see that the response from S3 says signature does not match and the x-amz-expected-bucket-owner header is empty even though I set value in the expectedBucketOwner method.

### Reproduction Steps

```
S3Presigner presigner = S3Presigner.create();
software.amazon.awssdk.services.s3.model.PutObjectRequest objectRequest = software.amazon.awssdk.services.s3.model.PutObjectRequest.builder()
    .bucket(destinationBucket)
    .key(key)
    .contentLength(contentLength)
    .expectedBucketOwner("MY_AWS_ACCOUNT_ID") // If I pass this as empty string, it works, ideally it should throw 403
    .build();

PutObjectPresignRequest presignRequest = PutObjectPresignRequest.builder()
    .signatureDuration(Duration.ofMinutes(10))
    .putObjectRequest(objectRequest)
    .build();

PresignedPutObjectRequest presignedRequest = presigner.presignPutObject(presignRequest);
return presignedRequest.url();
```
  
  
 When I try to set expectedBucketOwner as empty string, the Put request succeeds to the presigned URL which should not be the case as it needs to verify that the destination bucket is in the correct account ID.

### AWS Java SDK version used

2.0

### JDK version used

11

### Operating System and version

Java Lambda functions in AWS

**Comment by debora-ito** [comment]
How are you using the url later on?

According to this example, you need to add the expectedBucketOwner header as a request property: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-s3-presign.html#generate-presignedurl

See how ContentType is added to PutObjectRequest and also as a `Content-Type` header to the HttpURLConnection when the url is in fact used.

**Comment by kamesh95** [comment]
I am using the URL in frontend to make a PUT request directly to the presigned URL with the file object. I tried adding the `x-amz-expected-bucket-owner` header explicitly to my request and it seems to work fine now. Thanks for the quick help :) 

Code for reference:

```
await fetch(putObjectUrl, {
            method: 'PUT',
            body: file,
            headers: new Headers({
                "x-amz-expected-bucket-owner": "33622"
            })
        });
```
