### ISSUE TITLE
SWF Flow Framework Support

### ISSUE THREAD

**Issue by evanjaaahn** [aws/aws-sdk-java-v2#372]
Currently the SWF Flow framework classes (from aws-java-sdk-swf-libraries) only integrate with the 1.X SWF client. This requires workflow and activity hosts to keep around 1.X dependencies even after upgrading all other clients to 2.X.

While my understanding is aws-java-sdk-swf-libraries project is maintained by a different team, I'm filing this here in the hope that it may be integrated and updated with the 2.X effort

**Comment by kiiadi** [comment]
@evanjaaahn we'll be separately working with the owners of the AWS owned libraries that sit on top of the AWS SDK 1.0 in an effort to get them ported across. I've opened a tracking issue against the SWF repository for this: https://github.com/aws/aws-swf-flow-library/issues/16
