### ISSUE TITLE
DynamoDBEnhancedAsyncClient FlatteningSubscriber race condition causes empty response for batchGetItem

### ISSUE THREAD

**Issue by stevenshan** [aws/aws-sdk-java-v2#3734]
### Describe the bug

Using the `DynamoDBEnhancedAsyncClient` and calling `batchGetItem` (I think this is a bug in `FlatteningSubscriber` so it probably could occur in other APIs too but I've only tested it with `batchGetItem`) with a key that I know for certain exists in the table, I sometimes get no items back from the subscription (ie. `batchGetItem` says there were no items in the table with the specified key).

### Expected Behavior

The `batchGetItem` always returns the item since it is in the table and the table is never modified.

### Current Behavior

The `batchGetItem` calls `onComplete` and the future is completed without any items being returned.

### Reproduction Steps

https://gist.github.com/stevenshan/45c771a75ea0fe722f5ef5a263e2c748

### Possible Solution

I believe the issue occurs when the asynchronous call completes while `FlatteningSubscriber` is in `onCompleteNeeded`.

Specifically, in the line
```
return allItems.isEmpty() && onCompleteCalledByUpstream && !terminalCallMadeDownstream
```
if the upstream calls `onNext` and `onComplete` between `allItems.isEmpty()` and `onCompleteCalledByUpstream`, then the statement will return true and `FlatteningSubscriber` will call the downstream `onComplete`, even though `allItems` isn't empty.

This seems to be confirmed by modifying `onCompleteNeeded` to
```
final var allItemsEmpty = this.allItems.isEmpty();
try {
    Thread.sleep(1000);
} catch (InterruptedException e) {
    e.printStackTrace();
}
return allItemsEmpty && this.onCompleteCalledByUpstream && !this.terminalCallMadeDownstream;
```
and then retrying the reproduction steps, it makes it much easier to reproduce.

### Additional Information/Context

It seems that the `onComplete` method of the subscription is called without `onNext` being called.

### AWS Java SDK version used

2.19.22

### JDK version used

openjdk version "11.0.18" 2023-01-17 LTS

### Operating System and version

Amazon Linux 2

**Comment by dagnir** [comment]
Verified that this is a bug.
