### ISSUE TITLE
Add option to preopen connections in the HTTP client

### ISSUE THREAD

**Issue by mnylensc** [aws/aws-sdk-java-v2#3737]
### Describe the feature

I would like the ability to specify initial number of connections that would be opened as soon as the HTTP client instance is created:

```
NettyNioAsyncHttpClient
  .builder()
  .initialConnections(10, () -> { callback that gets called once 10 connections are opened })
  .maxConcurrency(100)
  .build()
```

### Use Case

We are seeing extremely slow performance straight after deploying our service. The problem seems to be that our DynamoDbAsyncClient instance immediately gets hammered with thousands of requests per second as there aren't any available connections yet.

Would be nice to have a way to preopen the connections before the instance gets reported as healthy, so we could start serving requests without added latency.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.17.275

### JDK version used

11.0.12

### Operating System and version

Linux

**Comment by debora-ito** [comment]
Hi @mnylensc,

We have some concerns about adding such configuration.

1. one of the premises of the connection pool management in the SDK is that the pool is lazily initialized, meaning connections are created only when requested; the whole connection lifecycle management is based on this

2. a poorly configured initial connection number can have unintentional consequences, like a large number of unused connections that need to be managed and reaped later, slowing the general application performance; and the number of unused connections can grow multiplied by the number of service clients created

One way to improve the slow initialization is to warm up the client and perform a simple API, call like DynamoDB listTables or S3 listBuckets, during the application build. The subsequent connections should be created faster.

**Comment by mnylensc** [comment]
Thanks @debora-ito, I understand if there is hesitation for adding a feature like this. I can try achieving this by concurrently calling DescribeEndpoints/ListTables on the DynamoDbAsyncClient instance inside a ThreadPoolExecutor.

Of course it's not really exact science using an approach like this, as with this approach you are trying to simulate enough concurrency so that the underlying HTTP client is forced to start multiple new connections. But I guess it will have to do.

**Comment by zoewangg** [comment]
Similar feature request: #3801

**Comment by bhoradc** [comment]
For anyone finding this issue - starting with version [2.54.0](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.54.0), the SDK provides `SdkWarmUp`, a feature that pre-initializes SDK client request paths. See the [developer guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/sdk-warmup.html) for details.
