### ISSUE TITLE
Enhanced Client doesn't return consumed capacity in all operations

### ISSUE THREAD

**Issue by Sathyvs** [aws/aws-sdk-java-v2#3744]
### Describe the feature

Enhanced Client has only Update and Put operation with Response that returns Consumer capacity, there is nothing for read or query operations, how to get the consumed capacity for every operation ?
Also is there a way to configure cloudwatch metrics and have the consumed capacity directly published to cloud watch for all the operations ?

### Use Case

This data can really help to understand where the dynamo db is not properly used and improve the performance and also make possible data model changes to effectively use the database and increase the application performance

### Proposed Solution

Every operation in the high level api has methods to return the consumed capacity units
Ability to publish the same as a metric to cloud watch automatically for every DB operation

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.19.30

### JDK version used

11

### Operating System and version

aws lambda x86_64

**Comment by debora-ito** [comment]
Hi @Sathyvs we've added to the backlog the task to return `consumedCapacity` on the high-level query and scan operations. The solution will probably be the same of putItem and updateItem, we'll introduce new methods like scanWithResponse.

Regarding publishing consumedCapacity to CloudWatch metrics, check the CloudWatchMetricPublisher javadoc to see how you can publish custom metrics -
https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/metrics/publishers/cloudwatch/CloudWatchMetricPublisher.html

**Comment by Sathyvs** [comment]
Thanks for the reply Debora, do we know when it will be available ?

**Comment by debora-ito** [comment]
We don't have a timeline to share.

**Comment by debora-ito** [comment]
Enhanced Client `GetItem` (since 2.20.146)  and `Query` (since 2.20.153) now support `ConsumedCapacity`.

Will mark this issue to auto close soon. Let us know if you have any further questions.
