### ISSUE TITLE
S3CrtAsyncClient causes 403 errors when interacting with multiple buckets in a cross-account configuration

### ISSUE THREAD

**Issue by dmurphy-ambra** [aws/aws-sdk-java-v2#3783]
### Describe the bug

Our architecture is to upload/download files from multiple S3 buckets across 10 different AWS accounts.  The target AWS accounts have a role, S3ObjectManager, that is assumed by an EC2 instance that runs in our primary AWS account.  The S3ObjectManager role in the upload/download accounts has a trust relationship back to the primary account.   Each bucket in the upload/download account has a bucket policy that allows the main AWS account to interact with it.

In our code, we we use 1 S3AsyncClient per target AWS account, so a total of 10 S3AsyncClients, and we cache these clients in memory by AWS acccount ID so that we can reuse them.  Each S3AsyncClient has a separate StsAssumeRoleCredentialsProvider that is specific to the AWS account and generates an AssumeRoleRequest to the S3ObjectManager role in the target account. 

So for each upload/download request, we:
1) Create or Get the S3AsyncClient from the cache for the target AWS account
2) Set the bucket on the request
3) Execute the request with the S3TransferManager

To be very clear, two requests that are executed in the same target AWS account may be against different buckets.

When we have a high volume of upload or download requests, we see that some of the requests succeed and some of the requests fail.  In all cases, the failure is a 403 error (see stack below).   AWS support tells us that the reason these 403 requests are generated is because the credentials for a target account "1" are being used to interact with a different target account "2".

### Expected Behavior

An S3AsyncClient with an StsAssumeRoleCredentialsProvider should be able to communicate with multiple buckets in the same target AWS account using the S3CrtAsyncClient implementation

### Current Behavior

403 errors are randomly received on some requests against target AWS accounts and buckets.  

### Reproduction Steps

see https://github.com/dicomgrid/s3crt-403-failure

### Possible Solution

We create the S3AsyncClient used by the S3TransferManager dynamically based on inbound requests to our app. This means two different requests, inbound from two different threads, may race to be the first to create the S3AsyncClient for a given AWS account. 

In the S3CrtAsyncClient or CRT HTTP client I suspect the credentials are cached, and in some cases, the wrong credentials for the wrong StsAssumeRoleCredentialProvider are used to communicate with a different AWS account.  The CrtCredentialsProviderAdapter looks to retrieve the credentials in a separate thread so there may be a race condition where the credentials for the next request aren't retrieved in time.  It seems like the CrtCredentialsProvider should block while it waits to get the latest token from the Sts, but instead some default credentials are used.

I found two workarounds:
1) Use the Netty Async Client
2) Instantiate all S3CrtAsyncClients up-front before accepting any traffic.  The downside here is we don't want to create these clients unnecessarily unless we have inbound traffic that requires we communicate with a specific AWS account.

### AWS Java SDK version used

2.20.4

### JDK version used

openjdk version "1.8.0-adoptopenjdk" (build 25.71-b00, mixed mode)

### Operating System and version

CentOS Linux release 7.7.1908

**Comment by debora-ito** [comment]
@dmurphy-ambra thank you for the detailed report. Please bear with me while I wrap my head around your use case.

Questions: 
> To be very clear, two requests that are executed in the same target AWS account may be against different buckets.

Those two buckets are in the same account?

Is it possible to enable the verbose wirelogs of the CRT client? Instructions can be found [here](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose).

The canonical request in the Trace logs will show the credentials used, and hopefully we'll be able to confirm your suspicions.

**Comment by dmurphy-ambra** [comment]
@debora-ito we captured the CRT log, and provided it to AWS via support ticket. Please reference CASE 12027012741.  They already confirmed that the reason for the 403 is the credentials for one AWS account was being used to perform an action on a different AWS account.

The two buckets are in the same account.  In parallel in very rapid succession, we have a single S3CrtAsyncClient communicating to multiple buckets within the same account.  At the same time other S3CrtAsyncClients are communicating to multiple buckets on other accounts.

**Comment by debora-ito** [comment]
@dmurphy-ambra I was finally able to reproduce the error using your repro project, but in my tests it's always the same account that fails throughout the application. When running multiple times, it's a different account that fails each time.

We'll investigate the root cause.

**Comment by zoewangg** [comment]
Hi @dmurphy-ambra we have pushed a fix in `2.20.16`. Could you try with the latest version?

**Comment by dmurphy-ambra** [comment]
@zoewangg The fix looks like it works in my test case, which is great news. It will take longer to verify in production but I will consider this closed for now and report back if we run into any issues. Thank you!
