### ISSUE TITLE
CloudFrontUtilities doesn't encode signed url 

### ISSUE THREAD

**Issue by satamas** [aws/aws-sdk-java-v2#3791]
### Describe the bug

`getSignedUrlWithCannedPolicy` decodes symbols in provided URL  and as result produces incorrect output

### Expected Behavior

`getSignedUrlWithCannedPolicy` produces encoded URL

### Current Behavior

`getSignedUrlWithCannedPolicy` produces decoded url

### Reproduction Steps

Call the method with `resourcePath=https://domain/path/to/%40blob?v=1n1dm%2F01n1dm0`

### Possible Solution

Use getRawQuery and getRawPath here https://github.com/aws/aws-sdk-java-v2/blob/master/services/cloudfront/src/main/java/software/amazon/awssdk/services/cloudfront/CloudFrontUtilities.java#L148

### AWS Java SDK version used

2.19.14

### JDK version used

17.0.5

### Operating System and version

Windows 11 Pro

**Comment by debora-ito** [comment]
@satamas Thank you for reaching out, a fix is in the works.
