### ISSUE TITLE
New ContentType is not set on S3 object copy

### ISSUE THREAD

**Issue by CiprianTudorMihalache-endava** [aws/aws-sdk-java-v2#3792]
### Describe the bug

We have one S3 object that has content type `application/octet-stream`. We need to copy it in a different location, and also update its content type to `application/pdf`. This is not possible. The code we used is the following:

    public void copy(final String sourceBucket, final String sourcekey, final String targetBucket, final String targetKey) {

        final var copyObjectRequest = CopyObjectRequest.builder()
                .sourceBucket(sourceBucket)
                .sourceKey(sourcekey)
                .destinationBucket(targetBucket)
                .destinationKey(targetKey)
                .contentType("application/pdf")
                .build();

        // Prints: copyObjectRequest=CopyObjectRequest(ContentType=application/pdf, DestinationBucket=...
        log.info("copyObjectRequest={}", copyObjectRequest);

        // Prints: Content type of initial s3 object: application/octet-stream
        log.info("Content type of initial s3 object: {}", extractContentType(sourceBucket, sourcekey));

        s3Client.copyObject(copyObjectRequest);

        // Prints: Content type of new s3 object: application/octet-stream
        log.info("Content type of new s3 object: {}", extractContentType(targetBucket, targetKey));
    }

    private String extractContentType(final String s3Bucket, final String s3key) {
        final var objectRequest = HeadObjectRequest.builder()
                .key(s3key)
                .bucket(s3Bucket)
                .build();

        final var objectHead = s3Client.headObject(objectRequest);
        return objectHead.contentType();
    }

### Expected Behavior

The content type of the new S3 object to be the value we set in `CopyObjectRequest` (`application/pdf` in our case)

### Current Behavior

The content type of the new S3 object is the value of the source S3 object (`application/octet-stream` in our case)

### Reproduction Steps

The above code. `S3Client` is created like this: `S3Client.builder().credentialsProvider(DefaultCredentialsProvider.create()).build();`
We tried to use `S3TransferManager` instead but the behavior is the same.

### AWS Java SDK version used

2.20.10

### JDK version used

15.0.2

### Operating System and version

Windows 10 Enterprise, OS build 19044.2486

**Comment by debora-ito** [comment]
According to the CopyObject API Reference [docs](https://docs.aws.amazon.com/AmazonS3/latest/API/API_CopyObject.html), in the section about Metadata - 
> To specify whether you want the object metadata copied from the source object or replaced with metadata provided in the request, you can optionally add the x-amz-metadata-directive header ...

> - x-amz-metadata-directive
Specifies whether the metadata is copied from the source object or replaced with metadata provided in the request.
> Valid Values: COPY | REPLACE

Providing `metadataDirective` to the CopyObjectRequest should work.

```
    CopyObjectRequest.builder()
            .sourceBucket(sourceBucket)
            .sourceKey(sourceKey)
            .destinationBucket(targetBucket)
            .destinationKey(targetKey)
            .contentType("application/pdf")
            .metadataDirective(MetadataDirective.REPLACE)
            .build();
```

**Comment by CiprianTudorMihalache-endava** [comment]
Thank you very much for this info, Debora. I was not aware that we need to call 2 different methods in order to achieve the desired functionality. Maybe you can improve the library by having warning messages in case we set things that are not used, or you can redesign the methods in order to be clear the behavior: `.setNewMetadata(<new object that has setter for content type and other properties>)`
