### ISSUE TITLE
Dependency convergence issue not fixed

### ISSUE THREAD

**Issue by Venorcis** [aws/aws-sdk-java-v2#3810]
### Describe the bug

The issue as originally described in https://github.com/aws/aws-sdk-java-v2/issues/3787 was unfortunately not fixed in release `2.20.14` (or later).

### Expected Behavior

Dependency convergence error for `commons-codec:commons-codec` to be resolved.

### Current Behavior

Dependency convergence error for `commons-codec:commons-codec` remains present.

### Reproduction Steps

Add a dependency on `software.amazon.awssdk:s3:jar:2.20.17` and do a `mvn install` including the `maven-enforcer-plugin` with `<dependencyConvergence />` set.

### Additional Information/Context

Latest error output:
```
Dependency convergence error for commons-codec:commons-codec:jar:1.11 paths to dependency are:
+-<my-project>:jar:2.0.0-SNAPSHOT
  +-software.amazon.awssdk:s3:jar:2.20.17:compile
    +-software.amazon.awssdk:apache-client:jar:2.20.17:runtime
      +-org.apache.httpcomponents:httpclient:jar:4.5.14:runtime
        +-commons-codec:commons-codec:jar:1.11:runtime
and
+-<my-project>:jar:2.0.0-SNAPSHOT
  +-software.amazon.awssdk:s3:jar:2.20.17:compile
    +-software.amazon.awssdk:apache-client:jar:2.20.17:runtime
      +-commons-codec:commons-codec:jar:1.15:runtime
```

### AWS Java SDK version used

2.20.17

### JDK version used

openjdk 17.0.6

### Operating System and version

ubuntu 22.04.2

**Comment by debora-ito** [comment]
We'll take look on how to improve our dependency convergence experience. Currently we don't use the enforcer plugin in our build process, but we'll consider adding it.

**Comment by Venorcis** [comment]
> We'll take look on how to improve our dependency convergence experience. Currently we don't use the enforcer plugin in our build process, but we'll consider adding it.

Thank you!

> Changing to feature request, as this is an improvement more than a bug.

As my organization does enforce this, for us it is a blocker for updating beyond 2.20.7.

**Comment by Venorcis** [comment]
Version `2.20.44` seems to work again (i.e. without dependency convergence issues); from the changelog I cannot really see which version fixed this (I didn't try every single one), but I'll close this issue in any case 😄
