### ISSUE TITLE
attribute_not_exists(path) function does not work when used in PutItemEnhancedRequest

### ISSUE THREAD

**Issue by Ram-Raghu** [aws/aws-sdk-java-v2#3816]
### Describe the bug

I am using aws sdk 2.20.15 and DynamoDbEnhancedClient to call putitem with 'PutItemEnhancedRequest'. My code looks as below. the attribute 'lifecycle_id' is the partition key and status#epoch as sort key in the ddb table. The ddb table I am using already has a record with lifecycle_id = "2345690". I am trying to add another record with same lifecycle_id value via below "PutItemEnhancedRequest" code and it goes through everytime without an exception adding duplicate rows.

**_AWS CLI command used:_**
`aws dynamodb put-item --table-name fincrime-2waysms-ddb-alert-message-inserts-only-poc2 --item '{\"lifecycle_id\":{\"S\":\"2345690\"}, \"status_and_created_datetime_utc\":{\"S\":\"NEW#1678174091550\"}}' --condition-expression "attribute_not_exists(lifecycle_id)"`

An error occurred (ConditionalCheckFailedException) when calling the PutItem operation: The conditional request failed

However, when I do the same via aws cli, it fails with error. "An error occurred (ConditionalCheckFailedException) when calling the PutItem operation: The conditional request failed"

This looks like a bug in java sdk to me.

**_inside Calling method:_**
`alertMessageDynamoDbTable.putItem(ensureLifecycleIdNotExistsAlready(alertMessageItem));`

```
private static PutItemEnhancedRequest<AlertMessage> ensureLifecycleIdNotExistsAlready(AlertMessage alertMessageItem) {
       
 Expression itemExistsExpression = Expression.builder()
                .expression("attribute_not_exists(lifecycle_id)")
                .build();

        return PutItemEnhancedRequest.builder(AlertMessage.class)
                .item(alertMessageItem)
                .conditionExpression(itemExistsExpression)
                .build();
    }
```

### Expected Behavior

ConditionalCheckFailedException must be thrown while trying to put item via PutItemEnhancedRequest that uses "attribute_not_exists" on the partitionkey.

### Current Behavior

attribute_not_exists(<partitionkey attribute name>) used in PutItemEnhancedRequest does not fail the putitem though a record with same partitionkey exists. However, when the same conditional expression when executed via aws cli, fails each time with error "(ConditionalCheckFailedException) when calling the PutItem operation:"

### Reproduction Steps

1. create a ddb table with a string partition key and a sort key that combines a status string and an epoch with hash as the seperator. For example: partition_key(lifecycle_id) = 2345690, sortkey(status_ = NEW#1678174091550
2. Use DynamoDbEnhancedClient and putItem(PutItemEnhancedRequest<T> request) to put an item with following conditional expression "attribute_not_exists(lifecycle_id)"
3. Check "ConditionCheckFailedException' is thrown when a record with lifecycle_id = 2345690 already exists.

### AWS Java SDK version used

2.20.15

### JDK version used

11

### Operating System and version

linux

**Comment by debora-ito** [comment]
> Current Behavior
attribute_not_exists() used in PutItemEnhancedRequest does not fail the putitem though a record with same partitionkey exists

@Ram-Raghu  I can't reproduce the error. Using the Java SDK, it throws a ConditionalCheckFailedException error in the conditions you described:

```
2023-03-13 15:11:27 [main] DEBUG software.amazon.awssdk.request:85 - Received failed response: 400, Request ID: xxx, Extended Request ID: not available

software.amazon.awssdk.services.dynamodb.model.ConditionalCheckFailedException: The conditional request failed (Service: DynamoDb, Status Code: 400, Request ID: xxx)

	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleErrorResponse(CombinedResponseHandler.java:125)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handleResponse(CombinedResponseHandler.java:82)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:60)
	at software.amazon.awssdk.core.internal.http.CombinedResponseHandler.handle(CombinedResponseHandler.java:41)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:40)
	at software.amazon.awssdk.core.internal.http.pipeline.stages.HandleResponseStage.execute(HandleResponseStage.java:30)

...
```

Note that "lifecycle_id" in `attribute_not_exists(lifecycle_id)` must match the name of the DynamoDB record - for example, if you're using the `@DynamoDBAttribute` annotation, the attribute name must be the one mapped in attributeName.


> how one can insert a record(put item) that has same hash value and sort value begins with a substring??

I don't quite understand the question, can you give an example?

**Comment by Ram-Raghu** [comment]
Thanks @debora-ito for looking into this.

Basically, I wonder if there is something like below I can do.

1. before putItem (adding an item into the dynamodb table), through PutItemEnhancedRequest that a record that has the same partition key and a sort key that begins with a substring say "NEW". Sort key of my table would look like: NEW#1678174091550. Sort key of my table is a concatenation of "AlertStatus" and "Epoch" with "#" as delimiter.

Is there any such capability to check for this condition and add item only if the condition evaluates to true?

**Comment by debora-ito** [comment]
You can store "AlertStatus" and "Epoch" in their own class and write a custom AttributeConverter to convert to and from a String attribute.

Check the Overview for more information - https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced#provide-custom-attribute-converter-providers

As examples, check the implementation of the AttributeConverters provided by default in the Enhanced Client - 
https://github.com/aws/aws-sdk-java-v2/tree/master/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute
