### ISSUE TITLE
Add support for forcePathStyle to S3CrtAsyncClientBuilder

### ISSUE THREAD

**Issue by almogtavor** [aws/aws-sdk-java-v2#3817]
### Describe the bug

As said in https://github.com/aws/aws-sdk-java-v2/issues/3813, I also agree that the `S3CrtAsyncClientBuilder` is missing a lot of functions available for `S3AsyncClientBuilder`. But for me, the case causes a pretty large bug, since I cannot connect to the implementation of the S3 I use (Ceph), while I could do that with the `S3AsyncClientBuilder` using `forcePathStyle`.

### Expected Behavior

I'd expect the AWS CRT SDK to be able to connect to the S3 implementation I use as usual, but in practice, it fails to do so and I get the error of: `software.amazon.awssdk.core.exception.SdkClientException: software.amazon.awssdk.crt.s3.CrtS3RuntimeException: Host name was invalid for dns resolution`. Enabling the `forcePathStyle` option would probably make this work.

### Current Behavior

I cannot migrate to the CRT implementation even though I really want to since I need the multipart uploading logic and I don't want to implement this all by myself just because I'm not able to connect to S3 using the crt client.

### Reproduction Steps

Cannot be provided since this error getting thrown only when I connect to the S3 implementation of Ceph.

### Possible Solution

Adding the `forcePathStyle`

### AWS Java SDK version used

2.20.17

### JDK version used

17.0.2

### Operating System and version

Windows 10

**Comment by debora-ito** [comment]
@almogtavor thank you for reaching out, this is in our backlog. 

Changing to a feature request, because it's a feature that is missing.

**Comment by debora-ito** [comment]
We don't have a public backlog unfortunately.

**Comment by almogtavor** [comment]
@debora-ito Thanks. Isn't there a workaround for now, until the implementation be ready? We cannot use the crt client at all right now...

**Comment by akolacca** [comment]
@zoewangg Any progress here? I really need this

**Comment by akolacca** [comment]
@debora-ito yes. and I cannot **at all** while using the crt client. Its not like a feature request, the whole crt client is not usable to me. For me to use the crt client I **have** to wait for this feature. No workarounds. Right now I implement the range fetching and the multipart upload myself and I got bugs, so I would really love to see this one gets implemented

**Comment by akolacca** [comment]
@debora-ito yes. and I cannot at all while using the crt client. Its not like a feature request, the whole crt client is not usable to me. For me to use the crt client I have to wait for this feature. No workarounds. Right now I implement the range fetching and the multipart upload myself and I got bugs, so I would really love to see this one gets implemented

**Comment by akolacca** [comment]
@debora-ito So this is by far the most important feature I ever needed and that I will ever need from this SDK

**Comment by akolacca** [comment]
@debora-ito @zoewangg I think this is pretty related to the PR of https://github.com/aws/aws-sdk-java-v2/pull/3824. Do you think it will be hard to implement or will this probably can get released at the next couple of weeks?

**Comment by fatih-celonis** [comment]
It's also important for us to use the SDK for local development as we're using Minio for both local development and integration test with testcontainers.

**Comment by akolacca** [comment]
@zoewangg @debora-ito Sorry for all of the interruptions, but we cannot really progress at using the `aws-sdk-java-v2` since I cannot connect at all to my S3.

**Comment by zoewangg** [comment]
Hi @akolacca, apologies for the delayed response. While we can't share a date, we have prioritized this task and are planning to work on this soon, in the next couple of weeks, if not earlier. Thank you for your patience. As a workaround, can you try with the standard Java s3 client? `S3AsyncClient.builder().build();`

**Comment by akolacca** [comment]
@akolacca Hi. I'm already using it, but I need to implement the fetch ranges logic and the multipart upload myself (pretty complicated. hard error handling and edge cases) because the `S3AsyncClient.builder().build();` won't do it automatically.

**Comment by okrische** [comment]
Same here. pathStyleAccess needs to be implemented. Otherwise we can not test anything against our s3 test container. 

Beside that, the TransferManager wants us to use the crtBuilder, as it otherwise lacks important features, like the automatic multipart handling, which saves us a lot of code:

> The provided DefaultS3AsyncClient is not an instance of S3CrtAsyncClient, and thus multipart upload/download feature is not enabled and resumable file upload is not supported. To benefit from maximum throughput, consider using S3AsyncClient.crtBuilder().build() instead

**Comment by akolacca** [comment]
@okrische Couldn't agree more. @debora-ito @zoewangg @davidh44 what do you think? I would really love to see this happen

**Comment by zoewangg** [comment]
This is the PR to support this: https://github.com/aws/aws-sdk-java-v2/issues/3817

**Comment by fatih-celonis** [comment]
Hey @zoewangg It is released as of 2.20.42 according to the changelog, right?

**Comment by zoewangg** [comment]
Yes, correct, please try with the latest version (`2.20.42` as of now).

Closing the issue, feel free to open a new issue if you have further questions.

**Comment by alicianewhagen** [comment]
> Yes, correct, please try with the latest version (`2.20.42` as of now).
> 
> Closing the issue, feel free to open a new issue if you have further questions.

I pulled the new jar 2.20.42 on Monday April 10 and the .forcePathStyle(true) now exists and it works. I can read, but I can't write with the S3TransferManager which uses the crt.Builder as the client even though it writes fine just using the client. The trace log says access denied, but the client itself has no problems, while would the s3transferManager have problems
