### ISSUE TITLE
Server crashes with 502 when executing putObject s3 function - memory leak - IdleConnectionReaper

### ISSUE THREAD

**Issue by andresaaap** [aws/aws-sdk-java-v2#3819]
### Describe the bug

I have a webapp based on JSF 2.2 that is running in AWS on the service Elastic Beanstalk Apache Tomcat/8.5.79 java-1.8.0-amazon-corretto 64bit Amazon Linux 2/4.2.17. The server crashes with 502 when executing putObject s3 function. I think that it could be an error related to a memory leak or the awssdk IdleConnectionReaper.

### Environment
- Cloud service: AWS
- Platform: Elastic Beanstalk Apache Tomcat/8.5.79 java-1.8.0-amazon-corretto 64bit Amazon Linux 2/4.2.17
- Browser (version): Safari Version 16.2
- Device (brand, operating system, version): iMac MacOS 13.1

### Expected Behavior

executing putObject s3 function should upload the image to an AWS S3 bucket

### Error messages

warning 1
> 023-03-06 20:33:12,635  WARN ApacheUtils:105 - NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information

warning 2
> 06-Mar-2023 20:33:17.173 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] is still processing a request that has yet to finish. This is very likely to create a memory leak. You can control the time allowed for requests to finish by using the unloadDelay attribute of the standard Context implementation. Stack trace of request processing thread:[
 java.lang.Object.wait(Native Method)
 java.lang.Thread.join(Thread.java:1257)
 java.lang.Thread.join(Thread.java:1331)
 java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
 java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
 java.lang.Shutdown.runHooks(Shutdown.java:123)
 java.lang.Shutdown.sequence(Shutdown.java:170)
 java.lang.Shutdown.exit(Shutdown.java:216)
 java.lang.Runtime.exit(Runtime.java:109)
 java.lang.System.exit(System.java:973)
 co.com.lookmed.web.bean.prof.PerfilProfesionalBean.putS3Object(PerfilProfesionalBean.java:1612)
 co.com.lookmed.web.bean.prof.PerfilProfesionalBean.uploadPhoto3(PerfilProfesionalBean.java:1552)

warning 3
> 06-Mar-2023 20:33:17.174 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ROOT] appears to have started a thread named [idle-connection-reaper] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Thread.sleep(Native Method)
 software.amazon.awssdk.http.apache.internal.conn.IdleConnectionReaper$ReaperTask.run(IdleConnectionReaper.java:150)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:750)

severe 4
> 06-Mar-2023 20:33:17.175 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ROOT] created a ThreadLocal with key of type [com.sun.faces.application.ApplicationAssociate$1] (value [com.sun.faces.application.ApplicationAssociate$1@637041]) and a value of type [com.sun.faces.application.ApplicationAssociate] (value [com.sun.faces.application.ApplicationAssociate@267fe9a0]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

### Reproduction Steps

1. I execute the function **uploadPhoto3** from my code which executes the function **putS3Object** that executes the **awssdk s3 function putObject**. I show the code below

2. The web app crashes

### Code

```
public void uploadPhoto3() {

        String fileName = "fotoprfo" + profesional.getIdProfesional() + ".png";

        try {

            byte[] bytes = null;
            fotoContentsb64 = fotoContentsb64.substring(fotoContentsb64.indexOf(",") + 1);
            if (Base64.isBase64(fotoContentsb64)) {                
                String rutaFoto = FileUploadutil.getPhotoRealPath();
                
                String previousNombreFoto = profesional.getNombreFoto();
       
                String nombreFotoUsuario = generateNombreFoto(profesional.getNombreFoto(), userSessionBean.getUserData().getIdUsuario());

                String bucketName = "s3-buck";
                String objectKey = nombreFotoUsuario;

                System.out.println("Start s3 process");
                Region region = Region.US_EAST_2;
                S3Client s3 = S3Client.builder()
                        .region(region)
                        .build();

                String result = putS3Object(s3, bucketName, objectKey);
                System.out.println("Tag information: "+result);
                
                if(previousNombreFoto != null){
                    if(!previousNombreFoto.equals("")){
                        String objectKeyDelete = previousNombreFoto;
                        DeleteObjectRequest deleteObjectRequest = DeleteObjectRequest.builder()
                        .bucket(bucketName)
                        .key(objectKeyDelete)
                        .build();

                        s3.deleteObject(deleteObjectRequest);
                    }
                }

                s3.close();
               
                profesional.setNombreFoto(nombreFotoUsuario);
                getProfesionalFacade().update(profesional);
                topProfesionalBean.setRecargarProfesionales(Boolean.TRUE);                
            }

        } catch (Exception ex) {
            LOGGER.error("Error en la actualizacion de informacion", ex);
            JsfUtil.addSystemErrorMessage();
        }

    }
    
    public String putS3Object(S3Client s3, String bucketName, String objectKey) {

        try {
            
           byte[] bytes = null;
            fotoContentsb64 = fotoContentsb64.substring(fotoContentsb64.indexOf(",") + 1);
            if (Base64.isBase64(fotoContentsb64)) {

                bytes = Base64.decodeBase64(fotoContentsb64);
            }
           // Define the metadata
            Map<String, String> metadata = new HashMap<>();
            metadata.put("author", "Mary Doe");
            metadata.put("version", "1.0.0.0");

            PutObjectRequest putOb = PutObjectRequest.builder()
                    .bucket(bucketName)
                    .key(objectKey)
                    .metadata(metadata)
                    .build();
            
            PutObjectResponse response = s3.putObject(putOb, RequestBody.fromBytes(bytes));
            LOGGER.info("putObject");

            return response.eTag();

        } catch (S3Exception e) {
            System.err.println(e.getMessage());
            System.exit(1);
        }
        return "";
    }
```

### AWS Java SDK version used

2.15.15

### JDK version used

Corretto 8 (java-1.8.0-amazon-corretto)

### Operating System and version

64bit Amazon Linux 2/4.2.17

**Comment by debora-ito** [comment]
@andresaaap There's not a lot in the stacktraces that indicate the error was triggered by the SDK, besides `IdleConnectionReaper` being mentioned in one of the warnings.

Usually, memory leaks are experienced when a new S3 client is created for every request, or not properly closing the client after it's no longer needed. We recommend to reuse the same instance of the client among the requests. This and other best practices are listed in the Developer Guide, please take a look: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/best-practices.html

> warning 1
>
> 023-03-06 20:33:12,635 WARN ApacheUtils:105 - NoSuchMethodException was thrown when disabling normalizeUri. This indicates you are using an old version (< 4.5.8) of Apache http client. It is recommended to use http client version >= 4.5.9 to avoid the breaking change introduced in apache client 4.5.7 and the latency in exception handling. See https://github.com/aws/aws-sdk-java/issues/1919 for more information

Warning 1 is saying that the `org.apache.httpcomponents:httpclient` dependency in your project is an old version and you should upgrade it to avoid issues with url encoding. The current version used by the Java SDK is `4.5.13`.

To investigate it further I recommend to generate a heapdump and analyze it with tools like MAT, it will give more insights on the memory leak.

**Comment by andresaaap** [comment]
Hi @debora-ito ! Thank you for your response. I will try to investigate it further by generating a heapdump and analyze it with tools like MAT.
