### ISSUE TITLE
Expose S3Object Metadata like HSA256 OR MD5 via api(With out actual downloading the whole object or InputStream)

### ISSUE THREAD

**Issue by sau3078** [aws/aws-sdk-java-v2#3820]
### Describe the bug

I am dealing with large set of objects stored inside my s3 bucket. I am scanning the buckets daily once and I want to get the object hash256 or md5 stored in the bucket with out actually downloading the file or inputstream.

The idea behind is we don't want our object moved from cold or intelligent access tier to standard or hot storage it will create a lot of cost.

### Expected Behavior

There should an api expose where we can get the metadata like hsa256 or md5 hash of the object without actually downloading it.

### Current Behavior

Right now it seems we are first required to download the whole inputstream of the object and then manually calculating the hash which is fine but in our case if we download every single time it will kick off the storage class.

### Reproduction Steps

use aws java sdk bom version above 2.

### Possible Solution

HeadObjectResponse objectMetadata = s3Client.headObject(objectRequest);

objectMetadata.checksumSHA256();
objectMetadata.eTag()

I guess we can use this but I am not sure.

### AWS Java SDK version used

2.18.25

### JDK version used

17

### Operating System and version

windows

**Comment by debora-ito** [comment]
Here's what the S3 HeadObject [documentation](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/HeadObjectResponse.html#checksumSHA256()) says about `checksumSHA256`:


> The base64-encoded, 256-bit SHA-256 digest of the object. This will only be present if it was uploaded with the object. With multipart uploads, this may not be a checksum value of the object. For more information about how checksums are calculated with multipart uploads, see [Checking object integrity](https://docs.aws.amazon.com/AmazonS3/latest/userguide/checking-object-integrity.html#large-object-checksums) in the Amazon S3 User Guide.

So `checksumSHA256` may be what you are looking for.

The "Checking object integrity" doc page referenced above also includes some helpful info about MD5 and eTag.
