### ISSUE TITLE
Missing parameter in S3AsyncClient.crtBuilder() - serviceConfiguration

### ISSUE THREAD

**Issue by akolacca** [aws/aws-sdk-java-v2#3821]
### Describe the feature

I need the `serviceConfiguration` parameter that exists in `S3AsyncClient.builder()` since this parameter enabled me to connect to S3, and without it I cannot configure many important S3 configurations. The parameters I needed were `checksumValidationEnabled(false)` and `pathStyleAccessEnabled(true)`.

### Use Case

I need to connect to S3 and I cannot use the CRT client for this. Because of this I need to implement S3 multi part uploading and routes splitting all by myself, which is pretty hard and redundant. I would **really** love to get the support for the `serviceConfiguration`. This is by far the most needed feature to me, since without it I cannot even connect.

### Proposed Solution

Support `serviceConfiguration` from the `S3AsyncClient.crtBuilder()`.

### AWS Java SDK version used

2.20.16

### JDK version used

17

### Operating System and version

Linux

**Comment by akolacca** [comment]
Currently my S3AsyncClient gets stuck when I download large files from S3. I would like to use the CRT client because I think the [byte-range fetches](https://docs.aws.amazon.com/whitepapers/latest/s3-optimizing-performance-best-practices/use-byte-range-fetches.html) would solve this to me

**Comment by zoewangg** [comment]
Hi @akolacca, forcePathStyle support is tracked in #3817. `checksumValidationEnabled` config is available in `S3CrtAsyncClientBuilder` https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/main/java/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.java#L139

**Comment by akolacca** [comment]
Regarding the checksum - thanks alot! Regarding the `forcePathStyle` - that's not what I meant. I meant:
```java
S3Configuration serviceConfiguration = S3Configuration.builder()
    .pathStyleAccessEnabled(true)
    .build();
```
But I see it has similar effect (am I right?) so I'm good with `forcePathStyle`.
Any timeline estimates?

**Comment by zoewangg** [comment]
Yes, it has the same effect. We don't have a timeline for that at the moment. Feel free add 👍🏼 to #3817, which will help us prioritize. I'll go ahead and close this issue for now.

**Comment by akolacca** [comment]
@zoewangg can you tell approximately when this will get implemented? The support for this is very crucial

**Comment by akolacca** [comment]
@zoewangg @debora-ito Can you update us about the progress here?

**Comment by debora-ito** [comment]
@akolacca please track the issue that is open #3817, we'll post any updates over there.
