### ISSUE TITLE
Request AWSSessionCredentialsProvider and BasicSessionCredentials

### ISSUE THREAD

**Issue by yyjyijie** [aws/aws-sdk-java-v2#3834]
### Describe the feature

AWSSessionCredentialsProvider: Interface for providing AWSSessionCredentialsProvider

BasicSessionCredentials: Simple session credentials with keys and session token.

### Use Case

In AWS SDK Java 1.x it supports [AWSSessionCredentialsProvider](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/AWSSessionCredentialsProvider.html), [BasicSessionCredentials](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/auth/BasicSessionCredentials.html) but it does not have a equivalent in AWS SDK Java 2.x [auth api guidance link](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/package-summary.html).

We implement AWSSessionCredentialsProvider and using BasicSessionCredentials in AWS SDK Java 1.x, we want to have it in java 2.x as well since we are migrating our application to AWS SDK Java 2.x.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.18.40

### JDK version used

1.8

### Operating System and version

macOS Ventura 13.2

**Comment by debora-ito** [comment]
[AwsSessionCredentials](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/AwsSessionCredentials.html) is the equivalent of v1 BasicSessionCredentials.

Java SDK v2 does not have an equivalent of v1 interface AWSSessionCredentialsProvider but all its implementing classes in v1 are implemented in v2, check the [AwsCredentialsProvider](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/auth/credentials/AwsCredentialsProvider.html) for more info.
