### ISSUE TITLE
Allow using non-default thread pool for `AsyncResponseTransformer.toFile`

### ISSUE THREAD

**Issue by mpdn** [aws/aws-sdk-java-v2#3851]
### Describe the feature

The `AsyncResponseTransformer` created via `toFile` always uses the default thread pool in [`AsynchronousChannelGroup`](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousChannelGroup.html). Instead, it should be possible to give an `ExecutorService` as an argument to select a specific thread pool.

### Use Case

I already have a thread pool dedicated to blocking IO and would like to use that one. I also generally want tight control over the threads my application is using and avoid global mutable state.

### Proposed Solution

- Add an `ExecutorService` parameter to `FileTransformerConfiguration`
- In [FileAsyncResponseTransformer.java](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/async/FileAsyncResponseTransformer.java#L82-L90), use the [`AsynchronousFileChannel.open`](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousFileChannel.html#open(java.nio.file.Path,%20java.util.Set,%20java.util.concurrent.ExecutorService,%20java.nio.file.attribute.FileAttribute...)) variant that accepts an `ExecutorService` instead and supply one if configured.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.29

### JDK version used

openjdk version "11.0.9" 2020-10-20 LTS

### Operating System and version

MacOS Ventura 13.2.1

**Comment by debora-ito** [comment]
Feature request acknowledged. PRs are welcome :)
