### ISSUE TITLE
Ignoring profile 'profile localDynamoDB' on line 23 because it was not alphanumeric with only these special characters: - / . % @ _ : +

### ISSUE THREAD

**Issue by lennykey** [aws/aws-sdk-java-v2#3858]
### Describe the bug

When loading e.g. SqsClient as a bean and not even using DynamoDB I get the following message as a warning:

```
Ignoring profile 'profile localDynamoDB' on line 23 because it was not alphanumeric with only these special characters: - / . % @ _ : +
```

### Expected Behavior

The warning should not appear

### Current Behavior

The warning is constantly appearing

### Reproduction Steps

import the library and create a bean in SpringBoot e.g. returning an Sqsclient

### AWS Java SDK version used

2.20.31

### JDK version used

17

### Operating System and version

MacOs

**Comment by debora-ito** [comment]
That warning indicates you have a profile in the aws `credentials` file called `[profile localDynamoDB]`.
Profile file names in the `credentials` file do not require the `profile` prefix, the warning is complaining about the space character.

You can: 
(1) change the profile name to `[localDynamoDB]` OR 
(2) move the `[profile localDynamoDB]` profile and all its content to the aws `config` file.
