### ISSUE TITLE
'.' in profile name

### ISSUE THREAD

**Issue by JumpyKitten** [aws/aws-sdk-java-v2#389]
Any profile name with a dot (a.k.a. fullstop) character is ignored.

## Expected Behavior
Dot is accepted by AWS CLI, SDK for Python, Ruby, etc. (and SDK Java V1 I believe) as a valid character in profile name. So should AWS SDK for Java V2.

## Current Behavior
In software/amazon/awssdk/auth/profile/internal/ProfileFileReader.java,
    private static final Pattern VALID_IDENTIFIER = Pattern.compile("^[A-Za-z0-9_\\-]*$");
Note that dot (a.k.a. fullstop) is excluded.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-7

**Comment by jpollard-cs** [comment]
the `/` character should also be supported

**Comment by jpollard-cs** [comment]
@millems this appears to break compatibility with Okta as profiles appear like so `671250123543/Retail-EC2-Admins/jane@company.com` (see https://support.okta.com/help/s/article/Integrating-the-Amazon-Web-Services-Command-Line-Interface-Using-Okta for more info)

I could open a ticket with them here https://github.com/oktadeveloper/okta-aws-cli-assume-role#configuring-aws-in-okta, but do you mind if I ask - is there a good case not to preserve backwards compatibility in this instance?

**Comment by millems** [comment]
What we have right now seems too strict, but we can't relax it all the way to what the CLI supports, because then it's too difficult to implement in other languages. We can't be fully compatible with the CLI, so we need to settle on what we *do* actually intend to support.

Your example makes a good case for /, @ and ., but it seems silly to play whack-a-mole with examples. Any proposals on what you might consider reasonable support?

**Comment by jpollard-cs** [comment]
my experience here is limited so looping in some okta devs: https://github.com/oktadeveloper/okta-aws-cli-assume-role/issues/208

**Comment by AlainODea** [comment]
@jpollard-cs `671250123543/Retail-EC2-Admins/jane@company.com` is STS role session name. AFAIK, the v2 SDK should have no problem with the named profile sessions https://github.com/oktadeveloper/okta-aws-cli-assume-role writes to ~/.aws/credentials. I haven't tried it yet, but I don't anticipate any problems.

**Comment by JumpyKitten** [comment]
Thank you for looking into this. I would be very happy with allowing the "." character since I typically named my profiles like:
[account-a.user-1]
[account-b.user-2]

An error message instead of ignoring invalid profile names would be helpful too.

**Comment by millems** [comment]
Unfortunately ignoring invalid profile names is the CLI's behavior, so that particular behavior cannot be changed without compromising compatibility.

**Comment by abrooksv** [comment]
Another complaint around '@' and '%'

**Comment by Marakai** [comment]
I was just going to submit a ticket for Jetbrains/Pycharm AWS Toolkit, when I stumbled on this. We too have Okta SSO/SAML created AWS profile names which contain '/' and '@'. Subscribing to see if there will be a solution.

**Comment by jeffalder** [comment]
+1 for '/' from Okta

**Comment by jeffalder** [comment]
I've opened #1538 . Please vote for it to get merged.

**Comment by millems** [comment]
@jeffalder Thanks for the PR on this. I know it seems minor, but it really does take the edge off getting it implemented. I'll review.

**Comment by jpollard-cs** [comment]
thanks @jeffalder
