### ISSUE TITLE
IAM Policy Builder

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#39]
The IAM policy builder includes some hacks and changes, like removing dashes from account IDs, that could be considered unintuitive.

Review the inherited state of the V1 IAM policy builder and determine which changes are necessary for V2.

(Feel free to comment on this issue with desired changes).

**Comment by millems** [comment]
This shouldn't be a high-effort migration, since there's not a lot of bells and whistles that can be added to the 1.11.x version.

**Comment by jensentanlo** [comment]
This would be helpful and preferable to importing the v1 SDK

**Comment by leifbennett** [comment]
I'm trying to get SNS over SQS working, and these classes would be very helpful, as the subscribe operation no longer sets the policy. I'd really prefer not to have to us the v1 SDK.

**Comment by millems** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/4185 created to add this feature

**Comment by millems** [comment]
This feature was released. Documentation in developer guide is in progress, but you can use it based on the docs here: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/policybuilder/iam/IamPolicy.html
