### ISSUE TITLE
Connecting to S3 with new force property on 2.20.42, S3TransferManager fails to write a file to s3 -Access denied, but I can do so with the client passed to the transfer object

### ISSUE THREAD

**Issue by alicianewhagen** [aws/aws-sdk-java-v2#3902]
### Describe the bug

I pulled the new jar of the S3 (awssdk v2)  2.20.42 on Monday April 10 and the .forcePathStyle(true) now exists and it works. I can read, but I can't write with the S3TransferManager which uses the crt.Builder as the client even though it writes fine just using the client. The trace log says access denied, but the client itself has no problems, while would the s3transferManager have problems.
I read about the property targetThroughputInGbps and creating too many connections on a poor network, but that is not what the Trace shows.  It reads the bytes but there is an incoming response status 403.  I don't get a 40w when I use the client to write.

### Expected Behavior

It should write the file to the S3

### Current Behavior

It says permission denied when the S3TransferManager tries to write even though I do have permissions and it writes using the client = crtBuilder passing the access and secret key but the S3TransferManager produces an access denied.
Noticed that I can read with the s3TransferManager, but not write

### Reproduction Steps

None

### Possible Solution

f

### Additional Information/Context

None

### AWS Java SDK version used

2.20.42

### JDK version used

Access denied 403

### Operating System and version

Linux 7.9.2009

**Comment by alicianewhagen** [comment]
Could it be that the property I needed so bad to connect to the s3, forcePathStyle(true) is somehow causing a denied access at write

**Comment by debora-ito** [comment]
Can you share a repro code and the full stacktrace with the error?

**Comment by alicianewhagen** [comment]
> Can you share a repro code and the full stacktrace with the error?

I am on a system I can't provide the whole full stack trace nor can I transfer it; I would have to write it manually. The trace has some of this information:
sending write message of size 8041, 
processing write requests, called for aws-socket_write
dequeued write request of size 8070, remaining to write 8070
send written size 8070
write request completed
scheduling socket_written_task for immediate execution
Bytes Writte 8041
detected more scheduled tasks with the next occurring at 0;, using timeout of 0
running scheduled task
running socket_written_task task with Running status
write of size 8070 
Running http1_connections_outgoing_stream task with Running status
Current outgoing stream is now (nil)
Outgoing  stream task stopped. waiting for chunks:0
detected more scheduled task with the next occurring at 999336377, using timeout of 999
activity on fd 99, invoking handler
closed remotely
socket is now readable
invoking read. 
read of 694
bytes read 665
sending read message of size 665
Incoming response status: 403 (forbidden)
Incoming header Date...
Request Id (a UID)
Connection close
This will be the final stream on this connections
Main header block done
Incoming body 296 bytet received
<xml version 1.0 encodingUTF-8, standalone yes, code AccessDenied Message Access Denied Resource /bucketname/uuid, Resource requestId uuid httpStatusCode 403

final byte buffer = out.getData(); // where out is some FileOuputStream
S3CrtAsyncClientBuilder builder = S3AsyncClient.crtBuilder().region(Region.US_EAST1).credentialsProvider(AwsBasicCredentials.create(accesskey, secretKey)
.targetThroughput InGbps(20.0).minimumPartSizeInBytes(8 * MB),. maxconcurrency(100),.forcePathStyle(true).

try (S3Transfermanager transferManager - S3transferManager.builder().s3Client(s3AsyncClient).build()) {
Map<String, String> metadata  = loadAttributes(attributes, md5, ..); // Loads the metadata map
PutObjectRequest putObject = PutObjectRequest.builder().bucket(bucketname).key(keyname).metadata(metadata).build();
Upload upload = transferManager.upload( ub ->putObjectRequest(putObject).addTransferListener(LoggingTransferListener.create()).requestBody(AsyncRequestBody.fromBytes(buffer)))
return Mono.just(upload.competionFuture().join().response()).doOnError(Throwable -> { log.error("......") });
}

**Comment by alicianewhagen** [comment]
If I replace the S3CrtAsyncClientBuilder s3AsyncClientBuilder = S3AsyncClient.crtBuilder() with an http client, such as, SdkAsyncHttpClient httpClient = NettyNioAsyncHttpClient.builder()  and I create the S3AsyncClient  with an S3AsyncClientBuilder s3ClientAsyncBuilder = S3AsyncClient.builder().httpClient(nettyClient)  and pass this s3Client to the S3TransferManager I am able to write to the S3 (still using the access and secret keys as I did before)  So something is different with the S3CrtAsyncClientBuilder and S3CrtAsyncClient.

We have a Unix host and we use https://xxxxx for the URI. 

Any ideas? I tried every parameter there is on the CRT client and nothing worked. Thanks again for your help.

**Comment by alicianewhagen** [comment]
Could it be that the S3AsyncClient built via the crtBuilder() call, which receives as one of the parameters,  a 'httpConfiguration' or S3CrtProxyConfiguration.Builder contains host, username, and password instead of secrets. 
When the property forcePathStyle(true) was incorporated, we were able to reach the S3 with this URI, with https://host instead of https://bucketname.host. 
But now that we try to write to the S3, the access/secret keys don't seem to work, we get Access Denied

**Comment by alicianewhagen** [comment]
I put a couple of questions under Issue #3902. If you would have the chance
to look at them and give me a reply, I would appreciate it
Thanks

**Comment by alicianewhagen** [comment]
> Can you share a repro code and the full stacktrace with the error?

I left a couple of questions, but I haven't heard from you

**Comment by debora-ito** [comment]
> Do you plan to upgrade the AWS CRT-based HTTP client version to support the S3 multipart upload API features?

Not in the near future.

In this case, since you are seeing an `403 Access Denied` response from S3, I don't think this is related to the use of the S3 CRT-based client. This looks like a permission issue.

> NOTE: If I use the s3AsyncClient instead of the S3TransferManager it works, it writes to the S3.
Mono.fromFuture(s3AsyncClient.putObject(putObject, AsyncRequestBody.fromByres(buffer)));

Do you see the same `Access Denied` error if you set path style in the s3AsyncClient?

**Comment by alicianewhagen** [comment]
You can't set the path style in the s3AsyncClient that is built with the crtBuilder() unfortunately, i.e.: S3CrtAsyncClientBuilder  builder = S3AsyncClient.crtBuilder(); No option pathStyleAccessEnabled(true) on this class or any of the parameters that you can use to build it.   The method .forcePathStyle(true) helps reaching the s3 but it does not go as far as the pathStyleAccessEnabled()

**Comment by alicianewhagen** [comment]
> > Do you plan to upgrade the AWS CRT-based HTTP client version to support the S3 multipart upload API features?
> 
> Not in the near future.
> 
> In this case, since you are seeing an `403 Access Denied` response from S3, I don't think this is related to the use of the S3 CRT-based client. This looks like a permission issue.
> 
> > NOTE: If I use the s3AsyncClient instead of the S3TransferManager it works, it writes to the S3.
> > Mono.fromFuture(s3AsyncClient.putObject(putObject, AsyncRequestBody.fromByres(buffer)));
> 
> Do you see the same `Access Denied` error if you set path style in the s3AsyncClient?

Replied last Friday. Thanks

**Comment by debora-ito** [comment]
> No option pathStyleAccessEnabled(true) on this class or any of the parameters that you can use to build it. The method .forcePathStyle(true) helps reaching the s3 but it does not go as far as the pathStyleAccessEnabled(true)

`pathStyleAccessEnabled` is a v1 configuration, `forcePathStyle` is its equivalent in v2.

Trying to summarize the issue:
- Using the S3TransferManager with S3CrtAsyncClient with forcePathStyle enabled, you can call `download` successfully but `upload` throws `403 Access Denied`
- Using the S3AsyncClient, `putObject` works fine

This still looks like a permission issue, as in the credential used does not have permission to upload to the bucket. There's nothing in the S3TransferManager that would make it work for download but not for upload.

Without any logs it's hard to troubleshoot, unfortunately. If you could reproduce the issue in a local environment with [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) enabled, we could check what is being sent in the request exactly.

Things to look for: see if the credentials used are correct (you can call STS GetCallerIdentity to check); see if the credentials have the necessary permissions; other tips here in the AWS Re:post - https://repost.aws/knowledge-center/s3-troubleshoot-403

**Comment by alicianewhagen** [comment]
Thank you for your help
