### ISSUE TITLE
SNS and EC2 SDKs (and possibly other SDKs) do not work with static access codes.

### ISSUE THREAD

**Issue by maurice85** [aws/aws-sdk-java-v2#3922]
### Describe the bug

I am reporting on the same bug that was reported more than a year ago. See https://github.com/aws/aws-sdk-java-v2/issues/2981

When I create an `SNSClient` or `EC2Client` using the access key and access secret key of an IAM user I'm unable to send any requests to AWS. The returned errors are different but both complain about invalid credentials. 
The SNS client will throw this error:

`software.amazon.awssdk.services.sns.model.SnsException: The security token included in the request is invalid. (Service: Sns, Status Code: 403, Request ID:`

and the EC2 client throws this error:

`software.amazon.awssdk.services.sns.model.EC2Exception: AWS was not able to validate the provided access credentials (Service: EC2 etc`.

It doesn't work when running the application from `localhost` and it doesn't work when running the application inside an EC2 instance either.

I have ruled out the possibility that my access credentials are invalid. I've done this by running a random EC2 and SNS command with the AWS cli that i've installed on my computer. The access keys are linked to an `IAM user` that has the `EC2FullAccess` and `SNSFullAccess` permissions.

I've also ruled out the possibility that the system time is off. I've set the windows system time zone to that of Ashburn virginia and synchronized. Then I restarted the app locally and tried running a command via the SDK again. The same error happened.

So this is clearly a bug in both the SNS java v2 SDK as well as the EC2 v2 SDK and the possibility exists that this same bug exists in many of the other AWS java v2 SDKs as well. 

Furthermore, **this bug does not exist in the version 1 variant of the SDK!**. When I'm using the `com.amazonaws.services.sns.AmazonSNSClientBuilder` from the v1 SDK to build an `AmazonSNS` instance that uses static access key credentials then i _am_ able to send requests to AWS SNS. The same goes for all the other V1 AWS SDKs that i'm still using, such as s3 and SES. But the v2 variants will throw an error.

The v2 SDKs _do_ work when i use an `InstanceProfileCredentialsProvider` instead of an `StaticCredentialsProvider` as the credentials provider. In this case the application will use the role that was assigned to the EC2 instance to make requests to SNS etc. But I can't use the InstanceProfileCredentialsProvider when i'm running the app locally.

 

### Expected Behavior

SDK's should work with static access keys as well.

### Current Behavior

They don't work. 

### Reproduction Steps

Here's the code to reproduce:

### V2 SDK code that breaks:

SNSClient

```
                SnsClient client = SnsClient.builder()
                        .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(awsAccessKey, awsSecretKey)))
                        .region(Region.of(awsRegion))
                        .build();
client.listSubscriptions(); //breaks
```

EC2Client

```
        Ec2Client client = Ec2Client.builder()
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(awsAccessKey, awsSecretKey))
                .region(Region.of(awsRegion))
                .build();
       client.describeInstances(); //breaks
```
 
### V1 SDK Code that _does_ work with StaticCredentials provider (only uses AmazonSNS as example)

```
        AmazonSNS client = AmazonSNSClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(
                        awsAccessKey, awsSecretKey))
                .withRegion(Regions.fromName(awsRegion))
                .build();

client.listSubscriptions(); //Works!
```

Please try it out yourself. You can find the maven dependency for the V1 SDKs here: https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-ec2
https://mvnrepository.com/artifact/com.amazonaws/aws-java-sdk-sns

### AWS Java SDK version used

1.12.451 and 2.20.48

### JDK version used

17.0.6

### Operating System and version

Windows 11

**Comment by martinKindall** [comment]
This works for me.

pom.xml

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.walruscode</groupId>
    <artifactId>aws-sns-list-subs</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <aws.java.sdk.version>2.20.48</aws.java.sdk.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>sns</artifactId>
            <version>${aws.java.sdk.version}</version>
        </dependency>
    </dependencies>
</project>`

Main.java

`import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
import software.amazon.awssdk.regions.Region;
import software.amazon.awssdk.services.sns.SnsClient;
import software.amazon.awssdk.services.sns.model.ListSubscriptionsResponse;

public class Main {

    public static void main(String[] args) {

        String awsAccessKey = "****";
        String awsSecretKey = "*****";
        String awsRegion = "eu-central-1";   // tried with us-east-1 and worked too

        try(SnsClient client = SnsClient.builder()
                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create(awsAccessKey, awsSecretKey)))
                .region(Region.of(awsRegion))
                .build()) {

            ListSubscriptionsResponse something = client.listSubscriptions();
            something.subscriptions().forEach(System.out::println);
        }
    }
}
`

Those credentials are from a user without console access and with an aws managed policy called **AmazonSNSReadOnlyAccess**

**Comment by debora-ito** [comment]
```
                        .region(Region.of(awsRegion))
```
@maurice85 what's the value of `awsRegion` in your code? 
Can you enable the verbose wirelogs? Please redact any sensitive information they may contain (like access keys).
Instructions on how to enable the verbose wirelogs can be found in our Developer Guide -https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose

@martinKindall thank you for trying to reproduce it. I use AwsBasicCredentials to reproduce issues all the time in my local env, so my guess is that some other configuration is causing the error.

**Comment by maurice85** [comment]
@debora-ito I'm using us-east-1 as the region. The access keys work for both EC2 and SNS when using the AWS cli to run commands and they also work when using the EC2 and SNS version 1 SDKs. But when I use the version 2.x SDKs I get errors.

**Comment by debora-ito** [comment]
> Could any of these settings be the culprit?

I'm not sure, the best way to confirm is to check the verbose wirelogs if possible.

> I'm using us-east-1 as the region.

I see, but I meant to ask for a sample code showing how the value of `awsRegion` is being ingested, to check if it's actually a valid value.

**Comment by maurice85** [comment]
I am trying to resolve this issue using AWS premium support. I've already
partly solved the problem. The problem no longer exists after adding a
passRole policy to the policy list of the instance profile role, however
when i try to make requests via the SDK using IAM user access keys the same
problem still exists. I tried adding the same passroll policy to the IAM
user's policy list but it didn't work.

The keys that i use are brand new and valid. The IAM user has the
permission EC2FullAccess and the system time is synchronized with that of
time.windows.com. I have no idea what is causing this error.

**Comment by maurice85** [comment]
@debora-ito The problem has been solved. It was caused because the wrong application property was injected as the access key. I made a mistake when copying and pasting this property. My apologies.
