### ISSUE TITLE
Javadoc incorrect for DocumentTableSchema

### ISSUE THREAD

**Issue by tkhill-AWS** [aws/aws-sdk-java-v2#3929]
### Describe the issue

The following appears in the introductory description of the [Javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/document/DocumentTableSchema.html):

>  DocumentTableSchema specifying primaryKey, sortKey and a customAttributeConverter can be created as below
> 
> ```
>  DocumentTableSchema documentTableSchema = DocumentTableSchema.builder()
>  .primaryKey("sampleHashKey", AttributeValueType.S)
>  .sortKey("sampleSortKey", AttributeValueType.S)
>  .attributeConverterProviders(customAttributeConverter, AttributeConverterProvider.defaultProvider())
>  .build();
> ```

However, if you look at the [DocumentTableSchema.Builder](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/document/DocumentTableSchema.Builder.html) documentation, the method names are different:

- addIndexPartitionKey() (not primaryKey())
- addIndexSortKeyy() (not sortKey())

The description should be fixed to use the actual method names.

### Links

[DocumentTableSchema](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/enhanced/dynamodb/document/DocumentTableSchema.html)

**Comment by debora-ito** [comment]
Acknowledged. Thank you Todd!

**Comment by anuq** [comment]
I will work on this and submit a PR later.

**Comment by debora-ito** [comment]
Fixed via https://github.com/aws/aws-sdk-java-v2/pull/4348.
