### ISSUE TITLE
NoClassDefFoundError when using S3TransferManager with non-crt client

### ISSUE THREAD

**Issue by tmccombs** [aws/aws-sdk-java-v2#3936]
### Describe the bug

I'm using the S3TransferManager without the regular, non-CRT S3AsyncClient, and therefore not including aws-crt as a dependency, but `DefaultS3TransferManager` throws a NoClassDefFoundError.

### Expected Behavior

`S3TransferManager` works without having to opt in to including the aws-crt package as a dependency.

### Current Behavior

An exception like the following is thrown when calling `s3TransferManager.uploadFile`:

```
Exception in thread "external-1" java.lang.NoClassDefFoundError: software/amazon/awssdk/crt/s3/S3MetaRequest                                                                                               
        at software.amazon.awssdk.services.s3.internal.crt.S3MetaRequestPauseObservable.<init>(S3MetaRequestPauseObservable.java:33)                                                                       
        at software.amazon.awssdk.transfer.s3.internal.DefaultS3TransferManager.uploadFile(DefaultS3TransferManager.java:205)
```

### Reproduction Steps

Create a java (or other JVM language) project that doesn't include the option `aws-crt` project as a depency but does use the s3-transfer-manager package.

Then have code something like:

```
S3AsyncClient client = S3AsyncClient.builder().build() // optionally specify more options
S3TransferManager transferManager = S3TransferManager.builder().s3Client(client).builder()
transferManager.uploadFile(uploadRequest)
```

And run the code.

### Possible Solution

Either make aws-crt a required dependency, or make it so that missing the dependency doesn't break the transfer manager.

### Additional Information/Context

Possibly related to #3179 

### AWS Java SDK version used

2.20.17

### JDK version used

11.0.19

### Operating System and version

Ubuntu 20.04

**Comment by debora-ito** [comment]
@tmccombs I see the behavior and how it can be confusing. Will discuss this with the team.

**Comment by debora-ito** [comment]
Confirmed as a bug, we'll work on a fix.

**Comment by zoewangg** [comment]
We have released a fix. Could you try with the latest version?

**Comment by tmccombs** [comment]
Looks like that fixed it. Thanks!

**Comment by zoewangg** [comment]
Thanks for confirming. Closing the issue.
