### ISSUE TITLE
DynamoDB AttributeValue should compare set equality regardless of ordering

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#3951]
### Describe the bug

The `equals` implementation for `AttributeValue` compares two `AttributeValue` instances by field equality. The datatypes `bs`, `ns`, and `ss` are defined in DynamoDB to have set semantics, but since `AttributeValue` internally uses a Java `List`, the equality comparison is sensitive to ordering.

### Expected Behavior

I expected `ss` attribute values built from `['this', 'that']` and `['that', 'this']` to compare as equal.

### Current Behavior

Set-cardinality attributes are sensitive to ordering.

### Reproduction Steps

```
var av1 = AttributeValue.builder().ss("this", "that").build();
var av2 = AttributeValue.builder().ss("that", "this").build();

assert av1.equals(av2);
```

### AWS Java SDK version used

2.20.50

### JDK version used

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)

### Operating System and version

Gentoo Linux

**Comment by debora-ito** [comment]
So actually  `AttributeValue` is a modeled type, and the arrays are defined as Lists.
We don't support set types in the model, so I don't think we'll be able to make this change.

Is your request required for testing purposes only?

**Comment by chrylis** [comment]
It's relevant in production code as well as test code. I understand the presentation of "set" types as lists may be unavoidable for the lifetime of SDKv2, but the disparity between the documentation (set semantics) and the behavior (list semantics) is a landmine.

**Comment by debora-ito** [comment]
Understood. 

I'll close this as there's no action we can take on our side, set types are not supported by the json model.
