### ISSUE TITLE
S3TransferManager.downloadDirectory tries to download sub-prefixes: Exception

### ISSUE THREAD

**Issue by charlesritchea** [aws/aws-sdk-java-v2#3961]
### Describe the bug

I'm trying to download all files for a prefix 

### Expected Behavior

listObjectsV2 should only include actual objects or downloadDirectory should be smart enough to only download actual objects

### Current Behavior

This fails with an UncheckedIOEXception because listObjectsV2 includes "folders" i.e. delimited prefixes in the list instead of just actual objects, and when TransferManager tries to download these it complains that the destination is a directory

### Reproduction Steps

```kotlin
s3TransferManager.downloadDirectory { dd ->
            dd.bucket(bucket)
                .listObjectsV2RequestTransformer { lor ->
                    lor.prefix(prefix1)
                }
                .destination(localDir.toPath())
                .build()
        }
```

### Possible Solution

A work around is to add a filter ignoring keys that end in delimiter, i.e. '/'

### AWS Java SDK version used

2.20.48

### JDK version used

openjdk 17.0.7 2023-04-18 LTS OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Operating System and version

Ubuntu 23.04

**Comment by debora-ito** [comment]
@charlesritchea I can't reproduce the UncheckedIOEXception.

Can you give an example describing a real file tree and the prefix used in listObjectsV2RequestTransformer?
