### ISSUE TITLE
S3TransferManager with CRT locks up after SIGINT

### ISSUE THREAD

**Issue by jpalmucci** [aws/aws-sdk-java-v2#3963]
### Describe the bug

We need to upload data that is still in memory using the transfer manager upon SIGINT to perform a graceful shutdown. However, the transfer manager refuses to transfer anything inside the shutdown hook if we are using the transfer manager created with a CRT S3 client (ie S3AsyncClient.crtBuilder()). It works fine with the regular client (S3AsyncClient.builder()).

Transfers work fine before the interrupt.

### Expected Behavior

I would like the same behavior as the non CRT S3 client. Allow transfers after interrupts in the shutdown hook.

### Current Behavior

There are no exceptions. It just sits there waiting for FileUpload.completionFuture to return. You actually have to kill the process because the interrupt handler never finishes.

### Reproduction Steps
```
public static void main(String[] argv) throws InterruptedException {
    // switch to this client and it works
    // S3AsyncClient client = S3AsyncClient.builder().region(Region.US_EAST_2).build();
    S3AsyncClient client = S3AsyncClient.crtBuilder().region(Region.US_EAST_2).build();
    S3TransferManager manager = S3TransferManager.builder().s3Client(client).build();
    Runtime.getRuntime()
        .addShutdownHook(
            new Thread() {
              @Override
              public void run() {
                try {
                  FileUpload upload =
                      manager.uploadFile(
                          b ->
                              b.source(Path.of("test.txt"))
                                  .putObjectRequest(
                                      p -> p.bucket("causalexample").key("test.txt")));
                  upload.completionFuture().join();
                  System.out.println("Success!");
                } catch (Exception e) {
                  System.out.println(e.getMessage());
                }
              }
            });
    Thread.sleep(100000);
    // Hit ctrl-c here to start the shutdown hook
  }
```

### AWS Java SDK version used

2.20.47

### JDK version used

11.0.18

### Operating System and version

Ubuntu 22.04 (under WSL 2)

**Comment by debora-ito** [comment]
@jpalmucci thank you for reaching out. This was reported to the CRT team already in the `aws-crt-java` repo - https://github.com/awslabs/aws-crt-java/issues/561.

Once the CRT client gets an update, we'll update it in the SDK.

Let us know if you have follow-up questions.

**Comment by vthacker** [comment]
I guess this should be marked as resolved?

I was able to use `CRT.acquireShutdownRef();` and `CRT.releaseShutdownRef();` which did the trick

**Comment by alo-id** [comment]
@vthacker 
> I guess this should be marked as resolved?
> 
> I was able to use `CRT.acquireShutdownRef();` and `CRT.releaseShutdownRef();` which did the trick
 Where did you place this code?
