### ISSUE TITLE
Make SdkPresigner a part of SdkClient hierarchy

### ISSUE THREAD

**Issue by kivan-mih** [aws/aws-sdk-java-v2#4000]
### Describe the feature

Make SdkPresigner and SdkClient a part of one class hierarchy

### Use Case

For now SdkClient and SdkPresigner are in different class hierarchy branches. It's not convenient, since you need to repeat the same code for initialization of the SdkPresigner (same methods like endpointOverride, region, credentialsProvider) without any real necessity. Also for unknown reason for SdkPresigner it's not possible to set custom Http request provider which is bad since if you  use one for S3Client and want to use the same for presigner, you don't have an API to do it. 

### Proposed Solution

The best solution to the problems mentioned in the Use Case is to place SdkClient and SdkPresigner into the same class hierarchy with common methods and approaches to configuration in some base class. I assume it will be safe to make this base class a SdkClient since presigner IS a SdkClient by essence.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.12

### JDK version used

17

### Operating System and version

Ubuntu 22

**Comment by debora-ito** [comment]
@kivan-mih we appreciate your feedback, but the SdkPresigner was designed this way. The builder methods are available for use cases that need to customize those attributes. If you want to use the default region and credentials you can simply call `S3Presigner.create()`.

> Also for unknown reason for SdkPresigner it's not possible to set custom Http request provider

If you are talking about HTTP Clients, the SdkPresigner does not use any HTTP client in its underlying code. If you want to see examples using ApacheHttpClient to execute a presigned request, you can check the section "Execute a Pre-Signed Request from Java code" at the top of the [S3Presigner](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/presigner/S3Presigner.html)  javadoc.
