### ISSUE TITLE
File handle leak when uploading a file to S3 with checksum enabled

### ISSUE THREAD

**Issue by mkostrze-vs** [aws/aws-sdk-java-v2#4001]
### Describe the bug

When uploading a file with checsum enabled (.checksumAlgorithm("SHA256")) as in code below

```
PutObjectRequest putOb = PutObjectRequest.builder()
				.bucket(bucketName)
				.key(objectKey)
				.checksumAlgorithm(ChecksumAlgorithm.SHA256)   
				.build();
```

and using RequestBody.fromFile(file) as in code below

`s3.putObject(putOb, RequestBody.fromFile(file));`

The input file handle is not properly closed by the SDK library.

Removing the .checsumAlgorithm or using RequestBody.fromInputStream(is, file.length()) fixes the problem

### Expected Behavior

The file handle should be closed in the scenario described above

### Current Behavior

The file handle is not closed, on Linux you can easily check it with 

ls -la /proc/PID/fd

after putObject method finished. You should see the handle in the list of symbolic links

### Reproduction Steps

See the code below, tried with SDK 2.20.65 (maven pom.xml also included below)

The app takes 3 params:
bucket name, object key and path to the file

After uploading it has a handle leak check routine based on /prod/PID/fd filesystem (works on linux only, uses API of java 9)

```
package com.test.s3leak;

import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

import software.amazon.awssdk.core.sync.RequestBody;
import software.amazon.awssdk.services.s3.S3Client;
import software.amazon.awssdk.services.s3.model.ChecksumAlgorithm;
import software.amazon.awssdk.services.s3.model.PutObjectRequest;

public class AppMain {

	public static void putS3Object(S3Client s3, String bucketName, String objectKey, File file)
			throws Exception {
		
		PutObjectRequest putOb = PutObjectRequest.builder()
				.bucket(bucketName)
				.key(objectKey)
				.checksumAlgorithm(ChecksumAlgorithm.SHA256)   // Comment this out to get rid of the problem, or ....
				.build();

		s3.putObject(putOb, RequestBody.fromFile(file));
		
		// ... comment out the line above and uncoment stream-based sending - the leak will disappear as well
		
//		try (InputStream is = new FileInputStream(file)) {
//			s3.putObject(putOb, RequestBody.fromInputStream(is, file.length()));
//		}
		
		System.out.println("Successfully placed " + objectKey + " into bucket " + bucketName);
	}

	public static void main(String[] args) throws Exception {
		S3Client s3 = S3Client.builder().build();
		File inputFile = new File(args[2]);
		putS3Object(s3, args[0], args[1], inputFile);
		testForLeak(inputFile);
	}

	private static void testForLeak(File inputFile) throws IOException {
		long pid = ProcessHandle.current().pid();
		System.out.println("PID = " + pid);
		File proc = new File("/proc");
		File myself = new File(proc, String.valueOf(pid));
		File fds = new File(myself, "fd");
		for (File f: fds.listFiles()) {
			if (Files.isSymbolicLink(f.toPath())) {
				Path target = Files.readSymbolicLink(f.toPath());
				//System.out.println("f = " + f + " " + target);
				if (inputFile.getAbsoluteFile().toPath().normalize().equals(target)) {
					System.out.println("f = " + f + " " + target + " LEAK!!!");
				}
			}
		}
	}

}


```

maven pom.xml:

```
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.test</groupId>
	<artifactId>s3leak</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.source>9</maven.compiler.source>
		<maven.compiler.target>9</maven.compiler.target>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>software.amazon.awssdk</groupId>
				<artifactId>bom</artifactId>
				<version>2.20.65</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>software.amazon.awssdk</groupId>
			<artifactId>s3</artifactId>
		</dependency>
	</dependencies>


	<build>
		<plugins>
			<plugin><!-- Use latest to build recent Java applications -->
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.8.1</version>
			</plugin>
		</plugins>
	</build>

</project>
```

### AWS Java SDK version used

2.20.65

### JDK version used

openjdk version "11.0.10" 2021-01-19

### Operating System and version

Linux Ubuntu 20.04.4 LTS

**Comment by martinKindall** [comment]
I could reproduce this error easily by following the steps provided, thanks for the detailed code.
Indeed the leak was produced when providing a checksum algorithm, which added extra steps to the upload pipeline, one of those steps opened a wrapped InputStream which didn't close the inner stream when close() was called.

I created a PR.

**Comment by debora-ito** [comment]
@mkostrze-vs thank you for the detailed repro case, and sorry about the delay in responding. I can repro on Mac OS using `lsof -p PID` to check for open files.

@martinKindall thank you for the PR, we'll review it.

**Comment by debora-ito** [comment]
@mkostrze-vs @martinKindall as pointed out in #4005, it looks like the issue was fixed, it's not reproducible in the latest SDK version.

Marking this to auto close soon. Let us know if you still see the issue, and in which SDK version.
