### ISSUE TITLE
DynamoDbEnhancedClient: Add StreamSpecification to CreateTableEnhancedRequest

### ISSUE THREAD

**Issue by acouvreur** [aws/aws-sdk-java-v2#4010]
### Describe the feature

The CreateTableEnhancedRequest should provide a streamSpecification method to allow the user to specify a StreamSpecification to generate the table schema.

### Use Case

Right now when using table.createTable we cannot specify any StreamSpecification.

This means that you must create the schema using CreateTableRequest instead.

Using CreateTableRequest instead. But I'm not sure what I should create to have the same behavior as the DynamoDbTable.createTable method.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.66-SNAPSHOT

### JDK version used

1.8

### Operating System and version

MacOS M1 (13.3.1)

**Comment by debora-ito** [comment]
This feature makes sense. We'll take a look at the PR you submitted. Thank you!
