### ISSUE TITLE
S3Client.getBucketNotificationConfiguration(GetBucketNotificationConfigurationRequest getBucketNotificationRequest) is throwing UnsupportedOperationException

### ISSUE THREAD

**Issue by virenshekhawat** [aws/aws-sdk-java-v2#4035]
We are trying to get bucket notification configuration from S3Client but the method **S3Client.getBucketNotificationConfiguration(GetBucketNotificationConfigurationRequest getBucketNotificationRequest)** is throwing **UnsupportedOperationException**!  
There is one more method getBucketNotificationConfiguration(Consumer<GetBucketNotificationConfigurationRequest.Builder) but we are not sure whether we can use this method as inside this method multiple casting is happening(this.getBucketNotificationConfiguration((GetBucketNotificationConfigurationRequest)((GetBucketNotificationConfigurationRequest.Builder)GetBucketNotificationConfigurationRequest.builder().applyMutation(getBucketNotificationConfigurationRequest)).build());)

We also observed that there is no method support to get NotificationConfiguration in GetBucketNotificationConfigurationResponse class(similar to **BucketNotificationConfiguration.getConfigurationByName(String)** from AWS SDK 1.X)

@spfink @debora-ito @millems 

### Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#getBucketNotificationConfiguration(software.amazon.awssdk.services.s3.model.GetBucketNotificationConfigurationRequest)

**Comment by bhoradc** [comment]
Hello @virenshekhawat,

Can you please share the code sample that is throwing the exception?

In V2, you may process the `GetBucketNotificationConfigurationResponse` object to access the notification configuration details according to your requirements. You may want to iterate over the lists of `queueConfigurations`, `topicConfigurations` or `lambdaFunctionConfigurations` objects in the response and process them as needed.

Using Consumer<GetBucketNotificationConfigurationRequest.Builder> will create an instance of the GetBucketNotificationConfigurationRequest.Builder. So, you don't have to create one manually via GetBucketNotificationConfigurationRequest.builder().

The `Consumer<GetBucketNotificationConfigurationRequest.Builder>` method in the API reference guide can be found [here](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Client.html#getBucketNotificationConfiguration(java.util.function.Consumer))

In the Consumer builder method, we can pass a lambda expression to the GetBucketNotificationConfiguration method, which accepts a `Consumer<GetBucketNotificationConfigurationRequest.Builder>`. Inside the lambda expression, we can directly call the bucket() method on the provided Builder object to set the bucket name. This approach provides a flexible way to configure the request object by allowing multiple method calls within the lambda expression.

Regards,
Chaitanya
