### ISSUE TITLE
CopyObjectRequest fails with S3CrtAsyncClient when copying cross-region

### ISSUE THREAD

**Issue by markusbaumg** [aws/aws-sdk-java-v2#4037]
### Describe the bug

Copying objects cross region does not work using `S3CrtAsyncClient` using the `CopyObjectRequest`. It works with the non-crt `S3AsyncClient.`

Using the  `S3CrtAsyncClient` copying `s3://bucket-in-eu-central-1/hello.txt` to `s3://bucket-in-eu-central-2/hello.txt `fails with` SdkClientException: Failed to retrieve metadata from the source object`

eu-central-1 and eu-central-2 are just examples, the issue is not limited to them.

### Expected Behavior

`hello.txt` is successfully copied to `s3://bucket-in-eu-central-2/hello.txt` using the CRT client.
Alternatively, an understandable Exception is thrown that S3CrtAsyncClient does not support cross-region copying.

### Current Behavior

Exception is thrown.
```
software.amazon.awssdk.core.exception.SdkClientException: Failed to retrieve metadata from the source object
...
Caused by: software.amazon.awssdk.core.exception.SdkClientException: Failed to retrieve metadata from the source object
	at software.amazon.awssdk.core.exception.SdkClientException$BuilderImpl.build(SdkClientException.java:111)
	at software.amazon.awssdk.core.exception.SdkClientException.create(SdkClientException.java:47)
	at software.amazon.awssdk.services.s3.internal.crt.CopyObjectHelper.handleException(CopyObjectHelper.java:221)
	at software.amazon.awssdk.services.s3.internal.crt.CopyObjectHelper.lambda$copyObject$1(CopyObjectHelper.java:79)
	...
	at java.base/java.lang.Thread.run(Thread.java:1589)
Caused by: software.amazon.awssdk.services.s3.model.S3Exception: null (Service: S3, Status Code: 400, Request ID: XXX, Extended Request ID: KQ4ooFRvPxw//zR8ufg++12qn+Bf1ymarXxBMAyQiMU8TKX/8R2BbFuE+xx=)
	at software.amazon.awssdk.protocols.xml.internal.unmarshall.AwsXmlPredicatedResponseHandler.handleErrorResponse(AwsXmlPredicatedResponseHandler.java:156)
```

### Reproduction Steps

Given `s3://bucket-in-eu-central-1/hello.txt`, `bucket-in-eu-central-1` and `bucket-in-eu-central-2` exists.

```
var clientEuCentral2 = S3AsyncClient.crtBuilder().region(Region.EU_CENTRAL_2).build();
var copyRequest =
        CopyObjectRequest.builder()
        // bucket in EU-CENTRAL-1
        .sourceBucket("bucket-in-eu-central-1")
        .sourceKey("hello.txt")

        // bucket in EU-CENTRAL-2
        .destinationBucket("bucket-in-eu-central-2")
        .destinationKey("hello.txt").build();

clientEuCentral2.copyObject(copyRequest).join();

--> Fails with software.amazon.awssdk.core.exception.SdkClientException: Failed to retrieve metadata from the source object
```

However using the non-CRT version works:
```
var clientEuCentral2 = S3AsyncClient.builder().region(Region.EU_CENTRAL_2).build();
var copyRequest =
        CopyObjectRequest.builder()
        // bucket in EU-CENTRAL-1
        .sourceBucket("bucket-in-eu-central-1")
        .sourceKey("hello.txt")

        // bucket in EU-CENTRAL-2
        .destinationBucket("bucket-in-eu-central-2")
        .destinationKey("hello.txt").build();

clientEuCentral2.copyObject(copyRequest).join();

--> hello.txt is successfully copied.
```

### Additional Information/Context

The `S3CrtAsyncClient` makes a failing `HEAD` request to the target region (eu-central-2), trying to get metadata for the given source key, which is actually in the region of the source bucket (eu-central-1)

```
HEAD
/hello.txt

...
host:bucket-in-eu-central-1.s3.eu-central-2.amazonaws.com
...
```

See:
software/amazon/awssdk/services/s3/internal/crt/CopyObjectHelper.java:72
that leads to an handleException on line 79.

### AWS Java SDK version used

software.amazon.awssdk.s3: 2.20.69, software.amazon.awssdk.crt.aws-crt: 0.21.17

### JDK version used

openjdk 19.0.2 2023-01-17 OpenJDK Runtime Environment (build 19.0.2+7-44) OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

### Operating System and version

Any, macOS 13.3.1

**Comment by debora-ito** [comment]
@markusbaumg we do have this request in our backlog already, reported previously here: https://github.com/aws/aws-sdk-java-v2/issues/3353. I'll close this one, please use the other issue to keep track of updates.
