### ISSUE TITLE
Nulling an enum-field creates an unreadable DynamoDB record

### ISSUE THREAD

**Issue by KarolineKarkosch** [aws/aws-sdk-java-v2#4043]
### Describe the bug

An enum-field can also be null. This works when saving the enum but fails on read, so currently if you set an enum-field to null you create a record in the database which can not be read again. 

### Expected Behavior

When an enum-field is null it can be read from the database and the value of the field will be null.

### Current Behavior

When an enum-field is null, trying to read the record from the database throws an Exception.

### Reproduction Steps

Create a DynamoDB-Database class with an enum field.

Set that field to null.

Save it and try to read it again.

### Possible Solution

https://github.com/aws/aws-sdk-java-v2/pull/4042/files

### AWS Java SDK version used

2.20.49

### JDK version used

17.0.6

### Operating System and version

Zorin OS 16.2

**Comment by debora-ito** [comment]
@KarolineKarkosch apologies for the delay.

 I can't reproduce the issue. I ran `getItem()` with a null enum field with no errors in my local tests.

Can you provide a sample code I can use to reproduce, including the table bean or the static schema?
And also the stacktrace with the exception.
