### ISSUE TITLE
ApiCallTimeoutException occurs

### ISSUE THREAD

**Issue by horaceto** [aws/aws-sdk-java-v2#4057]
### Describe the bug

We've got a Java application running on AWS ECS which sends transaction data to Firehose, S3 and SQS using AWS SDK V2 java library.

Nearly each day, during the peak load period, ApiCallTimeoutException occurs as follows:

`software.amazon.awssdk.core.exception.ApiCallTimeoutException: Client execution did not complete before the specified timeout configuration: 600000 millis`

The API Timeout on the AWS SDK objects are configured to 10 minutes. This is to rule out the possibility that timeout is caused by insufficient time given for retries by the SDK. Default settings is applied for retries.

Issue happens nearly each day. When it occurs, it 's during peak load (around 30,000 transactions within a few minutes).

Once it occurs to a transaction, it would occur to all subsequent transactions, until the JVM throws OutOfMemoryError.

Resolution at the moment is to recycle the ECS container gracefully before OutOfMemoryError occurs.

No issue occurs with the newly started-up container for the rest of the day.

Issue occurs again next day during peak volume.

This cycle has been repeated for few weeks.

Notes: 
* Issue is not necessarily caused by high transaction volume. Very occasionally, this error occurs to some other applications of similar nature even when transaction volume is low.
* When exception occurs to an AWS SDK operation, all subsequent AWS SDK operations fail with the exception. e.g. when it occurs to an AWS SQS client call, all subsequent calls to SQS client, S3 client and Firehose client fail with the same exception, regardless of the fact that they are 3 different SDK client objects

### Expected Behavior

SDK operations completed timely without throwing ApiCallTimeoutException

### Current Behavior

ApiCallTimeoutException is thrown

### Reproduction Steps

To be provided

### AWS Java SDK version used

2.10.47

### JDK version used

Amazon Corretto 11

### Operating System and version

Amazon Linux 2

**Comment by bhoradc** [comment]
Hello @horaceto,

Can you please provide a code sample for the SQS client calls which are getting timed out? 

Regards, 
Chaitanya
