### ISSUE TITLE
Facing intermittent issue while s3 copy from bucket to bucket (same account)

### ISSUE THREAD

**Issue by vasoo-dang** [aws/aws-sdk-java-v2#4098]
### Describe the bug

Hi,

We are working with a large number of files and it requires to download and upload them. We are facing issue while copying files from one bucket to another. The issue is sporadic and occurs very infrequently (20 files in 20k files). 
Below is the error:- 

**"software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Provider com.ctc.wstx.stax.WstxInputFactory not found". Error message: {}.**

We are using transfer manager with S3AyncClient with CRT builder. 

### Expected Behavior

Copying of the files should not fail

### Current Behavior

**"software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Provider com.ctc.wstx.stax.WstxInputFactory not found". Error message: {}.**

getting this error intermittently. 

The code is deployed as an image on eks pods. Only some files within a pod fail intermittently with the above issue and then the following files within the same pod are working fine. 

### Reproduction Steps

using transfer manager with s3aynclient with crt builder. 

S3AsyncClient s3AsyncClient =
                S3AsyncClient.crtBuilder()
                        .checksumValidationEnabled(false)
                        .credentialsProvider(awsCredentials())
                        .region(Region.US_WEST_2)
                        .targetThroughputInGbps(20.0)
                        .minimumPartSizeInBytes(8 * MB)
                        .build();

### AWS Java SDK version used

aws sdk version 2

### JDK version used

8

### Operating System and version

linux,alpine

**Comment by debora-ito** [comment]
Can you share the full stacktrace?

**Comment by debora-ito** [comment]
@vasoo-dang with this one single line of stacktrace we can't help you much. The error says `WstxInputFactory` was not found, and it's not from a Java SDK package. You can search for relevant solutions for the error on developer communities like stackoverflow.

Closing this for now. Feel free to reopen if you have questions about the AWS SDK.
