### ISSUE TITLE
AttributeValue does not get serialized/deserialized correctly

### ISSUE THREAD

**Issue by ndodda-amazon** [aws/aws-sdk-java-v2#4107]
### Describe the bug

I have a requirement where I need to be able to serialize a DynamoDB item to a string and then deserialize it as an item again. I do the serialization by creating a `TableSchema` object, calling `itemToMap`, and then using Gson to convert the map to a JSON string. Similarly, I do the deserialization by converting the string to a map and then calling `mapToItem` from the same table schema to get the item.

However, when the serialization occurs, the JSON string for an attribute value looks like the following:

```
"dimensions":{"ss":[],"ns":[],"bs":[],"m":{},"l":["name":{"s":"name","ss":[],"ns":[],"bs":[],"m":{},"l":[],"type":"S"}},"l":[],"type":"M"}],"type":"L"}
``` 

where this corresponds to a list of `Dimension` objects, which looks like:

```
@DynamoDbBean
data class Dimension(var name: String? = null)
```

The issue here is that other collections in the attribute value get initialized as an empty data structure, instead of not being initialized in the first place. This leads to an error during deserialization when using the `ListAttributeConverter`.

### Expected Behavior

I expected that the ListAttributeConverter can convert lists of custom objects correctly and deserialize the JSON as an object correctly.

### Current Behavior

Instead it fails with the following error: 

```
software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.ListAttributeConverter cannot convert an attribute of type M into the requested type interface java.util.List
java.lang.IllegalStateException: software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.ListAttributeConverter cannot convert an attribute of type M into the requested type interface java.util.List
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.TypeConvertingVisitor.defaultConvert(TypeConvertingVisitor.java:188)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.TypeConvertingVisitor.convertMap(TypeConvertingVisitor.java:113)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.TypeConvertingVisitor.convert(TypeConvertingVisitor.java:88)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.EnhancedAttributeValue.convert(EnhancedAttributeValue.java:428)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.ListAttributeConverter$Delegate.transformTo(ListAttributeConverter.java:156)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.ListAttributeConverter.transformTo(ListAttributeConverter.java:121)
	at software.amazon.awssdk.enhanced.dynamodb.internal.converter.attribute.ListAttributeConverter.transformTo(ListAttributeConverter.java:83)
```

This is because when the enhanced attribute value is trying to determine how to parse the attribute value ([ref](https://github.com/aws/aws-sdk-java-v2/blob/65679164e69fc3b69082698b0952b3052806e733/services-custom/dynamodb-enhanced/src/main/java/software/amazon/awssdk/enhanced/dynamodb/internal/converter/attribute/EnhancedAttributeValue.java#L386)), 

```
if (attributeValue.hasM()) {
            return EnhancedAttributeValue.fromMap(attributeValue.m());
        }
```

`hasM` returns true and it fails to parse the list as a map. `hasM` returns True, because it checks if `m` is null instead of empty.

### Reproduction Steps

1. Create an attribute value of type list
2. Serialize the attribute value using `Gson.toJson`
3. Deserialize the attribute value using `Gson.fromJson`
4. Call `EnhancedAttributeValue.fromAttributeValue` to reproduce the failure 

### Possible Solution

Two quick fixes:
1. Use a switch statement on the attribute value type instead of using the boolean functions 
2. Modify `hasM` to check if the field is an empty dictionary

Long term - I don't think it makes sense to even allow a state where an attribute value has multiple values. It probably makes more sense to throw an error if we attempt to set multiple values.

### Additional Information/Context

This may be an issue in the serialization itself (i.e. why are multiple fields written for each attribute value). If this isn't the correct way to serialize an AttributeValue as a JSON, please suggest an alternative method.

### AWS Java SDK version used

2.20.40

### JDK version used

11

### Operating System and version

MacOS Ventura 13.4

**Comment by debora-ito** [comment]
@ndodda-amazon we don't consider this a bug, it's a use case we don't support. Initializing the attributes with empty values was a design decision of the DDB Enhanced Client. Also, I don't think we can change `hasM` to check for empty values without doing a breaking change.

We do have a open feature request to support a native JSON attribute converter, feel free to add a :+1: - https://github.com/aws/aws-sdk-java-v2/issues/2162
