### ISSUE TITLE
Slash '/' is not added to the request after the bucket

### ISSUE THREAD

**Issue by skipkolch** [aws/aws-sdk-java-v2#4117]
### Describe the bug

The final http request does not include a slash after bucket.
RuleEvaluator does not add slash after bucket.
`e.g. : https://host/bucket`
As a result, S3Exception 301 Moved permanently is obtained.
However, when adding a slash, the request is processed without errors
`e.g. : https://host/bucket/`

### Expected Behavior

I expect correct processing of requests

### Current Behavior

```
lambda$evaluateRuleset$2:33, RuleEvaluator (software.amazon.awssdk.services.s3.endpoints.internal) get:-1,
RuleEvaluator$$Lambda$1015/0x0000000801717040 (software.amazon.awssdk.services.s3.endpoints.internal) inScope:55,
Scope (software.amazon.awssdk.services.s3.endpoints.internal) evaluateRuleset:25, 
RuleEvaluator (software.amazon.awssdk.services.s3.endpoints.internal) evaluate:25, 
DefaultRuleEngine (software.amazon.awssdk.services.s3.endpoints.internal) resolveEndpoint:35, 
DefaultS3EndpointProvider (software.amazon.awssdk.services.s3.endpoints.internal) modifyRequest:137,
S3ResolveEndpointInterceptor (software.amazon.awssdk.services.s3.endpoints.internal) modifyRequest:68,
ExecutionInterceptorChain (software.amazon.awssdk.core.interceptor) runInitialInterceptors:179, 
AwsExecutionContextBuilder (software.amazon.awssdk.awscore.internal) invokeInterceptorsAndCreateExecutionContext:115,
AwsExecutionContextBuilder (software.amazon.awssdk.awscore.internal) invokeInterceptorsAndCreateExecutionContext:69,
AwsSyncClientHandler (software.amazon.awssdk.awscore.client.handler) lambda$execute$1:78,
BaseSyncClientHandler (software.amazon.awssdk.core.internal.handler) get:-1,
...
```

### Reproduction Steps

```
private val client =  S3AsyncClient.builder()
            .httpClientBuilder(AwsCrtAsyncHttpClient.builder())
            .credentialsProvider(credentials)
            .endpointOverride(uri)
            .region(region)
            .forcePathStyle(true)
            .build()
            
private val objects = client.listObjects {
            it.bucket(bucket)
                .prefix(prefix)
                .applyMutation(mutation)
        }
```

### AWS Java SDK version used

2.20.12

### JDK version used

java -version 17.0

### Operating System and version

Win 10

**Comment by debora-ito** [comment]
"301 Moved permanently" usually indicates the regional s3 endpoint does not match the bucket region.

- Can you confirm the region set in the s3 client is the same as the bucket region?
- Can you provide the verbose wirelogs? Please make sure to remove any sensitive data (like access keys)
For verbose wirelogs instructions, check: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose
