### ISSUE TITLE
S3TransferManager download memory leak

### ISSUE THREAD

**Issue by daltonporter** [aws/aws-sdk-java-v2#4155]
### Describe the bug

When downloading files using transferManager.downloadFile( ), memory leaked and eventually leads to program termination.

### Expected Behavior

Program should run indefinitely with at worst a plateau in memory usage.

### Current Behavior

With each download from S3, overall memory usage increases.
I'm downloading a 30MB file.

### Reproduction Steps

    while(true) {
            S3TransferManager transferManager = S3TransferManager.create();
            DownloadFileRequest downloadFileRequest =
                    DownloadFileRequest.builder()
                            .getObjectRequest(req -> req.bucket(bucket).key(key))
                            .destination(Paths.get(outFile))
                            .build();

            FileDownload download = transferManager.downloadFile(downloadFileRequest);
            download.completionFuture().join();
            log("count="+(++counter));
            try {
                Thread.sleep(5000);
            }catch(Exception e){
                log(e.toString());
            }finally{
                transferManager.close();
                transferManager=null;
            }
    }

### AWS Java SDK version used

software.amazon.awssdk:bom:2.20.26

### JDK version used

openjdk version "17.0.7" 2023-04-18 LTS OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.7.7.1 (build 17.0.7+7-LTS, mixed mode, sharing)

### Operating System and version

NAME="Amazon Linux" VERSION="2023" ID="amzn" ID_LIKE="fedora" VERSION_ID="2023" PLATFORM_ID="platform:al2023" PRETTY_NAME="Amazon Linux 2023" ANSI_COLOR="0;33" CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023" HOME_URL="https://aws.amazon.com/linux/" BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023" SUPPORT_END="2028-03-01"

**Comment by daltonporter** [comment]
dependencies {
    implementation platform('software.amazon.awssdk:bom:2.20.26')
    implementation 'software.amazon.awssdk:s3'
    implementation 'software.amazon.awssdk:aws-crt-client'
    implementation 'software.amazon.awssdk:s3-transfer-manager'
}

**Comment by debora-ito** [comment]
Hi @daltonporter try reusing a single instance of `S3TransferManager` instead of creating a new one for each request. Every new instance of S3TransferManager creates new resources.

You can see this and other tips listed in our Best Practices page - 
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/best-practices.html

**Comment by daltonporter** [comment]
Hi @debora-ito , thank you for the tip.   While it may not be a best practice, doing this as I described still causes the issue.  From the guide:  

> If you don't want to share a client instance, **call close() on the instance to release the resources** when the client is not needed.

Even if I have a global copy of the TM, there seems to be no method to check if it's "alive".  I'm sure it may be possible for a long lived instance to die in which case we are back to calling close and creating a new instance.  Perhaps the TM should be redesigned as a singleton.  create( ) seems to keep creating new instances that are impossible to clean up with a close( ) as described in the best practices document.

**Comment by debora-ito** [comment]
Calling close() will effectively close the TransferManager when it's safe to do so. At the same time, in cases of long-lived instances, the SDK will not close clients while they are active. 

It looks like we need to do more investigation. Changing this back to bug.

How are you perceiving the memory leak? Can you provide the data/graphs/dumps?

**Comment by daltonporter** [comment]
The memory growth is visible using "top".  This will run until memory is exhausted, then it will crash.
I used a 30M file for the download.

**Comment by debora-ito** [comment]
@daltonporter we made several improvements in the CRT client core memory handling, can you test the latest version of the SDK?

The latest version also includes a new optional attribute `maxNativeMemoryLimitInBytes` that limits the memory used by the crt client.

Let us know of your findings after checking the latest version.
