### ISSUE TITLE
Modify FileAsyncRequestBody.FileSubscription to create less heap garbage

### ISSUE THREAD

**Issue by shikharid** [aws/aws-sdk-java-v2#4159]
### Describe the feature

**Concerned class**: FileAsyncRequestBody.FileSubscription

FileSubscription reads File from disk in defined chunks (16 Kb by default) and eventually things get uploaded to S3 down the line. All great, even a large file should not create a lot of memory/GC pressure on JVM.

But that's doesn't seem to be the case, the issue is impl of FileSubscription.readData()
```java

        private void readData() {
            // It's possible to have another request for data come in after we've closed the file.
            if (!inputChannel.isOpen() || done) {
                return;
            }

            ByteBuffer buffer = ByteBuffer.allocate(chunkSize);
            inputChannel.read(buffer, position.get(), buffer, new CompletionHandler<Integer, ByteBuffer>() { .....
```

I don't understand why we need to allocate a new buffer for every chunk? 
Isn't reusing a common small buffer for **entire** data transfer the primary benefit of chunked File transfers?

Doing it this way negates the memory usage benefits of File backed chunked uploads, at least until the next GC round happens. 
In our case, we have been actively trying to bring time spent in GC to as little as possible. 

### Use Case

We are using `S3AsyncClient` for a new project which handles S3 object uploads/downloads at a high concurrency.
With uploads going upto 1 Gbps and downloads upto 2-3 Gbps at times .

Most of the files are small, less than 1 MB and we expect upto 10K concurrent ul/dl's.

### Proposed Solution

Make the buffer an instance variable in FileSubscription and reuse for all transfers.

We can use the existing "**lock**" mechanism that is used to manage outstandingDemand to avoid any concurrency issues, if there are any. 

Shouldn't have concurrency issues, as `CompletionHandler.completed` being triggered implies no one is using the buffer anymore.

----- 
Another unrelated optimisation can be to use direct memory instead of heap memory for the buffer.
   Direct memory being faster for networking
   And maybe even lighter for Garbage Collector (instead of managing a 16 KB memory block from heap, it manages a 8-byte reference)

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

 2.20.51

### JDK version used

17

### Operating System and version

MacOS Ventura 13.2

**Comment by shikharid** [comment]
Any opinion on this folks? 
If possible, please let me know if/when can this be picked up and merged upstream.
If you don't see a good enough reason to do this somehow, we can maintain our own custom impl of AsyncRequestBody

**Comment by debora-ito** [comment]
> I don't understand why we need to allocate a new buffer for every chunk?

We can't reuse the same buffer because we don't know when the chunk will be read by the reader downstream.
We appreciate the feedback but are not interested in changing this at the moment.
