### ISSUE TITLE
The CHANGELOG.md file does not render

### ISSUE THREAD

**Issue by raymondchen625** [aws/aws-sdk-java-v2#4161]
### Describe the issue

The `CHANGELOG.md` doesn't render on GitHub. If I try to render it in VSCode, I get error messages like `Maximum call stack size exceeded`. This seems to be related to the size of the document. My VSCode could render it after cutting down the file size to around 15K lines. But it took quite a while to show the preview. 
Might need to break it down into multiple files to keep the changelog rendering sustainable.

### Links

https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md

**Comment by debora-ito** [comment]
Yes, it's a known issue, apologies for that.

We have in our backlog a task to break the changelog in smaller parts, it's just a matter of prioritizing it against other tasks we need to work on.

Since the changelog is auto generated, we need to figure out a way to programmatically break it in parts that make sense and are easy to use.

Feel free to comment here with suggestions of a better changelog.

**Comment by DrizzyHendrix** [comment]
bump for visibility, i'm still unable to open the changelog and I'd really like to know the changes going into the SDK...especially with the larger version changes

**Comment by millems** [comment]
@DrizzyHendrix Sorry that a lot of time is passing without this getting fixed. We're continually trying to improve our prioritization process to avoid paper cuts like this one from going so long unaddressed. You shouldn't have to resort to workarounds, but the raw, unrendered markdown for the changelog is available without the loading issues here: https://raw.githubusercontent.com/aws/aws-sdk-java-v2/master/CHANGELOG.md

**Comment by dagnir** [comment]
Hi @DrizzyHendrix I'm working on pushing an update to our release system to publish the changelog updates as [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) which will make viewing the changes for a specific version much easier; please keep an out for this update :). We will keep the text `CHANGELOG.md` file so changes can be easily searched in aggregate, but will "archive" older entries to a separate file, similar to what we have done for 1.11.x https://github.com/aws/aws-sdk-java/tree/master/changelogs

**Comment by DrizzyHendrix** [comment]
> Hi @DrizzyHendrix I'm working on pushing an update to our release system to publish the changelog updates as [GitHub releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) which will make viewing the changes for a specific version much easier; please keep an out for this update :). We will keep the text `CHANGELOG.md` file so changes can be easily searched in aggregate, but will "archive" older entries to a separate file, similar to what we have done for 1.11.x https://github.com/aws/aws-sdk-java/tree/master/changelogs

Hell yea! Thank you contributors for being responsive

**Comment by dagnir** [comment]
Hi @DrizzyHendrix, we have now archived older changelog entries to make the main `CHANGELOG.md` file easier to load/render: https://github.com/aws/aws-sdk-java-v2/blob/master/CHANGELOG.md#22318-2024-02-05. Just as in 1.x, changelogs for older versions can be found in the [`changelogs`](https://github.com/aws/aws-sdk-java-v2/blob/master/changelogs). In addition, we're also now creating GitHub releases for each version of the SDK going forward: https://github.com/aws/aws-sdk-java-v2/releases/tag/2.23.18

**Comment by raymondchen625** [comment]
Looks nice. Thank you @dagnir
