### ISSUE TITLE
BinaryUtils.immutableCopyOf(ByteBuffer) discards limit

### ISSUE THREAD

**Issue by guss77** [aws/aws-sdk-java-v2#4166]
### Describe the bug

The `BinaryUtils.immutableCopyOf(ByteBuffer)` is used to create request bodies of type `AsyncRequestBody` from a `java.nio.ByteBuffer`.

NIO `ByteBuffer`s are used as intermediate buffers for read write operations, and in addition to their capacity they have a "position" and a "limit", where "position" is used to determine where the next read or write operation will continue from, and "limit" is used to specify where the actual data in the buffer ends.

A standard set of operations to read data for preparation to for writing - using a BIO `ByteBuffer` are as follows:
- allocate the `ByteBuffer`
- `put()` data in the `ByteBuffer`, which will advance its position.
- once all data has been put into the buffer, set its "limit" to past the last data byte in the buffer.
- `rewind()` the buffer to set its position back to 0
Now the `ByteBuffer` is ready to write the contents between 0 and "limit".

The problem is that `AsyncRequestBody.fromByteBuffer(ByteBuffer)` uses `BinaryUtils.immutableCopyOf(ByteBuffer)` to create a copy of the provided `ByteBuffer` and then operates on the copy, but `BinaryUtils.immutableCopyOf(ByteBuffer)` creates a copy that discards the "limit" of the original and have its limit set to the capacity of the buffer. As a result, the body of the request to be sent will include a lot more than the data that was requested.

### Expected Behavior

Only the data that was loaded into the `ByteBuffer`, between "position" and "limit" should be used.

### Current Behavior

The copied `ByteBuffer` makes available all the data between "position" (which it does retain correctly) to "capacity".

### Reproduction Steps

Here's a small Java shell program that demonstrates the issue:

```java
byte[] data = new byte[5000];
  // => data ==> byte[5000] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,  ... , 0, 0, 0, 0, 0, 0, 0, 0 }
new java.security.SecureRandom().nextBytes(data);
java.nio.ByteBuffer buffer = java.nio.ByteBuffer.allocate(100_000);
  // => buffer ==> java.nio.HeapByteBuffer[pos=0 lim=100000 cap=100000]
buffer.put(data);
  // => $29 ==> java.nio.HeapByteBuffer[pos=5000 lim=100000 cap=100000]
buffer.rewind();
  // => $30 ==> java.nio.HeapByteBuffer[pos=0 lim=100000 cap=100000]
buffer.limit(data.length);
  // => $31 ==> java.nio.HeapByteBuffer[pos=0 lim=5000 cap=100000]
software.amazon.awssdk.utils.BinaryUtils.immutableCopyOf(buffer);
  // => $32 ==> java.nio.HeapByteBufferR[pos=0 lim=100000 cap=100000]
```

### Possible Solution

To create a proper copy of a `ByteBuffer`, `BinaryUtils.immutableCopyOf(ByteBuffer)` should also copy the limit.

### AWS Java SDK version used

2.20.93

### JDK version used

openjdk version "19.0.2" 2023-01-17

### Operating System and version

Ubuntu 22.04

**Comment by debora-ito** [comment]
@guss77 Makes sense, seems like a bug.

**Comment by geetptl** [comment]
@debora-ito Can I take this?

**Comment by guss77** [comment]
Hey guys, just wanted to ping about the status of this small issue - what's the time line for having a fix in the git for this?

If you want, I can offer a pull request for this issue.

**Comment by davidh44** [comment]
Thanks for bringing it up, fix for the bug has been merged. Closing issue
