### ISSUE TITLE
Dms 2.x API is still in preview 2.0 version , Needs an update for compatibility

### ISSUE THREAD

**Issue by letsbe-x** [aws/aws-sdk-java-v2#4179]
### Describe the feature

The aws dms API for 2.x Java SDK needs an update

### Use Case

I was utilizing `aws-sdk-java-v2` to create a monitoring integration with Flink.

I was working on the [DMS status](https://docs.aws.amazon.com/dms/latest/APIReference/API_DescribeReplicationTasks.html) article, but the following error popped up to report it.

```
java.lang.ClassNotFoundException: software.amazon.awssdk.core.runtime.transform.Unmarshaller
```

```gradle
dependencies {
...
implementation("software.amazon.awssdk:cloudwatch:2.20.94")
implementation("software.amazon.awssdk:dms:2.0.0-preview-11")
...
}
```

### Proposed Solution

The AWS Database Migration Service API for 2.x Java SDK needs an update

- [software.amazon.awssdk:dms, the latest version is 2.0.0-preview-11](https://mvnrepository.com/artifact/software.amazon.awssdk/dms) 
This version is incompatible with all the netty fixes which have been done for the more latest versions in the sdk java 2.x stack .

The version (2.0.0-preview-11) is also incompatible with the latest AWS runtime core marshallers/unmarshallers.

Kindly publish a new jar with all the netty and aws core runtime dependencies please 🙏 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.94

### JDK version used

openjdk version "17.0.5"

### Operating System and version

macOS Ventura 13.4

**Comment by debora-ito** [comment]
The module name changed from `dms` to `databasemigration` in 2.0.0-preview-12.

https://mvnrepository.com/artifact/software.amazon.awssdk/databasemigration

**Comment by letsbe-x** [comment]
Thank you for the detailed explanation. 

I will close this issue
