### ISSUE TITLE
AWS SDK Java Clients report the remote IP Address

### ISSUE THREAD

**Issue by Y-Luo** [aws/aws-sdk-java-v2#4217]
### Describe the feature

Have all AWS SDK Java Clients report the remote IP Address that they connected to for a call. Ideally add the remote ip address info to service log. 

### Use Case

After a recent event, we knew we were talking to DDB's public endpoint, but we did not know that a subset of IPs that their DNS was resolving to were having issues.  Had we had this information readily available, we would have been able to root cause it much faster.

### Proposed Solution

Right now the remote IP address only gets logged in debugging log. Maybe make it available in AwsSdkMetricsFactory or AwsSdkMetricsRequestHandler.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

AWSJavaSDKExternalRelease = 1.11.x;

### JDK version used

1.8.0_372

### Operating System and version

ec2

**Comment by debora-ito** [comment]
Hi @Y-Luo 

the Java SDK 2.x will print the IP address in the logs when the Netty client is used, under Channel Information - for example:

> software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: The connection was closed during the request. The request will usually succeed on a retry, but if it does not: consider disabling any proxies you have configured, enabling debug logging, or performing a TCP dump to identify the root cause. If this is a streaming operation, validate that data is being read or written in a timely manner. Channel Information: ChannelDiagnostics(channel=[id: 0x321f2d4c, L:/192.153.177.20:50484 - R:kinesis.us-west-2.amazonaws.com/3.123.11.183:443], channelAge=PT12.410S, requestCount=1)

I see you are using Java SDK 1.11.x - we don't have plans to support this in the Java SDK 1.x.
