### ISSUE TITLE
Mysterious "Connection Pool Closed" Error

### ISSUE THREAD

**Issue by Khongchai** [aws/aws-sdk-java-v2#4221]
### Describe the bug

Calling `putObject` with the `s3AsyncClient` from `software.amazon.awssdk.services.s3.S3AsyncClient` while using `WebIdentityTokenFileCredentialsProvider` as the credential provider will cause the "connection pool closed" error from `AwsSyncClientHandler` the STS library uses.

We were using AWS SDK version `2.20.19`. Upgrading to newer ones didn't solve our problem, but when we downgraded to `2.16.18` the problem disappeared.

When this error happens, all subsequent requests to the endpoint that uses this library will throw the same error, the only solution is to restart the microservice. I will provide the stack trace here, this stack shows the assertion error at the HTTP client level, but we don't know who closed it (still trying to reproduce it locally so we can use the debugger to help us).

<img width="671" alt="image" src="https://github.com/aws/aws-sdk-java/assets/56601823/03b4d9c0-5484-46f5-89d6-12b93e65ee49">

### Expected Behavior

The error should not be thrown. We didn't call any `close` on any HTTP client or thread pools.

### Current Behavior

Once we deploy our microservice, it will function normally, then fail within an hour -- likely after having handled a number of requests from our test team. 

### Reproduction Steps

# Initialization

```java
final var httpClient = SdkAsyncHttpClient httpClient = NettyNioAsyncHttpClient.builder()
                .connectionTimeout(Duration.ofMillis(60000)
                .writeTimeout(Duration.ofMillis(60000)
                .readTimeout(Duration.ofMillis(60000)
                .maxConcurrency(8)
                .maxPendingConnectionAcquires(10000)
                .build();
final var credentialsProvider =  WebIdentityTokenFileCredentialsProvider.builder()
                    .roleArn(assumeRoleARN)
                    .webIdentityTokenFile(Path.of(tokenPath))
                    .build();
S3AsyncClientBuilder s3AsyncClientBuilder = S3AsyncClient.builder()
                .httpClient(httpClient)
                .region("ap-southeast-1")
                .credentialsProvider(credentialsProvider)
                .serviceConfiguration(serviceConfiguration)  // S3Configuration instance
                .build();

this. asyncClient = s3AsyncClientBuilder.build(); 
```

# Calling `putObject`

```java
asyncClient 
                .putObject(
                        PutObjectRequest.builder()
                                .bucket(...)
                                .contentLength(...)
                                .contentType(...)
                                .metadata(...)
                                .key(...)
                                .build(),
                        fileByte
                );
```

Calling putObject with this setup code a few times...or sporadically for an hour and the error appeared.

### AWS Java SDK version used

2.20.19

### JDK version used

jdk-11

### Operating System and version

"linux", version: "3.10.0-1160.6.1.el7.x86_64", arch: "amd64", family: "unix"

**Comment by pewtpong** [comment]
Hello, I am here to continue Khongchai's work. Our behavior is similar to the issue described in this link: [[BUG: S3 Connection pool shut down for S3Client](https://github.com/aws/aws-sdk-java/issues/1282#top)](https://github.com/aws/aws-sdk-java/issues/1282) Currently, I am in the process of reproducing the problem, and I will promptly post the results of the reproduction once it is completed.

**Comment by debora-ito** [comment]
@pewtpong noted.

**Comment by chenlin2001** [comment]
I can see the same issue. I'm using Micronaut aws sdk which creates the credentials this way:
` */
@Factory
@BootstrapContextCompatible
public class CredentialsAndRegionFactory {

    /**
     * @param environment The {@link Environment}
     * @return An {@link AwsCredentialsProviderChain} that attempts to read the values from the Micronaut environment
     * first, then delegates to {@link DefaultCredentialsProvider}.
     */
    @Bean(preDestroy = "close")
    @Singleton
    public AwsCredentialsProviderChain awsCredentialsProvider(Environment environment) {
        return AwsCredentialsProviderChain.of(
                EnvironmentAwsCredentialsProvider.create(environment),
                DefaultCredentialsProvider.create()
        );
    }
`
When using STS to assume role with services running in Kuberenets, things works ok in the beginning, but after an hour I see the same issues of connection pool. Seems to be the same error as in this ticket and https://github.com/aws/aws-sdk-java/issues/1282 and https://github.com/aws/aws-sdk-java-v2/issues/4386 
Any solution? This ticket seems to keep getting closed without solutions

**Comment by rlconst** [comment]
Try to do https://github.com/Frachtwerk/essencium-backend-file-storage/pull/196

**Comment by matschaffer-roblox** [comment]
I ran into this today in a spark 4.0.1  + hadoop 3.4 on k8s setup.

But only when attempting to use `fs.s3a.aws.credentials.provider=software.amazon.awssdk.auth.credentials.DefaultCredentialsProvider` 

Using `fs.s3a.aws.credentials.provider=software.amazon.awssdk.auth.credentials.WebIdentityTokenFileCredentialsProvider` seems to be fine.

My setup should be fine without a full credential chain, but it's surprising that the provider works when called directly, but not from a chain. This has me curious if there's some interplay between the providers causing the pool to close.

this was the full exception I ran into:

```
org.apache.hadoop.fs.s3a.auth.NoAuthWithAWSException: No AWS Credentials provided by DefaultCredentialsProvider : software.amazon.awssdk.core.exception.SdkClientException: Unable to load credentials from any of the providers in the chain AwsCredentialsProviderChain(credentialsProviders=[SystemPropertyCredentialsProvider(), EnvironmentVariableCredentialsProvider(), WebIdentityTokenCredentialsProvider(), ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])), ContainerCredentialsProvider(), InstanceProfileCredentialsProvider()]) : [SystemPropertyCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.acc
essKeyId)., EnvironmentVariableCredentialsProvider(): Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)., WebIdentityTokenCredentialsProvider(): Connection pool shut down, ProfileCredentialsProvider(profileName=default, profileFile=ProfileFile(sections=[])): Profile file contained no credentials for profile 'default': ProfileFile(sections=[]), Conta
inerCredentialsProvider(): Cannot fetch credentials from container - neither AWS_CONTAINER_CREDENTIALS_FULL_URI or AWS_CONTAINER_CREDENTIALS_RELATIVE_URI environment variables are set., InstanceProfileCredentialsProvider(): Failed to load credentials from IMDS.]  
```

the failures from the other providers in the chain are expected, but the WebIdentityTokenCredentialsProvider which I expected to work (IRSA, confirmed `AWS_WEB_IDENTITY_TOKEN_FILE` present in the container), just fails with `Connection pool shut down`

**Comment by acasademont** [comment]
I believe we hit the same issue as @matschaffer-roblox today when trying to switch from our hardcoded WebIdentityToken provider to the DefaultCredentialsProvider for the `fs.s3a.aws.credentials.provider` property. It might be a hadoop bug then?
