### ISSUE TITLE
Reopen issue #4213 - This is not a way to treat a customer

### ISSUE THREAD

**Issue by vgiguere** [aws/aws-sdk-java-v2#4225]
### Describe the feature

Can you please reopen issue #4213

I have spent the time to identify the root cause of a problem affecting DynamoDBLocal and to submit a ticket with lots of details with regards to it. It is an actual problem that I argue should be solved. I am willing to spend time engaging with the DynamoDBLocal team on this but there is unfortunately no other way for me to reach out to that team directly other than through this repo (which was done by other engineers numerous times in the past if you check)

@debora-ito closed the ticket on me, vaguely saying she will reach out to the team, which effectively cuts me out of that conversation and puts me in a position in which all I have left to do is to pray and hope something happens eventually someday because there is no way for me to interact with anyone and track progress.

I suggest you reopen the ticket and ask the folks from DynamoDBLocal team to comment on the ticket so I can engage with them, help them and be in a position in which I an see progress on the issue. 

If there is another ticket system I can use, please point me in the right direction instead of closing the issue.
This way, as a customer, I feel like I am treated right for doing the right thing and informing you of problems with your software libraries.

https://github.com/aws/aws-sdk-java-v2/issues/4213

### Use Case

Can you please reopen issue #4213

### Proposed Solution

Can you please reopen issue #4213

### Other Information

Can you please reopen issue #4213

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

latest 

### JDK version used

java 17, Kotlin 1.8

### Operating System and version

Mac OS 13.4

**Comment by debora-ito** [comment]
Please see my comments in #4213.
