### ISSUE TITLE
A 1.52 TB single file took 5 hours to download while only 50 minutes to upload

### ISSUE THREAD

**Issue by linzhu-isoftstone** [aws/aws-sdk-java-v2#4257]
### Describe the bug

We use the same instance of CRT S3AsyncClient and S3TransferManager to upload and download files from the S3 bucket with accelerate mode enabled.

It took 50 minutes to upload a 1.52TB single file and the transfer speed is acceptable. But it consistently took 5 hours to download the same file from the s3 bucket, which is too longer far away with what it used for uploading.

### Expected Behavior

The downloading should take time close to what it needs for uploading.

### Current Behavior

The downloading took 5 hours which is 6 times of the uploading time.

### Reproduction Steps

1. Have a s3 bucket with accelerate mode enabled.
2. Create a CRT based S3AsyncClient and S3TransferManager with default settings.
3. Use the transfer manager instance to upload a 1.52 TB single file, and log the used time.
4. Download the uploaded 1.52TB file with the same transfermanager, and log the used time.
5. Compare the download vs upload time.

### Possible Solution

S3TransferManager and CRT S3AsyncClient probably uses 8MB (the default minimum part size) as part size to download, but the file's actual part size is probably 160MB due to the parts could not exceed 10,000. Using 8MB as part size to download the file could incur too much overhead.

Currently, the S3TransferManager doesn't allow to set the minimum part size at upload/download request level, instead it's per S3TransferManager/S3Client instance level.

Can it be implemented this way?
1. Use the object's part size or multiple times of its part size to download it.
2. Or let the user to specify the part size at the download/request level.

### Additional Information/Context

It's fast to download several even hundreds of GB file. So the network is not a problem.

<aws.sdk.version>2.20.115</aws.sdk.version>
<aws-crt.version>0.24.0</aws-crt.version>

### AWS Java SDK version used

2.20.115

### JDK version used

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Operating System and version

Cent OS 7.9

**Comment by debora-ito** [comment]
@linzhu-isoftstone can you share a repro code?
