### ISSUE TITLE
Async Netty maxConnectionsPerEndpoint always uses the default value

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#426]
The current netty implementation ignores the connection override specified in the client factory: https://github.com/aws/aws-sdk-java-v2/blob/master/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/NettyConfiguration.java#L56-L58

**Comment by millems** [comment]
Nope, it was based on an external bug report and the fact that we were returning "serviceDefaults". 

Should we at least fix the naming? I read through the code a few times and missed that.

**Comment by shorea** [comment]
Yeah we should definitely fix the naming. Just curious if it was an actual regression because I haven't seen this behavior while performance testing.

**Comment by zoewangg** [comment]
This looks obsolete.
We are merging the configuration correctly now. Closing the issue.
```
        @Override
        public SdkAsyncHttpClient buildWithDefaults(AttributeMap serviceDefaults) {
            return new NettyNioAsyncHttpClient(this, standardOptions.build()
                                                                    .merge(serviceDefaults)
                                                                    .merge(SdkHttpConfigurationOption.GLOBAL_HTTP_DEFAULTS));

        }
```
