### ISSUE TITLE
Support java records in DynamoDbEnhancedClient and related annotations

### ISSUE THREAD

**Issue by ashr123** [aws/aws-sdk-java-v2#4281]
### Describe the feature

I want to be able to use records (practically improvement to `DynamoDbImmutable`)

### Use Case

improvement to `DynamoDbImmutable`

### Proposed Solution

all annotation should be applicable on fields types and use the auto-generated getters

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### AWS Java SDK version used

2

### JDK version used

17

### Operating System and version

MacOS 13.5

**Comment by debora-ito** [comment]
Hi @ashr123 thank you for your request.

Java Records were introduced in JDK 14. Currently, the Java SDK v2 provides full support to JDK 8, 11 and 17, so we can't add Records without breaking backwards compatibility, which you noticed as you marked the "breaking change" check in the template.

Record support would require a major version upgrade, it will not be added to the current DynamoDbEnhancedClient.

Let us know if you have further questions.

**Comment by ashr123** [comment]
Maybe this is deserving another issue, but can you add support for new annotation to handle TTL fields?
i.e. add the option to set the field according to another field (4 weeks since `lastUpdateTime` field) and another options

**Comment by debora-ito** [comment]
We already got a request about DynamoDB TTL, let's use that one to track - https://github.com/aws/aws-sdk-java-v2/issues/4295

**Comment by ashr123** [comment]
@debora-ito what about the 2 other subjects?

**Comment by debora-ito** [comment]
Oh sorry, I missed those.
I believe we have an open request for (2) already, will do a quick search and post the link here.
I don't think we'll be able to support (3), if we start to load the extension that wasn't loaded before it's a breaking change.

**Comment by debora-ito** [comment]
Found the link for (2), it's the same ask for Lombok use cases - https://github.com/aws/aws-sdk-java-v2/issues/1932.

**Comment by ashr123** [comment]
@debora-ito regarding 2, I wait for the issue reference, regarding 3, I don't think it's a breaking change, cause it's related to specific annotation and anyway anyone who wants to use `DynamoDbAutoGeneratedTimestampAttribute` will need to load the `software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension` in addition to `software.amazon.awssdk.enhanced.dynamodb.internal.client.ExtensionResolver#defaultExtensions` as described in `software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension`'s javadoc:
```java
DynamoDbEnhancedClient dynamoDbEnhancedClient = DynamoDbEnhancedClient.builder()
        .extensions(Stream.concat(
                        ExtensionResolver.defaultExtensions().stream(),
                        Stream.of(AutoGeneratedTimestampRecordExtension.create())
                )
                .collect(Collectors.toList()))
        .build();
```

 and I guess it's pretty common behavior and looks like a lot of boilerplate.

I think it won't be a breaking change…

**Comment by debora-ito** [comment]
Regardless, we don't have plans to start loading the AutoGeneratedTimestampRecordExtension by default.

Will go ahead and close this, please check the other github links to track progress.
