### ISSUE TITLE
Client is not sending `Host:` header

### ISSUE THREAD

**Issue by kevinwright** [aws/aws-sdk-java-v2#429]
When using the 2.0 client, with an endpoint override, against a mock S3 for testing purposes - no `Host:` header is sent.  Confirmed via WireShark

## Expected Behaviour
As per rfc2616, sec14: "A client **MUST** include a Host header field in all HTTP/1.1 request messages . If the requested URI does not include an Internet host name for the service being requested, then the Host header field MUST be given with an empty value."

See [https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html)

## Current Behaviour
The client is not presently rfc2616 compliant

## Possible Solution
Send the REQUIRED `Host:` header on all requests

## Context
It prevents me from being able to test/explore this API in a mocked environment

## Your Environment

* 2.0.0-preview-8
* Confirmed under both JDK 8 and JDK 9
* Confirmed under both Linux and OSX

**Comment by smigfu** [comment]
I am seeing the same issue when using build `2.0.0-preview-11` with s3Proxy (https://github.com/gaul/s3proxy).

**Comment by zoewangg** [comment]
Did a quick s3.putObject test with the latest version and verified the host header is present.
```
2018-11-29 13:19:11,916 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "PUT /test/test HTTP/1.1[\r][\n]"
2018-11-29 13:19:11,916 [main] DEBUG org.apache.http.wire - http-outgoing-1 >> "Host: localhost:55761[\r][\n]"

```

Can you try with the latest version? Feel free to reopen if you are still experiencing the issue with the latest version.

**Comment by sworisbreathing** [comment]
@zoewangg it looks like the host header is only being set by the Apache client, not the netty or url connection ones.
