### ISSUE TITLE
Revisit DynamoDB Retry Policy

### ISSUE THREAD

**Issue by shorea** [aws/aws-sdk-java-v2#431]
The retry policy for DynamoDB V1 is set to retry 10 times. This seems excessive and we should work with the service team to come up with more reasonable default retry behavior.

**Comment by RyanHoldren** [comment]
I have been using the default retry policy with `DynamoDBAsyncClient` and a DynamoDB table with "Auto Scaling" enabled. I am seeing a lot of `ProvisionedThroughputExceededException` exceptions when my reads or writes spike, which surprised me. I assumed the default retry policy to wait long enough for additional capacity to be allocated, but this seems not to be the case.

I suppose I have two questions:
1. Can `DynamoDBAsyncClient` be configured to wait long enough to that "Auto Scaling" has time to provision more capacity, so I stop seeing `ProvisionedThroughputExceededException` bubble up?
3. Would this be a useful configuration to bake into the SDK? Perhaps even the default configuration?

**Comment by zoewangg** [comment]
@RyanHoldren We've made a couple of fixes on the retrying logic. Can you try with the latest version? `2.0.0-Preview-11` as of now 

Fixed via #574
