### ISSUE TITLE
Investigate Deadlock risk in async client

### ISSUE THREAD

**Issue by shorea** [aws/aws-sdk-java-v2#432]
With the async client there is risk of deadlock if a customer makes a "synchronous" client call in their async future callback. This is a problem in both our current threading model where the Netty event loop completes the future and the proposed threading model where we submit future completion to a client owned thread pool.

### Risk in current threading model
Imagine a client with just a single thread in its Netty event loop
1)	Customer makes a request on their thread, we do all the marshalling on that thread and then pass it over to the Netty thread
2)	Netty thread makes the HTTP request and then submits the completion on that netty thread
3)	In the customers callbacks of that future, they decide to make a synchrounous call back into the client. This does all the marshalling on that thread then dispatches to Netty again
4)	Since the single event loop thread is blocked on the completion of the next request, the next request can't actually execute and we have a deadlock

### Risk in proposed threading model
Imagine a client with just a single thread in its thread pool
1)	Customer makes a request on their thread, we do all the marshalling on that thread and then pass it over to the Netty thread
2)	Netty thread makes the HTTP request and then submits the completion to the single client thread
3)	In the customers callbacks of that future, they decide to make a synchrounous call back into the client. This does all the marshalling on that thread then dispatches to Netty again
4)	Netty makes another HTTP request and then submits the completion to that same single client thread.
5)	Since that single client thread is blocked waiting on the completion, the actual completion can never execute and you have a deadlock.

**Comment by shorea** [comment]
Possible solution, override CompletableFuture to thrown an exception if get() or join() is called in a SDK client thread.

**Comment by zoewangg** [comment]
Done via #515
