### ISSUE TITLE
Lack of Examples with PostgreSQL Using IAM

### ISSUE THREAD

**Issue by StuxxNet** [aws/aws-sdk-java-v2#4320]
### Describe the issue

I have been trying to setup a simple application to execute a select statement in an Aurora Serverless cluster using IAM roles to authenticate, and I couldn't find any proper example on how to do this in the docs. I just found examples for the V1 version of the library and for MySQL, from which I tried to derive part of the code, but I'm still getting 403 errors from RDSProxy.

Is there any sample besides this? https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html

And besides this? https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java_rds_code_examples.html

I know that the problem is not the role or the Kubernetes cluster, because I was able to do exactly this using Go and the example from the docs in 5 minutes, and I have also validated using a PSQL + AWS CLI pod and the role attached to the service account of my pod is, indeed, working.

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/java_rds_code_examples.html
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html

**Comment by debora-ito** [comment]
Hi @StuxxNet I'm sorry you are getting blocked by the lack of Java SDK v2 code examples.

Looking at the examples in the [RDS Dev Guide](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/UsingWithRDS.IAMDBAuth.Connecting.Java.html), I see:
- The v1 `RdsIamAuthTokenGenerator` is used to generate the authentication token. The v2 equivalent is `RdsUtilities`: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/rds/RdsUtilities.html
- In the `IAMDatabaseAuthenticationTester` class, the only v1 classes used are the ones to obtain the AWS credentials. All v1 credential providers have equivalents in v2: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/credentials.html

Also found some troubleshooting steps for getting Access Denied - https://repost.aws/knowledge-center/rds-mysql-access-denied

Let me know if any of these references help, or if you'd like to see an example using v2.
