### ISSUE TITLE
Client-Level Trust Stores

### ISSUE THREAD

**Issue by ksemba** [aws/aws-sdk-java-v2#433]
Hi all,

I'm using the library within a Java application that is running on a wildfly application server. That server is started with a custom Java TrustStore which does NOT have the required certificates from neither "Starfield Services" nor the Amazon root CA. So my code failes with an error mentioning empty trustAnchors, etc.

I can dynamically set these environment variables to point the JVM (and thus the AWS library) to use the default Java truststore (which contains the required certs) and make it work that way:
```
System.setProperty("javax.net.ssl.trustStore", "/usr/local/java/jre/lib/security/cacerts");
System.setProperty("javax.net.ssl.trustStorePassword", "changeit");
```
But that is not an option in my case since this will alter the truststore for all Java apps running on that widlfly server and that is a no-go.

I was looking into the new feature that allows me to overwrite the HTTP client but I couldn't find a way to supply that custom HTTP client with a custom TrustStore...

Any ideas on how to achieve this?
Thanks

**Comment by spfink** [comment]
We'll have to look into how we want to support this. Bit trickier than v1 as we would need to support this for any HTTP client that can be plugged in to the SDK in v2.

**Comment by ksemba** [comment]
@spfink Thanks for looking into it. For the moment, I solved it using version 1 of the SDK but I assume that sooner or later that version will be out of support and won't get new features.
