### ISSUE TITLE
High cpu utilization in DynamoDbEnhancedAsyncClient

### ISSUE THREAD

**Issue by cukyz** [aws/aws-sdk-java-v2#4333]
### Describe the bug

I am using DynamoDbEnhancedAsyncClient.
When I did a performance test using awssdk version 2.20.47, the CPU utilization was too high. 
getItem and query are both high CPU utilization.
So I changed the awssdk version and the CPU utilization was quite different.

The versions are as follows.
- awssdk 2.20.47 (before)
- awssdk 2.20.121 (later)

After changing the SDK version to awssdk 2.20.121, the CPU utilization decreased. 

but i think still shows high CPU utilization.

### Expected Behavior

tested with ElastiCache on the same code, it showed much lower CPU utilization.
At least It would be better if the CPU utilization was not significantly different with ElastiCache.

### Current Behavior

Current measurements

Server test results:
- The server is configured in aws EC2 (4core 8GB x 2ea)
- I used ngrinder for performance-test. (similar to jmeter)

Vusers : 100

  | ver 2.20.47 | ver 2.20.121
-- | -- | --
TPS | 6,252.5 | 6,512.6
CPU | 69.5% | 62.4%

CPU utilization so different depending on the sdk version.
So I have plan to update production to 2.20.121.
And if I test with ElastiCache instead of DynamoDB, the CPU utilization is much lower.

Here are the results of testing in Local PC to check for GC.
- Local PC is configured 12core x 32GB

Vusers : 32

  | ver 2.20.47 | ver 2.20.121
-- | -- | --
TPS | 737.8 | 809.4
CPU | 20% | 11%

- awssdk 2.20.47 (before), TPS: 737.8, CPU: 20%
![image2023-8-11_17-18-26](https://github.com/aws/aws-sdk-java-v2/assets/25068727/c4cbf426-bc15-4f25-98e8-aae7e4933539)
![image2023-8-11_17-16-1](https://github.com/aws/aws-sdk-java-v2/assets/25068727/26e76f19-fef3-4039-8f61-4f028160cc6b)

- awssdk 2.20.121 (later), TPS: 809.4, CPU: 11%
![image2023-8-11_17-17-56](https://github.com/aws/aws-sdk-java-v2/assets/25068727/3603c6b7-fcca-4629-afa2-dcd0e2002a20)
![image2023-8-11_17-16-17](https://github.com/aws/aws-sdk-java-v2/assets/25068727/e7ab5a26-fa8e-44d9-94f4-6d09d28ce7e1)

### Reproduction Steps

    ```

    private final DynamoDbEnhancedAsyncClient dynamoDbEnhancedAsyncClient;
    private final DynamoDbAsyncTable<Test> testDynamoDbAsyncTable;

    @Autowired
    public TestRepository(DynamoDBProperty dynamoDBProperty, DynamoDbEnhancedAsyncClient dynamoDbEnhancedAsyncClient) {
        this.dynamoDbEnhancedAsyncClient = dynamoDbEnhancedAsyncClient;
        this.testDynamoDbAsyncTable = this.dynamoDbEnhancedAsyncClient.table(
                TABLE_NAME,
                TableSchema.fromImmutableClass(Test.class)
        );
    }

    @Override
    public Mono<Test> getItemByPartitionKey(String id) {
        String sk = "test#" + id.substring(10, 17);
        Key testKey = Key.builder().partitionValue(id).sortValue(sk).build();
        return Mono.fromCompletionStage(testDynamoDbAsyncTable.getItem(testKey));
    }
	
    @Override
    public Flux<Test> queryByPartitionKey(String id) {
        Key testKey = Key.builder().partitionValue(id).build();
        QueryConditional queryConditional = QueryConditional.keyEqualTo(testKey);
        QueryEnhancedRequest queryEnhancedRequest = QueryEnhancedRequest.builder()
                .queryConditional(queryConditional)
                .build();
        return Flux.defer(() -> Flux.from(testDynamoDbAsyncTable.query(queryEnhancedRequest)
                .flatMapIterable(Page::items)));
    }	
```

### AWS Java SDK version used

awssdk 2.20.47

### JDK version used

OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 

### Operating System and version

amazon linux 2

**Comment by debora-ito** [comment]
We're glad that 2.20.121 showed improvements when compared to 2.20.47.

> tested with ElastiCache on the same code, it showed much lower CPU utilization.

Do you mean running the code on ElastiCache clusters? 
ElastiCache is a solution that is focused in high-performance, so I don't think it's a fair expectation to see the same CPU usage.

Can you generate a CPU flame graph for your tests? Flame graphs are easier to visualize and identify potential parts that can be optimized .

**Comment by cukyz** [comment]
Thank you for your feedback.
Attach additional test results as shown below.

Conditions used in the test
  - Same condition (vUser: 32), running on the same local PC (12core)


### Test case 1

#### 1. Run on SDK 2.20.47
![sdk-2 20 47_async-profiler-flame_01](https://github.com/aws/aws-sdk-java-v2/assets/25068727/3e209526-df1c-416e-afb2-33f09b4492e9)

#### 2. Run on SDK 2.20.121
![sdk-2 20 121_ async-profiler-flame_01](https://github.com/aws/aws-sdk-java-v2/assets/25068727/4976e222-377c-41a5-aacb-1daa76626b24)


#### Conclusion : 
I found logging thread in flame graph.
So, remove logging and tested again. (In Local env, I was logging as DEBUG level in relation to DynamoDB, but I modified it to INFO and tested it. When testing on the server I reported before, I was logging as INFO)


### Test case 2
Test again after removing logging.

#### 1. Run on SDK 2.20.47

- a) Flame Graph

![sdk-2 20 47_async-profiler-flame_04_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/05d29366-71de-41e6-9322-aa338e611213)

- b) CPU, TPS

![1  ngrinder_sdk-2 20 47_3_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/89dbfefb-ccab-4ca0-b1dd-1ae5015283da)

![2  jvm_sdk-2 20 47_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/97b8181b-10d4-43b2-b647-233d337db1c0)


#### 2. Run on SDK 2.20.121

- a) Flame Graph

![sdk-2 20 121_ async-profiler-flame_04_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/91dcc34b-55e0-4497-ae52-41e6af130e93)


- b) CPU, TPS

![1  ngrinder_sdk-2 20 121_3_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/ec485e0b-1faf-4446-8139-4bbe8bde5b1b)

![2  jvm_sdk-2 20 121_removelog](https://github.com/aws/aws-sdk-java-v2/assets/25068727/e539988d-89a3-4fba-a606-7cd417f9d5e8)


#### Conclusion : 

there was an increase TPS, due to not logging.
there was still a difference in CPU utilization between the sdk versions.
higher CPU utilization on the old version (and lower TPS).

**Comment by debora-ito** [comment]
@cukyz thank you for the flame graphs, and I'm sorry for the long silence.

Nothing in the flame graphs stand out as areas to improve. If you're looking to minimize CPU usage, we suggest:
- try the sync clients: async client's non-blocking IO is meant to increase throughput at the expense of CPU and possibly latency
- try the CRT-based HTTP client: benchmarks show performance improvement when the CRT-based HTTP client is used vs. netty HTTP client. More details can be found in our blog - https://aws.amazon.com/blogs/developer/introducing-aws-common-runtime-http-client-in-the-aws-sdk-for-java-2-x/
