### ISSUE TITLE
Shaded third-party jackson-core 2.13.2 is missing fix for sonatype-2022-6438

### ISSUE THREAD

**Issue by ericfreese** [aws/aws-sdk-java-v2#4336]
### Describe the bug

The shaded third-party `jackson-core` is set at version `2.13.2` which does not have a fix for vulnerability issue `sonatype-2022-6438`.

https://github.com/aws/aws-sdk-java-v2/blob/5aa3ff309ca5698eb452aa077f191d842f0fa55a/pom.xml#L95

### Expected Behavior

The shaded third-party `jackson-core` should be at least version `2.15.0`.

### Current Behavior

The issue was flagged by a [prisma](https://www.paloaltonetworks.com/prisma/cloud) scan.

### Reproduction Steps

N/A

### Possible Solution

Upgrade to at least 2.15.0. Hopefully this is not too difficult because of the shading.

From https://github.com/aws/aws-sdk-java-v2/pull/2598#issuecomment-886902569:

> Shading allows us to use the latest, secure Jackson version without worrying about breaking customer applications.

### Additional Information/Context

See:
- https://github.com/FasterXML/jackson-core/issues/861
- https://github.com/FasterXML/jackson-core/pull/827
- https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.15

This issue is similar to: https://github.com/aws/aws-sdk-java-v2/issues/3825

### AWS Java SDK version used

2.18.41

### JDK version used

openjdk version "1.8.0_382" OpenJDK Runtime Environment Corretto-8.382.05.1 (build 1.8.0_382-b05) OpenJDK 64-Bit Server VM Corretto-8.382.05.1 (build 25.382-b05, mixed mode)

### Operating System and version

Linux 9d7c897afc63 6.4.11-arch2-1 #1 SMP PREEMPT_DYNAMIC Sat, 19 Aug 2023 15:38:34 +0000 x86_64 x86_64 x86_64 GNU/Linux

**Comment by debora-ito** [comment]
@ericfreese acknowledged.

**Comment by debora-ito** [comment]
The jackson version was upgraded as part of Java SDK version `2.20.140`.
