### ISSUE TITLE
S3Utilities::parseUri truncates keys of URIs containing #

### ISSUE THREAD

**Issue by jackdreinhardt** [aws/aws-sdk-java-v2#4359]
### Describe the bug

I am working with S3 objects that have keys containing a single 'pound' (`#`) character. When calling the `parseUri` function, the key value is truncated just before the pound.

### Expected Behavior

I expect the full key value to be present
```java
var uri = s3.utilities().parseUri(URI.create("s3://bucket/key#with%20pound"));
uri.key(); // key#with%20pound
```

### Current Behavior

The key value does not contain any characters after the 'pound' (`#`)
```java
var uri = s3.utilities().parseUri(URI.create("s3://bucket/key#with%20pound"));
uri.key(); // key
```

### Reproduction Steps

```java
import java.net.URI;
import software.amazon.awssdk.services.s3.S3Client;

var s3 = S3Client.create();
var uri = s3.utilities().parseUri(URI.create("s3://bucket/key#with%20pound"));
if (uri.key() != "key#with%20pound") {
  throw new RuntimeException();
}
```

### Possible Solution

[S3 docs state that the 'pound' (`#`) character should be avoided](https://docs.aws.amazon.com/AmazonS3/latest/userguide/object-keys.html#object-key-guidelines-avoid-characters), but objects can still be created containing this value. URI parsing sends all characters after the `#` to the fragment. One possible solution could be to include the fragment in the key [here](https://github.com/aws/aws-sdk-java-v2/blob/f502f9f1e8a511cfae571adbb9390a3cf0c82f40/services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java#L384) if it's present. Another possible solution could be to replace any `#` characters with `%23` before the URI is passed to `parseUri`. If the intended behavior is to not support keys with `#`, failing fast with a clear error message would be better than the existing experience.

### AWS Java SDK version used

latest

### JDK version used

11

### Operating System and version

MacOS

**Comment by debora-ito** [comment]
@jackdreinhardt apologies for the delay in replying.

This is mentioned in the [parseUri](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3Utilities.html#parseUri(java.net.URI)) Javadoc:

> If you work with object keys and/or query parameters with special characters, they must be URL-encoded, e.g., replace " " with "%20". If you work with virtual-hosted-style URIs with bucket names that contain a dot, i.e., ".", the dot must not be URL-encoded. Encoded buckets, keys, and query parameters will be returned decoded.

You need to encode the input manually, because adding the encoding now in the SDK would break customers who are already encoding on their side.
