### ISSUE TITLE
`getObject` future completes before file downloaded

### ISSUE THREAD

**Issue by AntonOellerer** [aws/aws-sdk-java-v2#4365]
### Describe the bug

I am using the aws sdk v2 together with project reactor to fetch files from S3.
During production deployment, we noticed that sometimes it seemed as if the download did not happen, without any notice being given.
Upon further examination, we think that the problem is that the `getObject` future completes before the file is fully visible to the system. 

### Expected Behavior

The file is downloaded and accessible by further processing steps.

### Current Behavior

Sometimes, the file cannot be used by the following processing steps

### Reproduction Steps

```java
  public Mono<Path> downloadFile(String key, String bucket, Path downloadPath) {
    GetObjectRequest getObjectRequest = GetObjectRequest
        .builder()
        .bucket(bucket)
        .key(key)
        .build();
    return Mono.fromCallable(() -> Files.createDirectories(downloadPath.getParent()))
        .subscribeOn(Schedulers.boundedElastic())
        .then(Mono.fromFuture(s3AsyncClient.getObject(getObjectRequest, downloadPath)))
        .doOnSuccess(getObjectResponse -> log.info("Downloaded file {}, exists {}", downloadPath, Files.exists(downloadPath)))
        .thenReturn(downloadPath);
  }
```

### Possible Solution
The following extended stream fixes the problem

```java
    return Mono.fromCallable(() -> Files.createDirectories(downloadPath.getParent()))
        .subscribeOn(Schedulers.boundedElastic())
        .then(Mono.fromFuture(s3AsyncClient.getObject(getObjectRequest, downloadPath)))
        .thenMany(Flux.interval(Duration.ofMillis(5)))
        .takeUntil(i -> Files.exists(downloadPath))
        .then(Mono.just(downloadPath))
        .timeout(Duration.ofSeconds(deployment.maxWaitSeconds()))
        .doOnSuccess(getObjectResponse -> log.info("Downloaded file {}", downloadPath));
```

### Additional Information/Context

spring boot & spring-boot-starter-webflux 3.1.3

### AWS Java SDK version used

2.20.136

### JDK version used

17

### Operating System and version

[eclipse-temurin:17-jre-alpine](https://hub.docker.com/_/eclipse-temurin)

**Comment by debora-ito** [comment]
This is weird.

> Upon further examination, we think that the problem is that the getObject future completes before the file is fully visible to the system.

How did you get to this conclusion? 

Can you show the logs of the error when you try to access the files?
How often does it happen? Do you have a rough estimate of errors/download?

**Comment by AntonOellerer** [comment]
It seems as if it is connected to [this issue](https://stackoverflow.com/a/60798321/4786733)
I changed to the sync sdk and the problem disappeared

**Comment by debora-ito** [comment]
The [StackOverflow question](https://stackoverflow.com/questions/60783347/how-to-use-project-reactors-scheduler-with-executor-based-libraries/60798321#60798321) was a great find, thank you for sharing.

Seems this is a particularity of Reactor Mono. Do you have any questions about the Java SDK side?
