### ISSUE TITLE
Release connection when closing s3 ResponseInputStream

### ISSUE THREAD

**Issue by peterfouquet0001** [aws/aws-sdk-java-v2#438]
I get a s3 ResponseInputStream with
final ResponseInputStream<GetObjectResponse> inputStream = s3Client.getObject(GetObjectRequest.builder()
            .bucket(bucketname)
            .key(filename)
            .build());

after reading the content I close the stream with inputStream.close(); but the underlaying connection is not released, so I got an out of connection exception from the http cient.
SdkClientException: Unable to execute HTTP request: Timeout waiting for connection from pool
 
## Expected Behavior
Calling close() on a SdkFilterInputStream should release the underlaying connection.

## Current Behavior
Calling close() on a SdkFilterInputStream didn't release the underlaying connection.

## Possible Solution
Wrap the ResponseInputStream with an own wrapper class to release the connecttion when close the input stream.

## Steps to Reproduce (for bugs)
Create and close the ResponseInputStream from s3Client.getObject(...) multiple times (> 50 by default) and log the org.apache.http.impl.conn.PoolingHttpClientConnectionManager on debug level.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview8

**Comment by lqjack** [comment]
Do you any update ?

**Comment by millems** [comment]
Investigating...

**Comment by millems** [comment]
A fix will go out with the next release.
