### ISSUE TITLE
Shaded jar third-party-jackson-core:2.20.140 has duplicate multi-jar classes

### ISSUE THREAD

**Issue by dspaven** [aws/aws-sdk-java-v2#4391]
### Describe the bug

Updating to third-party-jackson-core version 2.20.140 is failing our builds due to it containing duplicate classes with jackson-core.

This appears to be a build issue with third-party-jackson-core where it creates a shaded jar of jackson-core by relocating classes to the awssdk package namespace. However, the current build configuration falls down because it doesn't relocate the jackson-core multi-release classes. So these remain in the shaded jar as multi-release classes but packaged within com.fasterxml.jackson.core - causing duplicate class conflicts.

### Expected Behavior

Jackson core multi-release classes should be relocated to the appropriate awssdk package in third-party-jackson-core

### Current Behavior

jackson-core multi-releases classes are not relocated.

### Reproduction Steps

Inspect META-INF\versions\ in third-party-jackson-core:2.20.140

### AWS Java SDK version used

2.20.140

### JDK version used

17.0.6

### Operating System and version

Windows 10

**Comment by debora-ito** [comment]
@dspaven thank you for reaching out, a PR is in the works.
