### ISSUE TITLE
HTTP Pipelining

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#44]
For some AWS APIs, customers may wish to execute multiple concurrent requests over a single connection without relying on the service having implemented a "batch" version of the API. An API could be provided to execute multiple "pipelinable" requests over a single connection if the HTTP client supports it.

**Comment by shorea** [comment]
Resolving this for now as we have no plan to implement support for this.

**Comment by wem** [comment]
Hello

Sorry about adding comment on closed issue, but i think it's better than open a new one.

I tested this against DynamoDB with a custom http client (Vert.x) and enabled pipelining. I worked without issues in a first instance.

So my question is, at least some the AWS services supports HTTP pipelining on server side? I'm right?

Regards
