### ISSUE TITLE
Cancelling response stream subscription

### ISSUE THREAD

**Issue by DGolubets** [aws/aws-sdk-java-v2#440]
When subscription is cancelled before consuming all the response data, an exception is thrown.

## Expected Behavior
It should call _onComplete_.

## Current Behavior
After a while, _OnError_ is called with _ReadTimeoutException_
```
[error] s.a.a.h.n.n.i.ResponseHandler - Exception processing request: software.amazon.awssdk.http.DefaultSdkHttpFullRequest@6d8c3b28
io.netty.handler.timeout.ReadTimeoutException: null
```

## Possible Solution
I didn't dig into the code yet. 
I hope it's an easy fix for the contributors.

## Steps to Reproduce (for bugs)
Implement AsyncResponseHandler like this:
```scala
val handler = new AsyncResponseHandler[GetObjectResponse, Unit] {

      override def responseReceived(responseT: GetObjectResponse): Unit = { }

      override def exceptionOccurred(throwable: Throwable): Unit = {}

      override def onStream(publisher: Publisher[ByteBuffer]): Unit = {
        publisher.subscribe(new Subscriber[ByteBuffer] {
          var sub: Subscription = _
          override def onError(throwable: Throwable): Unit = {}

          override def onComplete(): Unit = {}

          override def onNext(t: ByteBuffer): Unit = {
            sub.cancel()
          }

          override def onSubscribe(subscription: Subscription): Unit = {
            sub = subscription
            sub.request(1)
          }
        })
      }

      override def complete(): Unit = { }
    }
```

## Context
I'm working with S3 in my Scala+ Akka Stream project and I've written a simple S3 client on top of the new SDK to utilize it's non-blocking capabilities.

One of my components only needs to read the beginning of the stream to do it's job and then it closes it. That's how I discovered the problem. If I consume stream in full - everything is fine.

I've shown the naive "how to reproduce" implementation of the AsyncResponseHandler above. My real code at the moment is:
```scala
def getObjectAsByteStream(bucket: String, key: String): Source[ByteString, NotUsed] = {
    val promise = Promise[Source[ByteBuffer, NotUsed]]()

    val req = buildObjectRequest(bucket, key)
    val handler = new AsyncResponseHandler[GetObjectResponse, Unit] {

      override def responseReceived(responseT: GetObjectResponse): Unit = {
      }

      override def exceptionOccurred(throwable: Throwable): Unit = {
        promise.tryFailure(throwable)
      }

      override def onStream(publisher: Publisher[ByteBuffer]): Unit = {
        promise.trySuccess(Source.fromPublisher(publisher))
      }

      override def complete(): Unit = {
      }
    }

    client
      .getObject(req, handler)
      .asScala
      .andThen {
        case Failure(t) =>
          promise.tryFailure(t)
      }

    Source
      .fromFutureSource(promise.future)
      .map(ByteString(_))
      .mapMaterializedValue(_ => NotUsed)
  }
```
My application works so far in the development mode, but I guess there are some connections sitting in the background that will make it an issue under the load in production.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-8
* JDK version used: 1.8
* Operating System and version: Windows 10

**Comment by dagnir** [comment]
As in v1, we should discard the connection if the response is not fully consumed by the user.

**Comment by varunnvs92** [comment]
#406 has been resolved. Try out the latest version and feel free to re-open if the issue still exists.
