### ISSUE TITLE
S3 AsyncClient Increasing LeasedConcurrency 

### ISSUE THREAD

**Issue by leesanghyeok** [aws/aws-sdk-java-v2#4417]
### Describe the bug

Hello.

We are operating a service that uploads and downloads files to S3.

Suddenly one day, the leasedConcurrency continued to increase, and a failure occurred as it reached MaxConcurrency. As leasedConcurrency is the number of current request, it should decrease when processing is completed, but it continues to increase. The issue can be reproduced as follows.

Canceling a large file download is a common case. Please check it and let me know your response. Thank you.

### Expected Behavior

Even if users cancel in the browser, LeasedConcurrency should not increase.

### Current Behavior

if users cancel in the browser, LeasedConcurrency is increasing

### Reproduction Steps

Reproduction case:

- Prepare a large file on S3 that takes a long time to download.
- Set up an API that calls getObject() using webflux + coroutine + S3AsyncClient.
- Open multiple **Chrome browsers** and call the file download API
- Cancel the download before it is completed.
- Check leasedConcurrency and see that it does not decrease but increases.

When checking with this reproduction case, leasedConcurrency increased when multiple downloads were canceled simultaneously, but it decreased when processed sequentially. This part may need to be reproduced and analyzed.

## Dependencies
- kotlin + webflux + coroutine + S3AsyncClient
- JVM : 11
- spring-boot : 2.7.3
- aws sdk : 2.20.144
- chrome : 116.0.5845.179 (arm64)

### AWS Java SDK version used

2.20.144

### JDK version used

11

### Operating System and version

Local : MacOs 13.2.1, Server : Alpine Linux 3.13.12

**Comment by debora-ito** [comment]
@leesanghyeok can you share a self-contained repro code?
When you say "Cancel the download before it is completed", how exactly are you canceling it?

**Comment by leesanghyeok** [comment]
@debora-ito 
Thank you for your response.
Unfortunately, it seems difficult to share the repository.
Instead, I have a code block left when I inquired about the relevant content through AWS support.
You can check the code by contacting the case manager. I'll also let the case manager know that I can share the code.
The case number is 13755064641.

And canceling is very simple. Just click 'Cancel File' as shown in the attached image.
![image](https://github.com/aws/aws-sdk-java-v2/assets/5162913/da444ea2-c7bb-4938-b3e7-5882faf272f3)

**Comment by leesanghyeok** [comment]
Hello, it's been 3 weeks since I left an issue, and I'd like to check the current status.
What was the root cause of the problem?

Additionally, I will explain in more detail how to reproduce the issue.
Reproducible case: Download1 -> Download2 -> Download3 -> Cancel1 -> Cancel2 -> Cancel3
Non-reproducible case: Download1 -> Cancel1 -> Download2 -> Cancel2 -> Download3 -> Cancel3

thank you

**Comment by debora-ito** [comment]
@leesanghyeok sorry for the loosing track of this in here. I was replying in your support ticket. 

If the Java SDK is not part of the cancel process, I can't tell why the leased connection doesn't get back to the connection pool when a download is cancelled via the Chrome UI. You previously mentioned this is not reproducible with CURL, so this indicates it's not an issue with the Java SDK.

We can't offer general guidelines on how to handle the increasing leasedConcurrency without knowing what's causing it. I would expect that the api call would timeout at some point and the connection would get back to the connection pool, so you can tweak the timeouts to lower values - we can't provide exact values, this is something you will need to experiment in your application.

If you can provide a repro code where the download is canceled via Java SDK code and you still see the issue, we can take a look.

**Comment by leesanghyeok** [comment]
Hello.
Since your team couldn't reproduce the issue, I prepared a toy project that does. 
But I couldn't make the repo public, so I sent it through a support ticket. 
It would be great if you could do additional analysis with this project. 
While creating the toy project, I accidentally found out that the issue disappeared when not using the e-tag feature. 
It seems to be related, so it would be helpful if you could refer to it when analyzing.

If you have any additional thoughts, please let me know.
Thank you.
