### ISSUE TITLE
CreateMeetingResponse returning nested object but while trying to return it as response of API call in  Java Spring Boot Application.

### ISSUE THREAD

**Issue by pgope-mdsol** [aws/aws-sdk-java-v2#4419]
### Describe the issue

Nested Object getting from AWS SDK for Java 2.0 ( Chime ) methods not getting serialized 

<img width="1261" alt="image" src="https://github.com/aws/aws-sdk-java-v2/assets/84412231/2616c0b5-98b8-4855-bf83-23a0a8cf8749">

**Getting this exception**
"com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class software.amazon.awssdk.services.chimesdkmeetings.model.CreateMeetingResponse and 
no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)"

### Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/chimesdkmeetings/model/CreateMeetingResponse.html#serializableBuilderClass()

**Comment by debora-ito** [comment]
@pgope-mdsol Apologies, this issue got overlooked.

Do you still see the serializer error?
If so, please generate the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) of the CreateMeeting call so we can see the exact response the SDK is trying to deserialize. Make sure to redact any sensitive information (like access keys) before sharing the logs.
