### ISSUE TITLE
Release Date?

### ISSUE THREAD

**Issue by noviceamateur** [aws/aws-sdk-java-v2#443]
Can anyone provide me the GA timeline for the v2 sdk? Even a tentative on will do.

**Comment by baynezy** [comment]
I have been told by some representatives of AWS that this will be Q4. It will be missing a few things that V1 has when it hits GA.

**Comment by oripwk** [comment]
It looks like it has been released as a non-preview version:

https://github.com/aws/aws-sdk-java-v2/releases/tag/2.0.5

Is it safe to use? (although it only contains limited services)

**Comment by millems** [comment]
The three services released under 2.0.x are safe to use in production.
