### ISSUE TITLE
Add ReturnValuesOnConditionCheckFailure member to Update & Put Enhanced Request

### ISSUE THREAD

**Issue by masakiasanuma** [aws/aws-sdk-java-v2#4442]
### Describe the feature

Currently, only [UpdateItemRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/UpdateItemRequest.html#returnValuesOnConditionCheckFailure()) and [PutItemRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/PutItemRequest.html#returnValuesOnConditionCheckFailure()) using the non-enhanced Dynamo DB client allows you to set the `ReturnValuesOnConditionCheckFailure` member to make the `ConditionalCheckFailedException` to return the failed item. I want this member to be added to the `UpdateItemEnhancedRequest` and `PutItemEnhancedRequest` so that this feature can be used with the enhanced Dynamo DB client.

### Use Case

My service currently uses multiple conditions when creating & updating items, and there's no way to differentiate which condition failed without retrieving & checking the item that failed in the `ConditionalCheckFailedException` object. With the `ReturnValuesOnConditionCheckFailure` feature, my service will be able to throw specific exceptions based on which condition failed, allowing the service clients to handle exceptions more clearly. 

### Proposed Solution

Add an optional `returnValuesOnConditionCheckFailure` member to `UpdateItemEnhancedRequest.builder` and `PutItemEnhancedRequest.builder` that takes in the [ReturnValuesOnConditionCheckFailure Enum](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dynamodb/model/ReturnValuesOnConditionCheckFailure.html). When this member is set to `ALL_OLD`, it will append the failed/old item as a `Map<String, AttributeValue>` in the [ConditionalCheckFailedException](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/ConditionalCheckFailedException.html) object.

### Other Information

I believe this was a recent feature added based on the [announcement date](https://aws.amazon.com/about-aws/whats-new/2023/06/amazon-dynamodb-cost-failed-conditional-writes/), which might be the reason this was not added to the Enhanced requests yet.

Somewhat similar to this [issue](https://github.com/aws/aws-sdk-java-v2/issues/4247), but I specifically need the value to be returned on `ConditionalCheckFailedException`. The `ReturnValues` attribute _does not_ return the item in the exception object, it only returns when the operation succeeds.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2

### JDK version used

17

### Operating System and version

AL2

**Comment by debora-ito** [comment]
@masakiasanuma thank you for reaching out. Request acknowledged.

Community note: add a 👍 reaction to the original description to help us prioritize this request.

**Comment by masakiasanuma** [comment]
Hi @debora-ito, thank you for picking this up! Just curious, is there an average ETA for the completion of these kind of requests? I want to determine if it's worth implementing a workaround for now or if I should just wait until this feature request is completed. Thanks!

**Comment by breader124** [comment]
Hi, I'd like to start working on it if possible

**Comment by masakiasanuma** [comment]
Hi @breader124, it seems like they have not started working on this yet as they might not have enough bandwidth to prioritize this request over others. If you have the time, I would very much appreciate it if you could implement this feature!

**Comment by debora-ito** [comment]
This is now supported, via https://github.com/aws/aws-sdk-java-v2/pull/4708.

Available in version `2.21.37`. Thank you @breader124 for your contribution!

**Comment by masakiasanuma** [comment]
Thank you @debora-ito and @breader124!
