### ISSUE TITLE
Missing classes (ListObjectsV2Iterable/ListObjectsV2Publisher)?

### ISSUE THREAD

**Issue by NikolayAtSony** [aws/aws-sdk-java-v2#447]
Please clarify are those classes
import software.amazon.awssdk.services.s3.paginators.ListObjectsV2Iterable;
import software.amazon.awssdk.services.s3.paginators.ListObjectsV2Publisher;

which are referenced from
https://github.com/aws/aws-sdk-java-v2/blob/75440747143a78f19606440d82ebf5cd8837418c/services/s3/src/it/java/software/amazon/awssdk/services/s3/ListObjectsV2PaginatorsIntegrationTest.java

are missing?

**Comment by NikolayAtSony** [comment]
I guess it's a little bit more generic question - does S3 follows the rest of the SDK now to avoid checking-in any autogenerated code (like S3AsyncClient.java, etc) to the source control to be aligned with other services?

**Comment by shorea** [comment]
Yes S3 is not generated from a model and source code is not directly checked in. You'll have to build locally with maven to see those classes.
