### ISSUE TITLE
toJson implementation for IamPolicy.java class is wrong.

### ISSUE THREAD

**Issue by stripathi1988** [aws/aws-sdk-java-v2#4481]
### Describe the bug

In toJson implementation, actions are being added to resources field.
Because of this, wrong json document is getting created.

<img width="767" alt="image" src="https://github.com/aws/aws-sdk-java-v2/assets/141525060/72d7a4af-e300-4c72-ae5a-8e8a13052dcd">

### Expected Behavior

toJson method should create correct json.

### Current Behavior

In toJson implementation, actions are being added to resources field.
Because of this, wrong json document is getting created.

### Reproduction Steps

Create a IamPolicy.java object , add resources to it. 
Then convert it to json by calling toJson method.

### AWS Java SDK version used

2.20.109

### JDK version used

java 17

### Operating System and version

windows 11

**Comment by debora-ito** [comment]
@stripathi1988 that was fixed via https://github.com/aws/aws-sdk-java-v2/pull/4223. Please upgrade to version 2.20.111 or later.
