### ISSUE TITLE
Does the SDK include Lambda trigger shapes?

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#4498]
### Describe the issue

I am trying to write support for consuming the Cognito `PreSignup` Lambda trigger, and the documentation (scattered across multiple pages) shows the top-level members but not any internal structure. I have looked through the source and binary of `cognitoidentityprovider`, and though the `LambdaConfigType` references the `PreSignup` trigger, there appears to be no further reference to it.

I had hoped that the SDK would include a Java class that modeled the incoming data structore for the Lambda triggers applicable to the product in question; is it present somewhere that I haven't yet found?

### Links

* https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-lambda-pre-sign-up.html#cognito-user-pools-lambda-trigger-syntax-pre-signup
* https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-pools-lambda-trigger-syntax-shared
* https://github.com/aws/aws-sdk-java-v2/blob/b0d5c74/services/cognitoidentityprovider/src/main/resources/codegen-resources/service-2.json#L5583-L5586

**Comment by debora-ito** [comment]
Going through the Cognito Lambda triggers [documentation](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html), I understand you need to [configure a Lambda trigger](https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html#cognito-user-identity-pools-working-with-aws-lambda-triggers-using-lambda) in the user pool, providing a trigger type (like Pre Signup) and the Lambda function you want to be invoked. 

Is this the example you are looking for? How to configure the Lambda trigger in the user pool using Java SDK?

**Comment by debora-ito** [comment]
Here's a sample of how to associate a lambda function to a user pool in the preSignedUp trigger:

```Java
    UpdateUserPoolRequest request = UpdateUserPoolRequest.builder()
        .userPoolId(USER_POOL_ID)
        .lambdaConfig(l -> l.preSignUp("arn:aws:lambda:us-west-2:<xxx>:function:<myLambdaFunction>"))
        .build();

    UpdateUserPoolResponse response = client.updateUserPool(request);
```

The [`LambdaConfigType`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/cognitoidentityprovider/model/LambdaConfigType.html) docs are not super clear, but each trigger method takes a Lambda ARN as an argument.
