### ISSUE TITLE
Where did IDynamoDBMapper go?

### ISSUE THREAD

**Issue by efenderbosch** [aws/aws-sdk-java-v2#450]
Or classes that have replaced it?

We're evaluating moving to v2 for some greenfield development, but I can't seem to find mapper functionality.

**Comment by spfink** [comment]
We haven't yet refactored the mapper for v2:

https://github.com/aws/aws-sdk-java-v2/issues/35

It will definitely be back in some form but we don't have an ETA for that yet.

**Comment by dagnir** [comment]
We're tracking the mapper impl in #35 so I'll go ahead and close this.
