### ISSUE TITLE
Support endpoint override with environment variables

### ISSUE THREAD

**Issue by fkjaekel** [aws/aws-sdk-java-v2#4501]
### Describe the feature

I'm looking forward to use this [feature](https://aws.amazon.com/blogs/developer/new-improved-flexibility-when-configuring-endpoint-urls-with-the-aws-sdks-and-tools/) with the Java SDK.

I was not able to get it working with the SSM client version 2.20.156 and there are no mentions to the Java SDK [here](https://github.com/aws/aws-sdk/issues/229).

### Use Case

Be able to use SsmClient.create() instead of SsmClient.builder().endpointOverride(customUri).build() when AWS_ENDPOINT_URL or AWS_ENDPOINT_URL_SSM is set.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.20.156

### JDK version used

openjdk version "17.0.6" 2023-01-17

### Operating System and version

Linux Mint 21.2

**Comment by BalmungSan** [comment]
The compatibility page also mentions this not being supported by the **Java* SDK `v2`: https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html#ss-endpoints-sdk-compat

**Comment by debora-ito** [comment]
Feature request acknowledged. 


Community note: if you want to show your support for this feature, add a 👍 to the description, it helps us with feature prioritization.

**Comment by benvalkin** [comment]
Any progress on this? I am currently testing a Java app using LocalStack and it would be great to be able to switch between the real AWS endpoint and my local testing endpoint without changing any code. This feature is exactly what I am looking for currently and there aren't any other feasible workarounds I can use.

**Comment by mikiTesf** [comment]
Related issue [here](https://github.com/awslabs/aws-sdk-rust/issues/932)

**Comment by MateuszWicherski** [comment]
I am looking forward to it as well, but I have other (somewhat related) question - are there any plans/options to support providing the endpoints at runtime using System properties (similarly to the credentials)? If this is something that is worth a separate issue, then could you point me to the place I can create it (if it is not Java SDK only related)

**Comment by theodiefenthal** [comment]
While @BalmungSan correctly points out that in the referenced compatibility matrix the Java SDK is currently listed as not supporting the feature, another page on the AWS documentation actually states it is supported: https://docs.aws.amazon.com/sdkref/latest/guide/settings-reference.html#JVMSettings

At least for JVM properties, it states that `You can use the following JVM system properties for the AWS SDK for Java and the AWS SDK for Kotlin (targeting the JVM)` and lists `aws.endpointUrl` and `aws.endpointUrl<ServiceName>` as those. However, same as with the environment variables, it actually doesn't work with the aws java sdk. 

Would be awesome to have this feature added soon as (at least for me) I'd finally get rid of all custom configurations when creating a S3 client and can rely on standardized configuration everywhere.

**Comment by matheisco** [comment]
After upgrading to 2.28.4, the JVM system property `aws.endpointUrl` worked for me.

**Comment by debora-ito** [comment]
That's right, thank you @matheisco.

Support for service-specific endpoints with environment variables and system properties was added in Java SDK version [2.28.1](https://github.com/aws/aws-sdk-java-v2/releases/tag/2.28.1). 

We updated the compatibility matrix in the [Service-specific endpoints reference guide](https://docs.aws.amazon.com/sdkref/latest/guide/feature-ss-endpoints.html) to show SDK for Java 2.x = yes.
