### ISSUE TITLE
ReceiveMessageResponse.messages is null when no message is returned by SQS

### ISSUE THREAD

**Issue by vhiairrassary** [aws/aws-sdk-java-v2#454]
Hello,

Not sure if this is the expected behaviour but `ReceiveMessageResponse.messages()` is `null` if no message has been returned but the queue. Otherwise it is a regular instance of a list.

If it expected then it should be documented `ReceiveMessageResponse.java`, otherwise it should be fixed.

Thank you for your help!

**Comment by ochrons** [comment]
Should definitely return an empty list instead of `null`

**Comment by dagnir** [comment]
#529 has been merged. This will be fixed in the next preview release!
