### ISSUE TITLE
credential_process is not implemented

### ISSUE THREAD

**Issue by tyehle** [aws/aws-sdk-java-v2#455]
The SDK is not compatible with an external `credential_process`

## Expected Behavior
Specifying a `credential_process` in the credentials file should allow a user of the sdk to authenticate.

## Current Behavior
The `credential_process` option is ignored.

## Possible Solution
I have some thoughts about how to implement this and I would be happy to work on a PR, I just wanted to make sure that was something that would be useful. If so we can talk more about an implementation.

## Steps to Reproduce
- Put a `credentials_process` line in `~/.aws/credentials`
- Try to build a client with a `ProfileCredentialsProvider`

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-9
* JDK version used: 1.8.0_161

**Comment by dagnir** [comment]
@tyehle Thanks for your interest in the SDK!

Can you explain your use case for supporting `credential_process`?

At a glance, it seems like similar functionality can be achieved by a custom implementation of [`AwsCredentialsProvider`](https://github.com/aws/aws-sdk-java-v2/blob/521015e59b04059ac28ac3b6414231a4513af480/auth/src/main/java/software/amazon/awssdk/auth/credentials/AwsCredentialsProvider.java#L28) that communicates with the external process.

**Comment by tyehle** [comment]
I'm sure that extending `AwsCredentialsProvider` would work. My thoughts were that since the Python API and the CLI support `credential_process` it might be nicer to users to add that functionality to the Java API. Especially since code surrounding `credential_process` could have security consequences.

**Comment by millems** [comment]
We've internally discussed the credentials features that we intend to support in the non-Python/CLI SDKs, and `credential_process` isn't currently one we intend to roll out to the other SDKs at this time. 

+1s on this issue will help show the customer demand for the feature and will enable us to roll out something similar to `credential_process` in the non-Python/CLI SDKs.

**Comment by JathinSanghvi** [comment]
+1

**Comment by ChristianWilkie** [comment]
+1

**Comment by jnewbigin** [comment]
+1

**Comment by zachahuy** [comment]
+1

**Comment by bijaya1** [comment]
+1

**Comment by lorengordon** [comment]
+1 though "something similar" is not what I'm looking for. I want to be able to configure the AWS shared config file, and have every SDK support every option the same way. Anything less feels like it breaks the user experience.

**Comment by jeroenvandijk** [comment]
For what it's worth, I have added support for `credential_process` to a Clojure library that wraps this library https://github.com/mcohen01/amazonica/pull/391 It's currently being evaluated.

**Comment by zachahuy** [comment]
Looks like this has been implemented and works fine for us.

**Comment by thebenwaters** [comment]
@zachahuy where is it? / where do you see it? sdkv2? sdkv3?

**Comment by millems** [comment]
It hasn't been implemented in v2 yet.
