### ISSUE TITLE
[help] Launch Template

### ISSUE THREAD

**Issue by lmittmann** [aws/aws-sdk-java-v2#458]
hi, how do I start an ec2 instance using a launch template?

The ec2 `RunInstancesRequest` in v1 used to have the method `setLaunchConfigurationName(...)`. How can this be done in v2?

**Comment by debora-ito** [comment]
Apologies for the super long delay in response here.

You may have figured this out already, but in V2 you can use the [launchTemplate](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/model/RunInstancesRequest.Builder.html#launchTemplate-software.amazon.awssdk.services.ec2.model.LaunchTemplateSpecification-) method and provide a template name in the launchTemplateSpecification.

**Comment by debora-ito** [comment]
Closing this one. Feel free to reopen if you have any other question.
