### ISSUE TITLE
Support Composable Annotations

### ISSUE THREAD

**Issue by efenderbosch** [aws/aws-sdk-java-v2#463]
```java
@JsonIgnore
@DynamoDBIgnore
public @interface PseudoAttribute {}
```

It would occasionally be nice to write a composite annotation as above. Jackson supports it because ```ElementType.ANNOTATION_TYPE``` is in ```@Target```. Adding this would be relatively easy, but I'm not sure of any drawbacks.

**Comment by millems** [comment]
Tracking this feature request in #35
