### ISSUE TITLE
Enhanced dynamodb java async client batchGet returns empty list unexpectedly.

### ISSUE THREAD

**Issue by bgparkerdev** [aws/aws-sdk-java-v2#4644]
### Describe the bug

When doing a batchGet using the java enhanced dynamodb client if one of the item keys does not exist an empty list is returned.

### Expected Behavior

Every item which has a key that exists should be returned based on the dynamoDB documentation.

### Current Behavior

An empty list is returned if one of the keys doesn't exist. 

### Reproduction Steps

Do a batchGet with the enhanced dynamoDB java client. Provide keys for items that exist and a key for an item that doesn't exist.

### AWS Java SDK version used

2.17

### JDK version used

11

### Operating System and version

Mac OSX

**Comment by bhoradc** [comment]
Hello @bgparkerdev,

Thank you for reporting the issue. Somehow, I am unable to reproduce the described scenario. 

Can you kindly help with the code snippet for it?

Regards, 
Chaitanya

**Comment by bgparkerdev** [comment]
Hi @bhoradc,

I'll try to get a code snippet together later this week.

Thank you.
