### ISSUE TITLE
Avoid null in return values

### ISSUE THREAD

**Issue by jodastephen** [aws/aws-sdk-java-v2#47]
The new v2 API looks to be following most of the recommendations for good Java APIs, which is great. One key thing I've not seen mentioned however is the use of `null`.

Ideally, no method in the SDK should return `null`. The `Optional` class should be used instead. This includes POJOs as well as key classes like `AmazonS3`.

If this proves to be too big a change, at least the key classes like `AmazonS3` should never return `null`.

This particularly affects cases where a remote call is made and the target is not found, eg row not found in Dynamo. At present, some services return `null` while others throw an exception, and this is often not well documented. A consistent use of `Optional` for missing data (or a consistent use of exceptions) would be desirable.

**Comment by millems** [comment]
It might be tricky to standardize the throws-exception vs returns-null between services for existing APIs because we federate that out to the service owners, but returning `Optional<Response>` instead of `null` for services that do so for not-found results makes a lot of sense. Good catch.

**Comment by kiiadi** [comment]
The other complication for having `Optional` on our pojo's based on service models is that (currently) it's considered backwards compatible from a service API perspective to 'relax' the validation on a "required" field. This would result in compile-time backwards incompatibility. See lengthy discussion here https://github.com/aws/aws-sdk-java/issues/965

One possibility is that for Pojo's we could annotate them with meta-data from the service model. This would be subject to change as the service model does but it might be a good indicator.

I agree for classes that we control returning Optional as opposed to null is desirable. I'd like to go further and annotate our methods with `@Nonnull` (or similar) when we know that we're not going to return null. This will aid interoperability with languages like Kotlin.

**Comment by dagnir** [comment]
Partly related is #529, so service responses will not return `null` `List`s (and `Map`s in the future) unless customized to do so.

**Comment by millems** [comment]
We're doing the best we can to fulfill this feature request as we build new features.
