### ISSUE TITLE
DynamoDBException: "Rate exceeded" from DynamoDBStreamsClient

### ISSUE THREAD

**Issue by RyanHoldren** [aws/aws-sdk-java-v2#470]
I am `PUT`ing new items into my DynamoDB table at a rate of about 10 per second. They are going in just fine, so it doesn't look like provisioned throughput is a problem. When I try to stream the new items, however, I am getting this error:

```
java.util.concurrent.CompletionException: software.amazon.awssdk.services.dynamodb.model.DynamoDBException: Rate exceeded (Service: DynamoDBStreamsClient; Status Code: 400; Request ID: LDJJKB4G38BFRI1T6PO7R5R8GNVV4KQNSO5AEMVJF66Q9ASUAAJG)
```

What would cause this? Is there a rate limit for the stream itself?

Thanks,
Ryan

**Comment by switch180** [comment]
Yes, DescribeStream and GetRecords are rate limited. [DescribeStream can be called 10 times per second](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_DescribeStream.html) and GetRecords can be be called at 5 TPS per stream shard or 2MB/s, whichever comes first, but I can't find a reference for it. Although DynamoDB Streams is a separate service from Kinesis Data Streams, KDS's API reference nicely explains the GetRecords limit which Dynamo follows - [Kinesis GetRecords](https://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetRecords.html).

I don't see how this is related to the SDK; can you want to close this issue?

**Comment by zoewangg** [comment]
Closing the issue. Feel free to reopen if you have further questions.
