### ISSUE TITLE
SQS DeleteMessageBatchResponse hasFailed method unexpected response

### ISSUE THREAD

**Issue by hsulich** [aws/aws-sdk-java-v2#4713]
### Describe the bug

After upgrading the aws sdk version from 2.21.16 to 2.21.23, the behavior of the SQS ```DeleteMessageBatchResponse``` ```hasFailed``` method has changed. The version upgrade includes changes to the SQS sdk so it appears to be related.

Previous behavior:
If there were no messages in the batch that were failed to be deleted, ```hasFailed``` returned false.

Current behvaior:
For the same scenario ```hasFailed``` now returns true, even though no messages in the batch were failed to be deleted. Sample log from our application that shows the ```Failed``` list is empty - this log is written when ```hasFailed``` returns true:

```
Failed to delete processed messages: DeleteMessageBatchResponse(Successful=[DeleteMessageBatchResultEntry(Id=3bd265b6-0f3a-47f5-93da-e4262e76469d)], Failed=[])
```

The [javadoc](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/sqs/model/DeleteMessageBatchResponse.html#hasFailed()) confuses me because it says the following:

```
This DOES NOT check that the value is non-empty (for which, you should check the isEmpty() method on the property)
```

However, it seems that before this sdk upgrade, we did not need to check if the list for the ```Failed``` property was non-empty.

### Expected Behavior

```hasFailed``` should return false if there are no messages in the batch that were failed to be deleted.

### Current Behavior

```hasFailed``` now returns true if there are no messages in the batch that were failed to be deleted.

### Reproduction Steps

Perform ```DeleteMessageBatch``` request and call the ```hasFailed``` method for the resulting ```DeleteMessageBatchResponse```.

### AWS Java SDK version used

2.21.23

### JDK version used

17

### Operating System and version

debian11

**Comment by debora-ito** [comment]
@hsulich we are aware of the issue. You're correct, seems like it was an effect of the SQS protocol change.

We are actively working with the SQS team, discussing possible solutions.

**Comment by jppavez** [comment]
Looks like `SendMessageBatchResponse` is also impacted. Also getting `true` when the list of `.failed()` is empty.

**Comment by debora-ito** [comment]
@hsulich @jppavez 

a service-side fix is rolling out now. It should be fixed in `us-west-2`, which region are you all using?

**Comment by hsulich** [comment]
Glad to hear that! I'm using ```us-east-2```

**Comment by debora-ito** [comment]
Just tested locally, the fix didn't hit `us-east-2` yet. 

I don't have an estimate time for the fix, but the deploy is ongoing. We appreciate your patience with this.

**Comment by frederikmartin1337** [comment]
I am using `eu-central-1`. Do you know when the fix is planned to be rolled out in Europe?

**Comment by debora-ito** [comment]
@hsulich @frederikmartin1337 the fix is now available in all regions. Let us know if you still see the issue.
