### ISSUE TITLE
Provided encryption materials do not match information retrieved from the encrypted object

### ISSUE THREAD

**Issue by StanislavKozlovsky** [aws/aws-sdk-java-v2#4716]
### Describe the bug

Hi,
We encountered strange behavior while migrating the s3 encryption client to V2.
We were guided by the following - [s3-encryption-migration](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/s3-encryption-migration.html).

Initial state and dependencies:
We have several buckets with encrypted client data. Two microservices work with these buckets.
Microservice A - puts it in s3 and then encrypts it.
Microservice B - takes it out of s3 and decrypts it.
We use Java 17 and Amazon s3 encryption client V1.

Microservice A configuration aka "writer":

<dependency>
    <groupId>com.amazonaws</groupId>
    <artifactId>aws-java-sdk-bom</artifactId>
    <version>${amazon.aws.api.version}</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>
<amazon.aws.api.version>1.11.587</amazon.aws.api.version>

@Bean
    public AwsRegionProvider awsRegionProvider() {
        return new DefaultAwsRegionProviderChain();
    }

    @Bean
    @Primary
    public AWSCredentialsProvider awsCredentialsProvider() {
        return new DefaultAWSCredentialsProviderChain();
    }

    @Bean
    @Lazy
    public AmazonClient encryptedAmazonClient(
            AWSCredentialsProvider awsCredentialsProvider,
            AwsRegionProvider awsRegionProvider,
            @Value("${fs.kms.cmkId}") String kmsCmkId,
            HealthCheckRegistry healthCheckRegistry) {
        CryptoConfiguration cryptoConfig = new CryptoConfiguration()
                .withAwsKmsRegion(RegionUtils.getRegion(awsRegionProvider.getRegion()));
        EncryptionMaterialsProvider cryptoProvider = new KMSEncryptionMaterialsProvider(kmsCmkId);
        AmazonS3EncryptionClient client = new AmazonS3EncryptionClient(awsCredentialsProvider, cryptoProvider, cryptoConfig);
        return new AmazonClientImpl(client, healthCheckRegistry);
    }
fs.kms.cmkId=alias/prod-fs-user-uploads

// usage
AmazonS3Object fileInfo = amazonClient.upload(amazonBucket, filename, fileContent, contentType);
AmazonS3ObjectContent amazonS3ObjectContent = amazonClient.download(info.getBucket(), info.getKey());

@Override
    public AmazonS3Object upload(String bucket, String key, byte[] data, String contentType) {
        InputStream in = new ByteArrayInputStream(data);

        ObjectMetadata objectMetadata = new ObjectMetadata();
        if (contentType != null) {
            objectMetadata.setContentType(contentType);
        }
        objectMetadata.setContentLength(data.length);
        PutObjectRequest putRequest = new PutObjectRequest(bucket, key, in, objectMetadata);
        PutObjectResult result = client.putObject(putRequest);

        AmazonS3Object response = new AmazonS3Object();
        response.setBucket(bucket);
        response.setKey(key);
        response.setMd5(result.getContentMd5());
        response.setVersion(result.getVersionId());
        response.setSize(data.length);
        return response;
    }

    @Override
    public AmazonS3ObjectContent download(String bucket, String key) {
        LOGGER.info("S3 download started {} {}", bucket, key);
        GetObjectRequest getObjectRequest = new GetObjectRequest(bucket, key);
        S3Object s3Object = client.getObject(getObjectRequest);
        try {
            AmazonS3ObjectContent response = new AmazonS3ObjectContent();
            response.setContentType(s3Object.getObjectMetadata().getContentType());
            response.setContent(IOUtils.toByteArray(s3Object.getObjectContent()));
            LOGGER.info("S3 download completed {} {}", bucket, key);
            return response;
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
Microservice B configuration aka "reader":

<dependency>
       <groupId>com.amazonaws</groupId>
       <artifactId>aws-java-sdk-bom</artifactId>
       <version>${amazon.aws.api.version}</version>
       <type>pom</type>
       <scope>import</scope>
</dependency>
<amazon.aws.api.version>1.11.587</amazon.aws.api.version>

    @Bean
    public AwsRegionProvider awsRegionProvider() {
        return new DefaultAwsRegionProviderChain();
    }

    @Bean
    public AWSCredentialsProvider awsCredentialsProvider() {
        return new DefaultAWSCredentialsProviderChain();
    }

    @Bean
    @Lazy
    public AmazonS3Client amazonClient(
            AWSCredentialsProvider awsCredentialsProvider,
            AwsRegionProvider awsRegionProvider,
            @Value("${fs.kms.cmkId}") String kmsCmkId) {
        CryptoConfiguration cryptoConfig = new CryptoConfiguration()
                .withAwsKmsRegion(RegionUtils.getRegion(awsRegionProvider.getRegion()));

        AmazonS3 client = AmazonS3EncryptionClientBuilder.standard()
                .withCredentials(awsCredentialsProvider)
                .withCryptoConfiguration(cryptoConfig)
                .withEncryptionMaterials(new KMSEncryptionMaterialsProvider(kmsCmkId))
                .build();

        return new AmazonS3Client(client);
    }
fs.kms.cmkId=alias/env-fs-user-uploads

//usage
AmazonS3ObjectContent amazonS3ObjectContent = amazonS3Client.downloadFile(fileInfo.getS3bucket(), fileInfo.getS3key());

public AmazonS3ObjectContent downloadFile(String bucket, String key) {
        log.info("S3 download started {} {}", bucket, key);

        try {
            S3Object s3Object = client.getObject(new GetObjectRequest(bucket, key));

            AmazonS3ObjectContent response = new AmazonS3ObjectContent();
            response.setContentType(s3Object.getObjectMetadata().getContentType());
            response.setContentStream(s3Object.getObjectContent());

            log.info("S3 download completed {} {}", bucket, key);
            return response;
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

When starting migration, the first thing we did: update dependency versions on both microservices.
from
<amazon.aws.api.version>1.11.587</amazon.aws.api.version>
to
<amazon.aws.api.version>1.11.837</amazon.aws.api.version>
with redeploy of course.

After that, we first updated the "reader" client to V2 in this way:

@Bean
@Lazy
public AmazonS3Client amazonClient(AwsRegionProvider awsRegionProvider,
                                   @Value("${fs.kms.cmkId}") String kmsCmkId) {
    EncryptionMaterialsProvider cryptoProvider = new KMSEncryptionMaterialsProvider(kmsCmkId);
    AmazonS3EncryptionV2 client = AmazonS3EncryptionClientV2.encryptionBuilder()
            .withEncryptionMaterialsProvider(cryptoProvider)
            .withCryptoConfiguration(new CryptoConfigurationV2()
                    // The following setting allows the client to read V1 encrypted objects
                    .withCryptoMode(CryptoMode.AuthenticatedEncryption)
                    .withAwsKmsRegion(RegionUtils.getRegion(awsRegionProvider.getRegion())))
            .build();

    return new AmazonS3Client(client);
}
After that, we redeployed the reader microservice and started testing in the test environment.
According to the documentation, CryptoMode.AuthenticatedEncryption can read V1 and V2 encrypted objects, but we encountered a strange error for new encrypted files:
Provided encryption materials do not match information retrieved from the encrypted object
Although old historical files are decrypted correctly.

During the investigation we found that the error comes from ContentCryptoMaterial.validateMaterialsForDecrypt.

private static void validateMaterialsForDecrypt(EncryptionMaterials materials, Map<String, String> mergedMatDesc,
                                                    CryptoMode cryptoMode, InternalKeyWrapAlgorithm keyWrapAlgorithm) {
        if (materials == null) {
            throw new SdkClientException("Unable to retrieve the client encryption materials");
        }
        if (keyWrapAlgorithm == null || !keyWrapAlgorithm.isKMS()) {
            return;
        }
        if (!keyWrapAlgorithm.isV1Algorithm()
            && KMSMaterialsHandler.isValidV2Description(materials.getMaterialsDescription(), mergedMatDesc)) {
            return;
        }
        boolean isValidV1MaterialsDescription =
            KMSMaterialsHandler.isValidV1Description(materials.getMaterialsDescription(), mergedMatDesc);
        if (keyWrapAlgorithm.isV1Algorithm() && isValidV1MaterialsDescription) {
            if (CryptoMode.AuthenticatedEncryption.equals(cryptoMode)) {
                return;
            } else {
                throw new IllegalStateException("A previous version of the client may have been used to encrypt " +
                                                        "key via KMS. Use crypto mode " +
                                                        CryptoMode.AuthenticatedEncryption + " to decrypt object.");
            }
        }
        throw new IllegalStateException("Provided encryption materials do not match information" +
                                                " retrieved from the encrypted object");
    }
KMSMaterialsHandler.isValidV1Description(materials.getMaterialsDescription(), mergedMatDesc) returns false

public static boolean isValidV1Description(Map<String, String> configuredMatDesc, Map<String, String> kmsMatDesc) {
        return configuredMatDesc.equals(kmsMatDesc);
    }
Because compares:
{"kms_cmk_id":"alias/env-fs-user-uploads"} with {kms_cmk_id=arn:aws:kms:eu-west-1:accountId:key/keyId}
As for old files both keys are "alias/env-fs-user-uploads".
We tried few manipulations with changing configured cmk id.(used full arn key and keyId).
So if we leave alias as it is - we can't decrypt new files, but if we are using full arn key - then old files couldn't be decrypted without that error.

Could you please have a look and assist?
Since we did not find a similar problem on the forums, perhaps we missed something.
Thanks

### Expected Behavior

V2 client can decrypt both objects

### Current Behavior

Old historical files are decrypted with error: Provided encryption materials do not match information retrieved from the encrypted object

### Reproduction Steps

see describe the bug section

### Possible Solution

idk

### AWS Java SDK version used

1.11.837

### JDK version used

java version "17.0.7" 2023-04-18 LTS Java(TM) SE Runtime Environment (build 17.0.7+8-LTS-224) Java HotSpot(TM) 64-Bit Server VM (build 17.0.7+8-LTS-224, mixed mode, sharing)

### Operating System and version

docker container

**Comment by debora-ito** [comment]
@StanislavKozlovsky hi, I'm sorry for the super long silence. Have you figured out the issue or are you still blocked?

> Because compares:
> {"kms_cmk_id":"alias/env-fs-user-uploads"} with {kms_cmk_id=arn:aws:kms:eu-west-1:accountId:key/keyId}
> As for old files both keys are "alias/env-fs-user-uploads".
We tried few manipulations with changing configured cmk id.(used full arn key and keyId).
So if we leave alias as it is - we can't decrypt new files, but if we are using full arn key - then old files couldn't be decrypted without that error.

I found a report in StackOverflow [here](https://stackoverflow.com/questions/73615817/java-aws-s3-encryption-client-cant-decrypt-file-with-v2-client-but-v1-client) hitting the same issue when KMSEncryptionMaterialsProvider is used. 

Even thought this looks like a bug in the AmazonS3EncryptionV2, Java SDK 1.x is now in [Maintenance Mode](https://aws.amazon.com/blogs/developer/announcing-end-of-support-for-aws-sdk-for-java-v1-x-on-december-31-2025/) so this won't be fixed. The recommendation is migrate to Amazon S3 Encryption Client v3 (which uses the Java SDK 2.x) and if you experience the same issue than this still has a chance to be fixed since the S3 Encryption Client v3 is fully supported. The Amazon S3 Encryption Client is a [standalone library](https://docs.aws.amazon.com/amazon-s3-encryption-client/latest/developerguide/what-is-s3-encryption-client.html) now, and the Developer documentation has a migration guide: https://docs.aws.amazon.com/amazon-s3-encryption-client/latest/developerguide/java-v3-migration.html

Let us know if you have questions.
