### ISSUE TITLE
S3AsyncClient putObject for InputStream does not write content to created object

### ISSUE THREAD

**Issue by adityajee** [aws/aws-sdk-java-v2#4722]
### Describe the bug

I tried using the example in the SDK (https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/s3/src/main/java/com/example/s3/async/PutObjectFromStreamAsync.java) for uploading InputStream to AWS. The code works without any exception, the object is created in the bucket but the content, which in this case is a test string does not get written in it and the size of the object is still 0B. Due to this the returned eTag and the md5 of the test string did not match.

My code snippet - 
```
            String key = "nov13.txt";
            String randomString = "AAAAAA";
            logger.info("random string to upload: {}: length={}", randomString, randomString.length());

            ByteArrayInputStream inputStream = new ByteArrayInputStream(randomString.getBytes());
            BlockingInputStreamAsyncRequestBody body = AsyncRequestBody.forBlockingInputStream(6L);
            CompletableFuture<PutObjectResponse> responseFuture = adapter.s3AsyncClient.putObject(r -> r.bucket(adapter.bucketName).key(key), body);
            body.writeInputStream(inputStream);
            PutObjectResponse response = null; // Wait for the response.
            response = responseFuture.get();
            logger.info("Object {} uploaded to bucket {}.", key, adapter.bucketName);
            logger.info(String.valueOf(response));
```

I also tried providing the requestBody to the putObject instead of using `ByteArrayInputStream` - 
`AsyncRequestBody body = AsyncRequestBody.fromInputStream(inputStream, 6L, Executors.newSingleThreadExecutor());`

S3AsyncClient has been configured as follows:
```
s3CrtAsyncClientBuilder = S3AsyncClient.crtBuilder()
                                                   .httpConfiguration(httpConfiguration)
                                                   .credentialsProvider(credentialsProvider)
                                                   .forcePathStyle(pathStyleAccess)
                                                   .region(regionType)
                                                   .minimumPartSizeInBytes(CLOUD_ADAPTER_MULTIPART_COPY_PARTSIZE)
                                                   .thresholdInBytes(CLOUD_ADAPTER_MULTIPART_COPY_THRESHOLD);
s3AsyncClient = s3CrtAsyncClientBuilder.build()
```

Same issue was observed with TransferManager using this s3AsyncClient and used the example - https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/s3/src/main/java/com/example/s3/transfermanager/UploadStream.java

Another thing to note is that in the given examples, the ByteArrayInputStream is initialized with a null 
`BlockingInputStreamAsyncRequestBody body = AsyncRequestBody.forBlockingInputStream(null);`
but this fails and causes the following IllegalStateException
```
java.lang.IllegalStateException: The service request was not made within 10 seconds of doBlockingWrite being invoked. Make sure to invoke the service request BEFORE invoking doBlockingWrite if your caller is single-threaded.
	at software.amazon.awssdk.core.async.BlockingInputStreamAsyncRequestBody.waitForSubscriptionIfNeeded(BlockingInputStreamAsyncRequestBody.java:110) ~[sdk-core-2.20.146.jar:na]
	at software.amazon.awssdk.core.async.BlockingInputStreamAsyncRequestBody.writeInputStream(BlockingInputStreamAsyncRequestBody.java:74) ~[sdk-core-2.20.146.jar:na]
```

### Expected Behavior

The putObject should correctly create the object and write the contents in it. In case there is an exception, it should be propagated instead of silently failing with the wrong values.

### Current Behavior

The object is created in the bucket but the content is not written in it and the request completes with a success.

![image](https://github.com/aws/aws-sdk-java-v2/assets/97121487/18086531-7387-465c-b30a-9cd64ecdfced)

### Reproduction Steps

Create or read an inputStream and try uploading pushing it to AWS as mentioned in example - 

https://github.com/awsdocs/aws-doc-sdk-examples/blob/main/javav2/example_code/s3/src/main/java/com/example/s3/async/PutObjectFromStreamAsync.java

### AWS Java SDK version used

2.20.146

### JDK version used

openjdk version "1.8.0_302"

### Operating System and version

Ubuntu 22.04.3

**Comment by debora-ito** [comment]
@adityajee apologies for the long delay in response.

I can't reproduce the issue. My upload is successful when I run the sample code you provided, the only difference is I'm using a default S3 CRT AsyncClient with no custom attributes.

Can you share the CRT debug logs with the error?
Instructions can be found in the [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html).

**Comment by debora-ito** [comment]
I also tested with a newer version of the SDK, can you try upgrading the version? The latest version is `2.28.8` as of today.
