### ISSUE TITLE
DAX Support

### ISSUE THREAD

**Issue by madgnome** [aws/aws-sdk-java-v2#473]
As a DynamoDB user I would like to use DAX with this client instead of https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.html

**Comment by dagnir** [comment]
Hi @madgnome, DAX is currently not part of the SDK because it uses a binary protocol directly over TCP rather HTTP.

I think it would be really cool to support DAX in the SDK but given that, it would require some work.

**Comment by ielkhalloufi** [comment]
What is the status of this issue? The "software.amazon.awssdk.dynamodb" artifact is already released, as of now "2.0.6". Which is completely non-blocking, the DAX client is tightly coupled with the 1.11 version of the sdk dynamodb.

**Comment by grelland** [comment]
Any updates on this? Any way to reach out to the DAX team with this feature request?

**Comment by lopun** [comment]
Any updates on this issue? I gave up migrating v2 code to v1 just to use DAX 😢

**Comment by millems** [comment]
We've forwarded this feedback to the DAX team (they were also already aware of it). We understand it's a headache.

**Comment by lucaswiechmann** [comment]
Any updates on this issue?

**Comment by millems** [comment]
Sorry, no updates.

**Comment by bagipriyank** [comment]
any updates?

**Comment by xavierKress** [comment]
Hi, I have the same issue. Forced to stay in v1 just because of dax :(

**Comment by millems** [comment]
Sorry, still no updates.

**Comment by bitnitesh** [comment]
Hi @millems ,
Does the DAX(dax.2.15.5.jar) provided can be used as DAX Client for performing DB Operation and does it supports by the AWS SDK v2.
I don't see any api returning DynamoDbClient instance similar to V1 version(https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-java.TryDaxHelper.html).
Please updates.

Thanks,
Nitesh

**Comment by millems** [comment]
DAX does not support 'implementing' the 2.x interfaces at this time, sorry.

**Comment by longravuth** [comment]
Any plan when Dax client can support Async V2 library? This limits us from being able to use SDK V2 and utilize reactive programming.

**Comment by rehevkor5** [comment]
This means that issues not being fixed in v1 such as https://github.com/aws/aws-sdk-java/issues/1893 still persist, sadly. Is DAX being deprecated?

**Comment by millems** [comment]
We are in communication with the DAX team, and are very aware that this is a blocker to your ability to use 2.x for DAX's data plane. We promise to update this issue as soon as we have something that we can share.

**Comment by Bolshem** [comment]
Is there any work going on this issue? Should we wait for SDK2 support or switch to SDK1?

**Comment by sken77** [comment]
what part is not supported?

i see that there is a client

https://github.com/aws/aws-sdk-java-v2/blob/caab8b95bc7f5a9bbd9b3d5ee979bb082873f42d/docs/LaunchChangelog.md#63-client-names

does this doesnt work if i try to use it?

**Comment by debora-ito** [comment]
@sken77 the DaxClient listed in the changelog is the service client to manage DAX clusters - https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/dax/DaxClient.html.

This issue is regarding the standalone `amazon-dax-client`, used to make calls against DAX clusters: http://dax-sdk.s3-website-us-west-2.amazonaws.com/

**Comment by dinesh-rajaveeran** [comment]
Is there an update on this ?

**Comment by millems** [comment]
The DAX team has released support for the AWS SDK for Java 2.x. https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.client.run-application-java.html Please give it a try!
