### ISSUE TITLE
Equivalent of AmazonS3 from sdk v1

### ISSUE THREAD

**Issue by NathanEckert** [aws/aws-sdk-java-v2#4756]
### Describe the issue

I am looking for the replacement of the interface `AmazonS3` from the sdk v1.
I did not find any mention of it in the [changelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#4-service-changes) nor in the migration guide 

For example, I want to migrate the following code:

```java
public class MyClass {

    private final AmazonS3 client;
    private final String bucket;
    private final String name;

    public MyClass(final AmazonS3 client, final String bucket, final String name) {
        super(name, bucket);
        this.client = client;
    }

    public boolean exists() {
        return this.client.doesObjectExist(this.bucket, this.name);
    }

    public void delete() {
        this.client.deleteObject(this.bucket, this.name);
    }

     protected void doGetEntity() {
        final S3Object s3Object = this.client.getObject(new GetObjectRequest(this.bucket, this.name));
        ...
    }

    public Date getLastModifiedTime() {
        if (exists()) {
            return this.client.getObjectMetadata(this.bucket, this.name).getLastModified();
        } else {
            return null;
        }
    }
}
```

Thanks in advance !

### Links

- https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#4-service-changes
- https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/migration-whats-different.html

**Comment by debora-ito** [comment]
This is how you create a S3Client in v2: 

Sync client:

```java
    S3Client s3Client = S3Client.builder()
                    .region(Region.US_WEST_2)
                    .build();
```

Async client:
```java
    S3AsyncClient s3AsyncClient = S3AsyncClient.builder()
                .region(Region.US_WEST_2)
                .build();
```
Note that Java SDK v2 S3 clients are auto-generated from the service model, so some v1 APIs are not present in v2, like `DoesObjectExist` and `GetObjectMetadata`. You can use [`HeadObject`](https://docs.aws.amazon.com/AmazonS3/latest/API/API_HeadObject.html) as an alternative (HeadObject is what the SDK calls in v1).

Check our [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration.html) for more information on the HTTP Clients and how to customize them.
