### ISSUE TITLE
UpdateItemEnhancedRequest ignoreNulls not Working for Nested Beans

### ISSUE THREAD

**Issue by JustinMarinelli** [aws/aws-sdk-java-v2#4758]
### Describe the bug

I have a DynamoDbBean with a nested DynamoDbBean property.

I would like to update a single field in the inner bean without modifying any of the other properties in the outer bean record or its inner bean section. I'm unable to do this using an `UpdateItemEnhancedRequest`.

Despite using `ignoreNulls(true)` on my `UpdateItemEnhancedRequest` and `@DynamoDbIgnoreNulls`, I still see null fields in the inner bean NOT being ignored when the item is updated in the database.

### Expected Behavior

Null fields in the inner bean should be ignored and only non-null fields should be updated.

### Current Behavior

Null fields in the inner bean are NOT ignored and are written to the database.

### Reproduction Steps

```
@DynamoDbBean
public class OuterBean {
    private String Id;
    private InnerBean innerBean;

    public OuterBean() {
        
    }

    @DynamoDbPartitionKey
    @DynamoDbAttribute(value = "Id")
    public String getId() {
        return Id;
    }

    public void setId(String Id) {
        this.Id = Id;
    }

    @DynamoDbIgnoreNulls
    @DynamoDbAttribute(value = "innerBean")
    public InnerBean getInnerBean() {
        return innerBean;
    }

    public void setInnerBean(@Nullable InnerBean innerBean) {
        this.innerBean = innerBean;
    }
}

@DynamoDbBean
public class InnerBean {
    private Integer field1;
    private Integer field2;

    public Integer getField1() {
        return field1;
    }

    public void setField1(Integer field1) {
        this.field1 = field1;
    }

    public Integer getField2() {
        return field2;
    }

    public void setField2(Integer field2) {
        this.field2 = field2;
    }
}
```
```
        DynamoDbEnhancedClient client = DynamoDbEnhancedClient.builder()
                .dynamoDbClient(
                        DynamoDbClient.builder()
                                .region(Region.of("us-east-1"))
                                .credentialsProvider(ProfileCredentialsProvider.create())
                                .build())
                .build();

        DynamoDbTable<OuterBean> table = client.table(caseTableName, TableSchema.fromBean(OuterBean.class));

        OuterBean outerBean = new OuterBean();
        outerBean.setId("1");

        InnerBean innerBean = new InnerBean();
        innearBean.setField1(1);
        // Notice field2 is null

        outerBean.setInnerBean(innerBean);

        table.updateItem(
                UpdateItemEnhancedRequest
                        .builder(OuterBean.class)
                        .item(outerBean)
                        .ignoreNulls(true)
                        .build()
        );
```

### AWS Java SDK version used

2.20.156

### JDK version used

17

### Operating System and version

Windows Server 2016 Standard Edition

**Comment by WPJustinM** [comment]
@debora-ito Commenting just to make sure this issue has been noticed by the team.

**Comment by JustinMarinelli** [comment]
@debora-ito Commenting just to make sure the team has noticed this issue.

**Comment by JustinMarinelli** [comment]
@debora-ito Any updates here?

**Comment by debora-ito** [comment]
Hi @JustinMarinelli I apologize for the long long silence in here.

I just ran you code snippet in my local machine and I couldn't reproduce the issue, this is entry that gets added to DynamoDB :-

| Id (String) | innerBean |
| --- | --- |
| 1 | { "field1" : { "N": "1" } } |

Have you checked the [verbose wirelogs](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) to see exactly how the UpdateExpression is being sent in the request?

**Comment by isururandika** [comment]
@debora-ito Hello, I have an issue and that it pretty much same issue mentioned in this thread and thought of adding my query would be appropriate.

I have the model structure same as mentioned in the above issue (Outerbean & InnerBean) and within the InnerBean i have several attributes. 

Steps to reproduce the issue -

1. I created a record using DynamoDbAsyncTable putItem method and it has all the OuterBean & InnerBean attributes. 
2. When I tried to update the same record like below

`DynamoDbAsyncTable<T> table = dbEnhancedAsyncClient.table(tableName, TableSchema.fromBean(modelClass));
    return table
        .updateItem(UpdateItemEnhancedRequest.builder(modelClass).item(item).ignoreNulls(Boolean.TRUE).build());`

It will update all the OuterBean attributes without any issue but when I looked at the InnerBean only the provided attributes were there within the record, other attributes were removed. 

Could you please help me on this ??
