### ISSUE TITLE
Describe vpc attributes in ec2

### ISSUE THREAD

**Issue by erotallgeese** [aws/aws-sdk-java-v2#477]
## Expected Behavior
Receive vpc attributes normally

## Current Behavior
Calling describeVpcAttribute, it would raise an exception:
Unable to unmarshall response (Encountered unexpected event: <['http://ec2.amazonaws.com/doc/2016-11-15/']::value>). Response Code: 200, Response Text: OK

## Possible Solution
I have try calling another similar api, modifyVpcAttribute and it works well.

## Steps to Reproduce (for bugs)
Following is my code snippets:
``` java
DescribeVpcAttributeRequest request = DescribeVpcAttributeRequest.builder()
                                                    .vpcId(vpcId)
                                                    .attribute(VpcAttributeName.ENABLE_DNS_SUPPORT)
                                                    .build();
DescribeVpcAttributeResponse response = null;
String errMsg = "";

try {
     response = ec2Client.describeVpcAttribute(request);
}
catch(SdkException ex) {
    errMsg = "describeVpcAttribute fail:" + ex.getMessage();
    System.out.println(errMsg);
}
```

## Context
I hope i could be able to get and set the vpc attributes for dns functions.

## Your Environment

* AWS Java SDK version used: 2.0.0-preview-9
* JDK version used: 1.8.0_162
* Operating System and version: Debian GNU/Linux 9

**Comment by dagnir** [comment]
@erotallgeese We release `2.0.0-preview-10` recently. Is this still an issue with that version?

**Comment by erotallgeese** [comment]
Thanks your hard work.
I have update from preview 9 to 10, but it's still not work with same error message.

**Comment by zoewangg** [comment]
Tested with current code base(the latest commit 707ced821ef1c3e2bf52597bc4cfc99fd9d8e61b) and verified `ec2.describeVpcAttribute` is working.

We will let you know once the next release is out.

**Comment by zoewangg** [comment]
Please try with `preview-13`.  Going to close the issue and feel free to reopen if issue occurs.
