### ISSUE TITLE
Support immutable classes in DynamoDbMapper

### ISSUE THREAD

**Issue by cjkent** [aws/aws-sdk-java-v2#48]
`DynamoDbMapper` requires all mapped classes to be mutable. Immutable domain objects are increasingly the norm in Java, and using `DynamoDbMapper` means creating mutable duplicates of all domain objects or giving up on the benefits of immutability.

**Comment by millems** [comment]
+1 

Do you mind migrating this suggestion to our dynamo DB mapper refactor issue? https://github.com/aws/aws-sdk-java-v2/issues/35

We haven't really changed the mapper yet for V2, but we intend to. Suggestions like these give us a good new-feature foundation when we take on that task.

**Comment by gpolaert** [comment]
+1

**Comment by cjkent** [comment]
@millems done

**Comment by millems** [comment]
@cjkent Thank you!

**Comment by millems** [comment]
Closing this in favor of https://github.com/aws/aws-sdk-java-v2/issues/35

**Comment by OndraZizka** [comment]
Is there any chance that DynamoDbMapper could get this feature back in SDK 1.x? It's not that big change, just use constructor instead of a setter. If I coded it, could that get in?

**Comment by OndraZizka** [comment]
I have one more idea. I need this for Kotlin's data classes. And actually, I could add the setters, which would call copy(), but the unmapper would then have to replace the reference of the object with what it would receive from the setter call. That would be even easier implementation.

**Comment by bmaizels** [comment]
Hi @OndraZizka , thanks for your suggestions and feedback. At this time we're not considering any significant feature requests for the DynamoDBMapper in the v1 SDK (even customer submitted PRs, as there is still a cost and risk associated with these for us). We would encourage customers to upgrade to the enhanced client in the v2 SDK if it is possible for them to do so as that is where we want to focus our resources and energy.
