### ISSUE TITLE
ca-west-1 region is not in the service metadata

### ISSUE THREAD

**Issue by daeho-ro** [aws/aws-sdk-java-v2#4805]
### Describe the bug

Simple test for new region `ca-west-1` is failed.
```
        String region = "ca-west-1";
        Assert.assertTrue(Ec2Client.serviceMetadata().regions().contains(Region.of(region)));
```

I suspect that the service metadata for the ec2 is not updated well.
Maybe the new region should be added into the file, endpoints.json right?

### Expected Behavior

Since the new region, `ca-west-1` is announced, the region can be found from the service metadata.

### Current Behavior

I cannot find the new region `ca-west-1` from the service metadata.

### Reproduction Steps

```
        String region = "ca-west-1";
        Assert.assertTrue(Ec2Client.serviceMetadata().regions().contains(Region.of(region)));
```

FAILED.

### AWS Java SDK version used

2.22.9

### JDK version used

17

### Operating System and version

M1

**Comment by debora-ito** [comment]
> Maybe the new region should be added into the file, endpoints.json right?

Yup, that's right. I'll raise this issue to the EC2 team, they need to add `ca-west-1` to their list of supported regions. Thank you for reaching out.

**Comment by daeho-ro** [comment]
I have checked the service metadata for ec2 only, but it is better to check the metadata for other services, too.

**Comment by debora-ito** [comment]
@daeho-ro starting in SDK version `2.24.5`, ec2 metadata now lists the ca-west-1 region. Thank you for bringing this up.

**Comment by daeho-ro** [comment]
It is working in my test code. Thanks!
