### ISSUE TITLE
Expose client-level context params on service client configuration

### ISSUE THREAD

**Issue by shiva958** [aws/aws-sdk-java-v2#4811]
### Describe the feature

Currently, while configuring plugins on AWS service clients only service client configuration is passed onto the plugin. However, having access to the client-level context params available as part of service client configuration will simplify and expand the use cases of plugins.

### Use Case

As an example, Our team is implementing a plugin that can be attached to the AWS S3 Clients. S3 Clients today support cross-region setting that is only available as part of client-context params. We want our plugin to be able to support cross-region access as well. Since, the plugin does not have access to the client-context params, our approach currently is to have the customers turn-on cross-region setting on the plugin along with the setting on the S3Client. This approach might cause unexpected errors if the customers forgets to turn-on the setting on one of the **S3Client or the plugin** but not on the other. However, if the plugin has access to the client-context params, we can drop the cross-region setting on the plugin by referencing the configuration on the S3 Client thereby reducing unexpected behaviors.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.22.3

### JDK version used

1.8

### Operating System and version

MacOS Sonoma 14.2.1

**Comment by debora-ito** [comment]
@shiva958 thank you for reaching out. We've added a task to our backlog.

**Comment by debora-ito** [comment]
Fixed via PR https://github.com/aws/aws-sdk-java-v2/pull/4834, released in SDK version 2.23.7.
