### ISSUE TITLE
Allow to override FUTURE_COMPLETION_EXECUTOR for S3Crt client

### ISSUE THREAD

**Issue by scrocquesel** [aws/aws-sdk-java-v2#4841]
### Describe the feature

`S3AsyncClientBuilder` allows to configure the executor used to complete future. This configuration is not exposed on the `S3CrtAsyncClientBuilder`

### Use Case

In a quarkus application, futures are executed on a thread with a different TCCL and I encounter class not found exception when CDI proxy tries to create the real object from within the default `sdk-async-response` executor.

### Proposed Solution

Expose `advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR, executor)` somewhere in `S3CrtAsyncClientBuilder`.

### Other Information

I think that `SCHEDULED_EXECUTOR_SERVICE` should also be configured.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.23.6

### JDK version used

17

### Operating System and version

linux

**Comment by geniusit** [comment]
I notice a huge performance benefit when using the injected quarkus ManagedExecutor : 

```java
.asyncConfiguration(builder -> builder.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR, managedExecutor))
```

**Comment by scrocquesel** [comment]
> I notice a huge performance benefit when using the injected quarkus ManagedExecutor for the DynamoDbAsyncClient (Netty):
> 
> ```java
> .asyncConfiguration(builder -> builder.advancedOption(SdkAdvancedAsyncClientOption.FUTURE_COMPLETION_EXECUTOR, managedExecutor))
> ```

Thank you for the feedback. I guess, we could expect the same boost with S3Crt.
BTW, In Quarkus application, if you'd use the [Quarkus Amazon extension](https://github.com/quarkiverse/quarkus-amazon-services), this is the default behavior when injecting clients produced by the extension for netty and crt http based async clients. Netty clients will also reuse the Netty EventLoop used by Vert.x if available to avoid having multiple EventLoop competiting the same cpu resources.

**Comment by scrocquesel** [comment]
@zoewangg Too bad you didn't add SCHEDULED_EXECUTOR_SERVICE as suggested in other information. Should I open another issue ?

**Comment by zoewangg** [comment]
@scrocquesel ah, sorry, I missed that. `SCHEDULED_EXECUTOR_SERVICE` is not directly used in S3 CRT client though. It's used in retry layer and waiters, and retry in S3 CRT client is handled in the native CRT library.

**Comment by scrocquesel** [comment]
> @scrocquesel ah, sorry, I missed that. `SCHEDULED_EXECUTOR_SERVICE` is not directly used in S3 CRT client though. It's used in retry layer and waiters, and retry in S3 CRT client is handled in the native CRT library.

Ok, I will close the issue I just opened then. Thank you for the feedback
