### ISSUE TITLE
AWS SDK STS doesn't autorefresh cross account token

### ISSUE THREAD

**Issue by VelDeveloper** [aws/aws-sdk-java-v2#4844]
### Describe the bug

I am using spring-boot and the latest version of aws-java-sdk. My application is trying to access DynamoDB which is in a different account so I am using STS assumeRoleRequest to connect to the account. Everything is working fine but the STS token is valid only for a few minutes (max 30 minutes) after that we started getting the Token expired exception.  If it is in the same account the STS default StsAssumeRoleCredentialsProvider takes care of the autoRefresh token where as it is working for cross account. Please find the below code for your reference,

### Expected Behavior

Autorefresh token should work out of the box for cross account like the same account.

### Current Behavior

Autorefresh token should work out of the box for cross accounts like same account but it doesn't.

### Reproduction Steps

```java
  @Bean
  @ConditionalOnProperty(name = "app.common.roleArn")
  public Credentials stsCredentials() {
    StsClient stsClient = StsClient.create();
    AssumeRoleRequest assumeRoleRequest =
        AssumeRoleRequest.builder()
            .roleArn(propertiesAccessor.getCommonProperty().getRoleArn())
            .roleSessionName("CrossAccountDynamoRole")
            .build();
    AssumeRoleResponse assumeRoleResponse = stsClient.assumeRole(assumeRoleRequest);
    return assumeRoleResponse.credentials();
  }
```

```java
 @Bean
  @Profile("!local & !test")
  public DynamoDbClient dynamoDbClient() {
    if (Objects.nonNull(stsCredentials)) {
      AwsSessionCredentials awsCredentials =
          AwsSessionCredentials.create(
              stsCredentials.accessKeyId(),
              stsCredentials.secretAccessKey(),
              stsCredentials.sessionToken());
      return DynamoDbClient.builder()
          .region(Region.of(propertiesLoader.getProperty("aws.region")))
          .credentialsProvider(StaticCredentialsProvider.create(awsCredentials))
          .build();
    }
    return DynamoDbClient.create();
  }

  @Bean
  @Profile("!local & !test")
  public DynamoDbEnhancedClient dynamoDbEnhancedClient() {
    return DynamoDbEnhancedClient.builder().dynamoDbClient(dynamoDbClient()).build();
  }
```

### AWS Java SDK version used

2.20.65

### JDK version used

17

### Operating System and version

AWS EKS linux

**Comment by debora-ito** [comment]
@VelDeveloper 

`StsAssumeRoleCredentialsProvider` should work with cross account role arns too, is there any particular reason is not working? You can set a custom AssumeRoleRequest, something like:

```java
        AssumeRoleRequest assumeRoleRequest = AssumeRoleRequest.builder()
                .roleArn(ROLE_ARN)
                .roleSessionName("CrossAccountDynamoRole")
                .build();

        StsAssumeRoleCredentialsProvider provider = StsAssumeRoleCredentialsProvider.builder()
                .refreshRequest(assumeRoleRequest)
                .build();

        DynamoDbClient client = DynamoDbClient.builder().credentialsProvider(provider).build();
```

If you can't use the `StsAssumeRoleCredentialsProvider` like showed in the snippet above and need to use the low-level STS AssumeRole API, you'll need to write your own auto refresh logic.

**Comment by kalyc** [comment]
Hi I am facing similar issue. I have used StsAssumeRoleCredentialsProvider on cross account role but the access token doesn't appear to be auto-refreshing.  This is trying to access cross account s3 bucket.


```

     StsClient stsClient = StsClient.builder().region(Region.of(jobProperties.getAwsRegion())).build();
     
    AssumeRoleRequest assumeRoleRequest = AssumeRoleRequest.builder()
                .roleArn(ROLE_ARN)
                .roleSessionName("name")
               .durationSeconds(3600)
                .build();

        StsAssumeRoleCredentialsProvider provider = StsAssumeRoleCredentialsProvider.builder()
            .stsClient(stsClient)
            .refreshRequest(assumeRoleRequest)
            .build();

```
