### ISSUE TITLE
remove final from class ApacheHttpClient 

### ISSUE THREAD

**Issue by yeguangsuixing** [aws/aws-sdk-java-v2#4875]
### Describe the feature

we want to create ourselves HttpClientBuilder, which overrides the decorateMainExec like below
```java
public class TraceHttpClientBuilder extends HttpClientBuilder {
  private Tracer tracer;

  public ClientExecChain decorateMainExec(ClientExecChain exec) {
    return new TraceMainExec(this.tracer, exec);
  }
}
```
Is it possible that remove final from class ApacheHttpClient and change createClient method from private to protected? And, so that we can create a subclass extends ApacheHttpClient and overrides createClient.

```java
public final class ApacheHttpClient implements SdkHttpClient {
  // ...... 
  private ConnectionManagerAwareHttpClient createClient(DefaultBuilder builder, AttributeMap standardOptions) {
    //......
    HttpClientBuilder builder = HttpClients.custom(); // we will only change this statement
    //......
  }
}
```

### Use Case

we will create myself TraceHttpClient extends ApacheHttpClient, and override the createClient method to create myself HttpClientBuilder

### Acknowledgements

- [x] I may be able to implement this feature request ([PR](https://github.com/aws/aws-sdk-java-v2/pull/4876))
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.23.14

### JDK version used

1.8

### Operating System and version

any

**Comment by viditpandey06** [comment]
`public class ApacheHttpClient implements SdkHttpClient {

  protected ConnectionManagerAwareHttpClient createClient(DefaultBuilder builder, AttributeMap standardOptions) {
    //......
    HttpClientBuilder builder = HttpClients.custom(); // this statement can be overridden in subclasses

  }
}
`

**Comment by debora-ito** [comment]
@yeguangsuixing all implementations of SdkHttpClient are final for a reason, we want to make sure their behavior remains unchanged and works as we expect. We don't have plans to remove 'final'.
