### ISSUE TITLE
 software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Write timed out(short issue description)

### ISSUE THREAD

**Issue by mubasherhussain9d** [aws/aws-sdk-java-v2#4894]
### Describe the bug

when i upload the small file upto the 8MB it uploads in the bucket correctly but when i upload a little bit large file it throws an exception  software.amazon.awssdk.core.exception.SdkClientException: Unable to execute HTTP request: Write timed out.
i am using S3TransferManager with S3AsyncClient if i give the writeTimeout(Duration.ofMinutes(1)) inside NettyNioAsyncHttpClient  then it upload file of size upto 20MB but this is not the proper solution what if user connect with slow internet large file in GBs????

` val s3Client = S3AsyncClient.builder()
            .region(Constants.REGION)
//            .httpClient(
//                NettyNioAsyncHttpClient.builder()
//                    .connectionTimeToLive(Duration.ofMinutes(8))
////                    .readTimeout(Duration.ofMinutes(1))
//                    .writeTimeout(Duration.ofMinutes(4))
////                    .connectionAcquisitionTimeout()
////                    .connectionTimeout(Duration.ofMinutes(1))
//                    .maxConcurrency(64)
//                    .build()
//            )
            .endpointOverride(URI(Constants.ENDPOINT))
            .credentialsProvider(credentials)
            .build()

        val transferListener = object : TransferListener {
            override fun transferInitiated(context: TransferListener.Context.TransferInitiated?) {
                super.transferInitiated(context)
                Log.e(TAG, "transferInitiated: total bytes ${humanReadableByteCountSI(context?.progressSnapshot()?.totalBytes()?.asLong!!)}")
            }

            override fun bytesTransferred(context: TransferListener.Context.BytesTransferred?) {
                super.bytesTransferred(context)
                Log.e(TAG, "bytesTransferred: ${humanReadableByteCountSI(context?.progressSnapshot()?.transferredBytes()!!)} | ${humanReadableByteCountSI(context.progressSnapshot()?.remainingBytes()?.asLong!!)}")
            }

            override fun transferComplete(context: TransferListener.Context.TransferComplete?) {
                super.transferComplete(context)
                Log.e(TAG, "transferComplete: ")
                binding.mcvProgress.hide()
                requireActivity().showToast("true")
            }

            override fun transferFailed(context: TransferListener.Context.TransferFailed?) {
                super.transferFailed(context)
                Log.e(TAG, "transferFailed: ${context?.exception()}")
                binding.mcvProgress.hide()
                requireActivity().showToast("Error")
            }
        }

        val transferManager = S3TransferManager
            .builder()
            .s3Client(s3Client)
            .build()
        val putObjectRequest: PutObjectRequest = PutObjectRequest
            .builder()
            .bucket(pref.bucketName)
            .key(file.name)
//            .contentLength(file.length())
            .build()

        val uploadFileRequest: UploadFileRequest = UploadFileRequest
            .builder()
            .source(file)
            .putObjectRequest(putObjectRequest)
            .addTransferListener(transferListener)
            .build()

        transferManager
            .uploadFile(uploadFileRequest)
            .completionFuture()
            .whenComplete { _, error ->
                Log.d("--upload error", ":${error.message} ")
            }`

### Expected Behavior

we are expecting that user can upload any file with any slow kind of internet smoothly ,if there is too much slow internet then it show error that internet is slow.  

### Current Behavior

we trying to upload a file inside the bucket if file is low in size and internet is in excellent quality then it work proper otherwise it is throwing exception which is mentioned above.

### Reproduction Steps

` val s3Client = S3AsyncClient.builder()
            .region(Constants.REGION)
//            .httpClient(
//                NettyNioAsyncHttpClient.builder()
//                    .connectionTimeToLive(Duration.ofMinutes(8))
////                    .readTimeout(Duration.ofMinutes(1))
//                    .writeTimeout(Duration.ofMinutes(4))
////                    .connectionAcquisitionTimeout()
////                    .connectionTimeout(Duration.ofMinutes(1))
//                    .maxConcurrency(64)
//                    .build()
//            )
            .endpointOverride(URI(Constants.ENDPOINT))
            .credentialsProvider(credentials)
            .build()

        val transferListener = object : TransferListener {
            override fun transferInitiated(context: TransferListener.Context.TransferInitiated?) {
                super.transferInitiated(context)
                Log.e(TAG, "transferInitiated: total bytes ${humanReadableByteCountSI(context?.progressSnapshot()?.totalBytes()?.asLong!!)}")
            }

            override fun bytesTransferred(context: TransferListener.Context.BytesTransferred?) {
                super.bytesTransferred(context)
                Log.e(TAG, "bytesTransferred: ${humanReadableByteCountSI(context?.progressSnapshot()?.transferredBytes()!!)} | ${humanReadableByteCountSI(context.progressSnapshot()?.remainingBytes()?.asLong!!)}")
            }

            override fun transferComplete(context: TransferListener.Context.TransferComplete?) {
                super.transferComplete(context)
                Log.e(TAG, "transferComplete: ")
                binding.mcvProgress.hide()
                requireActivity().showToast("true")
            }

            override fun transferFailed(context: TransferListener.Context.TransferFailed?) {
                super.transferFailed(context)
                Log.e(TAG, "transferFailed: ${context?.exception()}")
                binding.mcvProgress.hide()
                requireActivity().showToast("Error")
            }
        }

        val transferManager = S3TransferManager
            .builder()
            .s3Client(s3Client)
            .build()
        val putObjectRequest: PutObjectRequest = PutObjectRequest
            .builder()
            .bucket(pref.bucketName)
            .key(file.name)
//            .contentLength(file.length())
            .build()

        val uploadFileRequest: UploadFileRequest = UploadFileRequest
            .builder()
            .source(file)
            .putObjectRequest(putObjectRequest)
            .addTransferListener(transferListener)
            .build()

        transferManager
            .uploadFile(uploadFileRequest)
            .completionFuture()
            .whenComplete { _, error ->
                Log.d("--upload error", ":${error.message} ")
            }`

### AWS Java SDK version used

JavaVersion.VERSION_17

### JDK version used

'software.amazon.awssdk:s3:2.20.157'             'software.amazon.awssdk:s3-transfer-manager:2.20.157'

### Operating System and version

on all android versions

**Comment by debora-ito** [comment]
@mubasherhussain9d 

Tuning the timeout values is the proper solution in this case.

The SDK uses default timeout values that will work on most of the use cases. At the same time, we expose client configurations that you can customize to fit your specific use case, like running in an environment with high latency connectivity.

We suggest you generate the SDK client-side metrics to have an insight of the client performance in its own application environment. The metrics can be used to define what's the best timeout value to set in the client. For instructions on how to generate the metrics, check the [Developer Guide](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/metrics.html) and the [blog post](https://aws.amazon.com/blogs/developer/using-the-new-client-side-metrics-feature-in-the-aws-sdk-for-java-v2/).

**Comment by mubasherhussain9d** [comment]
I know tuning the timeout values is the solution, but the problem here is that uploading a large file takes a lot of time. For example, I was trying to upload a file of size 300MB, but it took 25 minutes even though the internet speed was excellent. If, in my case, I want to add a feature in my application to upload many files of many GBs, then how much time will it take? User will wait for many hours??

**Comment by debora-ito** [comment]
A timeout that will work for all file sizes is a higher timeout. You can use [AwsRequestOverrideConfiguration](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/awscore/AwsRequestOverrideConfiguration.html) to set some timeouts at the request level, but not all timeout settings are available. If you don't want a timeout that is too high for the smaller files, you can create different clients with different settings: one s3 client with lower timeouts for the small files, and another s3 client with higher timeouts for the bigger files.

I still highly recommend to generate the SDK client-side metrics. You can then interpret the SDK metrics of your client to help define better custom settings.

We do have two blog posts that show how to interpret the client-side metrics to improve resiliency of your application (note that the blog posts show Java SDK v1 code, but the theory behind is the same, and most of the v1 metrics have v2 equivalents):
- Tuning AWS Java SDK HTTP request settings for latency-aware Amazon DynamoDB applications - [link](https://aws.amazon.com/blogs/database/tuning-aws-java-sdk-http-request-settings-for-latency-aware-amazon-dynamodb-applications/)
- Tuning the AWS SDK for Java to Improve Resiliency - [link](https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/)

Out of curiosity, have you tried using the [S3CrtAsyncClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3CrtAsyncClientBuilder.html) in the S3TransferManager, instead of NettyNio? It would be interesting to see how the S3 CRT client performs in comparison to Netty in this case.
