### ISSUE TITLE
"400 bad request" instead of proper errorCode on completeMultipartUpload

### ISSUE THREAD

**Issue by andrewl6097** [aws/aws-sdk-java-v2#492]
## Expected Behavior

".errorCode()" on S3Exception should return the proper error code as described on https://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadComplete.html .

This works correctly for "NoSuchUpload":

error with code "NoSuchUpload" and message "The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed."

## Current Behavior

error with code "400 Bad Request" and message "One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag."

error with code "400 Bad Request" and message "The list of parts was not in ascending order. Parts must be ordered by part number."

error with code "400 Bad Request" and message "Your proposed upload is smaller than the minimum allowed size"

## Steps to Reproduce (for bugs)
With the S3AsyncClient, complete a multipart upload that triggers one of the above error conditions.

## Context
I'm writing code that handles these error conditions, but now must string-match on the error message instead of using the code.

## Your Environment

* AWS Java SDK version used: 2.0 preview 9
* JDK version used: JDK8
* Operating System and version: Amazon Linux 2012.03

**Comment by andrewl6097** [comment]
I have a suspicion this is related to "NoSuchUploadException" existing, but not any of the others, so it's falling back on some base case.

**Comment by zoewangg** [comment]
Tested with the latest SnapshotVersion (as of now 69e57a64e16ab9b10a1294d60262502f8d3ac6d8) and verified the `s3Exception.awsErrorDetails().errorCode()` contains the corresponding error code.

For `NoSuchUpload` error, SDK will throw `NoSuchUploadException`.

**Comment by zoewangg** [comment]
Please try with `preview-13` and feel free to reopen if you continue to see the issue.
