### ISSUE TITLE
Firehose client error with GraalVM

### ISSUE THREAD

**Issue by kthumin-work** [aws/aws-sdk-java-v2#4938]
### Describe the bug

We are facing timeout error and connection error with Firehose client in GraalVM environment. It is working fine in normal traffic, but started to have timeout in high request rate environment.

### Expected Behavior

It's running fine before we migrated to GraalVM. There is no change to connection configuration or the code calling firehose.

### Current Behavior

Most requests got timeout in the reactive stream. And started seeing this error 

Error message
```
Unable to execute HTTP request: Acquire operation took longer than the configured maximum time. This indicates that a request cannot get a connection from the pool within the specified maximum time. This can be due to high request rate.
Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate.
Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
```

### Reproduction Steps

Below is the code snippet of how firehose client is called. 

```   
 return Mono.fromFuture(() ->
        firehoseAsyncClient.putRecordBatch(builder ->
            builder.deliveryStreamName(this.nextStream())
              .records(records))
          .thenApply(PutRecordBatchResponse::failedPutCount)
      )
      // retry 1 time in the event of failure
      .retry(1)
      // repeat if failed count is more than 0
      .filter(failedCount -> failedCount == 0)
      .repeatWhenEmpty(Repeat.once())
      // time out set to 2 sec
      .timeout(timeout, Mono.error(new FirehoseException("Exceeded " + timeout)))
```

Firehose Configuration
```
  public FirehoseAsyncClient firehoseAsyncClient(AwsConfigProperties awsConfigProperties) {
    var nettyConfig = awsConfigProperties.getNettyClient();
    return FirehoseAsyncClient.builder()
      .region(Region.of(awsConfigProperties.getRegion()))
      .endpointOverride(URI.create(awsConfigProperties.getFirehose().getEndpoint()))
      .defaultsMode(DefaultsMode.IN_REGION)
      .overrideConfiguration(builder ->
        builder.apiCallTimeout(nettyConfig.getConnectionTimeout())
          .apiCallAttemptTimeout(nettyConfig.getConnectionTimeout()))
      .httpClientBuilder(NettyNioAsyncHttpClient.builder()
        .useIdleConnectionReaper(nettyConfig.getUseIdleConnectionReaper())
        .connectionTimeout(nettyConfig.getConnectionTimeout())
        .readTimeout(nettyConfig.getConnectionTimeout())
        .writeTimeout(nettyConfig.getConnectionTimeout())
        .connectionAcquisitionTimeout(nettyConfig.getConnectionTimeout())
        .tlsNegotiationTimeout(nettyConfig.getConnectionTimeout()))
      .build();
  }
  ```

### Additional Information/Context

We are using java client software.amazon.awssdk.firehose, version `2.20.159`.

### AWS Java SDK version used

2.20.159

### JDK version used

openjdk 17.0.7 2023-04-18 OpenJDK Runtime Environment GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18) OpenJDK 64-Bit Server VM GraalVM CE 22.3.2 (build 17.0.7+7-jvmci-22.3-b18, mixed mode, sharing)

### Operating System and version

AWS Farget using paketobuildpacks/builder-jammy-tiny:latest

**Comment by debora-ito** [comment]
> It is working fine in normal traffic, but started to have timeout in high request rate environment.

The error is expected in these conditions, it indicates all connections from the pool were actively being used and the queued requests timed out while awaiting for a connection to become available. The message gives hints on how to mitigate:

> Consider taking any of the following actions to mitigate the issue: increase max connections, increase acquire timeout, or slowing the request rate. 
> Increasing the max connections can increase client throughput (unless the network interface is already fully utilized), but can eventually start to hit operation system limitations on the number of file descriptors used by the process. If you already are fully utilizing your network interface or cannot further increase your connection count, increasing the acquire timeout gives extra time for requests to acquire a connection before timing out. If the connections doesn't free up, the subsequent requests will still timeout.
