### ISSUE TITLE
Android  XMLInputFactory NoClassDefFound

### ISSUE THREAD

**Issue by Cornflower1991** [aws/aws-sdk-java-v2#4942]
### Describe the issue

java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/xml/stream/XMLInputFactory;

### Links

https://github.com/aws/aws-sdk-java-v2/issues/1180

**Comment by debora-ito** [comment]
@Cornflower1991 there's not enough details in this issue to be able to help you out. Can you give more context on what's your asking for?
