### ISSUE TITLE
"aws s3 sync" through the Java SDK.

### ISSUE THREAD

**Issue by BaeEunshik** [aws/aws-sdk-java-v2#4980]
### Describe the feature

This is an issue related to #2685.
I want to use the "aws s3 sync" feature from the SDK. Is there anything in progress right now?
Thank you

### Use Case

I want to create a Java program to sync between a bucket and the local file system or between buckets, but it's difficult to implement with the features currently available in the SDK that I've looked into.

### AWS Java SDK version used

software.amazon.awssdk:s3-transfer-manager:2.19.1

### JDK version used

openjdk version "1.8.0_222"

### Operating System and version

Windows10

**Comment by debora-ito** [comment]
We don't have plans to add a `s3 sync` operation to S3TransferManager. We suggest to use the operation available in aws cli. 

In the interest of gathering community engagement: Please vote on this issue by adding a 👍 to the original issue if you'd like to see this in the Java SDK v2.

And please don't comment with a "+1" comment, this will only generate noise.

**Comment by kwaikar** [comment]
Sad! Wish this functionality was available in Java SDK. @PM - If you need a customer to talk to regarding this requirement, ping me.

**Comment by nitulkukadia** [comment]
Why such basic things are missing in AWS SDK.
