### ISSUE TITLE
Acknowledgement(EX:-SQSSession.UNORDERED_ACKNOWLEDGE) on message after listing from SQS is missing? in AWS JAVA SDK v2(short issue description)

### ISSUE THREAD

**Issue by pjonnlagadda** [aws/aws-sdk-java-v2#4981]
### Describe the bug

My requirement is to acknowledge the message after listing from SQS rather deleting using Java SDK v2. I am referring the below page where suggesting to delete it after listen or read from queue
https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/examples-sqs-messages.html

SQSSession.UNORDERED_ACKNOWLEDGE?? how to use this in V2?
https://stackoverflow.com/questions/46863834/acknowledge-message-in-sqs-queue

### Expected Behavior

Should be able to acknowledge the messages using SQSSession.UNORDERED_ACKNOWLEDGE or Session.CLIENT_ACKNOWLEDGE

### Current Behavior

Not able to see the acknowledgement behavior or Session related things in V2

### Reproduction Steps

Need to acknowledge the message after listing from SQS rather deleting using Java SDK v2. I am referring the below page where suggesting to delete it after listen or read from queue.
Raised the documentation issue but no response :( 
https://github.com/aws/aws-sdk-java-v2/discussions/4959

### AWS Java SDK version used

v2

### JDK version used

java 17

### Operating System and version

Windows

**Comment by debora-ito** [comment]
@pjonnlagadda sorry for missing your question in the Github Discussion.

SQSSession.UNORDERED_ACKNOWLEDGE and Session.CLIENT_ACKNOWLEDGE are part of a separate library: `com.amazonaws:amazon-sqs-java-messaging-lib`

The library is maintained by the SQS Team, if you have any usage questions please reach out to them in their Github repo: [awslabs/amazon-sqs-java-messaging-lib](https://github.com/awslabs/amazon-sqs-java-messaging-lib/tree/cda5934fdc83650ecc559224c4d53b0cc5a54013)

**Comment by pjonnlagadda** [comment]
Hi @debora-ito,
Thank you for your response.
Here I am using V2 for consuming and later deleting the messages, But you are recomending V1 (`com.amazonaws:amazon-sqs-java-messaging-lib`) for Acknowledgements?
```
<dependency>
    <groupId>software.amazon.awssdk</groupId>
     <artifactId>sqs</artifactId>
</dependency>
```

**Comment by debora-ito** [comment]
`com.amazonaws:amazon-sqs-java-messaging-lib` is a separate lib, it's not vended under Java SDK v1 either. Their latest version is [using Java SDK 2.x under the hood](https://github.com/awslabs/amazon-sqs-java-messaging-lib/blob/cda5934fdc83650ecc559224c4d53b0cc5a54013/pom.xml#L33).
