### ISSUE TITLE
[Feature Request] Provide a dependency free jar

### ISSUE THREAD

**Issue by prelipceang** [aws/aws-sdk-java-v2#499]
In most cases the client will be used within an existing application which might have its own dependencies. Adding the client might break those dependencies (especially netty).

## Expected Behavior

Have the possibility to have a uber jar of the client with the transitive dependencies relocated.

## Current Behavior

Uber jar (with relocated transitive dependencies) is not part of the published artifacts

## Possible Solution

Use the [maven shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/) to create a dependency free jar 
## Your Environment

* AWS Java SDK version used: 2.0.0-preview-9
* JDK version used: java 8
* Operating System and version:

**Comment by arjantop** [comment]
You have ti available as `software.amazon.awssdk:bundle`:

> A single bundled dependency that includes all service and dependent JARs with third-party libraries relocated to different namespaces.

**Comment by dagnir** [comment]
Hi @prelipceang, @arjantop is correct the [bundle](https://github.com/aws/aws-sdk-java-v2/tree/master/bundle) should meet your requirements. Feel free to reopen if it doesn't!

**Comment by prelipceang** [comment]
Thank you @arjantop @dagnir . The fat jar would do the job but I'm wondering why just a subset of dependencies have been relocated. For example `io.netty` is not relocated and it creating a conflict in my case.

**Comment by colin-williams** [comment]
Think I mentioned a conflict via netty in the Gitter channel a few weeks ago..

**Comment by dagnir** [comment]
@prelipceang @colin-williams This appears to be a bug. Please see #485

**Comment by prelipceang** [comment]
thank you for clarifying this, @dagnir @colin-williams

**Comment by dagnir** [comment]
@aaronlee29 Yup, if you need access to it right away, you should be able to clone the repo and run a `mvn install -P quick` from the project root so it's available in your local repo.

Keep in mind that you'll need to update the version to `2.0.0-preview-11-SNAPSHOT` in your POMs and if you distribute your project then anyone consuming it will also need to install the project locally.
