### ISSUE TITLE
Aws Java sdk v2 thread leak

### ISSUE THREAD

**Issue by sid22** [aws/aws-sdk-java-v2#4991]
### Describe the bug

We have a software running perpetually on a vm. We create new object of S3Client for jobs / processes internally as the d3 bucket, credentials change based on usage.

We use ApacheHttpClient when creating an object of S3Client. As part of that we set `useIdleConnectionReaper` to true to close unused s3 clients ( https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/http/apache/ApacheHttpClient.Builder.html#useIdleConnectionReaper(java.lang.Boolean) )

We were using Aws Java SDK v1 client earlier and did not face this issue.
Toggling back to v1 SDK the issue seems to be resolved. As we pass the object to different classes we cannot encapsulate it in Try { } block.

### Expected Behavior

`useIdleConnectionReaper` in ApacheHttpClient should close unused s3Client threads.

### Current Behavior

We  see a lot of “sdk-ScheduledExecutor” from jstack. 
```
"sdk-ScheduledExecutor-297-0" #107305 daemon prio=5 os_prio=0 cpu=0.14ms elapsed=14.49s tid=0x00005633af0d0800 nid=0x176ce7 waiting on condition  [0x00007f4387d77000]
   java.lang.Thread.State: TIMED_WAITING (parking)
        at jdk.internal.misc.Unsafe.park(java.base@11.0.20/Native Method)
        - parking to wait for  <0x00000005576a4ef8> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.parkNanos(java.base@11.0.20/LockSupport.java:234)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@11.0.20/AbstractQueuedSynchronizer.java:2123)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.20/ScheduledThreadPoolExecutor.java:1182)
        at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(java.base@11.0.20/ScheduledThreadPoolExecutor.java:899)
        at java.util.concurrent.ThreadPoolExecutor.getTask(java.base@11.0.20/ThreadPoolExecutor.java:1054)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@11.0.20/ThreadPoolExecutor.java:1114)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@11.0.20/ThreadPoolExecutor.java:628)
        at java.lang.Thread.run(java.base@11.0.20/Thread.java:829)
```

### Reproduction Steps

client =  
      S3Client
        .builder()
        .credentialsProvider(
          credentials.getAwsV2CredentialsProvider
        )
        .httpClientBuilder(        ApacheHttpClient
          .builder()
          .useIdleConnectionReaper(true))
        .build()

client.putObject(
    putObjectRequest,
    RequestBody.fromInputStream(stream, size)
  )

### AWS Java SDK version used

2.20.121

### JDK version used

Azul 11.0.19

### Operating System and version

Ubuntu 20 LTS

**Comment by debora-ito** [comment]
@sid22 how are you analyzing the thread leaks? Are you running JProfiler or Java Flight Recorder (JFR)? Can you share the full report?

**Comment by sid22** [comment]
<img width="1395" alt="Screenshot 2024-03-19 at 3 21 18 PM" src="https://github.com/aws/aws-sdk-java-v2/assets/17125030/be9adcdf-9af2-4e91-9e31-79552f4a9e6d">

@debora-ito unfortunately we saw the leak in prod customers and i cannot share the full report. But we analyze threads using JProfiler.

**Comment by debora-ito** [comment]
Make sure you are applying all the best practices listed here: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/best-practices.html

Specially:
- Reusing the client is recommended, instead of creating a new client per request
- Close input streams from client operations

To troubleshoot this further, please provide a self-contained code sample we can use to reproduce. http://sscce.org/

**Comment by sid22** [comment]
> [@sid22](https://github.com/sid22) how are you analyzing the thread leaks? Are you running JProfiler or Java Flight Recorder (JFR)? Can you share the full report?

@debora-ito yes we used JProfiler. We have now tried to manually call `.close()` on each object of the S3Client when we exit a process. But is this not a change from other SDKs where the objects are GCed automatically.
