### ISSUE TITLE
Add ability to disable "*** Sensitive Data Redacted ***" message.

### ISSUE THREAD

**Issue by bwrichik** [aws/aws-sdk-java-v2#4992]
### Describe the feature

At the moment, some of the objects return `*** Sensitive Data Redacted ***` for certain fields when calling the `toString()` method.

I would like the original values to be returned rather than the redaction.

### Use Case

When debugging failures, I need to print something to the log, or STDOUT. In those instances, sometimes I need to know the contents of the sensitive data. Given the redaction, I have to print out the fields individually, and I can't have it printed fully.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.0.20671.0

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
@bwrichik the fields are redacted as a security measure, to avoid sensitive data leak. We won't add an option to disable it.

Another option for debugging is to use a log level closer to the wire, it'll show all the request and response headers and body content. Our Developer Guide has instructions on how to enable verbose wirelogs for the different http clients in the [Logging](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/logging-slf4j.html#sdk-java-logging-verbose) section.
