### ISSUE TITLE
Error upgrading Rekognition to use v7

### ISSUE THREAD

**Issue by thara-nagaraj** [aws/aws-sdk-java-v2#4995]
### Describe the bug

In order to upgrade Rekognition to Version7,  followed instructions present here - [https://d1m67pwji3rslw.cloudfront.net/guide/Guide_Java2.x.pdf](https://d1m67pwji3rslw.cloudfront.net/guide/Guide_Java2.x.pdf)
and found that `requestedModelVersion` is not available on `DetectModerationLabelsRequest`

### Expected Behavior

DetectModerationLabelsRequest should include RequestedModelVersion

### Current Behavior

RequestedModelVersion not exposed, so we're unable to create the request object to test against version 7 of the model.

### Reproduction Steps

Follow steps mentioned in [https://d1m67pwji3rslw.cloudfront.net/guide/Guide_Java2.x.pdf](url)

### AWS Java SDK version used

2.22.13

### JDK version used

21

### Operating System and version

MacOS 14.3.1

**Comment by debora-ito** [comment]
@thara-nagaraj do you have a contact from the AWS Rekognition team or a technical account that provided this document - https://d1m67pwji3rslw.cloudfront.net/guide/Guide_Java2.x.pdf ? If not, how did you obtained it?

**Comment by thara-nagaraj** [comment]
It's on the Rekognition page - [https://docs.aws.amazon.com/rekognition/latest/dg/procedure-moderate-images.html#moderation-labels-update-sdk](url)

**Comment by debora-ito** [comment]
Got it, thanks for the follow-up.

You need to download the `aws_rekognition_java_v2.jar` referenced in that Rekognition page, and follow the instructions in the pdf to use the jar as a dependency:

```xml
    <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>rekognition</artifactId>
        <scope>system</scope>
        <systemPath>path/to/aws_rekognition_java_v2.jar</systemPath>
    </dependency>
```

Only the `aws_rekognition_java_v2.jar` will have the `requestedModelVersion` field.
