### ISSUE TITLE
jackson-jr or third-party-jackson-core - which is it?

### ISSUE THREAD

**Issue by patrickjamesbarry** [aws/aws-sdk-java-v2#5036]
### Describe the issue

Here AWS advises devs to use jackson-jr if you are trying to make your jars as small as possible for AWS lambda's sake. https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/lambda-optimize-starttime.html

And then here you state AWS decided to roll their own jackson depedency.
https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-2-17-removes-its-external-dependency-on-jackson/

I have confirmed that aws sdk v2 comes bundled with "software.amazon.awssdk:third-party-jackson-core", so if a dev team is including either jackson-databind or jackson-jr, they are duplicating jackson dependencies, etc

What is correct?  Please update docs to reflect the correct route devs should take.

### Links

https://aws.amazon.com/blogs/developer/the-aws-sdk-for-java-2-17-removes-its-external-dependency-on-jackson/
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/lambda-optimize-starttime.html

**Comment by debora-ito** [comment]
I believe `jackson-jr` was called out in the "Reduce SDK startup time" page in comparison with Java SDK v1, not as an advice to use. The Java SDK v2 uses `jackson-jr` for the codegen process ([search](https://github.com/search?q=repo%3Aaws%2Faws-sdk-java-v2+jackson-jr&type=code)).

As for the SDK internal copy of jackson, once a library is shaded it is effectively a different package, there is no way to "deduplicate". If you need to use jackson in your project outside the SDK, you will declare it as a dependency as usual. You will see an increase in the SDK module size as the blog post mentions, but no additional steps are required.
