### ISSUE TITLE
 Metadata will be lost when using s3TransferManager to copy large file

### ISSUE THREAD

**Issue by SinnoSong** [aws/aws-sdk-java-v2#5049]
### Describe the bug

I have a large file(2.5GB), I use S3TransferManager copy the object to another key.

### Expected Behavior

A new file will be created, and the new file contains original metadata.

### Current Behavior

The new file be created, but it does not have the original metadata.

### Reproduction Steps

 Here is my code:
```java
CopyObjectRequest request = CopyObjectRequest.builder().sourceBucket(bucket).sourceKey(key)
                .destinationBucket(destinationBucket).destinationKey(newKey).metadataDirective(MetadataDirective.COPY).build();
        var copyRequest = CopyRequest.builder().copyObjectRequest(request).build();
        s3TransferManager.copy(copyRequest).completionFuture().join();
```

### AWS Java SDK version used

2.25.16
aws-crt used version 0.29.13

### JDK version used

jdk17

### Operating System and version

aws lambda java17

**Comment by zoewangg** [comment]
Hi @SinnoSong, this is the expected behavior. 

>  Note that for multipart copy request, existing metadata stored in the source object is NOT copied to the destination object; if required, you can retrieve the metadata from the source object and set it explicitly in the @link CopyObjectRequest.Builder#metadata(Map)}.

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/transfer/s3/S3TransferManager.html#copy(software.amazon.awssdk.transfer.s3.model.CopyRequest)

**Comment by SinnoSong** [comment]
@zoewangg Thank you.

**Comment by arikogan** [comment]
I think this was finally fixed [here](https://github.com/aws/aws-sdk-java-v2/pull/6989)
