### ISSUE TITLE
Auth doesn't work if SSO Session Name contains a space

### ISSUE THREAD

**Issue by stickfigure** [aws/aws-sdk-java-v2#5054]
### Describe the bug

If you have a space in your SSO Session Name, auth doesn't work. The aws cli works fine, but the SDK doesn't recognize it.

### Expected Behavior

I expect auth to succeed

### Current Behavior

If you run `aws configure sso` and give a sso session name of `FOO BAR`, you get this in your `~/.aws/config`:

```
[profile myprofile]
sso_session = FOO BAR
...
[sso-session 'FOO BAR']
...
```

This works fine for the `aws` cli, but if you try to use this profile with the `ProfileCredentialsProvider`, you get this error:

```
Caused by: java.lang.IllegalArgumentException: Sso-session section not found with sso-session title FOO BAR.
```

Everything works if you remove the space and quotes from the config file.

### Reproduction Steps

See "current behavior" above.

### AWS Java SDK version used

2.25.18

### JDK version used

openjdk 17.0.10 2024-01-16 LTS

### Operating System and version

OSX 14.4.1

**Comment by celesteking** [comment]
This fails Terraform.

**Comment by debora-ito** [comment]
Hi @stickfigure 

Space characters in the profile name is a known difference from the CLI behavior, and we understand the config file should be shared across SDKs and CLI, but we don't have plans to add support in the Java SDK v2.

Parsing multi-word profile names is complex task not only in Java but in other languages too. The recommendation is to use names with no spaces, e.g. "[sso-session FOO-BAR]". This recommendation is valid for regular profile names too, not only sso sessions.
