### ISSUE TITLE
DynamoDbAutoGeneratedTimestampAttribute custom date format and time zone

### ISSUE THREAD

**Issue by chrisbloe-nhse** [aws/aws-sdk-java-v2#5062]
### Describe the feature

The `@DynamoDbAutoGeneratedTimestampAttribute` annotation allows an `Instant` to be stored in DynamoDB as a String, however, the format of this string is fixed to (e.g.) `2023-06-06T18:16:40.632760903Z`.

I have a requirement to store the date in a different format e.g. `2023-06-06T18:16:40+01:00`.

### Use Case

I have tried the following:
```
    @DynamoDbAttribute("CreatedAt")
    @DynamoDbAutoGeneratedTimestampAttribute
    @DynamoDbUpdateBehavior(UpdateBehavior.WRITE_IF_NOT_EXISTS)
    @DynamoDbConvertedBy(OffsetDateTimeAsStringAttributeConverter.class)
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }
```
However `@DynamoDbAutoGeneratedTimestampAttribute` requires the method to return an `Instant`, leaving no easy way of specifying the format of the auto generated time.

### Proposed Solution

A nice way to achieve this would be to allow the annotation user to specify a format and time zone e.g.

 `@DynamoDbAutoGeneratedTimestampAttribute(format=DateTimeFormatter.ISO_OFFSET_DATE_TIME, timezone="Europe/London")`

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.25.23

### JDK version used

21.0.1

### Operating System and version

N/A

**Comment by ungaratto93** [comment]
Hi, this feature can breaks who use a custom converter ?

**Comment by debora-ito** [comment]
Hi @chrisbloe-nhse thank you for raising this, acknowledged as a feature request.

One possible workaround is to use attribute converters - https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ddb-en-client-adv-features-conversion.html

@ungaratto93 we'll keep custom attribute converters in mind when designing the feature, we avoid doing breaking changes in general.

**Comment by debora-ito** [comment]
@chrisbloe-nhse looks like this is already supported by using `@DynamoDbConvertedBy` together with `@DynamoDbAutoGeneratedTimestampAttribute` - see Use Cases 2 and 3 here: https://github.com/aws/aws-sdk-java-v2/pull/2757.

For a code example, you can refer to the converters written for our internal tests: [TimeFormatUpdateTestConverter.java](https://github.com/aws/aws-sdk-java-v2/blob/56f97aab2a0048bdbd714adedf32a2fb0bd0fb32/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/TimeFormatUpdateTestConverter.java#L4), [EpochMillisFormatTestConverter.java](https://github.com/aws/aws-sdk-java-v2/blob/56f97aab2a0048bdbd714adedf32a2fb0bd0fb32/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/enhanced/dynamodb/converters/EpochMillisFormatTestConverter.java).

Let me know if this helps.
