### ISSUE TITLE
Generated client's close() method should not throw checked exceptions

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#51]
Generated clients currently inherit their `close()` method from `AutoCloseable`, which currently declares that it `throws Exception`. In actuality, checked exceptions will never be throw. The client interfaces should override the `close()` method to remove the `throws` statement.

**Comment by millems** [comment]
https://github.com/aws/aws-sdk-java-v2/pull/99

**Comment by shorea** [comment]
Implemented
