### ISSUE TITLE
AWS SDK contains a copy of slf4j which causes problems for the components that have slf4j on the path for imports.

### ISSUE THREAD

**Issue by HarshitGupta11** [aws/aws-sdk-java-v2#5108]
### Describe the bug

Slf4j is shaded in the bundle.jar but there is also a unshaded copy of it present in the jar as well. This causes errors in programs having both slf4j and bundle.jar on the classpath.

The current latest version of the sdk has two LoggerFactory class,
```
./org/slf4j/LoggerFactory.class
./software/amazon/awssdk/thirdparty/org/slf4j/LoggerFactory.class
```

### Expected Behavior

There should be no unshaded artefacts in the bundle.jar.

### Current Behavior

Described above.

### Reproduction Steps

A simple unzip of the jar reveals the issue.

### AWS Java SDK version used

2.24.6

### JDK version used

1.8

### Operating System and version

Redhat 8

**Comment by debora-ito** [comment]
Thank you for reaching out @HarshitGupta11, yes we should fix this. Marking as a bug.

**Comment by HarshitGupta11** [comment]
Any update on this?
