### ISSUE TITLE
endpoints-spi is missing in bom

### ISSUE THREAD

**Issue by laymain** [aws/aws-sdk-java-v2#5116]
### Describe the bug

Hi,

It seems that [endpoints-spi](https://github.com/aws/aws-sdk-java-v2/blob/5deea56ba5925a44f7607f57f2b2e93158ddc030/core/endpoints-spi/pom.xml#L27) artifact is missing in [bom](https://github.com/aws/aws-sdk-java-v2/blob/5deea56ba5925a44f7607f57f2b2e93158ddc030/bom/pom.xml) which could lead to version conflict issues.

### Expected Behavior

Having `endpoints-spi` in `bom`

### Current Behavior

Missing `endpoints-spi` in `bom`

### Reproduction Steps

Import bom

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>bom</artifactId>
      <version>${aws.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

### Possible Solution

Workaround:

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>software.amazon.awssdk</groupId>
      <artifactId>bom</artifactId>
      <version>${aws.version}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
    <dependency>
       <groupId>software.amazon.awssdk</groupId>
       <artifactId>endpoints-spi</artifactId>
       <version>${aws.version}</version>
    </dependency>
  </dependencies>
</dependencyManagement>
```

### AWS Java SDK version used

2.25.33

### JDK version used

not relevant

### Operating System and version

not relevant

**Comment by debora-ito** [comment]
@laymain acknowledged. Marking as a bug.
