### ISSUE TITLE
Add GetSpotInstancesAction to retrieve action from spot instances like on demand instances

### ISSUE THREAD

**Issue by RayaneABDI** [aws/aws-sdk-java-v2#5142]
### Describe the feature

Currently, the aws-sdk-java includes the method getInstanceAction(), which retrieves data from the URL "/latest/meta-data/instance-action". However, to access the action of a spot instance, we must retrieve it from the URL "/latest/meta-data/spot/instance-action".

### Use Case

I aim to determine if AWS will claim my spot instance, and when, adjusting my calculations accordingly. I prefer not to utilize the AWS CLI since I'm already employing the AWS SDK for Java.

### Proposed Solution

```
diff --git a/core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java b/core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java
index 83c41052da9..d2746f18b94 100644
--- a/core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java
+++ b/core/regions/src/main/java/software/amazon/awssdk/regions/internal/util/EC2MetadataUtils.java
@@ -80,6 +80,7 @@ public final class EC2MetadataUtils {
     private static final String EC2_METADATA_ROOT = "/latest/meta-data";
     private static final String EC2_USERDATA_ROOT = "/latest/user-data/";
     private static final String EC2_DYNAMICDATA_ROOT = "/latest/dynamic/";
+    private static final String EC2_SPOT_METADATA_ROOT = "/latest/meta-data/spot";

     private static final String EC2_METADATA_TOKEN_HEADER = "x-aws-ec2-metadata-token";

@@ -139,6 +140,12 @@ public final class EC2MetadataUtils {
         return fetchData(EC2_METADATA_ROOT + "/instance-action");
     }

+    /**
+     * Notifies the instance that it will be stopped.
+     * Valid values: none | stop | terminate.
+     */
+    public static String getSpotInstanceAction() { return fetchData(EC2_SPOT_METADATA_ROOT + "/instance-action"); }
+
     /**
      * Get the ID of this instance.
      */
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.25.17

### JDK version used

openjdk version "17.0.8.1"

### Operating System and version

Linux

**Comment by debora-ito** [comment]
@RayaneABDI you can use the `Ec2MetadataClient` to retrieve the instance metadata you need: 
https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-ec2-IMDS.html

Note that `EC2MetadataUtils` is an internal API class, you should not depend on it because it can introduce breaking changes.

**Comment by RayaneABDI** [comment]
> @RayaneABDI you can use the `Ec2MetadataClient` to retrieve the instance metadata you need: https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/examples-ec2-IMDS.html
> 
> Note that `EC2MetadataUtils` is an internal API class, you should not depend on it because it can introduce breaking changes.

@debora-ito thank you for your reply but that’s make no sense why can we get instance action from on-demand instances and not from spot instances

**Comment by debora-ito** [comment]
> why can we get instance action from on-demand instances and not from spot instances

Without diving into the code, I'd say the SDK doesn't use the spot instance metadata internally.
Using the `Ec2MetadataClient` should get you unblocked.

**Comment by RayaneABDI** [comment]
> > why can we get instance action from on-demand instances and not from spot instances
> 
> Without diving into the code, I'd say the SDK doesn't use the spot instance metadata internally. Using the `Ec2MetadataClient` should get you unblocked.

Okay I will try thank you !
