### ISSUE TITLE
AsyncRequestBody: ability to set content-type

### ISSUE THREAD

**Issue by chaykin** [aws/aws-sdk-java-v2#5143]
### Describe the feature

There is special `AsyncRequestBody` implementation for uploading content to S3 by `InputStream`. It is `BlockingInputStreamAsyncRequestBody`. This class is useful and simple, but it has no way to set custom content-type:
- class is final (so, no way to inherit from it)
- no `contentType` method overriding (so, default implementation from `AsyncRequestBody` used instead. That implementation simply always returns `application/octet-stream`)

### Use Case

Any time I need to upload my existing `InputStream`, I want to use this `BlockingInputStreamAsyncRequestBody`. But, then my content type is differ from `application/octet-stream` (almost always), I need to have own copy-past implementation with my custom content-type...

### Proposed Solution

- Add private final field `contentType` to `BlockingInputStreamAsyncRequestBody`
- Add new constructor with additional argument `contentType`
- Override `contentType` method to return corresponding field

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.25.37

### JDK version used

java 17.0.6 2023-01-17 LTS Java(TM) SE Runtime Environment (build 17.0.6+9-LTS-190) Java HotSpot(TM) 64-Bit Server VM (build 17.0.6+9-LTS-190, mixed mode, sharing)

### Operating System and version

Ubuntu 22.04.3 LTS

**Comment by debora-ito** [comment]
Providing content-type to PutObjectRequest (not the request body) should work fine, I believe.

Can you share a repro code showing how you're making the upload?

**Comment by chaykin** [comment]
I do it like this:

```java
public CompletableFuture<PutObjectResponse> uploadContentAsync(ContentId contentId, AsyncRequestBody body) {
        String contentType = body.contentType();

        var requestBuilder = PutObjectRequest.builder()
                .bucket(contentId.bucket())
                .key(contentId.key());
        if (StringUtils.isNotBlank(contentType)) {
            requestBuilder.contentType(contentType);
        }


        return client.putObject(requestBuilder.build(), body);
    }
```

So, content-type _can_ be set in `requestBuilder`, but use `AsyncRequestBody` for that is more preferrable for me...

**Comment by debora-ito** [comment]
Understood, thank you for the code sample. Feature request acknowledged. 

Community note: please show your support by adding a 👍 reaction to the original issue to help us prioritize this request.

**Comment by davidh44** [comment]
Thanks for the PR! Can we update the changelog and add tests as well?

https://github.com/aws/aws-sdk-java-v2/blob/master/services/s3/src/it/java/software/amazon/awssdk/services/s3/PutObjectIntegrationTest.java

https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/test/java/software/amazon/awssdk/core/async/BlockingInputStreamAsyncRequestBodyTest.java

**Comment by chaykin** [comment]
Feature was implemented in [PR 5234](https://github.com/aws/aws-sdk-java-v2/pull/5234) and merged to master
