### ISSUE TITLE
Inconsistent methods for UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder and AuthorizeSecurityGroupIngressRequest.Builder

### ISSUE THREAD

**Issue by xsimo** [aws/aws-sdk-java-v2#5217]
### Describe the bug

Version 2.25.50
Can not programmatically annotate Security group rules with a description

### Expected Behavior

1. AuthorizeSecurityGroupIngressRequest.Builder should have a description() method
2. UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder should not have an ipPermission() method
3. UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder should have a securityGroupRuleId() method

### Current Behavior

1. AuthorizeSecurityGroupIngressRequest.Builder does not have a description() method
2. UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder has ipPermission() ( not supported by server )
3. UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder does not have securityGroupRuleId()

### Reproduction Steps

Issue an ec2Client.updateSecurityGroupRuleDescriptionsIngress(updateSecurityGroupRuleDescriptionsIngressRequest)
with the updateSecurityGroupRuleDescriptionsIngressRequest containing an ipPermission, the server answers 400 with message 
The parameter 'ipPermissions' may not be used in combination with 'securityGroupRuleDescriptions'. (Service: Ec2, Status Code: 400,

### AWS Java SDK version used

2.25.50

### JDK version used

1.8.0_351-b10

### Operating System and version

Windows 11

**Comment by debora-ito** [comment]
@xsimo to avoid getting the error message 

`The parameter 'ipPermissions' may not be used in combination with 'securityGroupRuleDescriptions'`

you need to add a validation in your code to not send both attributes 'ipPermissions' and 'securityGroupRuleDescriptions' in the same request. We cannot remove attributes from the request at this point, it's a breaking change.

As for
> UpdateSecurityGroupRuleDescriptionsIngressRequest.Builder should have a securityGroupRuleId() method

'securityGroupRuleId' can be found under [SecurityGroupRuleDescription.Builder](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/ec2/model/SecurityGroupRuleDescription.Builder.html), and then you can provide the SecurityGroupRuleDescription to the UpdateSecurityGroupRuleDescriptionsIngressRequest::securityGroupRuleDescriptions request attribute.

Let us know if you have any follow-up question.

**Comment by xsimo** [comment]
Ok, thank you very much for this explanation.
One last precision: Is it possible to add a rule to an existing security group and specify the rule description in the same ec2Client call ?

**Comment by debora-ito** [comment]
I don't think it's possible, you need to call separate APIs: 'ModifyInstanceAttribute' to assign a security group to an instance, and 'ModifySecurityGroupRules' to change the description.

Please refer to the EC2 User Guide for more info: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/working-with-security-groups.html
