### ISSUE TITLE
Parse QueryParams when building S3Uri from AWS CLI Style format

### ISSUE THREAD

**Issue by itisam** [aws/aws-sdk-java-v2#5246]
### Describe the feature

Seems like query parameters are not parsed when building an `S3Uri` from aws cli style uris e.g. `s3://bucket/key?versionId=`. 

### Use Case

Currently it seems I cannot build an S3Uri containing a versionId using `S3Utilities` when my uris are under s3 scheme (e.g. `s3://bucket/key?versionId=`). However, when the same uri is under http scheme, the same class will build the query parameters correctly. I think the library should support passing query parameters with cli style uris. 

### Proposed Solution

[method](https://github.com/aws/aws-sdk-java-v2/blob/7436fdb613fc1f7b07cea49fcd584a1696d4ce85/services/s3/src/main/java/software/amazon/awssdk/services/s3/S3Utilities.java#L380-L404)

```java
...
Map<String, List<String>> queryParams = new HashMap<>();

if (uri.getQuery() != null) {
    queryParams.addAll(SdkHttpUtils.uriParams(uri));
}
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2

### JDK version used

20

### Operating System and version

macOS

**Comment by debora-ito** [comment]
@itisam Is `s3://bucket/key?versionId=` a valid S3 URI though? 

According to the aws console, the versionId is part of the object url (as in `https://bucket.s3.us-west-2.amazonaws.com/key?versionId=abc`), but not of the S3 URI. Is there any documentation that mentions the versionId in the S3 URI?

**Comment by itisam** [comment]
> @itisam Is `s3://bucket/key?versionId=` a valid S3 URI though?
> 
> According to the aws console, the versionId is part of the object url (as in `https://bucket.s3.us-west-2.amazonaws.com/key?versionId=abc`), but not of the S3 URI. Is there any documentation that mentions the versionId in the S3 URI?

You are right, this may not be a valid s3 uri (confirmed with aws console that it didn't work). But would def be helpful if `versionIds` could also work with s3 URIs. 

Closing the issue then.
