### ISSUE TITLE
Regression between SDK v1 and v2 around client side encryption

### ISSUE THREAD

**Issue by NathanEckert** [aws/aws-sdk-java-v2#5252]
### Describe the bug

In AWS SDK v1, I was using `com.amazonaws.services.s3.AmazonS3EncryptionClientBuilder`. In AWS SDK v2, I used `software.amazon.encryption.s3.S3EncryptionClient`

However, there are some issues when using the new client (`S3EncryptionClient.builder().rsaKeyPair(keyPair).wrappedClient(baseClient).build()`).

We tracked down the issue and opened https://github.com/aws/amazon-s3-encryption-client-java/issues/231, but as there was no response from the AWS team, I am opening a new ticket here as it is a migration problem from the SDK v1 to v2

Regards,

### Expected Behavior

To be able to use Range Queries with RSA based client side encryption in the SDK v2

### Current Behavior

Range Queries with RSA based client side encryption raise an Exception

### Reproduction Steps

See https://github.com/aws/amazon-s3-encryption-client-java/issues/231

### Possible Solution

See https://github.com/aws/amazon-s3-encryption-client-java/issues/231#issuecomment-2117064615

### AWS Java SDK version used

- `software.amazon.awssdk:bom`: 2.25.18
- `software.amazon.encryption.s3:amazon-s3-encryption-client-java`: 3.1.2

### JDK version used

openjdk 21.0.3 2024-04-16 LTS

### Operating System and version

Ubuntu 22.04.4 LTS

**Comment by debora-ito** [comment]
Hi @NathanEckert I'll see if I can raise your issue to the Encryption team, they are the maintainers of `aws/amazon-s3-encryption-client-java`.

Closing this for now.
