### ISSUE TITLE
S3 Transfer Manager created using S3Aysnc Client with CRT Builder holding significant memory even after downloads are completed

### ISSUE THREAD

**Issue by fivetran-arunsuri** [aws/aws-sdk-java-v2#5271]
### Describe the bug

We are using S3 Transfer manager to download the files which is created using CRT builder Async client. We download the files on the disk and then we delete those files and again we do the same process. This process is done for the around 500 times and we have put some sleep time in between to observe what happens to memory when S3 tarnsfer manager is not downloading files and we have observed that it is not releasing 100% of the memory and it is holding the same even if it is not downloading anything. 

We have observed that even after some time memory started piling up, though we were not able to observe any OOM just because of this.
Following steps we are using:
        S3AsyncClient s3AsyncClient = S3AsyncClient.crtBuilder()
                .credentialsProvider(
                        StaticCredentialsProvider.create(
                                getCreds()))

                .region(Region.of("us-east-1"))
                .build();
        S3TransferManager s3TransferManager = S3TransferManager.builder().s3Client(s3AsyncClient).build();
   var downloadFutures =
                files.stream()
                        .map(
                                file ->
                                        DOWNLOAD_EXECUTOR_SERVICE.submit(
                                                () -> download(file, downloadDir, s3TransferManager, bucket)))
                        .toList();

for (var downloadFuture : downloadFutures) {
                downloadFuture.get();
            }

And Inside Download:
            DownloadFileRequest downloadFileRequest =
                    DownloadFileRequest.builder()
                            .getObjectRequest(b -> b.bucket(s3bucket).key(s3Object))
                            .addTransferListener(LoggingTransferListener.create())
                            .destination(file)
                            .build();
            s3TransferManager.downloadFile(downloadFileRequest).completionFuture().join();

### Expected Behavior

1. It should release the memory when we are not downloading any new files in every iteration
2. Memory should not increase overtime as we are downloading same files again and again
3. It should not hold the memory even if downloads are not happening

### Current Behavior

It is holding up the memory
Memory is piling up after continuous iterations

### Reproduction Steps

We ran the above setup inside a docker container and we are referring to RSS and docker_stats for checking the memory usage over a period of time

### AWS Java SDK version used

2.25.58

### JDK version used

java 17

### Operating System and version

c7gd.8xlarge ec2 instance

**Comment by debora-ito** [comment]
@fivetran-arunsuri a recent release of the CRT client included a memory leak fix, can you test it with a more recent SDK version? The fix is included starting in SDK version `2.27.14`/`aws-crt-java:0.30.9`.

If upgrading still doesn't fix the memory issue, please provide:
- A [SSCCE](http://sscce.org) self-contained code we can use to reproduce
- A heap dump
- Question: are you creating a new `S3TransferManager` for every request, or reusing?
