### ISSUE TITLE
Unshaded dependencies in AWS SDK

### ISSUE THREAD

**Issue by HarshitGupta11** [aws/aws-sdk-java-v2#5275]
### Describe the bug

Currently there are unshaded dependencies in the aws sdk which causes a lot of deployment failures. In an ideal scenario, there should be no unshaded dependencies and there should be a test check after packaging that should fail as such if there are.

### Expected Behavior

N/A

### Current Behavior

n/A

### Reproduction Steps

Unzip the jar file and check for classes not starting with /software/amazon

### AWS Java SDK version used

2.25.53

### JDK version used

1.8

### Operating System and version

Redhat 8

**Comment by mukund-thakur** [comment]
@HarshitGupta11  could you add some examples of unshaded dependencies?

**Comment by debora-ito** [comment]
@HarshitGupta11 can you tell us more why do you need the SDK to shade dependencies? What you're trying to do?

**Comment by SentryMan** [comment]
are you aware that you can use the maven shade plugin to do this yourself?

**Comment by HarshitGupta11** [comment]
Hi @debora-ito , these are the unshaded classes i found in version 2.25.53: `List of unshaded classes:[org/reactivestreams/FlowAdapters$FlowPublisherFromReactive.class, org/reactivestreams/FlowAdapters$FlowToReactiveProcessor.class, org/reactivestreams/FlowAdapters$FlowToReactiveSubscriber.class, org/reactivestreams/FlowAdapters$FlowToReactiveSubscription.class, org/reactivestreams/FlowAdapters$ReactivePublisherFromFlow.class, org/reactivestreams/FlowAdapters$ReactiveToFlowProcessor.class, org/reactivestreams/FlowAdapters$ReactiveToFlowSubscriber.class, org/reactivestreams/FlowAdapters$ReactiveToFlowSubscription.class, org/reactivestreams/FlowAdapters.class, org/reactivestreams/Processor.class, org/reactivestreams/Publisher.class, org/reactivestreams/Subscriber.class, org/reactivestreams/Subscription.class]` 
I am writing a test in hadoop to verify that there are no as in the past upgrading to 2.24.46 has caused deployment failures having us to rollback all the changes.

**Comment by HarshitGupta11** [comment]
the hadoop pull: https://github.com/apache/hadoop/pull/6865

**Comment by mukund-thakur** [comment]
@debora-ito  here are more details of slf4j issue we fixed before https://github.com/aws/aws-sdk-java-v2/issues/4778#issuecomment-1864992897

**Comment by debora-ito** [comment]
Thank you all, this context would be helpful in the initial description.

Discussed with the team, and we don't want to shade `org.reactivestreams` so the SDK can use the interoperability between other reactive stream libraries.

We have an [internal test](https://github.com/aws/aws-sdk-java-v2/blob/master/test/bundle-shading-tests/src/test/java/software/amazon/awssdk/bundle/BundleShadedCorrectlyTest.java) for the bundle shading that allows the `org.reactivestreams` path, the suggestion here is to do something similar in your tests.

**Comment by mukund-thakur** [comment]
Okay sounds good. thanks. 
We were trying to write a similar test and we can add that to the ignore list.

**Comment by debora-ito** [comment]
Glad to hear. Let us know if there's any follow-up questions.
