### ISSUE TITLE
ApiName does not implement equals

### ISSUE THREAD

**Issue by brettkail-wk** [aws/aws-sdk-java-v2#5292]
### Describe the bug

The [`ApiName` class](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/ApiName.java) doesn't implement `equals`.  This complicates unittests using `Mockito` that want to verify requests are as expected.

### Expected Behavior

Equal request objects after overriding configuration with a custom name (similar to `AmazonSQSExtendedClient`).

### Current Behavior

Unequal request objects.

### Reproduction Steps

```
Supplier<ReceiveMessageRequest> reqFactory = () ->
    ReceiveMessageRequest.builder()
        .overrideConfiguration(
            AwsRequestOverrideConfiguration.builder()
                .addApiName(ApiName.builder().name("n").version("v").build())
                .build())
        .build();
System.err.println(reqFactory.get().equals(reqFactory.get()));
```

### Possible Solution

Implement `equals`.

### AWS Java SDK version used

2.26.1

### JDK version used

N/A

### Operating System and version

N/A

**Comment by debora-ito** [comment]
@brettkail-wk acknowledged. Will try to work on this next week, but in the meantime if you can provide a PR we'd appreciate it.
