### ISSUE TITLE
How to configure KMS vpc endpoint while creating s3Encryption client and s3async client

### ISSUE THREAD

**Issue by dreamerHarshit** [aws/aws-sdk-java-v2#5371]
### Describe the bug

How to configure KMS vpc endpoint while creating s3Encryption client and s3async client

### Expected Behavior

We want to connect with kms from outside of AWS and it is failing 

### Current Behavior

In Earlier SDK version there was a option to configure encryption material provider

### Reproduction Steps

NA

### AWS Java SDK version used

2.25.10

### JDK version used

java17

### Operating System and version

rhel8

**Comment by debora-ito** [comment]
@dreamerHarshit which s3Encryption client are you using, is it `amazon-s3-encryption-client-java` 3.x?
```xml
<dependency>
  <groupId>software.amazon.encryption.s3</groupId>
  <artifactId>amazon-s3-encryption-client-java</artifactId>
  <version>3.x</version>
</dependency>
```

If so, you need to set the vpce url in the custom KMS client, see some Java code examples in the S3 Encryption Client dev guide - https://docs.aws.amazon.com/amazon-s3-encryption-client/latest/developerguide/java-examples.html#java-encrypt-example.

If you have follow-up questions, please reach out to the Crypto Tools team, they maintain the `amazon-s3-encryption-client-java` 3.x library here: https://github.com/aws/amazon-s3-encryption-client-java
