### ISSUE TITLE
equivalent of static RetryCondition defaultRetryCondition()

### ISSUE THREAD

**Issue by eternachen** [aws/aws-sdk-java-v2#5392]
### Describe the issue

I'm just upgraded to 2.26.16 and I had a RetryCondition defaultRetryCondition()

I have to use RetryStrategy.Builder.html#retryOnException(java.util.function.Predicate)).

Deprecated.
Use instead [RetryStrategy.Builder.retryOnException(Predicate)](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/retries/api/RetryStrategy.Builder.html#retryOnException(java.util.function.Predicate)).

Is there an equivalent or Predicate for defaultRetryCondition?

### Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/retry/conditions/RetryCondition.html#defaultRetryCondition()

**Comment by sugmanue** [comment]
The equivalent will be to use the static method [`AwsRetryStrategy.configure`](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.html#configure(T)) ([source](https://github.com/aws/aws-sdk-java-v2/blob/b8f136c7e1bedde1811dc20839ad78ff25b8e0da/core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.java#L129)) to configure a `RetryStrategy.Builder<?,?>` type. For example:

```java
StandardRetryStrategy.Builder builder = StandardRetryStrategy.builder();
builder = AwsRetryStrategy.configure(builder);
StandardRetryStrategy retryStrategy = builder.build();
```

Notice that the retry strategies returned by the static methods in `AwsRetryStrategy` are already configured to retry for AWS retryable errors using that configure method ([source](https://github.com/aws/aws-sdk-java-v2/blob/b8f136c7e1bedde1811dc20839ad78ff25b8e0da/core/aws-core/src/main/java/software/amazon/awssdk/awscore/retry/AwsRetryStrategy.java#L95-L98)), so the example above can be simplified to:

```java
StandardRetryStrategy builder = AwsRetryStrategy.standardRetryStrategy();
```

Please elaborate on your use case and what you're trying to accomplish if you need a more nuance answer.

**Comment by eternachen** [comment]
Thanks a lot, @sugmanue.  It is very helpful.

There are 2 things I am trying

1. convert custom RetryCondition to Predicate.
Old Code:
public final CustomRetryCondition implements RetryCondition {
      public boolean shouldRetry(RetryPolicyContext context) {
             SdkException exn = context.exception()...
             // test your condition here
      } 
}

New Code:
Public final CustomRetryPredicate implements Predicate<SdkException> {
      public boolean test(SDKException exn) {
            // test your condition here
      }
}

2. Convert RetryOnExceptionsCondition.create(Set<Exception> exns) and RetryOnErrorCodeCondition.create(Set<String> codes) to Predicate
It would be easier to have some utility class.

**Comment by sugmanue** [comment]
For the first point, what's preventing you from implementing the predicate?

For the second point, you can see how is done by [the SDK here](https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetryStrategy.java#L157-L169). Notice that the SDK is designed to be generic and not necessarily tied to AWS, therefore we put the generic logic (including retrying on specific status code on the `sdk-core` module while the AWS specific error codes are configured in the `aws-core` module). That's why we have to separated methods to configure retry startegies.

**Comment by eternachen** [comment]
Thanks a lot, @sugmanue.

No issues on First point.

For the second point, thanks a lot for your sample code.
