### ISSUE TITLE
Equivalents of BackoffStrategy.defaultStrategy(), BackoffStrategy.defaultThrottlingStrategy() and RetryCondition.defaultRetryCondition()

### ISSUE THREAD

**Issue by eternachen** [aws/aws-sdk-java-v2#5409]
### Describe the issue

Deprecated method is not allowed...

BackoffStrategy/RetryPolicy/RetryCondition have been deprecated.

I have a code
```
    public static final RetryPolicy RETRY_POLICY = RetryPolicy.builder()
            .retryCondition(RetryCondition.defaultRetryCondition())
            .backoffStrategy(BackoffStrategy.defaultStrategy())
            .throttlingBackoffStrategy(BackoffStrategy.defaultThrottlingStrategy())
            .numRetries(MAX_RETRY)
            .build();
```

I am thinking of below code to replace above code
```
    public static final RetryStrategy RETRY_STRATEGY = AwsRetryStrategy.defaultRetryStrategy()
            .toBuilder()
            .maxAttempts(MAX_RETRY)
            .build();
```

RetryCondition.defaultRetryCondition() / BackoffStrategy.defaultStrategy()/BackoffStrategy.defaultThrottlingStrategy() should be built in AwsRetryStrategy.defaultRetryStrategy()

Please correct me if I am wrong.

### Links

https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/core/retry/backoff/BackoffStrategy.html

**Comment by sugmanue** [comment]
Hi @eternachen, yes, the snippet that you pasted will be the correct replacement.
