### ISSUE TITLE
Getting UnknownHostException with S3AsyncClient

### ISSUE THREAD

**Issue by fivetran-krunalpande** [aws/aws-sdk-java-v2#5427]
### Describe the bug

Getting this transient exception while using S3AsyncClient

Exception Stack Trace:
Failed to download existing files |software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.|Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.|Unable to execute HTTP request: sts.us-east-1.amazonaws.com|sts.us-east-1.amazonaws.com"

### Expected Behavior

Should not get this error

### Current Behavior

Exception Stack Trace:
Failed to download existing files |software.amazon.awssdk.core.exception.SdkClientException: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.|Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.|Unable to execute HTTP request: sts.us-east-1.amazonaws.com|sts.us-east-1.amazonaws.com"

### Reproduction Steps

Call to download file file using grpc from s3 failed

### AWS Java SDK version used

2.25.64
aws-crt version: 0.29.19

### JDK version used

17

### Operating System and version

MacOS 14.5

**Comment by debora-ito** [comment]
`UnknownHostException` is usually a DNS issue. It means the DNS resolver is not able to resolve to the ip address of the sts endpoint. As the message says, it's a network connectivity issue. Have you tried any of the actions listed in the message? 

Note that the SDK uses the underlying 'java.net.InetAddress' as a resolver, you should check you JDK configuration.
