### ISSUE TITLE
Validate AWS::CUR::ReportDefinition in template in all regions

### ISSUE THREAD

**Issue by niraj-ranjan-comprinno** [aws/aws-sdk-java-v2#5503]
### Describe the bug

While running these yaml file of creating the CloudFormation stack in Mumbai we encountered this error which said "Template format error: Unrecognized resource types: [AWS::CUR::ReportDefinition]".
The file when it is used to create a stack in the N.Virginia region is working perfectly fine.
If the template is working in N.Virginia region then there shouldn't be any Template format error for other regions but we're still facing this issue.
With all the required permissions.

### Expected Behavior

AWS::CUR::ReportDefinition in template should work in all regions

### Current Behavior

AWS::CUR::ReportDefinition in template is working only in N.Virginia region

### Reproduction Steps

None

### AWS Java SDK version used

2.25.60

### JDK version used

17

### Operating System and version

Ubuntu

**Comment by debora-ito** [comment]
AWS Cost and Usage Reports is only available in us-east-1 (N. Virginia):

https://docs.aws.amazon.com/general/latest/gr/billing.html

When you see region-related issues, always check the service availability for that region.
