### ISSUE TITLE
DynamDB Enhanced Optimistic Locking for DeleteItem

### ISSUE THREAD

**Issue by LeeroyHannigan** [aws/aws-sdk-java-v2#5511]
### Describe the feature

> The behavior is similar, but v2 does not does not automatically add conditions for the delete operations. You must add condition expressions manually if you want to control the delete behavior. 

Why does `DeleteItem` not support optimistic locking by default?

### Use Case

Using optimistic locking to prevent race conditions, and not honoring it for DeleteItem causes concern.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

SDK 2.X

### JDK version used

17

### Operating System and version

MAC OS

**Comment by debora-ito** [comment]
It's a bug, it was reported here: https://github.com/aws/aws-sdk-java-v2/issues/2358, which I see you've already found and commented.

Closing this as a duplicate, please keep track of upgrades in the other issue.
