### ISSUE TITLE
Cognito API - Add the ability to request an MFA SMS code be re-sent

### ISSUE THREAD

**Issue by alan-wint** [aws/aws-sdk-java-v2#5578]
### Describe the feature

Sometimes a user will not get an MFA code sent by Cognito via SMS.   Please add a method to request re-sending the MFA code via SMS.

### Use Case

Sometimes a user will not get an MFA code sent by Cognito via SMS.  This can be due to a multitude of reasons:

1. The user had the phone number disabled (multi-SIM)
2. The cellular network was down
3. The reception was too poor
4. The user was in flight mode

### Proposed Solution

Add a method for requesting that the MFA code be re-sent via SMS.  It should be rate-limited (configurable per-pool), to prevent abuse.

### Other Information

There is definitely a demand for this across AWS products:
https://github.com/aws/aws-sdk-js/issues/3488
https://github.com/aws-amplify/amplify-js/issues/6676
We have a workaround which involves re-logging in, but its not really a good way to do things.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.27.21

### JDK version used

21

### Operating System and version

Ubuntu 22.04 LTS

**Comment by debora-ito** [comment]
According to the comments, the Cognito team has their eyes in the Amplify tracking issue https://github.com/aws-amplify/amplify-js/issues/6676 -

> Hello everyone, the Cognito team is collecting feedback since they are planning on enabling this feature. If you are open to having us reach out and get your feedback on our proposed experience, can you please send us an email to [aws-amplify-customer@amazon.com](mailto:aws-amplify-customer@amazon.com) with the subject of `Resend MFA feedback`

So I recommend to reach out to the Cognito team by sending them an email. This feature must be supported as a Cognito API in order to be available in the SDKs.

**Comment by debora-ito** [comment]
Please add your comments and thumbs ups in the issue Cognito team is tracking - https://github.com/aws-amplify/amplify-js/issues/6676 - or send an email as instructed.

Closing this, there's no action pending on the Java SDK team.
