### ISSUE TITLE
software.amazon.awssdk:dms is not in BOM

### ISSUE THREAD

**Issue by liyanzh** [aws/aws-sdk-java-v2#5598]
### Describe the feature

I have these in build.gradle
    implementation(platform('software.amazon.awsskd:bom:2.27.21')
    implementation 'software.amazon.awssdk:dms'

in java i imported software.amazon.awssdk.services.databasemigration.DatabaseMigrationClient

But gradle build failed with:
  could not find software.amazon.awssdk:dms

Would you please add dms to BOM?

Thanks!

### Use Case

I am using java to trigger DMS task, since we need to sync two tables regularly.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

v2

### JDK version used

17.0.6

### Operating System and version

cygwin 3.36-341.x86_64

**Comment by debora-ito** [comment]
@liyanzh try using `software.amazon.awssdk:databasemigration` instead of `software.amazon.awssdk:dms`. 

A quick tip is the package name (as in software.amazon.awssdk.services.databasemigration) and the artifact id are usually the same.
