### ISSUE TITLE
Add Explicit DynamoDB TTL Annotation for DynamoDB Mapper

### ISSUE THREAD

**Issue by akiesler** [aws/aws-sdk-java-v2#5609]
### Describe the feature

When modeling a Time To Live attribute it would be beneficial if there was an annotation to mark the attribute in the model to ensure that it is correctly converted to the epoch seconds format expected by DynamoDB. This would prevent clients from mistakenly assuming the default Date converters would handle this case. Additionally, this should be compatible with the `@DynamoDbAutoGeneratedTimestampAttribute` annotation to ensure that clients can easily setup automatic retention of records based on either creation or last use.

### Use Case

When tracking work items in DynamoDB it would be nice to have a simple way to ensure they're deleted after some expected time period (maximum lifetime). This shouldn't require additional logic from clients to implement other than specifying key parameters in the annotations for their model. Clients can then monitor the DynamoDB Stream to detect any records that are being deleted by TTL that are in an open state and send them to a DLQ for further processing and investigation.

Being able to achieve this result using standard classes (Date, DateTime, Calendar, Instant) and annotations simplifies the implementation and reduces the risk of incorrect implementation. A common mistake is failing to truncate from Epoch millis to Epoch seconds. By having the mapper handle the conversions it eliminates the ambiguity for clients and provides a known correct implementation to use.

### Proposed Solution

Add a `@DynamoDbTimeToLiveAttribute` annotation that can be checked for during field conversion and used to infer the conversion type should be numeric and truncated to seconds instead of millis. Additionally, add support to `@DynamoDbAutoGeneratedTimestampAttribute` for an `offset` field of type `Duration` to automatically compute the time to live based on creation or update time.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.26

### JDK version used

openjdk version "1.8.0_422"

### Operating System and version

Mac OS 14.6.1

**Comment by debora-ito** [comment]
Duplicate, we are tracking this request in https://github.com/aws/aws-sdk-java-v2/issues/4295.
