### ISSUE TITLE
Getting 'java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.core.ClientEndpointProvider.isEndpointOverridden()" 

### ISSUE THREAD

**Issue by munishchouhan** [aws/aws-sdk-java-v2#5646]
### Describe the bug

After updating aws sdk to 2.28.15, getting 'java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.core.ClientEndpointProvider.isEndpointOverridden()" because "ep" is null'

in software.amazon.awssdk.services.s3.presigner.S3Presigner

### Regression Issue

- [x] Select this option if this issue appears to be a regression.

### Expected Behavior

i should not throw the exception

### Current Behavior

throwing exception
```
java.lang.NullPointerException: Cannot invoke "software.amazon.awssdk.core.ClientEndpointProvider.isEndpointOverridden()" because "ep" is null
	at software.amazon.awssdk.core.interceptor.SdkExecutionAttribute.lambda$static$3(SdkExecutionAttribute.java:122)
	at software.amazon.awssdk.core.interceptor.ExecutionAttribute$DerivationValueStorage.lambda$set$0(ExecutionAttribute.java:277)
	at java.base/java.util.HashMap.compute(HashMap.java:1324)
	at software.amazon.awssdk.core.interceptor.ExecutionAttribute$DerivationValueStorage.set(ExecutionAttribute.java:277)
	at software.amazon.awssdk.core.interceptor.ExecutionAttributes.putAttribute(ExecutionAttributes.java:75)
	at software.amazon.awssdk.services.s3.internal.signing.DefaultS3Presigner.invokeInterceptorsAndCreateExecutionContext(DefaultS3Presigner.java:341)
	at software.amazon.awssdk.services.s3.internal.signing.DefaultS3Presigner.presign(DefaultS3Presigner.java:308)
	at software.amazon.awssdk.services.s3.internal.signing.DefaultS3Presigner.presignGetObject(DefaultS3Presigner.java:230)
```

### Reproduction Steps

you can check out this pr
https://github.com/seqeralabs/wave/pull/667

### AWS Java SDK version used

2.28.15

### JDK version used

11

### Operating System and version

linux

**Comment by munishchouhan** [comment]
this error is related to this PR
https://github.com/aws/aws-sdk-java-v2/pull/5562

**Comment by munishchouhan** [comment]
this is the code i am using
```
    S3Presigner s3presigner() {
        final builder = S3Presigner.builder()
                .region(Region.of(blobConfig.storageRegion))
                .credentialsProvider(DefaultCredentialsProvider.create())
        if ( blobConfig.storageEndpoint ) {
            builder.endpointOverride(URI.create(blobConfig.storageEndpoint))
        }
        return builder.build()
    }
```
you can find the class here:
https://github.com/seqeralabs/wave/blob/master/src/main/groovy/io/seqera/wave/service/blob/impl/AwsS3PresignerFactory.groovy

**Comment by munishchouhan** [comment]
can it be a dependency issue?

I am adding these three in my project, do i need to add some extra?
```
implementation "software.amazon.awssdk:ecr:2.28.15"
    implementation "software.amazon.awssdk:ecrpublic:2.28.15"
    implementation 'software.amazon.awssdk:ses:2.28.15'
```

**Comment by munishchouhan** [comment]
This turn out to be a missing dependency issue, when i dont mentioned any version, then i thnk micornaut provides teh whole sdk, but with version, i need to provide the depdency
adding this solves the issue
`implementation 'software.amazon.awssdk:aws-sdk-java:2.28.17' `

**Comment by munishchouhan** [comment]
but the whole sdk is too big, how to know which part is missing?

**Comment by debora-ito** [comment]
You need to add as a dependency the SDK modules that correspond to the service clients you want to use, plus any HTTP client if you want to customize its configurations - Apache and NettyNio are added automatically. 

S3Presigner is in `software.amazon.awssdk:s3`, looks like s3 is missing from your list.

Another thing you can check is for version mismatches between SDK modules. Ideally all modules should be in the same version.

**Comment by munishchouhan** [comment]
thank you
s3 fixed the error
