### ISSUE TITLE
S3AsyncClient putObjectRequest memory issues

### ISSUE THREAD

**Issue by Edwin-192** [aws/aws-sdk-java-v2#5647]
### Describe the bug

I am creating a simple Spring application that exposes an endpoint where a file can be written to, which then should be uploaded to our S3 bucket. The application is running in a Kubernetes pod, which has a limit of 500mb memory and I have a hard limit of 100mb for files that will be uploaded.

When I start the application, it will use around 110mb memory.

If I then upload a file of 100mb, the memory consumption will suddenly spike to almost 400mb while uploading. In around 50% of the times I tested it, the container even went OOM during the first upload. When the upload is finished, the baseline of memory consumption will be around 260mb. The remaining 150mb will not be freed again. 
Execution of another upload, will increase this baseline even further, until it does go OOM eventually. 

When commenting out the code to upload to S3 and instead write the data to a temp file, the memory will spike to 210mb, and falling back to a baseline of 110mb right after. 
This makes me believe the memory issues originate from the S3AsyncClient. 

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

I don't expect my container to go OOM when uploading a 100mb file, while having almost 400mb available memory

### Current Behavior

After 1 or more file uploads, the pod gets killed with an 137 OOM, no logging is visible in the container and no out of memory heapdump will be generated.
This makes us believe it is related to the bytebuffer size. 

### Reproduction Steps

My dependencies are:
```	
implementation platform('software.amazon.awssdk:bom:2.28.4')
implementation 'software.amazon.awssdk:s3'
implementation 'software.amazon.awssdk:sts'
```

The simplified code of my controller is:
```	
@PostMapping 
public ResponseEntity<String> uploadRuntimeJar(@RequestParam("file") MultipartFile file) {
  String key = generateKey(file);
  try (InputStream inputStream = file.getInputStream()) {
	return this.fileService.uploadAsync(inputStream, file.getSize(), key)
		.handle((response, throwable) -> {
			if (throwable != null) {
				return ResponseEntity.internalServerError().body("An unexpected error occurred while uploading the file");
			}
			return ResponseEntity.status(HttpStatus.CREATED).body("Successfully uploaded file with key " + key);
		})
		.join(); // Await the upload while the input stream is not closed yet
  } catch (Exception e) {
	  return ResponseEntity.internalServerError().body("An unexpected error occurred while uploading the file");
  }
}
```

The method for uploading the file is the following:
```
public CompletableFuture<PutObjectResponse> uploadAsync(InputStream stream, long contentLength, String key) {
  PutObjectRequest putObjectRequest = PutObjectRequest.builder()
		  .bucket(this.bucketName)
		  .key(key)
		  .build();

  ExecutorService executorService = Executors.newSingleThreadExecutor();
  AsyncRequestBody body = AsyncRequestBody.fromInputStream(stream, contentLength, executorService);
  return this.s3AsyncClient.putObject(putObjectRequest, body)
		  .orTimeout(30, TimeUnit.SECONDS)
		  .exceptionally(throwable -> {
			  throw new RuntimeException("Failed to upload file with key " + key, throwable);
		  }).whenComplete((req, res) -> executorService.shutdownNow());
}
```

which reuses my async client for every call:
```		
this.s3AsyncClient = S3AsyncClient.builder()
				.region(Region.EU_CENTRAL_1)
				.credentialsProvider(WebIdentityTokenFileCredentialsProvider.create())
				.multipartEnabled(true)
				.build();
```

### AWS Java SDK version used

2.28.4

### JDK version used

IBM Semeru Runtime Open Edition 17.0.10.0 (build 17.0.10+7)

### Operating System and version

Linux Ubuntu 22.04.4 LTS

**Comment by debora-ito** [comment]
@Edwin-192 it is weird that the memory baseline keeps growing after each upload. Can you provide a heap dump?
Is the InputStream closed after the upload is finished?

**Comment by Edwin-192** [comment]
@debora-ito I'm sorry, I consistently had this problem last week. Now I try to reproduce it for the heap dump, and I think it knows it's being monitored, since it won't go OOM anymore while no changes were made to the code or container. At least the problem seems to be fixed for now :)
