### ISSUE TITLE
DynamoDbPreserveEmptyObject should apply to Maps

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#5674]
### Describe the feature

The `@DynamoDbPreserveEmptyObject` annotation should write an empty `m` attribute when applied to a `Map` property.

### Use Case

I have a DynamoDB record object with a property of type `Map<String, OtherRecord> nested` that I will fill in as events happen. Unfortunately, [DynamoDB won't let me do a single-shot update if the `nested` attribute does not already exist](https://stackoverflow.com/questions/35377729/how-to-set-a-dynamodb-map-property-value-when-the-map-doesnt-exist-yet), so I want to write an empty map attribute on record creation. Currently, even with `@DynamoDbPreserveEmptyObject` the `Map` property is omitted

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.28.27

### JDK version used

OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Operating System and version

Gentoo Linux

**Comment by Pranjalbharat** [comment]
We can do this by implementing custom Marshaler interface on map. I would like to work on it, Can you please provide me more details?

**Comment by RanVaknin** [comment]
Hi @chrylis ,

Can you please give a little more details about the case that doesn't work? 

>so I want to write an empty map attribute on record creation. Currently, even with @DynamoDbPreserveEmptyObject the Map property is omitted

can you please share your setup and your code as well as the expected  and actual item that is being created? 

Thanks,
Ran~
