### ISSUE TITLE
AWS SDK Java CRT and S3 multi part upload API

### ISSUE THREAD

**Issue by sullis** [aws/aws-sdk-java-v2#5697]
### Describe the issue

I was reading the AWS SDK for Java CRT documentation: 

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-crt.html

The web page says:

`the AWS CRT-based HTTP clients do not use the aws-c-s3 and do not support the S3 multipart upload API features`

Is this still the case?    Please confirm if the doc is accurate.

### Links

https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/http-configuration-crt.html

**Comment by debora-ito** [comment]
Hi @sullis, the documentation is still accurate. That except is regarding the AWS CRT-based HTTP client, which is different than the CRT-based **S3 client**.

Do you have a specific concern behind the question?
