### ISSUE TITLE
Consider migrating from Apache Commons logging to SLF4J

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#57]
SLF4J is more commonly suggested as an alternative to Apache commons logging because of its simplicity and reduction in magic. Look at cold-start performance, features, usability and consider migrating to SLF4J.

**Comment by abrooksv** [comment]
Look into Log4j2 API also?

**Comment by uriahcarpenter** [comment]
The Log4J2 project provides an SLF4J binding.

https://logging.apache.org/log4j/2.0/log4j-slf4j-impl/index.html

**Comment by spfink** [comment]
We have now moved to slf4j as of PR #66 

This has also been released as part of 2.0.0-preview-2

slf4j was chosen due to its compatibility with Log4j2 and it's superior performance on cold start due to its use of static bindings.
