### ISSUE TITLE
"aws s3 sync" through the Java SDK

### ISSUE THREAD

**Issue by nitulkukadia** [aws/aws-sdk-java-v2#5705]
### Describe the feature

Describe the feature
I want to use the "aws s3 sync" feature from the SDK. 

Use Case
I want to create a Java program to sync between a bucket and the local file system or between buckets, but it's difficult to implement with the features currently available in the SDK that I've looked into.

AWS Java SDK version used

<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>bom</artifactId>
    <version>2.29.9</version>
    <type>pom</type>
    <scope>runtime</scope>
</dependency>

JDK version used
openjdk version "1.8.0_222"

Operating System and version
Any OS

### Use Case

I want to use the "aws s3 sync" feature from the SDK. 

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### AWS Java SDK version used

2.29.9

### JDK version used

java version "17.0.9" 2023-10-17 LTS Java(TM) SE Runtime Environment (build 17.0.9+11-LTS-201) Java HotSpot(TM) 64-Bit Server VM (build 17.0.9+11-LTS-201, mixed mode, sharing)

### Operating System and version

macOS Sonoma 14.6.1

**Comment by debora-ito** [comment]
There's no plans to add a `aws s3 sync` equivalent operation to S3TransferManager. 

We recommend to use the operation available in aws cli.
