### ISSUE TITLE
DynamoDbEnhancedClient default extensions are being overridden/replaced when new extensions are being added

### ISSUE THREAD

**Issue by Boyapati36** [aws/aws-sdk-java-v2#5728]
### Describe the bug

DynamoDbEnhancedClient default extensions are being overridden/replaced when new extensions are being added

### Regression Issue

- [ ] Select this option if this issue appears to be a regression.

### Expected Behavior

Default extensions shouldn't be overridden/replaced by the addition of non-default extensions

### Current Behavior

Default extensions are being overridden/replaced by the addition of non-default extensions

### Reproduction Steps

Create a DyanamoDbEnhancedClient bean as follows.
`@Bean
    public DynamoDbEnhancedClient dynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
        return DynamoDbEnhancedClient.builder()
                .dynamoDbClient(dynamoDbClient)
                .extensions(AutoGeneratedTimestampRecordExtension.create(), AutoGeneratedUuidExtension.create())
                .build();
    }`

create a @DynamoDbBean *which is versioned(@DynamoDbVersionAttribute)* class and create a equivalent table for it in dynamoDb environment. try to create a record using putItem/UpdateItem methods of dynamoDbTable class.

You will notice that version number not being created/updated.

### Possible Solution

https://github.com/aws/aws-sdk-java-v2/pull/5727

### AWS Java SDK version used

2.29.1

### JDK version used

21

### Operating System and version

windows 11 23H2

**Comment by debora-ito** [comment]
Hi @Boyapati36 this is not a bug, it's the intended behavior.
Also, the change you are proposing in https://github.com/aws/aws-sdk-java-v2/pull/5727 is a breaking change, we won't be able to merge it.

The "Use extensions" [documentation](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ddb-en-client-extensions.html) mention this:
> If you load your own extensions, the enhanced client doesn't load any default extensions. If you want the behavior provided by either default extension, you need to explicitly add it to the list of extensions.
