### ISSUE TITLE
Rekognition DetectTextRequest/Response?

### ISSUE THREAD

**Issue by efenderbosch** [aws/aws-sdk-java-v2#573]
Is text detection/OCR going to be included in 2.0? I'm starting a new project and would like to use the 2.0 SDK, but I don't see the DetectTextRequest/DetectTextResponse API. Has this been deprecated, or moved somewhere else, or just not implemented yet?

**Comment by dagnir** [comment]
Hey @efenderbosch. We don't currently keep up with all service updates in v2 yet. We will need to merge in the new service model updates for this new API.

**Comment by dagnir** [comment]
Closing this and tracking it in #577.
