### ISSUE TITLE
Lambda sample using Netty-based HTTP client timeouts

### ISSUE THREAD

**Issue by mrudnytskyi** [aws/aws-sdk-java-v2#583]
## Expected Behavior
Java Netty sample should feed `DynamoDb` table with 10k items from `Lambda` in less than 5 minutes. Since Node.js [sample](https://gist.github.com/mrudnytskyi/374291cc0c9188ce3e8feaccdfa7c7c5#file-highloadsample-js) spent 10 seconds for such work, similar performance is expected.

## Current Behavior
After 5 minutes of run, lambda timeouts due to reaching [maximum execution duration](https://docs.aws.amazon.com/lambda/latest/dg/limits.html). Very little amount of items were actually stored in table.

## Steps to Reproduce
Sample for reproducing located in [gist](https://gist.github.com/mrudnytskyi/374291cc0c9188ce3e8feaccdfa7c7c5).

## Context
My goal is to fill DynamoDb table with 650k items as fast, as possible. Because of business-logic requirements, put with condition should be used instead of batch write. It seems strange, that throttling using semaphore should be used in Java implementation, since Node.js (which uses comparable async approach) implementation is not suffering from this issue.

## Environment
* AWS Java SDK version used: 2.0.0-preview-10
* Lambda resources used: 3008Mb
* DynamoDb table write capacity provisioned: 3k

**Comment by dagnir** [comment]
@mrudnytskyi Thanks for the report? To clarify, are you only experiencing this in Lambda?

**Comment by mrudnytskyi** [comment]
Timeout is specific `Lambda` issue, naturally, because of it's time limits.
But it seems, that Netty client performs unexpected under load. On `Batch` jobs we are limiting put requests amount to 5k running simultaneously, but still should have retry logic in case of throwing `SSLException` or `ClosedChannelException`.

**Comment by millems** [comment]
We're continually iterating on SDK performance. If you have any specific contributions in this area, could you make a contribution?

I don't know if this is still an issue, because we've definitely made some improvements since it was opened, but this issue is specific enough that it's not something we directly intend to "fix" (having identical performance to node.js on lambda for writing to DynamoDB using an event-loop based architecture).
