### ISSUE TITLE
Retry on IOException not working as expected

### ISSUE THREAD

**Issue by madgnome** [aws/aws-sdk-java-v2#585]
## Expected Behavior
By default, the SDK should retry on any kind of `IOException` as specified by `SdkDefaultRetrySettings` ( https://github.com/aws/aws-sdk-java-v2/blob/5872b1536ed4434c3297c261b546e482060e61be/core/src/main/java/software/amazon/awssdk/core/internal/retry/SdkDefaultRetrySetting.java#L64 )

## Current Behavior
The SDK only retry if the exception was exactly an `IOException` and ignores all subclasses. As a result exceptions like `ClosedChannelException` or `SSLException` don't trigger a retry.

## Possible Solution
2 fixes are possible:

- Explicitly defines specific `IOException` we want to handle by default
- Modify `RetryOnExceptionsCondition` to check if the thrown exception is a subclass of one of the `exceptionsToRetryOn` using `isAssignableFrom()`

## Context
Call to dynamodb sometime fails because with `ClosedChannelException` or `SSLException` and are not retried.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-10

**Comment by zoewangg** [comment]
Thanks for reporting! We are aware of this and are actively working on this.

https://github.com/aws/aws-sdk-java-v2/blob/5872b1536ed4434c3297c261b546e482060e61be/core/src/main/java/software/amazon/awssdk/core/retry/conditions/RetryOnExceptionsCondition.java#L53-L54

**Comment by madgnome** [comment]
Awesome, I won't raise a PR then.
