### ISSUE TITLE
Conflicting setter definitions for property "networkMode"

### ISSUE THREAD

**Issue by siddheshswnt** [aws/aws-sdk-java-v2#603]
**Summary**
Not being able to deserialize RegisterTaskDefinitionRequest using jackson. 

**Expected Behavior**
I should be able to get RegisterTaskDefinitionRequest from its string input.

## Current Behavior
I am getting following error:
Exception in thread "main" org.codehaus.jackson.map.JsonMappingException: Conflicting setter definitions for property "networkMode": com.amazonaws.services.ecs.model.RegisterTaskDefinitionRequest#setNetworkMode(1 params) vs com.amazonaws.services.ecs.model.RegisterTaskDefinitionRequest#setNetworkMode(1 params)

Here is my code : 
```
ObjectMapper mapper = new ObjectMapper();
mapper.configure(JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES, true);
RegisterTaskDefinitionRequest ronaldo = mapper.readValue(taskDefStr, RegisterTaskDefinitionRequest.class);
```

Also, the versions of Jackson I am using are as follows:
<dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-core</artifactId>
            <version>2.8.0</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-xml</artifactId>
            <version>2.8.5</version>
        </dependency>

Java ecs SDK : 1.11.228

**Comment by dagnir** [comment]
Hi @siddheshswnt this repository is for v2 of the AWS SDK for Java. For v1 issues, can you please open an issue here? https://github.com/aws/aws-sdk-java/issues Thank you!
