### ISSUE TITLE
Move internal classes to "internal" package

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#63]
It isn't obvious without looking for an SdkInternal annotation (that may not even be there) which classes are internal to the SDK. If internal classes were moved to an package with "internal" in the name, this would make it more obvious what should be used by customers. It will also simplify things during Java 9 modularization.

**Comment by MikeFHay** [comment]
Alternatively, many classes could just be made package-private? That makes it even less likely that a user will rely on them directly.

**Comment by millems** [comment]
+1 Once we put everything under an `internal` package, we could possibly use static analysis to make sure the things that can be package private are marked as such. We do that today where possible, but having static analysis to help out will make it harder to miss.

**Comment by dagnir** [comment]
Partially (fully?) completed in the following PR's:

 - #549 
 - #552 
 - #558 
 - #559
