### ISSUE TITLE
Configurable Retry Throttling

### ISSUE THREAD

**Issue by madgnome** [aws/aws-sdk-java-v2#645]
As indicated in `AmazonAsyncHttpClient` we should allow users to customize throttled retries:

```
private CapacityManager createCapacityManager() {
        // When enabled, total retry capacity is computed based on retry cost and desired number of retries.
        // TODO: Allow customers to configure throttled retries (https://github.com/aws/aws-sdk-java-v2/issues/17)
        return new CapacityManager(SdkDefaultRetrySetting.RETRY_THROTTLING_COST * SdkDefaultRetrySetting.THROTTLED_RETRIES);
    }
```

The linked issue is marked as fixed but the issue is not fixed.

## Expected Behavior
User can customize throttled retries/capacity manager.

## Current Behavior
Users can't customize throttled retries/capacity manager.

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-11

**Comment by millems** [comment]
This was fixed, but never resolved. See here: https://github.com/aws/aws-sdk-java-v2/blob/master/core/sdk-core/src/main/java/software/amazon/awssdk/core/retry/RetryPolicy.java#L283-L295
