### ISSUE TITLE
secretsmanager is missing in the BOM

### ISSUE THREAD

**Issue by saiya** [aws/aws-sdk-java-v2#650]
Please add `secretsmanager` into BOM (https://github.com/aws/aws-sdk-java-v2/blob/master/bom/pom.xml).

## Expected Behavior

BOM has `<dependencyManagement>` definition for `software.amazon.awssdk:secretsmanager`

## Current Behavior

BOM does not have it, thus user cannot rely on BOM.

## Possible Solution

Please add following into `<dependencyManagement>` of https://github.com/aws/aws-sdk-java-v2/blob/master/bom/pom.xml 

```
            <dependency>
                <artifactId>secretsmanager</artifactId>
                <groupId>software.amazon.awssdk</groupId>
                <version>${awsjavasdk.version}</version>
            </dependency>
```

## Steps to Reproduce (for bugs)

1. Add dependency to BOM
2. Add dependency to `secretsmanager`, without explicit version
3. Failed to resolve dependency because there is no version specification

## Context

When use BOM in maven/gradle.

## Your Environment

* AWS Java SDK version used: 2.0.0-preview-11
* JDK version used: Any (I used 8, 10, 11)
* Operating System and version: Any (I used Mac OS, Linux)

**Comment by dagnir** [comment]
Fixed by #707.
