### ISSUE TITLE
AttributeKey names should be namespaced to avoid collisions

### ISSUE THREAD

**Issue by dagnir** [aws/aws-sdk-java-v2#669]
We use Netty's `AttributeKey` class, but with fairly generic names: https://github.com/aws/aws-sdk-java-v2/blob/b8f833a9f94131583181c93a0aa09fb4870546ac/http-clients/netty-nio-client/src/main/java/software/amazon/awssdk/http/nio/netty/internal/ChannelAttributeKey.java#L31

This could cause issues if customers pull in the Netty client but are also using Netty and `AttributeKey` directly in their application because only one `AttributeKey` instance can be created per name: https://netty.io/4.1/api/io/netty/util/AttributeKey.html#newInstance-java.lang.String-

**Comment by zoewangg** [comment]
Fixed via #834
