### ISSUE TITLE
New Change log generate script fails with Object Encoding Error

### ISSUE THREAD

**Issue by sushilamazon** [aws/aws-sdk-java-v2#681]
## Expected Behavior
./scripts/new-change script is used to generate new change files here  -  https://github.com/aws/aws-sdk-java-v2/tree/master/.changes/next-releas
Once the script is run, it takes you to an editor like vim where 3 fields are required. Once those fields are populated, you should save and that should generate a change log file.

## Current Behavior
In my case, after coming out from editor It gave me an error - 

Traceback (most recent call last):
  File "./scripts/new-change", line 205, in <module>
    main()
  File "./scripts/new-change", line 201, in main
    sys.exit(new_changelog_entry(args))
  File "./scripts/new-change", line 89, in new_changelog_entry
    filename = write_new_change(parsed_values)
  File "./scripts/new-change", line 142, in write_new_change
    contents_digest = hashlib.sha1(contents).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

## Possible Solution
No clear
## Steps to Reproduce (for bugs)
run ./scripts/new-change command and read the instruction in editor, populate the fields and save it.
## Context
Not able to generate change log file. 

## Your Environment
* AWS Java SDK version used: SDK V2
* JDK version used: 8
* Operating System and version: Mac (Sierra)

**Comment by dagnir** [comment]
@sushilamazon Can you provide sample input that triggered the error?

**Comment by zoewangg** [comment]
Closing due to lack of response, please reopen if you're still experiencing this issue.
