### ISSUE TITLE
get s3 bucket failed when using / in bucketname

### ISSUE THREAD

**Issue by arelaxend** [aws/aws-sdk-java-v2#682]
Hi,

I am looking to get a file from a bucket named "folder/subfolder" but it fails with an 403 error. It works well for a file in a bucket without "/" like "folder". What is the right way to do this?

I am using 2.0.0-preview-11
Best,A.

**Comment by dagnir** [comment]
@arelaxend S3 does not permit butcket names with '/': https://docs.aws.amazon.com/AmazonS3/latest/dev/BucketRestrictions.html

If your bucket is `folder`, then for a file like `subfolder/my_file`, then the request should look something like

```java
GetObjectRequest.builder().bucket("folder").key("subfolder/my_file").build();
```
