### ISSUE TITLE
Question: Version 2.0.1 of some artifacts do not exist on maven central

### ISSUE THREAD

**Issue by hisener** [aws/aws-sdk-java-v2#684]
## Context
It seems like v2.0.1 is released on [releases section](https://github.com/aws/aws-sdk-java-v2/releases) but some artifacts like ec2, sqs etc. are not accessible in [maven central](https://search.maven.org/search?q=g:software.amazon.awssdk).

**Comment by hisener** [comment]
@zoewangg any idea on this?

**Comment by brharrington** [comment]
They have mentioned on the gitter channel that only a subset are fully released at this point:

https://gitter.im/aws/aws-sdk-java-v2?at=5b859c409c71d363c14137cf

**Comment by hisener** [comment]
Thanks @brharrington

From Matthew Miller
> Only cloudwatch, dynamodb and kinesis are released under 2.0.0 and 2.0.1 (production-ready) at this time.

So, I will close the issue.
