### ISSUE TITLE
Unable to work with Kinesis when behind proxy

### ISSUE THREAD

**Issue by mscharp** [aws/aws-sdk-java-v2#685]
I'm attempting to update my "stock-trader" sample application to use the new 2.0 sdk ( in prep for updating a real application ).  The only Kinesis Client that I can create is the KinesisAsyncClient, which uses the Netty Http client.  This is a problem because the AWS version of the netty-http-client doesn't support proxy configuration.

Will there be a KinesisSyncClient?  When will it be available? If not, any reason?

Will proxy config support be added to the Netty Http Client?

I'm not opposed to submitting a PR for adding proxy config support to the netty http client if I can figure it out.  Are there any particular reasons why it wasn't added in the first place of which I should be aware?

thanks!

**Comment by dagnir** [comment]
Hi @mscharp, sounds like you're using versions `2.0.0`/`2.0.1` (non -preview). Answers below: 

> Will there be a KinesisSyncClient? When will it be available? If not, any reason?

Yes, they're currently only available in the preview releases. They were excluded from `2.0.0` since we're still finalizing the sync interfaces.

> Will proxy config support be added to the Netty Http Client?

Yes, this is something that we want to support. If you're willing to put a PR together, we'll be happy to take a look 😄

**Comment by mscharp** [comment]
Ok great.  Thanks for the clarification on the 2.0.1 vs the preview sdks.

**Comment by rjinoy** [comment]
I have the same question - how do i set proxy to KinesisAsyncClient, i am using 2.0.6.

**Comment by dagnir** [comment]
@rjinoy We have yet to implement this for the Netty HTTP client (our default for all async clients). Feel free to thumbs up the original comment so we can help prioritize this against other pending feature requests 😃

**Comment by rjinoy** [comment]
Is there a KinesisSyncClient ?

**Comment by dagnir** [comment]
@rjinoy Yes there is, but at the moment, they're only in the preview versions, not in `2.0.6` (or any other non `-preview` version). If you want to try it (not recommended for production yet), you can try the latest preview version `2.0.0-preview-12`.

**Comment by rjinoy** [comment]
Is there a proxy support for KinesisSyncClient  ?
Do you have an ETA when proxy support would be available for KinesisAsyncClient.

**Comment by dagnir** [comment]
@rjinoy Unfortunately not. The latest updates in the `master` branch do support proxies for the sync clients (see https://github.com/aws/aws-sdk-java-v2/pull/713) but this change has not yet been released as part of a preview release. Note, we'll be doing a preview release soon, but I don't have a concrete date for you.

We don't have an ETA for proxy support in Netty yet, but it's in our backlog. We're also more than happy to take a look at a PR if you'd like to tackle this 😄

**Comment by rjinoy** [comment]
Sure, this is important for me, without the proxy support i cant use KCL.

**Comment by cafecoffee** [comment]
Hi @dagnir 
Is there a proxy support for KinesisSyncClient at current java sdk version?

**Comment by millems** [comment]
Closing in favor of #858
