### ISSUE TITLE
CodeDeploy API putLifecycleEventHookExecutionStatus

### ISSUE THREAD

**Issue by sullis** [aws/aws-sdk-java-v2#687]
## Expected Behavior

I want to use AWS CodeDeploy putLifecycleEventHookExecutionStatus in my Java application.

## Current Behavior

The v2 SDK  does not expose CodeDeploy putLifecycleEventHookExecutionStatus

## Possible Solution

The v1 SDK already provides this functionality:
https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-codedeploy/src/main/java/com/amazonaws/services/codedeploy/AmazonCodeDeployAsyncClient.java#L1551

Can you provide the same functionality in the V2 SDK?

## Steps to Reproduce (for bugs)

n/a

## Context

n/a

## Your Environment
* AWS Java SDK version used:   preview11
* JDK version used: Java 8
* Operating System and version:  MacOS

**Comment by dagnir** [comment]
Hey @sullis, this is related to #577. Looks like the models need to be updated with the latest from upstream.

**Comment by dagnir** [comment]
Fixed by #692.

**Comment by sullis** [comment]
Thanks!
