### ISSUE TITLE
Better error message for global services

### ISSUE THREAD

**Issue by varunnvs92** [aws/aws-sdk-java-v2#691]
Clients for global services like Cloudfront, IAM etc should be created with [AWS_GLOBAL](https://github.com/aws/aws-sdk-java-v2/blob/c2005a7b765523a9e6a3c083f6a6d022f3f8bde4/core/regions/src/main/java/software/amazon/awssdk/regions/Region.java#L69) region. If other aws regions (like us-east-1) are used, it fails with a unclear error message.

Update error message for global services which will inform customers to use AWS_GLOBAL.
Also investigate how global service clients work with cn, gov regions
Related issue: https://github.com/aws/aws-sdk-java-v2/issues/689

**Comment by millems** [comment]
We have this already. We throw a special exception if a request fails due to an DNS error for a service that is global, according to RIP.
