### ISSUE TITLE
S3AsyncClient advanced configuration removed but not documented

### ISSUE THREAD

**Issue by shines2k** [aws/aws-sdk-java-v2#697]
In preview-10 this works fine:
```
    S3AsyncClientBuilder builder = S3AsyncClient.builder()
          .advancedConfiguration(config -> config.pathStyleAccessEnabled(true));
```
In preview-11 it fails to compile. But due to the complete lack of documentation on preview-11, there's no way to know what the new method is supposed to be. There's a cryptic note that "S3AdvancedConfiguration was renamed to S3Configuration" in the change logs, but a simple rename in the code above does nothing.

**Comment by millems** [comment]
Sorry, the bad changelog is my fault. This should work:

```java
    S3AsyncClientBuilder builder = S3AsyncClient.builder()
          .serviceConfiguration(config -> config.pathStyleAccessEnabled(true));
```
