### ISSUE TITLE
[Feature Request] Create overloaded methods in DynamoDBMapper to set RequestMetricCollector for each operation

### ISSUE THREAD

**Issue by swaranga** [aws/aws-sdk-java-v2#703]
We should have the ability to collect DynamoDB service call metrics even when using the DynamoDBMapper library. Note that while I can attach a client level RequestMetricCollector directly to the underlying DynamoDB client, this is not sufficient because I need to collect metrics based on calls to my service and having the ability to attach a metric collector at runtime is what solves the problem for me.

**Comment by dagnir** [comment]
Related to #35

**Comment by SeekerWing** [comment]
i'm not too sure if its directly related to #35 

this feature request is not limited to DynamoDBMapper. in v1 all [AwsClientBuilder](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.html#withMetricsCollector-com.amazonaws.metrics.RequestMetricCollector-) and [AmazonWebServiceRequest](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/AmazonWebServiceRequest.html#withRequestMetricCollector-com.amazonaws.metrics.RequestMetricCollector-) objects provided for the client to provide a [RequestMetricCollector](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/RequestMetricCollector.html)

v2 should provide for the same.

**Comment by dagnir** [comment]
Hi @SeekerWing we're tracking the work for clientside metrics here: #23

**Comment by SeekerWing** [comment]
@dagnir thanks; apologies for duplication

**Comment by millems** [comment]
Closing in favor of #35 and #23
