### ISSUE TITLE
Documentation problem

### ISSUE THREAD

**Issue by kiiadi** [aws/aws-sdk-java-v2#706]
The Javadoc Param reference for streaming response handlers doesn't match the method signature see here : https://github.com/aws/aws-sdk-java-v2/blob/8984b09b5d589a7c6af9a7cd6192f5bd2ee1fb39/codegen/src/test/resources/software/amazon/awssdk/codegen/poet/client/test-json-client-class.java#L478-L502

In javadoc the param is called `streamingHandler` - the actual method includes a `ResponseTransformer` type - looks like the docs need to be updated. 

## Expected Behavior

Java doc should match the actual method signature and describe how to use the component.

**Comment by dagnir** [comment]
Fixed by #718
