### ISSUE TITLE
netty-reactive-streams dependency does not have OSGi support

### ISSUE THREAD

**Issue by dagnir** [aws/aws-sdk-java-v2#726]
## Expected Behavior
The `netty-nio-client` module is usable in an OSGi container.

## Current Behavior
The `netty-nio-client` cannot be loaded because the `netty-reactive-streams` dependency does not support OSGi.

## Possible Solution
Add OSGi support to the `netty-reactive-streams` package: https://github.com/playframework/netty-reactive-streams

## Steps to Reproduce (for bugs)
Using the code from #725, attempt to load `netty-nio-client` into an OSGi container.

## Context
Allow customers to use the Netty client within OSGi.

## Your Environment

* AWS Java SDK version used: `2.0.0-preview-12`
* JDK version used:
* Operating System and version:

**Comment by dagnir** [comment]
PR to fix: https://github.com/playframework/netty-reactive-streams/pull/44

**Comment by dagnir** [comment]
Waiting for a new release to Maven of `netty-reactive-streams` so we can update the Netty client's dependency.

**Comment by debora-ito** [comment]
Updated via #1391, released in `2.8.0`.
