### ISSUE TITLE
Expose ValidationMethod in software.amazon.awssdk.services.acm.model.DomainValidation

### ISSUE THREAD

**Issue by sjmisterm** [aws/aws-sdk-java-v2#735]
## Expected Behavior
The JSON returned for https://docs.aws.amazon.com/acm/latest/APIReference/API_DescribeCertificate.html already contains https://docs.aws.amazon.com/acm/latest/APIReference/API_DomainValidation.html#ACM-Type-DomainValidation-ValidationMethod as part of the response. So the equivalent class, DomainValidation, should have such a property exposed.

## Current Behavior
DomainValidation should have a `validationMethod()` which returns:

`public enum ValidationMethod { DNS, EMAIL}`

## Possible Solution
As shown above

## Steps to Reproduce (for bugs)
N/A

## Context
I'd like to write a rule for our infrastructure in a similar fashion as: https://github.com/cloudsploit/scans/blob/master/plugins/acm/acmValidation.js

## Your Environment
* AWS Java SDK version used: software.amazon.awssdk -> acm 2.0.0-preview-9
* JDK version used: 8u181
* Operating System and version: Windows 10

**Comment by dagnir** [comment]
Hi @sjmisterm looks like you're using an older preview fversion of the SDK. The newest preview version (`2.0.0-preview-12`) should have the `ValidationMethod` enum:

https://github.com/aws/aws-sdk-java-v2/blob/92f35e02839610d7dc86e41d66d6e78c6db6b757/services/acm/src/main/resources/codegen-resources/service-2.json#L1105-L1111

**Comment by dagnir** [comment]
Closing this per above comment. Please feel free to reopen if upgrading to `preview-12` does fix the issue.

**Comment by sjmisterm** [comment]
@dagnir Are javadocs out of date then? http://aws-java-sdk-javadoc.s3-website-us-west-2.amazonaws.com/latest/software/amazon/awssdk/services/acm/model/DomainValidation.html

**Comment by dagnir** [comment]
@sjmisterm That appears to be an outdated link, sorry about that! The correct docs link is https://sdk.amazonaws.com/java/api/latest/overview-summary.html but it looks like it's hosting the `2.0.4` docs at the moment (not `2.0.0-preview-12`). We'll investigate the issue.

**Comment by sjmisterm** [comment]
@dagnir That's the address linked from: https://docs.aws.amazon.com/sdk-for-java/index.html#lang/en_us

**Comment by dagnir** [comment]
Ah, thanks for pointing that out. We'll get it sorted out.

**Comment by sjmisterm** [comment]
@dagnir , are the latest preview javadocs available somewhere already?

**Comment by dagnir** [comment]
@sjmisterm No, unfortunately not. We will be releasing preview-13 soon, so the javadocs will be updated then. Apologies for the delay.
