### ISSUE TITLE
Loading endpoints.json takes a while

### ISSUE THREAD

**Issue by stuartleylandcole** [aws/aws-sdk-java-v2#748]
## Expected Behavior
Creating a service client (e.g. `DynamoDbClient` could potentially be quicker. Currently, the SDK parses the `endpoints.json` file into a POJO which takes a reasonable amount of time.

## Current Behavior
When building a `DynamoDbClient` for the first time, the SDK ends up parsing the `endpoints.json` file into a POJO which takes a reasonable amount of time (the file is approximately 2700 lines long). The code path for this is:

- `software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(SdkClientConfiguration)`
  -  `software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.resolveSigningRegion(SdkClientConfiguration)` 
     - `software.amazon.awssdk.regions.ServiceMetadata.of(String)`
       -  `software.amazon.awssdk.regions.internal.RegionMetadataLoader.getServiceMetadata(String)` which, if `provider` is null, calls
          - `software.amazon.awssdk.regions.internal.RegionMetadataLoader.build()`

## Possible Solution
It would be great if the `Partitions` class could be pre-generated in the SDK so that consumers of it do not need to incur that penalty. There may be good reasons for not doing this, please let me know if so!

## Steps to Reproduce (for bugs)
The following code will take you down the code path I highlighted above

```
DynamoDbClient.builder().build();

```

## Context
I am using the SDK in a Lambda which CRUDs data in a DynamoDB table. The Lambdas provide the API for my client so need to be responsive; creating the `DynamoDbClient` is by far the slowest part of starting my Lambda (provisioning aside, which I can't control).

## Your Environment
* AWS Java SDK version used: 2.0.0-preview-12
* JDK version used: 8 (provided by AWS Lambda)
* Operating System and version: N/A

I would be willing to submit a PR if this functionality is desirable - please give me some pointers if you have a good idea about how it should be implemented.

**Comment by spfink** [comment]
We are actively working on this and should have a PR out soon!

**Comment by stuartleylandcole** [comment]
@spfink that's fantastic! I'm happy to close/for this issue to be closed if you don't need it.

**Comment by spfink** [comment]
We'll keep the issue around until we have the updated code merged.

**Comment by spfink** [comment]
Just merged PR #759 that now generates region and service metadata rather than parsing the file at runtime.
