### ISSUE TITLE
where is KinesisSyncClient ?

### ISSUE THREAD

**Issue by rjinoy** [aws/aws-sdk-java-v2#783]
HI

I want to use KinesisSyncClient because its support proxy, but i do not find in the source code, i downloaded aws-sdk-java-v2-2.0.0-preview-12 preview release it dont have it.

**Comment by dagnir** [comment]
@rjinoy The client is generated at build time.

If you're using Maven, it's pushed to [Maven Central](https://search.maven.org/classic/#artifactdetails%7Csoftware.amazon.awssdk%7Ckinesis%7C2.0.0-preview-12%7Cjar) so you can just declare a dependency on preview-12

```xml
<dependency>
    <groupId>software.amazon.awssdk</groupId>
    <artifactId>kinesis</artifactId>
    <version>2.0.0-preview-12</version>
</dependency>
```

**Comment by dagnir** [comment]
Closing. Please feel free to reopen if you have further questions.
