### ISSUE TITLE
No support for DeletionProtection for DBInstance using AWS SDK2 preview

### ISSUE THREAD

**Issue by luisCavalcantiDev** [aws/aws-sdk-java-v2#793]
## Expected Behavior
DeletionProtection property in https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBInstance.html should be avaliable in software.amazon.awssdk.services.rds.model.DBInstance using AWS SDK2 preview

## Current Behavior
DeletionProtection property is not avaiable in software.amazon.awssdk.services.rds.model.DBInstance using AWS SDK2 preview

## Possible Solution
As shown above

## Steps to Reproduce (for bugs)
N/A

## Context
I'd like to write a rule for our infrastructure to detect RDS instances without DeletionProtectionenabled.

## Your Environment
AWS Java SDK version used: software.amazon.awssdk -> acm 2.0.0-preview-12
JDK version used: 8u192
Operating System and version: Windows 10

**Comment by zoewangg** [comment]
Verified `DBInstance` has `deletionProtection` property in the latest released version `2.1.0`. Can you try with `2.1.0`? Closing the issue, feel free to reopen if you have further question.
