### ISSUE TITLE
Aws iot C sdk mqtt_connect issue

### ISSUE THREAD

**Issue by gecloudtest** [aws/aws-sdk-java-v2#810]
Hi,

I am trying to connect qca4020 board with aws cloud.

I have loaded all the credentials including certificate and private key.

I have referred aws  iot embedded C sdk, When I am executing sample application (subscribe_publish_sample) on ubuntu machine is working fine.
But when I integreted same code  in qca 4020 aws_run.c . I am facing error code -28 which is timeout.
I am not getting why server is  not responding . Could anyone help me in resolving the issue.

Waiting for response.

Thanks ,
Sushmita

**Comment by zoewangg** [comment]
Can you create an issue in https://github.com/aws/aws-iot-device-sdk-embedded-C ?
