### ISSUE TITLE
Regarding the use of the EC2 of 2.0SDK  "description instances" method Instance return instanceLifecycleAsString is null

### ISSUE THREAD

**Issue by kildee** [aws/aws-sdk-java-v2#811]
hello ，I use  DescriptionInstances of EC2  method， I want to get  instanceLifecycle of  Instance. but
result return “null”

![image](https://user-images.githubusercontent.com/26431033/48334103-70fd5900-e694-11e8-81ee-e9f20d000bd4.png)
![image](https://user-images.githubusercontent.com/26431033/48334107-78246700-e694-11e8-8c01-46533a6e2375.png)

**Comment by zoewangg** [comment]
What AWS Java SDK version are you using?
Could you provide the wire logs(be sure to redact any sensitive information) ?

**Comment by kildee** [comment]
> What AWS Java SDK version are you using?
The version is 2.0.0-preview-12
`        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>aws-sdk-java</artifactId>
            <version>2.0.0-preview-12</version>
        </dependency>`

> Could you provide the wire logs(be sure to redact any sensitive information) ?
The log 
https://s3-ap-southeast-1.amazonaws.com/bucketkilde/log

**Comment by zoewangg** [comment]
@kildee I deleted your comment because I noticed the link you provided contains all the wire logs. Please be sure to remove the logs from the link you posted for security reasons.

I will continue investigating the issue.

**Comment by zoewangg** [comment]
Looking at the wire logs, `InstanceLifeCycle` was not in the raw response from ec2, so it's null in the sdk response. 

According to the api docs, `InstanceLifeCycle` is an optional field. https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Instance.html

**Comment by kildee** [comment]
@zoewangg   So what do I get  _InstanceLifeCycle_ of Instance by  describeInstances() of Ec2Client ?

**Comment by kildee** [comment]
@zoewangg  I know return “nul”l is because is “nomal”.Thank you very much
