### ISSUE TITLE
S3 completeMultipartUpload Marshalling Error

### ISSUE THREAD

**Issue by zoewangg** [aws/aws-sdk-java-v2#820]
## Current Behavior
When calling `s3.completeMultipartUpload`, it will throw `S3Exception` with the error message "The XML you provided was not well-formed or did not validate against our published schema (Service: S3, Status Code: 400 ...)"

The issue is in `CompletedMultipartUpload.PARTS_FIELD` field, the `locationName` should be `Part` instead of `Parts`, see below
```java
    private static final SdkField<List<CompletedPart>> PARTS_FIELD = SdkField
            .<List<CompletedPart>> builder(MarshallingType.LIST)
            .getter(getter(CompletedMultipartUpload::parts))
            .setter(setter(Builder::parts))
            .traits(LocationTrait.builder().location(MarshallLocation.PAYLOAD).locationName("Parts")
                    .unmarshallLocationName("Part").build(),
```

## Steps to Reproduce (for bugs)
```java
        String key = "uploadpart";
        CreateMultipartUploadResponse multipartUpload = s3.createMultipartUpload(b ->
                                                                                     b.bucket(BUCKET).key(key));
        long length = "helloworld".getBytes().length;
        UploadPartResponse uploadPartResponse =
            s3.uploadPart(b -> b.bucket(BUCKET).key(key)
                                .uploadId(multipartUpload.uploadId())
                                .partNumber(1)
                                .contentLength(length), RequestBody.fromString("helloworld"));

        String etag = uploadPartResponse.eTag();
        s3.completeMultipartUpload(b -> b.bucket(BUCKET).key(key).uploadId(multipartUpload.uploadId())
                                         .multipartUpload(CompletedMultipartUpload.builder().parts(CompletedPart.builder().
                                             eTag(etag).partNumber(1).build()).build()));

```
## Your Environment

* AWS Java SDK version used: preview-13-snapshot
* JDK version used:
* Operating System and version:

**Comment by shorea** [comment]
Relevant code, https://github.com/aws/aws-sdk-java-v2/blob/master/codegen/src/main/java/software/amazon/awssdk/codegen/AddShapes.java#L289

Don't immediately see what the issue is, that code is quite complicated.

**Comment by trdesilva** [comment]
I'm getting the same error with 1.11.x. I know this is the v2 repo, but is it possible that there's a common root cause? I didn't see a similar issue tracked in the aws-sdk-java repo; does anyone here know if this is a known issue in both projects or just this one?

**Comment by selalerercapitolis** [comment]
A more detailed solution for googlers:
