### ISSUE TITLE
"Waiter" like mechanism for async API

### ISSUE THREAD

**Issue by oakad** [aws/aws-sdk-java-v2#84]
For an async client, a mechanism, "Poller" is required to fulfill the purpose of "Waiter", as used on sync clients (and if such thing exists, may it be better documented?).

Basically, given an async request, "Poller" will repeat the request asynchronously until user specified condition is satisfied by a response, or until policy mandated number of retries/wall clock duration is exceeded - upon either of those outcomes the user specified completion handler is invoked.

**Comment by millems** [comment]
Tracking in #24
