### ISSUE TITLE
URL Presigners

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#849]
This issue tracks the 2.x implementation of equivalent functionality to the 1.11.x presigned URLs in S3, Polly, etc.

**Comment by ddinger** [comment]
Does this mean that in the current version there is no equivalent functionality ? I used this method several times in my existing code base ? What are the plans here ?

**Comment by millems** [comment]
Unfortunately there's no equivalent functionality right now. There are some workarounds posted (e.g. https://github.com/aws/aws-sdk-java-v2/issues/868) if you don't want to use 1.11.x, but workarounds aren't ideal.

It sounds like this functionality is pretty important to a lot of customers, particularly for S3.

**Comment by SuhanKoh** [comment]
@millems Can we expect the feature to have a similar API interface like the work around?

**Comment by millems** [comment]
@SuhanKoh The API hasn't been designed yet, so it's doubtful that is will be the same.

**Comment by brainstorm** [comment]
Third party libs to patch this seem to start cropping up to solve this?: 

https://github.com/aaronanderson/aws-java-sdk-v2-utils

**Comment by zoraida** [comment]
Any update on this?

**Comment by brainstorm** [comment]
@zoraida, si necesitas código de ejemplo para esto, puedes usar el mío:

https://github.com/umccr/igv/blob/umccr/src/main/java/org/broad/igv/util/AmazonUtils.java#L246

Essentially there are ways around this until they include it upstream.

**Comment by zoraida** [comment]
Hi Roman! gràcies! de momento voy a intentarlo sin incluir otra nueva dependencia.
I guess you are using S3Presigner from here, isn't?  
https://github.com/aaronanderson/aws-java-sdk-v2-utils

Just trying  as was suggested on #868

**Comment by mleonhard** [comment]
When you implement this, will you add a way to specify maximum or exact object length for presigned PUTs?

**Comment by millems** [comment]
Closing to track in #203

**Comment by DiaGitHub** [comment]
any update about this issue?

**Comment by debora-ito** [comment]
@DiaGitHub pre-signed urls are now supported in V2: https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/presigner/S3Presigner.html

**Comment by DiaGitHub** [comment]
thanks @debora-ito 
Is it possible to update the [changelog](https://github.com/aws/aws-sdk-java-v2/blob/master/docs/LaunchChangelog.md#7-high-level-libraries) please ?
Thank you
