### ISSUE TITLE
Netty HTTP Proxy Support

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#858]
The Apache HTTP implementation supports proxy configuration, but Netty does not. This feature should be added to Netty.

**Comment by favetelinguis** [comment]
Any status updates on this?

**Comment by vinayys** [comment]
@dagnir - any update on this?

**Comment by dagnir** [comment]
Hi @favetelinguis @vinayys we still have this planned, but have not begun work on this yet.

**Comment by alexmnyc** [comment]
this is very much needed for anyone working in enterprise,.,.,,,,

**Comment by IDWalsh** [comment]
This is a major issue for us adopting it.

**Comment by danieladams456** [comment]
We want to use Spring Boot Webflux to build reactive services.  Currently will have to wrap SDK calls in their own separate thread pools rather than just using Netty all the way through.

Spring Boot lets you inject a [Reactor Netty HttpClient](https://projectreactor.io/docs/netty/release/api/reactor/netty/http/client/HttpClient.html), but I assume you all are using Netty directly instead of Reactor Netty so that wouldn't be available.

**Comment by Krishnaghimire** [comment]
+1

**Comment by BhargavChoksi** [comment]
Can we please add the proxy config support for **_DynamoDbAsyncClient_** ?????

I am in urgent need.

**Comment by dagnir** [comment]
Hi @BhargavChoksi, this feature was built into the Netty HTTP client instead of at the service clients level. To use the Netty client's proxying feature with the DynamoDB client, you will need to configure the Netty client directly on the client:

```java
        SdkAsyncHttpClient.Builder nettyBuilder = NettyNioAsyncHttpClient.builder()
                .proxyConfiguration(ProxyConfiguration.builder()
                        ...
                        .build());

        DynamoDbAsyncClient ddb = DynamoDbAsyncClient.builder()
                .httpClientBuilder(nettyBuilder)
                .build();
```

**Comment by BhargavChoksi** [comment]
Thanks a lot @dagnir, for your quick response. Here, I am able to set proxy-host and proxy-port.
How can I ser proxy username and proxy-password? 

It seems there is no way to set proxy-username ans proxy-password.

final ProxyConfiguration proxyConfiguration =
				ProxyConfiguration.builder().host("http-gw.tcif.telstra.com.au").port(8080).build();

**Comment by dagnir** [comment]
Hey @BhargavChoksi That is not currently supported at the moment. This is being tracked here: https://github.com/aws/aws-sdk-java-v2/issues/1432

**Comment by dagnir** [comment]
Marking this is done. Other proxy related features will be tracked separately (e.g. #1432)

**Comment by LindaByrne** [comment]
Thanks for implementing this, it's working well for me.

One note though, the example configuration [here](https://docs.aws.amazon.com/streams/latest/dev/building-enhanced-consumers-kcl-java.html]) shows using the `KinesisClientUtil.createKinesisAsyncClient` method which will override setting `httpClientBuilder` on the `KinesisAsyncClientBuilder`. Using the KinesisAsyncClient.builder() directly solves this issue.
