### ISSUE TITLE
S3 Select Object Content

### ISSUE THREAD

**Issue by millems** [aws/aws-sdk-java-v2#859]
The S3 SelectObjectContent isn't yet supported in V2, so customers have to use 1.11.x. This API should be supported in V2.

**Comment by humanzz** [comment]
Any updates on this?

**Comment by abatkin** [comment]
Any reason why the release notes claim that 2.10.3 (2019-10-28) contains support for `SelectObjectContent`?

**Comment by abatkin** [comment]
Also, should this get the `1.11.x Parity` tag?

**Comment by spfink** [comment]
@abatkin added 1.11.x Parity tag.

The changelog includes that note on SelectObjectContent as there was an upstream release of an S3 update for AWS. That update only pertained to S3 Select and while we don't support S3 Select we don't filter S3 releases at that granular of a level. It was likely either a no-op for us or potentially added new documentation to other methods.

**Comment by esafzay** [comment]
Til now S3 Select is only available in v1?

**Comment by ilio** [comment]
Hi AWS team, please add the feature support.

**Comment by cemo** [comment]
Can we contribute to support this as well?

**Comment by ilio** [comment]
I have implemented the functionality, but it is in a quick and dirty format, if you want I can later organize and lay out the code.

**Comment by amannm** [comment]
This has been open for a while. Is this portion of the S3 API being omitted from 2.x support on purpose?

**Comment by millems** [comment]
It's not being omitted on purpose, except for prioritization purposes. It's still in our backlog.

**Comment by raghuvaran** [comment]
+1

**Comment by dagnir** [comment]
Hi all, I'm happy to report that this PR #2943 adds support for this operation, and has now been merged. It will be part of the next release of the SDK.

**Comment by NoelCov** [comment]
Has this been released? I seen the last comment from Jan 4 2022 says the PR has been merged and that it will be part of the next release of the SDK but I'm using SDK V2 and don't seem to have access to this yet.

**Comment by kekbur** [comment]
> Has this been released?

It has been released. Check the version of your SDK, it should contain at least the class [SelectObjectContentRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/SelectObjectContentRequest.html).

**Comment by NoelCov** [comment]
> > Has this been released?
> 
> It has been released. Check the version of your SDK, it should contain at least the class [SelectObjectContentRequest](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/model/SelectObjectContentRequest.html).

Hey there @kekbur, thanks for the reply. I did see that for the Java AWS SDK V2 the SelectObjectContentRequest and SelectObjectContentResponse exist and are available, however I did not find a way to make the actual call to select the object content. I looked for a while and didn't find a way to do it. At the end I ended up just switching to the SDK V1 for now. However, if you know of a way to do it using the Java SDK V2 I'd appreciate if you can link a resource or something like that here so I can look at it, thanks a lot.

**Comment by kekbur** [comment]
@NoelCov, I think it's only possible with the [S3AsyncClient](https://sdk.amazonaws.com/java/api/latest/software/amazon/awssdk/services/s3/S3AsyncClient.html#selectObjectContent(software.amazon.awssdk.services.s3.model.SelectObjectContentRequest,software.amazon.awssdk.services.s3.model.SelectObjectContentResponseHandler)) class and not S3Client.
