### ISSUE TITLE
Dynamo's GetItemResponse#item() return an empty map if nothing found

### ISSUE THREAD

**Issue by sedovalx** [aws/aws-sdk-java-v2#865]
I'm trying to get a Dynamo item by a primary key value. Here is my code:
```
DynamoDbClient client = null;
String tableName = "...";
String queryId = "...";
Map<String, AttributeValue> key = new TreeMap<>();
key.put("query_id", AttributeValue.builder().s(queryId).build());
GetItemRequest request = GetItemRequest.builder()
        .tableName(tableName)
        .key(key)
        .build();
Map<String, AttributeValue> result = client.getItem(request).item();
```

I expect this code to assign `null` to the `result` variable if nothing is found by the `queryId` and to assign a not-null map otherwise.

Now, the response's item contains an empty map if nothing is found and a map with filed values otherwise. As I see while debugging the actual http response contains an empty json object in the body in case of passing a non-existent `queryId` into the request. 

I'm looking for a way to reliably distinguish the case when the item is not found. Do I miss something? 

* AWS Java SDK version used:  2.1.0
* JDK version used: 1.8.0_181
* Operating System and version: MacOS 10.14.1 (18B75)

**Comment by zoewangg** [comment]
We made the default list/map to be an instance of `SdkAutoConstructList`/`SdkAutoConstructMap` so that users don’t need to do null check anymore. So if the item is not found, it should be an instance of `SdkAutoConstructMap` and you can do `instanceof` check  to replace of null check.

**Comment by sedovalx** [comment]
That doesn't look like an obvious contract here. I would suggest to use a proper return type for the `GetItemResponse#item()` method - a type that can "say" that the result is actually absent without a need to do a type check. Maybe `Optional`?

**Comment by zoewangg** [comment]
I agree that this is not very discoverable and we will work on improving the documentations to make it more clear. 

We have considered using `Optional` but the tricky part is that all the pojos are generated based on the service models owned by the service teams and they might change from time to time. For example, a service may tighten the response constraint by making a previously optional value always present (this is considered backwards compatible from service point of view). In this case, it does not make much sense to continue using Optional for that value and we cannot change it to not return Optional for backwards compatibility reasons. See similar discussions in #47

**Comment by sedovalx** [comment]
I see. From that point of view, using a `@Notnull`/`@Nullable` annotation in such places seems the better approach than `Optional`. If a service change the response contract to make a value always present you may change the `@Nullable` annotation to `@Notnull` and it will be backward compatible also. Speaking of Kotlin, in that language it would be a self speaking and clear API. In the Java case, most IDEs will warn a user on dereferencing a value that is marked as `@Nullable` without a null check.

I hope you guys will revisit this decision to check types of returned lists and maps.

**Comment by millems** [comment]
We've discussed @Notnull and @Nullable, and we're in favor of adding them for static analysis and kotlin users. We just haven't gotten to them, quite yet.

We couldn't backwards-compatibly introduce a subtype of List/Map that adds a method to see if it was set by the service (e.g. `response.item().hasValue()`), and we can't make them start returning null now, but we could probably add another way of getting at this information (e.g. `response.hasItem()`) before attempting to use the value.

**Comment by sedovalx** [comment]
Right, `response.hasItem()` would be more explicit approach than type checking. Right now I ended up with a similar extension (in terms of Kotlin) function. I'm looking forward to see it in the API. Thank you very much!
