### ISSUE TITLE
2.1.0 missed organizations

### ISSUE THREAD

**Issue by funnycoding** [aws/aws-sdk-java-v2#872]
## Expected Behavior

use maven dependency  aws-sdk-java and I can use all aws services java sdk.
## Current Behavior
organizations sdk not found in aws-sdk-java so I use to individual introduce maven dependency organizations.

## Your Environment

* AWS Java SDK version used:  2.1.0
* JDK version used:
* Operating System and version:

**Comment by zoewangg** [comment]
Thanks for reporting. This has been fixed via #876 and will be included in the next release.
