### ISSUE TITLE
Add and document X-Ray tracing for clients

### ISSUE THREAD

**Issue by ashleymercer** [aws/aws-sdk-java-v2#874]
## Expected Behavior

The v2 SDK should provide an equivalent of 1.11's `TracingHandler` for clients, so service calls can be traced in X-Ray:

```java
AWSLambda lambda = AWSLambdaClientBuilder
      .standard()
      .withRequestHandlers(new TracingHandler(recorder))
      .build()
```

## Current Behavior

I can't see an equivalent implementation in the v2 SDK anywhere - assuming it would use the new `ExecutionInterceptor` API - or if there is one, I can't see it documented in [the developer guide](https://docs.aws.amazon.com/sdk-for-java/v2/developer-guide/welcome.html).

## Possible Solution
Add and document an implementation of `ExecutionInterceptor` that traces AWS client requests.

## Steps to Reproduce (for bugs)
N/A

## Context
Required for parity with the 1.11 SDK.

## Your Environment
* AWS Java SDK version used: 2.1.0
* JDK version used: 8

**Comment by zoewangg** [comment]
We don't own AWS XRay SDK, can you open an issue with XRay team https://github.com/aws/aws-xray-sdk-java/issues?

**Comment by ashleymercer** [comment]
@zoewangg Thanks for the quick response: have cross-posted to the X-Ray project

https://github.com/aws/aws-xray-sdk-java/issues/43
