### ISSUE TITLE
Port aws/aws-sdk-java/#1653 to v2

### ISSUE THREAD

**Issue by slandelle** [aws/aws-sdk-java-v2#918]
aws/aws-sdk-java/#1653 introduced `EC2MetadataUtils#getInstanceSignature`.
This method is missing in v2.

## Expected Behavior

v2 should provide a builtin solution for fetching the instance's signature.
Current workaround is `EC2MetadataUtils.getData("/latest/dynamic/instance-identity/signature")`

## Current Behavior

Method exists in v1 but not in v2

## Your Environment
* AWS Java SDK version used: 2.1.3

**Comment by millems** [comment]
Tracking in #61
