### ISSUE TITLE
Custom Endpoints Files

### ISSUE THREAD

**Issue by craig-dae** [aws/aws-sdk-java-v2#938]
"Loading region configuration from a custom endpoints.json file is no longer supported."

I require the ability to load region configuration from a custom endpoints.json file. Can you add this feature back in?

**Comment by craig-dae** [comment]
Yes. We offer a product that allows customer to emulate an AWS air-gapped region. The idea is you can have a commercial product, and if the code is written properly (without magic strings, etc) you should be able to configure it for an air-gapped region without changing the code. 

The endpoints.json file is one of the main pieces of the puzzle. Without it, we'll have to download the source and figure out how to modify it before doing a maven build.

**Comment by joviegas** [comment]
With https://github.com/aws/aws-sdk-java-v2/pull/3502 we no longer need this .
Checked this with @dagnir
