### ISSUE TITLE
Is there any support for script runner in aws sdk java version2?

### ISSUE THREAD

**Issue by LamaBimal** [aws/aws-sdk-java-v2#945]
## Your Environment

* AWS Java SDK version used: 
* JDK version used:
* Operating System and version:

**Comment by shorea** [comment]
I'm not familiar with script runner. Can you elaborate?

**Comment by LamaBimal** [comment]
I would like to execute a script as a step in emr which is supported in version1.

**Comment by zoewangg** [comment]
Are you referring to  `StepFactory#newScriptRunnerStep`?
https://github.com/aws/aws-sdk-java/blob/2c0ee6c337cfea476ee9e9e1b1ede98f0bf453ce/aws-java-sdk-emr/src/main/java/com/amazonaws/services/elasticmapreduce/util/StepFactory.java#L132

This has not been implemented yet in v2. Marking it as a feature request.

**Comment by millems** [comment]
Closing in favor of #947
