### ISSUE TITLE
Failed while enforcing RequireUpperBoundDeps due to incorrect jackson-annotation version

### ISSUE THREAD

**Issue by tomliu4uber** [aws/aws-sdk-java-v2#948]
According to [jackson-bom-2.9.7.pom](http://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.9.7/jackson-bom-2.9.7.pom).  `jackson-databind:2.9.7` and all other `2.9.7` components depend on `jackson-annotation:2.9.0`, instead of `jackson-annotation:2.9.7`

However, [Amazon SDK V2](http://repo1.maven.org/maven2/software/amazon/awssdk/aws-sdk-java-pom/2.1.4/aws-sdk-java-pom-2.1.4.pom) always assume the versions are the same and it only defines a single `{jackson.version}` for all Jackson libraries.

When we use Jackson versions defined by [jackson-bom-2.9.7.pom](http://repo1.maven.org/maven2/com/fasterxml/jackson/jackson-bom/2.9.7/jackson-bom-2.9.7.pom) and also use `maven-enforcer-plugin` with `RequireUpperBoundDeps` policy, our project always fails due to `upper bound dependencies error`

## Expected Behavior
The build should pass

## Current Behavior
build fails due to `upper bound dependencies error`

## Possible Solution
please use dependency management to manage jackson version in [Amazon SDK V2](http://repo1.maven.org/maven2/software/amazon/awssdk/aws-sdk-java-pom/2.1.4/aws-sdk-java-pom-2.1.4.pom)
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.9.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
``` 

or define two versions: 
- `2.9.0` for `jackson-annotations`
- `2.9.7` for other components

## Steps to Reproduce (for bugs)
- create a new maven project
- import Jackson dependency
```
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.fasterxml.jackson</groupId>
                <artifactId>jackson-bom</artifactId>
                <version>2.9.7</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
``` 
- add both Jackson and Amazon dependency to the project
```
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
        </dependency>
        <dependency>
            <groupId>software.amazon.awssdk</groupId>
            <artifactId>dynamodb</artifactId>
            <version>2.1.40</version>
        </dependency>
```
 - enable `maven-enforcer-plugin`
```
                <plugin>
                    <artifactId>maven-enforcer-plugin</artifactId>
                    <version>3.0.0-M2</version>
                    <executions>
                        <execution>
                            <id>default-enforce</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <configuration>
                                <rules>
                                    <requireJavaVersion>
                                        <version>[1.8,)</version>
                                    </requireJavaVersion>
                                </rules>
                            </configuration>
                        </execution>
                        <execution>
                            <id>default-enforce-at-test-compile</id>
                            <goals>
                                <goal>enforce</goal>
                            </goals>
                            <phase>test-compile</phase>
                            <configuration>
                                <rules>
                                    <requireUpperBoundDeps/>
                                </rules>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
```
 - you should see the enforcer error

## Your Environment

* AWS Java SDK version used: 
* JDK version used: 1.8.0_162
* Operating System and version: MacOS

**Comment by zoewangg** [comment]
The fix has been released in [2.3.0](https://github.com/aws/aws-sdk-java-v2/blob/2.3.0/CHANGELOG.md#230-2019-01-09). Closing the issue.
