### ISSUE TITLE
A port of dynamodb-lock-client?

### ISSUE THREAD

**Issue by pshirshov** [aws/aws-sdk-java-v2#969]
Hi,

Could you give me a hint if we may expect something like https://github.com/awslabs/dynamodb-lock-client to appear for v2 sdk?

**Comment by zoewangg** [comment]
Hi, we don't own `dynamodb-lock-client`. Looks like https://github.com/awslabs/dynamodb-lock-client/issues/9 has been opened with them and there's no reply. I will reach out to the service team.

**Comment by zoewangg** [comment]
@pshirshov  They are working on v2 support. Tracking in https://github.com/awslabs/dynamodb-lock-client/pull/19 

Closing this issue. Feel free to reopen if you have further SDK questions.

**Comment by amcp** [comment]
@pshirshov this build should pass all tests in aws sdk v2: https://github.com/awslabs/dynamodb-lock-client/pull/19 , will merge soon
