### ISSUE TITLE
Please make EC2MetadataUtils non-internal

### ISSUE THREAD

**Issue by slukes** [aws/aws-sdk-java-v2#972]
EC2MetadataUtils is currently an internal API, theoretically means each applications developer needs to re-invent the wheel in order to obtain, for example, the instance id of the ec2 their application is running on.

## Expected Behavior
Please remove this class from the internal package.
Ideally, please make the api non-static to allow for easier testing of application code.

**Comment by zoewangg** [comment]
Related to #61 

We have plans to refactor `Ec2MetadataUtils` and make it public, but it may not happen soon. PRs are welcome!

**Comment by slukes** [comment]
Hello, I'm happy to contribute this.

Please could you provide any guidance as to what you have in mind an obvious lift / shift?

**Comment by millems** [comment]
Resolving to track in #61
