### ISSUE TITLE
mvn clean install报错

### ISSUE THREAD

**Issue by Hyz7** [aws/aws-sdk-java-v2#977]
## 问题
项目拉下来后,在目录里mvn clean install就报错,
![image](https://user-images.githubusercontent.com/43902466/50464688-5b868900-09cd-11e9-82da-c230fa280002.png)
![image](https://user-images.githubusercontent.com/43902466/50464772-da7bc180-09cd-11e9-9279-55819bfbeae7.png)

**Comment by zoewangg** [comment]
Related to #986

**Comment by zoewangg** [comment]
Closing in favor of #986
