### ISSUE TITLE
java.io.IOException: Connection reset by peer on asynchronous calls of SQS and SES (Channel closed - SSL handshake failure)

### ISSUE THREAD

**Issue by Jahx** [aws/aws-sdk-java-v2#978]
We are getting IOException "Connection reset by peer" for asynchronous SQS and SES clients which is caused by SSLException: "Inbound closed before receiving peer's close_notify: possible truncation attack?" 
Please check these screenshots from Intellij debug for more detail: https://photos.app.goo.gl/LCnmULCjzx54nbde9

## Expected Behavior
Connections are closed properly. No SSL handshake or channel was closed exceptions

## Current Behavior
Please check these screenshots for more detail: https://photos.app.goo.gl/LCnmULCjzx54nbde9

## Steps to Reproduce (for bugs)
Make asynchronous call using SesAsynchClinet or SqsAsyncClient. From time to time we get the exception (Usually in 1 minute delay after actual call). 

## Context
One of our services is used for sending emails. We get the errors and cannot handle it.

## Your Environment
* AWS Java SDK version used: 2.2.0
* JDK version used: java-1.8.0 (8u181-b13)
* Operating System and version: docker amazonlinux:latest

**Comment by Aleksandr-Filichkin** [comment]
Hi, I also see this issue for SES?
Any updates?

**Comment by baka2010** [comment]
@zoewangg 
please take a look at https://github.com/baka2010/ses
Just set EMAIL_ADDRESS_TO and EMAIL_ADDRESS_FROM.
This issue is reproduced when you try to send >100 emails after 1 min timeout.
Stack trace screenshot is in repo.

**Comment by Aleksandr-Filichkin** [comment]
@zoewangg did you have a chance to try this code from the previous comment?

**Comment by Jahx** [comment]
Hi @zoewangg! Thanks for your help.  Since it is duplicate issue for [#900](https://github.com/aws/aws-sdk-java-v2/issues/900#issuecomment-445093553) we can close this one.
