### ISSUE TITLE
DynamoDB Local

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#982]
I am writing a new module that uses DynamoDB, and I would like to use the v2 SDK. The only manageable way to run functional tests on my module is to use the [DynamoDBLocal](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.Maven.html) implementation to make sure that round-trip reads and writes behave as expected.

However, I'm not able to find any documentation that mentions local support for the v2 SDK. The `DynamoDBEmbedded.create()` call in DynamoDBLocal 1.11 returns the v1 `AmazonDynamoDB` interface, and there don't appear to be adapters to the v2 API. I also haven't been able to find a version 2.x of the DynamoDBLocal dependency.

Is a v2 version of DynamoDBLocal available? If not, is it on the roadmap, and is there a way (maybe using a loopback IP connection) to use the v1 embedded provider with the v2 client APIs?

**Comment by chrylis** [comment]
(Note: [The migration documentation](https://docs.aws.amazon.com/sdk-for-java/v2/migration-guide/whats-different.html) has a link for configuring "side-by-side" v1 and v2, but the link is broken.)

**Comment by zoewangg** [comment]
We don't own `DynamoDBLocal` and I will reach out to the service team regarding the migration plan for v2. Marking this as a feature request.

Thank you for reporting the broken link! We will make sure it gets fixed.

**Comment by chrylis** [comment]
As a followup, while it's a bit slow and requires some hackery to assign dynamic ports and wait until it's ready, I have been able to launch captive Local instances in a test setup and then point a v2 SDK client at them.

**Comment by wsargent** [comment]
@chrylis 	Can you share in a project or blog post?  I'm running into the same issue.

**Comment by wsargent** [comment]
Is the recommended option to use https://hub.docker.com/r/amazon/dynamodb-local/ as per https://aws.amazon.com/about-aws/whats-new/2018/08/use-amazon-dynamodb-local-more-easily-with-the-new-docker-image/ ?

**Comment by humanzz** [comment]
I've just learnt that the existing DynamoDBLocal can be used with v2 clients - just not using `DynamoDBEmbedded` but using it in server mode.

See https://github.com/aws/aws-sdk-java-v2/blob/93269d4c0416d0f72e086774265847d6af0d54ec/services-custom/dynamodb-enhanced/src/test/java/software/amazon/awssdk/extensions/dynamodb/mappingclient/functionaltests/LocalDynamoDb.java for more an example on using it in server mode.

**Comment by LME10** [comment]
@humanzz have you got it working connecting v2 clients with existing DynamoDBLocal?
I ran into several issues. One of most common issue I faced was  Class Not found exception for model "CancellationReason"
If you got working, could you share link for reference?

**Comment by chrylis** [comment]
@humanzz I was able to do that back when, but it's very slow compared to an in-memory instance.

**Comment by shapan1** [comment]
Did anyone find any resolution on this?
@humanzz @chrylis @zoewangg

**Comment by humanzz** [comment]
@shapan1 I ended up using it in server mode like above. It's working just fine in our unit tests.

**Comment by shapan1** [comment]
> @shapan1 I ended up using it in server mode like above. It's working just fine in our unit tests.

Could you please provide more info or reference to your code on this? because I cannot find `DynamoDBProxyServer` or `ServerRunner` as this is no longer available in aws sdk 2.

**Comment by zoewangg** [comment]
@humanzz Yeah, 1.16.0 is actually available now :) https://github.com/aws/aws-sdk-java-v2/pull/2452

**Comment by spanierm** [comment]
@zoewangg Thanks for the information about the `1.16.0` version. We successfully created an embedded DynamoDB local instance in a test. However, we get the following compiler warnings now

```

**Comment by spanierm** [comment]
@zoewangg Thanks for the information about the release of `1.16.0`. We were successfully able to start an embedded DynamoDB local instance in a JUnit test. However, once we now face some compiler warning:
```
w: Some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
w: /home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar: Library has Kotlin runtime bundled into it
```
Moreover, all integration tests fail due to conflicting Kotlin standard library files, see the following error details:
```
***************************
APPLICATION FAILED TO START
***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
    kotlin.reflect.jvm.internal.impl.descriptors.Visibilities.<clinit>(Visibilities.kt:56)
The following method did not exist:
    'java.util.Map kotlin.collections.MapsKt.createMapBuilder()'
The method's class, kotlin.collections.MapsKt, is available from the following locations:
    jar:file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar!/kotlin/collections/MapsKt.class
    jar:file:/home/markus/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.0/29dae2501ca094416d15af0e21470cb634780444/kotlin-stdlib-1.5.0.jar!/kotlin/collections/MapsKt.class
The class hierarchy was loaded from the following locations:
    kotlin.collections.MapsKt: file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar
    kotlin.collections.MapsKt___MapsKt: file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar
    kotlin.collections.MapsKt__MapsKt: file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar
    kotlin.collections.MapsKt__MapsJVMKt: file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar
    kotlin.collections.MapsKt__MapWithDefaultKt: file:/home/markus/.gradle/caches/modules-2/files-2.1/com.amazonaws/DynamoDBLocal/1.16.0/f705aa07cee4eb8199e70a393c5bd8173e7290ac/DynamoDBLocal-1.16.0.jar
Action:
Correct the classpath of your application so that it contains a single, compatible version of kotlin.collections.MapsKt
```
Can you help us with the issue or guide us towrads a collegue that can provide more information?

We are using Kotlin 1.5, AWS SDK 2, Spring Boot, Corretto 11 as JRE, Gradle. Moreover, it seems like the DynamoDB local jar contains indeed a copy of the Kotlin standard library classes/files. Is it possible to remove those from the bundle?

**Comment by zoewangg** [comment]
Hi @spanierm I've reached out to the team that maintains DynamoDB Local and will follow up if there's any update. Could you create a new issue to track this since this issue is to track the 2.x support?

**Comment by zoewangg** [comment]
Closing this issue. Feel free to open new issues if you have further questions.

**Comment by mmatsumoto** [comment]
> I think DynamoDB Local has added Java SDK v2 support in the latest version.
> 
> ```java
> DynamoDBEmbedded.create().dynamoDbClient();
> DynamoDBEmbedded.create().dynamoDbAsyncClient();
> ```

@zoewangg Your comment actually helped me. Thank you so much.

Here is a gist of how I'm using DynamoDBLocal with SDK 2 with Junit.

[LocalDynamoDBCreationRule](https://gist.github.com/mmatsumoto/6b872365d31f8fb32d6e7d0e307e027e)

I'm always open to suggestions.

**Comment by rajan-github** [comment]
Thanks @zoewangg, 1.16.0 is released and working fine.
