### ISSUE TITLE
Convenience Constructors for Union Types

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#983]
In the DynamoDB client, `AttributeValue` wraps a single DDB-typed value. In keeping with the global v2 SDK model, wrapping a value requires code like this:

```
AttributeValue.builder().s("value").build()
```

Since `AttributeValue` is by nature intended to wrap exactly a single value, it would be much cleaner for client code to provide static factories for the various data types:

```
AttributeValue.s("value")
```

**Comment by jeffalder** [comment]
How should we identify union types? The service json isn't clear (to me, at least) as to what are and are not union types. Is this a shape modifier, or something else in customization.config?

**Comment by millems** [comment]
We're working on a union-type trait that can be attached to union types, like AttributeValue. With that we would like to add static constructors and visitors for branching over the different options.

**Comment by millems** [comment]
With our release tomorrow, this and other union types have a from* constructor (e.g. `AttributeValue.fromS("foo")`) that is equivalent to calling the builder and then build. They also contain a `type()` method for determining which field is populated in constant time.
