### ISSUE TITLE
Difference between FooRequest and FooItemRequest classes

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#984]
This is likely a documentation issue.

The v2 API includes a number of class pairs such as `PutRequest` and `PutItemRequest`. The difference between these classes is very unclear, and the Javadoc does not provide a useful explanation. I think the `Item` classes may be for use with one-shot API calls while the others are for batch operations. Unfortunately, [the example code](https://github.com/awsdocs/aws-doc-sdk-examples/tree/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb) shows how to use `PutItem` but not `BatchWriteItem`, and the default expectation (that `BatchWriteItem` would simply take multiple instances of `PutItem` and `DeleteItem`) doesn't seem to hold.

The generated Java code appears to be doing a very literal interpretation of an API document; it seems like it would be cleaner for clients if, for example, `BatchWriteItemRequest` could take just a `Collection<PutItem>` and not have to have separate code paths for serializing business objects depending on whether they're intended to be written differently.

**Comment by millems** [comment]
This documentation and modeling is indeed generated from a model file that is controlled by the service team. 

Unfortunately it wasn't possible to accept the same `PutItemRequest` for batch operations and non-batch operations. The non-batch operations were created a long time ago, and include operation-level configuration, like `CredentialProviders`. They also include features not available in the batch equivalents at this time, like `returnConsumedCapacity`. These fields wouldn't make sense in the context of a batch line-item, so a separate structure was created.

I agree the documentation that attempts to distinguish PutRequest and PutItemRequest isn't clear. I'll pass along this feedback to the service team that owns the docs.

**Comment by millems** [comment]
Forwarded this feedback to the service team. They've been linked this issue, if there was any other dynamo DB documentation feedback you would like to share.

**Comment by millems** [comment]
Closing this because it is still in the service's hands to fix. There's nothing we can do from the SDK end.
