### ISSUE TITLE
Javadoc for Put[Item]Request.Builder.item(Map)

### ISSUE THREAD

**Issue by chrylis** [aws/aws-sdk-java-v2#985]
The `item(Map)` methods on [these two classes](https://github.com/aws/aws-sdk-java-v2/issues/984) have Javadocs that specifically say that they're for setting "the primary key of an item to be processed by `PutItem`". However, [the `PutItem` example](https://github.com/awsdocs/aws-doc-sdk-examples/blob/master/javav2/example_code/dynamodb/src/main/java/com/example/dynamodb/PutItem.java#L89-L91) seems to pass all of the item's attributes here, and there's no other place to set extra attributes. It seems that the Javadoc should be updated to reflect this.

**Comment by millems** [comment]
Closing this because it is still in the service's hands to fix. There's nothing we can do from the SDK end. You can reach out to the various service teams to reinforce your desire for this to be fixed via the AWS forums.
