### ISSUE TITLE
Support Apache BeanUtils for accessing modeled fields

### ISSUE THREAD

**Issue by ProTip** [aws/aws-sdk-java-v2#987]
I'm attempting to access ec2 instance model properties dynamically based on user supplied 'selector' strings. This was pretty straight forward in the existing v1 sdk code which I didn't write but am attempting to refactor.

```java
Instance inst
PropertyUtils.getNestedProperty(inst.toBuilder(), selector);
```

## Expected Behavior
No error and value returned.

## Current Behavior
```
com.dtolabs.rundeck.plugin.resources.ec2.InstanceToNodeMapper$GeneratorException: java.lang.NoSuchMethodException: Property 'instanceId' has no getter method in class 'class software.amazon.awssdk.services.ec2.model.Instance$BuilderImpl'
```

## Possible Solution
Make the nested internal class public? The getters appear to follow naming convention, so this is a potential solution from my googling...

## An aside
I'm finding working with the models in v2 EXTREMELY cumbersome. I'm honestly a bit shocked at the move to builders for both constructing models, and needing them for serialization or programmatic access. I'm having a hard time understanding why getters aren't accessible to common tools, and why the properties are all private.. In 2018 this feels like a step backwards. Sure there are a lot of `Final` things(!!!) but I thought we were moving more toward immutable data classes/interfaces that got operated on..

For my part I'm trying to update code based on v1 to v2 that accesses properties programatically by string using apache utils. It I'm a bit stumped now wondering if I need to write my own reflection libs.. I'm honestly new-ish to the Java ecosystem, but this library feels like a usability regression.

**Comment by millems** [comment]
Apache bean utils seems to be very strict about accessibility. If the class isn't public, it needs a public interface or superclass to use when invoking the method, even if the method itself is public.

Marking this as a feature request to find a workaround for the more strict libraries.

**Comment by millems** [comment]
Since this issue was created, 2.x introduced the `getValueForField` method. 

E.g.
```
PutObjectRequest request = PutObjectRequest.builder().bucket("foo").build();
String bucket = request.getValueForField("Bucket", String.class);
assertEquals("foo", bucket);
```

Is this sufficient for your use-case? This feature doesn't seem to have a lot of demand, so I suspect that it might not get prioritized. It might be worth looking into other options.
