### ISSUE TITLE
UpdateStackRequest and CreateStackRequest do not have a parameters method that takes a collection of consumers

### ISSUE THREAD

**Issue by bamapookie** [aws/aws-sdk-java-v2#992]
When creating an `UpdateStackRequest` (in `software.amazon.awssdk.services.cloudformation.model`), it is possible to pass in a `Collection` or an array of `Parameter`s, but only an array of `Consumer<Parameter.Builder>`s.  There is no overloaded method that accepts a `Collection` of `Consumer`s.  This is problematic because you cannot create a generic array.

## Expected Behavior
    Collection<Consumer<Parameter.Builder>> parameters = new ArrayList<>();
    CreateStackRequest request = CreateStackRequest.create(parameters).parameters().build();

## Current Behavior
    Consumer<Parameter.Builder>[] parameters = new Consumer<Parameter.Builder>[1]{
        builder -> builder.parameterKey(key).parameterValue(value).usePreviousValue(false)
    };
    // gives compilation error

## Possible Solution
Add

    Builder parameters(Collection<Consumer<Parameter.Builder>> parameters);

to CreateStackRequest and UpdateStackRequest.

## Steps to Reproduce (for bugs)
n/a

## Context
If you are using properly typed collections, you can't use the consumer builder convenience methods.

## Your Environment
* AWS Java SDK version used: 2.2.0
* JDK version used: 1.8.0_181
* Operating System and version: OSX 10.14.2

**Comment by millems** [comment]
Unfortunately `Builder parameters(Collection<Consumer<Parameter.Builder>> parameters)` would have the same erasure as `Builder parameters(Collection<Parameter> parameters)`, so we'd have to introduce a new method name. Using the standard builder pattern here might just be the lesser of two evils...

**Comment by millems** [comment]
Closing due to no response.
